import { TAXONOMIA } from "./taxonomia.mjs";

export const penal03Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "pen-03-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considera-se funcionário público, para os efeitos penais, quem, embora transitoriamente ou sem remuneração, exerce cargo, emprego ou função pública.",
    explicacao: "GABARITO: CERTO. Art. 327, caput, do Código Penal: 'Considera-se funcionário público, para os efeitos penais, quem, embora transitoriamente ou sem remuneração, exerce cargo, emprego ou função pública.'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No peculato culposo (art. 312, § 2º, do CP), a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade; se lhe é posterior, reduz de metade a pena imposta.",
    explicacao: "GABARITO: CERTO. Art. 312, § 3º, do Código Penal: No caso do § 2º (peculato culposo), a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade; se lhe é posterior, reduz de metade a pena imposta.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O crime de corrupção passiva consuma-se com a efetiva percepção ou recebimento da vantagem indevida, sendo a simples solicitação considerada mero ato preparatório impunível.",
    explicacao: "GABARITO: ERRADO. Art. 317 do Código Penal: O crime de corrupção passiva é formal (ou de consumação antecipada). Consuma-se no momento em que o funcionário solicita, recebe ou aceita a promessa de vantagem indevida, sendo o recebimento mero exaurimento do delito.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "pen-03-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O crime de concussão (art. 316 do CP) diferencia-se da corrupção passiva (art. 317 do CP) porque, na concussão, o funcionário público EXIGE a vantagem indevida, enquanto na corrupção passiva ele SOLICITA, RECEBE ou ACEITA PROMESSA de tal vantagem.",
    explicacao: "GABARITO: CERTO. O verbo núcleo da concussão é exigir (imposição com temor de represália funcional), ao passo que na corrupção passiva os núcleos são solicitar, receber ou aceitar promessa de vantagem indevida.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal, configura o crime de prevaricação.",
    explicacao: "GABARITO: CERTO. Art. 319 do Código Penal: Retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal: Prevaricação.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A morte do agente, a anistia, a graça, o indulto e a prescrição são causas extintivas da punibilidade expressamente previstas no Código Penal.",
    explicacao: "GABARITO: CERTO. Art. 107, I e II, do Código Penal: Extingue-se a punibilidade: I - pela morte do agente; II - pela anistia, graça ou indulto; IV - pela prescrição, decadência ou perempção.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A conduta do particular que desacata funcionário público no exercício da função ou em razão dela continua tipificada no Código Penal brasileiro como crime de desacato (art. 331), tendo o Superior Tribunal de Justiça (HC 379.269/MS - 3ª Seção) e o Supremo Tribunal Federal (ADPF 496) confirmado sua plena vigência e compatibilidade com a Convenção Americana sobre Direitos Humanos.",
    explicacao: "GABARITO: CERTO. O STJ (Terceira Seção) e o STF (ADPF 496) pacificaram que a tipificação do desacato (art. 331 do CP) é constitucional e compatível com a CADH/Pacto de San José, não violando a liberdade de expressão.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "pen-03-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O funcionário público que se apropria de dinheiro ou qualquer utilidade que, no exercício do cargo, recebeu por erro de outrem, comete o crime de excesso de exação.",
    explicacao: "GABARITO: ERRADO. Art. 313 do Código Penal: Apropriar-se de dinheiro ou qualquer utilidade que, no exercício do cargo, recebeu por erro de outrem configura o crime de Peculato mediante erro de outrem (ou peculato-estelionato). O excesso de exação (art. 316, § 1º) consiste em exigir tributo ou contribuição social indevida ou de forma vexatória.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "pen-03-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O funcionário público que deixa, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo ou, quando lhe falte competência, não leva o fato ao conhecimento da autoridade competente, pratica o crime de:",
    explicacao: "GABARITO: B. Art. 320 do Código Penal: Deixar o funcionário, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo ou, quando lhe falte competência, não levar o fato ao conhecimento da autoridade competente: Condescendência criminosa.",
    alternativas: [
      { texto: "Prevaricação.", correta: false },
      { texto: "Condescendência criminosa.", correta: true },
      { texto: "Advocacia administrativa.", correta: false },
      { texto: "Corrupção passiva privilegiada.", correta: false },
      { texto: "Usurpação de função pública.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A conduta de ingressar, promover, intermediar, auxiliar ou facilitar a entrada de aparelho telefônico móvel de comunicação celular ou similar em estabelecimento prisional, sem autorização legal (art. 349-A do CP), é punida com:",
    explicacao: "GABARITO: A. Art. 349-A do Código Penal: Ingressar, promover, intermediar, auxiliar ou facilitar a entrada de aparelho telefônico móvel de comunicação, de rádio ou similar, sem autorização legal, em estabelecimento prisional: Pena - detenção, de 3 meses a 1 ano.",
    alternativas: [
      { texto: "detenção, de 3 meses a 1 ano.", correta: true },
      { texto: "reclusão, de 10 a 20 anos, inafiançável.", correta: false },
      { texto: "apenas sanção administrativa disciplinar sem tipificação penal.", correta: false },
      { texto: "prestação de serviços comunitários de 15 dias.", correta: false },
      { texto: "reclusão de 2 a 5 anos e confisco definitivo dos bens.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de resistência (art. 329 do CP) caracteriza-se por:",
    explicacao: "GABARITO: C. Art. 329 do Código Penal: Opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio: Resistência. Se a oposição não envolver violência ou ameaça (ex.: mera fuga), pode configurar desobediência (art. 330) ou ser conduta atípica, mas não resistência.",
    alternativas: [
      { texto: "desobedecer verbalmente à ordem legal de funcionário sem qualquer contato físico.", correta: false },
      { texto: "fugir a pé sem ameaçar ou agredir os policiais executores da ordem.", correta: false },
      { texto: "opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio.", correta: true },
      { texto: "solicitar vantagem indevida em troca de informação privilegiada.", correta: false },
      { texto: "ofender a honra do policial em repartição pública.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 115 do Código Penal, são reduzidos de metade os prazos de prescrição da pretensão punitiva e executória quando o criminoso era, ao tempo do crime, menor de 21 (vinte e um) anos, ou, na data da sentença:",
    explicacao: "GABARITO: D. Art. 115 do Código Penal: São reduzidos de metade os prazos de prescrição quando o criminoso era, ao tempo do crime, menor de vinte e um anos, ou, na data da sentença, maior de setenta anos.",
    alternativas: [
      { texto: "maior de 60 anos.", correta: false },
      { texto: "maior de 65 anos.", correta: false },
      { texto: "portador de enfermidade mental comprovada.", correta: false },
      { texto: "maior de 70 anos.", correta: true },
      { texto: "maior de 80 anos.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário, configura o crime de:",
    explicacao: "GABARITO: E. Art. 321 do Código Penal: Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário: Advocacia administrativa.",
    alternativas: [
      { texto: "Corrupção passiva.", correta: false },
      { texto: "Tráfico de influência.", correta: false },
      { texto: "Exploração de prestígio.", correta: false },
      { texto: "Prevaricação funcional.", correta: false },
      { texto: "Advocacia administrativa.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "pen-03-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Oferecer ou prometer vantagem indevida a funcionário público, para determiná-lo a praticar, omitir ou retardar ato de ofício, configura o crime de:",
    explicacao: "GABARITO: A. Art. 333 do Código Penal: Oferecer ou prometer vantagem indevida a funcionário público, para determiná-lo a praticar, omitir ou retardar ato de ofício: Corrupção ativa.",
    alternativas: [
      { texto: "Corrupção ativa.", correta: true },
      { texto: "Corrupção passiva.", correta: false },
      { texto: "Tráfico de influência.", correta: false },
      { texto: "Favorecimento real.", correta: false },
      { texto: "Concussão.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O crime de usurpação de função pública (art. 328 do CP) consiste em:",
    explicacao: "GABARITO: B. Art. 328 do Código Penal: Usurpar o exercício de função pública. Consiste em apossar-se indevidamente de cargo ou função estatal que não lhe pertence legalmente.",
    alternativas: [
      { texto: "recusar prestar socorro a quem necessita.", correta: false },
      { texto: "usurpar o exercício de função pública exercendo atos funcionais sem investidura legal.", correta: true },
      { texto: "solicitar empréstimo a particular em nome de terceiros.", correta: false },
      { texto: "extraviar documento particular de interesse pessoal.", correta: false },
      { texto: "fazer justiça com as próprias mãos sem ameaça.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O funcionário público que revela fato de que tem ciência em razão do cargo e que deva permanecer em segredo, ou facilita-lhe a revelação, comete o crime de:",
    explicacao: "GABARITO: C. Art. 325 do Código Penal: Revelar fato de que tem ciência em razão do cargo e que deva permanecer em segredo, ou facilitar-lhe a revelação: Violação de sigilo funcional.",
    alternativas: [
      { texto: "falso testemunho.", correta: false },
      { texto: "fraude processual qualificada.", correta: false },
      { texto: "violação de sigilo funcional.", correta: true },
      { texto: "desobediência hierárquica.", correta: false },
      { texto: "comunicação falsa de crime.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "pen-03-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 117 do Código Penal, o curso da prescrição da pretensão punitiva interrompe-se pelo(a):",
    explicacao: "GABARITO: D. Art. 117, I, do CP: O curso da prescrição interrompe-se: I - pelo recebimento da denúncia ou da queixa; II - pela pronúncia; III - pela decisão confirmatória da pronúncia; IV - pela publicação da sentença ou acórdão condenatórios recorríveis; V - pelo início ou continuação do cumprimento da pena; VI - pela reincidência.",
    alternativas: [
      { texto: "instauração de inquérito policial pela autoridade competente.", correta: false },
      { texto: "expedição do relatório final do delegado de polícia.", correta: false },
      { texto: "simples protocolo da petição inicial acusatória.", correta: false },
      { texto: "recebimento da denúncia ou da queixa pelo juiz competente.", correta: true },
      { texto: "concessão de liberdade provisória com fiança.", correta: false },
    ],
  },
  {
    idSlug: "pen-03-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de favorecimento pessoal (art. 348 do CP) consiste em auxiliar a subtrair-se à ação de autoridade pública autor de crime a que é cominada pena de reclusão. Se quem presta o auxílio é ascendente, descendente, cônjuge ou irmão do criminoso:",
    explicacao: "GABARITO: A. Art. 348, § 2º, do Código Penal: Se quem presta o auxílio é ascendente, descendente, cônjuge ou irmão do criminoso, fica isento de pena (escusa absolutória por laço de parentesco estreito).",
    alternativas: [
      { texto: "fica isento de pena.", correta: true },
      { texto: "tem a pena aumentada em dobro.", correta: false },
      { texto: "responde em coautoria pelo crime principal praticado pelo familiar.", correta: false },
      { texto: "perde automaticamente o direito de herança.", correta: false },
      { texto: "sujeita-se a pena de multa compulsória em favor do fundo penitenciário.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "pen-03-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Desobedecer a ordem legal de funcionário público configura o crime de:",
    explicacao: "GABARITO: E. Art. 330 do Código Penal: Desobedecer a ordem legal de funcionário público: Desobediência.",
    alternativas: [
      { texto: "Peculato culposo.", correta: false },
      { texto: "Falso testemunho.", correta: false },
      { texto: "Tráfico de influência.", correta: false },
      { texto: "Resistência qualificada.", correta: false },
      { texto: "Desobediência.", correta: true },
    ],
  },
  {
    idSlug: "pen-03-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_funcionario_publico,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Fazer justiça pelas próprias mãos, para satisfazer pretensão, embora legítima, salvo quando a lei permite, constitui o crime de:",
    explicacao: "GABARITO: B. Art. 345 do Código Penal: Fazer justiça pelas próprias mãos, para satisfazer pretensão, embora legítima, salvo quando a lei permite: Exercício arbitrário das próprias razões.",
    alternativas: [
      { texto: "Coação no curso do processo.", correta: false },
      { texto: "Exercício arbitrário das próprias razões.", correta: true },
      { texto: "Denunciação caluniosa.", correta: false },
      { texto: "Fraude processual.", correta: false },
      { texto: "Desacato.", correta: false },
    ],
  },
];
