import { TAXONOMIA } from "./taxonomia.mjs";

export const port01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "port-01-001",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considere o trecho: 'A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio.' Infere-se do texto que a responsabilidade pela segurança pública é compartilhada entre os órgãos estatais e a coletividade.",
    explicacao: "GABARITO: CERTO. A expressão 'dever do Estado, direito e responsabilidade de todos' deixa explícito que, embora o dever primordial de execução e garantia pertença ao Estado, a responsabilidade é de toda a sociedade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-002",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O boletim de ocorrência policial e o laudo pericial cadavérico são gêneros textuais caracterizados predominantemente pela tipologia injuntiva, com linguagem conotativa e subjetiva.",
    explicacao: "GABARITO: ERRADO. Documentos oficiais e técnicos policiais (boletins e laudos) são predominantemente descritivos/expositivos, pautados pela objetividade, denotação e clareza técnico-científica, e não injuntivos/conotativos.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "port-01-003",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No período: 'Embora as condições climáticas fossem adversas na rodovia, a equipe tática manteve o patrulhamento preventivo.', o conector sublinhado 'Embora' introduz uma oração subordinada com sentido concessivo, podendo ser substituído por 'Conquanto' sem prejuízo do sentido original e da correção gramatical.",
    explicacao: "GABARITO: CERTO. 'Embora' e 'conquanto' são conjunções subordinativas concessivas sinônimas e ambas exigem verbo no modo subjuntivo ('fossem').",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-004",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Considere a frase: 'A ressocialização do custodiado depende não apenas de medidas punitivas proporcionais, mas também de oportunidades efetivas de trabalho e educação profissional no estabelecimento penal.' A estrutura correlativa 'não apenas... mas também' expressa uma relação semântica de oposição/contradição entre punição e trabalho.",
    explicacao: "GABARITO: ERRADO. A locução correlativa 'não apenas... mas também' (ou 'não só... como também') expressa relação de ADIÇÃO e soma de argumentos, e não de oposição ou contradição.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "port-01-005",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "No trecho: 'O delegado concluiu as oitivas das testemunhas. Estas confirmaram o álibi do suspeito; aquele, contudo, solicitou novas diligências periciais.', os pronomes 'Estas' e 'aquele' exercem coesão referencial anafórica, retomando, respectivamente, 'testemunhas' e 'delegado'.",
    explicacao: "GABARITO: CERTO. Coesão referencial por pronomes demonstrativos: 'Estas' retoma o elemento mais próximo citado ('testemunhas') e 'aquele' retoma o termo mais distante mencionado ('delegado').",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-006",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O editorial de jornal que analisa e critica as diretrizes orçamentárias de segurança pública de um estado classifica-se predominantemente como texto dissertativo-argumentativo.",
    explicacao: "GABARITO: CERTO. O editorial expressa a opinião/posicionamento institucional de um veículo de imprensa, fundamentando teses com argumentos, constituindo típico texto dissertativo-argumentativo.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-007",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No trecho: 'A ampliação das rondas comunitárias reduziu a criminalidade patrimonial no centro histórico, haja vista o aumento da presença ostensiva dos agentes.', a locução 'haja vista' possui valor causal, indicando o motivo pelo qual a criminalidade decresceu.",
    explicacao: "GABARITO: CERTO. 'Haja vista', 'visto que', 'já que' e 'porque' possuem valor semântico explicativo/causal no contexto apresentado.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-008",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Em: 'O socorrista acionou a sirene para que o trânsito abrisse passagem na avenida.', a locução conjuntiva 'para que' estabelece uma relação de finalidade.",
    explicacao: "GABARITO: CERTO. 'Para que', 'a fim de que' e 'com o objetivo de' são locuções subordinativas finais que indicam o propósito/objetivo da ação.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-009",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Considere: 'A utilização de inteligência artificial na análise de evidências forenses otimiza o tempo da perícia; todavia, a validação humana crítica permanece indispensável.' O emprego do conectivo 'todavia' introduz uma ressalva que relativiza o alcance da automação tecnológica na atividade pericial.",
    explicacao: "GABARITO: CERTO. 'Todavia' é conjunção coordenativa adversativa que introduz contraposição e ressalva em relação à premissa anterior.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "port-01-010",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O manual de operações táticas especiais da polícia, contendo passos sequenciais e ordens diretas para abordagem veicular de alto risco, enquadra-se tipologicamente no modo textual injuntivo ou prescritivo.",
    explicacao: "GABARITO: CERTO. Textos instrucionais, manuais, receitas e prescrições que utilizam verbos imperativos ou no infinitivo diretivo configuram tipologia injuntiva/prescritiva.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 11-16. FGV (Múltipla Escolha)
  {
    idSlug: "port-01-011",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Analise o fragmento: 'Não se combate a criminalidade organizada apenas com a apreensão de carregamentos nas estradas; é imperativo estrangular o fluxo financeiro ilícito e descapitalizar as lideranças faccionadas.' A ideia central defendida pelo autor é a de que:",
    explicacao: "GABARITO: A. O texto argumenta que ações ostensivas de apreensão física são insuficientes isoladamente, sendo imprescindível focar na descapitalização financeira e patrimonial do crime organizado.",
    alternativas: [
      { texto: "a eficácia no combate às facções exige priorizar a asfixia financeira e patrimonial sobre as apreensões isoladas de mercadorias.", correta: true },
      { texto: "o policiamento rodoviário ostensivo deve ser extinto por falta de resultados concretos.", correta: false },
      { texto: "as lideranças criminosas são indiferentes à perda de recursos patrimoniais.", correta: false },
      { texto: "o crime organizado não utiliza o sistema financeiro nacional para lavagem de dinheiro.", correta: false },
      { texto: "as apreensões em rodovias resolvem de forma definitiva a violência urbana.", correta: false },
    ],
  },
  {
    idSlug: "port-01-012",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a frase em que o conector sublinhado estabelece relação de CONFORMIDADE:",
    explicacao: "GABARITO: B. 'Conforme', 'segundo', 'consoante' e 'de acordo com' introduzem orações subordinadas adverbiais conformativas.",
    alternativas: [
      { texto: "A operação foi deflagrada tão logo amanheceu o dia.", correta: false },
      { texto: "Os policiais agiram conforme as diretrizes do plano de segurança operacional.", correta: true },
      { texto: "Caso persista o bloqueio, a tropa de choque será acionada.", correta: false },
      { texto: "O agente permaneceu em vigília a fim de capturar os fugitivos.", correta: false },
      { texto: "Quanto mais se investe em inteligência, menos ocorrem confrontos letais.", correta: false },
    ],
  },
  {
    idSlug: "port-01-013",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Leia o excerto: 'Era uma noite chuvosa e sem iluminação pública na praça central. Dois indivíduos trajando casacos pretos aproximaram-se do monumento às 22h15.' O fragmento apresenta traços característicos predominantes da tipologia:",
    explicacao: "GABARITO: C. O fragmento descreve o ambiente (noite chuvosa, sem iluminação) e narra uma sequência temporal cronológica com personagens (aproximaram-se às 22h15), constituindo tipologia narrativa e descritiva.",
    alternativas: [
      { texto: "Dissertativa reflexiva pura.", correta: false },
      { texto: "Injuntiva prescritiva.", correta: false },
      { texto: "Narrativo-descritiva.", correta: true },
      { texto: "Argumentativa polêmica.", correta: false },
      { texto: "Expositiva didática.", correta: false },
    ],
  },
  {
    idSlug: "port-01-014",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Considere: 'A superlotação carcerária não é causa primária, mas sintoma visível de disfunções profundas do sistema de justiça criminal.' Do ponto de vista semântico, infere-se que:",
    explicacao: "GABARITO: D. O autor estabelece que a superlotação é uma consequência perceptível (sintoma) originada por falhas estruturais e institucionais mais amplas (causas) do sistema de justiça penal.",
    alternativas: [
      { texto: "a superlotação dos presídios é a única responsável pelo aumento dos índices de criminalidade.", correta: false },
      { texto: "não existem problemas estruturais na administração penitenciária.", correta: false },
      { texto: "o encarceramento decorre unicamente de escolhas individuais dos apenados.", correta: false },
      { texto: "o excedente populacional nas prisões reflete e decorre de problemas estruturais mais amplos no sistema de justiça criminal.", correta: true },
      { texto: "o fechamento das penitenciárias solucionaria de imediato todas as disfunções criminais.", correta: false },
    ],
  },
  {
    idSlug: "port-01-015",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Assinale a opção em que a substituição do conector mantém o mesmo sentido e correção gramatical no trecho: 'O sigilo telefônico foi quebrado, VISTO QUE havia fortes indícios de associação criminosa.'",
    explicacao: "GABARITO: E. 'Visto que', 'já que', 'porquanto' e 'dado que' são locuções conjuntivas causais equivalentes e intercambiáveis no contexto.",
    alternativas: [
      { texto: "contanto que", correta: false },
      { texto: "ao passo que", correta: false },
      { texto: "não obstante", correta: false },
      { texto: "a menos que", correta: false },
      { texto: "porquanto", correta: true },
    ],
  },
  {
    idSlug: "port-01-016",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Em: 'O tempo é fator determinante no resgate de vítimas de soterramento; cada minuto de retardo diminui drasticamente as chances de sobrevida.', a relação entre as duas orações é de:",
    explicacao: "GABARITO: A. A primeira oração faz a afirmação ('O tempo é fator determinante') e a segunda, separada por ponto e vírgula, comprova e explica a razão dessa premissa.",
    alternativas: [
      { texto: "afirmação geral seguida de justificativa explicativa.", correta: true },
      { texto: "condição hipotética seguida de consequência imprevisível.", correta: false },
      { texto: "concessão circunstancial seguida de oposição factual.", correta: false },
      { texto: "comparação proporcional inversa.", correta: false },
      { texto: "ordem imperativa com ressalva temporal.", correta: false },
    ],
  },
  // 17-20. VUNESP (Múltipla Escolha)
  {
    idSlug: "port-01-017",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "No trecho: 'A utilização de câmeras corporais operacionais pelos policiais resultou em queda expressiva nos índices de violência letal em intervenções urbanas.', o termo 'expressiva' tem sentido de:",
    explicacao: "GABARITO: B. 'Expressiva' no contexto significa significativa, notável, relevante, de grande magnitude.",
    alternativas: [
      { texto: "passageira e discreta.", correta: false },
      { texto: "significativa e relevante.", correta: true },
      { texto: "duvidosa e inconclusiva.", correta: false },
      { texto: "negativa e prejudicial.", correta: false },
      { texto: "imperceptível e irrelevante.", correta: false },
    ],
  },
  {
    idSlug: "port-01-018",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a alternativa que apresenta a correta correlação de sentido para o termo sublinhado: 'A perícia foi inconclusiva, POR CONSEGUINTE o juiz determinou nova reconstituição dos fatos.'",
    explicacao: "GABARITO: C. 'Por conseguinte', 'logo', 'portanto', 'por isso' e 'assim' são conjunções coordenativas conclusivas.",
    alternativas: [
      { texto: "Causa.", correta: false },
      { texto: "Finalidade.", correta: false },
      { texto: "Conclusão.", correta: true },
      { texto: "Condição.", correta: false },
      { texto: "Proporcionalidade.", correta: false },
    ],
  },
  {
    idSlug: "port-01-019",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Um cartaz afixado na entrada de um parque municipal com o seguinte texto: 'É proibido fumar e transitar com animais sem coleira nas dependências do parque sob pena de multa' tem caráter:",
    explicacao: "GABARITO: D. Cartazes normativos, placas de sinalização e avisos que impõem condutas e proibições sob cominação de sanção possuem caráter injuntivo/prescritivo.",
    alternativas: [
      { texto: "Poético lírico.", correta: false },
      { texto: "Narrativo ficcional.", correta: false },
      { texto: "Dramático encenado.", correta: false },
      { texto: "Prescritivo ou normativo.", correta: true },
      { texto: "Dissertativo acadêmico.", correta: false },
    ],
  },
  {
    idSlug: "port-01-020",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Considere a oração: 'Embora houvesse rigor na revista, os visitantes tentavam ludibriar a fiscalização penitenciária.' O verbo 'ludibriar' é sinônimo de:",
    explicacao: "GABARITO: E. 'Ludibriar' significa enganar, trapacear, iludir, burlar.",
    alternativas: [
      { texto: "apoiar.", correta: false },
      { texto: "agradecer.", correta: false },
      { texto: "obedecer.", correta: false },
      { texto: "fotografar.", correta: false },
      { texto: "enganar ou burlar.", correta: true },
    ],
  },
  // 21-23. AOCP (Múltipla Escolha)
  {
    idSlug: "port-01-021",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Em um relatório policial, a frase 'O depoimento da vítima foi corroborado pelas imagens das câmeras do circuito de segurança' significa que o depoimento foi:",
    explicacao: "GABARITO: A. 'Corroborar' significa confirmar, ratificar, dar sustentação ou validar uma alegação com provas.",
    alternativas: [
      { texto: "confirmado e validado pelas imagens.", correta: true },
      { texto: "desmentido e anulado pelos vídeos.", correta: false },
      { texto: "ignorado pela equipe de peritos.", correta: false },
      { texto: "reescrito com base nas gravações.", correta: false },
      { texto: "encaminhado para censura judicial.", correta: false },
    ],
  },
  {
    idSlug: "port-01-022",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em: 'O alerta foi emitido, TODAVIA a equipe de reforço não chegou a tempo.', a palavra 'TODAVIA' pode ser substituída sem alteração de sentido por:",
    explicacao: "GABARITO: B. 'Todavia', 'porém', 'contudo', 'entretanto', 'no entanto' são conjunções adversativas sinônimas.",
    alternativas: [
      { texto: "portanto.", correta: false },
      { texto: "contudo.", correta: true },
      { texto: "porquanto.", correta: false },
      { texto: "conforme.", correta: false },
      { texto: "caso.", correta: false },
    ],
  },
  {
    idSlug: "port-01-023",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.tipologia_generos_textuais,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A descrição minuciosa das características de um extintor de incêndio (capacidade, tipo de carga, pressão nominal e validade) em um relatório técnico constitui exemplo de texto eminentemente:",
    explicacao: "GABARITO: C. A enumeração de propriedades físicas, técnicas e visuais de um objeto sem enredo narrativo ou defesa de tese opinativa caracteriza texto descritivo/técnico.",
    alternativas: [
      { texto: "narrativo ficcional.", correta: false },
      { texto: "argumentativo opinativo.", correta: false },
      { texto: "descritivo técnico.", correta: true },
      { texto: "lírico poético.", correta: false },
      { texto: "dramático teatral.", correta: false },
    ],
  },
  // 24-25. IBFC (Múltipla Escolha)
  {
    idSlug: "port-01-024",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.interpretacao_texto,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "No enunciado 'A ação rápida da guarnição evitou que o princípio de incêndio se alastrasse pelo prédio público', o termo 'alastrasse' expressa a ideia de:",
    explicacao: "GABARITO: D. 'Alastrar-se' significa propagar-se, espalhar-se, disseminar-se por uma área maior.",
    alternativas: [
      { texto: "extinguir-se completamente.", correta: false },
      { texto: "reduzir-se ao ponto de origem.", correta: false },
      { texto: "concentrar-se no térreo.", correta: false },
      { texto: "propagar-se ou espalhar-se.", correta: true },
      { texto: "reiniciar em outro bairro.", correta: false },
    ],
  },
  {
    idSlug: "port-01-025",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.coesao_coerencia,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Assinale a alternativa que indica corretamente o sentido estabelecido pela conjunção sublinhada em: 'O sentenciado terá direito à progressão de regime, DESDE QUE cumpra os requisitos objetivo e subjetivo.'",
    explicacao: "GABARITO: E. 'Desde que', 'caso', 'se', 'contanto que' seguidos de verbo no subjuntivo introduzem orações com valor de CONDIÇÃO.",
    alternativas: [
      { texto: "Concessão.", correta: false },
      { texto: "Causa.", correta: false },
      { texto: "Consequência.", correta: false },
      { texto: "Finalidade.", correta: false },
      { texto: "Condição.", correta: true },
    ],
  },
];
