import { TAXONOMIA } from "./taxonomia.mjs";

export const transito01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "tran-01-001",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O trânsito de qualquer natureza nas vias terrestres do território nacional, abertas à circulação, rege-se pelo Código de Trânsito Brasileiro (CTB), considerando-se trânsito a utilização das vias por pessoas, veículos e animais, isolados ou em grupos, conduzidos ou não, para fins de circulação, parada, estacionamento e operação de carga ou descarga.",
    explicacao: "GABARITO: CERTO. Art. 1º, caput e § 1º, do CTB: O trânsito de qualquer natureza nas vias terrestres do território nacional, abertas à circulação, rege-se por este Código. Considera-se trânsito a utilização das vias por pessoas, veículos e animais, isolados ou em grupos, conduzidos ou não, para fins de circulação, parada, estacionamento e operação de carga ou descarga.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-002",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Os veículos precedidos de batedores terão prioridade de passagem, respeitadas as demais normas de circulação, ao passo que os destinados a socorro de incêndio e salvamento, os de polícia, os de fiscalização e operação de trânsito e as ambulâncias gozam de livre circulação, estacionamento e parada apenas quando estiverem em serviço de urgência, de policiamento ostensivo ou de preservação da ordem pública e devidamente identificados por dispositivos regulamentares de alarme sonoro e iluminação vermelha intermitente.",
    explicacao: "GABARITO: CERTO. Art. 29, VI e VII, do CTB: Os veículos precedidos de batedores terão prioridade de passagem; os de socorro de incêndio, polícia, fiscalização de trânsito e ambulâncias gozam de livre circulação, estacionamento e parada quando em serviço de urgência e devidamente identificados por alarme sonoro e iluminação vermelha intermitente.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-003",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Nas vias urbanas abertas à circulação, onde não existir sinalização regulamentadora de velocidade, a velocidade máxima permitida nas vias de trânsito rápido será de 80 km/h.",
    explicacao: "GABARITO: CERTO. Art. 61, § 1º, I, 'a', do CTB: Onde não existir sinalização regulamentadora, a velocidade máxima será de 80 km/h nas vias de trânsito rápido.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-004",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Quando veículos, transitando por fluxos que se cruzem, se aproximarem de local não sinalizado, terá preferência de passagem, no caso de apenas um fluxo ser proveniente de rodovia, aquele que estiver circulando por ela; no caso de rotatória, aquele que não estiver circulando por ela; e, nos demais casos, o que vier pela esquerda do condutor.",
    explicacao: "GABARITO: ERRADO. Art. 29, III, do CTB: No caso de rotatória, a preferência é daquele que ESTIVER circulando por ela (e não quem não estiver); nos demais casos, a preferência é do veículo que vier pela DIREITA do condutor (e não pela esquerda).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "tran-01-005",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O condutor deverá manter acesos os faróis do veículo, por meio da utilização da luz baixa, durante a noite e durante o dia em túneis e sob chuva, neblina ou cerração.",
    explicacao: "GABARITO: CERTO. Art. 40, I, do CTB (com alterações da Lei nº 14.071/2020): O condutor manterá acesos os faróis do veículo, por meio da utilização da luz baixa, à noite e de dia em túneis e sob chuva, neblina ou cerração.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-006",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Nas rodovias de pista dupla situadas fora do perímetro urbano, em trechos sem sinalização regulamentadora, os veículos leves e os veículos pesados submetem-se ao mesmo limite máximo de velocidade de 110 km/h.",
    explicacao: "GABARITO: ERRADO. Art. 61, § 1º, II, 'a', do CTB: Nas rodovias de pista dupla, a velocidade máxima é de 110 km/h para automóveis, camionetas, caminhonetes e motocicletas, e de 90 km/h para os demais veículos (veículos pesados como caminhões e ônibus). Portanto, não é o mesmo limite.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "tran-01-007",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Conselho Nacional de Trânsito (CONTRAN), órgão coordenador do Sistema Nacional de Trânsito e órgão máximo normativo e consultivo, tem sede no Distrito Federal.",
    explicacao: "GABARITO: CERTO. Art. 7º, I, e art. 12 do CTB: O CONTRAN é o órgão coordenador do Sistema Nacional de Trânsito e órgão máximo normativo e consultivo, com sede no Distrito Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-008",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Ao aproximar-se de qualquer tipo de cruzamento, o condutor do veículo deve demonstrar prudência especial, transitando em velocidade moderada, de forma que possa deter seu veículo com segurança para dar passagem a pedestre e a veículos que tenham o direito de preferência.",
    explicacao: "GABARITO: CERTO. Art. 44 do CTB: Ao aproximar-se de qualquer tipo de cruzamento, o condutor do veículo deve demonstrar prudência especial, transitando em velocidade moderada, de forma que possa deter seu veículo com segurança para dar passagem a pedestre e a veículos que tenham o direito de preferência.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "tran-01-009",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A realização de teste, exame clínico, perícia ou outro procedimento que, por meios técnicos ou científicos, permita certificar o estado de embriaguez do condutor é faculdade exclusiva dos peritos criminais federais, não podendo o policial rodoviário federal lavrar auto de infração com base em sinais notórios de alteração da capacidade psicomotora.",
    explicacao: "GABARITO: ERRADO. Art. 277 do CTB: O estado de embriaguez ou alteração da capacidade psicomotora poderá ser constatado por teste de alcoolemia (etilômetro), exame clínico, perícia, vídeo, prova testemunhal ou a constatação de sinais notórios que indiquem a alteração da capacidade psicomotora pelo agente de fiscalização de trânsito.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "tran-01-010",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O pedestre tem prioridade de passagem sobre os veículos em todas as travessias de pedestres onde não houver sinalização semafórica, sendo dever do condutor dar preferência de passagem.",
    explicacao: "GABARITO: CERTO. Art. 70, caput, do CTB: Os pedestres que estiverem atravessando a via sobre as faixas delimitadas para esse fim terão prioridade de passagem, exceto nos locais com sinalização semafórica, onde deverão ser respeitadas as disposições deste Código.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 11-16. FGV (Múltipla Escolha)
  {
    idSlug: "tran-01-011",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 29, II, do CTB, o condutor deverá guardar distância de segurança lateral e frontal entre o seu e os demais veículos, bem como em relação ao bordo da pista. Ao ultrapassar um ciclista (art. 201 do CTB), o condutor deve manter a distância lateral mínima obrigatória de:",
    explicacao: "GABARITO: B. Art. 201 do CTB: Deixar de guardar a distância lateral de 1,50 m (um metro e cinquenta centímetros) ao passar ou ultrapassar bicicleta é infração de trânsito.",
    alternativas: [
      { texto: "0,50 metro.", correta: false },
      { texto: "1,50 metro.", correta: true },
      { texto: "2,50 metros.", correta: false },
      { texto: "3,00 metros.", correta: false },
      { texto: "1,00 metro.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-012",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com o art. 64 do Código de Trânsito Brasileiro (com as alterações da Lei nº 14.071/2020), as crianças com idade inferior a 10 (dez) anos que não tenham atingido 1,45 m (um metro e quarenta e cinco centímetros) de altura devem ser transportadas:",
    explicacao: "GABARITO: C. Art. 64 do CTB: As crianças com idade inferior a 10 (dez) anos que não tenham atingido 1,45 m de altura devem ser transportadas nos bancos traseiros, em dispositivo de retenção adequado à sua idade, peso e altura, salvo exceções regulamentadas pelo CONTRAN.",
    alternativas: [
      { texto: "no banco dianteiro, usando apenas o cinto de segurança comum de dois pontos.", correta: false },
      { texto: "no colo de passageiro adulto no banco traseiro.", correta: false },
      { texto: "nos bancos traseiros, em dispositivo de retenção adequado à sua idade, peso e altura.", correta: true },
      { texto: "no compartimento de carga devidamente fechado.", correta: false },
      { texto: "livremente sem necessidade de retenção se o trajeto for inferior a 5 km.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-013",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre as ordens emanadas pelos agentes da autoridade de trânsito e a hierarquia da sinalização de trânsito no CTB (art. 89), assinale a afirmativa correta.",
    explicacao: "GABARITO: D. Art. 89 do CTB: A sinalização terá a seguinte ordem de prevalência: I - as ordens do agente de trânsito sobre as normas de circulação e outros sinais; II - as indicações do semáforo sobre os demais sinais; III - as indicações dos sinais sobre as demais normas de trânsito.",
    alternativas: [
      { texto: "As placas de trânsito prevalecem sobre as ordens do agente de fiscalização.", correta: false },
      { texto: "As normas gerais de circulação prevalecem sobre as indicações do semáforo.", correta: false },
      { texto: "A sinalização horizontal sempre prevalece sobre as ordens do policial rodoviário federal.", correta: false },
      { texto: "As ordens do agente da autoridade de trânsito prevalecem sobre as normas de circulação e outros sinais.", correta: true },
      { texto: "O semáforo tem prevalência máxima absoluta sobre qualquer comando gestual do agente de trânsito.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-014",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O uso da buzina nas vias urbanas é permitido pelo CTB (art. 41) apenas em:",
    explicacao: "GABARITO: A. Art. 41 do CTB: O condutor de veículo só poderá fazer uso de buzina, desde que em toque breve, nas seguintes situações: I - para fazer as advertências necessárias a fim de evitar acidentes; II - fora das áreas urbanas, quando for conveniente advertir a um condutor que se tem o propósito de ultrapassá-lo.",
    alternativas: [
      { texto: "toque breve, para fazer as advertências necessárias a fim de evitar acidentes.", correta: true },
      { texto: "toques prolongados e sucessivos para apressar pedestres lentos.", correta: false },
      { texto: "qualquer circunstância entre as 22h e 6h em frente a hospitais.", correta: false },
      { texto: "substituição ao uso do freio e da seta em cruzamentos.", correta: false },
      { texto: "comemorações desportivas em áreas residenciais à noite.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-015",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Oficial Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Ao ouvirem os dispositivos sonoros de alarme acionados por viatura do Corpo de Bombeiros Militar em atendimento de emergência (art. 29, VII, 'a', do CTB), todos os condutores de veículos que transitam na mesma via deverão:",
    explicacao: "GABARITO: E. Art. 29, VII, 'a', do CTB: Quando os dispositivos estiverem acionados, todos os condutores deverão deixar livre a passagem pela faixa da esquerda, indo para a direita da via e parando, se necessário.",
    alternativas: [
      { texto: "acelerar para ultrapassar o veículo de emergência o mais rápido possível.", correta: false },
      { texto: "ocupar imediatamente a faixa da esquerda para abrir a faixa da direita.", correta: false },
      { texto: "fazer marcha a ré no acostamento até o veículo passar.", correta: false },
      { texto: "ligar o pisca-alerta e permanecer imóvel no meio da via.", correta: false },
      { texto: "deixar livre a passagem pela faixa da esquerda, indo para a direita da via e parando, se necessário.", correta: true },
    ],
  },
  {
    idSlug: "tran-01-016",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação ao tráfego de ciclomotores nas vias públicas (art. 57 do CTB), assinale a afirmativa correta.",
    explicacao: "GABARITO: C. Art. 57 do CTB: Os ciclomotores devem ser conduzidos pela direita da pista de rolamento, preferencialmente no centro da faixa mais à direita ou no bordo direito da pista sempre que não houver acostamento ou faixa própria a eles destinada, sendo proibida a sua circulação nas vias de trânsito rápido e sobre as calçadas das vias urbanas.",
    alternativas: [
      { texto: "Podem circular livremente em vias de trânsito rápido e rodovias sem qualquer restrição.", correta: false },
      { texto: "Devem transitar obrigatoriamente pela faixa da esquerda em velocidade máxima de 100 km/h.", correta: false },
      { texto: "Devem ser conduzidos pela direita da pista, preferencialmente no centro da faixa mais à direita, sendo proibida a sua circulação nas vias de trânsito rápido.", correta: true },
      { texto: "São autorizados a circular sobre as calçadas das vias urbanas em qualquer situação.", correta: false },
      { texto: "Dispensam o uso de capacete de segurança se conduzidos por maiores de 21 anos.", correta: false },
    ],
  },
  // 17-20. VUNESP (Múltipla Escolha)
  {
    idSlug: "tran-01-017",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Onde não houver sinalização regulamentadora, a velocidade máxima permitida nas vias urbanas locais é de:",
    explicacao: "GABARITO: B. Art. 61, § 1º, I, 'd', do CTB: Nas vias urbanas locais, onde não houver sinalização regulamentadora, a velocidade máxima é de 30 km/h.",
    alternativas: [
      { texto: "20 km/h.", correta: false },
      { texto: "30 km/h.", correta: true },
      { texto: "40 km/h.", correta: false },
      { texto: "50 km/h.", correta: false },
      { texto: "60 km/h.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-018",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A ultrapassagem de outro veículo em movimento deverá ser feita pela esquerda, obedecida a sinalização regulamentar e as demais normas estabelecidas no CTB, exceto quando:",
    explicacao: "GABARITO: A. Art. 29, IX, do CTB: A ultrapassagem de outro veículo em movimento deverá ser feita pela esquerda, obedecida a sinalização regulamentar e as demais normas estabelecidas neste Código, exceto quando o veículo a ser ultrapassado estiver sinalizando o propósito de entrar à esquerda.",
    alternativas: [
      { texto: "o veículo a ser ultrapassado estiver sinalizando o propósito de entrar à esquerda.", correta: true },
      { texto: "o condutor estiver com pressa em rodovia pedagiada.", correta: false },
      { texto: "houver acostamento asfaltado na pista da direita.", correta: false },
      { texto: "o veículo à frente for de grande porte como um caminhão bitrem.", correta: false },
      { texto: "se tratar de via com limite de 120 km/h.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-019",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 29, IV, do CTB, quando uma pista de rolamento comportar várias faixas de circulação no mesmo sentido, são as da direita destinadas:",
    explicacao: "GABARITO: D. Art. 29, IV, do CTB: Quando uma pista de rolamento comportar várias faixas de circulação no mesmo sentido, são as da direita destinadas ao deslocamento dos veículos mais lentos e de maior porte, quando não houver faixa especial a eles destinada, e as da esquerda, destinadas à ultrapassagem e ao deslocamento dos veículos de maior velocidade.",
    alternativas: [
      { texto: "exclusivamente aos veículos oficiais em operação de emergência.", correta: false },
      { texto: "à ultrapassagem de veículos leves e esportivos.", correta: false },
      { texto: "ao trânsito de pedestres em áreas rurais.", correta: false },
      { texto: "ao deslocamento dos veículos mais lentos e de maior porte, quando não houver faixa especial a eles destinada.", correta: true },
      { texto: "ao estacionamento livre durante horário comercial.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-020",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O embarque e o desembarque de passageiros devem ser feitos (art. 49 do CTB):",
    explicacao: "GABARITO: C. Art. 49 do CTB: O condutor e os passageiros não deverão abrir a porta do veículo, deixá-la aberta ou descer do veículo sem antes se certificarem de que isso não constitui perigo para eles e para outros usuários da via. Parágrafo único: O embarque e o desembarque devem ocorrer sempre do lado da calçada, pouco importando o tipo de veículo, salvo para o condutor.",
    alternativas: [
      { texto: "sempre pelo lado esquerdo da via, voltado para o fluxo dos veículos rápidos.", correta: false },
      { texto: "indiferentemente por qualquer lado, mesmo com a porta aberta em movimento.", correta: false },
      { texto: "sempre do lado da calçada, pouco importando o tipo de veículo, salvo para o condutor.", correta: true },
      { texto: "exclusivamente na faixa central das rodovias.", correta: false },
      { texto: "em marcha lenta sem necessidade de parada total do veículo.", correta: false },
    ],
  },
  // 21-23. AOCP (Múltipla Escolha)
  {
    idSlug: "tran-01-021",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 62 do CTB, a velocidade mínima não poderá ser inferior à:",
    explicacao: "GABARITO: B. Art. 62 do CTB: A velocidade mínima não poderá ser inferior à metade da velocidade máxima estabelecida, respeitadas as condições operacionais de trânsito e da via.",
    alternativas: [
      { texto: "um terço da velocidade máxima estabelecida.", correta: false },
      { texto: "metade da velocidade máxima estabelecida, respeitadas as condições da via e do trânsito.", correta: true },
      { texto: "20 km/h em qualquer tipo de rodovia.", correta: false },
      { texto: "quarta parte da velocidade média do fluxo.", correta: false },
      { texto: "metade da velocidade do veículo que trafega logo atrás.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-022",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o art. 26 do CTB, os usuários das vias terrestres devem:",
    explicacao: "GABARITO: E. Art. 26, I e II, do CTB: Os usuários das vias terrestres devem abster-se de todo ato que possa constituir perigo ou obstáculo para o trânsito de veículos, de pessoas ou de animais, ou ainda causar danos a propriedades públicas ou privadas, e abster-se de obstruir o trânsito ou torná-lo perigoso, atirando, depositando ou abandonando na via objetos ou substâncias.",
    alternativas: [
      { texto: "priorizar a velocidade máxima dos veículos automotores sobre a segurança dos pedestres.", correta: false },
      { texto: "depositar entulhos de obras nas calçadas desde que autorizados informalmente.", correta: false },
      { texto: "utilizar a buzina em áreas hospitalares para advertência de rotina.", correta: false },
      { texto: "estacionar em esquinas a menos de 5 metros para melhor visibilidade.", correta: false },
      { texto: "abster-se de todo ato que possa constituir perigo ou obstáculo para o trânsito de pessoas, veículos ou animais, ou causar danos.", correta: true },
    ],
  },
  {
    idSlug: "tran-01-023",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O condutor não poderá ultrapassar veículos em vias com duplo sentido de direção e pista única, nos seguintes trechos, EXCETO:",
    explicacao: "GABARITO: A. Art. 32 do CTB: O condutor não poderá ultrapassar veículos em vias com duplo sentido de direção e pista única, nos trechos em curvas e em aclives sem visibilidade suficiente, nas passagens de nível, nos cruzamentos e em passagens de pedestres, exceto quando houver sinalização permitindo a ultrapassagem. Em retas planas com linha pontilhada (seccionada) e visibilidade livre, a ultrapassagem é plenamente permitida.",
    alternativas: [
      { texto: "em trechos retos com visibilidade ampla e sinalização horizontal seccionada permitindo a manobra.", correta: true },
      { texto: "nas passagens de nível.", correta: false },
      { texto: "nas curvas e em aclives sem visibilidade suficiente.", correta: false },
      { texto: "nos cruzamentos sem sinalização específica permitindo.", correta: false },
      { texto: "nas passagens de pedestres demarcadas.", correta: false },
    ],
  },
  // 24-25. IBFC (Múltipla Escolha)
  {
    idSlug: "tran-01-024",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O uso do cinto de segurança é obrigatório no território nacional (art. 65 do CTB) para:",
    explicacao: "GABARITO: C. Art. 65 do CTB: É obrigatório o uso do cinto de segurança para condutor e passageiros em todas as vias do território nacional, salvo em situações regulamentadas pelo CONTRAN.",
    alternativas: [
      { texto: "apenas o condutor do veículo em rodovias federais.", correta: false },
      { texto: "exclusivamente os passageiros do banco dianteiro.", correta: false },
      { texto: "o condutor e os passageiros em todas as vias do território nacional, salvo situações regulamentadas pelo CONTRAN.", correta: true },
      { texto: "apenas quando a velocidade do veículo ultrapassar 60 km/h.", correta: false },
      { texto: "somente veículos de transporte coletivo interestadual.", correta: false },
    ],
  },
  {
    idSlug: "tran-01-025",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_normas_circulacao,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nas vias urbanas arteriais onde não houver sinalização regulamentadora, a velocidade máxima permitida será de:",
    explicacao: "GABARITO: D. Art. 61, § 1º, I, 'b', do CTB: Nas vias urbanas arteriais, onde não existir sinalização regulamentadora, a velocidade máxima será de 60 km/h.",
    alternativas: [
      { texto: "30 km/h.", correta: false },
      { texto: "40 km/h.", correta: false },
      { texto: "50 km/h.", correta: false },
      { texto: "60 km/h.", correta: true },
      { texto: "80 km/h.", correta: false },
    ],
  },
];
