import { TAXONOMIA } from "./taxonomia.mjs";

const D = TAXONOMIA.disciplinas.portugues;
const A = TAXONOMIA.assuntos;

const ce = (id, assunto, banca, orgao, cargo, ano, dificuldade, ...rest) => {
  let texto_apoio = null;
  let enunciado = "";
  let correta = true;
  let explicacao = "";
  if (rest.length === 4) {
    [texto_apoio, enunciado, correta, explicacao] = rest;
  } else if (rest.length === 3) {
    [enunciado, correta, explicacao] = rest;
  }
  return {
    idSlug: `batch3-port-${String(id).padStart(3, "0")}`,
    disciplina_id: D,
    assunto_id: A[assunto],
    banca_nome: banca,
    orgao_nome: orgao,
    cargo_nome: cargo,
    ano,
    tipo: "certo_errado",
    dificuldade,
    texto_apoio: texto_apoio || null,
    enunciado,
    explicacao,
    alternativas: [
      { texto: "Certo", correta, explicacao_especifica: correta ? "A afirmação está de acordo com a norma-padrão e com o sentido do texto." : "A afirmação contraria a norma-padrão ou altera o sentido apresentado." },
      { texto: "Errado", correta: !correta, explicacao_especifica: !correta ? "A afirmação identifica corretamente o desvio gramatical ou semântico indicado." : "A afirmação deve ser rejeitada porque a construção original está correta." },
    ],
  };
};

const me = (id, assunto, banca, orgao, cargo, ano, dificuldade, ...rest) => {
  let texto_apoio = null;
  let enunciado = "";
  let explicacao = "";
  let alternativas = [];
  if (rest.length === 4) {
    [texto_apoio, enunciado, explicacao, alternativas] = rest;
  } else if (rest.length === 3) {
    [enunciado, explicacao, alternativas] = rest;
  }
  return {
    idSlug: `batch3-port-${String(id).padStart(3, "0")}`,
    disciplina_id: D,
    assunto_id: A[assunto],
    banca_nome: banca,
    orgao_nome: orgao,
    cargo_nome: cargo,
    ano,
    tipo: "multipla_escolha",
    dificuldade,
    texto_apoio: texto_apoio || null,
    enunciado,
    explicacao,
    alternativas,
  };
};

export const portQuestions = [
  ce(1, "interpretacao", "CEBRASPE", "Polícia Federal", "Agente de Polícia Federal", 2024, "medio",
    "Em relatório de inteligência, registrou-se: 'A queda dos roubos no entorno da rodoviária coincidiu com a presença ostensiva de equipes a pé; ainda assim, a chefia recomendou cautela antes de atribuir o resultado exclusivamente à operação.'",
    "Infere-se do texto que a chefia reconheceu a possibilidade de relação entre policiamento ostensivo e redução dos roubos, mas evitou afirmar causalidade única.", true,
    "O advérbio 'exclusivamente' e a recomendação de cautela afastam leitura de causa única, sem negar possível relação entre os fatos."),
  me(2, "interpretacao", "FGV", "Polícia Civil do Rio de Janeiro", "Inspetor de Polícia", 2023, "medio",
    "Comunicado interno: 'Não se divulgarão imagens de suspeitos antes da checagem jurídica, a fim de preservar a investigação e evitar exposição indevida.'",
    "A paráfrase que preserva o sentido original do comunicado é:",
    "A alternativa correta mantém finalidade dupla e a condição prévia de checagem jurídica.", [
      { letra: "A", texto: "As imagens de suspeitos somente serão divulgadas após verificação jurídica, para proteger a investigação e impedir exposição indevida.", correta: true, explicacao_especifica: "Conserva a condição temporal e as finalidades indicadas." },
      { letra: "B", texto: "As imagens de suspeitos serão sempre divulgadas quando a investigação estiver preservada.", correta: false, explicacao_especifica: "Acrescenta ideia de divulgação obrigatória inexistente." },
      { letra: "C", texto: "A checagem jurídica será dispensada se houver risco de exposição indevida.", correta: false, explicacao_especifica: "Inverte a exigência expressa no texto." },
      { letra: "D", texto: "A divulgação de imagens foi proibida porque a investigação já foi comprometida.", correta: false, explicacao_especifica: "Transforma cautela preventiva em fato consumado." },
      { letra: "E", texto: "A exposição de suspeitos é necessária para preservar a apuração policial.", correta: false, explicacao_especifica: "Contraria a finalidade do comunicado." },
    ]),
  ce(3, "regencia_crase", "VUNESP", "PC-SP", "Investigador de Polícia", 2024, "medio",
    "No despacho, escreveu-se: 'A equipe retornou à delegacia ao amanhecer e comunicou o fato à autoridade plantonista.'",
    "As duas ocorrências do acento grave estão justificadas pela fusão da preposição 'a' com artigo feminino.", true,
    "'Retornar a' exige preposição, e 'delegacia' admite artigo; 'comunicar algo a alguém' rege preposição diante de 'autoridade', também com artigo."),
  me(4, "regencia_crase", "IBFC", "Polícia Penal de Minas Gerais", "Policial Penal", 2022, "medio",
    "Considere a frase: 'O servidor referiu-se ___ medida protetiva e encaminhou a vítima ___ unidade especializada.'",
    "Assinale a opção que preenche corretamente as lacunas.",
    "Há crase em ambas as lacunas: 'referir-se a' e 'encaminhar a', somados ao artigo feminino dos substantivos.", [
      { letra: "A", texto: "à / à", correta: true, explicacao_especifica: "As duas formas resultam de preposição mais artigo feminino." },
      { letra: "B", texto: "a / à", correta: false, explicacao_especifica: "Falta o acento em 'à medida protetiva'." },
      { letra: "C", texto: "à / a", correta: false, explicacao_especifica: "Falta o acento em 'à unidade especializada'." },
      { letra: "D", texto: "a / a", correta: false, explicacao_especifica: "Ignora a fusão nas duas ocorrências." },
      { letra: "E", texto: "há / à", correta: false, explicacao_especifica: "'Há' não exerce papel preposicional nesse contexto." },
    ]),
  ce(5, "concordancia", "CEBRASPE", "Polícia Rodoviária Federal", "Policial Rodoviário Federal", 2021, "dificil",
    "Relatório operacional: 'A maior parte dos condutores abordados apresentou documento válido.'",
    "A forma verbal 'apresentou' está correta, mas também seria admissível 'apresentaram', porque o sujeito é expressão partitiva seguida de especificador plural.", true,
    "Com expressões partitivas como 'a maior parte de', admite-se concordância com o núcleo singular ou com o termo plural especificador."),
  me(6, "concordancia", "AOCP", "Polícia Científica do Paraná", "Perito Criminal", 2023, "medio",
    "Em laudo preliminar, o perito escreveu quatro versões de uma mesma informação.",
    "Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão.",
    "O verbo haver, no sentido de existir, é impessoal e permanece na terceira pessoa do singular.", [
      { letra: "A", texto: "Havia marcas de frenagem próximas ao veículo apreendido.", correta: true, explicacao_especifica: "'Haver' existencial fica no singular." },
      { letra: "B", texto: "Haviam marcas de frenagem próximas ao veículo apreendido.", correta: false, explicacao_especifica: "Flexão indevida de verbo impessoal." },
      { letra: "C", texto: "Fazem três horas que a equipe isolou a área.", correta: false, explicacao_especifica: "'Fazer' indicando tempo decorrido é impessoal: faz." },
      { letra: "D", texto: "Existia muitos vestígios sob a ponte.", correta: false, explicacao_especifica: "'Existir' é pessoal e deve concordar: existiam." },
      { letra: "E", texto: "Chegou ao setor os documentos lacrados.", correta: false, explicacao_especifica: "O sujeito plural exige 'chegaram'." },
    ]),
  ce(7, "pontuacao", "FGV", "Secretaria Nacional de Segurança Pública", "Analista Técnico", 2024, "medio",
    "Texto: 'Os policiais que atuaram na divisa receberam treinamento específico. Os policiais, que atuaram na divisa, receberam treinamento específico.'",
    "No segundo período, as vírgulas transformam a oração adjetiva em explicativa e sugerem que todos os policiais mencionados atuaram na divisa.", true,
    "Orações adjetivas explicativas vêm entre vírgulas e atribuem a característica a todo o referente; as restritivas selecionam parte do grupo."),
  me(8, "pontuacao", "FCC", "Tribunal de Justiça Militar", "Oficial de Justiça", 2022, "facil",
    "Durante a madrugada os agentes cumpriram mandado em área rural sem registro de confronto.",
    "Assinale a pontuação adequada para destacar o adjunto adverbial deslocado sem alterar o sentido.",
    "Adjunto adverbial deslocado de maior extensão costuma ser separado por vírgula.", [
      { letra: "A", texto: "Durante a madrugada, os agentes cumpriram mandado em área rural, sem registro de confronto.", correta: true, explicacao_especifica: "As vírgulas marcam o adjunto inicial e o adjunto final destacado." },
      { letra: "B", texto: "Durante, a madrugada os agentes cumpriram mandado em área rural sem registro de confronto.", correta: false, explicacao_especifica: "Separa indevidamente preposição e complemento." },
      { letra: "C", texto: "Durante a madrugada os agentes, cumpriram mandado em área rural sem registro de confronto.", correta: false, explicacao_especifica: "Separa sujeito e verbo." },
      { letra: "D", texto: "Durante a madrugada os agentes cumpriram, mandado em área rural sem registro de confronto.", correta: false, explicacao_especifica: "Separa verbo e objeto direto." },
      { letra: "E", texto: "Durante a madrugada, os agentes, cumpriram mandado, em área rural sem registro de confronto.", correta: false, explicacao_especifica: "Isola indevidamente o sujeito." },
    ]),
  ce(9, "morfologia", "CEBRASPE", "PC-DF", "Escrivão de Polícia", 2023, "medio",
    "Em nota à imprensa, leu-se: 'Como a área permanecia instável, a perícia foi adiada.'",
    "No período, 'Como' introduz oração com valor causal, equivalente a 'visto que'.", true,
    "No início do período e seguido de fato que justifica a oração principal, 'como' pode ter valor causal."),
  me(10, "morfologia", "FGV", "Polícia Militar de São Paulo", "Soldado", 2024, "medio",
    "Frase do boletim: 'A guarnição preservou o local, pois aguardava a chegada da perícia.'",
    "O conectivo 'pois' estabelece relação de:",
    "Posposto à oração principal sem intercalação explicativa complexa, 'pois' apresenta justificativa para a conduta narrada.", [
      { letra: "A", texto: "explicação", correta: true, explicacao_especifica: "A segunda oração explica por que o local foi preservado." },
      { letra: "B", texto: "concessão", correta: false, explicacao_especifica: "Não há quebra de expectativa." },
      { letra: "C", texto: "comparação", correta: false, explicacao_especifica: "Não compara dois elementos." },
      { letra: "D", texto: "condição", correta: false, explicacao_especifica: "Não indica requisito para realização do fato." },
      { letra: "E", texto: "alternância", correta: false, explicacao_especifica: "Não apresenta escolhas excludentes." },
    ]),
  ce(11, "sintaxe", "VUNESP", "PC-BA", "Delegado de Polícia", 2022, "dificil",
    "Despacho: 'Determino que se preservem os vestígios até a chegada da equipe técnica.'",
    "Em 'se preservem os vestígios', o 'se' funciona como partícula apassivadora, razão pela qual o verbo concorda com o sujeito paciente plural.", true,
    "Com verbo transitivo direto e sujeito paciente expresso, o 'se' é apassivador: os vestígios sejam preservados."),
  me(12, "sintaxe", "Instituto AOCP", "Polícia Penal do Distrito Federal", "Policial Penal", 2023, "medio",
    "Em normas internas, aparecem as construções: I. 'Precisa-se de agentes no pátio.' II. 'Revistam-se as celas antes da troca de turno.'",
    "Assinale a análise correta.",
    "Em I, o verbo é transitivo indireto e o 'se' indetermina o sujeito; em II, há voz passiva sintética com sujeito plural.", [
      { letra: "A", texto: "Em I, o 'se' é índice de indeterminação do sujeito; em II, é partícula apassivadora.", correta: true, explicacao_especifica: "A distinção decorre da regência verbal e da presença de sujeito paciente." },
      { letra: "B", texto: "Em I e II, o 'se' é sempre pronome reflexivo.", correta: false, explicacao_especifica: "Não há ação praticada e recebida pelo mesmo sujeito." },
      { letra: "C", texto: "Em I, o verbo deveria obrigatoriamente ir ao plural.", correta: false, explicacao_especifica: "Com sujeito indeterminado, fica no singular." },
      { letra: "D", texto: "Em II, 'as celas' é objeto direto, não sujeito.", correta: false, explicacao_especifica: "Na passiva sintética, 'as celas' é sujeito paciente." },
      { letra: "E", texto: "As duas construções estão incorretas pela presença de 'se'.", correta: false, explicacao_especifica: "Ambas são admitidas pela norma-padrão." },
    ]),
  ce(13, "ortografia", "IBFC", "Polícia Militar da Bahia", "Soldado", 2023, "facil",
    "Aviso no plantão: 'É imprescindível discriminar corretamente os pertences apreendidos e descrevê-los no auto.'",
    "A palavra 'discriminar' foi empregada adequadamente no sentido de distinguir ou relacionar minuciosamente.", true,
    "'Discriminar' significa distinguir, separar ou especificar; 'descriminar' significa deixar de considerar crime."),
  me(14, "ortografia", "VUNESP", "Guarda Civil Municipal", "Guarda Municipal", 2024, "facil",
    "O chefe da equipe pediu atenção à grafia de palavras recorrentes em ocorrências.",
    "Assinale a alternativa em que todas as palavras estão grafadas corretamente.",
    "'Exceção', 'flagrante' e 'mandado' estão corretamente grafadas e têm sentidos adequados ao contexto policial.", [
      { letra: "A", texto: "exceção, flagrante, mandado", correta: true, explicacao_especifica: "Todas seguem a ortografia oficial." },
      { letra: "B", texto: "excessão, fragrante, mandato", correta: false, explicacao_especifica: "Há erro em 'excessão' e confusão semântica entre mandado e mandato." },
      { letra: "C", texto: "exceção, fragrante, mandadto", correta: false, explicacao_especifica: "'Fragrante' refere-se a aroma; 'mandadto' inexiste." },
      { letra: "D", texto: "esceção, flagrante, mandado", correta: false, explicacao_especifica: "'Esceção' está grafada incorretamente." },
      { letra: "E", texto: "exceção, flagante, mandado", correta: false, explicacao_especifica: "Falta 'r' em 'flagrante'." },
    ]),
  ce(15, "interpretacao", "CEBRASPE", "Polícia Civil de Pernambuco", "Agente de Polícia", 2024, "medio",
    "Trecho de notícia institucional: 'A delegacia ampliou o horário de atendimento, mas manteve a triagem para casos urgentes.'",
    "Pressupõe-se que já havia algum horário de atendimento antes da ampliação mencionada.", true,
    "O verbo 'ampliou' pressupõe existência anterior daquilo que foi aumentado."),
  me(16, "interpretacao", "FGV", "Polícia Civil de Santa Catarina", "Escrivão de Polícia", 2022, "dificil",
    "Nota técnica: 'Embora o aplicativo tenha agilizado registros simples, ocorrências complexas continuam a exigir escuta qualificada do cidadão.'",
    "A conclusão compatível com o texto é:",
    "O texto contrasta ganho de agilidade em casos simples com permanência de atendimento humano qualificado em casos complexos.", [
      { letra: "A", texto: "A digitalização não elimina a necessidade de atendimento especializado em determinadas ocorrências.", correta: true, explicacao_especifica: "É inferência autorizada pelo contraste apresentado." },
      { letra: "B", texto: "O aplicativo tornou dispensável a escuta do cidadão em qualquer ocorrência.", correta: false, explicacao_especifica: "Contraria a oração principal." },
      { letra: "C", texto: "Ocorrências simples passaram a exigir escuta mais demorada.", correta: false, explicacao_especifica: "O texto afirma que foram agilizadas." },
      { letra: "D", texto: "A nota defende o fim do registro digital de ocorrências.", correta: false, explicacao_especifica: "Não há rejeição ao aplicativo." },
      { letra: "E", texto: "Todas as ocorrências complexas foram resolvidas pelo aplicativo.", correta: false, explicacao_especifica: "Não se menciona resolução automática." },
    ]),
  ce(17, "regencia_crase", "FCC", "Polícia Militar do Pará", "Oficial", 2023, "medio",
    "Ordem de serviço: 'A patrulha chegou a Brasília antes do comboio oficial.'",
    "A ausência de crase antes de 'Brasília' está correta, pois o topônimo não vem antecedido de artigo no uso corrente da frase.", true,
    "Aplica-se o teste do retorno: chegou de Brasília, não da Brasília; logo, não há artigo a fundir com a preposição."),
  me(18, "regencia_crase", "CEBRASPE", "Polícia Federal", "Papiloscopista", 2021, "dificil",
    "Complete: 'A testemunha referiu-se à cidade ___ qual retornaria e ao bairro ___ que fora conduzida.'",
    "Considerando a regência e o uso de pronomes relativos, assinale a opção correta.",
    "Com 'retornar a' e antecedente feminino 'cidade', ocorre crase antes de 'qual'; com 'conduzir a' e antecedente masculino 'bairro', usa-se 'a que', sem crase.", [
      { letra: "A", texto: "à / a", correta: true, explicacao_especifica: "'À qual' retoma cidade; 'a que' retoma bairro." },
      { letra: "B", texto: "a / à", correta: false, explicacao_especifica: "Inverte as marcas exigidas pelos antecedentes." },
      { letra: "C", texto: "à / à", correta: false, explicacao_especifica: "Não há artigo feminino em 'bairro'." },
      { letra: "D", texto: "a / a", correta: false, explicacao_especifica: "Falta crase em 'à qual'." },
      { letra: "E", texto: "há / a", correta: false, explicacao_especifica: "'Há' não substitui preposição exigida pelo verbo." },
    ]),
  ce(19, "concordancia", "FGV", "Polícia Civil do Amazonas", "Investigador", 2024, "medio",
    "Boletim: 'Faz cinco dias que a equipe monitora a rota usada pelos suspeitos.'",
    "A forma 'Faz' está correta, porque o verbo fazer, indicando tempo decorrido, é impessoal.", true,
    "Verbos impessoais não têm sujeito e permanecem na terceira pessoa do singular."),
  me(20, "concordancia", "VUNESP", "PC-SP", "Escrivão de Polícia", 2023, "medio",
    "Analise as versões de uma informação administrativa.",
    "Assinale a alternativa correta quanto à concordância nominal.",
    "O adjetivo anteposto concorda com o substantivo mais próximo ou, no caso, pode caracterizar adequadamente os dois núcleos no plural quando posposto.", [
      { letra: "A", texto: "Foram anexados ao inquérito a foto e o vídeo periciais.", correta: true, explicacao_especifica: "O particípio concorda com sujeito composto posposto e o adjetivo qualifica os dois núcleos no plural." },
      { letra: "B", texto: "Foi anexado ao inquérito a foto e o vídeo pericial.", correta: false, explicacao_especifica: "O sujeito composto exige plural em 'foram anexados'." },
      { letra: "C", texto: "Seguem incluso as cópias dos mandados.", correta: false, explicacao_especifica: "'Incluso' deve concordar: inclusas." },
      { letra: "D", texto: "É proibida entrada de pessoas não autorizados.", correta: false, explicacao_especifica: "O adjetivo deve concordar com 'pessoas': autorizadas." },
      { letra: "E", texto: "As equipes permaneceram alerta, cansadas e atento.", correta: false, explicacao_especifica: "'Atento' deve ir ao plural feminino; 'alerta' é invariável nesse uso." },
    ]),
  ce(21, "pontuacao", "CEBRASPE", "Polícia Civil do Ceará", "Inspetor", 2022, "medio",
    "Frase: 'No fim da tarde, a equipe de busca encerrou as diligências.'",
    "A vírgula após 'tarde' separa adjunto adverbial deslocado e seu emprego é adequado.", true,
    "Adjuntos adverbiais deslocados para o início, sobretudo com mais de uma palavra, podem ser separados por vírgula."),
  me(22, "pontuacao", "FGV", "Polícia Penal do Espírito Santo", "Policial Penal", 2024, "dificil",
    "Considere: 'Os internos que aderiram ao programa educacional receberam certificados.'",
    "A alteração que muda o sentido original é:",
    "A inserção de vírgulas transforma oração restritiva em explicativa, ampliando o alcance para todos os internos.", [
      { letra: "A", texto: "Os internos, que aderiram ao programa educacional, receberam certificados.", correta: true, explicacao_especifica: "Passa a indicar que todos os internos aderiram ao programa." },
      { letra: "B", texto: "Receberam certificados os internos que aderiram ao programa educacional.", correta: false, explicacao_especifica: "A inversão preserva a restrição." },
      { letra: "C", texto: "Os internos que aderiram ao programa educacional foram certificados.", correta: false, explicacao_especifica: "Mantém o grupo restrito." },
      { letra: "D", texto: "Foram certificados os internos que aderiram ao programa educacional.", correta: false, explicacao_especifica: "Não altera o alcance da oração adjetiva." },
      { letra: "E", texto: "Os internos que aderiram ao programa educacional receberam a certificação.", correta: false, explicacao_especifica: "Troca expressão equivalente." },
    ]),
  ce(23, "morfologia", "AOCP", "Polícia Militar do Paraná", "Cadete", 2023, "medio",
    "Trecho: 'Se a câmera corporal estiver ativa, o procedimento será registrado integralmente.'",
    "O vocábulo 'Se' introduz oração subordinada adverbial condicional.", true,
    "A oração iniciada por 'se' estabelece condição para que o procedimento seja registrado."),
  me(24, "morfologia", "IBFC", "Polícia Civil de Minas Gerais", "Investigador", 2022, "medio",
    "No período 'Embora a denúncia fosse anônima, a equipe verificou os dados mínimos antes de agir', o termo 'Embora' expressa:",
    "A oração introduzida por 'embora' apresenta obstáculo insuficiente para impedir a ação da equipe.",
    "Trata-se de conjunção concessiva.", [
      { letra: "A", texto: "concessão", correta: true, explicacao_especifica: "Indica fato contrário à expectativa, mas não impeditivo." },
      { letra: "B", texto: "causa", correta: false, explicacao_especifica: "Não apresenta motivo direto da ação." },
      { letra: "C", texto: "finalidade", correta: false, explicacao_especifica: "Não equivale a 'para que'." },
      { letra: "D", texto: "proporção", correta: false, explicacao_especifica: "Não há ideia de variação simultânea." },
      { letra: "E", texto: "conformidade", correta: false, explicacao_especifica: "Não equivale a 'conforme'." },
    ]),
  ce(25, "sintaxe", "FCC", "Polícia Civil do Maranhão", "Escrivão", 2021, "medio",
    "Frase: 'Convém que a autoridade registre a justificativa da busca.'",
    "A oração 'que a autoridade registre a justificativa da busca' exerce função de sujeito da forma verbal 'convém'.", true,
    "Com verbos unipessoais como 'convém', a oração substantiva subjetiva funciona como sujeito oracional."),
  me(26, "sintaxe", "CEBRASPE", "Polícia Federal", "Delegado de Polícia Federal", 2024, "dificil",
    "Considere as possibilidades de reescrita: 'A chefia determinou que as equipes reforçassem o patrulhamento.'",
    "Assinale a reescrita gramaticalmente correta e coerente.",
    "A alternativa preserva a relação de determinação e usa adequadamente a voz passiva analítica.", [
      { letra: "A", texto: "Foi determinado pela chefia que as equipes reforçassem o patrulhamento.", correta: true, explicacao_especifica: "Mantém o conteúdo e a correção gramatical." },
      { letra: "B", texto: "A chefia determinou de que as equipes reforçassem o patrulhamento.", correta: false, explicacao_especifica: "Há preposição indevida antes da oração objetiva direta." },
      { letra: "C", texto: "Determinou-se as equipes reforçassem o patrulhamento.", correta: false, explicacao_especifica: "Falta conectivo que introduza a oração determinada." },
      { letra: "D", texto: "A chefia determinou as equipes de reforçarem o patrulhamento.", correta: false, explicacao_especifica: "A regência e a estrutura infinitiva são inadequadas." },
      { letra: "E", texto: "As equipes determinaram pela chefia o reforço do patrulhamento.", correta: false, explicacao_especifica: "Altera agente e sentido." },
    ]),
  ce(27, "ortografia", "FGV", "Polícia Civil da Bahia", "Perito Técnico", 2024, "facil",
    "Em registro formal, a grafia 'auto de prisão em flagrante' está correta.",
    "A palavra 'flagrante' designa situação percebida no momento da ocorrência, diferindo de 'fragrante', ligada a cheiro.", true,
    "A distinção ortográfica é recorrente: flagrante é evidente/no ato; fragrante é aromático."),
  me(28, "ortografia", "CEBRASPE", "Departamento Penitenciário Nacional", "Agente Federal de Execução Penal", 2021, "medio",
    "Assinale a frase sem erro de grafia ou de emprego vocabular.",
    "A alternativa correta distingue 'mandado' (ordem judicial) de 'mandato' (representação eletiva ou procuração).", [
      { letra: "A", texto: "O mandado de busca foi cumprido pela equipe especializada.", correta: true, explicacao_especifica: "'Mandado' é ordem emanada de autoridade." },
      { letra: "B", texto: "O mandato de busca foi cumprido pela equipe especializada.", correta: false, explicacao_especifica: "'Mandato' não designa ordem judicial de busca." },
      { letra: "C", texto: "O mandado foi comprido às seis horas.", correta: false, explicacao_especifica: "O correto é 'cumprido', não 'comprido'." },
      { letra: "D", texto: "A ordem judicial foi descriminada no sistema.", correta: false, explicacao_especifica: "O adequado é 'discriminada', no sentido de especificada." },
      { letra: "E", texto: "A equipe apreendeu objetos em fragrante delito.", correta: false, explicacao_especifica: "O correto é 'flagrante delito'." },
    ]),
  ce(29, "interpretacao", "VUNESP", "Guarda Civil Metropolitana", "Guarda Civil", 2023, "medio",
    "Trecho: 'A nova iluminação da praça não substitui o patrulhamento, mas reduz pontos de vulnerabilidade explorados por infratores.'",
    "O texto sustenta que a melhoria urbana atua como medida complementar, não como solução isolada de segurança.", true,
    "A expressão 'não substitui' e a conjunção adversativa orientam a leitura de complementaridade."),
  me(30, "interpretacao", "FCC", "Polícia Militar de Alagoas", "Soldado", 2022, "medio",
    "Relatório social: 'Quando a comunidade confia nos canais de denúncia, informações relevantes chegam mais cedo às equipes de investigação.'",
    "Está subentendido no trecho que:",
    "A oração temporal-condicional associa confiança comunitária à antecipação de informações úteis.", [
      { letra: "A", texto: "a confiança da comunidade pode favorecer o fluxo oportuno de informações", correta: true, explicacao_especifica: "É inferência compatível com a relação apresentada." },
      { letra: "B", texto: "as investigações prescindem de canais de denúncia", correta: false, explicacao_especifica: "Contraria o papel atribuído aos canais." },
      { letra: "C", texto: "toda denúncia comunitária é falsa", correta: false, explicacao_especifica: "Generalização sem base textual." },
      { letra: "D", texto: "as equipes só investigam crimes já solucionados", correta: false, explicacao_especifica: "Afirmação absurda e não autorizada pelo texto." },
      { letra: "E", texto: "a confiança impede a chegada de informações", correta: false, explicacao_especifica: "Inverte a relação do trecho." },
    ]),
  ce(31, "regencia_crase", "AOCP", "Polícia Civil do Pará", "Delegado", 2023, "dificil",
    "Frase: 'A diligência visava à proteção da vítima e ao resguardo das provas.'",
    "O acento grave em 'à proteção' é obrigatório, pois o verbo 'visar', no sentido de ter por objetivo, rege preposição 'a' na norma-padrão formal.", true,
    "'Visar a' no sentido de objetivar, em registro formal, soma-se ao artigo de 'proteção'."),
  me(32, "regencia_crase", "FGV", "Polícia Civil do Espírito Santo", "Investigador", 2024, "medio",
    "Assinale a frase em que o emprego da crase é proibido.",
    "Antes de verbo no infinitivo não ocorre artigo feminino, portanto não há crase.", [
      { letra: "A", texto: "A equipe começou a apurar a denúncia ainda no plantão.", correta: true, explicacao_especifica: "'Apurar' é verbo; não há artigo antes de infinitivo." },
      { letra: "B", texto: "A equipe retornou à sala de custódia.", correta: false, explicacao_especifica: "Há crase obrigatória." },
      { letra: "C", texto: "O delegado dirigiu-se à autoridade judicial.", correta: false, explicacao_especifica: "A regência exige preposição e o nome admite artigo." },
      { letra: "D", texto: "O documento foi entregue à escrivã responsável.", correta: false, explicacao_especifica: "Há fusão de preposição e artigo." },
      { letra: "E", texto: "A vítima compareceu à unidade especializada.", correta: false, explicacao_especifica: "Crase adequada após 'comparecer a'." },
    ]),
  ce(33, "concordancia", "CEBRASPE", "Polícia Civil de Alagoas", "Agente", 2021, "dificil",
    "Frase: 'Alugam-se equipamentos de radiocomunicação para operações integradas.'",
    "O plural em 'Alugam-se' justifica-se porque o 'se' é partícula apassivadora e 'equipamentos' é sujeito paciente.", true,
    "Equivale a 'equipamentos são alugados', com concordância no plural."),
  me(34, "concordancia", "IBFC", "Polícia Penal da Bahia", "Agente Penitenciário", 2023, "medio",
    "Assinale a alternativa em que a concordância com expressão partitiva está correta.",
    "Com 'parte de' seguida de plural, a concordância no singular é aceita por concordar com o núcleo 'parte'.", [
      { letra: "A", texto: "Parte dos servidores aderiu ao treinamento de escolta.", correta: true, explicacao_especifica: "Concordância com o núcleo singular 'parte'." },
      { letra: "B", texto: "Parte dos servidores aderiram ao treinamento de escolta está incorreto em qualquer contexto.", correta: false, explicacao_especifica: "A concordância com o especificador plural também pode ser admitida." },
      { letra: "C", texto: "A maioria dos internos recusaram-se é a única forma correta.", correta: false, explicacao_especifica: "Não é a única; a concordância com 'maioria' também é possível." },
      { letra: "D", texto: "Grande número de agentes compareceram é sempre erro absoluto.", correta: false, explicacao_especifica: "Há casos de concordância atrativa admitida com especificador plural." },
      { letra: "E", texto: "Um grupo de policiais chegaram é obrigatório pela norma-padrão.", correta: false, explicacao_especifica: "O obrigatório não procede; o núcleo singular permite 'chegou'." },
    ]),
  ce(35, "pontuacao", "VUNESP", "PC-SP", "Médico Legista", 2024, "medio",
    "Frase: 'O laudo, elaborado por peritos oficiais, foi juntado ao inquérito.'",
    "As vírgulas isolam termo de valor explicativo, sem restringir qual laudo foi juntado.", true,
    "O particípio entre vírgulas acrescenta informação explicativa sobre o laudo já identificado."),
  me(36, "pontuacao", "CEBRASPE", "Polícia Rodoviária Federal", "Agente Administrativo", 2022, "medio",
    "Assinale a opção em que a vírgula foi empregada indevidamente.",
    "Não se separa sujeito de predicado por vírgula.", [
      { letra: "A", texto: "Os agentes da barreira, abordaram o caminhão suspeito.", correta: true, explicacao_especifica: "A vírgula separa indevidamente sujeito e verbo." },
      { letra: "B", texto: "Após a revista, os agentes liberaram o veículo.", correta: false, explicacao_especifica: "A vírgula marca adjunto adverbial deslocado." },
      { letra: "C", texto: "O motorista, nervoso, apresentou documentos vencidos.", correta: false, explicacao_especifica: "O termo intercalado está corretamente isolado." },
      { letra: "D", texto: "A carga, que estava sem nota fiscal, foi apreendida.", correta: false, explicacao_especifica: "Oração explicativa corretamente isolada." },
      { letra: "E", texto: "No posto fiscal, havia fila de veículos.", correta: false, explicacao_especifica: "Adjunto deslocado com vírgula adequada." },
    ]),
  ce(37, "morfologia", "FCC", "Polícia Científica de Goiás", "Auxiliar de Autópsia", 2023, "medio",
    "Trecho: 'Que a cadeia de custódia seja preservada é condição para a validade da prova.'",
    "O 'que' inicial introduz oração substantiva subjetiva.", true,
    "A oração 'Que a cadeia...' funciona como sujeito de 'é condição'."),
  me(38, "morfologia", "FGV", "Polícia Militar do Rio de Janeiro", "Oficial", 2024, "dificil",
    "Assinale a alternativa em que 'como' tem valor conformativo.",
    "Valor conformativo equivale a 'conforme', indicando acordo com norma, ordem ou informação.", [
      { letra: "A", texto: "Como determinou o comandante, a tropa permaneceu na base.", correta: true, explicacao_especifica: "Equivale a 'conforme determinou'." },
      { letra: "B", texto: "Como chovia forte, a barreira foi suspensa.", correta: false, explicacao_especifica: "Nesse caso, 'como' é causal." },
      { letra: "C", texto: "O agente atuou como mediador do conflito.", correta: false, explicacao_especifica: "Indica papel/função, não conformidade." },
      { letra: "D", texto: "A viatura era rápida como uma motocicleta.", correta: false, explicacao_especifica: "Valor comparativo." },
      { letra: "E", texto: "Não se sabe como o suspeito saiu do local.", correta: false, explicacao_especifica: "Valor interrogativo indireto/modal." },
    ]),
  ce(39, "sintaxe", "IBFC", "Polícia Civil de Roraima", "Agente", 2022, "medio",
    "Frase: 'O escrivão informou ao delegado que as testemunhas chegariam às oito horas.'",
    "A oração iniciada por 'que' exerce função de objeto direto do verbo 'informou'.", true,
    "Quem informa informa algo a alguém; a oração corresponde ao conteúdo informado."),
  me(40, "sintaxe", "VUNESP", "Guarda Municipal de Campinas", "Guarda Municipal", 2023, "medio",
    "Assinale a reescrita que preserva correção gramatical e coerência: 'Os agentes recolheram as câmeras porque elas registraram a fuga.'",
    "A alternativa correta mantém relação causal e referência clara às câmeras.", [
      { letra: "A", texto: "Como registraram a fuga, as câmeras foram recolhidas pelos agentes.", correta: true, explicacao_especifica: "Preserva a causa e emprega passiva corretamente." },
      { letra: "B", texto: "As câmeras recolheram os agentes porque registraram a fuga.", correta: false, explicacao_especifica: "Altera agente e sentido." },
      { letra: "C", texto: "Os agentes recolheram as câmeras embora elas registraram a fuga.", correta: false, explicacao_especifica: "Além de mudar o nexo, exige 'registrassem'." },
      { letra: "D", texto: "Registrando a fuga, recolheram-se os agentes pelas câmeras.", correta: false, explicacao_especifica: "Cria sentido incoerente." },
      { letra: "E", texto: "Os agentes recolheram às câmeras porque elas registraram a fuga.", correta: false, explicacao_especifica: "Há crase indevida diante de objeto direto plural sem artigo adequado." },
    ]),
  ce(41, "ortografia", "CEBRASPE", "Polícia Federal", "Escrivão", 2021, "medio",
    "Frase: 'O agente agiu com descrição ao entrevistar a vítima.'",
    "A palavra 'descrição' está empregada corretamente, pois significa reserva e prudência na conduta.", false,
    "O sentido de reserva e prudência é 'discrição'; 'descrição' é ato de descrever."),
  me(42, "ortografia", "AOCP", "Polícia Militar de Goiás", "Soldado", 2024, "facil",
    "Assinale a alternativa correta quanto ao uso de 'por que', 'porque', 'por quê' e 'porquê'.",
    "Em pergunta direta, usa-se 'por que' separado e sem acento quando não está no fim da frase.", [
      { letra: "A", texto: "Por que a equipe interrompeu a perseguição?", correta: true, explicacao_especifica: "Trata-se de pergunta direta inicial." },
      { letra: "B", texto: "Porque a equipe interrompeu a perseguição?", correta: false, explicacao_especifica: "'Porque' introduz resposta/causa, não pergunta direta." },
      { letra: "C", texto: "A equipe interrompeu a perseguição por que?", correta: false, explicacao_especifica: "No fim, o correto é 'por quê'." },
      { letra: "D", texto: "Não foi informado o por que da interrupção.", correta: false, explicacao_especifica: "Com valor substantivo, usa-se 'o porquê'." },
      { letra: "E", texto: "A equipe retornou por quê recebeu ordem.", correta: false, explicacao_especifica: "Em resposta causal, usa-se 'porque'." },
    ]),
  ce(43, "interpretacao", "FGV", "Polícia Civil do Paraná", "Papiloscopista", 2023, "dificil",
    "Trecho: 'A ausência de vestígios visíveis não autoriza concluir, de imediato, que o local não foi violado.'",
    "O texto rejeita uma conclusão apressada baseada apenas naquilo que é perceptível visualmente.", true,
    "A expressão 'não autoriza concluir, de imediato' critica inferência precipitada fundada na falta de vestígios visíveis."),
  me(44, "interpretacao", "CEBRASPE", "Polícia Penal Federal", "Agente Federal", 2024, "medio",
    "Manual de procedimentos: 'Toda revista deve ser registrada, inclusive quando nada for encontrado, pois a ausência de apreensão também informa sobre a regularidade do procedimento.'",
    "Segundo o texto, o registro de revista sem apreensão é necessário porque:",
    "O manual atribui valor informativo à ausência de apreensão, relacionada à regularidade procedimental.", [
      { letra: "A", texto: "a inexistência de apreensão também é dado relevante do procedimento", correta: true, explicacao_especifica: "Reproduz a justificativa do texto." },
      { letra: "B", texto: "revistas sem apreensão devem ser apagadas do sistema", correta: false, explicacao_especifica: "Contraria a obrigação de registro." },
      { letra: "C", texto: "somente revistas com apreensão têm valor administrativo", correta: false, explicacao_especifica: "O texto afirma o oposto." },
      { letra: "D", texto: "a regularidade dispensa documentação", correta: false, explicacao_especifica: "A documentação é exigida justamente para demonstrar regularidade." },
      { letra: "E", texto: "o registro deve ocorrer apenas se houver suspeita de falta disciplinar", correta: false, explicacao_especifica: "O manual fala em toda revista." },
    ]),
  ce(45, "regencia_crase", "VUNESP", "PC-SP", "Delegado", 2022, "medio",
    "Frase: 'O delegado assistiu à reprodução simulada dos fatos.'",
    "No sentido de presenciar, o verbo 'assistir' rege preposição 'a', justificando a crase antes de expressão feminina determinada.", true,
    "Assistir a algo, quando significa ver/presenciar; 'reprodução' admite artigo feminino."),
  me(46, "regencia_crase", "FCC", "Polícia Militar do Amazonas", "Oficial", 2023, "medio",
    "Assinale a frase em que a crase é facultativa.",
    "Antes de pronome possessivo feminino singular, com substantivo elíptico ou expresso, a crase pode ser facultativa em muitos contextos: a/à sua equipe.", [
      { letra: "A", texto: "O comandante entregou a escala a sua equipe.", correta: true, explicacao_especifica: "Poderia ser 'à sua equipe', por se tratar de possessivo feminino singular." },
      { letra: "B", texto: "A viatura retornou à garagem central.", correta: false, explicacao_especifica: "Crase obrigatória." },
      { letra: "C", texto: "Os agentes começaram a correr.", correta: false, explicacao_especifica: "Crase proibida antes de verbo." },
      { letra: "D", texto: "A ordem foi dada a homens armados.", correta: false, explicacao_especifica: "Não há artigo feminino." },
      { letra: "E", texto: "O preso permaneceu frente a frente com o defensor.", correta: false, explicacao_especifica: "Expressão com palavras repetidas não recebe crase." },
    ]),
  ce(47, "concordancia", "FGV", "Polícia Civil do Rio Grande do Sul", "Inspetor", 2024, "medio",
    "Frase: 'Existiam indícios suficientes para a representação cautelar.'",
    "A forma plural 'Existiam' está correta, pois o verbo 'existir' concorda com o sujeito 'indícios suficientes'.", true,
    "Diferentemente de 'haver' existencial, 'existir' é verbo pessoal e concorda com o sujeito."),
  me(48, "concordancia", "CEBRASPE", "Polícia Rodoviária Federal", "Policial Rodoviário Federal", 2024, "dificil",
    "Assinale a frase correta segundo a norma-padrão.",
    "A passiva sintética exige concordância com sujeito paciente plural.", [
      { letra: "A", texto: "Fiscalizaram-se os documentos dos passageiros.", correta: true, explicacao_especifica: "'Os documentos' é sujeito paciente plural." },
      { letra: "B", texto: "Fiscalizou-se os documentos dos passageiros.", correta: false, explicacao_especifica: "Na passiva sintética, o verbo deve ir ao plural." },
      { letra: "C", texto: "Precisam-se de novos coletes no posto.", correta: false, explicacao_especifica: "Com verbo transitivo indireto, o 'se' indetermina o sujeito e o verbo fica no singular." },
      { letra: "D", texto: "Houveram abordagens durante a noite.", correta: false, explicacao_especifica: "'Haver' existencial é impessoal." },
      { letra: "E", texto: "Fazem meses desde a última capacitação.", correta: false, explicacao_especifica: "'Fazer' temporal é impessoal." },
    ]),
  ce(49, "pontuacao", "IBFC", "Polícia Penal de Minas Gerais", "Policial Penal", 2022, "medio",
    "Frase: 'A cela que passou por manutenção será reaberta amanhã.'",
    "A ausência de vírgulas indica que apenas determinada cela, entre outras possíveis, passou por manutenção e será reaberta.", true,
    "A oração adjetiva restritiva delimita o referente 'cela'."),
  me(50, "pontuacao", "FGV", "Polícia Civil de Sergipe", "Agente", 2023, "medio",
    "Assinale a frase pontuada corretamente.",
    "O vocativo deve ser isolado por vírgula; não se separa verbo de complemento.", [
      { letra: "A", texto: "Senhor perito, encaminhe o material ao laboratório ainda hoje.", correta: true, explicacao_especifica: "O vocativo 'Senhor perito' está corretamente isolado." },
      { letra: "B", texto: "Senhor perito encaminhe, o material ao laboratório ainda hoje.", correta: false, explicacao_especifica: "Falta vírgula do vocativo e há separação indevida entre verbo e objeto." },
      { letra: "C", texto: "Senhor, perito encaminhe o material ao laboratório ainda hoje.", correta: false, explicacao_especifica: "Divide indevidamente a forma de tratamento." },
      { letra: "D", texto: "Senhor perito encaminhe o material, ao laboratório ainda hoje.", correta: false, explicacao_especifica: "Falta isolamento do vocativo e há vírgula desnecessária." },
      { letra: "E", texto: "Senhor perito, encaminhe, o material ao laboratório ainda hoje.", correta: false, explicacao_especifica: "Separa verbo e complemento." },
    ]),
  ce(51, "morfologia", "VUNESP", "PC-SP", "Investigador", 2024, "dificil",
    "Frase: 'A ordem era que ninguém deixasse o prédio sem identificação.'",
    "O vocábulo 'que' introduz oração subordinada substantiva predicativa, ligada ao sujeito 'A ordem'.", true,
    "A oração após o verbo de ligação 'era' funciona como predicativo do sujeito."),
  me(52, "morfologia", "CEBRASPE", "Polícia Federal", "Agente Administrativo", 2023, "medio",
    "Em qual alternativa o 'se' tem valor de índice de indeterminação do sujeito?",
    "Com verbo transitivo indireto ('tratar de'), o 'se' não forma passiva; indetermina o sujeito.", [
      { letra: "A", texto: "Tratou-se de tema sigiloso na reunião.", correta: true, explicacao_especifica: "Não há sujeito paciente; o sujeito é indeterminado." },
      { letra: "B", texto: "Apreenderam-se armas na operação.", correta: false, explicacao_especifica: "Partícula apassivadora; 'armas' é sujeito paciente." },
      { letra: "C", texto: "O agente feriu-se durante a perseguição.", correta: false, explicacao_especifica: "Pronome reflexivo." },
      { letra: "D", texto: "Se chover, a barreira será transferida.", correta: false, explicacao_especifica: "Conjunção condicional." },
      { letra: "E", texto: "Os policiais cumprimentaram-se no pátio.", correta: false, explicacao_especifica: "Valor recíproco." },
    ]),
  ce(53, "sintaxe", "AOCP", "Polícia Militar do Paraná", "Soldado", 2022, "medio",
    "Frase: 'O comandante necessita de que os relatórios sejam enviados até as 18 horas.'",
    "A oração 'de que os relatórios sejam enviados até as 18 horas' completa o sentido de 'necessita' e exerce função de objeto indireto oracional.", true,
    "O verbo 'necessitar' rege preposição 'de'; a oração introduzida por 'de que' funciona como complemento verbal indireto."),
  me(54, "sintaxe", "FGV", "Polícia Civil do Ceará", "Delegado", 2024, "dificil",
    "Assinale a frase em que a reescritura mantém a correção gramatical.",
    "A forma 'de cujo' respeita a regência de 'precisar de' e a relação de posse com 'imagens'.", [
      { letra: "A", texto: "O prédio de cujas imagens a perícia precisava foi isolado.", correta: true, explicacao_especifica: "'Precisava de imagens do prédio' justifica 'de cujas imagens'." },
      { letra: "B", texto: "O prédio cujas imagens a perícia precisava foi isolado.", correta: false, explicacao_especifica: "Falta a preposição exigida por 'precisar'." },
      { letra: "C", texto: "O prédio que as imagens a perícia precisava foi isolado.", correta: false, explicacao_especifica: "Construção sintaticamente truncada." },
      { letra: "D", texto: "O prédio onde as imagens a perícia precisava foi isolado.", correta: false, explicacao_especifica: "'Onde' não estabelece a relação de posse nem supre a regência." },
      { letra: "E", texto: "O prédio aonde as imagens a perícia precisava foi isolado.", correta: false, explicacao_especifica: "'Aonde' é inadequado e não atende à regência." },
    ]),
  ce(55, "ortografia", "FCC", "Polícia Militar de Pernambuco", "Soldado", 2023, "facil",
    "Frase: 'A sessão de treinamento sobre abordagem ocorrerá no auditório.'",
    "A palavra 'sessão' está corretamente empregada para indicar reunião ou período de atividade.", true,
    "'Sessão' é reunião/tempo de atividade; 'seção' é divisão; 'cessão' é ato de ceder."),
  me(56, "ortografia", "VUNESP", "Guarda Civil Municipal de São José dos Campos", "Guarda Civil", 2024, "medio",
    "Assinale a alternativa em que o par de palavras está corretamente empregado no contexto policial.",
    "'Ratificar' significa confirmar; 'retificar' significa corrigir.", [
      { letra: "A", texto: "O delegado ratificou a prisão após analisar o auto; depois, mandou retificar um erro de digitação.", correta: true, explicacao_especifica: "Os dois verbos foram empregados com sentido adequado." },
      { letra: "B", texto: "O delegado retificou a prisão, confirmando-a integralmente.", correta: false, explicacao_especifica: "Para confirmar, o adequado é 'ratificou'." },
      { letra: "C", texto: "A escrivã ratificou o número errado, corrigindo-o no sistema.", correta: false, explicacao_especifica: "Para corrigir, usa-se 'retificou'." },
      { letra: "D", texto: "O perito fragranteou o delito no laudo.", correta: false, explicacao_especifica: "Forma inexistente e confusão com 'flagrante'." },
      { letra: "E", texto: "O comandante cassou a viatura no pátio.", correta: false, explicacao_especifica: "'Caçar' seria procurar; 'cassar' é anular direitos/atos." },
    ]),
  ce(57, "interpretacao", "CEBRASPE", "Polícia Civil do Distrito Federal", "Agente", 2024, "medio",
    "Trecho: 'O protocolo não pretende engessar a atuação policial; busca, antes, reduzir improvisos em situações recorrentes.'",
    "A expressão 'antes' introduz retificação argumentativa: o texto afasta uma interpretação negativa e apresenta a finalidade do protocolo.", true,
    "O trecho nega que o protocolo engesse a atuação e corrige a leitura ao indicar objetivo de padronização racional."),
  me(58, "regencia_crase", "IBFC", "Polícia Militar de Minas Gerais", "Soldado", 2024, "medio",
    "Assinale a alternativa em que a crase foi empregada corretamente.",
    "A locução adverbial feminina 'à noite' recebe acento grave por tradição normativa.", [
      { letra: "A", texto: "A patrulha intensificou as rondas à noite.", correta: true, explicacao_especifica: "Locução adverbial feminina com crase." },
      { letra: "B", texto: "A patrulha começou à monitorar a praça.", correta: false, explicacao_especifica: "Crase proibida antes de verbo." },
      { letra: "C", texto: "Os agentes chegaram à pé ao local.", correta: false, explicacao_especifica: "Não há artigo feminino em 'pé'." },
      { letra: "D", texto: "O informe foi enviado à todos os postos.", correta: false, explicacao_especifica: "Crase proibida antes de pronome indefinido masculino/plural sem artigo feminino." },
      { letra: "E", texto: "A ordem foi entregue à cada equipe.", correta: false, explicacao_especifica: "Crase proibida antes de 'cada'." },
    ]),
  ce(59, "concordancia", "FCC", "Polícia Científica de Santa Catarina", "Perito Criminal", 2022, "medio",
    "Frase: 'Mais de um agente participou da reconstituição.'",
    "A forma verbal no singular está correta, embora a expressão indique, semanticamente, quantidade superior a um.", true,
    "Com 'mais de um', em regra, o verbo concorda no singular, salvo ideia de reciprocidade ou repetição."),
  me(60, "pontuacao", "CEBRASPE", "Polícia Federal", "Agente de Polícia Federal", 2024, "medio",
    "Considere a frase: 'Depois da apreensão o material foi lacrado e encaminhado ao depósito judicial.'",
    "Assinale a reescrita com pontuação adequada e sem alteração de sentido.",
    "A vírgula após o adjunto adverbial deslocado organiza o período sem separar termos essenciais.", [
      { letra: "A", texto: "Depois da apreensão, o material foi lacrado e encaminhado ao depósito judicial.", correta: true, explicacao_especifica: "Pontua corretamente o adjunto adverbial inicial." },
      { letra: "B", texto: "Depois, da apreensão o material foi lacrado e encaminhado ao depósito judicial.", correta: false, explicacao_especifica: "Separa indevidamente elementos do adjunto." },
      { letra: "C", texto: "Depois da apreensão o material, foi lacrado e encaminhado ao depósito judicial.", correta: false, explicacao_especifica: "Separa sujeito e locução verbal." },
      { letra: "D", texto: "Depois da apreensão, o material foi lacrado, e, encaminhado ao depósito judicial.", correta: false, explicacao_especifica: "Vírgulas fragmentam indevidamente a coordenação." },
      { letra: "E", texto: "Depois da apreensão o material foi, lacrado e encaminhado, ao depósito judicial.", correta: false, explicacao_especifica: "Separa verbo de predicativo/complemento de modo inadequado." },
    ]),
];
