import { TAXONOMIA } from "./taxonomia.mjs";

export const adm02Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "adm-02-001",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Durante perseguição policial ostensiva a assaltantes armados em via pública de tráfego intenso, a viatura da Polícia Militar colide acidentalmente com um veículo de particular estacionado regularmente na calçada. Nessa situação, consoante a teoria do risco administrativo acolhida pela Constituição Federal de 1988, o Estado responde de forma objetiva pelos danos materiais causados ao proprietário do veículo atingido, cabendo ação regressiva contra os policiais condutores unicamente se comprovado dolo ou culpa.",
    explicacao: "GABARITO: CERTO. Aplica-se a responsabilidade civil objetiva do Estado (art. 37, § 6º, CF/88) fundada na teoria do risco administrativo, que dispensa a prova de culpa da administração para a reparação do dano ao terceiro prejudicado. Já o direito de regresso contra o servidor público depende necessariamente da comprovação de que ele agiu com dolo ou culpa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-002",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Com as alterações promovidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa (Lei nº 8.429/1992), passou-se a exigir a presença do elemento subjetivo dolo específico para a caracterização de qualquer ato de improbidade administrativa, tendo sido revogadas as modalidades culposas.",
    explicacao: "GABARITO: CERTO. Art. 1º, §§ 1º e 2º, da Lei nº 8.429/1992 (redação da Lei nº 14.230/2021): Consideram-se atos de improbidade administrativa as condutas dolosas tipificadas nos artigos 9º, 10 e 11, exigindo-se o dolo específico (vontade livre e consciente de alcançar o resultado ilícito). Foi extinta a improbidade culposa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-003",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme tese fixada pelo STF no Tema 940 de Repercussão Geral (RE 1.027.633), a ação de indenização por dano causado por agente público deve ser proposta diretamente contra a pessoa jurídica de direito público ou a prestadora de serviço público, sendo vedada a inclusão direta do agente público no polo passivo.",
    explicacao: "GABARITO: CERTO. STF, Tema 940: 'A teor do disposto no art. 37, § 6º, da Constituição Federal, a ação por danos causados por agente público deve ser ajuizada contra o Estado ou a pessoa jurídica de direito privado prestadora de serviço público, sendo parte ilegítima para a ação o autor do ato, assegurado o direito de regresso contra o responsável nos casos de dolo ou culpa' (Teoria da Dupla Garantia).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-004",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A legitimidade ativa para propor a ação de improbidade administrativa cabe privativamente ao Ministério Público, nos termos da Lei nº 8.429/1992, com as alterações da Lei nº 14.230/2021 e do julgamento da ADI 7042 pelo STF, que admitiu também a legitimidade concorrente da pessoa jurídica interessada.",
    explicacao: "GABARITO: CERTO. Na ADI 7042 e ADI 7043, o STF declarou a inconstitucionalidade parcial da exclusividade do MP, assentando a legitimidade concorrente e disjuntiva entre o Ministério Público e a pessoa jurídica interessada prejudicada para a propositura da ação de improbidade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-005",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A teoria do risco administrativo adota a responsabilidade objetiva do Estado, mas admite a exclusão ou atenuação da responsabilidade estatal quando comprovada culpa exclusiva ou concorrente da vítima, caso fortuito ou força maior.",
    explicacao: "GABARITO: CERTO. Ao contrário da teoria do risco integral (que não admite excludentes), a teoria do risco administrativo admite causas excludentes do nexo causal (culpa exclusiva da vítima, fato exclusivo de terceiro, caso fortuito e força maior) e atenuantes (culpa concorrente).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-006",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O prazo prescricional para ajuizamento da ação de improbidade administrativa é de 8 (oito) anos, contados a partir da ocorrência do fato ou, no caso de infrações permanentes, do dia em que tiver cessado a permanência, admitindo-se a prescrição intercorrente no prazo de 4 (quatro) anos.",
    explicacao: "GABARITO: CERTO. Art. 23 da Lei nº 8.429/1992 (redação da Lei nº 14.230/2021): A ação para a aplicação das sanções prescreve em 8 anos, contados a partir da ocorrência do fato ou da cessação da permanência, com previsão de prescrição intercorrente de 4 anos entre os marcos interruptivos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-007",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Estado responde objetivamente pelos danos causados por atos lícitos praticados por seus agentes, desde que causem dano anormal e específico a determinado indivíduo em benefício de toda a coletividade.",
    explicacao: "GABARITO: CERTO. A responsabilidade do Estado incide tanto sobre condutas ilícitas quanto lícitas, desde que da conduta lícita resulte prejuízo especial e anormal que imponha sacrifício desproporcional a um cidadão em prol da coletividade (princípio da isonomia na repartição dos encargos públicos).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-02-008",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O mero exercício da função pública ou desempenho de competências públicas, sem comprovação de ato doloso com fim ilícito, afasta a responsabilidade por ato de improbidade administrativa.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 3º, da Lei nº 8.429/1992 (redação da Lei nº 14.230/2021): 'O mero exercício da função ou desempenho de competências públicas, sem comprovação de ato doloso com fim ilícito, afasta a responsabilidade por ato de improbidade administrativa'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "adm-02-009",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.429/1992 (com alterações da Lei nº 14.230/2021), constitui ato de improbidade administrativa que importa em ENRIQUECIMENTO ILÍCITO (art. 9º):",
    explicacao: "GABARITO: A. Art. 9º, I, da Lei 8.429/1992: Constitui ato de improbidade administrativa importando em enriquecimento ilícito auferir qualquer tipo de vantagem patrimonial indevida em razão do exercício de cargo, mandato, função, emprego ou atividade, notadamente: I - receber, para si ou para outrem, dinheiro, bem móvel ou imóvel, ou qualquer outra vantagem econômica, direta ou indireta, a título de comissão, percentagem, gratificação ou presente de quem tenha interesse que possa ser atingido por ação ou omissão decorrente das atribuições do agente público.",
    alternativas: [
      { texto: "receber, para si ou para outrem, dinheiro ou vantagem econômica a título de propina, comissão ou presente de interessado em ato do agente.", correta: true },
      { texto: "frustrar a licitude de processo licitatório sem auferir vantagem pessoal.", correta: false },
      { texto: "deixar de prestar contas de recursos quando impossibilitado por motivo de força maior.", correta: false },
      { texto: "celebrar termo de parceria com entidade privada sem dolo de desvio.", correta: false },
      { texto: "negar publicidade aos atos oficiais por falha técnica no portal da transparência.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-010",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em matéria de responsabilidade civil do Estado por danos decorrentes de disparos de arma de fogo durante operações policiais em comunidades urbanas (tiroteios), o STF (Tema 1.237 / RE 1.368.672) fixou a tese de que:",
    explicacao: "GABARITO: B. STF, Tema 1.237: O Estado é responsável, na esfera cível, por morte ou ferimento decorrente de operações de segurança pública, mesmo na hipótese de a perícia ser inconclusiva sobre a origem do disparo fatal, cabendo ao Poder Público demonstrar causa excludente de responsabilidade.",
    alternativas: [
      { texto: "o Estado só responde se houver confissão do policial ou perícia de balística conclusiva apontando a arma estatal.", correta: false },
      { texto: "o Estado responde objetivamente pela morte ou ferimento de vítima decorrente de operação de segurança pública, mesmo quando a perícia sobre a origem do disparo for inconclusiva, incumbindo ao Poder Público demonstrar causa excludente de nexo causal.", correta: true },
      { texto: "a responsabilidade do Estado é sempre subjetiva e depende de prévia condenação criminal do comandante da tropa.", correta: false },
      { texto: "a responsabilidade recai exclusivamente sobre a associação de moradores da localidade.", correta: false },
      { texto: "aplica-se a teoria da irresponsabilidade estatal para operações em áreas conflagradas.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-011",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O terceiro que não é agente público, mas induz ou concorre dolosamente para a prática de ato de improbidade administrativa:",
    explicacao: "GABARITO: C. Art. 3º da Lei nº 8.429/1992 (redação da Lei nº 14.230/2021): As disposições desta Lei são aplicáveis, no que couber, àquele que, mesmo não sendo agente público, induza ou concorra dolosamente para a prática do ato de improbidade.",
    alternativas: [
      { texto: "não pode ser responsabilizado pela Lei de Improbidade em nenhuma hipótese.", correta: false },
      { texto: "responde apenas criminalmente, ficando isento de sanções patrimoniais.", correta: false },
      { texto: "está sujeito às sanções da Lei de Improbidade no que couber.", correta: true },
      { texto: "responde apenas se for parente consanguíneo do prefeito municipal.", correta: false },
      { texto: "fica sujeito apenas a advertência confidencial.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-012",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação à morte de detento sob custódia estatal em estabelecimento prisional, a jurisprudência do STF (Tema 592 de Repercussão Geral) consolidou que o Estado:",
    explicacao: "GABARITO: D. STF, Tema 592 (RE 841.526): Em caso de morte de detento, a responsabilidade do Estado é objetiva em virtude do dever específico de proteção (art. 5º, XLIX, da CF/88), cabendo ao Estado o ônus de comprovar que a morte decorreu de causa que não poderia ter sido evitada (rompimento do nexo causal).",
    alternativas: [
      { texto: "nunca responde, por se tratar de ambiente de alto risco assumido pelo condenado.", correta: false },
      { texto: "responde apenas na hipótese de culpa comprovada do diretor da penitenciária.", correta: false },
      { texto: "responde subjetivamente exigindo prova de omissão dolosa dos agentes de plantão.", correta: false },
      { texto: "responde objetivamente em razão do dever específico de proteção da integridade física e moral dos presos, salvo se provar que a morte decorreu de fato inevitável alheio ao dever de custódia.", correta: true },
      { texto: "isenta-se de indenização se o preso cometeu crime hediondo.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-013",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Entre as sanções cominadas na Lei de Improbidade Administrativa (art. 12 da Lei nº 8.429/1992, com redação da Lei nº 14.230/2021) para o agente condenado por ato de improbidade que causa PREJUÍZO AO ERÁRIO (art. 10), incluem-se:",
    explicacao: "GABARITO: E. Art. 12, II, da Lei 8.429/1992: Perda dos bens ou valores acrescidos ilicitamente, perda da função pública, suspensão dos direitos políticos até 12 anos, pagamento de multa civil equivalente ao valor do dano e proibição de contratar com o poder público ou receber benefícios fiscais até 12 anos.",
    alternativas: [
      { texto: "pena de reclusão de 4 a 12 anos em regime fechado.", correta: false },
      { texto: "prisão administrativa preventiva sem fiança.", correta: false },
      { texto: "perda definitiva de direitos civis fundamentais.", correta: false },
      { texto: "cassação imediata de passaporte e CNH por ato ministerial.", correta: false },
      { texto: "perda dos bens havidos ilicitamente, ressarcimento integral do dano, perda da função pública, suspensão dos direitos políticos até 12 anos e multa civil.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "adm-02-014",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A teoria adotada no Brasil como regra geral para a responsabilidade civil extracontratual do Estado por condutas comissivas de seus agentes é a Teoria:",
    explicacao: "GABARITO: A. No ordenamento brasileiro, o art. 37, § 6º, da CF/88 consagra a Teoria do Risco Administrativo (responsabilidade civil objetiva, independente de culpa, admitindo excludentes).",
    alternativas: [
      { texto: "do Risco Administrativo (responsabilidade objetiva).", correta: true },
      { texto: "da Culpa Civilística Privada.", correta: false },
      { texto: "da Irresponsabilidade Soberana do Estado.", correta: false },
      { texto: "do Risco Integral absoluto para todos os casos.", correta: false },
      { texto: "da Responsabilidade Subjetiva Pura com inversão do ônus probatório.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-015",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 8.429/1992 (com alterações da Lei nº 14.230/2021), a perda da função pública decorrente de condenação por ato de improbidade:",
    explicacao: "GABARITO: B. Art. 12, § 1º, da Lei 8.429/1992: A sanção de perda da função pública atinge apenas o vínculo de mesma qualidade e natureza que o agente público detinha com o poder público na época do cometimento da infração, podendo o magistrado, em caráter excepcional, estendê-la a outro vínculo considerando a gravidade do fato.",
    alternativas: [
      { texto: "é automática e ocorre no momento do recebimento da petição inicial.", correta: false },
      { texto: "atinge apenas o vínculo de mesma qualidade e natureza que o agente detinha com o poder público na época do cometimento da infração, ressalvada extensão judicial excepcional.", correta: true },
      { texto: "impede o cidadão de prestar novos concursos públicos para o resto da vida.", correta: false },
      { texto: "depende de homologação prévia do Tribunal de Contas da União.", correta: false },
      { texto: "não se aplica aos ocupantes de cargos efetivos estáveis.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-016",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em caso de omissão genérica do Estado (ex.: furto praticado por criminoso em via pública sem atuação direta da autoridade), a responsabilidade civil do Estado:",
    explicacao: "GABARITO: C. A jurisprudência do STJ e do STF distingue omissão específica (responsabilidade objetiva por quebra de dever específico de custódia) de omissão genérica (responsabilidade subjetiva fundada na teoria da falta do serviço / faute du service, que exige demonstração de culpa da administração).",
    alternativas: [
      { texto: "é sempre objetiva pelo risco integral.", correta: false },
      { texto: "inexiste em qualquer situação fática.", correta: false },
      { texto: "é subjetiva, exigindo a comprovação da falta do serviço (faute du service) decorrente de culpa ou negligência da Administração.", correta: true },
      { texto: "acarreta a demissão sumária do Secretário de Segurança.", correta: false },
      { texto: "transfere-se integralmente para a empresa fabricante do veículo furtado.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "adm-02-017",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.429/1992, o rol dos atos de improbidade administrativa que atentam contra os princípios da administração pública (art. 11), após as alterações da Lei nº 14.230/2021, passou a ter caráter:",
    explicacao: "GABARITO: D. Art. 11, caput e incisos, da Lei 8.429/1992 (redação da Lei 14.230/2021): O rol do art. 11 tornou-se taxativo (numerus clausus), punindo-se apenas as condutas dolosas expressamente tipificadas nos seus incisos.",
    alternativas: [
      { texto: "meramente exemplificativo (numerus apertus).", correta: false },
      { texto: "orientativo sem força normativa vinculante.", correta: false },
      { texto: "subsidiário ao Código Civil.", correta: false },
      { texto: "taxativo (numerus clausus), punindo apenas as condutas dolosas expressamente descritas em seus incisos.", correta: true },
      { texto: "inconstitucional por afronta à separação de poderes.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-018",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Na ação de regresso movida pelo Estado contra o policial que causou dano a terceiro durante perseguição veicular, a responsabilidade do agente perante a Administração:",
    explicacao: "GABARITO: A. Art. 37, § 6º, da CF/88: A responsabilidade do Estado perante a vítima é objetiva; mas a responsabilidade do agente público em ação regressiva é SUBJETIVA, exigindo demonstração de dolo ou culpa.",
    alternativas: [
      { texto: "é subjetiva, dependendo da comprovação de dolo ou culpa do servidor.", correta: true },
      { texto: "é objetiva, prescindindo de comprovação de culpa.", correta: false },
      { texto: "é solidária de primeiro grau com o particular lesado.", correta: false },
      { texto: "é presumida pelo simples fato de ser funcionário público.", correta: false },
      { texto: "está extinta se o servidor pedir exoneração do cargo.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "adm-02-019",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "É admitida a celebração de Acordo de Não Persecução Civil (ANPC) nas ações de improbidade administrativa? Assinale a alternativa correta segundo a Lei nº 8.429/1992:",
    explicacao: "GABARITO: B. Art. 17-B da Lei nº 8.429/1992 (redação da Lei nº 14.230/2021): O acordo de não persecução civil (ANPC) poderá ser celebrado no curso da investigação ou da ação de improbidade, prevendo o ressarcimento integral do dano e a perda das vantagens auferidas.",
    alternativas: [
      { texto: "Não, a lei veda expressamente qualquer tipo de transação ou acordo em improbidade.", correta: false },
      { texto: "Sim, é permitida a celebração de acordo de não persecução civil nos termos do art. 17-B da lei.", correta: true },
      { texto: "Apenas se o réu for primário e menor de 21 anos.", correta: false },
      { texto: "Apenas se o valor do dano for inferior a um salário mínimo.", correta: false },
      { texto: "Somente após o trânsito em julgado de sentença condenatória.", correta: false },
    ],
  },
  {
    idSlug: "adm-02-020",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quando a vítima concorre para o evento danoso juntamente com o agente do Estado (culpa concorrente):",
    explicacao: "GABARITO: C. Na hipótese de culpa concorrente da vítima, a responsabilidade do Estado não é totalmente excluída, mas a indenização devida pelo Poder Público é atenuada (reduzida proporcionalmente ao grau de culpa da vítima).",
    alternativas: [
      { texto: "a obrigação de indenizar do Estado é completamente extinta.", correta: false },
      { texto: "o Estado responde pelo valor da indenização em dobro.", correta: false },
      { texto: "a indenização é atenuada/reduzida proporcionalmente à parcela de culpa da vítima.", correta: true },
      { texto: "a vítima perde o direito de recorrer ao Poder Judiciário.", correta: false },
      { texto: "o agente público deve pagar a indenização do próprio bolso imediatamente sem ação de regresso.", correta: false },
    ],
  },
];
