import { TAXONOMIA } from "./taxonomia.mjs";

export const penal01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b10-pen-01-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Em relação ao tempo do crime, o Código Penal brasileiro adotou a teoria da ubiquidade, segundo a qual considera-se praticado o crime tanto no momento da ação ou da omissão quanto no momento da produção do resultado.",
    explicacao: "GABARITO: ERRADO. Quanto ao tempo do crime, o Código Penal adotou a teoria da atividade (art. 4º do CP: 'Considera-se praticado o crime no momento da ação ou omissão, ainda que outro seja o momento do resultado'). A teoria da ubiquidade (ou mista) foi adotada para o lugar do crime (art. 6º do CP).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-01-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Aplica-se a lei brasileira ao crime cometido no exterior contra a administração pública por quem está a seu serviço, ainda que o agente tenha sido absolvido ou condenado no estrangeiro, em hipótese de extraterritorialidade incondicionada.",
    explicacao: "GABARITO: CERTO. Art. 7º, I, 'c' e § 1º, do Código Penal. Os crimes praticados contra a administração pública por quem está a seu serviço submetem-se ao princípio da extraterritorialidade incondicionada, sendo punidos pela lei brasileira mesmo que absolvido ou condenado no exterior.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No erro sobre a pessoa (error in persona), não se consideram as condições ou qualidades da vítima real atingida, mas sim as da pessoa contra quem o agente pretendia praticar o crime, aplicando-se a teoria da equivalência para fins de fixação de pena e incidência de agravantes ou atenuantes.",
    explicacao: "GABARITO: CERTO. Art. 20, § 3º, do Código Penal: 'O erro quanto à pessoa contra a qual o crime é praticado não isenta de pena. Não se consideram, neste caso, as condições ou qualidades da vítima, senão as da pessoa contra quem o agente queria praticar o crime'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na cooperação dolosamente distinta, se algum dos concorrentes quis participar de crime menos grave, ser-lhe-á aplicada a pena deste; essa pena será aumentada até a metade, na hipótese de ter sido previsível o resultado mais grave.",
    explicacao: "GABARITO: CERTO. Art. 29, § 2º, do CP: 'Se algum dos concorrentes quis participar de crime menos grave, ser-lhe-á aplicada a pena deste; essa pena será aumentada até metade, na hipótese de ter sido previsível o resultado mais grave'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O agente que, voluntariamente, desiste de prosseguir na execução ou impede que o resultado se produza, responde por tentativa com redução obrigatória de um a dois terços da pena do crime pretendido.",
    explicacao: "GABARITO: ERRADO. Na desistência voluntária e no arrependimento eficaz (art. 15 do CP), o agente NÃO responde por tentativa do crime pretendido, mas somente pelos atos já praticados ('só responde pelos atos já praticados'). A tentativa é excluída (ponte de ouro).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-01-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços, configurando o arrependimento posterior.",
    explicacao: "GABARITO: CERTO. Art. 16 do Código Penal: 'Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até o recebimento da denúncia ou da queixa, por ato voluntário do agente, a pena será reduzida de um a dois terços'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A superveniência de causa relativamente independente exclui a imputação quando, por si só, produziu o resultado; imputam-se, contudo, os fatos anteriores, a quem os praticou.",
    explicacao: "GABARITO: CERTO. Art. 13, § 1º, do Código Penal: 'A superveniência de causa relativamente independente exclui a imputação quando, por si só, produziu o resultado; imputam-se, porém, os fatos anteriores, a quem os praticou'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O estado de necessidade putativo ocorre quando o agente supõe erroneamente a existência de situação de perigo iminente que, se existisse de fato, tornaria sua ação legítima.",
    explicacao: "GABARITO: CERTO. As descriminantes putativas (art. 20, § 1º, do CP) compreendem situações em que o indivíduo, por erro plenamente justificado pelas circunstâncias, supõe situação de fato que, se existisse, tornaria a ação legítima, como no estado de necessidade putativo ou legítima defesa putativa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No concurso formal heterogêneo de crimes, quando a ação resulta em dois crimes dolosos idênticos praticados com desígnios autônomos, aplica-se o sistema da exasperação da pena com aumento de um sexto até metade.",
    explicacao: "GABARITO: ERRADO. Art. 70, caput, segunda parte, do CP: Se a ação decorre de desígnios autônomos (concurso formal impróprio ou imperfeito), as penas aplicam-se CUMULATIVAMENTE (cúmulo material), e não por exasperação.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-01-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A coação moral irresistível e a obediência hierárquica a ordem não manifestamente ilegal são causas excludentes da ilicitude previstas expressamente na parte geral do Código Penal.",
    explicacao: "GABARITO: ERRADO. A coação moral irresistível e a estrita obediência a ordem não manifestamente ilegal (art. 22 do CP) são causas de exclusão da CULPABILIDADE (por inexigibilidade de conduta diversa), e não de exclusão da ilicitude. A ilicitude é excluída pelo art. 23 (estado de necessidade, legítima defesa, estrito cumprimento de dever legal e exercício regular de direito).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },

  // 11-20. FGV / VUNESP / FCC (Múltipla Escolha)
  {
    idSlug: "b10-pen-01-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Marcos, policial civil, durante abordagem a um indivíduo foragido da justiça em via pública, é surpreendido por disparos de arma de fogo efetuados pelo suspeito. Para defender sua vida e a de transeuntes, Marcos efetua disparos de retorno, atingindo o agressor e cessando o ataque. Nesse caso, a conduta de Marcos está amparada por:",
    explicacao: "GABARITO: D. Trata-se de típica legítima defesa (art. 23, II, e art. 25 do Código Penal e art. 25, parágrafo único, incluído pela Lei 13.964/2019, que expressamente abrange a atuação de agentes de segurança pública para repelir agressão ou risco de agressão a vítima mantida refém ou em legítima defesa própria e de terceiros).",
    alternativas: [
      { texto: "Estado de necessidade justificante.", correta: false },
      { texto: "Exercício regular de direito stricto sensu.", correta: false },
      { texto: "Estrito cumprimento de dever legal sem dolo.", correta: false },
      { texto: "Legítima defesa própria e de terceiros.", correta: true },
      { texto: "Inexigibilidade de conduta diversa exculpante.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com o princípio da legalidade e da anterioridade penal consagrados na Constituição Federal e no Código Penal:",
    explicacao: "GABARITO: B. Art. 1º do Código Penal e Art. 5º, XXXIX, da CF/88: 'Não há crime sem lei anterior que o defina, não há pena sem prévia cominação legal'.",
    alternativas: [
      { texto: "A lei penal posterior sempre retroage para alcançar condutas pretéritas sob medida provisória.", correta: false },
      { texto: "Não há crime sem lei anterior que o defina, nem pena sem prévia cominação legal.", correta: true },
      { texto: "A analogia in malam partem é permitida nos crimes patrimoniais graves.", correta: false },
      { texto: "O costume é fonte primária do direito penal brasileiro para cominação de sanções corporais.", correta: false },
      { texto: "A lei penal temporária não se aplica aos fatos praticados durante sua vigência após decorrido o período.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Considere a teoria tripartida do crime adotada majoritariamente pelo direito penal brasileiro. São elementos que integram a culpabilidade:",
    explicacao: "GABARITO: A. No conceito analítico tripartido (fato típico, ilícito e culpável), a culpabilidade é composta por: 1) Imputabilidade penal; 2) Potencial consciência da ilicitude; 3) Exigibilidade de conduta diversa. Dolo e culpa estão alocados na tipicidade (conduta).",
    alternativas: [
      { texto: "Imputabilidade penal, potencial consciência da ilicitude e exigibilidade de conduta diversa.", correta: true },
      { texto: "Conduta com dolo ou culpa, nexo de causalidade e resultado naturalístico.", correta: false },
      { texto: "Tipicidade formal, tipicidade conglobante e antijuridicidade material.", correta: false },
      { texto: "Estrito cumprimento de dever legal, legítima defesa e imputabilidade.", correta: false },
      { texto: "Dolo eventual, coação física irresistível e ausência de tipicidade.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quando o agente, por erro no uso dos meios de execução, atinge pessoa diversa daquela que pretendia ofender, responde como se tivesse praticado o crime contra:",
    explicacao: "GABARITO: C. Art. 73 do Código Penal (Aberratio ictus / erro na execução): 'Quando, por acidente ou erro no uso dos meios de execução, o agente, ao invés de atingir a pessoa que pretendia ofender, atinge pessoa diversa, responde como se tivesse praticado o crime contra aquela' (vítima virtual/pretendida).",
    alternativas: [
      { texto: "A pessoa efetivamente lesionada, com aplicação de circunstância atenuante obrigatória.", correta: false },
      { texto: "Ambas as pessoas em concurso material imperfeito de infrações hediondas.", correta: false },
      { texto: "A pessoa que pretendia ofender, considerando-se suas qualidades e condições pessoais.", correta: true },
      { texto: "Nenhuma das pessoas, restando a conduta desclassificada para delito exclusivamente culposo.", correta: false },
      { texto: "A vítima real, vedada a consideração dos motivos dirigidos à vítima almejada.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Não se pune a tentativa quando, por ineficácia absoluta do meio ou por absoluta impropriedade do objeto, é impossível consumar-se o crime. Esse instituto é denominado pela doutrina e pelo Código Penal como:",
    explicacao: "GABARITO: E. Art. 17 do Código Penal trata expressamente do crime impossível (ou tentativa inidônea/delito putativo por obra do agente provocador).",
    alternativas: [
      { texto: "Desistência voluntária qualificada.", correta: false },
      { texto: "Arrependimento eficaz superveniente.", correta: false },
      { texto: "Arrependimento posterior com reparação.", correta: false },
      { texto: "Tentativa abandonada imperfeita.", correta: false },
      { texto: "Crime impossível.", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-01-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade. Se a participação for de menor importância, a pena pode ser:",
    explicacao: "GABARITO: B. Art. 29, § 1º, do CP: 'Se a participação for de menor importância, a pena pode ser diminuída de um sexto a um terço'.",
    alternativas: [
      { texto: "Extinta de pleno direito pelo juiz da instrução.", correta: false },
      { texto: "Diminuída de um sexto a um terço.", correta: true },
      { texto: "Reduzida da metade até dois terços.", correta: false },
      { texto: "Substituída unicamente por admoestação verbal.", correta: false },
      { texto: "Aumentada em razão da covardia moral do partícipe.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São causas extintivas da punibilidade expressamente arroladas no art. 107 do Código Penal, EXCETO:",
    explicacao: "GABARITO: D. A legítima defesa é causa de exclusão da ilicitude (art. 23, II, do CP), e não causa de extinção da punibilidade. As demais alternativas (morte do agente, anistia/graça/indulto, decadência/prescrição/perempção, renúncia/perdão) constam no rol do art. 107 do CP.",
    alternativas: [
      { texto: "Morte do agente.", correta: false },
      { texto: "Anistia, graça ou indulto.", correta: false },
      { texto: "Decadência ou perempção.", correta: false },
      { texto: "Legítima defesa própria confirmada em juízo.", correta: true },
      { texto: "Prescrição da pretensão punitiva ou executória.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre a imputabilidade penal no ordenamento jurídico brasileiro, assinale a afirmativa correta:",
    explicacao: "GABARITO: A. Art. 28, II, do CP: A embriaguez, voluntária ou culposa, pelo álcool ou por substância de efeitos análogos, NÃO exclui a imputabilidade penal, adotando-se a teoria da actio libera in causa. Somente a embriaguez completa decorrente de caso fortuito ou força maior exclui a imputabilidade (art. 28, § 1º).",
    alternativas: [
      { texto: "A embriaguez voluntária ou culposa pelo álcool não exclui a imputabilidade penal.", correta: true },
      { texto: "A emoção e a paixão excluem a imputabilidade penal nos crimes passionais.", correta: false },
      { texto: "Os menores de 18 anos são imputáveis quando comprovado desenvolvimento mental precoce.", correta: false },
      { texto: "O desenvolvimento mental incompleto sempre gera extinção da punibilidade automática.", correta: false },
      { texto: "A embriaguez proveniente de caso fortuito, mesmo incompleta, isenta totalmente de pena.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Quando o agente, mediante mais de uma ação ou omissão, pratica dois ou mais crimes da mesma espécie e, pelas condições de tempo, lugar, maneira de execução e outras semelhantes, devem os subsequentes ser havidos como continuação do primeiro, verifica-se o:",
    explicacao: "GABARITO: C. Art. 71 do Código Penal define o crime continuado (continuidade delitiva), aplicando-se a pena de um só dos crimes, se idênticas, ou a mais grave, se diversas, aumentada, em qualquer caso, de um sexto a dois terços.",
    alternativas: [
      { texto: "Concurso formal próprio.", correta: false },
      { texto: "Concurso material cumulativo.", correta: false },
      { texto: "Crime continuado.", correta: true },
      { texto: "Conflito aparente de normas integrativas.", correta: false },
      { texto: "Bis in idem sancionatório.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal de 1ª Classe",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Considera-se em estado de necessidade quem pratica o fato para salvar de perigo atual:",
    explicacao: "GABARITO: B. Art. 24 do Código Penal: 'Considera-se em estado de necessidade quem pratica o fato para salvar de perigo atual, que não provocou por sua vontade, nem podia de outro modo evitar, direito próprio ou alheio, cujo sacrifício, nas circunstâncias, não era razoável exigir-se'.",
    alternativas: [
      { texto: "Apenas direito patrimonial alheio de valor economicamente relevante.", correta: false },
      { texto: "Que não provocou por sua vontade, nem podia de outro modo evitar, direito próprio ou alheio.", correta: true },
      { texto: "Agressão injusta, atual ou iminente, perpetrada dolosamente por outrem.", correta: false },
      { texto: "Cujo sacrifício era exigível legalmente por força de dever funcional específico.", correta: false },
      { texto: "Exclusivamente a integridade física de ascendentes ou descendentes.", correta: false },
    ],
  },

  // 21-30. Módulos Avançados de Direito Penal Geral
  {
    idSlug: "b10-pen-01-021",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O erro sobre a ilicitude do fato (erro de proibição), se inevitável, isenta de pena; se evitável, poderá diminuí-la de um sexto a um terço.",
    explicacao: "GABARITO: CERTO. Art. 21, caput, do Código Penal: 'O desconhecimento da lei é inescusável. O erro sobre a ilicitude do fato, se inevitável, isenta de pena; se evitável, poderá diminuí-la de um sexto a um terço'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-022",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A lei excepcional ou temporária, embora decorrido o período de sua duração ou cessadas as circunstâncias que a determinaram, aplica-se ao fato praticado durante sua vigência, consagrando a ultratividade gravosa.",
    explicacao: "GABARITO: CERTO. Art. 3º do Código Penal: 'A lei excepcional ou temporária, embora decorrido o período de sua duração ou cessadas as circunstâncias que a determinaram, aplica-se ao fato praticado durante sua vigência'. Trata-se de hipótese expressa de ultratividade da lei temporária/excepcional.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-023",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Diz-se consumado o crime quando nele se reúnem todos os elementos de sua definição legal.",
    explicacao: "GABARITO: CERTO. Art. 14, I, do Código Penal: 'Diz-se o crime: I - consumado, quando nele se reúnem todos os elementos de sua definição legal'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-024",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O excesso doloso ou culposo nas causas de justificação (excludentes de ilicitude) sujeita o agente a responder pelo excesso punível nos termos do Código Penal.",
    explicacao: "GABARITO: CERTO. Art. 23, parágrafo único, do CP: 'O agente, em qualquer das hipóteses deste artigo, responderá pelo excesso doloso ou culposo'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-025",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Não se comunicam no concurso de pessoas as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime.",
    explicacao: "GABARITO: CERTO. Art. 30 do Código Penal: 'Não se comunicam as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime'. Exemplo clássico: a condição de funcionário público no peculato se comunica ao coautor particular se este conhecia tal condição.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-026",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A omissão é penalmente relevante quando o omitente devia e podia agir para evitar o resultado. O dever de agir incumbe a quem, EXCETO:",
    explicacao: "GABARITO: E. Art. 13, § 2º, do CP estabelece o dever de agir para quem: a) tenha por lei obrigação de cuidado, proteção ou vigilância; b) de outra forma, assumiu a responsabilidade de impedir o resultado (garantidor de fato); c) com seu comportamento anterior, criou o risco da ocorrência do resultado. Presenciar como simples testemunha não gera dever de garante penal do art. 13, § 2º (salvo omissão de socorro autônoma do art. 135).",
    alternativas: [
      { texto: "Tenha por lei obrigação de cuidado, proteção ou vigilância.", correta: false },
      { texto: "De outra forma, assumiu a responsabilidade de impedir o resultado.", correta: false },
      { texto: "Com seu comportamento anterior, criou o risco da ocorrência do resultado.", correta: false },
      { texto: "Exerça função de salva-vidas contratado em clube e veja banhista se afogando.", correta: false },
      { texto: "Presencie um furto em estabelecimento comercial como simples cliente transeunte.", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-01-027",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos do Código Penal brasileiro, a menoridade relativa (agente com menos de 21 anos na data do fato) e a senilidade (maior de 70 anos na data da sentença) operam como circunstâncias:",
    explicacao: "GABARITO: A. Art. 65, I, do Código Penal prevê a menoridade relativa (menor de 21 anos na data do fato) e a senilidade (maior de 70 anos na data da sentença) como circunstâncias atenuantes genéricas de aplicação na segunda fase da dosimetria da pena.",
    alternativas: [
      { texto: "Atenuantes genéricas de aplicação obrigatória.", correta: true },
      { texto: "Agravantes específicas da terceira fase da dosimetria.", correta: false },
      { texto: "Excludentes peremptórias de tipicidade conglobante.", correta: false },
      { texto: "Causas de anulação de processo penal em primeira instância.", correta: false },
      { texto: "Justificantes que afastam a antijuridicidade material.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-028",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O dolo eventual distingue-se da culpa consciente fundamentalmente porque, no dolo eventual, o agente:",
    explicacao: "GABARITO: B. No dolo eventual, o agente prevê o resultado e assume o risco de sua produção (anuência/assunção do risco, 'foda-se se ocorrer'). Na culpa consciente, o agente também prevê o resultado, mas acredita sinceramente que ele não ocorrerá ou que é capaz de evitá-lo com suas habilidades.",
    alternativas: [
      { texto: "Não prevê o resultado, agindo com imperícia manifesta.", correta: false },
      { texto: "Prevê o resultado lesivo e assume o risco de produzi-lo, sendo-lhe indiferente a consumação.", correta: true },
      { texto: "Acredita piamente que o resultado não ocorrerá em razão de sua extrema destreza pessoal.", correta: false },
      { texto: "Age movido por coação física irresistível imposta por terceiro.", correta: false },
      { texto: "Desiste voluntariamente no interregno entre a execução e a consumação.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-029",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A novatio legis in mellius (lei nova mais favorável ao réu) aplica-se aos fatos anteriores, ainda que já decididos por sentença condenatória transitada em julgado, competindo a sua aplicação ao juízo da execução penal nos termos da Súmula 611 do STF.",
    explicacao: "GABARITO: CERTO. Art. 2º, parágrafo único, do CP, art. 5º, XL, da CF e Súmula 611 do STF: 'Transitada em julgado a sentença condenatória, compete ao Juízo das Execuções a aplicação de lei mais benigna'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-01-030",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O Código Penal brasileiro, no tocante ao concurso de pessoas (art. 29), adotou como regra geral a teoria:",
    explicacao: "GABARITO: D. O Código Penal brasileiro adotou a teoria monista (ou unitária) temperada/matizada: todos os que concorrem para o crime incidem nas penas a este cominadas, na medida de sua culpabilidade (mitigada pela distinção de autoria, coautoria e participação).",
    alternativas: [
      { texto: "Pluralista irrestrita.", correta: false },
      { texto: "Dualista clássica.", correta: false },
      { texto: "Extrínseca finalista.", correta: false },
      { texto: "Monista (unitária) temperada.", correta: true },
      { texto: "Normativa pura da culpabilidade.", correta: false },
    ],
  },
];
