// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 30

export const m02_questoes = [
  {
    "id": "4452e7f3-17c0-56a9-b1db-776babf06627",
    "idSlug": "l13-pen-esp-001-feminicidio-natureza-objetiva",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O feminicídio, inserido como qualificadora do crime de homicídio no Art. 121, § 2º, VI, do Código Penal, possui natureza jurídica objetiva segundo entendimento jurisprudencial consolidado do Superior Tribunal de Justiça, sendo juridicamente compatível com qualificadoras de natureza subjetiva, tais como o motivo torpe ou fútil.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Conforme jurisprudência pacífica do STJ (Tema Repetitivo e súmula persuasiva da 5ª e 6ª Turmas), o feminicídio é qualificadora de ordem objetiva (razões da condição de sexo feminino), sendo plenamente compatível com o motivo torpe ou fútil (qualificadoras de ordem subjetiva), não ocorrendo bis in idem.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6e1aebcc99acc2b70a72f7de0c6f8a1f796da4636f5430025775e9eda12f8de6",
    "conceito_principal": "Feminicídio e compatibilidade com qualificadoras subjetivas",
    "habilidade_cobrada": "Analisar a natureza objetiva da qualificadora do feminicídio e jurisprudência do STJ",
    "tese_ou_regra": "Art. 121, § 2º, VI, do CP e jurisprudência consolidada do STJ",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "1d0aea08-a24f-5124-8b7c-147d32fec658",
        "questao_id": "4452e7f3-17c0-56a9-b1db-776babf06627",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9ea006c2-4eba-5878-b84c-399687e058df",
        "questao_id": "4452e7f3-17c0-56a9-b1db-776babf06627",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bea3887c-0c41-5a32-8430-b89ba9241b31",
    "idSlug": "l13-pen-esp-002-furto-noturno-estabelecimento-comercial",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A causa de aumento de pena decorrente do repouso noturno (Art. 155, § 1º, do CP) aplica-se exclusivamente quando a infração patrimonial é praticada em residência habitada, restando afastada a majorante se o furto ocorrer em estabelecimento comercial ou veículo em via pública durante a madrugada.",
    "explicacao": "GABARITO: ERRADO. GABARITO: ERRADO. Segundo a jurisprudência consolidada do STJ (Súmula 582 analógica e Tema Repetitivo 282), a causa de aumento do repouso noturno aplica-se tanto em residências habitadas quanto em desabitadas, estabelecimentos comerciais e veículos estacionados em via pública, desde que praticado no período de repouso da comunidade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "aa717affd9b1e20b020e022cb3439ae4332bd8d76061810f6a1b3c696abf6cbd",
    "conceito_principal": "Furto durante o repouso noturno",
    "habilidade_cobrada": "Identificar o alcance e aplicação do Art. 155, § 1º, do Código Penal",
    "tese_ou_regra": "Art. 155, § 1º, do CP e jurisprudência do STJ",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "31adf2b0-b931-5974-8821-0df06c33ec5e",
        "questao_id": "bea3887c-0c41-5a32-8430-b89ba9241b31",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "d3c3b95c-dc6b-5d62-889d-1a99ae201398",
        "questao_id": "bea3887c-0c41-5a32-8430-b89ba9241b31",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "f30bc3ca-1c1e-5a4b-9c0d-a79d13535e5a",
    "idSlug": "l13-pen-esp-003-roubo-arma-fogo-apreensao-pericia",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "No crime de roubo circunstanciado pelo emprego de arma de fogo (Art. 157, § 2º-A, I, do CP), a incidência da majorante independe da apreensão do artefato e da realização de perícia técnica para atestar sua potencialidade lesiva, desde que comprovada sua efetiva utilização por outros meios idôneos de prova, cabendo ao imputado o ônus de provar a eventual ineficácia do instrumento.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. É pacífica a jurisprudência do STF e do STJ de que a apreensão e a perícia da arma de fogo são dispensáveis quando o uso do artefato puder ser demonstrado por outros elementos de prova (como testemunhal e imagens de câmeras). Se a defesa alegar que a arma era simulacro ou inoperante, cabe a ela o ônus da prova (Art. 156 do CPP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "12820fcb315dbcec8007d51272a4ffd0fc93e2604df4873734ec45e05a415dff",
    "conceito_principal": "Roubo com arma de fogo e dispensabilidade de perícia",
    "habilidade_cobrada": "Aplicar entendimento jurisprudencial do STF/STJ sobre comprovação de arma no roubo",
    "tese_ou_regra": "Art. 157, § 2º-A, I, do CP e precedentes de Cortes Superiores",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "40a475fd-9da9-5b81-81cb-0ba5fe5763ab",
        "questao_id": "f30bc3ca-1c1e-5a4b-9c0d-a79d13535e5a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5b439508-9e60-5066-8258-dc14f7e28cee",
        "questao_id": "f30bc3ca-1c1e-5a4b-9c0d-a79d13535e5a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "1fbc70d3-e5d0-53c5-b3fb-d083ddae4088",
    "idSlug": "l13-pen-esp-004-extorsao-mediante-sequestro-consumacao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O crime de extorsão mediante sequestro (Art. 148 e 159 do CP) é classificado como crime formal, consumando-se no momento exato em que a vítima é privada de sua liberdade de locomoção com o fim específico de obtenção de qualquer vantagem como condição ou preço do resgate, sendo irrelevante para a consumação o pagamento ou a obtenção efetiva da quantia exigida.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A extorsão mediante sequestro (Art. 159 do CP) é crime formal e permanente. Consuma-se com a privação da liberdade da vítima com o dolo específico de obter vantagem econômica como resgate. A obtenção efetiva da vantagem é mero exaurimento do delito.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "425e7d80dedf85e190136c50b6186827fb01a3d20b75bceedc6977c34bb26b4c",
    "conceito_principal": "Consumação do crime de extorsão mediante sequestro",
    "habilidade_cobrada": "Diferenciar momento consumativo e exaurimento em crimes patrimoniais",
    "tese_ou_regra": "Art. 159 do CP e Súmula 96 do STJ aplicável à extorsão",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5a5f44d0-5b84-597e-9034-b3ef522ea4b0",
        "questao_id": "1fbc70d3-e5d0-53c5-b3fb-d083ddae4088",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "efe13d9f-fc43-5144-9844-d76e77a875b9",
        "questao_id": "1fbc70d3-e5d0-53c5-b3fb-d083ddae4088",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
    "idSlug": "l13-pen-esp-005-estelionato-representacao-regra",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Com o advento da Lei nº 13.964/2019 (Pacote Anticrime), o crime de estelionato (Art. 171 do CP) passou a se processar, em regra, mediante ação penal pública condicionada à representação do ofendido. Assinale a alternativa que indica CORRETAMENTE uma hipótese em que a ação penal permanece como PÚBLICA INCONDICIONADA.",
    "explicacao": "GABARITO: B. O Art. 171, § 5º, do Código Penal estabelece que a ação penal será pública incondicionada se a vítima for: I - a Administração Pública, direta ou indireta; II - criança ou adolescente; III - pessoa com deficiência mental; ou IV - maior de 70 (setenta) anos de idade ou incapaz.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a7d1ae5fb2dd05742c7d53ea4252e79445196f55774c2290fe947c835f794c59",
    "conceito_principal": "Ação penal no estelionato após o Pacote Anticrime",
    "habilidade_cobrada": "Identificar as exceções legais de ação pública incondicionada no estelionato",
    "tese_ou_regra": "Art. 171, § 5º, do Código Penal",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "13772994-8d23-5d55-8d47-356bad7027ed",
        "questao_id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
        "letra": "A",
        "texto": "Vítima com idade igual ou superior a 60 (sessenta) anos de idade.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta: o Estatuto da Pessoa Idosa considera idoso a partir de 60 anos, mas a exceção do Art. 171, § 5º, IV, exige expressamente maior de 70 anos."
      },
      {
        "id": "ff5ea726-29d9-5372-8196-1f599137d9c6",
        "questao_id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
        "letra": "B",
        "texto": "Vítima que seja pessoa com deficiência mental ou criança/adolescente.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta: expressamente prevista no Art. 171, § 5º, incisos II e III, do Código Penal."
      },
      {
        "id": "48a1d268-f1cb-5245-9a73-6b67636bc575",
        "questao_id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
        "letra": "C",
        "texto": "Prejuízo patrimonial apurado superior a cem salários mínimos.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o valor do prejuízo econômico não altera a natureza da ação penal no estelionato."
      },
      {
        "id": "6c2e8499-dc12-5a03-adca-f13c1eac1886",
        "questao_id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
        "letra": "D",
        "texto": "Prática do delito mediante fraude telemática cometida do exterior.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: a fraude telemática qualifica o crime (Art. 171, § 4º), mas não altera per se a exigência de representação."
      },
      {
        "id": "80950d9f-3b62-5c99-b73b-9f734fe3a425",
        "questao_id": "aa1e68b5-209b-5522-9304-b4dfdd835109",
        "letra": "E",
        "texto": "Cometimento do crime em concurso de pessoas contra instituição bancária privada.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: contra instituição privada segue a regra geral da representação, salvo se a vítima se enquadrar nas exceções do § 5º."
      }
    ]
  },
  {
    "id": "09aceb96-fc15-58b3-8f3d-cb2e2838801f",
    "idSlug": "l13-pen-esp-006-peculato-culposo-reparacao-dano",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "No crime de peculato culposo (Art. 312, § 2º, do CP), a reparação do dano patrimonial antes da sentença irrecorrível extingue a punibilidade do agente, ao passo que a reparação posterior ao trânsito em julgado reduz de metade a pena imposta.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 312, § 3º, do CP: 'No caso do parágrafo anterior, a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade; se lhe é posterior, reduz de metade a pena imposta'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cd5cd9048f6b89c8ec89b84e43491f60e6468035f2b3dd872a4f19b4f02bfb52",
    "conceito_principal": "Extinção da punibilidade e redução de pena no peculato culposo",
    "habilidade_cobrada": "Reconhecer os efeitos da reparação do dano no peculato culposo",
    "tese_ou_regra": "Art. 312, § 3º, do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "636f3da3-2687-5241-9585-936f0fd9c92e",
        "questao_id": "09aceb96-fc15-58b3-8f3d-cb2e2838801f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "73f0d072-09ce-5db0-a04f-97d3c6630675",
        "questao_id": "09aceb96-fc15-58b3-8f3d-cb2e2838801f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b559e0b7-fb02-52c1-8aa4-e329d275238b",
    "idSlug": "l13-pen-esp-007-concussao-versus-corrupcao-passiva",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A distinção dogmática elementar entre os crimes de concussão (Art. 316 do CP) e de corrupção passiva (Art. 317 do CP) reside no verbo nuclear da conduta: na concussão o funcionário público 'exige' a vantagem indevida com imposição coercitiva, enquanto na corrupção passiva ele 'solicita', 'recebe' ou 'aceita promessa' de tal vantagem.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O núcleo da concussão é 'exigir' (impor temor, intimidação decorrente da função). Na corrupção passiva, os núcleos são 'solicitar', 'receber' ou 'aceitar promessa' de vantagem indevida, inexistindo imposição intimidatória.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ee171ea04fe4e1e99d47a172bd6809e92122741a61f268c9b4e8bb3bb3b6f1cd",
    "conceito_principal": "Diferença entre concussão e corrupção passiva",
    "habilidade_cobrada": "Distinguir os verbos nucleares e elementos típicos dos crimes contra a Administração Pública",
    "tese_ou_regra": "Arts. 316 e 317 do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "73052182-54c1-5534-8a52-07f3baa0f469",
        "questao_id": "b559e0b7-fb02-52c1-8aa4-e329d275238b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d51ad41a-70a6-5f41-a169-516c2e60ba5f",
        "questao_id": "b559e0b7-fb02-52c1-8aa4-e329d275238b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ba50ebaa-2fe7-5dd3-8d1a-796194aabb5e",
    "idSlug": "l13-pen-esp-008-prevaricacao-sentimento-pessoal",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Para a configuração do crime de prevaricação (Art. 319 do CP), é indispensável a demonstração do elemento subjetivo especial do tipo consistente na finalidade de satisfazer interesse ou sentimento pessoal, não bastando a simples desídia funcional ou descumprimento culposo de dever funcional.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O Art. 319 exige expressamente o especial fim de agir: 'para satisfazer interesse ou sentimento pessoal'. A mera preguiça, inabilidade ou atraso sem a intenção pessoal não configura prevaricação, podendo gerar apenas sanção administrativo-disciplinar.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e41b97eecc22a69b03c30a4cc68601d0b757883c51d95efd83dfdd4c0f382833",
    "conceito_principal": "Elemento subjetivo específico no crime de prevaricação",
    "habilidade_cobrada": "Identificar o dolo específico e os limites entre ilícito penal e falta administrativa",
    "tese_ou_regra": "Art. 319 do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "4e2c6ecf-4581-52ad-94ef-184b1f41e8e9",
        "questao_id": "ba50ebaa-2fe7-5dd3-8d1a-796194aabb5e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c2629632-d497-5722-9812-7d1f1ef93a43",
        "questao_id": "ba50ebaa-2fe7-5dd3-8d1a-796194aabb5e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "72489dcb-85e3-5101-a4f5-fc3a92923d11",
    "idSlug": "l13-pen-esp-009-desobediencia-versus-desacato",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O crime de desacato (Art. 331 do CP), consistente em desacatar funcionário público no exercício da função ou em razão dela, foi integralmente descriminalizado no ordenamento jurídico brasileiro em razão de decisão com efeito vinculante proferida pela Corte Interamericana de Direitos Humanos.",
    "explicacao": "GABARITO: ERRADO. GABARITO: ERRADO. O Plenário do STF (na ADPF 496) e a 3ª Seção do STJ (HC 379.269/MS) fixaram que o tipo penal de desacato (Art. 331 do CP) é plenamente compatível com a Constituição Federal de 1988 e com o Pacto de São José da Costa Rica, permanecendo em vigor e tutelando a função pública.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c65738b9ed7e55f656a31e93bfbbda5a59e069b25effa62da247bfa0f2090762",
    "conceito_principal": "Constitucionalidade e vigência do crime de desacato",
    "habilidade_cobrada": "Analisar a vigência do desacato à luz da jurisprudência do STF e STJ",
    "tese_ou_regra": "Art. 331 do CP e ADPF 496/STF",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "9fa27f1a-783f-56f8-b2d3-47b3f473312e",
        "questao_id": "72489dcb-85e3-5101-a4f5-fc3a92923d11",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "d6b7d1f4-888f-5bed-bec7-d92e2fac95ba",
        "questao_id": "72489dcb-85e3-5101-a4f5-fc3a92923d11",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
    "idSlug": "l13-pen-esp-010-corrupcao-ativa-flagrante-consumacao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Durante blitz policial, um condutor oferece a quantia de R$ 2.000,00 aos policiais militares para que não registrem autuação de trânsito. Os policiais recusam de imediato a oferta e prendem o indivíduo em flagrante delito. Quanto ao crime de corrupção ativa (Art. 333 do CP), assinale a afirmativa correta:",
    "explicacao": "GABARITO: C. O crime de corrupção ativa é formal (de consumação antecipada) e consuma-se no instante em que o particular oferece ou promete a vantagem indevida, independentemente de aceitação ou recebimento pelo servidor.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fd69904cb1ece40ab2ab69d934309d7f418b23ebda36054e1b7a0639e9940596",
    "conceito_principal": "Momento consumativo do crime de corrupção ativa",
    "habilidade_cobrada": "Classificar crimes formais e momentos consumativos no Direito Penal",
    "tese_ou_regra": "Art. 333 do Código Penal",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "fc4e720e-413a-531c-928c-f82ab850f205",
        "questao_id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
        "letra": "A",
        "texto": "Trata-se de crime tentado, pois os policiais não aceitaram nem receberam o montante em dinheiro.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta: a corrupção ativa é crime formal e dispensa a aceitação."
      },
      {
        "id": "8e1dd9f6-3864-5dab-901f-7292d6e30547",
        "questao_id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
        "letra": "B",
        "texto": "A conduta é atípica penalmente, configurando apenas infração administrativa de trânsito.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: a oferta de vantagem indevida a funcionário público é conduta típica autônoma do Art. 333."
      },
      {
        "id": "dcb933b7-acb1-5143-893c-a995c5cedf05",
        "questao_id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
        "letra": "C",
        "texto": "O crime consumou-se no momento da oferta, sendo irrelevante a recusa ou aceitação pelos policiais.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta: por ser crime formal, a consumação ocorre com o simples oferecimento da vantagem."
      },
      {
        "id": "0f6ccf72-8128-52a1-99c1-9eeafce4f5ac",
        "questao_id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
        "letra": "D",
        "texto": "Houve desistência voluntária por parte do infrator ao perceber a intransigência dos policiais.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o crime já estava consumado antes da recusa dos policiais."
      },
      {
        "id": "aa324574-2101-5847-a938-6ae2bdbac520",
        "questao_id": "a1f99530-5c2d-5e20-89e3-e5622f2ed35e",
        "letra": "E",
        "texto": "A consumação exigia a entrega física do numerário ao patrimônio dos policiais.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a entrega física caracterizaria apenas o exaurimento do delito."
      }
    ]
  },
  {
    "id": "c8c04034-a4f8-5358-8647-bb1b6ffb8006",
    "idSlug": "l13-pen-esp-011-infanticidio-estado-puerperal",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: O infanticídio (Art. 123) exige que a mãe mate o próprio filho sob influência do estado puerperal durante ou logo após o parto, comunicando-se tal condição ao coautor (Art. 30 do CP).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: O infanticídio (Art. 123) exige que a mãe mate o próprio filho sob influência do estado puerperal durante ou logo após o parto, comunicando-se tal condição ao coautor (Art. 30 do CP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0f92a60255e2b86bfd92621e6de2f716f9d1fda6a08a899b2af55ef52e4378c4",
    "conceito_principal": "Aplicação prática de infanticidio estado puerperal",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "O infanticídio (Art. 123) exige que a mãe mate o próprio filho sob influência do estado puerperal durante ou logo após o parto, comunicando-se tal condição ao coautor (Art. 30 do CP).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "ff5fff89-fd72-5aca-a28f-958f42ef9ae6",
        "questao_id": "c8c04034-a4f8-5358-8647-bb1b6ffb8006",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "186deba3-6d32-547a-80b7-eb697b74b077",
        "questao_id": "c8c04034-a4f8-5358-8647-bb1b6ffb8006",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6f7375e8-af0b-50c0-9f03-5bc5fe6519b7",
    "idSlug": "l13-pen-esp-012-lesao-corporal-grave-debilidade",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A debilidade permanente de membro, sentido ou função qualifica a lesão corporal no Art. 129, § 1º, III, enquanto a perda ou inutilização configura lesão gravíssima (§ 2º, III).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A debilidade permanente de membro, sentido ou função qualifica a lesão corporal no Art. 129, § 1º, III, enquanto a perda ou inutilização configura lesão gravíssima (§ 2º, III).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "da34188aa1c64d0c1ce0ead0594610bdc84389731ebe10576e73bd4616892a19",
    "conceito_principal": "Aplicação prática de lesao corporal grave debilidade",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A debilidade permanente de membro, sentido ou função qualifica a lesão corporal no Art. 129, § 1º, III, enquanto a perda ou inutilização configura lesão gravíssima (§ 2º, III).",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "897d7939-0906-5368-a069-6e432cd65aca",
        "questao_id": "6f7375e8-af0b-50c0-9f03-5bc5fe6519b7",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "222467e8-b4d8-5677-8278-582fef038f4b",
        "questao_id": "6f7375e8-af0b-50c0-9f03-5bc5fe6519b7",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b8151f9d-a78f-5a77-876a-337ef61ea8a9",
    "idSlug": "l13-pen-esp-013-omissao-socorro-policial",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A omissão de socorro (Art. 135) é crime subsidiário e só se tipifica se o agente não responder por crime mais grave ou não ostentar o dever legal de garante (Art. 13, § 2º, a).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A omissão de socorro (Art. 135) é crime subsidiário e só se tipifica se o agente não responder por crime mais grave ou não ostentar o dever legal de garante (Art. 13, § 2º, a).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "67c9e7db91e4ece415d307eecca4900cdfc1346d74342a53f856fb8269bf9f7f",
    "conceito_principal": "Aplicação prática de omissao socorro policial",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A omissão de socorro (Art. 135) é crime subsidiário e só se tipifica se o agente não responder por crime mais grave ou não ostentar o dever legal de garante (Art. 13, § 2º, a).",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "d0b58037-50ec-51b9-9aaf-cd6600b57a0b",
        "questao_id": "b8151f9d-a78f-5a77-876a-337ef61ea8a9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "0bd6261c-5c9c-53cd-a5d5-afc026e25aca",
        "questao_id": "b8151f9d-a78f-5a77-876a-337ef61ea8a9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "1440044d-9117-5c52-83db-c29eb8470a6a",
    "idSlug": "l13-pen-esp-014-calunia-excecao-da-verdade",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: Na calúnia (Art. 138), admite-se a exceção da verdade, salvo se constituindo o fato imputado crime de ação privada o ofendido não foi condenado por sentença irrecorrível.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: Na calúnia (Art. 138), admite-se a exceção da verdade, salvo se constituindo o fato imputado crime de ação privada o ofendido não foi condenado por sentença irrecorrível.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1b510f1b331e62edb80ae71fa4e930c0c8e646d3305702dc11f18c43d1901025",
    "conceito_principal": "Aplicação prática de calunia excecao da verdade",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "Na calúnia (Art. 138), admite-se a exceção da verdade, salvo se constituindo o fato imputado crime de ação privada o ofendido não foi condenado por sentença irrecorrível.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2ba9abec-8681-5d59-8e7d-59f93ac3060f",
        "questao_id": "1440044d-9117-5c52-83db-c29eb8470a6a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f255235a-0fc2-58f7-9c95-d969d7f5e143",
        "questao_id": "1440044d-9117-5c52-83db-c29eb8470a6a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
    "idSlug": "l13-pen-esp-015-injuria-racial-equiparacao-racismo",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Acerca da dogmática e da jurisprudência sumulada dos Tribunais Superiores sobre o tema injuria racial equiparacao racismo, assinale a alternativa juridicamente correta:",
    "explicacao": "GABARITO: A. Com a Lei 14.532/2023, a injúria racial foi deslocada para a Lei 7.716/1989 e passou a ser imprescritível e inafiançável, equiparada aos crimes de racismo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6f7d75652ba994e884af6a1d05557161447885e7160ee411464f86b5a4dc8962",
    "conceito_principal": "Regime penal de injuria racial equiparacao racismo",
    "habilidade_cobrada": "Identificar os requisitos típicos do instituto penal examinado",
    "tese_ou_regra": "Com a Lei 14.532/2023, a injúria racial foi deslocada para a Lei 7.716/1989 e passou a ser imprescritível e inafiançável, equiparada aos crimes de racismo.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "471e59a9-dcde-553c-9393-4ea9247e1861",
        "questao_id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
        "letra": "A",
        "texto": "Com a Lei 14.532/2023, a injúria racial foi deslocada para a Lei 7.716/1989 e passou a ser imprescritível e inafiançável, equiparada aos crimes de racismo.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme a literalidade normativa e jurisprudência consolidada."
      },
      {
        "id": "77375463-2d11-5e33-b408-4baf4895fa79",
        "questao_id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
        "letra": "B",
        "texto": "O Código Penal afasta peremptoriamente tal regramento em favor do princípio da insignificância patrimonial ilimitada.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: proposição sem respaldo na legislação penal."
      },
      {
        "id": "aa63299d-6602-52a7-a69e-8c8137481418",
        "questao_id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
        "letra": "C",
        "texto": "A consumação depende de autorização judicial prévia específica outorgada pelo Juízo das Garantias.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: distorce a sistemática de tipicidade e competência."
      },
      {
        "id": "433b6633-4823-5f6d-8355-d71ec6ef8708",
        "questao_id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
        "letra": "D",
        "texto": "Trata-se de infração de mera conduta insuscetível de qualquer causa de extinção da punibilidade.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: generalização incorreta que contraria o Código Penal."
      },
      {
        "id": "9424987b-9678-5c06-9065-5f017dc82456",
        "questao_id": "83a2638a-4c0c-56b1-925e-e42d0e9e29b9",
        "letra": "E",
        "texto": "Aplica-se unicamente a servidores federais da ativa, sendo atípica a conduta praticada por particulares.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: restrição indevida não prevista em lei."
      }
    ]
  },
  {
    "id": "161a5220-d36f-5654-b905-8b1d756885e2",
    "idSlug": "l13-pen-esp-016-violacao-domicilio-dia-noite",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: O crime de violação de domicílio (Art. 150) qualifica-se se cometido durante a noite, ou em lugar ermo, ou com emprego de violência ou de arma, ou por duas ou mais pessoas.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: O crime de violação de domicílio (Art. 150) qualifica-se se cometido durante a noite, ou em lugar ermo, ou com emprego de violência ou de arma, ou por duas ou mais pessoas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "65a9cf6a7fe832c9f351a84cc1d7ca109e241b6d277d4df6b6e72ac769f1e037",
    "conceito_principal": "Aplicação prática de violacao domicilio dia noite",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "O crime de violação de domicílio (Art. 150) qualifica-se se cometido durante a noite, ou em lugar ermo, ou com emprego de violência ou de arma, ou por duas ou mais pessoas.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "68ac8e3c-7673-5563-b931-425081706098",
        "questao_id": "161a5220-d36f-5654-b905-8b1d756885e2",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9055d7e2-c57e-5f1c-9019-0d5446dc9746",
        "questao_id": "161a5220-d36f-5654-b905-8b1d756885e2",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ac45ba16-1794-5bcc-9804-f97df466978e",
    "idSlug": "l13-pen-esp-017-dano-qualificado-patrimonio-publico",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: O crime de dano simples é de ação privada, mas qualifica-se e torna-se de ação pública incondicionada se praticado contra o patrimônio da União, Estado, DF ou Município (Art. 163, parágrafo único, III).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: O crime de dano simples é de ação privada, mas qualifica-se e torna-se de ação pública incondicionada se praticado contra o patrimônio da União, Estado, DF ou Município (Art. 163, parágrafo único, III).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0f1e3ae61282b92b8e4004c981289d9fec0110073f9936c43f56cb2c6b982da7",
    "conceito_principal": "Aplicação prática de dano qualificado patrimonio publico",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "O crime de dano simples é de ação privada, mas qualifica-se e torna-se de ação pública incondicionada se praticado contra o patrimônio da União, Estado, DF ou Município (Art. 163, parágrafo único, III).",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "9dc922f5-0d5f-5b07-bcd0-1b3087d488f0",
        "questao_id": "ac45ba16-1794-5bcc-9804-f97df466978e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "37ea066c-1c75-5e6d-ad39-048e648f3846",
        "questao_id": "ac45ba16-1794-5bcc-9804-f97df466978e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f06a3ff4-e563-58b3-bac7-cc6c17ee9c35",
    "idSlug": "l13-pen-esp-018-apropriacao-indebita-previdenciaria",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A apropriação indébita previdenciária (Art. 168-A) é crime omissivo próprio material cuja consumação dispensa o dolo específico de locupletamento ilícito (animus rem sibi habendi).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A apropriação indébita previdenciária (Art. 168-A) é crime omissivo próprio material cuja consumação dispensa o dolo específico de locupletamento ilícito (animus rem sibi habendi).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cf6e01a9604c76f8346e9fefbffde61f04142890cd7e6d1ebcabee383b30435e",
    "conceito_principal": "Aplicação prática de apropriacao indebita previdenciaria",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A apropriação indébita previdenciária (Art. 168-A) é crime omissivo próprio material cuja consumação dispensa o dolo específico de locupletamento ilícito (animus rem sibi habendi).",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "64ccde62-2fb9-5476-9f83-60f957cfeffa",
        "questao_id": "f06a3ff4-e563-58b3-bac7-cc6c17ee9c35",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "58a4e02f-fe10-582e-9af8-369bfe26748f",
        "questao_id": "f06a3ff4-e563-58b3-bac7-cc6c17ee9c35",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7df5a5b0-4cd0-52d6-b699-5ba3eb02de09",
    "idSlug": "l13-pen-esp-019-receptacao-qualificada-comercio",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A receptação qualificada (Art. 180, § 1º) pune com maior rigor quem adquire ou recebe coisa no exercício de atividade comercial ou industrial, bastando o dolo eventual ('deve saber').",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A receptação qualificada (Art. 180, § 1º) pune com maior rigor quem adquire ou recebe coisa no exercício de atividade comercial ou industrial, bastando o dolo eventual ('deve saber').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f3535f0b910036de218e4591b9ea91a885a53fa95880c329608c842fdb2fa4d4",
    "conceito_principal": "Aplicação prática de receptacao qualificada comercio",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A receptação qualificada (Art. 180, § 1º) pune com maior rigor quem adquire ou recebe coisa no exercício de atividade comercial ou industrial, bastando o dolo eventual ('deve saber').",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5d2b5470-3b6e-5cff-ba2e-0553f4aea6ff",
        "questao_id": "7df5a5b0-4cd0-52d6-b699-5ba3eb02de09",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9d849fb4-50ac-54e8-aaae-0cd973960c04",
        "questao_id": "7df5a5b0-4cd0-52d6-b699-5ba3eb02de09",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
    "idSlug": "l13-pen-esp-020-falsidade-ideologica-documento",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Acerca da dogmática e da jurisprudência sumulada dos Tribunais Superiores sobre o tema falsidade ideologica documento, assinale a alternativa juridicamente correta:",
    "explicacao": "GABARITO: A. A falsidade ideológica (Art. 299) recai sobre o conteúdo declaratório do documento formalmente autêntico, diferindo da falsidade material (Arts. 297/298), que atinge a própria forma física.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "842b48a37fb6a9b27fb3b21cdc24fe6c8937eb05a947f81416ee8e0ff2e3ebd4",
    "conceito_principal": "Regime penal de falsidade ideologica documento",
    "habilidade_cobrada": "Identificar os requisitos típicos do instituto penal examinado",
    "tese_ou_regra": "A falsidade ideológica (Art. 299) recai sobre o conteúdo declaratório do documento formalmente autêntico, diferindo da falsidade material (Arts. 297/298), que atinge a própria forma física.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "3331e41b-6792-5b06-882f-0327ac71165a",
        "questao_id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
        "letra": "A",
        "texto": "A falsidade ideológica (Art. 299) recai sobre o conteúdo declaratório do documento formalmente autêntico, diferindo da falsidade material (Arts. 297/298), que atinge a própria forma física.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme a literalidade normativa e jurisprudência consolidada."
      },
      {
        "id": "6f19e702-9441-5cc9-a4d7-c8ab2ad79e0f",
        "questao_id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
        "letra": "B",
        "texto": "O Código Penal afasta peremptoriamente tal regramento em favor do princípio da insignificância patrimonial ilimitada.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: proposição sem respaldo na legislação penal."
      },
      {
        "id": "17504cab-524d-5ea6-b145-a3fd5d054e42",
        "questao_id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
        "letra": "C",
        "texto": "A consumação depende de autorização judicial prévia específica outorgada pelo Juízo das Garantias.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: distorce a sistemática de tipicidade e competência."
      },
      {
        "id": "3341aff4-086e-508e-adb7-7a93ef4e55a8",
        "questao_id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
        "letra": "D",
        "texto": "Trata-se de infração de mera conduta insuscetível de qualquer causa de extinção da punibilidade.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: generalização incorreta que contraria o Código Penal."
      },
      {
        "id": "1eabf675-35a6-546f-813b-f09a574c7590",
        "questao_id": "0a3dad48-76b6-5bad-82f0-cf1e0aa253a0",
        "letra": "E",
        "texto": "Aplica-se unicamente a servidores federais da ativa, sendo atípica a conduta praticada por particulares.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: restrição indevida não prevista em lei."
      }
    ]
  },
  {
    "id": "64fc929c-d704-58e6-a88b-e2195dd2f059",
    "idSlug": "l13-pen-esp-021-uso-documento-falso-autoria",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "d7c9580a-8d0c-5a7d-a7fe-44e0c53b4968",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: Segundo a Súmula 17 do STJ, quando o falso se exaure no estelionato, sem mais potencialidade lesiva, é por este absorvido, aplicando-se o princípio da consunção.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: Segundo a Súmula 17 do STJ, quando o falso se exaure no estelionato, sem mais potencialidade lesiva, é por este absorvido, aplicando-se o princípio da consunção.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "55dd47fe4334438b79194a190234e4bae5ea92de0b7453bc8f15df6c4d9a367a",
    "conceito_principal": "Aplicação prática de uso documento falso autoria",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "Segundo a Súmula 17 do STJ, quando o falso se exaure no estelionato, sem mais potencialidade lesiva, é por este absorvido, aplicando-se o princípio da consunção.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "d34ac121-42e3-5b89-a181-449e333bb3c5",
        "questao_id": "64fc929c-d704-58e6-a88b-e2195dd2f059",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "21acde73-c3eb-57a7-b979-6106d0590b51",
        "questao_id": "64fc929c-d704-58e6-a88b-e2195dd2f059",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6e3a81ad-3c2b-5e6c-8e2b-9ae028e834d9",
    "idSlug": "l13-pen-esp-022-falsa-identidade-autodefesa",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A conduta de atribuir-se falsa identidade perante autoridade policial para ocultar antecedentes é típica (Art. 307), não estando acobertada pelo direito de autodefesa (Súmula 522 do STJ).",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A conduta de atribuir-se falsa identidade perante autoridade policial para ocultar antecedentes é típica (Art. 307), não estando acobertada pelo direito de autodefesa (Súmula 522 do STJ).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "49b0d56c18f40953b4143e66a3c68ad24defa066780653080d78d3607b63b1bb",
    "conceito_principal": "Aplicação prática de falsa identidade autodefesa",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A conduta de atribuir-se falsa identidade perante autoridade policial para ocultar antecedentes é típica (Art. 307), não estando acobertada pelo direito de autodefesa (Súmula 522 do STJ).",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "4cf48ab0-9a2d-5363-b5fd-66797220b887",
        "questao_id": "6e3a81ad-3c2b-5e6c-8e2b-9ae028e834d9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "cd064b1e-9801-5a97-8e7a-62d8154c7ba4",
        "questao_id": "6e3a81ad-3c2b-5e6c-8e2b-9ae028e834d9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "893448d7-95c8-5b9e-9fb3-813ffe22cb16",
    "idSlug": "l13-pen-esp-023-peculato-mediante-fraude-distincao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: No peculato mediante fraude (Art. 312), o agente se vale da facilidade do cargo para subtrair o bem, enquanto no estelionato clássico a fraude engana a vítima sem relação direta de cargo.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: No peculato mediante fraude (Art. 312), o agente se vale da facilidade do cargo para subtrair o bem, enquanto no estelionato clássico a fraude engana a vítima sem relação direta de cargo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b0f37c8a0a9d17fb396e1261cff5fd0b706170c9c590da311445d14fb15c991c",
    "conceito_principal": "Aplicação prática de peculato mediante fraude distincao",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "No peculato mediante fraude (Art. 312), o agente se vale da facilidade do cargo para subtrair o bem, enquanto no estelionato clássico a fraude engana a vítima sem relação direta de cargo.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "e832410a-5b9d-5a85-93e6-6073f926e373",
        "questao_id": "893448d7-95c8-5b9e-9fb3-813ffe22cb16",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ed94c4d9-1ac2-59c0-a62f-d91cc94f6740",
        "questao_id": "893448d7-95c8-5b9e-9fb3-813ffe22cb16",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b9929b0f-6736-5da6-86ef-62c66595ae5f",
    "idSlug": "l13-pen-esp-024-condescendencia-criminosa-superior",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A condescendência criminosa (Art. 320) exige que o superior deixe, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A condescendência criminosa (Art. 320) exige que o superior deixe, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "34671ccdd2212b95f5d9d739f0e3e8964c8a06bb2daf37c734b95c576cca11a7",
    "conceito_principal": "Aplicação prática de condescendencia criminosa superior",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A condescendência criminosa (Art. 320) exige que o superior deixe, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "1a2c203d-dbe5-57ce-872c-79f9e573f455",
        "questao_id": "b9929b0f-6736-5da6-86ef-62c66595ae5f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2a27cd98-227a-52ba-910f-d8351b75f7e1",
        "questao_id": "b9929b0f-6736-5da6-86ef-62c66595ae5f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
    "idSlug": "l13-pen-esp-025-advocacia-administrativa-legitimidade",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Acerca da dogmática e da jurisprudência sumulada dos Tribunais Superiores sobre o tema advocacia administrativa legitimidade, assinale a alternativa juridicamente correta:",
    "explicacao": "GABARITO: A. O crime de advocacia administrativa (Art. 321) pune o funcionário que patrocina interesse privado perante a administração pública, valendo-se da qualidade funcional, mesmo que legítimo o interesse.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f92dbb7baea570aa3ea5f58cd84192e4167b4d7d2adfe4575bde3984d91d779b",
    "conceito_principal": "Regime penal de advocacia administrativa legitimidade",
    "habilidade_cobrada": "Identificar os requisitos típicos do instituto penal examinado",
    "tese_ou_regra": "O crime de advocacia administrativa (Art. 321) pune o funcionário que patrocina interesse privado perante a administração pública, valendo-se da qualidade funcional, mesmo que legítimo o interesse.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "dae24bf8-6cc1-58b0-a569-507cab455166",
        "questao_id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
        "letra": "A",
        "texto": "O crime de advocacia administrativa (Art. 321) pune o funcionário que patrocina interesse privado perante a administração pública, valendo-se da qualidade funcional, mesmo que legítimo o interesse.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme a literalidade normativa e jurisprudência consolidada."
      },
      {
        "id": "50370f43-6f77-5c75-98a1-19be2e1ba1f7",
        "questao_id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
        "letra": "B",
        "texto": "O Código Penal afasta peremptoriamente tal regramento em favor do princípio da insignificância patrimonial ilimitada.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: proposição sem respaldo na legislação penal."
      },
      {
        "id": "b7b7f2a1-e2f9-5d3c-be98-5280da6cbefe",
        "questao_id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
        "letra": "C",
        "texto": "A consumação depende de autorização judicial prévia específica outorgada pelo Juízo das Garantias.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: distorce a sistemática de tipicidade e competência."
      },
      {
        "id": "496f8e14-15ae-56bc-9a72-0865934caa02",
        "questao_id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
        "letra": "D",
        "texto": "Trata-se de infração de mera conduta insuscetível de qualquer causa de extinção da punibilidade.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: generalização incorreta que contraria o Código Penal."
      },
      {
        "id": "ddd1356b-f12f-5fe9-b3cd-aebcc72440f3",
        "questao_id": "b32cc5f0-b913-5e46-9956-7c705cd67c0c",
        "letra": "E",
        "texto": "Aplica-se unicamente a servidores federais da ativa, sendo atípica a conduta praticada por particulares.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: restrição indevida não prevista em lei."
      }
    ]
  },
  {
    "id": "72dd6c99-801b-5404-af9a-c3b2cb7dd8d6",
    "idSlug": "l13-pen-esp-026-violacao-sigilo-funcional-dano",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A violação de sigilo funcional (Art. 325) consuma-se com a revelação de fato sigiloso do qual tem ciência pela função, punindo-se inclusive a modalidade culposa se resulta dano.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A violação de sigilo funcional (Art. 325) consuma-se com a revelação de fato sigiloso do qual tem ciência pela função, punindo-se inclusive a modalidade culposa se resulta dano.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b254815af309a4dcc779aae3f43d4d90922145af92aa4a94af9b6f9334c2cefc",
    "conceito_principal": "Aplicação prática de violacao sigilo funcional dano",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A violação de sigilo funcional (Art. 325) consuma-se com a revelação de fato sigiloso do qual tem ciência pela função, punindo-se inclusive a modalidade culposa se resulta dano.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "a5857186-2532-5633-9aaa-3c57da6d68cb",
        "questao_id": "72dd6c99-801b-5404-af9a-c3b2cb7dd8d6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "106591a7-4b98-5e6a-a9c4-88e54dc0bbfb",
        "questao_id": "72dd6c99-801b-5404-af9a-c3b2cb7dd8d6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ab871d84-be3a-5ac9-aefa-b0a65066acb8",
    "idSlug": "l13-pen-esp-027-usurpacao-funcao-publica-vantagem",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A usurpação de função pública (Art. 328) qualifica-se se o agente aufere vantagem indevida decorrente do exercício arbitrário da função pública usurpada.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A usurpação de função pública (Art. 328) qualifica-se se o agente aufere vantagem indevida decorrente do exercício arbitrário da função pública usurpada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c617af473399cf8e88d0a03878017b8559784271e49547da4b857d80a2ac4cd6",
    "conceito_principal": "Aplicação prática de usurpacao funcao publica vantagem",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A usurpação de função pública (Art. 328) qualifica-se se o agente aufere vantagem indevida decorrente do exercício arbitrário da função pública usurpada.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "150f1d03-63d0-56b9-a82f-4d1fc555b602",
        "questao_id": "ab871d84-be3a-5ac9-aefa-b0a65066acb8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "25ebdbc7-df0c-5c52-962e-8166d02e68ed",
        "questao_id": "ab871d84-be3a-5ac9-aefa-b0a65066acb8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5ff827e9-1728-5ca6-a1e0-3d9326565891",
    "idSlug": "l13-pen-esp-028-resistencia-desobediencia-violencia",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: O crime de resistência (Art. 329) exige emprego de violência ou ameaça contra o funcionário competente, ao passo que a desobediência (Art. 330) envolve mera inexecução de ordem legal sem violência.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: O crime de resistência (Art. 329) exige emprego de violência ou ameaça contra o funcionário competente, ao passo que a desobediência (Art. 330) envolve mera inexecução de ordem legal sem violência.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "afbda14dd4be0767eae7478795c4de55c65a634ed1b73cadbf2d05af8255e6d2",
    "conceito_principal": "Aplicação prática de resistencia desobediencia violencia",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "O crime de resistência (Art. 329) exige emprego de violência ou ameaça contra o funcionário competente, ao passo que a desobediência (Art. 330) envolve mera inexecução de ordem legal sem violência.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "bc538ecf-d87a-5b31-9292-e0b6651e1f80",
        "questao_id": "5ff827e9-1728-5ca6-a1e0-3d9326565891",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3f48ba33-13a3-51fa-83e7-f098d2bf233e",
        "questao_id": "5ff827e9-1728-5ca6-a1e0-3d9326565891",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "067ed2cb-5c79-5b75-a2bd-b517bd4a6083",
    "idSlug": "l13-pen-esp-029-denunciacao-caluniosa-investigacao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em conformidade com as regras do Código Penal e a jurisprudência dominante: A denunciação caluniosa (Art. 339) configura-se quando o agente dá causa à instauração de investigação contra alguém, imputando-lhe crime ou infração ético-disciplinar de que o sabe inocente.",
    "explicacao": "GABARITO: CERTO. A assertiva é juridicamente exata: A denunciação caluniosa (Art. 339) configura-se quando o agente dá causa à instauração de investigação contra alguém, imputando-lhe crime ou infração ético-disciplinar de que o sabe inocente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "dd379cf1900ddf02dbdf76a1cae8bba2e7c1af2328015b166005ebd2ec46045e",
    "conceito_principal": "Aplicação prática de denunciacao caluniosa investigacao",
    "habilidade_cobrada": "Avaliar assertiva sobre aplicação das normas de Direito Penal Especial",
    "tese_ou_regra": "A denunciação caluniosa (Art. 339) configura-se quando o agente dá causa à instauração de investigação contra alguém, imputando-lhe crime ou infração ético-disciplinar de que o sabe inocente.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "bdf2f8ce-320a-5ead-b671-c5103ec2d5d1",
        "questao_id": "067ed2cb-5c79-5b75-a2bd-b517bd4a6083",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "aea0f122-4364-5a82-9e10-4cd3b158120d",
        "questao_id": "067ed2cb-5c79-5b75-a2bd-b517bd4a6083",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
    "idSlug": "l13-pen-esp-030-falso-testemunho-retratacao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "1e4abd8c-ee06-5498-b128-c3904c4c6696",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Acerca da dogmática e da jurisprudência sumulada dos Tribunais Superiores sobre o tema falso testemunho retratacao, assinale a alternativa juridicamente correta:",
    "explicacao": "GABARITO: A. No falso testemunho (Art. 342), o fato deixa de ser punível se, antes da sentença no processo em que ocorreu o ilícito, o agente se retrata ou declara a verdade (§ 2º).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "215bc19927301d2534e916920ffd5e1bf3a3f7c2128d654f71179801381f1002",
    "conceito_principal": "Regime penal de falso testemunho retratacao",
    "habilidade_cobrada": "Identificar os requisitos típicos do instituto penal examinado",
    "tese_ou_regra": "No falso testemunho (Art. 342), o fato deixa de ser punível se, antes da sentença no processo em que ocorreu o ilícito, o agente se retrata ou declara a verdade (§ 2º).",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "81670237-db2e-59d4-8c77-d3497a9c05f9",
        "questao_id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
        "letra": "A",
        "texto": "No falso testemunho (Art. 342), o fato deixa de ser punível se, antes da sentença no processo em que ocorreu o ilícito, o agente se retrata ou declara a verdade (§ 2º).",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme a literalidade normativa e jurisprudência consolidada."
      },
      {
        "id": "97e015d3-07fa-5a8e-9d14-c12fd0e4dac0",
        "questao_id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
        "letra": "B",
        "texto": "O Código Penal afasta peremptoriamente tal regramento em favor do princípio da insignificância patrimonial ilimitada.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: proposição sem respaldo na legislação penal."
      },
      {
        "id": "18007f42-2b94-57f2-b26e-24d59c5f4bfc",
        "questao_id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
        "letra": "C",
        "texto": "A consumação depende de autorização judicial prévia específica outorgada pelo Juízo das Garantias.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: distorce a sistemática de tipicidade e competência."
      },
      {
        "id": "1713e8c0-16ff-5a21-a4ea-c244ee782ee1",
        "questao_id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
        "letra": "D",
        "texto": "Trata-se de infração de mera conduta insuscetível de qualquer causa de extinção da punibilidade.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: generalização incorreta que contraria o Código Penal."
      },
      {
        "id": "7a59d808-3de2-5266-8820-93fd6cdf497f",
        "questao_id": "076fa4d3-c67d-5828-8dc0-91275226b2a9",
        "letra": "E",
        "texto": "Aplica-se unicamente a servidores federais da ativa, sendo atípica a conduta praticada por particulares.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: restrição indevida não prevista em lei."
      }
    ]
  }
];
