// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 25

export const m03_questoes = [
  {
    "id": "ab6e58c5-4ab8-5544-a060-182f80d97474",
    "idSlug": "l13-proc-001-inquerito-caracteristicas-inquisitivo",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: O inquérito policial é procedimento administrativo de natureza inquisitiva, informativo e preparatório da ação penal, não se aplicando em sua fase preliminar o contraditório pleno e a ampla defesa nos mesmos moldes do processo judicial.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: O inquérito policial é procedimento administrativo de natureza inquisitiva, informativo e preparatório da ação penal, não se aplicando em sua fase preliminar o contraditório pleno e a ampla defesa nos mesmos moldes do processo judicial.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "99ae6e47ed66efbcb764426f0bd72c13680e4d4b6696d0f38a64f1e033eee2ab",
    "conceito_principal": "Aplicação prática de inquerito caracteristicas inquisitivo",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "O inquérito policial é procedimento administrativo de natureza inquisitiva, informativo e preparatório da ação penal, não se aplicando em sua fase preliminar o contraditório pleno e a ampla defesa nos mesmos moldes do processo judicial.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "7a8f5adf-7dba-5eb4-b28b-62cfd2da576c",
        "questao_id": "ab6e58c5-4ab8-5544-a060-182f80d97474",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c813c9e8-36e1-5d0d-910e-3984eb476147",
        "questao_id": "ab6e58c5-4ab8-5544-a060-182f80d97474",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7510ee1c-a57a-506a-8061-57607918ed76",
    "idSlug": "l13-proc-002-inquerito-indisponibilidade-delegado",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A autoridade policial não poderá mandar arquivar autos de inquérito policial (Art. 17 do CPP), em observância ao princípio da indisponibilidade do inquérito policial.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A autoridade policial não poderá mandar arquivar autos de inquérito policial (Art. 17 do CPP), em observância ao princípio da indisponibilidade do inquérito policial.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "caf9a4a99f10905f55bb066c73364593caaabe2d4f2e6ce98d88bcedb298848b",
    "conceito_principal": "Aplicação prática de inquerito indisponibilidade delegado",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A autoridade policial não poderá mandar arquivar autos de inquérito policial (Art. 17 do CPP), em observância ao princípio da indisponibilidade do inquérito policial.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "7c734fbd-8328-512b-a82e-9b78c3ca7bec",
        "questao_id": "7510ee1c-a57a-506a-8061-57607918ed76",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2efb2f65-17ad-5efe-95eb-56d449e82809",
        "questao_id": "7510ee1c-a57a-506a-8061-57607918ed76",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a6f6aece-3317-55a0-99c3-1decc2da6038",
    "idSlug": "l13-proc-003-notitia-criminis-inqualificada-anonima",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A delatio criminis inqualificada (denúncia anônima) não autoriza, por si só, a imediata instauração do inquérito policial, exigindo prévia verificação sumária de sua procedência e plausibilidade pela polícia judiciária (VPI).",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A delatio criminis inqualificada (denúncia anônima) não autoriza, por si só, a imediata instauração do inquérito policial, exigindo prévia verificação sumária de sua procedência e plausibilidade pela polícia judiciária (VPI).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c94749b90f2eb16cb27afeb747db68aa708f7d8725b500e02a49bffe0608fd0c",
    "conceito_principal": "Aplicação prática de notitia criminis inqualificada anonima",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A delatio criminis inqualificada (denúncia anônima) não autoriza, por si só, a imediata instauração do inquérito policial, exigindo prévia verificação sumária de sua procedência e plausibilidade pela polícia judiciária (VPI).",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "19b3dba1-fc12-50ac-9649-f2fcd105e2ba",
        "questao_id": "a6f6aece-3317-55a0-99c3-1decc2da6038",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c4ad2b73-f1d2-5b6f-ac64-988d818b14fa",
        "questao_id": "a6f6aece-3317-55a0-99c3-1decc2da6038",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "c0e9e055-dd12-5108-85e5-dfbcc906d521",
    "idSlug": "l13-proc-004-reproducao-simulada-autoincriminacao",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A reprodução simulada dos fatos (reconstituição do crime - Art. 7º do CPP) não pode contrariar a moralidade e a ordem pública, sendo garantido ao indiciado o direito de recusa à participação com base no princípio nemo tenetur se detegere.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A reprodução simulada dos fatos (reconstituição do crime - Art. 7º do CPP) não pode contrariar a moralidade e a ordem pública, sendo garantido ao indiciado o direito de recusa à participação com base no princípio nemo tenetur se detegere.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "dae836fd85c4777022a5a5a3814d9f1883414a4e5b4ddc598b2e8aa3fd15c601",
    "conceito_principal": "Aplicação prática de reproducao simulada autoincriminacao",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A reprodução simulada dos fatos (reconstituição do crime - Art. 7º do CPP) não pode contrariar a moralidade e a ordem pública, sendo garantido ao indiciado o direito de recusa à participação com base no princípio nemo tenetur se detegere.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "da5626a1-ed2f-56cf-9d1c-dc00c8a1e91e",
        "questao_id": "c0e9e055-dd12-5108-85e5-dfbcc906d521",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "879f7feb-9e28-5883-9045-2822cb5bfe72",
        "questao_id": "c0e9e055-dd12-5108-85e5-dfbcc906d521",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
    "idSlug": "l13-proc-005-sumula-vinculante-14-advogado",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em relação às diretrizes normativas do Código de Processo Penal e à jurisprudência do STF/STJ sobre sumula vinculante 14 advogado, assinale a opção correta:",
    "explicacao": "GABARITO: A. Conforme a Súmula Vinculante 14 do STF, é direito do defensor ter amplo acesso aos elementos de prova que, já documentados em procedimento investigatório, digam respeito ao exercício do direito de defesa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "67160b6d49d6084c533050e1b3d66a2d6a4ccfc3847a77753dd89effcc16a4aa",
    "conceito_principal": "Regime processual de sumula vinculante 14 advogado",
    "habilidade_cobrada": "Identificar as regras de inquérito, ação penal e competência",
    "tese_ou_regra": "Conforme a Súmula Vinculante 14 do STF, é direito do defensor ter amplo acesso aos elementos de prova que, já documentados em procedimento investigatório, digam respeito ao exercício do direito de defesa.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c66ac645-a1d7-5f8a-ba92-8d2db048457a",
        "questao_id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
        "letra": "A",
        "texto": "Conforme a Súmula Vinculante 14 do STF, é direito do defensor ter amplo acesso aos elementos de prova que, já documentados em procedimento investigatório, digam respeito ao exercício do direito de defesa.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme disciplina legal e jurisprudencial dominante."
      },
      {
        "id": "228d212f-bb46-5ba4-9eca-8fb138e22bcc",
        "questao_id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
        "letra": "B",
        "texto": "A autoridade policial pode discricionariamente revogar medidas judiciais irrecorríveis.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: ausência de competência jurisdicional da autoridade policial."
      },
      {
        "id": "a61697d4-a5af-57ac-aea6-be5c2767c459",
        "questao_id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
        "letra": "C",
        "texto": "O titular da ação penal fica vinculado à capitulação jurídica atribuída no relatório policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o MP possui autonomia na formulação da opinio delicti."
      },
      {
        "id": "a8a06625-7397-5f7c-8cb8-7a397b2175ee",
        "questao_id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
        "letra": "D",
        "texto": "O procedimento investigatório preliminar submete-se à obrigatoriedade de contraditório prévio da defesa em todos os atos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o inquérito é marcado pela inquisitividade com as garantias da SV 14."
      },
      {
        "id": "33904db7-2161-52d6-8a3d-0413a33be200",
        "questao_id": "2d6a4652-1748-528e-9dfd-5c2c77b7adbf",
        "letra": "E",
        "texto": "A competência firma-se exclusivamente pelo domicílio da vítima em qualquer modalidade delitiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a regra geral é o local de consumação (Art. 70 do CPP)."
      }
    ]
  },
  {
    "id": "b86bc867-9346-57b7-9d59-6be4ffc12f1a",
    "idSlug": "l13-proc-006-inquerito-dispensabilidade-justa-causa",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: O inquérito policial é peça dispensável, podendo o titular da ação penal oferecer diretamente a denúncia ou queixa-crime se já dispuser de elementos informativos suficientes quanto à materialidade e indícios de autoria.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: O inquérito policial é peça dispensável, podendo o titular da ação penal oferecer diretamente a denúncia ou queixa-crime se já dispuser de elementos informativos suficientes quanto à materialidade e indícios de autoria.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b93fab3d2bc1285811978746f3beabf2abc96cf1baa198ca1455cb9e04c48cbd",
    "conceito_principal": "Aplicação prática de inquerito dispensabilidade justa causa",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "O inquérito policial é peça dispensável, podendo o titular da ação penal oferecer diretamente a denúncia ou queixa-crime se já dispuser de elementos informativos suficientes quanto à materialidade e indícios de autoria.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "14ecd915-d0aa-5175-818d-e3f5d98d1cec",
        "questao_id": "b86bc867-9346-57b7-9d59-6be4ffc12f1a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "37efe6c2-f65c-519d-9f6f-3a05bbe463e3",
        "questao_id": "b86bc867-9346-57b7-9d59-6be4ffc12f1a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "37531db4-c1c0-5deb-8491-7f8f2a9a055a",
    "idSlug": "l13-proc-007-arquivamento-inquerito-stf-adi6298",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: Na sistemática de arquivamento do inquérito policial validada pelo STF nas ADIs do Juiz das Garantias, a manifestação de arquivamento pelo Ministério Público deve ser submetida à instância revisora interna do órgão ministerial em caso de irresignação da vítima.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: Na sistemática de arquivamento do inquérito policial validada pelo STF nas ADIs do Juiz das Garantias, a manifestação de arquivamento pelo Ministério Público deve ser submetida à instância revisora interna do órgão ministerial em caso de irresignação da vítima.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "306c578be8ebc0ac110a08596a14728422723a0de46fa89e13764703eeef4108",
    "conceito_principal": "Aplicação prática de arquivamento inquerito stf adi6298",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "Na sistemática de arquivamento do inquérito policial validada pelo STF nas ADIs do Juiz das Garantias, a manifestação de arquivamento pelo Ministério Público deve ser submetida à instância revisora interna do órgão ministerial em caso de irresignação da vítima.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "30d24621-a55e-5ede-99eb-1bbb0713a3e6",
        "questao_id": "37531db4-c1c0-5deb-8491-7f8f2a9a055a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "79816870-11a8-54fa-9a2d-136cd63e25df",
        "questao_id": "37531db4-c1c0-5deb-8491-7f8f2a9a055a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d0e78ab2-ba4d-50b5-ae9e-7a78b8ffbf3c",
    "idSlug": "l13-proc-008-prazos-conclusao-inquerito-federal",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: No âmbito da Justiça Federal (Lei 5.010/66), o prazo para conclusão do inquérito policial é de 15 dias para investigado preso (prorrogável por mais 15) e de 30 dias para investigado solto.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: No âmbito da Justiça Federal (Lei 5.010/66), o prazo para conclusão do inquérito policial é de 15 dias para investigado preso (prorrogável por mais 15) e de 30 dias para investigado solto.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4b55fcc517784afc267be863c239820159570bc83df6ddbe3eb6007bb3f97bf5",
    "conceito_principal": "Aplicação prática de prazos conclusao inquerito federal",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "No âmbito da Justiça Federal (Lei 5.010/66), o prazo para conclusão do inquérito policial é de 15 dias para investigado preso (prorrogável por mais 15) e de 30 dias para investigado solto.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "7f0d5954-3af6-5fa6-a6c4-b1da1ee91ed4",
        "questao_id": "d0e78ab2-ba4d-50b5-ae9e-7a78b8ffbf3c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5aaa2630-2ed1-5eeb-b532-3775db1cd9d1",
        "questao_id": "d0e78ab2-ba4d-50b5-ae9e-7a78b8ffbf3c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b70a216e-f480-5afe-8add-2fe7f8de1d26",
    "idSlug": "l13-proc-009-acao-penal-publica-incondicionada-obrigatoriedade",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A ação penal pública incondicionada rege-se pelo princípio da obrigatoriedade ou legalidade processual, devendo o Ministério Público ajuizar a denúncia sempre que presentes os pressupostos processuais e a justa causa.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A ação penal pública incondicionada rege-se pelo princípio da obrigatoriedade ou legalidade processual, devendo o Ministério Público ajuizar a denúncia sempre que presentes os pressupostos processuais e a justa causa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "76ff53548a76a0d7c27cd7911de0f2a757ca6a6d3f323c3f28dbefb5fda37fce",
    "conceito_principal": "Aplicação prática de acao penal publica incondicionada obrigatoriedade",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A ação penal pública incondicionada rege-se pelo princípio da obrigatoriedade ou legalidade processual, devendo o Ministério Público ajuizar a denúncia sempre que presentes os pressupostos processuais e a justa causa.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "7ef57d34-1554-5c08-8ac9-e88af5b87856",
        "questao_id": "b70a216e-f480-5afe-8add-2fe7f8de1d26",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9b67dad5-5579-5455-bb08-ebb2eeceb552",
        "questao_id": "b70a216e-f480-5afe-8add-2fe7f8de1d26",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
    "idSlug": "l13-proc-010-representacao-prazo-decadencial",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em relação às diretrizes normativas do Código de Processo Penal e à jurisprudência do STF/STJ sobre representacao prazo decadencial, assinale a opção correta:",
    "explicacao": "GABARITO: A. O direito de representação do ofendido na ação penal pública condicionada decai no prazo improrrogável de 6 meses, contado do dia em que vier a saber quem é o autor do crime (Art. 38 do CPP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "85d9630b25cdb1fa721361b43489b083e06dfb59d0887c208a63f21e014b2df3",
    "conceito_principal": "Regime processual de representacao prazo decadencial",
    "habilidade_cobrada": "Identificar as regras de inquérito, ação penal e competência",
    "tese_ou_regra": "O direito de representação do ofendido na ação penal pública condicionada decai no prazo improrrogável de 6 meses, contado do dia em que vier a saber quem é o autor do crime (Art. 38 do CPP).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b34ff56b-1681-5757-b22a-884f2cba5174",
        "questao_id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
        "letra": "A",
        "texto": "O direito de representação do ofendido na ação penal pública condicionada decai no prazo improrrogável de 6 meses, contado do dia em que vier a saber quem é o autor do crime (Art. 38 do CPP).",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme disciplina legal e jurisprudencial dominante."
      },
      {
        "id": "34278e81-e3d3-5121-914c-7d1bc7207efd",
        "questao_id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
        "letra": "B",
        "texto": "A autoridade policial pode discricionariamente revogar medidas judiciais irrecorríveis.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: ausência de competência jurisdicional da autoridade policial."
      },
      {
        "id": "aed4426b-439d-5639-abdf-7b3a6664c215",
        "questao_id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
        "letra": "C",
        "texto": "O titular da ação penal fica vinculado à capitulação jurídica atribuída no relatório policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o MP possui autonomia na formulação da opinio delicti."
      },
      {
        "id": "e250b73b-7200-5b9e-b152-ae35bc03c8ae",
        "questao_id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
        "letra": "D",
        "texto": "O procedimento investigatório preliminar submete-se à obrigatoriedade de contraditório prévio da defesa em todos os atos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o inquérito é marcado pela inquisitividade com as garantias da SV 14."
      },
      {
        "id": "77ca581c-b674-54b3-8a11-5698b75e782d",
        "questao_id": "ef9ecd88-3006-56c4-9f44-8829e22df8d1",
        "letra": "E",
        "texto": "A competência firma-se exclusivamente pelo domicílio da vítima em qualquer modalidade delitiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a regra geral é o local de consumação (Art. 70 do CPP)."
      }
    ]
  },
  {
    "id": "3db7e642-c490-527b-872f-214851d347a5",
    "idSlug": "l13-proc-011-retratacao-representacao-limite",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A representação será irretratável depois de oferecida a denúncia (Art. 25 do CPP), ressalvada a disciplina protetiva especial da Lei Maria da Penha que exige audiência específica antes do recebimento da denúncia.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A representação será irretratável depois de oferecida a denúncia (Art. 25 do CPP), ressalvada a disciplina protetiva especial da Lei Maria da Penha que exige audiência específica antes do recebimento da denúncia.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "acff56e8346e68c21eff46a72e6691f6c9e04b735b08c1a3598a3c60bc388df6",
    "conceito_principal": "Aplicação prática de retratacao representacao limite",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A representação será irretratável depois de oferecida a denúncia (Art. 25 do CPP), ressalvada a disciplina protetiva especial da Lei Maria da Penha que exige audiência específica antes do recebimento da denúncia.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "8bc9cfb8-371e-52eb-a6f0-1c586a9a5592",
        "questao_id": "3db7e642-c490-527b-872f-214851d347a5",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "940a350d-d055-5409-b18b-e4be3b07a05c",
        "questao_id": "3db7e642-c490-527b-872f-214851d347a5",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f3f2814c-8f82-58ad-8927-010f9fece7eb",
    "idSlug": "l13-proc-012-acao-penal-privada-subsidiaria-prazo",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A ação penal privada subsidiária da pública é cabível quando o Ministério Público não oferecer a denúncia nem determinar o arquivamento ou diligências no prazo legal, iniciando-se o prazo decadencial de 6 meses após o esgotamento do prazo do MP.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A ação penal privada subsidiária da pública é cabível quando o Ministério Público não oferecer a denúncia nem determinar o arquivamento ou diligências no prazo legal, iniciando-se o prazo decadencial de 6 meses após o esgotamento do prazo do MP.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "dba11329de9fd42dc705cf79dddd0bfbe873ffcd11e65a175544f528a5512dbd",
    "conceito_principal": "Aplicação prática de acao penal privada subsidiaria prazo",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A ação penal privada subsidiária da pública é cabível quando o Ministério Público não oferecer a denúncia nem determinar o arquivamento ou diligências no prazo legal, iniciando-se o prazo decadencial de 6 meses após o esgotamento do prazo do MP.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "98dbaeae-e826-5f1e-b0d3-41282e7f237e",
        "questao_id": "f3f2814c-8f82-58ad-8927-010f9fece7eb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "690668b4-4f7e-5bef-967b-45c2dbd9c36f",
        "questao_id": "f3f2814c-8f82-58ad-8927-010f9fece7eb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8e071b20-b9d7-55aa-a0d0-ed486c88f7b8",
    "idSlug": "l13-proc-013-peremptio-acao-privada-morte",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: Na ação penal exclusivamente privada, sobrevindo a morte do querelante sem habilitação de sucessores no prazo legal de 60 dias, opera-se a perempção com a consequente extinção da punibilidade (Art. 60, II, do CPP).",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: Na ação penal exclusivamente privada, sobrevindo a morte do querelante sem habilitação de sucessores no prazo legal de 60 dias, opera-se a perempção com a consequente extinção da punibilidade (Art. 60, II, do CPP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "18d69d0909c2c09d3b4d98771983bbdfffba588c08108ebdc16def1644d394dd",
    "conceito_principal": "Aplicação prática de peremptio acao privada morte",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "Na ação penal exclusivamente privada, sobrevindo a morte do querelante sem habilitação de sucessores no prazo legal de 60 dias, opera-se a perempção com a consequente extinção da punibilidade (Art. 60, II, do CPP).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "52a3c630-cd69-5f01-b120-4bbd9517a099",
        "questao_id": "8e071b20-b9d7-55aa-a0d0-ed486c88f7b8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d03a8e34-ccea-5b66-971b-d005d1052db9",
        "questao_id": "8e071b20-b9d7-55aa-a0d0-ed486c88f7b8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a411234d-15e5-549c-b23c-9fbefece9de4",
    "idSlug": "l13-proc-014-principio-indivisibilidade-acao-privada",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: O princípio da indivisibilidade rege a ação penal privada, não podendo o querelante escolher contra qual dos coautores irá ajuizar a queixa-crime, sob pena de renúncia tácita estensível a todos.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: O princípio da indivisibilidade rege a ação penal privada, não podendo o querelante escolher contra qual dos coautores irá ajuizar a queixa-crime, sob pena de renúncia tácita estensível a todos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e5b5ca8ac5481e294c3d4cd53a7dcb3e2d19e382704aecc1d2a44c91834e1191",
    "conceito_principal": "Aplicação prática de principio indivisibilidade acao privada",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "O princípio da indivisibilidade rege a ação penal privada, não podendo o querelante escolher contra qual dos coautores irá ajuizar a queixa-crime, sob pena de renúncia tácita estensível a todos.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "0b00b2a3-8113-5c4d-bf17-c64ceaa8e57c",
        "questao_id": "a411234d-15e5-549c-b23c-9fbefece9de4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d7c4b76f-50cd-5e24-bb77-0cc1341773a1",
        "questao_id": "a411234d-15e5-549c-b23c-9fbefece9de4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
    "idSlug": "l13-proc-015-anpp-requisitos-cumulativos",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em relação às diretrizes normativas do Código de Processo Penal e à jurisprudência do STF/STJ sobre anpp requisitos cumulativos, assinale a opção correta:",
    "explicacao": "GABARITO: A. O Acordo de Não Persecução Penal (ANPP - Art. 28-A do CPP) exige confissão formal e circunstanciada de infração penal sem violência ou grave ameaça e com pena mínima cominada inferior a 4 anos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e7f72e7b3d3e86f838080159a2336115539c39125a034e992e4118b21b55d0e9",
    "conceito_principal": "Regime processual de anpp requisitos cumulativos",
    "habilidade_cobrada": "Identificar as regras de inquérito, ação penal e competência",
    "tese_ou_regra": "O Acordo de Não Persecução Penal (ANPP - Art. 28-A do CPP) exige confissão formal e circunstanciada de infração penal sem violência ou grave ameaça e com pena mínima cominada inferior a 4 anos.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "6605a7bf-5676-5614-bccd-b0e967360005",
        "questao_id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
        "letra": "A",
        "texto": "O Acordo de Não Persecução Penal (ANPP - Art. 28-A do CPP) exige confissão formal e circunstanciada de infração penal sem violência ou grave ameaça e com pena mínima cominada inferior a 4 anos.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme disciplina legal e jurisprudencial dominante."
      },
      {
        "id": "98c7c61c-8416-56c3-9b8a-5ec492a24e79",
        "questao_id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
        "letra": "B",
        "texto": "A autoridade policial pode discricionariamente revogar medidas judiciais irrecorríveis.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: ausência de competência jurisdicional da autoridade policial."
      },
      {
        "id": "90c71360-4150-5259-8998-b7e3df1a6af2",
        "questao_id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
        "letra": "C",
        "texto": "O titular da ação penal fica vinculado à capitulação jurídica atribuída no relatório policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o MP possui autonomia na formulação da opinio delicti."
      },
      {
        "id": "c68ab7f7-73d5-5fb4-883d-fce457e8c150",
        "questao_id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
        "letra": "D",
        "texto": "O procedimento investigatório preliminar submete-se à obrigatoriedade de contraditório prévio da defesa em todos os atos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o inquérito é marcado pela inquisitividade com as garantias da SV 14."
      },
      {
        "id": "050dc3fd-e0ea-55b3-a102-dbd817cf1bed",
        "questao_id": "bdcd2a4d-b04f-5e8a-890f-2d7dd4aad967",
        "letra": "E",
        "texto": "A competência firma-se exclusivamente pelo domicílio da vítima em qualquer modalidade delitiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a regra geral é o local de consumação (Art. 70 do CPP)."
      }
    ]
  },
  {
    "id": "eff94b8b-51cb-5777-a114-250249ac0573",
    "idSlug": "l13-proc-016-competencia-ratione-loci-teoria-resultado",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A competência de foro territorial (ratione loci) firma-se, como regra geral no processo penal brasileiro, pelo lugar em que se consumar a infração (Art. 70 do CPP - teoria do resultado).",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A competência de foro territorial (ratione loci) firma-se, como regra geral no processo penal brasileiro, pelo lugar em que se consumar a infração (Art. 70 do CPP - teoria do resultado).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b2179849fd384675d5e04414cc12bf5b6c05758599bf682c924ae00e3fff9fe4",
    "conceito_principal": "Aplicação prática de competencia ratione loci teoria resultado",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A competência de foro territorial (ratione loci) firma-se, como regra geral no processo penal brasileiro, pelo lugar em que se consumar a infração (Art. 70 do CPP - teoria do resultado).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "d670d02c-6e00-5688-b8a8-89c9f87f525f",
        "questao_id": "eff94b8b-51cb-5777-a114-250249ac0573",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7e13c2a6-f04e-5720-ba8e-d29969a1e95b",
        "questao_id": "eff94b8b-51cb-5777-a114-250249ac0573",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5b4d2dda-ca18-5a12-bb17-af80c93fcc13",
    "idSlug": "l13-proc-017-competencia-crimes-estelionato-deposito",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: Com a alteração do Art. 70, § 4º, do CPP, no crime de estelionato praticado mediante depósito, transferência de valores ou cheque sem provisão, a competência é do juízo do local do domicílio da vítima.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: Com a alteração do Art. 70, § 4º, do CPP, no crime de estelionato praticado mediante depósito, transferência de valores ou cheque sem provisão, a competência é do juízo do local do domicílio da vítima.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5e65dcf6ee112a226477f1c12f6f28177105526cbaa754a77b7d9c302f8907c8",
    "conceito_principal": "Aplicação prática de competencia crimes estelionato deposito",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "Com a alteração do Art. 70, § 4º, do CPP, no crime de estelionato praticado mediante depósito, transferência de valores ou cheque sem provisão, a competência é do juízo do local do domicílio da vítima.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "58e67dec-217e-5d53-8550-18372faf16d0",
        "questao_id": "5b4d2dda-ca18-5a12-bb17-af80c93fcc13",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3c622b44-2d47-5f25-8c92-8fe95bb7875d",
        "questao_id": "5b4d2dda-ca18-5a12-bb17-af80c93fcc13",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a61ed406-c2e0-50d9-b91e-f9abaced533e",
    "idSlug": "l13-proc-018-competencia-juri-crimes-conexos",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A competência do Tribunal do Júri para julgamento de crimes dolosos contra a vida atrai os crimes comuns conexos por força da vis attractiva constitucionalmente assegurada.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A competência do Tribunal do Júri para julgamento de crimes dolosos contra a vida atrai os crimes comuns conexos por força da vis attractiva constitucionalmente assegurada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "42b17e1ac6ffd39e57c86e9210170f8a0cefe3afe87ca1a8b324c90ab1c15d56",
    "conceito_principal": "Aplicação prática de competencia juri crimes conexos",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A competência do Tribunal do Júri para julgamento de crimes dolosos contra a vida atrai os crimes comuns conexos por força da vis attractiva constitucionalmente assegurada.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "2e7bf15f-d882-523a-9ba0-c54e3ce19025",
        "questao_id": "a61ed406-c2e0-50d9-b91e-f9abaced533e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7be53e16-af40-5197-b03b-8e3212747c55",
        "questao_id": "a61ed406-c2e0-50d9-b91e-f9abaced533e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "4cc92de8-4216-5e4f-95b8-4f2baf7a96b6",
    "idSlug": "l13-proc-019-perpetuatio-jurisdictionis-desclassificacao",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: Operada a desclassificação do crime doloso contra a vida para outro não doloso na primeira fase do rito do Júri (pronúncia), os autos devem ser remetidos ao juiz singular competente (Art. 419 do CPP).",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: Operada a desclassificação do crime doloso contra a vida para outro não doloso na primeira fase do rito do Júri (pronúncia), os autos devem ser remetidos ao juiz singular competente (Art. 419 do CPP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "48df237f76725f007d8bb9ac0f69db92f2b1b7231a90e94a2558b570fe38d09b",
    "conceito_principal": "Aplicação prática de perpetuatio jurisdictionis desclassificacao",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "Operada a desclassificação do crime doloso contra a vida para outro não doloso na primeira fase do rito do Júri (pronúncia), os autos devem ser remetidos ao juiz singular competente (Art. 419 do CPP).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "59020c64-f969-5a04-a0f9-67f5a865c35d",
        "questao_id": "4cc92de8-4216-5e4f-95b8-4f2baf7a96b6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "aeaecf99-0c5e-5f14-90fe-f9910a65f915",
        "questao_id": "4cc92de8-4216-5e4f-95b8-4f2baf7a96b6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
    "idSlug": "l13-proc-020-competencia-justica-federal-criterios",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em relação às diretrizes normativas do Código de Processo Penal e à jurisprudência do STF/STJ sobre competencia justica federal criterios, assinale a opção correta:",
    "explicacao": "GABARITO: A. Compete à Justiça Federal processar e julgar as infrações penais praticadas em detrimento de bens, serviços ou interesse da União ou de suas entidades autárquicas ou empresas públicas, excluídas as sociedades de economia mista (Art. 109, IV, da CF e Súmula 518/STJ).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "12836b67dc4de8f0c5b9c0ff4ebd99589f4837bd871101ee95095fe51e8c86d5",
    "conceito_principal": "Regime processual de competencia justica federal criterios",
    "habilidade_cobrada": "Identificar as regras de inquérito, ação penal e competência",
    "tese_ou_regra": "Compete à Justiça Federal processar e julgar as infrações penais praticadas em detrimento de bens, serviços ou interesse da União ou de suas entidades autárquicas ou empresas públicas, excluídas as sociedades de economia mista (Art. 109, IV, da CF e Súmula 518/STJ).",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "3707f963-5794-56e9-8511-6b9ba53dcd7c",
        "questao_id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
        "letra": "A",
        "texto": "Compete à Justiça Federal processar e julgar as infrações penais praticadas em detrimento de bens, serviços ou interesse da União ou de suas entidades autárquicas ou empresas públicas, excluídas as sociedades de economia mista (Art. 109, IV, da CF e Súmula 518/STJ).",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme disciplina legal e jurisprudencial dominante."
      },
      {
        "id": "bf6419a6-b2af-55d6-8833-b0575ce9ca68",
        "questao_id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
        "letra": "B",
        "texto": "A autoridade policial pode discricionariamente revogar medidas judiciais irrecorríveis.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: ausência de competência jurisdicional da autoridade policial."
      },
      {
        "id": "9af45892-d49b-5726-9aec-0e5106d1bbf9",
        "questao_id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
        "letra": "C",
        "texto": "O titular da ação penal fica vinculado à capitulação jurídica atribuída no relatório policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o MP possui autonomia na formulação da opinio delicti."
      },
      {
        "id": "3b58dcf5-591c-5edd-b157-6ea9f278d4a5",
        "questao_id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
        "letra": "D",
        "texto": "O procedimento investigatório preliminar submete-se à obrigatoriedade de contraditório prévio da defesa em todos os atos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o inquérito é marcado pela inquisitividade com as garantias da SV 14."
      },
      {
        "id": "b583f40c-61cb-543e-a3d6-6b1aa6dcf539",
        "questao_id": "d6fe17c0-59ce-51e5-9144-2d811805f89d",
        "letra": "E",
        "texto": "A competência firma-se exclusivamente pelo domicílio da vítima em qualquer modalidade delitiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a regra geral é o local de consumação (Art. 70 do CPP)."
      }
    ]
  },
  {
    "id": "84578572-99d0-5233-a007-d45628b9ba04",
    "idSlug": "l13-proc-021-foro-prerrogativa-funcao-stf-limites",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: O foro por prerrogativa de função aplica-se apenas aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas, prorrogando-se a competência se a instrução já se encerrou com intimação para alegações finais.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: O foro por prerrogativa de função aplica-se apenas aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas, prorrogando-se a competência se a instrução já se encerrou com intimação para alegações finais.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f9a8a4d097f15b57f7bb5155988126a484fa3125a2515c7ecf11c2c60d8ee0d6",
    "conceito_principal": "Aplicação prática de foro prerrogativa funcao stf limites",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "O foro por prerrogativa de função aplica-se apenas aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas, prorrogando-se a competência se a instrução já se encerrou com intimação para alegações finais.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "369ad351-71b2-5c57-892d-ceb269c1018a",
        "questao_id": "84578572-99d0-5233-a007-d45628b9ba04",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c65c6583-e447-51f0-814d-8efc7761edb4",
        "questao_id": "84578572-99d0-5233-a007-d45628b9ba04",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "501b481e-084a-5d9a-9739-23e8f068ef40",
    "idSlug": "l13-proc-022-conexao-intersubjetiva-concursal",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A conexão intersubjetiva por concurso (Art. 76, I, do CPP) ocorre quando duas ou mais infrações forem praticadas por várias pessoas em colaboração recíproca.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A conexão intersubjetiva por concurso (Art. 76, I, do CPP) ocorre quando duas ou mais infrações forem praticadas por várias pessoas em colaboração recíproca.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c848f0d6b279f09e1bab9509e07ec2beb7a0097c92c77aace271ba6da8b768d4",
    "conceito_principal": "Aplicação prática de conexao intersubjetiva concursal",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A conexão intersubjetiva por concurso (Art. 76, I, do CPP) ocorre quando duas ou mais infrações forem praticadas por várias pessoas em colaboração recíproca.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "205cf152-101c-5ea4-97b8-47c0b315708b",
        "questao_id": "501b481e-084a-5d9a-9739-23e8f068ef40",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "03dbc75f-e387-5428-abaf-ac16520f2002",
        "questao_id": "501b481e-084a-5d9a-9739-23e8f068ef40",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f901d9a8-d8a2-57a8-8ad8-8d04fcc473b2",
    "idSlug": "l13-proc-023-prevencao-juizo-competencia-subsidiaria",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "c8dc15e6-c026-5d07-b054-7bda9bc971fb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: A competência por prevenção firma-se quando, concorrendo dois ou mais juízes igualmente competentes, um deles tiver antecedido aos outros na prática de algum ato do processo ou de medida cautelar anterior.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: A competência por prevenção firma-se quando, concorrendo dois ou mais juízes igualmente competentes, um deles tiver antecedido aos outros na prática de algum ato do processo ou de medida cautelar anterior.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "01df906d909958ace2cb951071719263b69ee72c35b2768e294a3594ea81be99",
    "conceito_principal": "Aplicação prática de prevencao juizo competencia subsidiaria",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "A competência por prevenção firma-se quando, concorrendo dois ou mais juízes igualmente competentes, um deles tiver antecedido aos outros na prática de algum ato do processo ou de medida cautelar anterior.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "29825842-3046-5d5e-9756-d198ad79b666",
        "questao_id": "f901d9a8-d8a2-57a8-8ad8-8d04fcc473b2",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f2e899fe-bedf-5964-bbb2-38103a3d53b4",
        "questao_id": "f901d9a8-d8a2-57a8-8ad8-8d04fcc473b2",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "1f449a01-0289-5ea1-90bc-3f291892f646",
    "idSlug": "l13-proc-024-mutatio-libelli-aditamento-denuncia",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "3b2a1eda-d272-53f8-b66a-41ef31036863",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Julgue a assertiva sob a ótica do Direito Processual Penal: Na mutatio libelli (Art. 384 do CPP), surgindo prova nova em juízo de elementar ou circunstância não contida na denúncia que importe em nova definição jurídica com pena mais grave, é obrigatório o aditamento pelo Ministério Público.",
    "explicacao": "GABARITO: CERTO. A assertiva é correta: Na mutatio libelli (Art. 384 do CPP), surgindo prova nova em juízo de elementar ou circunstância não contida na denúncia que importe em nova definição jurídica com pena mais grave, é obrigatório o aditamento pelo Ministério Público.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4b36155b3b803ead2ed98396b1d383bca0b8aac4a909589efadf3565bf5403ff",
    "conceito_principal": "Aplicação prática de mutatio libelli aditamento denuncia",
    "habilidade_cobrada": "Julgar assertiva de inquérito e ação penal",
    "tese_ou_regra": "Na mutatio libelli (Art. 384 do CPP), surgindo prova nova em juízo de elementar ou circunstância não contida na denúncia que importe em nova definição jurídica com pena mais grave, é obrigatório o aditamento pelo Ministério Público.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "c62c48eb-776b-5e97-96cc-8f10a7fea6fa",
        "questao_id": "1f449a01-0289-5ea1-90bc-3f291892f646",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "96fcb3f9-04e2-58ed-886e-7d8ef9f380f6",
        "questao_id": "1f449a01-0289-5ea1-90bc-3f291892f646",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ef37a372-8b81-5e07-8902-ad8247d64319",
    "idSlug": "l13-proc-025-juiz-das-garantias-competencia-fim",
    "disciplina_id": "18877540-1bd4-5e15-b497-20b2582bc4d8",
    "assunto_id": "ba014b79-7c6e-5279-a517-abaeceb2771f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em relação às diretrizes normativas do Código de Processo Penal e à jurisprudência do STF/STJ sobre juiz das garantias competencia fim, assinale a opção correta:",
    "explicacao": "GABARITO: A. A competência funcional do Juiz das Garantias cessa com o recebimento da denúncia ou queixa, momento a partir do qual as decisões cabem ao juiz da instrução e julgamento (Art. 3º-C do CPP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e06644d87258f151aece53452f20a2665fa6d1a0d9a5468f88f5f596d3f21b7a",
    "conceito_principal": "Regime processual de juiz das garantias competencia fim",
    "habilidade_cobrada": "Identificar as regras de inquérito, ação penal e competência",
    "tese_ou_regra": "A competência funcional do Juiz das Garantias cessa com o recebimento da denúncia ou queixa, momento a partir do qual as decisões cabem ao juiz da instrução e julgamento (Art. 3º-C do CPP).",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "5cc16782-45a6-5101-9410-eeffe670f72f",
        "questao_id": "ef37a372-8b81-5e07-8902-ad8247d64319",
        "letra": "A",
        "texto": "A competência funcional do Juiz das Garantias cessa com o recebimento da denúncia ou queixa, momento a partir do qual as decisões cabem ao juiz da instrução e julgamento (Art. 3º-C do CPP).",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Alternativa correta conforme disciplina legal e jurisprudencial dominante."
      },
      {
        "id": "4b238af4-2e02-5b39-bb45-77d61a5affc4",
        "questao_id": "ef37a372-8b81-5e07-8902-ad8247d64319",
        "letra": "B",
        "texto": "A autoridade policial pode discricionariamente revogar medidas judiciais irrecorríveis.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta: ausência de competência jurisdicional da autoridade policial."
      },
      {
        "id": "a6e300cb-a643-5ef6-9800-b577830063a6",
        "questao_id": "ef37a372-8b81-5e07-8902-ad8247d64319",
        "letra": "C",
        "texto": "O titular da ação penal fica vinculado à capitulação jurídica atribuída no relatório policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: o MP possui autonomia na formulação da opinio delicti."
      },
      {
        "id": "9e4ef15e-7c29-5f7d-9494-a807a41d1be4",
        "questao_id": "ef37a372-8b81-5e07-8902-ad8247d64319",
        "letra": "D",
        "texto": "O procedimento investigatório preliminar submete-se à obrigatoriedade de contraditório prévio da defesa em todos os atos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: o inquérito é marcado pela inquisitividade com as garantias da SV 14."
      },
      {
        "id": "67519972-9126-543e-8886-9964c3c31856",
        "questao_id": "ef37a372-8b81-5e07-8902-ad8247d64319",
        "letra": "E",
        "texto": "A competência firma-se exclusivamente pelo domicílio da vítima em qualquer modalidade delitiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: a regra geral é o local de consumação (Art. 70 do CPP)."
      }
    ]
  }
];
