// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 27

export const m06_questoes = [
  {
    "id": "12437f2a-5db9-595a-b600-b5f2a0ccf91b",
    "idSlug": "l13-029-abuso-autoridade-elemento-subjetivo-especial",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "As condutas descritas na Lei nº 13.869/2019 somente constituem crime de abuso de autoridade quando praticadas pelo agente com a finalidade específica de prejudicar outrem ou beneficiar a si mesmo ou a terceiro, ou, ainda, por mero capricho ou satisfação pessoal, inexistindo modalidade culposa na referida legislação.",
    "explicacao": "GABARITO: CERTO. O art. 1º, § 1º da Lei 13.869/19 exige o dolo específico (finalidade especial de agir): prejudicar outrem, beneficiar a si/terceiro, ou por mero capricho/satisfação pessoal. Não há crimes culposos na lei.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d8d01d226ac07784278be9aecf2ec57730ff14eb86b397e22794a86b06f8c69e",
    "conceito_principal": "Elemento subjetivo especial na Lei de Abuso de Autoridade",
    "habilidade_cobrada": "Identificar o dolo específico exigido em todos os crimes da Lei 13.869/19",
    "tese_ou_regra": "Os crimes de abuso de autoridade exigem dolo específico de prejudicar, beneficiar ou agir por capricho ou satisfação pessoal.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "89c4b207-98e2-508a-a294-5d24b17fffb1",
        "questao_id": "12437f2a-5db9-595a-b600-b5f2a0ccf91b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "db2ebee6-7c2b-5863-ae1f-03a1627f23e4",
        "questao_id": "12437f2a-5db9-595a-b600-b5f2a0ccf91b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d89d858e-3a2f-5c9f-a1d9-e8b067048c2a",
    "idSlug": "l13-030-abuso-autoridade-divergencia-interpretativa",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A divergência na interpretação de lei ou na avaliação de fatos e provas não configura, por si só, crime de abuso de autoridade.",
    "explicacao": "GABARITO: CERTO. Trata-se da expressa vedação ao chamado 'crime de hermenêutica', insculpida no art. 1º, § 2º da Lei nº 13.869/2019.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9708f09845c0d82dbaa34ec75824aab794c2d2c44f004b6d51eb5586394ec1be",
    "conceito_principal": "Vedação ao crime de hermenêutica",
    "habilidade_cobrada": "Reconhecer que divergência interpretativa não configura abuso de autoridade",
    "tese_ou_regra": "A divergência na interpretação de lei ou na valoração de provas não configura abuso de autoridade (art. 1º, § 2º, Lei 13.869/19).",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "9d1e43d8-aa80-570f-9255-b60b669f4d05",
        "questao_id": "d89d858e-3a2f-5c9f-a1d9-e8b067048c2a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d3c7cb49-ffcc-5765-a092-ad1732cbb3d9",
        "questao_id": "d89d858e-3a2f-5c9f-a1d9-e8b067048c2a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "2dfa20c9-b8ff-59b8-bb3f-3a482635ba6b",
    "idSlug": "l13-031-abuso-autoridade-busca-mandado-noturno",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Incorre no crime de violação de domicílio por abuso de autoridade a autoridade policial que cumpre mandado de busca e apreensão domiciliar entre as 21 (vinte e uma) horas e as 5 (cinco) horas, ainda que amparada por expressa ordem judicial, ressalvadas as hipóteses constitucionais de flagrante delito ou socorro.",
    "explicacao": "GABARITO: CERTO. O art. 22, § 1º, III da Lei 13.869/19 tipifica expressamente o cumprimento de mandado de busca e apreensão domiciliar entre 21h e 5h.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "44442b0b5a5f79fbb0d3f80a09fcce9b7b0c120f61da0fa1c410f09f3f2e4aeb",
    "conceito_principal": "Horário proibido para cumprimento de mandado de busca domiciliar",
    "habilidade_cobrada": "Aplicar o marco temporal legal do cumprimento de mandados domiciliares (art. 22, § 1º, III)",
    "tese_ou_regra": "Cumprir mandado de busca e apreensão domiciliar entre as 21h e 5h constitui crime de abuso de autoridade.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "84935918-fc63-54d1-8f9b-0e319f51fbbe",
        "questao_id": "2dfa20c9-b8ff-59b8-bb3f-3a482635ba6b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "363c4252-8804-540f-86c0-26ef2cf42e22",
        "questao_id": "2dfa20c9-b8ff-59b8-bb3f-3a482635ba6b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "53095ad3-7d19-5162-8c42-a249f7bb57fb",
    "idSlug": "l13-032-maria-penha-unidade-domestica-coabitacao",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A configuração de violência doméstica e familiar contra a mulher na hipótese de relação íntima de afeto independe de coabitação atual ou passada entre o agressor e a vítima, aplicando-se a Lei Maria da Penha inclusive em relacionamentos de namoro já rompidos.",
    "explicacao": "GABARITO: CERTO. O art. 5º, III da Lei 11.340/06 e a Súmula 600 do STJ preveem expressamente que a violência doméstica independe de coabitação.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b3a26ee1e9188e8d6f653411fcfccdd066f5eae0f46d53196de4a8d1ca56a634",
    "conceito_principal": "Desnecessidade de coabitação na Lei Maria da Penha",
    "habilidade_cobrada": "Aplicar a Súmula 600 do STJ às relações de namoro e afeto na Lei 11.340/06",
    "tese_ou_regra": "A aplicação da Lei Maria da Penha independe de coabitação entre autor e vítima (Súmula 600/STJ).",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b4679dfc-2381-5ca7-8c7c-f76789e726a2",
        "questao_id": "53095ad3-7d19-5162-8c42-a249f7bb57fb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7ccf6cba-491f-54f0-8c5a-0f447a8b354f",
        "questao_id": "53095ad3-7d19-5162-8c42-a249f7bb57fb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e9b778a7-af1d-5e27-ac77-080cc26a4abb",
    "idSlug": "l13-033-maria-penha-afastamento-lar-policial",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Verificada a existência de risco atual ou iminente à vida ou à integridade física da mulher em situação de violência doméstica, o agressor será imediatamente afastado do lar pelo Delegado de Polícia quando o Município não for sede de comarca; e pelo policial militar ou civil quando o Município não for sede de comarca e não houver delegado disponível no momento do atendimento, devendo o juiz ser comunicado no prazo máximo de 24 horas para decidir sobre a manutenção da medida.",
    "explicacao": "GABARITO: CERTO. Conforme o art. 12-C da Lei 11.340/06 (com redação da Lei 13.827/19), o afastamento do lar pode ser determinado pelo delegado (quando não sede de comarca) ou pelo policial (quando não comarca e sem delegado), com comunicação em 24 horas ao juiz.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b58cc06c55e281ebac057be54cda15d334c2ce9cc824d4e1a783a6a55335727f",
    "conceito_principal": "Medida protetiva de afastamento cautelar por autoridade policial",
    "habilidade_cobrada": "Compreender os critérios subsidiários de aplicação do art. 12-C da Lei Maria da Penha",
    "tese_ou_regra": "O art. 12-C autoriza o afastamento do agressor por delegado ou policial em comarcas sem juiz de plantão, com validação judicial em 24h.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "c1031515-be5c-52c0-87ad-cceba2af7955",
        "questao_id": "e9b778a7-af1d-5e27-ac77-080cc26a4abb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6f471f39-72d0-522c-a4a0-83f08a82e1db",
        "questao_id": "e9b778a7-af1d-5e27-ac77-080cc26a4abb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ebb6bb09-50b9-5591-91b7-56ea73c94e2e",
    "idSlug": "l13-034-maria-penha-descumprimento-protetiva-fianca",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "No crime de descumprimento de medidas protetivas de urgência (art. 24-A da Lei nº 11.340/2006), a concessão de fiança na fase de flagrante delito é ato privativo da autoridade judicial, não podendo o Delegado de Polícia arbitrá-la, ainda que a pena máxima cominada seja de até 2 (dois) anos de detenção.",
    "explicacao": "GABARITO: CERTO. O art. 24-A, § 2º da Lei 11.340/06 estabelece que na prisão em flagrante por descumprimento de medida protetiva, apenas a autoridade judicial poderá conceder fiança.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b555e62d756da812646c056a151f4b49fbeb8bc7a85a91fd0022d8e435afcbb6",
    "conceito_principal": "Reserva de jurisdição para fiança no art. 24-A da Lei Maria da Penha",
    "habilidade_cobrada": "Identificar a vedação de concessão de fiança pelo delegado no crime do art. 24-A",
    "tese_ou_regra": "No crime de descumprimento de medidas protetivas, a fiança somente pode ser concedida pelo juiz de direito.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "159957d5-53bb-55fc-885c-728a490f0b81",
        "questao_id": "ebb6bb09-50b9-5591-91b7-56ea73c94e2e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6ccc8cc1-0732-532e-9c85-c3078ac3c558",
        "questao_id": "ebb6bb09-50b9-5591-91b7-56ea73c94e2e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0f0540ee-2503-524c-9493-5409b7738e8c",
    "idSlug": "l13-035-maria-penha-vedacao-cesta-basica-sumulas",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Aos crimes praticados com violência doméstica e familiar contra a mulher é vedada a aplicação de penas de cesta básica ou outras de prestação pecuniária, bem como a substituição de pena que implique o pagamento isolado de multa, sendo também inaplicável a Lei nº 9.099/1995 (Juizados Especiais Criminais).",
    "explicacao": "GABARITO: CERTO. O art. 17 e o art. 41 da Lei 11.340/06 vedam penas pecuniárias isoladas/cesta básica e afastam integralmente os institutos despenalizadores da Lei 9.099/95 (Súmula 536/STJ e Súmula 589/STJ).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c33ded056f6cbc199a88e54eeee45c1b449855af63958b37c456f0171dfd7b28",
    "conceito_principal": "Vedações penais e inaplicabilidade da Lei 9.099/95",
    "habilidade_cobrada": "Reconhecer as vedações de penas pecuniárias e a exclusão dos Juizados Especiais na Lei Maria da Penha",
    "tese_ou_regra": "Na violência doméstica contra a mulher é proibida a substituição por cesta básica/multa isolada e não se aplica a Lei 9.099/95.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "25401bfa-7305-5c19-b75c-6dafb5fbce74",
        "questao_id": "0f0540ee-2503-524c-9493-5409b7738e8c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e70fe6b6-a100-593e-becd-7bb65a29b246",
        "questao_id": "0f0540ee-2503-524c-9493-5409b7738e8c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b7f39968-7eff-53db-bb27-bb5f9b741b35",
    "idSlug": "l13-036-crimes-hediondos-rol-taxativo-roubo-qualificado",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "9ee8346f-7a1c-5ecd-95b5-0a9a6d29ff67",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O rol dos crimes hediondos previsto na Lei nº 8.072/1990 é taxativo (princípio da legalidade estrita), abrangendo o roubo circunstanciado pela restrição de liberdade da vítima, o roubo circunstanciado pelo emprego de arma de fogo de uso permitido ou proibido, e o roubo qualificado pelo resultado lesão corporal grave ou morte (latrocínio).",
    "explicacao": "GABARITO: CERTO. Com a Lei 13.964/19 (Pacote Anticrime), o art. 1º, II da Lei 8.072/90 passou a incluir no rol hediondo o roubo com restrição de liberdade, com emprego de arma de fogo (qualquer que seja) ou arma de uso proibido/restrito, e o qualificado por lesão grave ou morte.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e2adb5ca8e329ee7c217d994381ecf130f3831dd5c95b116cd56e02faa1b66bd",
    "conceito_principal": "Hipóteses de roubo hediondo após a Lei 13.964/19",
    "habilidade_cobrada": "Identificar as modalidades de roubo que integram o rol taxativo da Lei 8.072/90",
    "tese_ou_regra": "O rol dos crimes hediondos inclui roubo com restrição de liberdade, emprego de arma de fogo e roubo com resultado lesão grave ou morte.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "625c3631-6ba0-59ad-93ca-dd1d940adc78",
        "questao_id": "b7f39968-7eff-53db-bb27-bb5f9b741b35",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "04b63632-d333-5e98-8201-cff27fe9084b",
        "questao_id": "b7f39968-7eff-53db-bb27-bb5f9b741b35",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "adec2369-334b-5339-bae2-a9fdba608dd5",
    "idSlug": "l13-037-crimes-hediondos-regime-inicial-stf",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "9ee8346f-7a1c-5ecd-95b5-0a9a6d29ff67",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Conforme jurisprudência vinculante do Supremo Tribunal Federal (HC 111.840/STF), a fixação obrigatória de regime inicial fechado para o cumprimento de pena por crime hediondo ou equiparado é inconstitucional por violar a garantia da individualização da pena.",
    "explicacao": "GABARITO: CERTO. O STF declarou a inconstitucionalidade do art. 2º, § 1º da Lei 8.072/90 na parte que impunha regime inicial fechado obrigatório, devendo o juiz observar os critérios do art. 33 do CP.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fecba75f5782bc1562eda4561b6b11aad2cf20fecc8d786a474d442a9c1759de",
    "conceito_principal": "Inconstitucionalidade do regime fechado obrigatório em crimes hediondos",
    "habilidade_cobrada": "Aplicar a jurisprudência do STF sobre individualização da pena em crimes hediondos",
    "tese_ou_regra": "A imposição legal de regime inicial fechado automático para crimes hediondos é inconstitucional.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "83865c7a-ac6a-5b55-b1f0-afde3efb9db1",
        "questao_id": "adec2369-334b-5339-bae2-a9fdba608dd5",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3b5dc837-4b87-5622-9827-cc9a847870f3",
        "questao_id": "adec2369-334b-5339-bae2-a9fdba608dd5",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8712fbc7-bebf-5b60-8eb1-117987af2268",
    "idSlug": "l13-038-tortura-prova-vs-tortura-castigo-sujeito-ativo",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O crime de tortura-prova (art. 1º, I, 'a' da Lei nº 9.455/1997) é crime comum quanto ao sujeito ativo e pode ser cometido por qualquer pessoa, ao passo que a tortura-castigo (art. 1º, II) é crime próprio, exigindo que o sujeito ativo tenha a vítima sob sua guarda, poder ou autoridade.",
    "explicacao": "GABARITO: CERTO. A tortura-prova (com fim de obter informação/confissão) pode ser praticada por qualquer pessoa (crime comum). Já a tortura-castigo exige relação especial de guarda, poder ou autoridade (crime próprio).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "347c17e22bcdc49141d958094f4dbd38432426292dc3aafaf8f7a4fd9eb4ccfc",
    "conceito_principal": "Classificação doutrinária das espécies de tortura",
    "habilidade_cobrada": "Distinguir sujeito ativo e elementos da tortura-prova e da tortura-castigo",
    "tese_ou_regra": "Tortura-prova é crime comum; tortura-castigo é crime próprio decorrente de guarda, poder ou autoridade.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "ba1df57c-40c2-519c-b004-351d0734a192",
        "questao_id": "8712fbc7-bebf-5b60-8eb1-117987af2268",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2222cefa-3824-5b10-b40c-97e7fc2dbf36",
        "questao_id": "8712fbc7-bebf-5b60-8eb1-117987af2268",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f3695d0e-a263-5cfa-a15b-33be782ff0ef",
    "idSlug": "l13-039-tortura-omissao-pena-detencao",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "IBFC",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Aquele que se omite em face das condutas de tortura, quando tinha o dever de evitá-las ou de apurá-las, incorre nas mesmas penas de reclusão cominadas ao executor material da tortura ativa, não havendo diferenciação sancionatória na Lei nº 9.455/1997.",
    "explicacao": "GABARITO: ERRADO. O art. 1º, § 2º da Lei 9.455/97 pune a tortura por omissão com pena menor e mais branda (detenção de 1 a 4 anos), ao passo que a tortura ativa é apenada com reclusão de 2 a 8 anos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "769868da2953c0035afac883c7cd8547ccea36ed9aba860cd1d95572f4a53b96",
    "conceito_principal": "Pena da tortura por omissão imprópria",
    "habilidade_cobrada": "Identificar o tratamento sancionatório diferenciado da tortura por omissão (art. 1º, § 2º)",
    "tese_ou_regra": "A tortura por omissão é punida com pena de detenção de 1 a 4 anos, inferior à cominada à tortura ativa.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "f1845932-90da-56e5-bbc4-b7aa6df469b8",
        "questao_id": "f3695d0e-a263-5cfa-a15b-33be782ff0ef",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "31780a4a-e381-5540-97b0-5daf27f255fb",
        "questao_id": "f3695d0e-a263-5cfa-a15b-33be782ff0ef",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "592929c6-d1e7-5a23-a78c-6e92b82bb315",
    "idSlug": "l13-040-tortura-efeito-condenacao-perda-cargo-dobro",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A condenação por crime de tortura acarreta para o servidor público a perda automática do cargo, função ou emprego público e a interdição para seu exercício pelo dobro do prazo da pena aplicada, tratando-se de efeito extrapenal específico e automático que dispensa motivação expressa na sentença.",
    "explicacao": "GABARITO: CERTO. O art. 1º, § 5º da Lei 9.455/97 prevê perda do cargo e interdição pelo dobro da pena como efeito automático da condenação (STJ, AgRg no REsp 1.834.789).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a1abfaa13e430a9d3a36a72febd9b2f51ad0ff4c3ff286204cf7366d9b7b9ed6",
    "conceito_principal": "Efeitos automáticos da condenação por crime de tortura",
    "habilidade_cobrada": "Reconhecer a automaticidade da perda do cargo e prazo de interdição na Lei de Tortura",
    "tese_ou_regra": "A perda do cargo e a interdição funcional pelo dobro do prazo da pena são efeitos automáticos da condenação por tortura.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5cd13298-1d48-53b2-babc-f44acc948dc9",
        "questao_id": "592929c6-d1e7-5a23-a78c-6e92b82bb315",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "0cd2453c-74a3-514a-881a-76a8603e057d",
        "questao_id": "592929c6-d1e7-5a23-a78c-6e92b82bb315",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "24a15816-2ecb-5800-aba2-f7014c0d5478",
    "idSlug": "l13-041-interceptacao-telefonica-requisitos-proibicao-detencao",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "É vedada a realização de interceptação de comunicações telefônicas quando o fato investigado constituir infração penal punida, no máximo, com pena de detenção, ou quando a prova puder ser feita por outros meios disponíveis.",
    "explicacao": "GABARITO: CERTO. O art. 2º da Lei 9.296/96 proíbe a interceptação se: I - não houver indícios razoáveis de autoria; II - a prova puder ser feita por outros meios; III - o fato for apenado no máximo com detenção.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "53901ddf804ca519a4f6ee9d76b7e6ab6500401df64358101b8569070a6b35ac",
    "conceito_principal": "Requisitos impeditivos da interceptação telefônica",
    "habilidade_cobrada": "Aplicar as vedações legais à decretação de interceptação telefônica na Lei 9.296/96",
    "tese_ou_regra": "Não se admite interceptação telefônica para crimes punidos com pena máxima de detenção ou quando houver outros meios probatórios.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2063c043-115c-598f-a316-410cbe244208",
        "questao_id": "24a15816-2ecb-5800-aba2-f7014c0d5478",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "17362be6-79f3-5fc6-9fa7-3d1a8df2e61d",
        "questao_id": "24a15816-2ecb-5800-aba2-f7014c0d5478",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9e09f6e9-95cf-538e-9072-2bc9d643fd1c",
    "idSlug": "l13-042-lavagem-dinheiro-terceira-geracao-autonomia",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0551bd35-dcb3-5809-8a12-f9a40e1c0b83",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Com a edição da Lei nº 12.683/2012, o Brasil adotou o modelo de terceira geração de combate à lavagem de dinheiro, admitindo como infração antecedente qualquer crime ou contravenção penal que produza bens, direitos ou valores ilícitos.",
    "explicacao": "GABARITO: CERTO. A Lei 12.683/2012 revogou o rol taxativo de crimes antecedentes, permitindo que qualquer infração penal (crime ou contravenção penal) sirva de delito antecedente à lavagem.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0916fa2dd5306bb3332dbb5f479051e90dd105a5e9ea65465a56b4e5b943e924",
    "conceito_principal": "Leis de lavagem de terceira geração e infração antecedente",
    "habilidade_cobrada": "Compreender a abrangência da infração penal antecedente na Lei 9.613/98 alterada",
    "tese_ou_regra": "A lavagem de capitais brasileira admite qualquer crime ou contravenção penal como infração antecedente.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "fa069c07-fbbc-5228-88c2-80c27416240e",
        "questao_id": "9e09f6e9-95cf-538e-9072-2bc9d643fd1c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "420e598c-bdd5-5584-acde-2635f4985608",
        "questao_id": "9e09f6e9-95cf-538e-9072-2bc9d643fd1c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "74097a28-456f-557b-a6c0-358977f4834b",
    "idSlug": "l13-043-lavagem-dinheiro-processamento-autonomo-antecedente",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0551bd35-dcb3-5809-8a12-f9a40e1c0b83",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O processo e julgamento do crime de lavagem de capitais é autônomo em relação à infração penal antecedente, bastando a demonstração de indícios suficientes de sua existência, não sendo a punibilidade da lavagem afetada pela extinção da punibilidade ou desconhecimento do autor da infração antecedente.",
    "explicacao": "GABARITO: CERTO. O art. 2º, II e § 1º da Lei 9.613/98 consagra a autonomia processual da lavagem, cuja persecução independe de condenação prévia ou do conhecimento do autor do crime antecedente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "760dcd8fb4b38876b726e6cceb684a0cf6209ffb40b721fdc0a5818e8bde5056",
    "conceito_principal": "Autonomia material e processual da lavagem de dinheiro",
    "habilidade_cobrada": "Analisar a independência da ação penal de lavagem frente à sorte da infração antecedente",
    "tese_ou_regra": "O crime de lavagem de dinheiro é punível ainda que desconhecido ou isento de pena o autor da infração antecedente.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "2e053606-e9a2-53e0-9200-41db2b8b4fa4",
        "questao_id": "74097a28-456f-557b-a6c0-358977f4834b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "21451761-9db8-5317-90dd-233b3f218349",
        "questao_id": "74097a28-456f-557b-a6c0-358977f4834b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8caa4da2-4ad3-5644-a87c-d43bf134e7b1",
    "idSlug": "l13-044-lavagem-dinheiro-alienacao-antecipada",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0551bd35-dcb3-5809-8a12-f9a40e1c0b83",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O juiz poderá determinar a alienação antecipada para preservação do valor de bens sob constrição judicial sempre que estiverem sujeitos a qualquer grau de deterioração ou depreciação, ou quando houver dificuldade para sua manutenção.",
    "explicacao": "GABARITO: CERTO. Conforme o art. 4º-A da Lei 9.613/98, a alienação antecipada visa evitar a perda do valor econômico de bens apreendidos que sofram deterioração ou cuja guarda seja onerosa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "935f699fdeb54ba8a2ce898febad658e240758bbed21376c000ccaa9193e39de",
    "conceito_principal": "Alienação antecipada de bens na Lei de Lavagem",
    "habilidade_cobrada": "Identificar as hipóteses autorizadoras de alienação antecipada cautelar na Lei 9.613/98",
    "tese_ou_regra": "A alienação antecipada de bens apreendidos é autorizada para preservar seu valor econômico contra depreciação.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0a0710ac-e8f0-54d3-bb2a-244777608bda",
        "questao_id": "8caa4da2-4ad3-5644-a87c-d43bf134e7b1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "0ca33f42-6294-5db0-a458-750f59a8b1e0",
        "questao_id": "8caa4da2-4ad3-5644-a87c-d43bf134e7b1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5d24024f-d497-5dcb-925b-6328d39e60f1",
    "idSlug": "l13-045-abuso-autoridade-conducao-coercitiva-ilegal",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Decretar a condução coercitiva de testemunha ou investigado manifestamente descabida ou sem prévia intimação de comparecimento ao juízo constitui crime tipificado na Lei de Abuso de Autoridade (Lei nº 13.869/2019).",
    "explicacao": "GABARITO: CERTO. O art. 9º, parágrafo único da Lei 13.869/19 tipifica expressamente decretar condução coercitiva manifestamente descabida ou sem prévia intimação.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "aa357f6f54a77bf1e608a3d39cf257faa541bbb0fe441b37c97ca462b8aaf854",
    "conceito_principal": "Condução coercitiva ilegal como abuso de autoridade",
    "habilidade_cobrada": "Reconhecer a tipicidade penal da condução coercitiva sem prévia intimação",
    "tese_ou_regra": "A condução coercitiva sem prévia intimação de comparecimento configura abuso de autoridade.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "d57568de-801a-560c-a85e-ab60bdc0ee0f",
        "questao_id": "5d24024f-d497-5dcb-925b-6328d39e60f1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "959d040b-7f40-55b0-81e0-ff3ddafb340e",
        "questao_id": "5d24024f-d497-5dcb-925b-6328d39e60f1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "3aa1452e-ccee-537e-9357-156f0de1ca45",
    "idSlug": "l13-046-maria-penha-renuncia-representacao-audiencia",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Nas ações penais públicas condicionadas à representação da ofendida de que trata a Lei Maria da Penha, a renúncia ou retratação da representação somente será admitida perante o juiz, em audiência especialmente designada com tal finalidade, antes do recebimento da denúncia e ouvido o Ministério Público.",
    "explicacao": "GABARITO: CERTO. O art. 16 da Lei 11.340/06 prevê que a retratação/renúncia exige audiência específica perante o juiz, antes do recebimento da denúncia e ouvido o MP.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6e61a9dc0683eb9e349a824344ea11b8fdae6438118b122f3203885125976080",
    "conceito_principal": "Audiência de retratação da representação na Lei Maria da Penha",
    "habilidade_cobrada": "Identificar os requisitos e o marco temporal para renúncia à representação (art. 16, Lei 11.340/06)",
    "tese_ou_regra": "A retratação da representação na Lei Maria da Penha exige audiência perante o magistrado antes do recebimento da denúncia.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "728361dd-b680-59a5-81b7-76dba79f51c8",
        "questao_id": "3aa1452e-ccee-537e-9357-156f0de1ca45",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d745a2c4-bf9b-5d11-ac5f-c959dbfae47d",
        "questao_id": "3aa1452e-ccee-537e-9357-156f0de1ca45",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f9424778-9176-5ae1-a912-45c59efd9831",
    "idSlug": "l13-047-crimes-hediondos-livramento-condicional-reincidencia",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "9ee8346f-7a1c-5ecd-95b5-0a9a6d29ff67",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O condenado por crime hediondo ou equiparado que cometer falta grave ou for reincidente específico em crime dessa natureza tem direito ao livramento condicional após o cumprimento de metade da pena.",
    "explicacao": "GABARITO: ERRADO. O art. 83, V do CP veda expressamente o livramento condicional ao reincidente específico em crimes hediondos ou equiparados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "119ca2a07472448c449fbb02cb712c4b62c9641c85925aa82338392b35a445ff",
    "conceito_principal": "Vedação ao livramento condicional para reincidente específico hediondo",
    "habilidade_cobrada": "Reconhecer a proibição de livramento condicional na reincidência específica hedionda",
    "tese_ou_regra": "É vedado o livramento condicional ao condenado reincidente específico em crimes hediondos ou equiparados.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "1cfc9546-6eba-5d7e-8e8d-1811d3adbd07",
        "questao_id": "f9424778-9176-5ae1-a912-45c59efd9831",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "13442e0d-b34c-5f49-bc65-eaba6832600a",
        "questao_id": "f9424778-9176-5ae1-a912-45c59efd9831",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "e8e54cf2-c974-5d44-8ae4-944e30d13eae",
    "idSlug": "l13-048-tortura-majorante-agente-publico",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Aumenta-se a pena do crime de tortura de um sexto até um terço se o crime for cometido por agente público, ou se for praticado contra criança, gestante, pessoa portadora de deficiência, adolescente ou pessoa maior de 60 (sessenta) anos, ou ainda mediante sequestro.",
    "explicacao": "GABARITO: CERTO. O art. 1º, § 4º da Lei 9.455/97 estabelece majorante de 1/6 a 1/3 para crimes cometidos por agente público, contra vítimas vulneráveis ou mediante sequestro.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fcc598008b9c9da0a61fa0d55bcd4ff63ce50034dc3c9a1ebcb5117e5cd47e55",
    "conceito_principal": "Causas de aumento de pena na Lei de Tortura",
    "habilidade_cobrada": "Identificar as majorantes do art. 1º, § 4º da Lei 9.455/97",
    "tese_ou_regra": "O crime de tortura é majorado em 1/6 a 1/3 quando praticado por agente público ou contra pessoas vulneráveis.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "53fc9923-7d92-5fe7-9951-4f7b28a61f75",
        "questao_id": "e8e54cf2-c974-5d44-8ae4-944e30d13eae",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "09e74e21-a92c-5262-842e-6eb5ab46a228",
        "questao_id": "e8e54cf2-c974-5d44-8ae4-944e30d13eae",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
    "idSlug": "l13-049-abuso-autoridade-efeitos-condenacao-reincidencia",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Nos termos da Lei nº 13.869/2019, a perda do cargo, do mandato ou da função pública e a inabilitação para o exercício de cargo público por período de 1 a 5 anos:",
    "explicacao": "A alternativa B expressa o art. 4º, parágrafo único da Lei nº 13.869/2019: a perda do cargo e a inabilitação exigem reincidência específica em crime de abuso e declaração motivada na sentença.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e1222e3363478a8abd29551abbb4077c35a3566be5c185d90718bb58deca7034",
    "conceito_principal": "Requisitos para perda do cargo na Lei de Abuso de Autoridade",
    "habilidade_cobrada": "Reconhecer que a perda do cargo na Lei 13.869/19 depende de reincidência e motivação expressa",
    "tese_ou_regra": "A perda do cargo na Lei de Abuso de Autoridade não é automática e exige reincidência específica.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "10e91ddf-d44c-5a27-9437-46d56bdff9ab",
        "questao_id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
        "letra": "A",
        "texto": "São efeitos automáticos de qualquer sentença penal condenatória transitada em julgado por abuso de autoridade.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. O art. 4º, parágrafo único estabelece que não são automáticos e exigem motivação."
      },
      {
        "id": "4ac4cb28-7919-5915-bc05-b2bbf1395d90",
        "questao_id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
        "letra": "B",
        "texto": "Condicionam-se à ocorrência de reincidência em crime de abuso de autoridade e não são automáticos, devendo ser expressamente declarados na sentença.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Conforme o art. 4º, parágrafo único da Lei 13.869/19, a perda e inabilitação dependem de reincidência e fundamentação expressa."
      },
      {
        "id": "acbcc294-c0b9-5a4f-a0db-5ebb9d4145b3",
        "questao_id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
        "letra": "C",
        "texto": "Apuram-se exclusivamente na esfera civil-administrativa, sendo vedada sua imposição em sentença penal condenatória.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Trata-se de efeitos penais secundários expressos no art. 4º."
      },
      {
        "id": "bc831d6d-b766-5b69-8d62-1e5103c65def",
        "questao_id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
        "letra": "D",
        "texto": "Podem ser aplicados liminarmente no despacho inicial de recebimento da denúncia pelo juiz de primeiro grau.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A perda do cargo só ocorre após o trânsito em julgado de sentença condenatória."
      },
      {
        "id": "03ef693e-966b-5e12-b963-68c1e171c9b1",
        "questao_id": "b717092d-1003-52e2-8f5b-4f8e313552c5",
        "letra": "E",
        "texto": "Atingem apenas servidores ocupantes de cargos de provimento em comissão, sendo inaplicáveis a concursados.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Atinge qualquer servidor público, efetivo ou comissionado."
      }
    ]
  },
  {
    "id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
    "idSlug": "l13-050-maria-penha-formas-violencia-art7",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0c686bc8-7d6f-54b7-991f-b34086393aba",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "A conduta consistente em reter, subtrair, destruir parcialmente ou totalmente instrumentos de trabalho, documentos pessoais, bens ou valores da mulher em contexto de relacionamento íntimo caracteriza:",
    "explicacao": "A alternativa A corresponde à modalidade de violência patrimonial prevista no art. 7º, inciso IV da Lei Maria da Penha.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "71f32809eafc5c9b1d8c4878d59a1858751e08ca0b45bd4c7487db3fb38f3315",
    "conceito_principal": "Conceito de violência patrimonial na Lei Maria da Penha",
    "habilidade_cobrada": "Identificar as formas de violência contra a mulher tipificadas no art. 7º da Lei 11.340/06",
    "tese_ou_regra": "A retenção ou destruição de documentos e instrumentos de trabalho configura violência patrimonial doméstica.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "8d9b3a71-059b-5687-854a-f2b4908c6171",
        "questao_id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
        "letra": "A",
        "texto": "Violência patrimonial, expressamente tipificada no artigo 7º, IV da Lei Maria da Penha.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Trata-se da definição legal literal de violência patrimonial (art. 7º, IV da Lei 11.340/06)."
      },
      {
        "id": "33d61eb6-3b2d-5c14-b3bc-1efa29940a8a",
        "questao_id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
        "letra": "B",
        "texto": "Mero ilícito civil de desacordo comercial desprovido de qualquer relevância para a tutela protetiva de urgência.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Constitui forma expressa de violência doméstica patrimonial."
      },
      {
        "id": "d451e4aa-80b3-561a-871b-731c7f46b128",
        "questao_id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
        "letra": "C",
        "texto": "Violência moral restrita exclusivamente a atos de injúria verbal recíproca durante audiências de conciliação.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Violência moral diz respeito a calúnia, difamação ou injúria (art. 7º, V)."
      },
      {
        "id": "930d1a0f-5c45-5950-a157-9020c2d97a0e",
        "questao_id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
        "letra": "D",
        "texto": "Infração militar imprópria com competência privativa da Justiça Militar Estadual.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A violência doméstica é processada na Justiça Comum / Juizados de Violência Doméstica."
      },
      {
        "id": "4fff4b14-cf01-5549-8926-a43262d05b08",
        "questao_id": "3aa4c601-6a0b-5f23-9442-1f945fb71511",
        "letra": "E",
        "texto": "Violência sexual consumada com base no artigo 7º, III da Lei nº 11.340/2006.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A destruição/retenção de bens e documentos é violência patrimonial."
      }
    ]
  },
  {
    "id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
    "idSlug": "l13-051-crimes-hediondos-progressao-regime-lep-percentuais",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "9ee8346f-7a1c-5ecd-95b5-0a9a6d29ff67",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Após a reformulação dos percentuais de progressão de regime promovida pela Lei nº 13.964/2019 (Pacote Anticrime) no artigo 112 da Lei de Execução Penal, o apenado condenado pela prática de crime hediondo com resultado morte, se primário, progride de regime após cumprir:",
    "explicacao": "A alternativa A expressa a regra do art. 112, VI, 'a' da LEP para crimes hediondos com resultado morte praticados por réu primário: 50% da pena e vedação ao livramento condicional.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "14d000c56383393ee4ee4032950a19687b8d391704e9ad01acfb0fbb7eb7d626",
    "conceito_principal": "Percentuais de progressão de regime na LEP após o Pacote Anticrime",
    "habilidade_cobrada": "Aplicar o art. 112, VI, 'a' da LEP a crimes hediondos com resultado morte cometidos por primários",
    "tese_ou_regra": "A progressão de regime no crime hediondo com resultado morte para réu primário exige 50% da pena e veda livramento condicional.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "044ece4a-90fa-5b16-aad7-a542a443c1eb",
        "questao_id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
        "letra": "A",
        "texto": "50% (cinquenta por cento) da pena, vedado o livramento condicional.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Art. 112, VI, 'a' da LEP: 50% da pena se o apenado for condenado pela prática de crime hediondo ou equiparado com resultado morte, se for primário, vedado o livramento condicional."
      },
      {
        "id": "b3de95b4-d139-53ab-a554-f891fc114f93",
        "questao_id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
        "letra": "B",
        "texto": "2/5 (dois quintos) da pena se primário e 3/5 (três quintos) se reincidente.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. As frações de 2/5 e 3/5 foram revogadas e substituídas pelo sistema de percentuais."
      },
      {
        "id": "7f4dc0e0-bc46-5cb0-a0b7-1c9e2a3c05b9",
        "questao_id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
        "letra": "C",
        "texto": "70% (setenta por cento) da pena, admitindo-se indulto natalino e anistia.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. O percentual de 70% (art. 112, VIII) aplica-se ao reincidente em crime hediondo com resultado morte."
      },
      {
        "id": "4ad48dab-4cf4-5f69-a93b-382a01c48841",
        "questao_id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
        "letra": "D",
        "texto": "16% (dezesseis por cento) da pena, desde que mantenha bom comportamento carcerário.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. 16% aplica-se a apenado primário condenado por crime sem violência ou grave ameaça."
      },
      {
        "id": "98100884-2672-5053-88d4-64596e2b5e13",
        "questao_id": "2ab916d7-e3e2-5a8d-85c1-c3e61a88e487",
        "letra": "E",
        "texto": "25% (vinte e cinco por cento) da pena se houver colaboração premiada com restituição total do proveito criminoso.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Percentuais hediondos com morte variam entre 50% (primário) e 70% (reincidente)."
      }
    ]
  },
  {
    "id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
    "idSlug": "l13-052-interceptacao-telefonica-prazo-renovacoes-stf",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A respeito do prazo legal da interceptação telefônica e da jurisprudência consolidada do STF e STJ sobre prorrogações (Lei nº 9.296/1996), assinale a afirmativa correta:",
    "explicacao": "A alternativa A sintetiza a jurisprudência pacífica sobre o art. 5º da Lei 9.296/96: o prazo de 15 dias admite sucessivas prorrogações fundamentadas caso a prova continue indispensável.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "01ec124407ea700ff5fcc0a54a3839e452d0a53e7159707c4f61ba3416a4430c",
    "conceito_principal": "Prazos e renovações sucessivas da interceptação telefônica",
    "habilidade_cobrada": "Aplicar o entendimento jurisprudencial consolidado sobre a renovação de interceptações telefônicas",
    "tese_ou_regra": "A interceptação telefônica pode ser renovada por períodos de 15 dias tantas vezes quantas forem necessárias.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5d7c4e27-268e-5fd0-8ee7-593cef91ecce",
        "questao_id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
        "letra": "A",
        "texto": "A interceptação pode ser prorrogada por períodos sucessivos de até 15 (quinze) dias, desde que comprovada a indispensabilidade do meio de prova e devidamente fundamentada a decisão.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Conforme pacífica jurisprudência do STF e STJ, o prazo de 15 dias pode ser renovado sucessivamente enquanto perdurar a necessidade."
      },
      {
        "id": "0a10c6b3-cf94-5ae1-a50e-28de98964788",
        "questao_id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
        "letra": "B",
        "texto": "A interceptação tem prazo improrrogável de 15 dias, extinguindo-se a persecução penal se o investigado não confessar nesse ínterim.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A renovação sucessiva é amplamente admitida com base na complexidade fática."
      },
      {
        "id": "a46def13-dc64-594d-aad3-ae7892f13835",
        "questao_id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
        "letra": "C",
        "texto": "Admite-se apenas uma única prorrogação de 15 dias, totalizando no máximo 30 dias absolutos de monitoramento.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Não há limite legal rígido de renovações, exigindo-se fundamentação em cada prorrogação."
      },
      {
        "id": "605323c7-1162-56b9-866d-eab2edd6f0a0",
        "questao_id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
        "letra": "D",
        "texto": "A gravação das conversas prescinde de autorização judicial caso a empresa de telefonia seja controlada pelo Estado.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A inviolabilidade das comunicações exige reserva de jurisdição (CF/88, art. 5º, XII)."
      },
      {
        "id": "b9005f2b-e6c7-52f0-bd69-60822237ff81",
        "questao_id": "c1dbe345-f508-5643-b36e-acf40f74ebaf",
        "letra": "E",
        "texto": "É vedada a utilização do material interceptado como prova emprestada em outros processos de coautores.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A prova emprestada obtida licitamente é admitida com contraditório posterior."
      }
    ]
  },
  {
    "id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
    "idSlug": "l13-053-lavagem-dinheiro-fases-colocacao-ocultacao-integracao",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "0551bd35-dcb3-5809-8a12-f9a40e1c0b83",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "A doutrina internacional e nacional divide o processo de lavagem de capitais em três fases sequenciais clássicas: colocação (placement), dissimulação ou ocultação (layering) e integração (integration). A fase de colocação caracteriza-se por:",
    "explicacao": "A alternativa A descreve com precisão a fase de colocação (placement), incluindo a técnica conhecida como 'smurfing' ou fracionamento de depósitos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2f5cbd85dd18fe8e66de180391b46604773eddc9d758e09b9f72bf39232f5689",
    "conceito_principal": "Fases clássicas da lavagem de capitais",
    "habilidade_cobrada": "Distinguir as etapas de colocação, dissimulação/estratificação e integração na lavagem de capitais",
    "tese_ou_regra": "A colocação é a primeira fase da lavagem, consistindo na inserção de ativos brutos no circuito financeiro formal.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "03d03476-67dd-59c0-b80f-7858ef14d551",
        "questao_id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
        "letra": "A",
        "texto": "Introduzir o dinheiro ilícito no sistema financeiro ou na economia formal, comumente fracionando depósitos em valores inferiores ao limite de comunicação obrigatória (smurfing).",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Colocação (placement) é a primeira etapa, onde os recursos ilícitos brutos são injetados no sistema financeiro ou comercial."
      },
      {
        "id": "6acad4f1-f422-5c9d-8639-42bfc90063b9",
        "questao_id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
        "letra": "B",
        "texto": "Investir os valores já aparentemente lícitos em empresas de fachada para distribuição formal de dividendos e lucros limpos.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Esta é a fase final de integração (integration)."
      },
      {
        "id": "69fdddfb-767d-516a-9603-d78f6f2d582d",
        "questao_id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
        "letra": "C",
        "texto": "Realizar sucessivas e complexas transações financeiras internacionais em paraísos fiscais para distanciar os fundos de sua origem ilícita.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Esta é a fase intermediária de dissimulação/estratificação (layering)."
      },
      {
        "id": "b5d6bf12-ce95-585f-a1d3-08d79498628f",
        "questao_id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
        "letra": "D",
        "texto": "Confiscar judicialmente todos os ativos do investigado antes do oferecimento da inicial acusatória.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Trata-se de medida processual penal e não de fase executória da lavagem."
      },
      {
        "id": "36c8d651-7b41-5bae-8cd3-5fbb6dbf0beb",
        "questao_id": "108397fb-a682-5b0d-8c2d-5b4fcc8850e8",
        "letra": "E",
        "texto": "Obter termo de colaboração premiada perante a autoridade policial competente.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Trata-se de meio de obtenção de prova."
      }
    ]
  },
  {
    "id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
    "idSlug": "l13-054-tortura-garantias-constitucionais-inafiancabilidade",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "f8e100c9-16c7-52dc-87d3-4e111e52d81a",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "facil",
    "enunciado": "De acordo com a Constituição Federal de 1988 (art. 5º, XLIII) e a Lei nº 9.455/1997, o crime de tortura é considerado:",
    "explicacao": "A alternativa A reproduz literalmente o mandado de criminalização do art. 5º, XLIII da CF/88 e o art. 2º da Lei nº 9.455/1997.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "972841c1aae51557e6fe32ed740254e39503cbe34e830677f70ac5fb823d639e",
    "conceito_principal": "Mandado constitucional de criminalização da tortura",
    "habilidade_cobrada": "Reconhecer a inafiançabilidade e vedação de anistia/graça do crime de tortura",
    "tese_ou_regra": "O crime de tortura é inafiançável e insuscetível de graça ou anistia por mandamento constitucional.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "5be21988-d818-52d0-904a-5afc6dfe3679",
        "questao_id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
        "letra": "A",
        "texto": "Inafiançável e insuscetível de graça ou anistia, respondendo por ele os mandantes, os executores e os que, podendo evitá-lo, se omitirem.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Art. 5º, XLIII da CF/88 e art. 2º da Lei 9.455/97 preveem expressamente a inafiançabilidade e a vedação de graça ou anistia."
      },
      {
        "id": "630b1c7d-0038-55c3-ba1f-b614464e004e",
        "questao_id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
        "letra": "B",
        "texto": "Prescritível em 6 meses caso o autor seja primário e com bons antecedentes funcionais.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Aplica-se a regra geral da prescrição penal do Código Penal."
      },
      {
        "id": "17654b3f-20dd-5efd-9bdf-c16a1f1edbe8",
        "questao_id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
        "letra": "C",
        "texto": "Infração de menor potencial ofensivo que comporta transação penal nos termos da Lei nº 9.099/1995.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Trata-se de crime grave apenado com reclusão de 2 a 8 anos."
      },
      {
        "id": "e852c1ff-e11c-5425-b07a-ec9d583112f0",
        "questao_id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
        "letra": "D",
        "texto": "Afiançável pelo Delegado de Polícia no valor mínimo de 1 a 10 salários mínimos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O crime de tortura é inafiançável por mandamento constitucional."
      },
      {
        "id": "f1c740c6-3a7e-514a-a94a-af38633e6a25",
        "questao_id": "4eaac812-d9bc-5391-8886-f663cda3dce6",
        "letra": "E",
        "texto": "Passível de indulto coletivo presidencial sem qualquer restrição jurídica.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O indulto (espécie de graça coletiva) é vedado pela Constituição Federal."
      }
    ]
  },
  {
    "id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
    "idSlug": "l13-055-abuso-autoridade-exposicao-preso-midia",
    "disciplina_id": "f54b2f9a-3916-5409-a431-a93ce24510e9",
    "assunto_id": "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Constranger o preso ou o detento, mediante violência, grave ameaça ou redução de sua capacidade de resistência, a exibir-se ou ter seu corpo ou parte dele exibido à curiosidade pública, ou a submeter-se a situação vexatória ou a constrangimento não autorizado em lei (art. 13 da Lei nº 13.869/2019):",
    "explicacao": "A alternativa A corresponde exatamente ao tipo penal do art. 13 da Lei nº 13.869/2019, que tutela a dignidade do preso contra exibição pública abusiva.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "aa84b82908d72e86886af99a617818df3d19a4ff0dc4ff267d9adf89dfe32da2",
    "conceito_principal": "Crime de constrangimento e exposição abusiva de preso à mídia",
    "habilidade_cobrada": "Identificar o tipo penal do art. 13 da Lei 13.869/19",
    "tese_ou_regra": "Constranger preso a exibir-se à curiosidade pública ou situação vexatória configura crime de abuso de autoridade.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "435c7e68-508b-50bc-9844-2fc4ea38fba8",
        "questao_id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
        "letra": "A",
        "texto": "Configura crime de abuso de autoridade punido com pena de detenção de 1 a 4 anos e multa, sem prejuízo da pena cominada à violência.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. O art. 13 da Lei 13.869/19 tipifica a exposição indevida do preso com pena de detenção de 1 a 4 anos e multa."
      },
      {
        "id": "b372de73-70b0-58da-8a45-49e518bd13e6",
        "questao_id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
        "letra": "B",
        "texto": "Constitui procedimento administrativo legal obrigatório para assegurar a publicidade ampla dos atos da polícia investigativa.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. É conduta criminosa e atentatória à dignidade humana."
      },
      {
        "id": "446fddac-0aff-51c9-8309-376c7194793f",
        "questao_id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
        "letra": "C",
        "texto": "Trata-se de contravenção penal de menor potencial ofensivo julgada perante a Justiça Militar da União.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. É crime comum de abuso de autoridade punido com detenção de 1 a 4 anos."
      },
      {
        "id": "08938175-4e8a-5457-a335-22af7a2aefc4",
        "questao_id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
        "letra": "D",
        "texto": "Exclui a ilicitude quando a imprensa local solicitar formalmente a entrevista para veiculação ao vivo.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A solicitação da imprensa não afasta a tipicidade do constrangimento ilegal do preso."
      },
      {
        "id": "79123592-0c25-5c6e-b922-4bb560fef328",
        "questao_id": "839dc746-ac45-54b4-876e-cbc77d8ec7e9",
        "letra": "E",
        "texto": "Autoriza a suspensão automática das prerrogativas constitucionais de silêncio do conduzido.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. As garantias de silêncio e dignidade do preso são invioláveis."
      }
    ]
  }
];
