// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 20

export const m14_questoes = [
  {
    "id": "7a757fc6-4112-5848-be60-a9280445766b",
    "idSlug": "l13-adm-resp-001-responsabilidade-civil-objetiva-art37-par6",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "80853bc8-d70e-55bb-8ad2-b4439f7079b9",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "As pessoas jurídicas de direito público e as de direito privado prestadoras de serviços públicos responderão pelos danos que seus agentes, nessa qualidade, causarem a terceiros, assegurado o direito de regresso contra o responsável nos casos de dolo ou culpa, adotando o ordenamento a teoria do risco administrativo.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 37, § 6º da Constituição Federal de 1988: responsabilidade estatal objetiva e ação regressiva subjetiva.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e3a00db6fa1713f0526dce83e9a2e2957fe3c1637e12f586b44f561cbce1746c",
    "conceito_principal": "Responsabilidade civil objetiva do Estado (Teoria do Risco Administrativo)",
    "habilidade_cobrada": "Identificar os requisitos da responsabilidade estatal e do direito de regresso",
    "tese_ou_regra": "O Estado responde objetivamente por danos de seus agentes; a ação regressiva exige dolo ou culpa",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "25563f7d-8488-590f-af83-7667abe44fda",
        "questao_id": "7a757fc6-4112-5848-be60-a9280445766b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "36dfc726-4cd8-573e-8fc4-d9ce08e2e4b0",
        "questao_id": "7a757fc6-4112-5848-be60-a9280445766b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5ea026ce-6c44-50fd-9641-6ed7cf2393ca",
    "idSlug": "l13-adm-resp-002-stf-tema-940-vedacao-acao-direta-agente-publico",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "80853bc8-d70e-55bb-8ad2-b4439f7079b9",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Segundo a tese vinculante fixada pelo STF no Tema 940 de repercussão geral (RE 1.027.633), a ação por danos causados por agente público deve ser ajuizada necessariamente contra o Estado ou a pessoa jurídica de direito privado prestadora do serviço público, sendo o servidor público parte ilegítima para figurar no polo passivo da ação indenizatória movida pelo terceiro prejudicado (princípio da dupla garantia).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. STF Tema 940: veda o ajuizamento da ação indenizatória direta do particular em face do agente público.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "14e167620b5972d06e92a39a4f7cb6c19c2c04ed2c12acb2b778d86cb3a9d5a3",
    "conceito_principal": "Tese da Dupla Garantia no Tema 940 do STF",
    "habilidade_cobrada": "Aplicar a tese de ilegitimidade passiva do servidor público perante a vítima direta",
    "tese_ou_regra": "Ação indenizatória deve ser proposta contra o ente estatal, cabendo a este ação regressiva contra o agente",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "591ec39d-d0d5-51d4-8951-df4e4c760ddb",
        "questao_id": "5ea026ce-6c44-50fd-9641-6ed7cf2393ca",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "28dfc12f-b643-5a72-9577-c0c54f89b55b",
        "questao_id": "5ea026ce-6c44-50fd-9641-6ed7cf2393ca",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "93cbe78f-e4bf-5072-9e32-4231a3a21c0b",
    "idSlug": "l13-adm-imp-003-lei-improbidade-14230-dolo-especifico-obrigatorio",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "d9c11f93-08be-5a97-8c6b-5a32724f83bb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Com as alterações promovidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa (Lei nº 8.429/1992), passou-se a exigir a comprovação de dolo específico para a caracterização de qualquer ato de improbidade administrativa, tendo sido expressamente revogada a modalidade culposa anteriormente prevista para os atos que causam prejuízo ao erário.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 1º, §§ 1º, 2º e 3º da Lei nº 8.429/92 (redação da Lei 14.230/21): extinção da improbidade culposa e exigência de dolo específico.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5d15fa53903df3909800972763887ceb1a913c1f48382c44ed01263b83fc01a5",
    "conceito_principal": "Exigência de dolo específico na Lei de Improbidade Administrativa (Lei 14.230/21)",
    "habilidade_cobrada": "Reconhecer a extinção da improbidade administrativa culposa após a reforma de 2021",
    "tese_ou_regra": "Atos de improbidade exigem dolo específico com vontade livre e consciente de alcançar fim ilícito",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "cc696587-81bc-5332-bfee-c2a9f663c93d",
        "questao_id": "93cbe78f-e4bf-5072-9e32-4231a3a21c0b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "891a66bc-2663-559b-8d51-2b5bae9f665a",
        "questao_id": "93cbe78f-e4bf-5072-9e32-4231a3a21c0b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f4557de2-0314-5329-9b9a-2467f5f066bc",
    "idSlug": "l13-adm-imp-004-stf-tema-1199-retroatividade-lei-improbidade",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "d9c11f93-08be-5a97-8c6b-5a32724f83bb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "No julgamento do Tema 1.199 de repercussão geral (ARE 843.989), o STF decidiu que a revogação da modalidade culposa de improbidade administrativa pela Lei nº 14.230/2021 é irretroativa em relação às condenações transitadas em julgado, aplicando-se, contudo, aos atos de improbidade culposos praticados antes da lei nova desde que ainda não haja trânsito em julgado.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Tese do Tema 1.199 do STF: a lei nova retroage para processos em curso sem trânsito em julgado, resguardando a coisa julgada material.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "20cc199e3eed99b9260f527aed0bb21a3481cb9ffd62fa0a84b64764fa05159c",
    "conceito_principal": "Retroatividade da Lei 14.230/21 fixada no STF Tema 1199",
    "habilidade_cobrada": "Aplicar os critérios de modulação temporal da Lei de Improbidade Administrativa",
    "tese_ou_regra": "A revogação da improbidade culposa retroage para processos sem trânsito em julgado",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "abf71d1b-2190-5d6a-8df2-a05bccf7b8fd",
        "questao_id": "f4557de2-0314-5329-9b9a-2467f5f066bc",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c9ca4585-9f52-5066-bf63-34aa6be38293",
        "questao_id": "f4557de2-0314-5329-9b9a-2467f5f066bc",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
    "idSlug": "l13-adm-lic-005-lei-14133-modalidades-licitacao-dialogo-competitivo",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "25c0e38d-9020-5c46-849e-8c796fed3d27",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "A Lei nº 14.133/2021 (Nova Lei de Licitações e Contratos Administrativos) reestruturou o rol das modalidades licitatórias aplicáveis à Administração Pública direta e indireta. Assinale a opção que apresenta com exatidão as modalidades expressamente previstas no art. 28 da referida lei.",
    "explicacao": "GABARITO: C. Art. 28 da Lei nº 14.133/2021: pregão, concorrência, concurso, leilão e diálogo competitivo (foram extintos a tomada de preços e o convite).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8923cd09d7033ef8a455a83ec697d2ffc12980a5c201ec72dcad6220f7eebe3f",
    "conceito_principal": "Modalidades de licitação da Nova Lei de Licitações (Lei nº 14.133/2021)",
    "habilidade_cobrada": "Identificar o rol moderno de modalidades licitatórias da Lei 14.133/2021",
    "tese_ou_regra": "A Lei 14.133/21 prevê pregão, concorrência, concurso, leilão e diálogo competitivo",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "21f01e3a-1d85-5367-9003-8bf0532fc7ef",
        "questao_id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
        "letra": "A",
        "texto": "Pregão, concorrência, tomada de preços, convite e leilão.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Tomada de preços e convite foram extintos pela nova lei."
      },
      {
        "id": "0f116666-bf48-5054-8cb8-dfa725f74112",
        "questao_id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
        "letra": "B",
        "texto": "Concorrência, tomada de preços, leilão, concurso e pregão.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Tomada de preços não existe na Lei 14.133/21."
      },
      {
        "id": "4a9b193d-71cc-5ab6-af47-f1e3e97a4185",
        "questao_id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
        "letra": "C",
        "texto": "Pregão, concorrência, concurso, leilão e diálogo competitivo.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Rol taxativo do art. 28 da Lei nº 14.133/2021."
      },
      {
        "id": "c899b64e-3446-599e-bd52-08cbce4d0ba4",
        "questao_id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
        "letra": "D",
        "texto": "Diálogo competitivo, tomada de preços, concurso, leilão e consulta pública.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Consulta pública não é modalidade de licitação."
      },
      {
        "id": "d24d81c2-1632-5e3e-ab7d-601b8d3d480d",
        "questao_id": "14827ef7-f1fa-5ed8-bdf0-a78ae478e709",
        "letra": "E",
        "texto": "Concorrência restrita, convite eletrônico, pregão presencial e leilão.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Nomenclaturas não previstas no art. 28."
      }
    ]
  },
  {
    "id": "2023f435-31dd-5a14-b3c3-5bcea956635e",
    "idSlug": "l13-adm-lic-006-lei-14133-inexigibilidade-vs-dispensa",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "25c0e38d-9020-5c46-849e-8c796fed3d27",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na Nova Lei de Licitações (Lei nº 14.133/2021), a inexigibilidade de licitação decorre da inviabilidade fática ou jurídica de competição (art. 74), enquanto a dispensa de licitação abrange hipóteses em que a competição seria teoricamente viável, mas a lei autoriza ou determina a contratação direta por conveniência, segurança ou valor reduzido (art. 75).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Distinção essencial entre inexigibilidade (inviabilidade de competição) e dispensa (competição viável, mas contratação direta autorizada).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "edf9a9ed4c33568c7cf8d201b5be6dbd5e4f888e25c0f309a5adf1a762b3faac",
    "conceito_principal": "Distinção entre dispensa e inexigibilidade na Lei 14.133/2021",
    "habilidade_cobrada": "Classificar as hipóteses de contratação direta na Nova Lei de Licitações",
    "tese_ou_regra": "Inexigibilidade pressupõe inviabilidade de disputa; dispensa pressupõe disputa viável com exceção legal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "dc3fdfb9-5509-58e9-8a07-2482365fd9b1",
        "questao_id": "2023f435-31dd-5a14-b3c3-5bcea956635e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6c6b16c1-fedb-5fec-8e0c-49db73961cd6",
        "questao_id": "2023f435-31dd-5a14-b3c3-5bcea956635e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ff15eb2b-60f5-5eec-890d-d3822d888f6c",
    "idSlug": "l13-adm-age-007-lei-8112-estabilidade-estagio-probatorio",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O servidor público federal investido em cargo de provimento efetivo adquire a estabilidade após três anos de efetivo exercício, ficando condicionado à aprovação em avaliação especial de desempenho por comissão instituída para essa finalidade, conforme estabelecido pelo art. 41 da Constituição Federal e Súmula 21 do STF.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 41 da CF/88 (redação da EC 19/98) e Súmula 21 do STF: prazo de 3 anos e necessidade de avaliação especial.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "225356a8a19d78da3b861b09cd24705e0ac9f60716aac85a62f8f40136187672",
    "conceito_principal": "Estabilidade no serviço público e estágio probatório",
    "habilidade_cobrada": "Reconhecer o prazo e os requisitos constitucionais para a aquisição da estabilidade",
    "tese_ou_regra": "A estabilidade no cargo efetivo exige 3 anos de exercício e aprovação em avaliação especial",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "d95a810f-6002-56c4-a139-1af83e93466e",
        "questao_id": "ff15eb2b-60f5-5eec-890d-d3822d888f6c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3b30b87b-070d-5f8d-9795-7f2a0796a457",
        "questao_id": "ff15eb2b-60f5-5eec-890d-d3822d888f6c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "92829b1f-7dec-5972-b4ef-6fa51167d453",
    "idSlug": "l13-adm-age-008-lei-8112-demissao-pad-ampla-defesa",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A demissão de servidor estável ou em estágio probatório fundada na prática de infração disciplinar grave exige a prévia instauração de processo administrativo disciplinar (PAD), assegurados o contraditório e a ampla defesa, sendo nula a penalidade expulsória aplicada sumariamente por ato discricionário da chefia.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 41, § 1º da CF/88, Súmula 20 do STF e Lei nº 8.112/90.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7139c1afa98b8d885e0c3e3317447ab82de262d39c6c86cb41ff460eac3bf95e",
    "conceito_principal": "Garantia de PAD para aplicação de penalidade de demissão",
    "habilidade_cobrada": "Identificar as garantias do devido processo legal no regime disciplinar dos servidores",
    "tese_ou_regra": "A demissão funcional exige formalização de PAD com contraditório e ampla defesa",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "96616b53-77ae-5847-9405-5fdfb405aae2",
        "questao_id": "92829b1f-7dec-5972-b4ef-6fa51167d453",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "584910ff-068e-5f0d-8946-e5ea3d669d0c",
        "questao_id": "92829b1f-7dec-5972-b4ef-6fa51167d453",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5686f79f-8fb3-5e91-b131-a764462671f4",
    "idSlug": "l13-adm-age-009-reintegracao-reconducao-reversao-readaptacao",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A reintegração é a reinvestidura do servidor estável no cargo anteriormente ocupado quando invalidada a sua demissão por decisão judicial ou administrativa, com ressarcimento de todas as vantagens, acarretando a recondução do eventual ocupante da vaga ao cargo de origem, sem direito a indenização.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 28 da Lei nº 8.112/90 e art. 41, § 2º da Constituição Federal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cd39520131543b99a98adc687d6a1bcb702dc4f3e7f9149b825102c775e2b205",
    "conceito_principal": "Formas de provimento e vacância: reintegração e recondução",
    "habilidade_cobrada": "Diferenciar reintegração, recondução, reversão e readaptação na Lei 8.112/90",
    "tese_ou_regra": "A reintegração repara a demissão ilegal com ressarcimento integral e reconduz o substituto",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "97e751c6-9b4c-5756-9be8-11cbdd42f4e8",
        "questao_id": "5686f79f-8fb3-5e91-b131-a764462671f4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "dca63373-2966-5054-8b86-442982ef292f",
        "questao_id": "5686f79f-8fb3-5e91-b131-a764462671f4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "497134d2-7530-5976-9b10-1d241a9e817d",
    "idSlug": "l13-adm-imp-010-sancoes-lei-improbidade-perda-bens-funcao",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "d9c11f93-08be-5a97-8c6b-5a32724f83bb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Nos termos da Lei nº 8.429/1992, com as alterações da Lei nº 14.230/2021, a sanção de perda da função pública cominada em ação de improbidade administrativa:",
    "explicacao": "GABARITO: D. Art. 12, § 1º da Lei nº 8.429/92 (redação da Lei 14.230/21): a perda da função pública atinge apenas o vínculo de mesma qualidade e natureza que o agente público detinha na época do ato ímprobo, salvo hipótese de enriquecimento ilícito grave com extensão justificada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f376271ca2d4335797c680d6073e9f692bcda89442c22e8a411802d6245085cb",
    "conceito_principal": "Sanção de perda da função pública na Lei 14.230/21",
    "habilidade_cobrada": "Compreender os limites da sanção de perda da função pública após a reforma da LIA",
    "tese_ou_regra": "A perda da função pública atinge o cargo da época e pressupõe trânsito em julgado",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "752c2cfb-16d0-592b-8064-d0faf09cfcd1",
        "questao_id": "497134d2-7530-5976-9b10-1d241a9e817d",
        "letra": "A",
        "texto": "Atinge automaticamente todo e qualquer cargo público ocupado no momento da sentença, ainda que de outro poder ou esfera federativa sem nexo com o ato.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. A regra nova restringe a perda ao vínculo de mesma natureza."
      },
      {
        "id": "467a5b02-a7a9-5466-b6b9-2c1391f82525",
        "questao_id": "497134d2-7530-5976-9b10-1d241a9e817d",
        "letra": "B",
        "texto": "Aplica-se independentemente de trânsito em julgado imediatamente após a prolação da sentença condenatória de primeiro grau.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O art. 20 exige expressamente o trânsito em julgado para a perda da função pública."
      },
      {
        "id": "5bb7e72d-63db-558a-a0fb-40707ce97ce1",
        "questao_id": "497134d2-7530-5976-9b10-1d241a9e817d",
        "letra": "C",
        "texto": "Impede vitaliciamente o cidadão de prestar novos concursos públicos em qualquer esfera.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A lei prevê suspensão de direitos políticos e proibição de contratar por prazos determinados."
      },
      {
        "id": "6a93c6e3-4695-5afe-ba1a-d8f43f55399f",
        "questao_id": "497134d2-7530-5976-9b10-1d241a9e817d",
        "letra": "D",
        "texto": "Atinge apenas o vínculo de mesma qualidade e natureza que o agente detinha com o poder público na época do cometimento da infração, dependendo de trânsito em julgado.",
        "correta": true,
        "ordem": 4,
        "explicacao_especifica": "Correta. Art. 12, § 1º e art. 20 da Lei nº 8.429/92."
      },
      {
        "id": "11be15a8-7b99-5a42-9bf6-49b5f17f7c6c",
        "questao_id": "497134d2-7530-5976-9b10-1d241a9e817d",
        "letra": "E",
        "texto": "Pode ser decretada de ofício pelo Ministério Público sem necessidade de intervenção do Poder Judiciário.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. As sanções da LIA são privativas da jurisdição civil."
      }
    ]
  },
  {
    "id": "823faf43-039d-5114-a671-9e30208393fc",
    "idSlug": "l13-adm-resp-011-omissao-estatal-responsabilidade-subjetiva-faute-du-service",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "80853bc8-d70e-55bb-8ad2-b4439f7079b9",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Em se tratando de danos causados por omissão genérica do Poder Público, a jurisprudência dominante do STF e do STJ orienta que a responsabilidade civil do Estado é, em regra, subjetiva, exigindo a demonstração da culpa administrativa (falta do serviço — faute du service), caracterizada quando o serviço não funcionou, funcionou mal ou funcionou tardiamente.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina e jurisprudência consolidada sobre a responsabilidade subjetiva por omissão genérica estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "18166d49b9982ab5c87ee86ce7e809aff8d74f89884125f347096de691b48f67",
    "conceito_principal": "Responsabilidade civil do Estado por conduta omissiva genérica",
    "habilidade_cobrada": "Distinguir responsabilidade objetiva por ação e subjetiva por omissão genérica",
    "tese_ou_regra": "A omissão genérica do Estado enseja responsabilidade civil subjetiva fundada na falta do serviço",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "c7b85cba-5b30-53da-b4d7-199bec9cd0ed",
        "questao_id": "823faf43-039d-5114-a671-9e30208393fc",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7e03968a-c5fb-5530-a058-0cc0bfabca97",
        "questao_id": "823faf43-039d-5114-a671-9e30208393fc",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "46ff4e9a-99a0-5cc6-9b1b-b30e9129105a",
    "idSlug": "l13-adm-resp-012-morte-custodia-responsabilidade-objetiva-stf-tema592",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "80853bc8-d70e-55bb-8ad2-b4439f7079b9",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Segundo a tese vinculante fixada pelo STF no Tema 592 de repercussão geral, em caso de morte de pessoa presa sob custódia estatal, a responsabilidade civil do Estado é objetiva em virtude do dever constitucional de vigilância e proteção da integridade física do custodiado (art. 5º, XLIX da CF), cabendo ao Estado comprovar que a morte decorreu de causa natural ou que adotou todas as medidas necessárias para evitar o suicídio/homicídio.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. STF Tema 592 (RE 841.526): responsabilidade objetiva do Estado pela integridade física do preso sob sua custódia.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "aae3503648ad3f1fd3b356de2476fd661804e8a4121a0e712d1fa90a2290ec5c",
    "conceito_principal": "Responsabilidade civil objetiva por morte de preso em custódia (STF Tema 592)",
    "habilidade_cobrada": "Aplicar a tese de responsabilidade estatal pela integridade física dos presos",
    "tese_ou_regra": "O Estado responde objetivamente por danos e mortes ocorridas no sistema prisional sob sua custódia",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "18b74eb5-e5bd-50f2-9e03-83cc216ecde2",
        "questao_id": "46ff4e9a-99a0-5cc6-9b1b-b30e9129105a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5fc3a2e4-b1eb-5691-bc63-2853dfbe2960",
        "questao_id": "46ff4e9a-99a0-5cc6-9b1b-b30e9129105a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "eb99be38-92ed-550e-ab8e-300b6914346f",
    "idSlug": "l13-adm-lic-013-lei-14133-criterios-julgamento-menor-preco",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "25c0e38d-9020-5c46-849e-8c796fed3d27",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na Lei nº 14.133/2021, são critérios de julgamento das propostas licitatórias o menor preço, o maior desconto, a melhor técnica ou conteúdo artístico, a técnica e preço, o maior lance (no caso de leilão) e o maior retorno econômico.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 33 da Lei nº 14.133/2021.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "79fa318b05034cf029cfeaeb427414e98e8ba005eac374b7ebcfdcfb02e3b657",
    "conceito_principal": "Critérios de julgamento na Lei 14.133/2021",
    "habilidade_cobrada": "Identificar os tipos e critérios de julgamento da Nova Lei de Licitações",
    "tese_ou_regra": "A Lei 14.133/21 estabelece seis critérios formais de julgamento das propostas",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "c2fc2783-05e8-50c8-b431-54bc17530e0b",
        "questao_id": "eb99be38-92ed-550e-ab8e-300b6914346f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5689f6da-b78b-527c-b697-7d4f3a7967ca",
        "questao_id": "eb99be38-92ed-550e-ab8e-300b6914346f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9d957bb4-2c08-583c-9e85-835894c3f231",
    "idSlug": "l13-adm-age-014-acumulacao-cargos-policiais-regra-geral",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "É vedada a acumulação remunerada de cargos públicos, ressalvadas as hipóteses constitucionais expressas de dois cargos de professor, um de professor com outro técnico ou científico, e dois cargos privativos de profissionais de saúde, desde que haja compatibilidade de horários, sendo vedada a acumulação de cargo policial com outro cargo público efetivo.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 37, XVI da CF/88: o cargo policial é cargo de dedicação exclusiva que não se enquadra nas ressalvas de magistério ou saúde.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6319d3d2ca5d0878ab4edc2246f719f2db6201de722955d6faf60a6b8a87916c",
    "conceito_principal": "Regime constitucional de vedação à acumulação de cargos públicos",
    "habilidade_cobrada": "Analisar as hipóteses restritivas de acumulação remunerada de cargos",
    "tese_ou_regra": "Cargos policiais não admitem acumulação remunerada ordinária com outros cargos efetivos",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c1abc227-7da4-5b63-9489-9a774f1fd611",
        "questao_id": "9d957bb4-2c08-583c-9e85-835894c3f231",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "315bf943-6a96-55e5-a26d-4205813e7564",
        "questao_id": "9d957bb4-2c08-583c-9e85-835894c3f231",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
    "idSlug": "l13-adm-lic-015-contratacao-direta-seguranca-nacional-dispensa",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "25c0e38d-9020-5c46-849e-8c796fed3d27",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em matéria de contratações públicas para órgãos de segurança pública e defesa, a Lei nº 14.133/2021 prevê hipóteses específicas de dispensa de licitação. Assinale a afirmativa que apresenta hipótese legal de dispensa autorizada pelo art. 75 da referida lei.",
    "explicacao": "GABARITO: B. Art. 75, IV, 'b' e 'f' da Lei nº 14.133/2021: contratação de materiais bélicos de uso exclusivo das Forças Armadas e forças de segurança ou quando houver comprometimento da segurança nacional.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "48b72f279cbc0e9ca62560a993e24811ab4062a9ba8628e5e541a0a8d6e59630",
    "conceito_principal": "Dispensa de licitação em situações de emergência e segurança pública",
    "habilidade_cobrada": "Identificar as hipóteses de dispensa de licitação no art. 75 da Lei 14.133/2021",
    "tese_ou_regra": "Contratação emergencial por dispensa é limitada aos bens estritamente necessários ao socorro da situação",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "f9f64051-75dc-5bdb-8cfd-b75466c21c76",
        "questao_id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
        "letra": "A",
        "texto": "Para aquisição de bens de luxo destinados exclusivamente ao gabinete do Comandante-Geral da corporação.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Bens de luxo são expressamente vedados na administração pelo art. 20 da lei."
      },
      {
        "id": "a799835c-8a05-5a46-938c-88ecb16370cf",
        "questao_id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
        "letra": "B",
        "texto": "Nos casos de emergência ou de calamidade pública, para aquisição dos bens necessários ao atendimento da situação emergencial pelo prazo máximo de um ano.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Art. 75, VIII da Lei nº 14.133/2021."
      },
      {
        "id": "9c18fc91-a9a4-53b0-bc97-46d7b9c35b05",
        "questao_id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
        "letra": "C",
        "texto": "Sempre que a autoridade policial preferir fornecedor sediado no mesmo município da delegacia de polícia.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Viola o princípio da isonomia e competitividade."
      },
      {
        "id": "fded4eb9-7e3b-5f53-8578-d405041d3dd3",
        "questao_id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
        "letra": "D",
        "texto": "Em qualquer compra de viaturas blindadas, independentemente do valor ou de justificação de preço de mercado.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Exige procedimento de dispensa formal com justificativa de preço e razão da escolha."
      },
      {
        "id": "340982bf-4235-555b-9d4c-4d4bcd5f2931",
        "questao_id": "f8a017d0-2eeb-5d9c-b939-d324a83009e0",
        "letra": "E",
        "texto": "Para terceirização integral das atividades-fim de investigação criminal da Polícia Judiciária.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Atividade-fim de polícia de estado é indelegável a particulares."
      }
    ]
  },
  {
    "id": "d1ac5620-2aa6-52e5-b375-a1317d621d7e",
    "idSlug": "l13-adm-age-016-prescricao-disciplinar-art142-lei8112",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Nos termos da Lei nº 8.112/1990, a ação disciplinar prescreverá em 5 anos quanto às infrações puníveis com demissão, cassação de aposentadoria ou disponibilidade e destituição de cargo em comissão; o prazo de prescrição começa a correr da data em que o fato se tornou conhecido da autoridade competente para instaurar o procedimento, interrompendo-se com a publicação da portaria de instauração do PAD.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 142, I, § 1º e § 3º da Lei Federal nº 8.112/90.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0644d4a663bc0ec6e2b522d41372a966e81cc90aa4fa525b8e591c2c6193451e",
    "conceito_principal": "Prescrição da pretensão punitiva disciplinar na Lei 8.112/90",
    "habilidade_cobrada": "Calcular o termo inicial e as causas interruptivas da prescrição disciplinar",
    "tese_ou_regra": "Prescrição disciplinar para demissão corre em 5 anos a contar do conhecimento pela autoridade",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "5a9fb831-b7df-53ec-9b24-e783460fdc0b",
        "questao_id": "d1ac5620-2aa6-52e5-b375-a1317d621d7e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2ba61e64-5d22-5335-84ac-f8faccad42f0",
        "questao_id": "d1ac5620-2aa6-52e5-b375-a1317d621d7e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "886ab0e8-b047-52bc-9292-58b062c0bdb1",
    "idSlug": "l13-adm-imp-017-prescricao-intercorrente-lei-14230",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "d9c11f93-08be-5a97-8c6b-5a32724f83bb",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A Lei nº 14.230/2021 introduziu na Lei de Improbidade Administrativa a prescrição intercorrente, fixando que, ajuizada a ação civil de improbidade, o prazo prescricional de quatro anos para a prolação de sentença ou acórdão condenatório interrompe-se pelos marcos legais, extinguindo-se o processo caso ultrapassado o prazo sem julgamento.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 23, §§ 4º, 5º e 8º da Lei nº 8.429/92 (redação da Lei 14.230/21).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c53182613a95ef8b37976db4df4b843763917688f5b7c99297a7d59afe5a76e1",
    "conceito_principal": "Prescrição intercorrente na Lei de Improbidade Administrativa",
    "habilidade_cobrada": "Compreender os prazos e efeitos da prescrição intercorrente na LIA",
    "tese_ou_regra": "A Lei 14.230/21 fixou prazo de prescrição intercorrente de 4 anos entre os marcos processuais",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "d3eb0f07-c356-563e-9208-2260e6534180",
        "questao_id": "886ab0e8-b047-52bc-9292-58b062c0bdb1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a2b5e7fe-8d2f-5c49-8d63-906a0291d73c",
        "questao_id": "886ab0e8-b047-52bc-9292-58b062c0bdb1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "4dc86f66-be7b-5dd6-911e-ed6ec06187d8",
    "idSlug": "l13-adm-resp-018-excludentes-responsabilidade-culpa-exclusiva",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "80853bc8-d70e-55bb-8ad2-b4439f7079b9",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na responsabilidade civil objetiva do Estado fundada na teoria do risco administrativo, a comprovação inequívoca de culpa exclusiva da vítima ou de caso fortuito/força maior absoluta rompe o nexo de causalidade entre a conduta estatal e o dano sofrido, excluindo o dever de indenizar do ente público.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina clássica de responsabilidade civil extracontratual do Estado: a teoria do risco administrativo admite excludentes de nexo causal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0918674bbc8d7efc7e8c3576f73eb2da4252cfccbfa8d8c6f870d72e1e4e55c4",
    "conceito_principal": "Causas excludentes da responsabilidade civil objetiva do Estado",
    "habilidade_cobrada": "Identificar as excludentes de nexo de causalidade na teoria do risco administrativo",
    "tese_ou_regra": "Culpa exclusiva da vítima e força maior excluem a responsabilidade estatal por ruptura do nexo",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "bca6bb25-1e89-507a-b42f-2889b75b1c27",
        "questao_id": "4dc86f66-be7b-5dd6-911e-ed6ec06187d8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6828a4a3-3824-5023-be77-3ffb349abca7",
        "questao_id": "4dc86f66-be7b-5dd6-911e-ed6ec06187d8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "efe239cc-502d-553e-9976-13275af54c58",
    "idSlug": "l13-adm-lic-019-portal-nacional-contratacoes-publicas-pncp",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "25c0e38d-9020-5c46-849e-8c796fed3d27",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A Lei nº 14.133/2021 criou o Portal Nacional de Contratações Públicas (PNCP), sítio eletrônico oficial centralizado destinado à divulgação obrigatória dos editais de licitação, atas de registro de preços, contratos e termos aditivos celebrados por todos os entes federativos da Administração direta, autárquica e fundacional.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 174 da Lei nº 14.133/2021: o PNCP é instrumento central de transparência e publicidade obrigatória das licitações.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2cf72b12aa1e2ccd55007aeb886148d927cc10a425060e7d76a976b144d877f6",
    "conceito_principal": "Portal Nacional de Contratações Públicas (PNCP) e publicidade",
    "habilidade_cobrada": "Reconhecer o papel e a obrigatoriedade de publicação no PNCP na Nova Lei de Licitações",
    "tese_ou_regra": "A publicação de atos licitatórios e contratos no PNCP é condição de eficácia na Lei 14.133/21",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b3d5ae61-9c06-5e88-81ef-53d0cb652433",
        "questao_id": "efe239cc-502d-553e-9976-13275af54c58",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3bc7f410-1065-5931-801e-2f7913b0fc0b",
        "questao_id": "efe239cc-502d-553e-9976-13275af54c58",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8f9098b2-7907-540a-9304-2547bff16ae8",
    "idSlug": "l13-adm-age-020-processo-disciplinar-sumula-vinculante-5-advogado",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "f53e41f4-2792-53ab-8bc8-b6810fb944c0",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A respeito da defesa técnica no âmbito do Processo Administrativo Disciplinar (PAD), o Supremo Tribunal Federal editou a Súmula Vinculante nº 5. De acordo com o referido enunciado vinculante:",
    "explicacao": "GABARITO: A. Súmula Vinculante 5 do STF: a falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3693e097d8785efa089dabcbbe99c226cc1277689bb519420b9c70f59acb3515",
    "conceito_principal": "Súmula Vinculante nº 5 e defesa técnica no processo disciplinar",
    "habilidade_cobrada": "Aplicar a Súmula Vinculante 5 do STF à condução de procedimentos disciplinares policiais",
    "tese_ou_regra": "A ausência de advogado no processo administrativo disciplinar não invalida o procedimento",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "34ca72b3-6112-5b86-a634-43eb52ba5907",
        "questao_id": "8f9098b2-7907-540a-9304-2547bff16ae8",
        "letra": "A",
        "texto": "A falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Texto literal da Súmula Vinculante nº 5 do STF."
      },
      {
        "id": "53a92346-f36d-5cf5-8291-83c435aa99c3",
        "questao_id": "8f9098b2-7907-540a-9304-2547bff16ae8",
        "letra": "B",
        "texto": "É obrigatória a presença de advogado constituído em todos os atos do PAD sob pena de nulidade absoluta e automática.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A SV 5 pacificou que a presença de advogado é facultativa."
      },
      {
        "id": "6d9bcd07-d5ba-5c20-ba83-70ccf19c0e42",
        "questao_id": "8f9098b2-7907-540a-9304-2547bff16ae8",
        "letra": "C",
        "texto": "A Defensoria Pública deve obrigatoriamente patrocinar todo servidor público processado disciplinarmente que receba até cinco salários mínimos.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Não há essa exigência na súmula vinculante."
      },
      {
        "id": "92b9ceda-fb39-5996-ba83-de4e8490ea27",
        "questao_id": "8f9098b2-7907-540a-9304-2547bff16ae8",
        "letra": "D",
        "texto": "A comissão processante não é obrigada a intimar o servidor para prestar depoimento pessoal.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O interrogatório/depoimento e a oportunidade de defesa pessoal são garantias inafastáveis."
      },
      {
        "id": "5e983562-b33d-55b3-be69-a34919ff468d",
        "questao_id": "8f9098b2-7907-540a-9304-2547bff16ae8",
        "letra": "E",
        "texto": "O servidor fica impedido de nomear procurador leigo para apresentar sua defesa escrita.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O servidor pode defender-se pessoalmente ou constituir procurador."
      }
    ]
  }
];
