// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 15

export const m22_questoes = [
  {
    "id": "af6c6ee5-e53c-5ead-9ba5-eea93e567971",
    "idSlug": "l13-port-gram-001-concordancia-verbal",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6b6e36f324d0031ae9a066b6e23abc462aa4e77df8c4adb0efaa6057bb485d0a",
    "conceito_principal": "Concordância verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Concordância verbal em contexto de carreira policial",
    "tese_ou_regra": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "ecf3efc7-ffdd-5d50-807f-5f1f5ab18bfd",
        "questao_id": "af6c6ee5-e53c-5ead-9ba5-eea93e567971",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b9836e78-dc2d-59be-8646-470fd28dbbb1",
        "questao_id": "af6c6ee5-e53c-5ead-9ba5-eea93e567971",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ce90b8bf-a551-59c0-b45d-433d2d4fb8e0",
    "idSlug": "l13-port-gram-002-crase",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b26a84c27e01fb9dfb3faaa74bbd841accaeee32790ed9c4aa632ffa7d74cceb",
    "conceito_principal": "Crase",
    "habilidade_cobrada": "Avaliar aplicação do tema Crase em contexto de carreira policial",
    "tese_ou_regra": "A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "292e76a3-41f5-5a00-bb0e-f4e329d40f16",
        "questao_id": "ce90b8bf-a551-59c0-b45d-433d2d4fb8e0",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e3e24126-4c91-5f19-92ce-8492113f944b",
        "questao_id": "ce90b8bf-a551-59c0-b45d-433d2d4fb8e0",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "286f1d62-b7c4-5ab6-b58b-711b401fd82c",
    "idSlug": "l13-port-gram-003-regencia",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2c5e5c7c8b07e32def5b8c56d674810816da651a74bfbc569fda2179d445e6ba",
    "conceito_principal": "Regência verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Regência verbal em contexto de carreira policial",
    "tese_ou_regra": "Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "8cfc3e85-47d3-563d-9dd1-8e3b3844a670",
        "questao_id": "286f1d62-b7c4-5ab6-b58b-711b401fd82c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "16ac3fdc-a8c8-59fa-990e-b7397742cecc",
        "questao_id": "286f1d62-b7c4-5ab6-b58b-711b401fd82c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0708c91b-acb7-5c54-9490-ebbe9e44a70c",
    "idSlug": "l13-port-gram-004-sintaxe-adjunto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2d20c170-3c4e-5171-91d2-fe97c4b92480",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Complemento nominal modifica apenas verbos transitivos diretos, equivalendo sempre ao objeto direto da oração.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Adjunto adnominal e complemento nominal; a regra adequada é: Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5e9f80eb021b28b0994cf031726cb6b0924fb33805ce050833d165dfb01b92f1",
    "conceito_principal": "Adjunto adnominal e complemento nominal",
    "habilidade_cobrada": "Avaliar aplicação do tema Adjunto adnominal e complemento nominal em contexto de carreira policial",
    "tese_ou_regra": "Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "c65fdb29-62ee-58c2-b68e-5848fb1fe7e4",
        "questao_id": "0708c91b-acb7-5c54-9490-ebbe9e44a70c",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "9b2c6d23-9528-5e5b-908b-99f40fc57c2f",
        "questao_id": "0708c91b-acb7-5c54-9490-ebbe9e44a70c",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
    "idSlug": "l13-port-gram-005-morfologia-pronomes",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "ae0cb1a9-da13-5d87-92b8-c498b65f5f17",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em situação prática envolvendo Pronomes e colocação pronominal, assinale a alternativa correta para a atuação institucional de agente de polícia federal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "87190e4521873daa8ace57f011e72df3ae8b8a3cd11ca2beb42411ce61e98889",
    "conceito_principal": "Pronomes e colocação pronominal",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Pronomes e colocação pronominal",
    "tese_ou_regra": "A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "e6d91924-01b4-5d4a-aeb0-2fb5b9767c40",
        "questao_id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
        "letra": "A",
        "texto": "Afastar Pronomes e colocação pronominal por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "b66313cb-6751-5c22-9337-2bc7e9c36e90",
        "questao_id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
        "letra": "B",
        "texto": "Aplicar Pronomes e colocação pronominal somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "5f5cfc54-b04e-591e-9061-e8e1812c1805",
        "questao_id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
        "letra": "C",
        "texto": "Substituir Pronomes e colocação pronominal por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "8abae827-bcfb-50db-827d-c02d80f67ec5",
        "questao_id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
        "letra": "D",
        "texto": "Considerar que Pronomes e colocação pronominal não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "ac351c6d-b8a7-51da-99d4-ff2919c13491",
        "questao_id": "d2c7af3a-af0a-5330-a0fa-efab534c843e",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  },
  {
    "id": "4818f11c-513c-5563-b068-8bf54135a464",
    "idSlug": "l13-port-gram-006-concordancia-verbal",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6b6e36f324d0031ae9a066b6e23abc462aa4e77df8c4adb0efaa6057bb485d0a",
    "conceito_principal": "Concordância verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Concordância verbal em contexto de carreira policial",
    "tese_ou_regra": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "83feaa90-70db-5295-96a1-aeb92fa1ba5c",
        "questao_id": "4818f11c-513c-5563-b068-8bf54135a464",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9fae366c-82d4-5529-ab61-0ab8d04c18d2",
        "questao_id": "4818f11c-513c-5563-b068-8bf54135a464",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d8f703c3-5fed-5d83-9a8b-c99a8d16fca8",
    "idSlug": "l13-port-gram-007-crase",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b26a84c27e01fb9dfb3faaa74bbd841accaeee32790ed9c4aa632ffa7d74cceb",
    "conceito_principal": "Crase",
    "habilidade_cobrada": "Avaliar aplicação do tema Crase em contexto de carreira policial",
    "tese_ou_regra": "A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "69eafe33-58cf-57d4-89cc-f3ed55d8af90",
        "questao_id": "d8f703c3-5fed-5d83-9a8b-c99a8d16fca8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2db37c7f-1c0a-5d97-9ac3-fb147f991dc5",
        "questao_id": "d8f703c3-5fed-5d83-9a8b-c99a8d16fca8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8200250c-8c4a-5bc3-a198-85603f742207",
    "idSlug": "l13-port-gram-008-regencia",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A regência verbal é indiferente ao sentido do verbo, de modo que qualquer preposição pode introduzir seu complemento.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Regência verbal; a regra adequada é: Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e041b400a04f3a035a208e520fb829fd6cbd65a57fdb5bde7096ffa101fca98d",
    "conceito_principal": "Regência verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Regência verbal em contexto de carreira policial",
    "tese_ou_regra": "Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "ce683597-125e-5c6c-ad15-bdfef82750fe",
        "questao_id": "8200250c-8c4a-5bc3-a198-85603f742207",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "0bd2acea-f9e4-5037-86da-f6fc3a2d0f1a",
        "questao_id": "8200250c-8c4a-5bc3-a198-85603f742207",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "51edf996-88ef-54c6-8635-740c78b71280",
    "idSlug": "l13-port-gram-009-sintaxe-adjunto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2d20c170-3c4e-5171-91d2-fe97c4b92480",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "87a2433d469a4783e2c796ff06fbecea8a126cb7a851b151ae7ae6b5bcc69df1",
    "conceito_principal": "Adjunto adnominal e complemento nominal",
    "habilidade_cobrada": "Avaliar aplicação do tema Adjunto adnominal e complemento nominal em contexto de carreira policial",
    "tese_ou_regra": "Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "43d864e7-218e-5d9b-ad3f-8de59d793b65",
        "questao_id": "51edf996-88ef-54c6-8635-740c78b71280",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5e1f3a54-43e2-5b35-a8ff-03782d8a778d",
        "questao_id": "51edf996-88ef-54c6-8635-740c78b71280",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
    "idSlug": "l13-port-gram-010-morfologia-pronomes",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "ae0cb1a9-da13-5d87-92b8-c498b65f5f17",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em situação prática envolvendo Pronomes e colocação pronominal, assinale a alternativa correta para a atuação institucional de policial rodoviário federal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7f2091ecd0635630da4823638f28437ebc2156d3dd5b3c2ef6c25ccd310f1465",
    "conceito_principal": "Pronomes e colocação pronominal",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Pronomes e colocação pronominal",
    "tese_ou_regra": "A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "2c3dda58-1202-55bb-a45a-002b6a46d24e",
        "questao_id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
        "letra": "A",
        "texto": "Afastar Pronomes e colocação pronominal por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "48aba79e-0df4-5526-a184-f777858fd3ef",
        "questao_id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
        "letra": "B",
        "texto": "Aplicar Pronomes e colocação pronominal somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "5818009d-f64d-5083-a21d-d5100a5ac3cc",
        "questao_id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
        "letra": "C",
        "texto": "Substituir Pronomes e colocação pronominal por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "cdb299f7-834d-5641-8c9f-8e15367f2d5e",
        "questao_id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
        "letra": "D",
        "texto": "Considerar que Pronomes e colocação pronominal não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "1309a722-9eac-52bf-afe9-1aec2ea7d9a7",
        "questao_id": "b600ad8a-ab86-58a1-8ae3-63f6cf084b66",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  },
  {
    "id": "6e5cf750-6e9e-5f5d-a814-76807340c9e9",
    "idSlug": "l13-port-gram-011-concordancia-verbal",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6b6e36f324d0031ae9a066b6e23abc462aa4e77df8c4adb0efaa6057bb485d0a",
    "conceito_principal": "Concordância verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Concordância verbal em contexto de carreira policial",
    "tese_ou_regra": "O verbo concorda, em regra, com o núcleo do sujeito em número e pessoa, ainda que o sujeito venha posposto ou separado do verbo por termos intercalados.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "b8165419-2158-5f7f-94f0-82c7253fb25d",
        "questao_id": "6e5cf750-6e9e-5f5d-a814-76807340c9e9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a7b73021-c497-51b2-929a-b909229e8119",
        "questao_id": "6e5cf750-6e9e-5f5d-a814-76807340c9e9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f01983df-607b-52c6-a7c0-bd4bfad63e57",
    "idSlug": "l13-port-gram-012-crase",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A crase ocorre automaticamente antes de todo substantivo feminino, mesmo quando o verbo regente não exige preposição.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Crase; a regra adequada é: A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e540c4c9f0da6993a76e95d2cff81bda6b225f55d05f36be1f56904b0a245e6c",
    "conceito_principal": "Crase",
    "habilidade_cobrada": "Avaliar aplicação do tema Crase em contexto de carreira policial",
    "tese_ou_regra": "A crase resulta da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por a, exigindo termo regente que peça preposição e termo regido feminino determinado.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "bfa7363e-56da-53a1-8b54-22f4a23d43c5",
        "questao_id": "f01983df-607b-52c6-a7c0-bd4bfad63e57",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "58cb7ae9-9727-54a4-9658-da800aae7eb1",
        "questao_id": "f01983df-607b-52c6-a7c0-bd4bfad63e57",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "f5d61bb2-5e80-505b-bf50-98426980b975",
    "idSlug": "l13-port-gram-013-regencia",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2c5e5c7c8b07e32def5b8c56d674810816da651a74bfbc569fda2179d445e6ba",
    "conceito_principal": "Regência verbal",
    "habilidade_cobrada": "Avaliar aplicação do tema Regência verbal em contexto de carreira policial",
    "tese_ou_regra": "Regência verbal descreve a relação entre verbo e seus complementos, definindo se o complemento é direto, indireto ou exige preposição específica, conforme o sentido empregado.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "2b33f3b1-91b5-5f27-baa0-8d71c95802fb",
        "questao_id": "f5d61bb2-5e80-505b-bf50-98426980b975",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6abbe71f-f671-5b93-a037-8d64550c60ef",
        "questao_id": "f5d61bb2-5e80-505b-bf50-98426980b975",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b0cf64e2-c786-5612-965c-b3c268df6ae6",
    "idSlug": "l13-port-gram-014-sintaxe-adjunto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2d20c170-3c4e-5171-91d2-fe97c4b92480",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "87a2433d469a4783e2c796ff06fbecea8a126cb7a851b151ae7ae6b5bcc69df1",
    "conceito_principal": "Adjunto adnominal e complemento nominal",
    "habilidade_cobrada": "Avaliar aplicação do tema Adjunto adnominal e complemento nominal em contexto de carreira policial",
    "tese_ou_regra": "Adjunto adnominal caracteriza ou determina substantivo, frequentemente com valor ativo/possessivo, ao passo que complemento nominal completa nome abstrato, adjetivo ou advérbio com valor frequentemente passivo.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a81d4272-c346-525a-b1a6-90f8fbdd3c71",
        "questao_id": "b0cf64e2-c786-5612-965c-b3c268df6ae6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "17a1af26-534b-576a-80b8-cfbf33446421",
        "questao_id": "b0cf64e2-c786-5612-965c-b3c268df6ae6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "507bda58-42b6-5064-962f-c183e73a4d10",
    "idSlug": "l13-port-gram-015-morfologia-pronomes",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "ae0cb1a9-da13-5d87-92b8-c498b65f5f17",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Em situação prática envolvendo Pronomes e colocação pronominal, assinale a alternativa correta para a atuação institucional de guarda civil municipal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c10ef2d3876168c3d7266a3432fa02dc1817cda3ab2bc572ca49c206cd0e1bca",
    "conceito_principal": "Pronomes e colocação pronominal",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Pronomes e colocação pronominal",
    "tese_ou_regra": "A colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "89f1c7a9-b349-5d52-97e0-129b37e39913",
        "questao_id": "507bda58-42b6-5064-962f-c183e73a4d10",
        "letra": "A",
        "texto": "Afastar Pronomes e colocação pronominal por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "7612ada1-a55b-5136-af07-1e5008581082",
        "questao_id": "507bda58-42b6-5064-962f-c183e73a4d10",
        "letra": "B",
        "texto": "Aplicar Pronomes e colocação pronominal somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "ba29fe9f-f943-5f0c-812c-191d1fa42207",
        "questao_id": "507bda58-42b6-5064-962f-c183e73a4d10",
        "letra": "C",
        "texto": "Substituir Pronomes e colocação pronominal por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "0b83225c-dd1a-5718-ae9e-fd5cbbf3e156",
        "questao_id": "507bda58-42b6-5064-962f-c183e73a4d10",
        "letra": "D",
        "texto": "Considerar que Pronomes e colocação pronominal não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "c01af7ed-3f20-56df-abf4-4cdc642c096a",
        "questao_id": "507bda58-42b6-5064-962f-c183e73a4d10",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a colocação pronominal em português observa fatores de atração, tempos verbais e formalidade; palavras negativas, pronomes relativos e conjunções subordinativas atraem próclise em norma-padrão.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  }
];
