// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 20

export const m20_questoes = [
  {
    "id": "56c7f0b5-f294-5508-b557-2bafde51557b",
    "idSlug": "l13-rlm-prob-001-conjuntos-inclusao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "79d058d3-3b1a-5aa3-98ce-f0232fc612d3",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0015b828051ceb1b23e06d22f60f27f925a0a2aea4fa67ff56e685d0d7435d68",
    "conceito_principal": "Princípio da inclusão-exclusão",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio da inclusão-exclusão em contexto de carreira policial",
    "tese_ou_regra": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "68a0e5ff-e655-51e4-9ce2-0a03b210a1da",
        "questao_id": "56c7f0b5-f294-5508-b557-2bafde51557b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c5892959-05e5-51d9-82a4-0a7525038b79",
        "questao_id": "56c7f0b5-f294-5508-b557-2bafde51557b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f0e08f2b-7cc3-5646-be6a-b65da5e7234c",
    "idSlug": "l13-rlm-prob-002-arranjo-combinacao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1316b359dd535d5128c8805fedb9a36876e624e8ca10c2226a068c09e0f6213c",
    "conceito_principal": "Arranjos e combinações",
    "habilidade_cobrada": "Avaliar aplicação do tema Arranjos e combinações em contexto de carreira policial",
    "tese_ou_regra": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "96924cc6-3f50-5e25-9087-14b18969a6a8",
        "questao_id": "f0e08f2b-7cc3-5646-be6a-b65da5e7234c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f8ca2345-ec7a-5dc8-9187-f05c4358e098",
        "questao_id": "f0e08f2b-7cc3-5646-be6a-b65da5e7234c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "3f55b1c8-fe84-5216-91c8-f753714fd2b4",
    "idSlug": "l13-rlm-prob-003-principio-multiplicativo",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "349f9c3075564bc22bfe49254a727eeaf3d600337ecbd33908a6598989e472c8",
    "conceito_principal": "Princípio fundamental da contagem",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio fundamental da contagem em contexto de carreira policial",
    "tese_ou_regra": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "f9b3fe14-c7c6-58f9-8891-c17862ce3698",
        "questao_id": "3f55b1c8-fe84-5216-91c8-f753714fd2b4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c78e02c3-c241-5cec-b577-16e429a4a603",
        "questao_id": "3f55b1c8-fe84-5216-91c8-f753714fd2b4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d112172e-0528-57f9-855a-d6e9fef61c11",
    "idSlug": "l13-rlm-prob-004-probabilidade-complementar",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A probabilidade do evento complementar é sempre igual à probabilidade do próprio evento quando o espaço amostral é finito.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Probabilidade do evento complementar; a regra adequada é: A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "89b44cb2b25c26f9423b436c59b336f2c5f239e9d8af4c7fe77f3d33b20ec732",
    "conceito_principal": "Probabilidade do evento complementar",
    "habilidade_cobrada": "Avaliar aplicação do tema Probabilidade do evento complementar em contexto de carreira policial",
    "tese_ou_regra": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "910eaa27-d62a-597c-9134-d727bae75364",
        "questao_id": "d112172e-0528-57f9-855a-d6e9fef61c11",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "f3d7f5b6-8555-5d61-b674-5feab1d466fe",
        "questao_id": "d112172e-0528-57f9-855a-d6e9fef61c11",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
    "idSlug": "l13-rlm-prob-005-media-mediana",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em situação prática envolvendo Medidas de tendência central, assinale a alternativa correta para a atuação institucional de agente de polícia federal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b725b3a370080afc5a4ff16894031caa5192a8bf3433305b9dee5b7f553620bd",
    "conceito_principal": "Medidas de tendência central",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Medidas de tendência central",
    "tese_ou_regra": "A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "6ae6dff8-5817-5468-a183-82669d750731",
        "questao_id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
        "letra": "A",
        "texto": "Afastar Medidas de tendência central por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "45ca9884-b65b-565f-85a2-97941103166c",
        "questao_id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
        "letra": "B",
        "texto": "Aplicar Medidas de tendência central somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "f489ab3f-0b3f-5ece-a3f0-4049d183b7d5",
        "questao_id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
        "letra": "C",
        "texto": "Substituir Medidas de tendência central por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "757df717-c78d-5211-90a6-802655ac5277",
        "questao_id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
        "letra": "D",
        "texto": "Considerar que Medidas de tendência central não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "8da6071b-4a61-5e20-901e-0923ff3077e8",
        "questao_id": "1d6e1b33-3512-597b-8a72-b03f47e82597",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  },
  {
    "id": "7dccd2f1-6bc2-551f-9cef-0c8a1e0a4b36",
    "idSlug": "l13-rlm-prob-006-conjuntos-inclusao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "79d058d3-3b1a-5aa3-98ce-f0232fc612d3",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0015b828051ceb1b23e06d22f60f27f925a0a2aea4fa67ff56e685d0d7435d68",
    "conceito_principal": "Princípio da inclusão-exclusão",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio da inclusão-exclusão em contexto de carreira policial",
    "tese_ou_regra": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5f8cae4b-9ff1-5ef3-87c8-e51aaa042381",
        "questao_id": "7dccd2f1-6bc2-551f-9cef-0c8a1e0a4b36",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "df55b453-0e02-544a-8728-a0ab78a03445",
        "questao_id": "7dccd2f1-6bc2-551f-9cef-0c8a1e0a4b36",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "49857970-3d4f-5dcd-a603-86930b84fd4b",
    "idSlug": "l13-rlm-prob-007-arranjo-combinacao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1316b359dd535d5128c8805fedb9a36876e624e8ca10c2226a068c09e0f6213c",
    "conceito_principal": "Arranjos e combinações",
    "habilidade_cobrada": "Avaliar aplicação do tema Arranjos e combinações em contexto de carreira policial",
    "tese_ou_regra": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "b112b49f-0112-5faa-ac0d-cee05acf143a",
        "questao_id": "49857970-3d4f-5dcd-a603-86930b84fd4b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "34f8145e-4245-572f-9c3e-ef9678509445",
        "questao_id": "49857970-3d4f-5dcd-a603-86930b84fd4b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8975542d-a66d-5172-9f23-0b2ee30ac497",
    "idSlug": "l13-rlm-prob-008-principio-multiplicativo",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "No princípio multiplicativo, escolhas sucessivas independentes devem ser somadas, nunca multiplicadas.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Princípio fundamental da contagem; a regra adequada é: Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "94e5c633bf9ddb427ab575eef90f4e3c58f41cad321a81127525a5c8232e1ec7",
    "conceito_principal": "Princípio fundamental da contagem",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio fundamental da contagem em contexto de carreira policial",
    "tese_ou_regra": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "0cdda3fd-6c23-5223-9b22-c746596968be",
        "questao_id": "8975542d-a66d-5172-9f23-0b2ee30ac497",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "a14e076b-2f56-5adb-b5df-aad5c3336000",
        "questao_id": "8975542d-a66d-5172-9f23-0b2ee30ac497",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "a58c69cd-c271-5347-958c-f35140ec61f1",
    "idSlug": "l13-rlm-prob-009-probabilidade-complementar",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5e7b37a597f033df25781586b992de52f30110ea71c60995a8018addc21c6fc0",
    "conceito_principal": "Probabilidade do evento complementar",
    "habilidade_cobrada": "Avaliar aplicação do tema Probabilidade do evento complementar em contexto de carreira policial",
    "tese_ou_regra": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "3d8d9765-7af4-5c27-8ee4-163a8c79bc19",
        "questao_id": "a58c69cd-c271-5347-958c-f35140ec61f1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b6871ec0-ffcd-5125-b73a-c029ea408b42",
        "questao_id": "a58c69cd-c271-5347-958c-f35140ec61f1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
    "idSlug": "l13-rlm-prob-010-media-mediana",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em situação prática envolvendo Medidas de tendência central, assinale a alternativa correta para a atuação institucional de policial rodoviário federal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a99de70189eea1f2d86bfa7bda770730996927964700b816e33a9e9b89cb34a3",
    "conceito_principal": "Medidas de tendência central",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Medidas de tendência central",
    "tese_ou_regra": "A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "ebb91044-8753-51eb-bcca-380f83e8eb47",
        "questao_id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
        "letra": "A",
        "texto": "Afastar Medidas de tendência central por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "ce3b6878-aa83-56c0-a455-4d5348d654c5",
        "questao_id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
        "letra": "B",
        "texto": "Aplicar Medidas de tendência central somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "c1689d83-31ad-5a19-9f0e-5fac5dfd654c",
        "questao_id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
        "letra": "C",
        "texto": "Substituir Medidas de tendência central por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "ec938a8e-86b3-54d9-862f-1984fd5172dd",
        "questao_id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
        "letra": "D",
        "texto": "Considerar que Medidas de tendência central não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "5d29a6fc-385b-5f07-b91a-d94a68148b81",
        "questao_id": "e526d0f2-5f2c-5f01-821e-72f200b86971",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  },
  {
    "id": "b3973e18-5680-5072-bc48-9763dc5a7d9d",
    "idSlug": "l13-rlm-prob-011-conjuntos-inclusao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "79d058d3-3b1a-5aa3-98ce-f0232fc612d3",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0015b828051ceb1b23e06d22f60f27f925a0a2aea4fa67ff56e685d0d7435d68",
    "conceito_principal": "Princípio da inclusão-exclusão",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio da inclusão-exclusão em contexto de carreira policial",
    "tese_ou_regra": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "b81faf13-5838-54ba-aca8-f997fdd387f8",
        "questao_id": "b3973e18-5680-5072-bc48-9763dc5a7d9d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ef242116-1659-5456-985c-a4f668d971d0",
        "questao_id": "b3973e18-5680-5072-bc48-9763dc5a7d9d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "27e00532-9b55-59b1-b4db-fca4dfa40899",
    "idSlug": "l13-rlm-prob-012-arranjo-combinacao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Combinação e arranjo sempre produzem o mesmo resultado porque ambos escolhem elementos sem reposição.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Arranjos e combinações; a regra adequada é: Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2ea8d8fa17090a28bdfdf3b96a744772f98b6bd218a41721e0713dfc35b325fe",
    "conceito_principal": "Arranjos e combinações",
    "habilidade_cobrada": "Avaliar aplicação do tema Arranjos e combinações em contexto de carreira policial",
    "tese_ou_regra": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "c6f5e968-bf8f-55a3-aab4-d7313987246d",
        "questao_id": "27e00532-9b55-59b1-b4db-fca4dfa40899",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "167e8d2f-237f-5687-933d-9e2cabc956cd",
        "questao_id": "27e00532-9b55-59b1-b4db-fca4dfa40899",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "88b92e08-ddb4-54e7-bd67-36ebd85c63ca",
    "idSlug": "l13-rlm-prob-013-principio-multiplicativo",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "349f9c3075564bc22bfe49254a727eeaf3d600337ecbd33908a6598989e472c8",
    "conceito_principal": "Princípio fundamental da contagem",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio fundamental da contagem em contexto de carreira policial",
    "tese_ou_regra": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "49060d35-f14d-5604-9c54-021e2e324def",
        "questao_id": "88b92e08-ddb4-54e7-bd67-36ebd85c63ca",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "16f8dbe5-e704-5877-adc7-a12213656ce2",
        "questao_id": "88b92e08-ddb4-54e7-bd67-36ebd85c63ca",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "3ed03d02-0e68-5ca6-9748-4aafe587aa68",
    "idSlug": "l13-rlm-prob-014-probabilidade-complementar",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5e7b37a597f033df25781586b992de52f30110ea71c60995a8018addc21c6fc0",
    "conceito_principal": "Probabilidade do evento complementar",
    "habilidade_cobrada": "Avaliar aplicação do tema Probabilidade do evento complementar em contexto de carreira policial",
    "tese_ou_regra": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2cd67cbf-60e1-5955-9d67-0430acbb4927",
        "questao_id": "3ed03d02-0e68-5ca6-9748-4aafe587aa68",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7649ab88-82c9-5371-8d39-b6de9706c946",
        "questao_id": "3ed03d02-0e68-5ca6-9748-4aafe587aa68",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "76f56830-7290-514a-a4a7-70b2a159111e",
    "idSlug": "l13-rlm-prob-015-media-mediana",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Em situação prática envolvendo Medidas de tendência central, assinale a alternativa correta para a atuação institucional de guarda civil municipal.",
    "explicacao": "A alternativa correta conserva a regra matriz: A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c7f51c8b139a4e6fed4d54fe149df51b6fa87880ca2c825f022ced810b2f2113",
    "conceito_principal": "Medidas de tendência central",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Medidas de tendência central",
    "tese_ou_regra": "A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "44bafe3d-cfa5-5532-9ee7-43bed021fbc4",
        "questao_id": "76f56830-7290-514a-a4a7-70b2a159111e",
        "letra": "A",
        "texto": "Afastar Medidas de tendência central por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "4edc4913-e71c-538e-8032-f953914cf981",
        "questao_id": "76f56830-7290-514a-a4a7-70b2a159111e",
        "letra": "B",
        "texto": "Aplicar Medidas de tendência central somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "cc3ac240-b0b5-5611-93f0-fa9ae7e30d1c",
        "questao_id": "76f56830-7290-514a-a4a7-70b2a159111e",
        "letra": "C",
        "texto": "Substituir Medidas de tendência central por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "5085b524-7f63-54a6-b208-5ee935bbc071",
        "questao_id": "76f56830-7290-514a-a4a7-70b2a159111e",
        "letra": "D",
        "texto": "Considerar que Medidas de tendência central não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "2fa5b745-dcb2-5a27-918a-5a0ab933b50e",
        "questao_id": "76f56830-7290-514a-a4a7-70b2a159111e",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  },
  {
    "id": "132e955a-89b7-51e7-8021-b86bce3cc46a",
    "idSlug": "l13-rlm-prob-016-conjuntos-inclusao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "79d058d3-3b1a-5aa3-98ce-f0232fc612d3",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) + n(A ∩ B), pois a interseção deve ser somada duas vezes.",
    "explicacao": "GABARITO: ERRADO. A assertiva está incorreta. A formulação distorce o instituto cobrado em Princípio da inclusão-exclusão; a regra adequada é: Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fe60bf0421ab80a32b22e770f809bf143145715c9368d9d84016c3e305176a97",
    "conceito_principal": "Princípio da inclusão-exclusão",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio da inclusão-exclusão em contexto de carreira policial",
    "tese_ou_regra": "Para dois conjuntos finitos, n(A ∪ B) = n(A) + n(B) - n(A ∩ B), evitando a contagem duplicada dos elementos comuns.",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "968774d6-01fa-571e-b760-1e01df87f152",
        "questao_id": "132e955a-89b7-51e7-8021-b86bce3cc46a",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "512b0e9c-1bb3-5dd0-b26c-0af14a88af62",
        "questao_id": "132e955a-89b7-51e7-8021-b86bce3cc46a",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "668e3cbc-5f4a-50ec-8aee-68696ce94333",
    "idSlug": "l13-rlm-prob-017-arranjo-combinacao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "FGV",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1316b359dd535d5128c8805fedb9a36876e624e8ca10c2226a068c09e0f6213c",
    "conceito_principal": "Arranjos e combinações",
    "habilidade_cobrada": "Avaliar aplicação do tema Arranjos e combinações em contexto de carreira policial",
    "tese_ou_regra": "Arranjo considera a ordem dos elementos selecionados; combinação desconsidera a ordem, contando apenas subconjuntos de mesmo tamanho.",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "a15f2592-044d-5f69-abf9-5214e5b45443",
        "questao_id": "668e3cbc-5f4a-50ec-8aee-68696ce94333",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "59deaf3d-99e7-51c1-b536-b91584e21e5a",
        "questao_id": "668e3cbc-5f4a-50ec-8aee-68696ce94333",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ebaa226e-4f68-5e50-873b-833f3ef1670f",
    "idSlug": "l13-rlm-prob-018-principio-multiplicativo",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "349f9c3075564bc22bfe49254a727eeaf3d600337ecbd33908a6598989e472c8",
    "conceito_principal": "Princípio fundamental da contagem",
    "habilidade_cobrada": "Avaliar aplicação do tema Princípio fundamental da contagem em contexto de carreira policial",
    "tese_ou_regra": "Se uma decisão pode ser tomada de m modos e, para cada um deles, outra de n modos, então o número de resultados sucessivos é m vezes n.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "e3c27e29-a2f0-59ba-87a9-f03106ce0cad",
        "questao_id": "ebaa226e-4f68-5e50-873b-833f3ef1670f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "1aaa5ba9-8adf-5ef9-9ed0-5484acf55d22",
        "questao_id": "ebaa226e-4f68-5e50-873b-833f3ef1670f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d0ca2370-ed5e-521d-a136-12f165edf353",
    "idSlug": "l13-rlm-prob-019-probabilidade-complementar",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "explicacao": "GABARITO: CERTO. A assertiva está correta. A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5e7b37a597f033df25781586b992de52f30110ea71c60995a8018addc21c6fc0",
    "conceito_principal": "Probabilidade do evento complementar",
    "habilidade_cobrada": "Avaliar aplicação do tema Probabilidade do evento complementar em contexto de carreira policial",
    "tese_ou_regra": "A probabilidade do evento complementar é P(A^c)=1-P(A), desde que os eventos sejam considerados no mesmo espaço amostral.",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "661f1442-3840-524f-b4b2-cc408c540629",
        "questao_id": "d0ca2370-ed5e-521d-a136-12f165edf353",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "379a62b9-fd63-5224-906a-86481d81ac1f",
        "questao_id": "d0ca2370-ed5e-521d-a136-12f165edf353",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
    "idSlug": "l13-rlm-prob-020-media-mediana",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "facil",
    "enunciado": "Em situação prática envolvendo Medidas de tendência central, assinale a alternativa correta para a atuação institucional de soldado da polícia militar.",
    "explicacao": "A alternativa correta conserva a regra matriz: A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série. As demais proposições trocam garantia por conveniência, dispensam requisito ou ampliam indevidamente poder estatal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "bc9c24f4697e62b775a724addd2cd71ef1e4cdbec1701fdde478d1e3566950bc",
    "conceito_principal": "Medidas de tendência central",
    "habilidade_cobrada": "Selecionar a consequência jurídica correta em caso prático sobre Medidas de tendência central",
    "tese_ou_regra": "A média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "7b8cab31-6ab0-54f6-b6bc-ed7f88965c6c",
        "questao_id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
        "letra": "A",
        "texto": "Afastar Medidas de tendência central por mera conveniência administrativa, ainda que a norma imponha garantia mínima inderrogável.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "5c383727-6b5c-5763-ab62-7f43e9f69e7a",
        "questao_id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
        "letra": "B",
        "texto": "Aplicar Medidas de tendência central somente quando houver autorização posterior da autoridade policial, dispensando o parâmetro normativo principal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "d107397a-eb8e-5a33-9196-5f0b8c5fc81f",
        "questao_id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
        "letra": "C",
        "texto": "Substituir Medidas de tendência central por juízo discricionário sem motivação, suficiente por si só para restringir direito fundamental.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "3908341c-0c60-516b-86c1-f29a869ba4bd",
        "questao_id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
        "letra": "D",
        "texto": "Considerar que Medidas de tendência central não produz efeitos em concursos policiais por se tratar de matéria apenas teórica.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Alternativa incorreta: altera pressuposto normativo, confunde institutos ou dispensa requisito obrigatório."
      },
      {
        "id": "e7f96ad3-903d-56a9-a38a-94242a4a9616",
        "questao_id": "78387e51-10fc-5539-a87e-a82ddf281a8a",
        "letra": "E",
        "texto": "Observar a regra segundo a qual a média aritmética é a soma dos valores dividida pela quantidade de observações, enquanto a mediana é o valor central após ordenação da série.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Alternativa correta: preserva o parâmetro legal ou jurisprudencial exigido."
      }
    ]
  }
];
