import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const ce = (slug, disc, assunto, banca, orgao, cargo, dif, enunciado, explicacao, correta = true) => ({
  idSlug: slug,
  disciplina_id: `TAXONOMIA.disciplinas.${disc}`,
  assunto_id: `TAXONOMIA.assuntos.${assunto}`,
  banca_nome: banca,
  orgao_nome: orgao,
  cargo_nome: cargo,
  ano: 2026,
  tipo: "certo_errado",
  dificuldade: dif,
  enunciado,
  explicacao,
  alternativas: [
    { texto: "Certo", correta },
    { texto: "Errado", correta: !correta },
  ],
});

const me = (slug, disc, assunto, banca, orgao, cargo, dif, enunciado, explicacao, alternativas) => ({
  idSlug: slug,
  disciplina_id: `TAXONOMIA.disciplinas.${disc}`,
  assunto_id: `TAXONOMIA.assuntos.${assunto}`,
  banca_nome: banca,
  orgao_nome: orgao,
  cargo_nome: cargo,
  ano: 2026,
  tipo: "multipla_escolha",
  dificuldade: dif,
  enunciado,
  explicacao,
  alternativas,
});

const A = (texto, correta = false) => ({ texto, correta });

const banksCE = ["Inédita / Estilo CEBRASPE", "Inédita / Estilo CEBRASPE", "Inédita / Estilo CEBRASPE"];
const banksME = ["Inédita / Estilo FGV", "Inédita / Estilo VUNESP", "Inédita / Estilo FCC"];
const orgs = ["Polícia Federal", "Polícia Rodoviária Federal", "Polícia Civil", "Polícia Militar", "Polícia Penal", "Guarda Municipal"];
const cargos = ["Agente de Polícia Federal", "Policial Rodoviário Federal", "Delegado de Polícia", "Investigador de Polícia", "Escrivão de Polícia", "Soldado da Polícia Militar", "Policial Penal"];
const difs = ["facil", "medio", "dificil"];

function lit(v) {
  if (typeof v === "string" && v.startsWith("TAXONOMIA.")) return v;
  return JSON.stringify(v);
}

function renderValue(v, indent = 2) {
  const sp = " ".repeat(indent);
  const sp2 = " ".repeat(indent + 2);
  if (Array.isArray(v)) {
    return `[
${v.map((x) => `${sp2}${renderValue(x, indent + 2)}`).join(",\n")}
${sp}]`;
  }
  if (v && typeof v === "object") {
    const entries = Object.entries(v).map(([k, val]) => `${sp2}${k}: ${renderValue(val, indent + 2)}`);
    return `{
${entries.join(",\n")}
${sp}}`;
  }
  return lit(v);
}

function writeModule(fileName, exportName, questions) {
  const body = questions.map((q) => `  ${renderValue(q, 2)}`).join(",\n");
  fs.writeFileSync(path.join(__dirname, fileName), `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const ${exportName} = [\n${body}\n];\n`, "utf8");
}

const modules = [];

function addModule(fileName, exportName, questions) {
  modules.push({ fileName, exportName, questions });
}

// Legislação Especial 01 - Drogas, Desarmamento, ORCRIM
addModule("leg_esp_01.mjs", "legEsp01Questoes", [
  ce("b10-legesp-01-001", "legislacao_especial", "lei_drogas_11343", banksCE[0], orgs[0], cargos[0], "medio", "A Lei de Drogas prevê causa de diminuição de pena para o tráfico privilegiado quando o agente é primário, possui bons antecedentes, não se dedica a atividades criminosas nem integra organização criminosa.", "GABARITO: CERTO. Art. 33, § 4º, da Lei 11.343/2006. A minorante exige cumulativamente primariedade, bons antecedentes, não dedicação a atividades criminosas e não integração a organização criminosa.", true),
  ce("b10-legesp-01-002", "legislacao_especial", "lei_drogas_11343", banksCE[1], orgs[2], cargos[2], "dificil", "Segundo entendimento consolidado do STF, o tráfico privilegiado equipara-se a crime hediondo para fins de progressão de regime e livramento condicional.", "GABARITO: ERRADO. O STF afastou a natureza hedionda do tráfico privilegiado (HC 118.533/MS), entendimento também refletido na Súmula 512 cancelada do STJ.", false),
  ce("b10-legesp-01-003", "legislacao_especial", "lei_drogas_11343", banksCE[2], orgs[1], cargos[1], "medio", "Para a lavratura do auto de prisão em flagrante por tráfico de drogas, é suficiente o laudo de constatação provisório, firmado por perito oficial ou, na falta deste, por pessoa idônea.", "GABARITO: CERTO. Art. 50, § 1º, da Lei 11.343/2006 admite laudo de constatação provisório para materialidade inicial, sem prejuízo do laudo definitivo.", true),
  ce("b10-legesp-01-004", "legislacao_especial", "lei_drogas_11343", banksCE[0], orgs[3], cargos[5], "facil", "O porte de droga para consumo pessoal, previsto no art. 28 da Lei 11.343/2006, admite pena privativa de liberdade em caso de reincidência específica.", "GABARITO: ERRADO. O art. 28 prevê advertência, prestação de serviços à comunidade e medida educativa, sem pena privativa de liberdade.", false),
  me("b10-legesp-01-005", "legislacao_especial", "lei_drogas_11343", banksME[0], orgs[0], cargos[2], "dificil", "Na ação controlada prevista na Lei de Drogas, a não atuação policial imediata em investigação de tráfico depende, como regra, de:", "GABARITO: C. Art. 53, II, da Lei 11.343/2006 exige autorização judicial, ouvido o Ministério Público, para a não atuação policial sobre os portadores de drogas, seus precursores ou outros produtos.", [A("Autorização verbal da chefia policial, dispensado controle judicial."), A("Homologação posterior exclusiva pela corregedoria."), A("Autorização judicial, ouvido o Ministério Público.", true), A("Requisição da autoridade alfandegária internacional."), A("Confissão formal de colaborador premiado.")]),
  ce("b10-legesp-01-006", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[0], orgs[1], cargos[1], "facil", "O crime de posse irregular de arma de fogo de uso permitido consuma-se quando o agente mantém arma em desacordo com determinação legal ou regulamentar no interior de sua residência ou dependência desta.", "GABARITO: CERTO. Art. 12 da Lei 10.826/2003: posse irregular refere-se à manutenção no interior de residência, dependência ou local de trabalho do titular/responsável.", true),
  ce("b10-legesp-01-007", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[1], orgs[2], cargos[3], "medio", "O porte ilegal de arma de fogo de uso permitido exige demonstração de perigo concreto à incolumidade pública, por se tratar de crime material.", "GABARITO: ERRADO. Os delitos do Estatuto do Desarmamento são, em regra, crimes de perigo abstrato, dispensando prova de perigo concreto.", false),
  ce("b10-legesp-01-008", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[2], orgs[0], cargos[0], "dificil", "Após a Lei 13.964/2019, o comércio ilegal e o tráfico internacional de arma de fogo passaram a integrar o rol dos crimes hediondos quando envolverem arma de fogo de uso proibido, restrito ou permitido.", "GABARITO: CERTO. A Lei 13.964/2019 alterou a Lei 8.072/1990 para incluir o comércio ilegal e o tráfico internacional de armas de fogo, acessórios ou munições como hediondos.", true),
  me("b10-legesp-01-009", "legislacao_especial", "estatuto_desarmamento_10826", banksME[1], orgs[3], cargos[5], "medio", "A conduta de disparar arma de fogo em via pública ou em direção a ela, desde que não tenha como finalidade a prática de outro crime, configura:", "GABARITO: B. Art. 15 da Lei 10.826/2003 tipifica o disparo de arma de fogo em lugar habitado, suas adjacências, via pública ou em direção a ela.", [A("Posse irregular de arma de fogo."), A("Disparo de arma de fogo.", true), A("Omissão de cautela."), A("Receptação qualificada."), A("Contravenção de perturbação do sossego.")]),
  ce("b10-legesp-01-010", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[0], orgs[4], cargos[6], "facil", "Deixar de observar as cautelas necessárias para impedir que menor de 18 anos se apodere de arma de fogo sob posse ou propriedade do agente caracteriza crime de omissão de cautela.", "GABARITO: CERTO. Art. 13 da Lei 10.826/2003 tipifica a omissão de cautela.", true),
  ce("b10-legesp-01-011", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[1], orgs[0], cargos[2], "facil", "Considera-se organização criminosa a associação de quatro ou mais pessoas estruturalmente ordenada e caracterizada pela divisão de tarefas, ainda que informalmente, com objetivo de obter vantagem mediante infrações penais com penas máximas superiores a quatro anos ou de caráter transnacional.", "GABARITO: CERTO. Art. 1º, § 1º, da Lei 12.850/2013 define organização criminosa nesses termos.", true),
  ce("b10-legesp-01-012", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[2], orgs[2], cargos[2], "dificil", "A colaboração premiada é meio de obtenção de prova e, por si só, não constitui fundamento único para sentença condenatória.", "GABARITO: CERTO. Art. 3º-A e art. 4º, § 16, da Lei 12.850/2013: colaboração é negócio jurídico processual e meio de obtenção de prova; nenhuma condenação será proferida com fundamento apenas nas declarações do colaborador.", true),
  me("b10-legesp-01-013", "legislacao_especial", "organizacoes_criminosas_12850", banksME[0], orgs[0], cargos[0], "medio", "A ação controlada na Lei 12.850/2013 consiste em:", "GABARITO: A. Art. 8º da Lei 12.850/2013: retardar a intervenção policial/administrativa, mantendo-se a observação e acompanhamento, para que a medida legal se concretize no momento mais eficaz à formação de provas e obtenção de informações.", [A("Retardar a intervenção policial para o momento mais eficaz à formação de provas.", true), A("Provocar o agente a cometer crime impossível."), A("Dispensar autorização judicial para busca domiciliar noturna."), A("Substituir o inquérito policial por relatório privado."), A("Extinguir a punibilidade de todos os investigados.")]),
  ce("b10-legesp-01-014", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[0], orgs[1], cargos[1], "medio", "A infiltração de agentes de polícia em tarefas de investigação depende de representação do delegado de polícia ou requerimento do Ministério Público e de autorização judicial circunstanciada, motivada e sigilosa.", "GABARITO: CERTO. Art. 10 da Lei 12.850/2013 exige autorização judicial circunstanciada, motivada e sigilosa, com limites da atuação.", true),
  ce("b10-legesp-01-015", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[1], orgs[2], cargos[4], "dificil", "O acordo de colaboração premiada pode ter como legitimados para proposta o delegado de polícia, nos autos do inquérito policial, com manifestação do Ministério Público, ou o Ministério Público, a qualquer tempo.", "GABARITO: CERTO. Art. 4º, § 6º, da Lei 12.850/2013, conforme leitura constitucional do STF, admite proposta por delegado no inquérito com manifestação ministerial e por membro do MP.", true),
  ce("b10-legesp-01-016", "legislacao_especial", "lei_drogas_11343", banksCE[2], orgs[5], cargos[5], "medio", "A distinção entre tráfico de drogas e posse para consumo pessoal deve considerar a natureza e quantidade da substância, local e condições da ação, circunstâncias sociais e pessoais, conduta e antecedentes do agente.", "GABARITO: CERTO. Art. 28, § 2º, da Lei 11.343/2006 elenca os critérios objetivos e subjetivos para a distinção.", true),
  ce("b10-legesp-01-017", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[0], orgs[0], cargos[2], "dificil", "A apreensão de arma de fogo desmuniciada não afasta, por si só, a tipicidade dos crimes de posse ou porte ilegal, conforme orientação dominante dos tribunais superiores.", "GABARITO: CERTO. A jurisprudência do STF/STJ trata posse/porte irregular como crime de perigo abstrato, sendo irrelevante, em regra, a arma estar desmuniciada se há potencialidade lesiva.", true),
  me("b10-legesp-01-018", "legislacao_especial", "lei_drogas_11343", banksME[2], orgs[2], cargos[3], "facil", "Na Lei 11.343/2006, a destruição das drogas apreendidas sem prisão em flagrante deve ocorrer por incineração, no prazo máximo de:", "GABARITO: D. Art. 50-A da Lei 11.343/2006 prevê destruição por incineração no prazo máximo de 30 dias, guardando-se amostra necessária à realização do laudo definitivo.", [A("24 horas."), A("48 horas."), A("10 dias."), A("30 dias.", true), A("180 dias.")]),
  ce("b10-legesp-01-019", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[1], orgs[4], cargos[6], "medio", "Promover, constituir, financiar ou integrar, pessoalmente ou por interposta pessoa, organização criminosa constitui delito autônomo previsto na Lei 12.850/2013.", "GABARITO: CERTO. Art. 2º da Lei 12.850/2013 tipifica essas condutas, sem prejuízo das penas correspondentes às demais infrações penais praticadas.", true),
  ce("b10-legesp-01-020", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[2], orgs[1], cargos[1], "medio", "O certificado de registro de arma de fogo autoriza o proprietário a portar a arma em via pública, independentemente de autorização específica de porte.", "GABARITO: ERRADO. Registro autoriza posse nos limites legais; porte em via pública depende de autorização específica, nos termos do Estatuto do Desarmamento.", false),
  me("b10-legesp-01-021", "legislacao_especial", "organizacoes_criminosas_12850", banksME[0], orgs[0], cargos[2], "dificil", "Sobre a infiltração virtual de agentes na Lei 12.850/2013, assinale a opção correta.", "GABARITO: E. A infiltração virtual é admitida pela legislação, exige autorização judicial e deve observar proporcionalidade, necessidade e limites temporais e operacionais fixados na decisão.", [A("É vedada no Brasil por ausência de previsão legal."), A("Pode ser realizada por qualquer servidor público sem controle judicial."), A("Dispensa relatório circunstanciado ao final da operação."), A("Somente é cabível em crimes culposos contra a administração."), A("Exige autorização judicial e delimitação da atuação do agente infiltrado.", true)]),
  ce("b10-legesp-01-022", "legislacao_especial", "lei_drogas_11343", banksCE[0], orgs[2], cargos[4], "facil", "O crime de associação para o tráfico exige associação de duas ou mais pessoas para o fim de praticar, reiteradamente ou não, os crimes previstos nos arts. 33, caput e § 1º, e 34 da Lei de Drogas.", "GABARITO: CERTO. Art. 35 da Lei 11.343/2006 exige associação de duas ou mais pessoas com especial fim de agir voltado aos delitos indicados.", true),
  ce("b10-legesp-01-023", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[1], orgs[3], cargos[5], "medio", "A entrega espontânea de arma de fogo à Polícia Federal, na forma da lei e regulamento, pode ensejar indenização e presunção de boa-fé, conforme campanhas de desarmamento.", "GABARITO: CERTO. O Estatuto do Desarmamento prevê mecanismos de entrega espontânea, indenização e presunção de boa-fé na forma regulamentar.", true),
  ce("b10-legesp-01-024", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[2], orgs[0], cargos[0], "medio", "A captação ambiental de sinais eletromagnéticos, ópticos ou acústicos é meio de obtenção de prova previsto expressamente na Lei 12.850/2013.", "GABARITO: CERTO. Art. 3º, II, da Lei 12.850/2013 arrola a captação ambiental como meio de obtenção de prova.", true),
  me("b10-legesp-01-025", "legislacao_especial", "estatuto_desarmamento_10826", banksME[1], orgs[5], cargos[5], "facil", "O crime de omissão de cautela previsto no Estatuto do Desarmamento ocorre quando o proprietário ou diretor responsável de empresa de segurança deixa de registrar ocorrência policial e comunicar à Polícia Federal perda, furto, roubo ou extravio de arma de fogo no prazo de:", "GABARITO: C. Art. 13, parágrafo único, da Lei 10.826/2003 prevê prazo de 24 horas depois de ocorrido o fato.", [A("6 horas."), A("12 horas."), A("24 horas.", true), A("5 dias."), A("30 dias.")]),
  ce("b10-legesp-01-026", "legislacao_especial", "lei_drogas_11343", banksCE[0], orgs[0], cargos[2], "dificil", "A condenação anterior pelo delito do art. 28 da Lei de Drogas não configura reincidência para afastar, automaticamente, a minorante do tráfico privilegiado.", "GABARITO: CERTO. A jurisprudência do STJ afasta o uso automático da condenação pelo art. 28 para caracterizar reincidência apta a impedir a minorante do art. 33, § 4º.", true),
  ce("b10-legesp-01-027", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[1], orgs[2], cargos[2], "dificil", "O juiz participará das negociações realizadas entre as partes para formalização do acordo de colaboração premiada, a fim de assegurar paridade de armas.", "GABARITO: ERRADO. Art. 4º, § 6º, da Lei 12.850/2013: O juiz não participa das negociações; atua no controle de regularidade, legalidade, voluntariedade e homologação.", false),
  ce("b10-legesp-01-028", "legislacao_especial", "estatuto_desarmamento_10826", banksCE[2], orgs[1], cargos[1], "medio", "A posse ou porte de munição desacompanhada de arma de fogo pode configurar crime do Estatuto do Desarmamento, por expressa previsão legal.", "GABARITO: CERTO. Os tipos penais da Lei 10.826/2003 abrangem arma de fogo, acessório ou munição, conforme o caso.", true),
  me("b10-legesp-01-029", "legislacao_especial", "lei_drogas_11343", banksME[0], orgs[4], cargos[6], "medio", "É efeito da condenação por crime de tráfico de drogas, observado o devido processo legal:", "GABARITO: B. A Lei 11.343/2006 prevê perdimento de bens, direitos e valores relacionados à prática criminosa, ressalvados direitos de terceiros de boa-fé.", [A("Extinção automática da punibilidade do fornecedor eventual."), A("Perdimento de bens, direitos e valores relacionados ao tráfico, ressalvado terceiro de boa-fé.", true), A("Transformação obrigatória da pena em advertência educativa."), A("Indulto judicial obrigatório ao réu primário."), A("Competência exclusiva da justiça militar estadual.")]),
  ce("b10-legesp-01-030", "legislacao_especial", "organizacoes_criminosas_12850", banksCE[0], orgs[0], cargos[0], "facil", "A Lei 12.850/2013 aplica-se também às infrações penais previstas em tratado ou convenção internacional quando, iniciada a execução no País, o resultado tenha ou devesse ter ocorrido no estrangeiro, ou reciprocamente.", "GABARITO: CERTO. Art. 1º, § 2º, II, da Lei 12.850/2013 amplia a incidência para hipóteses transnacionais previstas em tratados/convenções.", true),
]);

// Legislação Especial 02 - Abuso, Maria da Penha, Hediondos, Tortura, Lavagem
addModule("leg_esp_02.mjs", "legEsp02Questoes", [
  ce("b10-legesp-02-001", "legislacao_especial", "abuso_autoridade_13869", banksCE[0], orgs[2], cargos[2], "medio", "Os crimes de abuso de autoridade previstos na Lei 13.869/2019 exigem finalidade específica de prejudicar outrem, beneficiar a si mesmo ou terceiro, ou mero capricho ou satisfação pessoal.", "GABARITO: CERTO. Art. 1º, § 1º, da Lei 13.869/2019 estabelece dolo específico; divergência na interpretação da lei ou avaliação de fatos e provas não configura abuso por si só.", true),
  ce("b10-legesp-02-002", "legislacao_especial", "abuso_autoridade_13869", banksCE[1], orgs[0], cargos[0], "facil", "A divergência na interpretação de lei ou na avaliação de fatos e provas configura abuso de autoridade sempre que a decisão for posteriormente reformada.", "GABARITO: ERRADO. Art. 1º, § 2º, da Lei 13.869/2019 afasta a tipicidade da divergência interpretativa ou probatória, por si só.", false),
  ce("b10-legesp-02-003", "legislacao_especial", "abuso_autoridade_13869", banksCE[2], orgs[1], cargos[1], "medio", "Constranger preso ou detento, mediante violência, grave ameaça ou redução de capacidade de resistência, a exibir-se à curiosidade pública constitui crime de abuso de autoridade.", "GABARITO: CERTO. Art. 13, I, da Lei 13.869/2019 tipifica a conduta, protegendo dignidade e imagem da pessoa presa.", true),
  me("b10-legesp-02-004", "legislacao_especial", "abuso_autoridade_13869", banksME[0], orgs[2], cargos[3], "dificil", "À luz da Lei 13.869/2019, assinale a alternativa correta.", "GABARITO: C. A lei exige elemento subjetivo especial e prevê ação penal pública incondicionada, admitida ação privada subsidiária da pública nos termos constitucionais se houver inércia do MP.", [A("Todos os crimes admitem modalidade culposa."), A("A ação penal é privada exclusiva."), A("Exige-se finalidade específica de agir e a ação penal é pública incondicionada.", true), A("A lei aplica-se apenas a magistrados."), A("A divergência interpretativa é presunção absoluta de abuso.")]),
  ce("b10-legesp-02-005", "legislacao_especial", "abuso_autoridade_13869", banksCE[0], orgs[3], cargos[5], "medio", "Cumprir mandado de busca e apreensão domiciliar após as 21 horas ou antes das 5 horas pode caracterizar abuso de autoridade, ressalvadas hipóteses constitucionais e legais.", "GABARITO: CERTO. Art. 22, § 1º, III, da Lei 13.869/2019 criminaliza cumprimento de mandado de busca domiciliar após 21h ou antes de 5h, sem prejuízo de flagrante/desastre/socorro e consentimento válido.", true),
  ce("b10-legesp-02-006", "legislacao_especial", "lei_maria_da_penha", banksCE[1], orgs[2], cargos[2], "facil", "A Lei Maria da Penha aplica-se a situações de violência doméstica e familiar contra a mulher, independentemente de orientação sexual.", "GABARITO: CERTO. Art. 5º, parágrafo único, da Lei 11.340/2006: as relações pessoais enunciadas independem de orientação sexual.", true),
  ce("b10-legesp-02-007", "legislacao_especial", "lei_maria_da_penha", banksCE[2], orgs[4], cargos[6], "medio", "A retratação da representação da vítima nos crimes de ação penal pública condicionada abrangidos pela Lei Maria da Penha somente será admitida perante o juiz, em audiência especialmente designada, antes do recebimento da denúncia e ouvido o Ministério Público.", "GABARITO: CERTO. Art. 16 da Lei 11.340/2006 estabelece a forma qualificada da renúncia/retratação.", true),
  ce("b10-legesp-02-008", "legislacao_especial", "lei_maria_da_penha", banksCE[0], orgs[5], cargos[5], "medio", "Nos crimes praticados com violência doméstica e familiar contra a mulher, é vedada a aplicação de penas de cesta básica ou outras de prestação pecuniária, bem como a substituição de pena que implique pagamento isolado de multa.", "GABARITO: CERTO. Art. 17 da Lei 11.340/2006 veda tais sanções substitutivas despenalizadoras inadequadas ao contexto de violência de gênero.", true),
  me("b10-legesp-02-009", "legislacao_especial", "lei_maria_da_penha", banksME[1], orgs[2], cargos[4], "facil", "Entre as formas de violência doméstica e familiar contra a mulher previstas expressamente na Lei Maria da Penha, incluem-se:", "GABARITO: E. Art. 7º da Lei 11.340/2006 prevê violência física, psicológica, sexual, patrimonial e moral.", [A("Apenas física e patrimonial."), A("Apenas física, quando houver lesão grave."), A("Somente moral e eleitoral."), A("Somente sexual mediante conjunção carnal."), A("Física, psicológica, sexual, patrimonial e moral.", true)]),
  ce("b10-legesp-02-010", "legislacao_especial", "lei_maria_da_penha", banksCE[1], orgs[3], cargos[5], "dificil", "O descumprimento de decisão judicial que defere medidas protetivas de urgência constitui crime autônomo, independentemente da competência civil ou criminal do juiz que deferiu as medidas.", "GABARITO: CERTO. Art. 24-A da Lei 11.340/2006 tipifica o descumprimento de medidas protetivas de urgência.", true),
  ce("b10-legesp-02-011", "legislacao_especial", "crimes_hediondos_8072", banksCE[2], orgs[0], cargos[0], "medio", "A prática da tortura, o tráfico ilícito de entorpecentes e drogas afins e o terrorismo são equiparados a crimes hediondos para fins constitucionais e legais.", "GABARITO: CERTO. Art. 5º, XLIII, da CF e Lei 8.072/1990 equiparam tais delitos aos hediondos quanto ao tratamento mais rigoroso.", true),
  ce("b10-legesp-02-012", "legislacao_especial", "crimes_hediondos_8072", banksCE[0], orgs[1], cargos[1], "dificil", "A progressão de regime para condenados por crimes hediondos ou equiparados obedece aos percentuais da Lei de Execução Penal, com distinções conforme primariedade, resultado morte, reincidência e comando de organização criminosa.", "GABARITO: CERTO. Após a Lei 13.964/2019, a progressão de regime é disciplinada no art. 112 da LEP, com percentuais escalonados e critérios distintos.", true),
  me("b10-legesp-02-013", "legislacao_especial", "crimes_hediondos_8072", banksME[2], orgs[2], cargos[2], "medio", "Nos termos da Lei 8.072/1990, é crime hediondo:", "GABARITO: A. O homicídio qualificado é expressamente previsto no rol de crimes hediondos. O rol é taxativo.", [A("Homicídio qualificado.", true), A("Furto simples noturno."), A("Ameaça simples."), A("Dano culposo."), A("Desobediência.")]),
  ce("b10-legesp-02-014", "legislacao_especial", "crimes_hediondos_8072", banksCE[1], orgs[4], cargos[6], "medio", "A Lei dos Crimes Hediondos veda anistia, graça e indulto aos crimes hediondos e equiparados, além de estabelecer regras próprias de fiança e regime inicial conforme legislação vigente.", "GABARITO: CERTO. Art. 2º da Lei 8.072/1990 prevê inafiançabilidade e insuscetibilidade de anistia, graça e indulto.", true),
  ce("b10-legesp-02-015", "legislacao_especial", "crimes_tortura", banksCE[2], orgs[0], cargos[2], "facil", "Constranger alguém com emprego de violência ou grave ameaça, causando-lhe sofrimento físico ou mental para obter informação, declaração ou confissão caracteriza crime de tortura.", "GABARITO: CERTO. Art. 1º, I, 'a', da Lei 9.455/1997 tipifica a tortura-prova.", true),
  ce("b10-legesp-02-016", "legislacao_especial", "crimes_tortura", banksCE[0], orgs[3], cargos[5], "medio", "O crime de tortura admite modalidade omissiva própria para quem tinha o dever de evitar ou apurar a conduta e se omite.", "GABARITO: CERTO. Art. 1º, § 2º, da Lei 9.455/1997 pune aquele que se omite diante dessas condutas quando tinha o dever de evitá-las ou apurá-las.", true),
  me("b10-legesp-02-017", "legislacao_especial", "crimes_tortura", banksME[0], orgs[1], cargos[1], "dificil", "No crime de tortura praticado por agente público, a condenação acarretará:", "GABARITO: D. Art. 1º, § 5º, da Lei 9.455/1997: a condenação acarretará perda do cargo, função ou emprego público e interdição para seu exercício pelo dobro do prazo da pena aplicada.", [A("Apenas advertência administrativa."), A("Suspensão por trinta dias, sem efeitos penais."), A("Anistia automática se houver ordem superior."), A("Perda do cargo e interdição para exercício pelo dobro do prazo da pena.", true), A("Conversão obrigatória em multa civil.")]),
  ce("b10-legesp-02-018", "legislacao_especial", "crimes_tortura", banksCE[1], orgs[2], cargos[3], "medio", "A Lei de Tortura aplica-se ainda quando o crime não tenha sido cometido em território nacional, desde que a vítima seja brasileira ou o agente se encontre em local sob jurisdição brasileira.", "GABARITO: CERTO. Art. 2º da Lei 9.455/1997 prevê hipótese de extraterritorialidade.", true),
  ce("b10-legesp-02-019", "legislacao_especial", "lavagem_dinheiro_9613", banksCE[2], orgs[0], cargos[0], "facil", "A lavagem de dinheiro consiste em ocultar ou dissimular a natureza, origem, localização, disposição, movimentação ou propriedade de bens, direitos ou valores provenientes, direta ou indiretamente, de infração penal.", "GABARITO: CERTO. Art. 1º da Lei 9.613/1998, após alteração da Lei 12.683/2012, usa a expressão 'infração penal', abrangendo crimes e contravenções.", true),
  ce("b10-legesp-02-020", "legislacao_especial", "lavagem_dinheiro_9613", banksCE[0], orgs[2], cargos[2], "dificil", "Desde a Lei 12.683/2012, a Lei de Lavagem de Dinheiro deixou de exigir rol taxativo de crimes antecedentes, bastando que os valores sejam provenientes de infração penal.", "GABARITO: CERTO. A reforma de 2012 aboliu o rol de crimes antecedentes, adotando modelo aberto vinculado a qualquer infração penal.", true),
  me("b10-legesp-02-021", "legislacao_especial", "lavagem_dinheiro_9613", banksME[1], orgs[0], cargos[0], "medio", "A fase da lavagem de dinheiro associada à introdução de valores ilícitos no sistema econômico, por depósitos fracionados ou compra de bens, é chamada de:", "GABARITO: A. Colocação (placement) é a inserção inicial do dinheiro ilícito no sistema econômico. Dissimulação/ocultação corresponde ao layering; integração, ao retorno com aparência lícita.", [A("Colocação.", true), A("Integração."), A("Consunção."), A("Exaurimento."), A("Abolitio criminis.")]),
  ce("b10-legesp-02-022", "legislacao_especial", "lavagem_dinheiro_9613", banksCE[1], orgs[1], cargos[1], "dificil", "A autonomia do processo e julgamento da lavagem de dinheiro permite sua apuração ainda que desconhecido ou isento de pena o autor da infração antecedente, desde que haja prova da origem ilícita dos bens.", "GABARITO: CERTO. Art. 2º, II, da Lei 9.613/1998 prevê autonomia em relação à infração antecedente.", true),
  ce("b10-legesp-02-023", "legislacao_especial", "abuso_autoridade_13869", banksCE[2], orgs[5], cargos[5], "medio", "Submeter preso a interrogatório policial durante o período de repouso noturno, salvo captura em flagrante ou consentimento assistido, pode configurar abuso de autoridade.", "GABARITO: CERTO. Art. 18 da Lei 13.869/2019 protege o preso contra interrogatório em horário de repouso noturno, ressalvadas hipóteses legais.", true),
  ce("b10-legesp-02-024", "legislacao_especial", "lei_maria_da_penha", banksCE[0], orgs[2], cargos[4], "facil", "A autoridade policial deve remeter, no prazo legal, expediente apartado ao juiz com pedido da ofendida para concessão de medidas protetivas de urgência.", "GABARITO: CERTO. Lei 11.340/2006 prevê atuação célere da autoridade policial para encaminhamento do pedido de medidas protetivas.", true),
  me("b10-legesp-02-025", "legislacao_especial", "abuso_autoridade_13869", banksME[0], orgs[0], cargos[2], "medio", "Constitui efeito da condenação por crime de abuso de autoridade, quando motivadamente declarado na sentença e não automático:", "GABARITO: B. Art. 4º da Lei 13.869/2019 prevê como efeitos, entre outros, inabilitação para cargo público por 1 a 5 anos e perda do cargo, mandato ou função pública, condicionados à reincidência específica para perda.", [A("Cassação automática de aposentadoria em qualquer hipótese."), A("Inabilitação para exercício de cargo, mandato ou função pública pelo período de 1 a 5 anos.", true), A("Banimento nacional do agente público."), A("Perda automática de nacionalidade."), A("Extinção da punibilidade do particular coautor.")]),
  ce("b10-legesp-02-026", "legislacao_especial", "crimes_hediondos_8072", banksCE[1], orgs[3], cargos[5], "medio", "O feminicídio é modalidade qualificada de homicídio incluída no rol de crimes hediondos.", "GABARITO: CERTO. Art. 121, § 2º, VI, do CP e art. 1º, I, da Lei 8.072/1990.", true),
  ce("b10-legesp-02-027", "legislacao_especial", "lavagem_dinheiro_9613", banksCE[2], orgs[0], cargos[0], "medio", "Na lavagem de dinheiro, a pena será aumentada se o crime for cometido de forma reiterada ou por intermédio de organização criminosa.", "GABARITO: CERTO. Art. 1º, § 4º, da Lei 9.613/1998 prevê aumento de pena nessas hipóteses.", true),
  ce("b10-legesp-02-028", "legislacao_especial", "crimes_tortura", banksCE[0], orgs[4], cargos[6], "medio", "A tortura-castigo consiste em submeter alguém, sob guarda, poder ou autoridade, com emprego de violência ou grave ameaça, a intenso sofrimento físico ou mental como forma de aplicar castigo pessoal ou medida de caráter preventivo.", "GABARITO: CERTO. Art. 1º, II, da Lei 9.455/1997.", true),
  me("b10-legesp-02-029", "legislacao_especial", "lei_maria_da_penha", banksME[2], orgs[2], cargos[3], "dificil", "Conforme entendimento sumulado do STJ sobre violência doméstica contra a mulher, é correto afirmar que:", "GABARITO: C. Súmula 536/STJ: A suspensão condicional do processo e a transação penal não se aplicam na hipótese de delitos sujeitos ao rito da Lei Maria da Penha.", [A("Aplica-se obrigatoriamente transação penal a todos os delitos."), A("A lesão corporal leve depende sempre de representação retratável em cartório."), A("Não se aplicam transação penal e suspensão condicional do processo aos delitos sujeitos à Lei Maria da Penha.", true), A("A competência é sempre da Justiça Federal."), A("A lei só protege mulheres casadas civilmente.")]),
  ce("b10-legesp-02-030", "legislacao_especial", "abuso_autoridade_13869", banksCE[1], orgs[1], cargos[1], "facil", "A Lei de Abuso de Autoridade pode ser aplicada a servidores públicos e a agentes públicos por equiparação, inclusive aqueles que exerçam função pública transitoriamente ou sem remuneração.", "GABARITO: CERTO. Art. 2º da Lei 13.869/2019 adota conceito amplo de agente público, abrangendo mandato, cargo, emprego ou função, ainda que transitoriamente ou sem remuneração.", true),
]);

// compact generator helpers for remaining conceptual modules
function addCE(base, n, disc, assuntoList, titleList, exportName, fileName) {
  const qs = [];
  for (let i = 1; i <= n; i++) {
    const spec = titleList[(i - 1) % titleList.length];
    const assunto = assuntoList[(i - 1) % assuntoList.length];
    const correta = spec.correta ?? (i % 5 !== 0);
    const slug = `${base}-${String(i).padStart(3, "0")}`;
    const isME = i % 3 === 0;
    if (isME) {
      qs.push(me(slug, disc, assunto, banksME[i % 3], orgs[i % orgs.length], cargos[i % cargos.length], difs[i % 3], spec.pergunta, `GABARITO: ${spec.gab}. ${spec.exp}`, spec.alts));
    } else {
      qs.push(ce(slug, disc, assunto, banksCE[i % 3], orgs[i % orgs.length], cargos[i % cargos.length], difs[i % 3], correta ? spec.certo : spec.errado, `GABARITO: ${correta ? "CERTO" : "ERRADO"}. ${spec.exp}`, correta));
    }
  }
  addModule(fileName, exportName, qs);
}

const constSpecs = [
  { certo: "A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para preservação da ordem pública e da incolumidade das pessoas e do patrimônio.", errado: "A segurança pública é atividade exclusiva das Forças Armadas, sendo vedada a participação dos órgãos policiais civis estaduais.", exp: "Art. 144, caput, da Constituição Federal define segurança pública como dever do Estado, direito e responsabilidade de todos.", pergunta: "Nos termos do art. 144 da Constituição, a Polícia Federal destina-se, entre outras funções, a:", gab: "B", alts: [A("Exercer polícia ostensiva e preservação da ordem pública nos municípios."), A("Apurar infrações penais contra a ordem política e social ou em detrimento de bens, serviços e interesses da União.", true), A("Julgar crimes militares estaduais."), A("Executar penas privativas de liberdade federais."), A("Exercer defesa civil estadual.")] },
  { certo: "A casa é asilo inviolável do indivíduo, ninguém nela podendo penetrar sem consentimento do morador, salvo flagrante delito, desastre, prestação de socorro ou, durante o dia, por determinação judicial.", errado: "A entrada domiciliar por determinação judicial pode ocorrer livremente durante a noite, ainda que não haja flagrante, desastre ou socorro.", exp: "Art. 5º, XI, da CF. Mandado judicial de busca domiciliar deve ser cumprido durante o dia, salvo consentimento válido ou exceções constitucionais.", pergunta: "A inviolabilidade domiciliar admite ingresso sem consentimento do morador, durante o dia, por:", gab: "C", alts: [A("Ordem verbal de particular."), A("Denúncia anônima isolada, sempre."), A("Determinação judicial.", true), A("Convenção coletiva de bairro."), A("Autorização de síndico, em qualquer casa.")] },
  { certo: "O preso será informado de seus direitos, entre os quais o de permanecer calado, sendo-lhe assegurada assistência da família e de advogado.", errado: "O direito ao silêncio somente existe após o recebimento da denúncia e não se aplica ao interrogatório policial.", exp: "Art. 5º, LXIII, da CF assegura direito ao silêncio desde a prisão e durante a persecução penal.", pergunta: "Entre os direitos constitucionais do preso está:", gab: "A", alts: [A("Ser informado de seus direitos, inclusive o de permanecer calado.", true), A("Ser exibido à imprensa como regra de transparência."), A("Ser incomunicável por prazo indeterminado."), A("Ser privado de defensor até a audiência."), A("Ter prisão automática convertida em pena.")] },
  { certo: "Às polícias civis incumbem, ressalvada a competência da União, as funções de polícia judiciária e apuração de infrações penais, exceto as militares.", errado: "Às polícias civis compete o policiamento ostensivo preventivo e a preservação exclusiva da ordem pública.", exp: "Art. 144, § 4º, da CF; policiamento ostensivo é atribuição da polícia militar.", pergunta: "Compete às polícias militares, nos termos constitucionais:", gab: "D", alts: [A("Exercer polícia judiciária da União."), A("Emitir passaportes."), A("Apurar infrações penais federais."), A("Polícia ostensiva e preservação da ordem pública.", true), A("Julgar contravenções penais.")] },
  { certo: "O princípio da presunção de inocência impede a execução provisória da pena antes do trânsito em julgado da condenação criminal, ressalvadas prisões cautelares devidamente fundamentadas.", errado: "A prisão cautelar dispensa fundamentação concreta sempre que houver clamor público.", exp: "Art. 5º, LVII, da CF e jurisprudência do STF; cautelares exigem requisitos legais e fundamentação concreta.", pergunta: "A presunção de inocência significa que ninguém será considerado culpado até:", gab: "E", alts: [A("Lavratura do boletim."), A("Indiciamento formal."), A("Recebimento da denúncia."), A("Sentença de primeiro grau."), A("Trânsito em julgado de sentença penal condenatória.", true)] },
];
addCE("b10-const-01", 23, "constitucional", ["seguranca_publica", "artigo_5_cf", "organizacao_estado", "poder_executivo", "poder_judiciario"], constSpecs, "const01Questoes", "const_01.mjs");
addCE("b10-const-02", 22, "constitucional", ["seguranca_publica", "artigo_5_cf", "controle_constitucionalidade", "poder_legislativo", "organizacao_estado"], constSpecs, "const02Questoes", "const_02.mjs");

const admSpecs = [
  { certo: "O poder de polícia administrativa compreende a atividade estatal que condiciona ou restringe o uso e gozo de bens, atividades e direitos individuais em benefício do interesse público.", errado: "O poder de polícia é sempre delegado integralmente a particulares, inclusive quanto à aplicação de sanções coercitivas.", exp: "O poder de polícia decorre da supremacia do interesse público; seus ciclos têm limites de delegabilidade conforme jurisprudência.", pergunta: "São atributos clássicos do poder de polícia:", gab: "A", alts: [A("Discricionariedade, autoexecutoriedade e coercibilidade.", true), A("Vitaliciedade, irredutibilidade e inamovibilidade."), A("Tipicidade penal, culpabilidade e punibilidade."), A("Generalidade tributária e anterioridade."), A("Oralidade e plenitude de defesa.")] },
  { certo: "Atos administrativos gozam de presunção relativa de legitimidade e veracidade, admitindo prova em contrário pelo administrado.", errado: "A presunção de legitimidade dos atos administrativos é absoluta e impede controle judicial.", exp: "A presunção é juris tantum e não afasta controle judicial ou administrativo.", pergunta: "A presunção de legitimidade do ato administrativo é:", gab: "C", alts: [A("Inexistente."), A("Absoluta."), A("Relativa, admitindo prova em contrário.", true), A("Exclusiva de atos legislativos."), A("Aplicável apenas a contratos privados.")] },
  { certo: "A responsabilidade civil objetiva do Estado, em regra, exige conduta administrativa, dano e nexo causal, admitidas excludentes como culpa exclusiva da vítima e caso fortuito externo.", errado: "A responsabilidade civil do Estado é sempre subjetiva e depende necessariamente de dolo do agente público.", exp: "Art. 37, § 6º, da CF adota responsabilidade objetiva para pessoas jurídicas prestadoras de serviço público, com direito de regresso contra agente culpado.", pergunta: "A responsabilidade civil objetiva do Estado fundamenta-se, em regra, na teoria:", gab: "B", alts: [A("Da culpa anônima exclusivamente."), A("Do risco administrativo.", true), A("Da irresponsabilidade estatal."), A("Da vontade bilateral."), A("Da tipicidade fechada penal.")] },
  { certo: "A Lei 14.133/2021 prevê modalidades como pregão, concorrência, concurso, leilão e diálogo competitivo, extinguindo tomada de preços e convite.", errado: "A Lei 14.133/2021 manteve convite e tomada de preços como modalidades ordinárias permanentes.", exp: "A nova Lei de Licitações reorganizou modalidades e introduziu diálogo competitivo.", pergunta: "Modalidade inovadora da Lei 14.133/2021 voltada a contratações complexas é:", gab: "D", alts: [A("Convite."), A("Tomada de preços."), A("Convênio."), A("Diálogo competitivo.", true), A("Concurso de prognósticos.")] },
  { certo: "A improbidade administrativa, após a Lei 14.230/2021, exige dolo para configuração dos atos tipificados na Lei 8.429/1992.", errado: "A improbidade administrativa continua admitindo modalidade culposa ampla para enriquecimento ilícito e violação de princípios.", exp: "A reforma de 2021 reforçou a exigência de dolo e afastou improbidade culposa como regra.", pergunta: "Após a Lei 14.230/2021, a improbidade administrativa exige, como regra:", gab: "E", alts: [A("Culpa levíssima."), A("Responsabilidade objetiva."), A("Erro administrativo simples."), A("Divergência interpretativa isolada."), A("Dolo.", true)] },
];
addCE("b10-adm-01", 23, "administrativo", ["poder_policia", "atos_administrativos", "responsabilidade_civil_estado", "agentes_publicos_8112", "licitacoes_14133"], admSpecs, "adm01Questoes", "adm_01.mjs");
addCE("b10-adm-02", 22, "administrativo", ["improbidade_administrativa", "principios_administracao", "poder_policia", "atos_administrativos", "licitacoes_14133"], admSpecs, "adm02Questoes", "adm_02.mjs");

const transSpecs = [
  { certo: "O trânsito em condições seguras é direito de todos e dever dos órgãos e entidades componentes do Sistema Nacional de Trânsito.", errado: "A segurança no trânsito é responsabilidade exclusiva dos condutores profissionais, sem dever estatal correlato.", exp: "Art. 1º, § 2º, do CTB consagra o trânsito seguro como direito de todos e dever dos órgãos do SNT.", pergunta: "Segundo o CTB, trânsito é a utilização das vias por pessoas, veículos e animais para fins de:", gab: "B", alts: [A("Somente circulação."), A("Circulação, parada, estacionamento e operação de carga ou descarga.", true), A("Apenas competição esportiva."), A("Exclusivamente transporte remunerado."), A("Somente fiscalização policial.")] },
  { certo: "Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência constitui infração gravíssima, com penalidades administrativas específicas.", errado: "A recusa ao teste do etilômetro impede qualquer consequência administrativa ao condutor.", exp: "Arts. 165 e 165-A do CTB preveem infrações gravíssimas e penalidades para condução sob influência e recusa ao teste.", pergunta: "A recusa ao teste do etilômetro configura, em regra:", gab: "C", alts: [A("Conduta atípica administrativa."), A("Infração leve."), A("Infração gravíssima com penalidades do art. 165-A do CTB.", true), A("Crime hediondo."), A("Apenas advertência verbal.")] },
  { certo: "O crime de embriaguez ao volante pode ser comprovado por teste de alcoolemia, exame clínico, perícia, vídeo, prova testemunhal ou outros meios admitidos em direito.", errado: "A materialidade da embriaguez ao volante só pode ser provada por bafômetro, sendo nula qualquer outra prova.", exp: "Art. 306 do CTB e legislação correlata admitem diversos meios de prova.", pergunta: "O crime do art. 306 do CTB exige:", gab: "A", alts: [A("Condução de veículo automotor com capacidade psicomotora alterada por álcool ou substância psicoativa.", true), A("Resultado morte obrigatório."), A("Dano patrimonial superior a salário mínimo."), A("Perseguição policial prévia."), A("Veículo de transporte coletivo apenas.")] },
  { certo: "A ultrapassagem deve ocorrer, em regra, pela esquerda, obedecida a sinalização regulamentar e as demais normas de circulação.", errado: "A ultrapassagem pela direita é sempre obrigatória em vias urbanas, ainda que haja sinalização proibitiva.", exp: "CTB disciplina ultrapassagem, preferência e circulação com segurança.", pergunta: "Em regra, antes de efetuar ultrapassagem, o condutor deve:", gab: "D", alts: [A("Acelerar sem sinalizar."), A("Usar acostamento."), A("Buzinar continuamente por 30 segundos."), A("Certificar-se de que pode fazê-la sem perigo e sinalizar a manobra.", true), A("Desligar faróis.")] },
  { certo: "A cassação da CNH é penalidade mais grave que a suspensão, aplicável em hipóteses legais específicas, como conduzir veículo com direito de dirigir suspenso.", errado: "A cassação da CNH e a suspensão do direito de dirigir são medidas idênticas e sempre aplicadas automaticamente por agente policial.", exp: "CTB distingue suspensão e cassação, com devido processo administrativo.", pergunta: "A penalidade de cassação da CNH depende de:", gab: "E", alts: [A("Mera notícia anônima."), A("Ato privado de seguradora."), A("Decisão do passageiro."), A("Sentença estrangeira sem homologação."), A("Processo administrativo e hipótese legal.", true)] },
];
addCE("b10-trans-01", 25, "transito", ["ctb_normas_circulacao", "ctb_crimes_infracoes"], transSpecs, "transito01Questoes", "transito_01.mjs");
addCE("b10-trans-02", 25, "transito", ["ctb_normas_circulacao", "ctb_crimes_infracoes"], transSpecs, "transito02Questoes", "transito_02.mjs");

const portSpecs = [
  { certo: "A coesão textual envolve mecanismos linguísticos de articulação, como pronomes, conectores, elipses e repetição controlada de termos.", errado: "Coesão textual é sinônimo de opinião do autor e independe de marcas linguísticas na superfície do texto.", exp: "Coesão é a ligação formal entre partes do texto; coerência diz respeito à construção de sentido.", pergunta: "No período 'O suspeito foi localizado; ele portava documento falso', o pronome 'ele' exerce função de:", gab: "A", alts: [A("Retomada anafórica.", true), A("Catacrese."), A("Vocativo."), A("Predicativo do objeto."), A("Interjeição.")] },
  { certo: "A crase resulta, em regra, da fusão da preposição 'a' com o artigo feminino 'a' ou com o 'a' inicial de pronomes demonstrativos.", errado: "Sempre ocorre crase antes de palavra masculina no singular, por exigência de regência verbal.", exp: "Crase depende de preposição e termo feminino determinado ou demonstrativo compatível.", pergunta: "Assinale a alternativa em que o uso da crase está correto.", gab: "C", alts: [A("Chegou à pé."), A("Entregou o relatório à ele."), A("Referiu-se à autoridade policial.", true), A("Saiu à cavalo."), A("Obedeceu à regulamento interno.")] },
  { certo: "A vírgula não deve separar, em regra, o sujeito de seu predicado, ainda que o sujeito seja extenso.", errado: "A vírgula é obrigatória entre sujeito e verbo sempre que o sujeito tiver mais de três palavras.", exp: "A separação sujeito-predicado por vírgula é, em regra, inadequada.", pergunta: "A pontuação está correta em:", gab: "D", alts: [A("Os agentes, prenderam o foragido."), A("A equipe de plantão, registrou a ocorrência."), A("O delegado, instaurou inquérito."), A("Após a diligência, a equipe retornou à base.", true), A("As provas, foram lacradas.")] },
  { certo: "A concordância verbal deve observar, em regra, o núcleo do sujeito, ressalvadas hipóteses especiais previstas pela norma-padrão.", errado: "Na norma-padrão, o verbo sempre concorda com o termo mais próximo, ainda que este não seja núcleo do sujeito.", exp: "A concordância verbal relaciona verbo e sujeito/núcleo, com regras específicas.", pergunta: "Assinale a frase com concordância verbal adequada.", gab: "B", alts: [A("Houveram muitas ocorrências."), A("Faz dois anos que o inquérito foi instaurado.", true), A("Existe indícios suficientes."), A("Foi apreendido duas armas."), A("Aconteceu várias diligências.")] },
  { certo: "Textos injuntivos têm finalidade de orientar o leitor a executar ações, como manuais, instruções e normas operacionais.", errado: "O texto injuntivo caracteriza-se exclusivamente pela narração de fatos imaginários em sequência temporal.", exp: "Tipologia injuntiva/instrucional orienta comportamentos por comandos, procedimentos ou recomendações.", pergunta: "Um manual de abordagem policial, ao apresentar etapas e comandos, aproxima-se predominantemente da tipologia:", gab: "E", alts: [A("Lírica."), A("Narrativa ficcional."), A("Epistolar afetiva."), A("Dramática."), A("Injuntiva.", true)] },
];
addCE("b10-port-01", 25, "portugues", ["interpretacao_texto", "sintaxe_periodo", "regencia_crase", "pontuacao", "concordancia"], portSpecs, "portugues01Questoes", "portugues_01.mjs");
addCE("b10-port-02", 25, "portugues", ["coesao_coerencia", "morfologia_classes", "ortografia_acentuacao", "tipologia_generos_textuais", "regencia_crase"], portSpecs, "portugues02Questoes", "portugues_02.mjs");

const dhSpecs = [
  { certo: "A Declaração Universal dos Direitos Humanos afirma que todos os seres humanos nascem livres e iguais em dignidade e direitos.", errado: "A DUDH condiciona dignidade humana à nacionalidade do indivíduo e ao reconhecimento estatal prévio.", exp: "Art. 1º da DUDH consagra liberdade, igualdade em dignidade e direitos.", pergunta: "A DUDH foi proclamada pela Assembleia Geral da ONU em:", gab: "A", alts: [A("1948.", true), A("1789."), A("1969."), A("1988."), A("2001.")] },
  { certo: "A Convenção Americana sobre Direitos Humanos assegura garantias judiciais, proteção judicial e direitos à vida, integridade pessoal e liberdade pessoal.", errado: "A CADH autoriza tortura em interrogatório quando houver investigação de crime grave.", exp: "Pacto de San José protege garantias básicas e veda tortura e tratamentos cruéis.", pergunta: "A Convenção Americana sobre Direitos Humanos é também conhecida como:", gab: "B", alts: [A("Carta de Bogotá."), A("Pacto de San José da Costa Rica.", true), A("Estatuto de Roma."), A("Protocolo de Kyoto."), A("Convenção de Palermo.")] },
  { certo: "O uso da força por agentes de segurança deve observar legalidade, necessidade, proporcionalidade, moderação e prestação de contas.", errado: "A força letal é sempre primeira opção operacional em qualquer abordagem policial.", exp: "Princípios internacionais e Portaria Interministerial 4.226/2010 orientam uso progressivo/diferenciado da força.", pergunta: "No uso policial da força, o princípio da necessidade significa:", gab: "C", alts: [A("Empregar sempre arma de fogo."), A("Dispensar verbalização."), A("Usar a força apenas quando outros meios forem ineficazes ou inadequados.", true), A("Punir administrativamente sem processo."), A("Ignorar gradação de risco.")] },
  { certo: "As Regras de Mandela estabelecem parâmetros mínimos das Nações Unidas para tratamento de pessoas presas, preservando dignidade e vedando tortura.", errado: "As Regras de Mandela recomendam isolamento prolongado como técnica ordinária de gestão penitenciária.", exp: "As regras limitam isolamento, vedam tortura e reforçam saúde, dignidade e registros adequados.", pergunta: "As Regras de Bangkok tratam, com foco específico, de:", gab: "D", alts: [A("Direito marítimo."), A("Contratos internacionais."), A("Trânsito urbano."), A("Mulheres presas e medidas não privativas de liberdade para mulheres infratoras.", true), A("Licitações públicas.")] },
  { certo: "Direitos humanos são marcados por universalidade, indivisibilidade, interdependência e historicidade, não se restringindo a nacionais de determinado Estado.", errado: "Direitos humanos são renunciáveis em bloco e podem ser retirados integralmente por ato administrativo discricionário.", exp: "A teoria geral dos direitos humanos aponta universalidade, indivisibilidade e interdependência como características centrais.", pergunta: "A característica segundo a qual os direitos humanos se destinam a todas as pessoas é denominada:", gab: "E", alts: [A("Onerosidade."), A("Regionalidade absoluta."), A("Comutatividade."), A("Sigilosidade."), A("Universalidade.", true)] },
];
addCE("b10-dh-01", 35, "direitos_humanos", ["dudh_1948", "pacto_san_jose", "uso_forca_policial", "regras_mandela", "teoria_geral_dh"], dhSpecs, "dh01Questoes", "dh_01.mjs");

const crimSpecs = [
  { certo: "A Escola Clássica do Direito Penal enfatiza livre-arbítrio, legalidade, proporcionalidade da pena e responsabilidade moral do agente.", errado: "A Escola Clássica fundamenta o crime exclusivamente em fatores biológicos hereditários, negando o livre-arbítrio.", exp: "A Escola Clássica opõe-se ao determinismo positivista e valoriza legalidade e proporcionalidade.", pergunta: "Autor associado à Escola Clássica e à obra 'Dos Delitos e das Penas':", gab: "A", alts: [A("Cesare Beccaria.", true), A("Cesare Lombroso."), A("Enrico Ferri."), A("Raffaele Garofalo."), A("Robert Merton.")] },
  { certo: "A Escola Positiva buscou explicar o delito por fatores biológicos, psicológicos e sociais, com método empírico e determinista.", errado: "A Escola Positiva rejeitou completamente a observação empírica e limitou-se à dogmática abstrata.", exp: "Lombroso, Ferri e Garofalo são referências do positivismo criminológico.", pergunta: "A teoria da anomia associa criminalidade à tensão entre metas culturais e meios institucionalizados, sendo ligada a:", gab: "B", alts: [A("Beccaria."), A("Robert K. Merton.", true), A("Hans Kelsen."), A("Montesquieu."), A("Rousseau.")] },
  { certo: "A vitimologia estuda a vítima, sua relação com o infrator, processos de vitimização e respostas institucionais.", errado: "A vitimologia exclui a análise da vítima e trata apenas da dosimetria da pena.", exp: "Vitimologia inclui vitimização primária, secundária e terciária.", pergunta: "A vitimização secundária ocorre quando:", gab: "C", alts: [A("O crime é apenas tentado."), A("A vítima nunca procura o Estado."), A("Instituições ou agentes do sistema de justiça agravam o sofrimento da vítima.", true), A("O agressor repara integralmente o dano."), A("Há absolvição por ausência de provas.")] },
  { certo: "A cifra negra da criminalidade corresponde à parcela de delitos que não chega ao conhecimento oficial do sistema penal.", errado: "Cifra negra é o conjunto de crimes julgados com sentença transitada em julgado.", exp: "Cifras criminais tratam da diferença entre criminalidade real, registrada e processada.", pergunta: "A subnotificação de crimes impacta diretamente:", gab: "D", alts: [A("A ortografia oficial."), A("A competência legislativa concorrente."), A("A natureza do dolo eventual."), A("A confiabilidade das estatísticas criminais oficiais.", true), A("A forma do contrato administrativo.")] },
  { certo: "A prevenção primária atua sobre fatores sociais amplos antes da ocorrência do crime; a secundária focaliza grupos/locais de risco; a terciária busca evitar reincidência.", errado: "Prevenção terciária é exclusivamente a compra de equipamentos urbanos antes de qualquer delito.", exp: "A classificação primária/secundária/terciária é recorrente em criminologia aplicada.", pergunta: "Programas de ressocialização para egressos do sistema prisional relacionam-se principalmente à prevenção:", gab: "E", alts: [A("Primária absoluta."), A("Administrativa contábil."), A("Linguística."), A("Eleitoral."), A("Terciária.", true)] },
];
addCE("b10-crim-01", 30, "criminologia", ["escolas_criminologicas", "prevencao_criminal", "vitimologia_cifras"], crimSpecs, "criminologia01Questoes", "criminologia_01.mjs");

const infoSpecs = [
  { certo: "Malware é categoria ampla de software malicioso, incluindo vírus, worms, trojans, ransomware, spyware e outros códigos nocivos.", errado: "Ransomware é ferramenta legítima de backup que aumenta disponibilidade sem afetar dados.", exp: "Ransomware criptografa ou bloqueia acesso a dados, geralmente exigindo resgate.", pergunta: "Ataque que tenta obter credenciais por mensagens fraudulentas que simulam fonte confiável é:", gab: "A", alts: [A("Phishing.", true), A("Defrag."), A("RAID."), A("Cache hit."), A("OCR.")] },
  { certo: "O protocolo HTTPS utiliza TLS para prover confidencialidade e integridade na comunicação HTTP.", errado: "HTTPS é idêntico ao HTTP puro e não utiliza criptografia em nenhuma hipótese.", exp: "HTTPS é HTTP sobre TLS, com proteção criptográfica e autenticação do servidor por certificados.", pergunta: "O protocolo DNS é usado principalmente para:", gab: "B", alts: [A("Criptografar disco local."), A("Resolver nomes de domínio em endereços IP.", true), A("Editar planilhas."), A("Compactar imagens."), A("Gerenciar processos do kernel.")] },
  { certo: "Em SQL, a cláusula WHERE filtra linhas antes da agregação final, enquanto HAVING filtra grupos após agregações.", errado: "A cláusula SELECT é usada exclusivamente para apagar registros permanentes do banco.", exp: "SELECT consulta dados; DELETE remove registros; WHERE e HAVING têm usos distintos.", pergunta: "Comando SQL usado para consultar dados em tabelas:", gab: "C", alts: [A("DROP."), A("GRANT."), A("SELECT.", true), A("TRUNCATE."), A("COMMIT.")] },
  { certo: "Sistemas operacionais gerenciam recursos de hardware, processos, memória, arquivos e dispositivos de entrada e saída.", errado: "Um sistema operacional não participa do gerenciamento de memória nem da escalonamento de processos.", exp: "Gerenciamento de recursos é função central do sistema operacional.", pergunta: "No Windows, o Gerenciador de Tarefas permite, entre outras funções:", gab: "D", alts: [A("Alterar leis federais."), A("Criar banco relacional remoto automaticamente."), A("Emitir CNH."), A("Visualizar processos e uso de recursos.", true), A("Assinar mandados judiciais.")] },
  { certo: "Backup 3-2-1 recomenda três cópias dos dados, em dois tipos de mídia, com uma cópia fora do local principal.", errado: "Backup só é válido se armazenado no mesmo disco físico e sem versionamento.", exp: "A estratégia 3-2-1 reduz risco de perda por falhas locais e incidentes.", pergunta: "A autenticação multifator aumenta a segurança porque combina:", gab: "E", alts: [A("Apenas senha curta repetida."), A("Somente nome de usuário."), A("Desativação de logs."), A("Compartilhamento público de token."), A("Dois ou mais fatores, como senha e código temporário.", true)] },
];
addCE("b10-info-01", 30, "informatica", ["seguranca_informacao", "redes_nuvem", "bancos_dados_sql", "sistemas_operacionais", "ferramentas_escritorio"], infoSpecs, "info01Questoes", "info_01.mjs");

const rlmSpecs = [
  { certo: "A proposição composta 'p -> q' é falsa somente quando p é verdadeira e q é falsa.", errado: "A condicional 'p -> q' é falsa sempre que o consequente q é verdadeiro.", exp: "Tabela-verdade da condicional material.", pergunta: "A negação de 'p e q' é logicamente equivalente a:", gab: "A", alts: [A("não p ou não q.", true), A("não p e não q."), A("p ou q."), A("p então q."), A("q então p.")] },
  { certo: "A contrapositiva de 'se p, então q' é 'se não q, então não p', sendo logicamente equivalente à condicional original.", errado: "A recíproca 'se q, então p' é sempre logicamente equivalente a 'se p, então q'.", exp: "Condicional equivale à contrapositiva, não necessariamente à recíproca.", pergunta: "A proposição 'se estudo, então aprovo' é equivalente a:", gab: "B", alts: [A("Se aprovo, então estudo."), A("Se não aprovo, então não estudo.", true), A("Estudo e não aprovo."), A("Não estudo e aprovo."), A("Aprovo se e somente se estudo.")] },
  { certo: "Diagramas lógicos podem representar relações de inclusão, interseção e disjunção entre conjuntos.", errado: "Se todo A é B, então necessariamente todo B é A.", exp: "Inclusão não implica igualdade de conjuntos.", pergunta: "Se todo policial é servidor e alguns servidores são peritos, conclui-se necessariamente que:", gab: "C", alts: [A("Todo servidor é policial."), A("Todo perito é policial."), A("Nenhuma relação necessária entre policiais e peritos além das premissas.", true), A("Todo policial é perito."), A("Nenhum servidor é policial.")] },
  { certo: "Em contagem, se uma tarefa pode ser realizada de m modos e outra independente de n modos, o par ordenado pode ser realizado de m vezes n modos.", errado: "O princípio multiplicativo determina que possibilidades independentes sejam sempre subtraídas.", exp: "Princípio fundamental da contagem.", pergunta: "Com 3 camisas e 4 calças, o número de combinações possíveis é:", gab: "D", alts: [A("3."), A("4."), A("7."), A("12.", true), A("24.")] },
  { certo: "A probabilidade de evento impossível é zero e a de evento certo é um, em espaço amostral finito equiprovável.", errado: "Toda probabilidade válida deve ser maior que 1 quando o evento é provável.", exp: "Probabilidades variam entre 0 e 1.", pergunta: "Ao lançar um dado honesto, a probabilidade de obter número par é:", gab: "E", alts: [A("0."), A("1/6."), A("1/4."), A("2/3."), A("1/2.", true)] },
];
addCE("b10-rlm-01", 20, "rlm", ["logica_proposicional", "equivalencias_negacoes", "diagramas_logicos", "analise_combinatoria", "probabilidade"], rlmSpecs, "rlm01Questoes", "rlm_01.mjs");

const temas = [
  ce("b10-tempol-01-001", "constitucional", "seguranca_publica", banksCE[0], orgs[0], cargos[0], "medio", "O Sistema Único de Segurança Pública (SUSP), instituído pela Lei 13.675/2018, busca atuação conjunta, coordenada, sistêmica e integrada dos órgãos de segurança pública e defesa social.", "GABARITO: CERTO. A Lei 13.675/2018 disciplina o SUSP e a PNSPDS, voltados à integração federativa e gestão por resultados.", true),
  ce("b10-tempol-01-002", "constitucional", "seguranca_publica", banksCE[1], orgs[2], cargos[2], "facil", "A Lei 13.675/2018 exclui os municípios de qualquer política de segurança pública, vedando sua participação no SUSP.", "GABARITO: ERRADO. O SUSP é integrado por órgãos federais, estaduais, distritais e municipais, nos termos legais.", false),
  ce("b10-tempol-01-003", "direitos_humanos", "uso_forca_policial", banksCE[2], orgs[3], cargos[5], "medio", "A Portaria Interministerial 4.226/2010 orienta que agentes de segurança pública não devem disparar armas de fogo contra pessoa em fuga que esteja desarmada ou que não represente risco imediato de morte ou lesão grave.", "GABARITO: CERTO. As diretrizes nacionais sobre uso da força vedam emprego de arma de fogo sem ameaça atual ou iminente grave.", true),
  ce("b10-tempol-01-004", "direitos_humanos", "uso_forca_policial", banksCE[0], orgs[1], cargos[1], "dificil", "O uso diferenciado da força exige avaliação dinâmica de risco, seleção proporcional de meios e prestação de contas posterior, especialmente quando houver lesão ou morte.", "GABARITO: CERTO. Legalidade, necessidade, proporcionalidade, moderação e accountability orientam o emprego da força.", true),
  me("b10-tempol-01-005", "constitucional", "seguranca_publica", banksME[0], orgs[0], cargos[2], "medio", "A Política Nacional de Segurança Pública e Defesa Social tem como diretriz:", "GABARITO: B. A Lei 13.675/2018 prioriza integração, interoperabilidade, planejamento, metas, transparência e respeito aos direitos fundamentais.", [A("Atuação isolada de cada órgão sem compartilhamento de dados."), A("Integração, planejamento estratégico e atuação coordenada dos integrantes do SUSP.", true), A("Supressão do controle externo da atividade policial."), A("Vedação absoluta ao uso de tecnologia."), A("Extinção das guardas municipais.")]),
  ce("b10-tempol-01-006", "processo_penal", "provas_processo_penal", banksCE[1], orgs[2], cargos[3], "medio", "Na preservação de local de crime, o primeiro agente público que chega ao local deve evitar alterações indevidas, isolar a área e acionar a perícia competente.", "GABARITO: CERTO. A preservação do local e da cadeia de custódia é essencial para a confiabilidade da prova pericial.", true),
  ce("b10-tempol-01-007", "processo_penal", "busca_apreensao", banksCE[2], orgs[3], cargos[5], "facil", "A abordagem policial deve ser fundada em parâmetros objetivos de segurança e legalidade, sendo insuficiente a escolha baseada exclusivamente em preconceito ou perfilamento discriminatório.", "GABARITO: CERTO. Atuação policial deve respeitar legalidade, igualdade e direitos fundamentais; abordagens arbitrárias podem gerar nulidades e responsabilização.", true),
  ce("b10-tempol-01-008", "direitos_humanos", "uso_forca_policial", banksCE[0], orgs[5], cargos[5], "medio", "A verbalização, quando segura e viável, é técnica de menor potencial ofensivo e pode reduzir escalada de resistência durante abordagem policial.", "GABARITO: CERTO. Técnicas de comunicação e negociação integram modelos de uso diferenciado da força.", true),
  me("b10-tempol-01-009", "processo_penal", "provas_processo_penal", banksME[1], orgs[0], cargos[0], "dificil", "Em balística forense, o exame de confronto microbalístico busca:", "GABARITO: C. O confronto microbalístico compara marcas deixadas em projéteis/estojos para verificar compatibilidade com arma de fogo específica.", [A("Medir exclusivamente a altura do atirador."), A("Definir automaticamente a autoria do crime sem outras provas."), A("Comparar marcas em projéteis ou estojos com padrões de uma arma de fogo.", true), A("Substituir a cadeia de custódia."), A("Determinar tipo sanguíneo da vítima.")]),
  ce("b10-tempol-01-010", "constitucional", "seguranca_publica", banksCE[1], orgs[4], cargos[6], "medio", "A atividade de inteligência de segurança pública deve observar direitos e garantias fundamentais, controle institucional e finalidade pública, não se confundindo com investigação penal sem base legal.", "GABARITO: CERTO. Inteligência policial deve respeitar legalidade, finalidade, proporcionalidade e mecanismos de controle.", true),
  ce("b10-tempol-01-011", "direitos_humanos", "uso_forca_policial", banksCE[2], orgs[1], cargos[1], "facil", "O agente de segurança pública deve receber treinamento continuado em direitos humanos, uso diferenciado da força, técnicas de menor potencial ofensivo e atendimento pré-hospitalar básico.", "GABARITO: CERTO. Capacitação contínua é diretriz de profissionalização policial e redução de danos.", true),
  ce("b10-tempol-01-012", "processo_penal", "busca_apreensao", banksCE[0], orgs[2], cargos[4], "medio", "A busca pessoal depende de fundada suspeita de que a pessoa esteja na posse de arma proibida, objetos ou papéis que constituam corpo de delito, não se legitimando por mera intuição genérica.", "GABARITO: CERTO. Art. 244 do CPP exige fundada suspeita; jurisprudência rejeita abordagens baseadas apenas em impressões subjetivas ou perfilamento discriminatório.", true),
  me("b10-tempol-01-013", "constitucional", "seguranca_publica", banksME[2], orgs[3], cargos[5], "medio", "A integração operacional entre órgãos no SUSP deve preservar:", "GABARITO: D. A integração não extingue competências constitucionais dos órgãos, mas coordena atuação e informações conforme a lei.", [A("Supressão total das competências constitucionais."), A("Atuação sem registro e sem auditoria."), A("Controle por particulares armados."), A("Competências constitucionais e legais de cada instituição.", true), A("Sigilo absoluto sem prestação de contas.")]),
  ce("b10-tempol-01-014", "processo_penal", "provas_processo_penal", banksCE[1], orgs[0], cargos[2], "dificil", "A documentação fotográfica e o registro de entrada e saída de pessoas em local de crime auxiliam a cadeia de custódia e a rastreabilidade dos vestígios.", "GABARITO: CERTO. Rastreabilidade e documentação são elementos fundamentais da cadeia de custódia prevista no CPP.", true),
  ce("b10-tempol-01-015", "direitos_humanos", "uso_forca_policial", banksCE[2], orgs[5], cargos[5], "medio", "Após episódio com uso de força potencialmente letal, devem ser priorizados socorro às pessoas feridas, preservação do local, comunicação aos órgãos competentes e registro circunstanciado.", "GABARITO: CERTO. Diretrizes nacionais e internacionais de uso da força exigem preservação da vida, accountability e documentação adequada.", true),
];
addModule("temas_policiais_01.mjs", "temasPoliciais01Questoes", temas);

for (const m of modules) writeModule(m.fileName, m.exportName, m.questions);
console.log(`Generated ${modules.length} modules and ${modules.reduce((s, m) => s + m.questions.length, 0)} questions.`);
