import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const transito02 = [
  // 1 to 10: Infrações e Penalidades (Pontuação escalonada, Alcoolemia, Suspensão)
  {
    idSlug: "b10-trans-02-001",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O limite de pontuação para instauração do processo de suspensão do direito de dirigir por acúmulo de pontos no período de 12 meses é de 20 pontos caso o condutor conste 2 ou mais infrações gravíssimas, 30 pontos com 1 infração gravíssima, e 40 pontos caso não conste nenhuma infração gravíssima.",
    explicacao: "GABARITO: CERTO. Art. 261, I, 'a', 'b' e 'c', do CTB (redação pela Lei 14.071/2020): regra escalonada de 20, 30 e 40 pontos conforme número de gravíssimas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-002",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para o condutor que exerce atividade remunerada ao veículo (EAR), a penalidade de suspensão por pontos é instaurada quando o condutor atinge o limite fixo de 40 pontos, independentemente da natureza das infrações cometidas.",
    explicacao: "GABARITO: CERTO. Art. 261, § 5º, do CTB: para condutores com EAR (qualquer categoria), o limite é sempre de 40 pontos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-003",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "No julgamento das ADIs 4103, 4017 e do Tema 1079 da Repercussão Geral (RE 1.224.374/RS), o Supremo Tribunal Federal declarou:",
    explicacao: "GABARITO: A. O STF julgou 100% constitucional a 'Lei Seca' e a autuação do art. 165-A (recusa ao teste do etilômetro), confirmando a tolerância zero e a aplicação da multa multiplicada por 10 e suspensão por 12 meses.",
    alternativas: [
      { texto: "Constitucional a imposição da penalidade administrativa de multa e suspensão ao condutor que se recusa a submeter-se ao teste de etilômetro ou perícia (art. 165-A do CTB).", correta: true },
      { texto: "Inconstitucional a aplicação de penalidade pela simples recusa sem prova pericial de embriaguez evidente.", correta: false },
      { texto: "Obrigatória a fixação de margem de tolerância de até 0,5 mg/l para todos os motoristas.", correta: false },
      { texto: "Nula a apreensão da CNH em blitz de trânsito.", correta: false },
      { texto: "Competência exclusiva da Polícia Federal para fiscalização da Lei Seca nas capitais.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-004",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Dirigir sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência (art. 165 do CTB) é infração gravíssima com penalidade de multa multiplicada por dez e suspensão do direito de dirigir por 12 meses.",
    explicacao: "GABARITO: CERTO. Art. 165 do CTB: gravíssima, multa 10x e suspensão por 12 meses, além de recolhimento da CNH e retenção do veículo.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-005",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em caso de reincidência na infração de dirigir sob influência de álcool no período de até 12 meses, aplica-se a multa em dobro e instaura-se o processo de cassação do documento de habilitação.",
    explicacao: "GABARITO: CERTO. Art. 165, parágrafo único, e art. 263, II, do CTB: reincidência em 12 meses acarreta multa em dobro e cassação da CNH.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-006",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O prazo para expedição da notificação da autuação ao infrator pelo órgão de trânsito é de no máximo 30 dias contados da data do cometimento da infração, sob pena de arquivamento do auto de infração e seu julgamento insubsistente.",
    explicacao: "GABARITO: CERTO. Art. 281, parágrafo único, II, do CTB e Súmula 312 do STJ: decadência do direito de punir se a notificação não for expedida em 30 dias.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-007",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São penalidades de trânsito expressamente previstas no art. 256 do CTB, EXCETO:",
    explicacao: "GABARITO: E. A retenção do veículo, a remoção do veículo e o recolhimento da CNH são medidas administrativas (art. 269 do CTB), e não penalidades. As penalidades são: advertência por escrito, multa, suspensão do direito de dirigir, cassação da CNH, cassação da PPD e frequência obrigatória em curso de reciclagem.",
    alternativas: [
      { texto: "Advertência por escrito.", correta: false },
      { texto: "Multa.", correta: false },
      { texto: "Suspensão do direito de dirigir.", correta: false },
      { texto: "Cassação da Carteira Nacional de Habilitação.", correta: false },
      { texto: "Retenção e remoção do veículo.", correta: true },
    ],
  },

  // 8 to 25: Crimes de Trânsito (Arts. 291 a 312-B)
  {
    idSlug: "b10-trans-02-008",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Aos crimes de trânsito de lesão corporal culposa não se aplicam os institutos da composição civil dos danos e da transação penal da Lei nº 9.099/1995 caso o condutor esteja sob a influência de álcool ou qualquer outra substância psicoativa.",
    explicacao: "GABARITO: CERTO. Art. 291, § 1º, I, do CTB afasta expressamente os benefícios da Lei 9.099/95 (composição e transação) na lesão culposa sob influência de álcool.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-009",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "No homicídio culposo na direção de veículo automotor (art. 302 do CTB), a pena é aumentada de 1/3 (um terço) à metade se o agente:",
    explicacao: "GABARITO: D. Art. 302, § 1º, I a IV, do CTB prevê as causas de aumento: não possuir PPD/CNH, praticá-lo em faixa de pedestres ou calçada, deixar de prestar socorro quando possível sem risco pessoal, ou no exercício de profissão em transporte de passageiros.",
    alternativas: [
      { texto: "Conduzir veículo com mais de dez anos de fabricação.", correta: false },
      { texto: "Cometer o crime em rodovia estadual não pedagiada.", correta: false },
      { texto: "Ultrapassar ciclista sem reduzir a velocidade.", correta: false },
      { texto: "Não possuir Permissão para Dirigir ou Carteira de Habilitação, ou praticá-lo em faixa de pedestres ou calçada.", correta: true },
      { texto: "Estar com o licenciamento anual do veículo em atraso.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-010",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "No homicídio culposo na direção de veículo automotor praticado por condutor com capacidade psicomotora alterada em razão de álcool ou outra substância psicoativa (art. 302, § 3º, do CTB), a pena cominada é de reclusão de cinco a oito anos, sendo vedada a substituição por pena restritiva de direitos pela Lei nº 14.071/2020.",
    explicacao: "GABARITO: CERTO. Art. 302, § 3º, e art. 312-A do CTB (introduzido pela Lei 14.071/20) vedam a substituição por restritiva de direitos no homicídio culposo embriagado.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-011",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de embriaguez ao volante (art. 306 do CTB) é de perigo abstrato, consumando-se com a condução de veículo automotor na via pública com capacidade psicomotora alterada, prescindindo da demonstração de dano potencial ou condução anormal.",
    explicacao: "GABARITO: CERTO. Tema 484 do STJ e jurisprudência pacífica do STF: o crime do art. 306 do CTB é de perigo abstrato.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-012",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Para a caracterização do crime de embriaguez ao volante previsto no art. 306 do CTB, a concentração de álcool por meio de etilômetro deve ser igual ou superior a:",
    explicacao: "GABARITO: C. Art. 306, § 1º, I, do CTB: concentração igual ou superior a 6 decigramas de álcool por litro de sangue ou igual ou superior a 0,3 miligrama de álcool por litro de ar alveolar (0,34 mg/l considerado o erro máximo admissível na tabela do CONTRAN).",
    alternativas: [
      { texto: "0,05 miligrama de álcool por litro de ar alveolar.", correta: false },
      { texto: "0,15 miligrama de álcool por litro de ar alveolar.", correta: false },
      { texto: "0,3 miligrama de álcool por litro de ar alveolar (ou 6 decigramas por litro de sangue).", correta: true },
      { texto: "1,0 miligrama de álcool por litro de ar alveolar.", correta: false },
      { texto: "2,0 decigramas de álcool por litro de sangue.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-013",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Ao condutor de veículo, nos casos de acidentes de trânsito de que resulte vítima, não se imporá a prisão em flagrante, nem se exigirá fiança, se prestar pronto e integral socorro àquela.",
    explicacao: "GABARITO: CERTO. Art. 301 do CTB veda a prisão em flagrante e a exigência de fiança ao condutor que presta socorro voluntário à vítima do acidente.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-014",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de omissão de socorro no trânsito (art. 304 do CTB) consuma-se ainda que a vítima tenha tido morte instantânea ou haja socorro prestado por terceiros presentes no local.",
    explicacao: "GABARITO: CERTO. Art. 304, parágrafo único, do CTB: a omissão de socorro é punível ainda que a vítima tenha morte instantânea ou seja socorrida por terceiros.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-015",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O tipo penal do art. 308 do CTB pune a participação em corrida, disputa ou competição automobilística não autorizada na via pública (racha). Se da prática resultar morte e as circunstâncias demonstrarem que o agente não quis o resultado nem assumiu o risco de produzi-lo:",
    explicacao: "GABARITO: B. Art. 308, § 2º, do CTB: trata-se de crime preterdoloso de racha qualificado pelo resultado morte culposa, com pena de reclusão de 5 a 10 anos.",
    alternativas: [
      { texto: "O agente responderá por homicídio doloso qualificado perante o Tribunal do Júri.", correta: false },
      { texto: "Aplica-se a pena de reclusão, de 5 (cinco) a 10 (dez) anos, tratando-se de figura qualificada preterdolosa.", correta: true },
      { texto: "O crime é absorvido pela infração administrativa de trânsito.", correta: false },
      { texto: "A pena será apenas de detenção de 6 meses a 2 anos.", correta: false },
      { texto: "Extingue-se a punibilidade se o veículo pertencer a terceiro de boa-fé.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-016",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O crime de fuga do local do acidente (art. 305 do CTB) teve sua constitucionalidade plenamente confirmada pelo STF no Tema 907 da Repercussão Geral, não violando o princípio que veda a autoincriminação.",
    explicacao: "GABARITO: CERTO. Tema 907 do STF (RE 971.959/RS): é constitucional o art. 305 do CTB (afastar-se o condutor do veículo do local do acidente para fugir à responsabilidade penal ou civil).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-017",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Dirigir veículo automotor, em via pública, sem a devida Permissão para Dirigir ou Habilitação ou, ainda, se cassado o direito de dirigir, gerando perigo de dano (art. 309 do CTB) é crime de perigo concreto.",
    explicacao: "GABARITO: CERTO. Art. 309 do CTB e Súmula 720 do STF: o crime do art. 309 exige perigo concreto de dano.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-018",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O crime de entregar a direção de veículo automotor a pessoa não habilitada, com habilitação cassada ou sem condições de conduzir com segurança (art. 310 do CTB) é de perigo abstrato, prescindindo de perigo concreto de dano.",
    explicacao: "GABARITO: CERTO. Súmula 575 do STJ: o crime do art. 310 do CTB é de perigo abstrato, dispensando demonstração de dano potencial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-019",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A penalidade de suspensão ou de proibição de se obter a permissão ou a habilitação para dirigir veículo automotor tem a duração de dois meses a cinco anos.",
    explicacao: "GABARITO: CERTO. Art. 293 do CTB: a penalidade judicial de suspensão/proibição da CNH varia de 2 meses a 5 anos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-020",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Violar a suspensão ou a proibição de se obter a permissão ou a habilitação para dirigir veículo automotor imposta com fundamento no CTB configura crime autônomo (art. 307 do CTB), cuja pena é de detenção de seis meses a um ano e multa, com nova imposição de suspensão ou de proibição por igual prazo.",
    explicacao: "GABARITO: CERTO. Art. 307, caput e parágrafo único, do CTB criminaliza a violação de suspensão imposta judicialmente.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-021",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre a aplicação do perdão judicial no crime de homicídio culposo de trânsito (art. 302 do CTB e art. 121, § 5º, do CP):",
    explicacao: "GABARITO: C. Súmula 18 do STJ e art. 121, § 5º, do CP (aplicável por força do art. 291 do CTB): o juiz pode deixar de aplicar a pena se as consequências da infração atingirem o próprio agente de forma tão grave que a sanção penal se torne desnecessária (ex.: o condutor atropela culposamente o próprio filho).",
    alternativas: [
      { texto: "O perdão judicial é expressamente proibido nos crimes previstos no Código de Trânsito Brasileiro.", correta: false },
      { texto: "O perdão judicial depende de prévia concordância do Ministério Público e pagamento de indenização de 100 salários mínimos.", correta: false },
      { texto: "O juiz poderá deixar de aplicar a pena se as consequências da infração atingirem o próprio agente de forma tão grave que a sanção penal se torne desnecessária.", correta: true },
      { texto: "O perdão judicial gera reincidência e registro na certidão de antecedentes para todos os efeitos.", correta: false },
      { texto: "Aplica-se apenas quando o autor do crime for policial em serviço ostensivo.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-022",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de trafegar em velocidade incompatível com a segurança nas proximidades de escolas, hospitais, estações de embarque e desembarque de passageiros (art. 311 do CTB) exige a geração de perigo de dano.",
    explicacao: "GABARITO: CERTO. Art. 311 do CTB exige expressamente a elementar 'gerando perigo de dano' (crime de perigo concreto).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-023",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Inovar artificiosamente, em caso de acidente automobilístico com vítima, na pendência do respectivo procedimento policial ou judicial, o estado de lugar, de coisa ou de pessoa, para induzir a erro o agente policial ou o perito, configura o crime do art. 312 do CTB.",
    explicacao: "GABARITO: CERTO. Art. 312 do CTB tipifica a fraude processual em acidente automobilístico de trânsito.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-024",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Nos crimes de homicídio culposo ou lesão corporal culposa de trânsito praticados sob a influência de álcool (art. 302, § 3º, e art. 303, § 2º, do CTB), não cabe a concessão de fiança pelo Delegado de Polícia, por ultrapassarem 4 anos de pena máxima cominada.",
    explicacao: "GABARITO: CERTO. Art. 322 do CPP: a autoridade policial só pode arbitrar fiança em crimes cuja pena privativa máxima não exceda a 4 anos. No art. 302, § 3º (reclusão de 5 a 8 anos) e no art. 303, § 2º (reclusão de 2 a 5 anos), a fiança é de competência exclusiva do juiz.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-02-025",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "e74dc693-757f-5086-97a0-0710b9473007",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A utilização de aparelho celular ao volante, segurando-o ou manuseando-o enquanto dirige, é classificada pelo CTB como infração gravíssima sujeita a multa.",
    explicacao: "GABARITO: CERTO. Art. 252, parágrafo único, do CTB: segurar ou manusear telefone celular é infração gravíssima.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
];

const file02Content = `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const transito02Questoes = ${JSON.stringify(transito02, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, "transito_02.mjs"), file02Content, "utf8");
console.log("transito_02.mjs gerado com sucesso! (25 questões)");
