import { TAXONOMIA } from "./taxonomia.mjs";

export const dhCriminologia02Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "dh-crim-02-001",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para a Escola Clássica da Criminologia (representada por Cesare Beccaria e Francesco Carrara), o crime é concebido como um ente jurídico, decorrente do livre-arbítrio e da escolha moral do indivíduo, devendo a pena possuir caráter eminentemente retributivo e proporcional.",
    explicacao: "GABARITO: CERTO. A Escola Clássica fundamenta-se no jusnaturalismo, no livre-arbítrio (homem como ser racional que escolhe o crime) e no crime como ente jurídico/infração da norma, com pena retributiva, certa e proporcional.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-002",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Escola Positiva da Criminologia substituiu o método abstrato e dedutivo da Escola Clássica pelo método empírico, indutivo e experimental, elegendo o criminoso como o centro das investigações e defendendo o determinismo biológico ou social.",
    explicacao: "GABARITO: CERTO. Positivismo Criminológico (Lombroso, Ferri e Garofalo): Adota o método empírico-indutivo (observação científica), nega o livre-arbítrio (determinismo) e foca na figura do delinquente e na periculosidade social.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-003",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A cifra negra da criminalidade corresponde à porcentagem ou número de crimes efetivamente cometidos na sociedade que não chegam ao conhecimento oficial dos órgãos estatais de controle formal (como polícias e Judiciário).",
    explicacao: "GABARITO: CERTO. Cifra Negra (Dark Number): Distorção estatística entre a criminalidade real (crimes praticados) e a criminalidade aparente/registrada oficialmente pelas forças policiais.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-004",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A Teoria da Associação Diferencial (desenvolvida por Edwin Sutherland) sustenta que o comportamento criminoso é aprendido por meio de processos de comunicação e interação com grupos íntimos, explicando a gênese dos crimes de colarinho branco (white-collar crimes).",
    explicacao: "GABARITO: CERTO. Sutherland formulou a Teoria da Associação Diferencial e o conceito de crimes de colarinho branco, demonstrando que a criminalidade não decorre de patologias biológicas ou pobreza, mas de aprendizagem social de técnicas e atitudes favoráveis à violação da lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-005",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A vitimização secundária (ou sobrevitimização) refere-se ao sofrimento adicional causado à vítima pelo próprio funcionamento insensível, burocrático e constrangedor das instâncias formais de persecução penal (delegacias de polícia, fóruns e perícias).",
    explicacao: "GABARITO: CERTO. Vitimização primária: dano direto decorrente do crime. Vitimização secundária: sofrimento gerado pelas instituições estatais de controle penal ao acolher ou inquirir a vítima. Vitimização terciária: estigmatização e abandono da vítima pelo seu grupo social.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-006",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A Teoria das Janelas Quebradas (Broken Windows Theory) preconiza que a tolerância estatal com pequenas desordens urbanas, vandalismo e contravenções transmite uma mensagem de ausência de controle social, atraindo a ocorrência de crimes mais graves e violentos na comunidade.",
    explicacao: "GABARITO: CERTO. Teoria formulada por James Q. Wilson e George Kelling em 1982: O descuido com pequenas desordens ambientais e infrações menores encoraja o surgimento de criminalidade violenta.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-007",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A prevenção terciária do crime é aquela voltada a atuar nas raízes profundas do conflito social, mediante políticas públicas de educação, emprego, saúde e habitação direcionadas a toda a população.",
    explicacao: "GABARITO: ERRADO. Políticas públicas amplas de educação, saúde e moradia correspondem à Prevenção PRIMÁRIA. A prevenção secundária foca em grupos de risco iminente ou locais específicos. A prevenção TERCIÁRIA é voltada ao sentenciado/apenado, visando à reintegração social e à não reincidência.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "dh-crim-02-008",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Labeling Approach (Teoria do Etiquetamento Social ou da Reação Social) sustenta que a criminalidade não é uma qualidade intrínseca do ato praticado, mas sim o resultado de um processo de estigmatização seletiva conferido pelas instâncias formais de controle sobre determinados indivíduos vulneráveis.",
    explicacao: "GABARITO: CERTO. Teoria do Etiquetamento (Becker, Lemert): O desvio não é uma qualidade intrínseca do comportamento, mas uma etiqueta criada pelas agências formais de punição que estigmatizam seletivamente certos indivíduos (desvio secundário).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "dh-crim-02-009",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A teoria sociológica do crime que explica o desvio pela dissociação estrutural entre as metas culturalmente valorizadas pelo sucesso social e a falta de meios institucionais legítimos disponíveis para que todas as classes alcancem tais objetivos é a:",
    explicacao: "GABARITO: A. Teoria da Anomia formulada por Robert Merton: Ocorre tensão/frustração quando a estrutura cultural impõe objetivos de sucesso material, mas a estrutura social não proporciona meios institucionais legítimos para todos os estratos.",
    alternativas: [
      { texto: "Teoria da Anomia (Strain Theory de Robert Merton).", correta: true },
      { texto: "Teoria da Defesa Social de Enrico Ferri.", correta: false },
      { texto: "Teoria Ecológica de Clifford Shaw.", correta: false },
      { texto: "Teoria da Neutralização de Sykes e Matza.", correta: false },
      { texto: "Teoria dos Círculos Concêntricos de Park e Burgess.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-010",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na tipologia vitimológica clássica de Benjamin Mendelsohn, a vítima que não concorreu de nenhuma forma para a eclosão do evento delituoso, sendo completamente inocente e alheia à conduta do agente, é classificada como:",
    explicacao: "GABARITO: B. Mendelsohn classifica as vítimas em: 1) Vítima completamente inocente ou ideal; 2) Vítima de culpabilidade menor/por ignorância; 3) Vítima tão culpada quanto o infrator (voluntária); 4) Vítima mais culpada que o infrator; 5) Vítima unicamente culpada/agressora.",
    alternativas: [
      { texto: "Vítima voluntária ou simuladora.", correta: false },
      { texto: "Vítima completamente inocente (ou vítima ideal).", correta: true },
      { texto: "Vítima unicamente culpada.", correta: false },
      { texto: "Vítima por provocação direta.", correta: false },
      { texto: "Vítima por imprudência profissional.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-011",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Escola de Chicago (ou Teoria Ecológica/Desorganização Social) destacou-se nos estudos criminológicos por demonstrar que a criminalidade urbana:",
    explicacao: "GABARITO: C. Escola de Chicago (Parck, Burgess, Shaw e McKay): A criminalidade decorre da rápida urbanização, deterioração física de áreas centrais, enfraquecimento das instituições de controle informal e desorganização social, e não de predisposição biológica.",
    alternativas: [
      { texto: "está geneticamente ligada a fatores atávicos e cranianos herdados.", correta: false },
      { texto: "é erradicada exclusivamente mediante elevação exponencial das penas de prisão.", correta: false },
      { texto: "concentra-se em zonas urbanas deterioradas de transição, onde impera a desorganização social e o enfraquecimento dos laços comunitários.", correta: true },
      { texto: "manifesta-se apenas em sociedades sem divisão de trabalho especializada.", correta: false },
      { texto: "depende exclusivamente da atuação arbitrária dos tribunais estatais.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-012",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A 'cifra dourada' (golden number) no âmbito da Criminologia refere-se aos crimes:",
    explicacao: "GABARITO: D. Cifra Dourada: Crimes praticados pela elite econômica/política (crimes de colarinho branco, crimes financeiros e de corrupção corporativa) que raramente são investigados ou punidos pelo sistema de justiça criminal.",
    alternativas: [
      { texto: "praticados exclusivamente contra instituições bancárias com uso de explosivos.", correta: false },
      { texto: "violentos com resultado morte não solucionados no prazo legal de 30 dias.", correta: false },
      { texto: "de menor potencial ofensivo resolvidos por transação penal.", correta: false },
      { texto: "praticados pela elite econômica ou política (crimes de colarinho branco) com baixíssimo índice de persecução penal.", correta: true },
      { texto: "cometidos com utilização de pedras e metais preciosos.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-013",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O movimento de Política Criminal conhecido como 'Direito Penal do Inimigo' (desenvolvido por Günther Jakobs) caracteriza-se por:",
    explicacao: "GABARITO: E. Direito Penal do Inimigo de Jakobs: Antecipação da punibilidade para atos preparatórios, supressão ou mitigação de garantias processuais e penais materiais, desproporcionalidade de penas e tratamento do agente como fonte de perigo (inimigo) e não como cidadão.",
    alternativas: [
      { texto: "adotar a descriminalização ampla e o abolicionismo penal irrestrito.", correta: false },
      { texto: "priorizar a conciliação e a justiça restaurativa nas penitenciárias de segurança máxima.", correta: false },
      { texto: "proibir a existência de crimes de perigo abstrato e hediondos.", correta: false },
      { texto: "reforçar a presunção de inocência irrestrita até a última instância internacional.", correta: false },
      { texto: "antecipar a punição a atos preparatórios, agravar penas e restringir garantias fundamentais daquele considerado perigo contínuo à ordem.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "dh-crim-02-014",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Cesare Lombroso, um dos fundadores da Criminologia Positiva com a obra 'O Homem Delinquente' (1876), notabilizou-se pela formulação da teoria do:",
    explicacao: "GABARITO: A. Lombroso formulou a controversa teoria do 'criminoso nato' com base no atavismo biológico e estigmas anatômicos corporais e cranianos.",
    alternativas: [
      { texto: "Criminoso Nato, fundamentado no atavismo e estigmas corporais.", correta: true },
      { texto: "Livre-arbítrio absoluto racional e proporcional.", correta: false },
      { texto: "Contrato social fundamentado no utilitarismo de Bentham.", correta: false },
      { texto: "Abolicionismo prisional por ausência de eficácia ressocializadora.", correta: false },
      { texto: "Etiquetamento social punitivo exclusivo dos desvalidos.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-015",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A Criminologia contemporânea define seu objeto de estudo como sendo composto por quatro elementos fundamentais inter-relacionados:",
    explicacao: "GABARITO: B. O quadrilátero fundamental da Criminologia moderna abrange: o Delito (crime), o Delinquente (criminoso), a Vítima e o Controle Social (formal e informal).",
    alternativas: [
      { texto: "o juiz, o promotor, o advogado e o perito oficial.", correta: false },
      { texto: "o delito, o delinquente, a vítima e o controle social.", correta: true },
      { texto: "o inquérito, a denúncia, a sentença e a execução penal.", correta: false },
      { texto: "a prisão temporária, a preventiva, o flagrante e a soltura provisória.", correta: false },
      { texto: "a arma de fogo, o local do crime, o cadáver e a perícia balística.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-016",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na Criminologia, as instâncias de CONTROLE SOCIAL FORMAL são representadas por:",
    explicacao: "GABARITO: C. Controle social formal: órgãos do Estado encarregados da coerção e aplicação do Direito Penal (Polícia, Ministério Público, Judiciário e Sistema Penitenciário). Controle social informal: família, escola, igreja, comunidade, clubes e opinião pública.",
    alternativas: [
      { texto: "família, religião, vizinhança e grupos de amigos.", correta: false },
      { texto: "redes sociais, imprensa e associações desportivas.", correta: false },
      { texto: "Polícia, Ministério Público, Poder Judiciário e Sistema Penitenciário.", correta: true },
      { texto: "conselhos comunitários de segurança e sindicatos civis.", correta: false },
      { texto: "escolas fundamentais e universidades públicas.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "dh-crim-02-017",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A 'vitimização terciária' consiste:",
    explicacao: "GABARITO: D. Vitimização terciária: Estigmatização, rejeição, discriminação ou abandono social que a vítima sofre perante seu próprio grupo social, familiar ou comunitário em virtude do fato de ter sido vitimizada.",
    alternativas: [
      { texto: "na agressão física inicial sofrida durante a prática do roubo.", correta: false },
      { texto: "no interrogatório agressivo do delegado durante o inquérito policial.", correta: false },
      { texto: "no ressarcimento financeiro do dano determinado na sentença penal.", correta: false },
      { texto: "na discriminação, estigmatização e abandono moral sofridos pela vítima no seio de seu próprio grupo social ou familiar.", correta: true },
      { texto: "na concessão do livramento condicional antecipado ao réu.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-018",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O método científico adotado primordialmente pela Criminologia para analisar a realidade do crime como fato social é o:",
    explicacao: "GABARITO: A. A Criminologia é uma ciência empírica e interdisciplinar, baseada na observação, indução e experimentação dos fatos da realidade criminal (método empírico-indutivo).",
    alternativas: [
      { texto: "empírico e interdisciplinar (baseado na observação e nos fatos da realidade).", correta: true },
      { texto: "dogmático-formal estrito e dedutivo da subsunção típica legal.", correta: false },
      { texto: "metafísico-especulativo desprovido de dados numéricos.", correta: false },
      { texto: "puramente lógico-matemático sem correlação sociológica.", correta: false },
      { texto: "normativo-prescritivo idêntico ao do Direito Processual Civil.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "dh-crim-02-019",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_vitimologia_prevencao,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A 'cifra verde' na classificação criminológica contemporânea refere-se:",
    explicacao: "GABARITO: B. Cifra Verde: Crimes ambientais ou ecológicos não registrados oficialmente ou que permanecem na impunidade sem a devida persecução fiscalizatória ou judicial.",
    alternativas: [
      { texto: "aos crimes praticados por servidores recém-empossados na administração.", correta: false },
      { texto: "às infrações e crimes ecológicos ou ambientais que não chegam ao conhecimento das autoridades de fiscalização e punição.", correta: true },
      { texto: "aos delitos cometidos durante o período eleitoral municipal.", correta: false },
      { texto: "aos crimes ocorridos em áreas rurais com o consentimento expresso da vítima.", correta: false },
      { texto: "aos furtos de espécies florestais com valor inferior a um salário mínimo.", correta: false },
    ],
  },
  {
    idSlug: "dh-crim-02-020",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.criminologia_escolas_teorias,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A Teoria da Neutralização (formulada por David Matza e Gresham Sykes) estuda as técnicas cognitivas pelas quais o indivíduo:",
    explicacao: "GABARITO: C. Técnicas de neutralização: O indivíduo racionaliza e justifica seu comportamento ilícito (negação da responsabilidade, negação do dano, negação da vítima, condenação dos que condenam, apelo a lealdades superiores) para neutralizar a culpa moral antes ou após a prática do delito.",
    alternativas: [
      { texto: "elimina completamente o uso de armas em disputas territoriais.", correta: false },
      { texto: "aceita voluntariamente a pena máxima de reclusão sem recurso.", correta: false },
      { texto: "justifica ou racionaliza moralmente sua conduta ilícita, atenuando temporariamente a culpa para violar a lei.", correta: true },
      { texto: "denuncia os comparsas para obter perdão judicial antecipado.", correta: false },
      { texto: "rejeita qualquer auxílio de advogados de defesa pública.", correta: false },
    ],
  },
];
