import { TAXONOMIA } from "./taxonomia.mjs";

export const adm02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-adm-02-001",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Após as alterações promovidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa (Lei nº 8.429/1992), exige-se a demonstração de dolo específico para a configuração de qualquer ato de improbidade administrativa, tendo sido expressamente revogada a modalidade culposa.",
    explicacao: "GABARITO: CERTO. Art. 1º, §§ 1º, 2º e 3º, da Lei 8.429/92 (redação dada pela Lei 14.230/2021): 'Consideram-se atos de improbidade administrativa as condutas dolosas tipificadas nos arts. 9º, 10 e 11... o mero exercício da função ou desempenho de competências sem comprovação de ato doloso com fim ilícito afasta a responsabilidade.' A modalidade culposa do art. 10 foi revogada.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-002",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Um Agente de Polícia Federal estável foi demitido após processo administrativo disciplinar. Inconformado, ajuizou ação na Justiça Federal e obteve sentença transitada em julgado que declarou a nulidade do ato demissional por vício insanável. Nessa situação, o retorno do policial ao cargo com ressarcimento integral dos vencimentos e vantagens pretéritas dar-se-á mediante reintegração, devendo o eventual ocupante da vaga, se estável, ser reconduzido ao cargo de origem, sem direito a indenização.",
    explicacao: "GABARITO: CERTO. Art. 28 da Lei 8.112/90: a reintegração é a reinvestidura do servidor estável no cargo anteriormente ocupado quando invalidada a demissão por decisão administrativa ou judicial, com ressarcimento de todas as vantagens. Conforme o § 2º do mesmo dispositivo e o art. 29, II, o eventual ocupante da vaga, se estável, será reconduzido ao cargo de origem sem direito a indenização.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-003",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O servidor público federal estável que for inabilitado em estágio probatório relativo a outro cargo público para o qual foi nomeado tem direito a ser reconduzido ao cargo anteriormente ocupado.",
    explicacao: "GABARITO: CERTO. Art. 29, I, da Lei 8.112/90: 'Recondução é o retorno do servidor estável ao cargo anteriormente ocupado e decorrerá de: I - inabilitação em estágio probatório relativo a outro cargo; II - reintegração do anterior ocupante.'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-004",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Lei nº 14.133/2021 (Nova Lei de Licitações e Contratos Administrativos) instituiu o 'diálogo competitivo' como nova modalidade licitatória obrigatória para todas as compras rotineiras e padronizadas da administração pública federal.",
    explicacao: "GABARITO: ERRADO. Art. 28, V, e Art. 32 da Lei 14.133/2021: o diálogo competitivo é restrito a contratações que envolvam inovação tecnológica ou técnica, impossibilidade de o órgão ter sua necessidade satisfeita sem adaptação de soluções disponíveis no mercado ou quando as especificações técnicas não possam ser definidas com precisão. Compras padronizadas utilizam pregão ou concorrência.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-005",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.429/1992 com a redação dada pela Lei nº 14.230/2021, o prazo prescricional para a ação de improbidade administrativa é de oito anos, contados a partir da data da ocorrência do fato ou, no caso de infrações permanentes, do dia em que cessou a permanência.",
    explicacao: "GABARITO: CERTO. Art. 23 da Lei 8.429/92 (com redação da Lei 14.230/2021): 'A ação para a aplicação das sanções previstas nesta Lei prescreve em 8 (oito) anos, contados a partir da ocorrência do fato ou, no caso de infrações permanentes, do dia em que cessou a permanência.'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-006",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A posse no cargo público dependerá de prévia inspeção médica oficial e só poderá ocorrer nos casos de nomeação para cargo de provimento efetivo ou em comissão, devendo acontecer no prazo improrrogável de trinta dias contados da publicação do ato de provimento.",
    explicacao: "GABARITO: CERTO. Art. 13, caput e § 1º, e Art. 14 da Lei nº 8.112/90: a posse dar-se-á no prazo de 30 dias contados da publicação oficial do ato de provimento, exigindo-se prévia inspeção médica oficial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-007",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Diretoria de Administração Penitenciária realizou processo licitatório para aquisição padronizada de coletes de proteção balística padrão e munições de treino convencional, classificando os itens como bens comuns. Sob a disciplina da Lei nº 14.133/2021, o órgão adotou compulsoriamente a modalidade pregão, cujos únicos critérios legais de julgamento admitidos são menor preço ou maior desconto.",
    explicacao: "GABARITO: CERTO. Art. 6º, XLI, e Art. 34 da Lei nº 14.133/2021: o pregão é a modalidade de licitação obrigatória para aquisição de bens e serviços comuns, cujos padrões de desempenho e qualidade possam ser objetivamente definidos pelo edital, adotando-se sempre os critérios de julgamento de menor preço ou de maior desconto.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-008",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme decisão do STF no ARE 843.989 (Tema 1.199 da Repercussão Geral), a revogação da modalidade culposa do ato de improbidade promovida pela Lei nº 14.230/2021 retroage para alcançar condenações com trânsito em julgado e processos em curso.",
    explicacao: "GABARITO: ERRADO. O STF fixou no Tema 1.199 que a Lei 14.230/2021 APLICA-SE aos atos praticados na vigência do texto anterior sem condenação transitada em julgado (processos em curso), mas NÃO retroage para desconstituir decisões transitadas em julgado (respeito à coisa julgada).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-009",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A demissão de servidor público federal em razão da prática de crime contra a administração pública ou ato de improbidade incompatibiliza o ex-servidor para nova investidura em cargo público federal pelo prazo de cinco anos.",
    explicacao: "GABARITO: ERRADO. Art. 137, parágrafo único, da Lei 8.112/90: a demissão por crime contra a administração pública, improbidade administrativa, aplicação irregular de dinheiros públicos, lesão aos cofres públicos e dilapidação do patrimônio e corrupção incompatibiliza o ex-servidor pelo prazo de CINCO ANOS no caput para outras infrações graves, mas no caso de improbidade e crime funcional a incompatibilização é definitiva/perpétua segundo a redação estrita do parágrafo único.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-010",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A nova Lei de Licitações (Lei nº 14.133/2021) extinguiu as modalidades licitatórias de 'tomada de preços' e 'convite', mantendo concorrência, concurso, leilão, pregão e criando o diálogo competitivo.",
    explicacao: "GABARITO: CERTO. Art. 28 da Lei 14.133/2021: são modalidades de licitação: I - pregão; II - concorrência; III - concurso; IV - leilão; V - diálogo competitivo. Convite e tomada de preços foram suprimidos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-02-011",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre as sanções aplicáveis aos atos de improbidade administrativa previstos na Lei nº 8.429/1992 com as alterações da Lei nº 14.230/2021, assinale a afirmativa CORRETA:",
    explicacao: "GABARITO: A. Art. 12, I, da Lei 8.429/92 (redação da Lei 14.230/21): nos atos que importam enriquecimento ilícito (art. 9º), comina-se a perda dos bens ou valores acrescidos ilicitamente, perda da função pública, suspensão dos direitos políticos até 14 anos e multa civil equivalente ao valor do acréscimo patrimonial.",
    alternativas: [
      { texto: "No caso de atos que importam enriquecimento ilícito (Art. 9º), a suspensão dos direitos políticos pode ser cominada por até 14 (quatorze) anos.", correta: true },
      { texto: "A perda da função pública atinge automaticamente todos os vínculos funcionais de qualquer esfera, independentemente da função ocupada no momento do fato.", correta: false },
      { texto: "A sanção de proibição de contratar com o poder público é perpétua e irretratável.", correta: false },
      { texto: "Os herdeiros do agente ímprobo respondem pelas sanções privativas de liberdade e suspensão de direitos políticos.", correta: false },
      { texto: "A multa civil substitui obrigatoriamente a reparação integral do dano patrimonial efetivo.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-012",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Um policial civil estável havia sido aposentado por incapacidade permanente para o trabalho. Quatro anos depois, em inspeção pericial ordinária de reavaliação, a junta médica oficial do Estado declarou formalmente insubsistentes os motivos clínicos que justificavam a aposentadoria. Sob a disciplina dos provimentos no regime dos servidores públicos (analogia ao art. 25, I, da Lei nº 8.112/1990), o retorno do servidor à atividade funcional efetiva dá-se mediante:",
    explicacao: "GABARITO: C. Art. 25, I, da Lei nº 8.112/90: 'Reversão é o retorno à atividade de servidor aposentado: I - por invalidez, quando junta médica oficial declarar insubsistentes os motivos da aposentadoria'.",
    alternativas: [
      { texto: "Readaptação.", correta: false },
      { texto: "Aproveitamento.", correta: false },
      { texto: "Reversão.", correta: true },
      { texto: "Recondução.", correta: false },
      { texto: "Reintegração.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-013",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Lei nº 14.133/2021 estabelece as hipóteses de inexigibilidade de licitação, caracterizadas pela inviabilidade de competição. Constitui caso expressamente legal de inexigibilidade:",
    explicacao: "GABARITO: E. Art. 74, I, da Lei 14.133/2021: aquisição de materiais, equipamentos ou gêneros que só possam ser fornecidos por produtor, empresa ou representante comercial exclusivo.",
    alternativas: [
      { texto: "Contratação de obras de engenharia de pequeno valor para reparos emergenciais.", correta: false },
      { texto: "Aquisição de combustíveis automotivos em postos de abastecimento credenciados.", correta: false },
      { texto: "Contratação de serviços de limpeza predial e copeiragem contínua.", correta: false },
      { texto: "Compra de viaturas policiais padronizadas existentes em múltiplos fabricantes concorrentes.", correta: false },
      { texto: "Aquisição de materiais, equipamentos ou gêneros que só possam ser fornecidos por produtor, empresa ou representante comercial exclusivo.", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-014",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O prazo de validade do concurso público, nos termos do Art. 37, III, da Constituição Federal e da Lei nº 8.112/1990, será de:",
    explicacao: "GABARITO: B. Art. 37, III, CF e Art. 12 da Lei 8.112/90: até 2 anos, prorrogável uma única vez por igual período.",
    alternativas: [
      { texto: "Até um ano, prorrogável por até cinco anos.", correta: false },
      { texto: "Até dois anos, prorrogável uma vez, por igual período.", correta: true },
      { texto: "Três anos improrrogáveis.", correta: false },
      { texto: "Quatro anos, sem possibilidade de renovação.", correta: false },
      { texto: "Prazo fixado livremente pela comissão sem teto legal.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-015",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "De acordo com o Art. 11 da Lei nº 8.429/1992 com redação da Lei nº 14.230/2021, constitui ato de improbidade administrativa que atenta contra os princípios da administração pública:",
    explicacao: "GABARITO: D. Art. 11, V, da Lei 8.429/92 (Lei 14.230/21): o rol do art. 11 tornou-se taxativo, incluindo condutas como frustrar a licitude de concurso público ou revelar fato confidencial.",
    alternativas: [
      { texto: "A interpretação jurídica divergente fundamentada em doutrina minoritária.", correta: false },
      { texto: "O erro material escusável na prestação de contas sem dolo de lesão.", correta: false },
      { texto: "A discordância funcional técnica entre parecerista e ordenador de despesas.", correta: false },
      { texto: "Frustrar, em ofensa aos princípios da impessoalidade e moralidade, a licitude de concurso público ou processo seletivo.", correta: true },
      { texto: "Atrasar o envio de relatório administrativo em razão de férias coletivas de servidores.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-016",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 14.133/2021, a alienação de bens imóveis da Administração Pública direta, autárquica e fundacional dependerá de autorização legislativa, avaliação prévia e licitação na modalidade:",
    explicacao: "GABARITO: A. Art. 76, I, da Lei 14.133/2021: alienação de bens imóveis exige autorização legislativa para órgãos diretos, avaliação prévia e licitação na modalidade leilão.",
    alternativas: [
      { texto: "Leilão.", correta: true },
      { texto: "Pregão.", correta: false },
      { texto: "Concurso.", correta: false },
      { texto: "Diálogo competitivo.", correta: false },
      { texto: "Tomada de preços simplificada.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-02-017",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Em razão de sequelas decorrentes de confronto armado em operação policial, um policial sofreu limitação motora parcial e permanente, atestada em laudo conclusivo por junta médica oficial. Constatado que o servidor não se encontra totalmente incapacitado para o serviço público, a Administração providenciou sua investidura em cargo de atribuições e responsabilidades compatíveis com a limitação apresentada. Esse instituto de ajuste funcional denomina-se:",
    explicacao: "GABARITO: C. Art. 24 da Lei nº 8.112/90: 'Readaptação é a investidura do servidor em cargo de atribuições e responsabilidades compatíveis com a limitação que tenha sofrido em sua capacidade física ou mental verificada em inspeção médica.'",
    alternativas: [
      { texto: "Recondução.", correta: false },
      { texto: "Remoção de ofício.", correta: false },
      { texto: "Readaptação.", correta: true },
      { texto: "Redistribuição funcional.", correta: false },
      { texto: "Reintegração judicial.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-018",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Constitui ato de improbidade administrativa que causa lesão ao erário (Art. 10 da Lei nº 8.429/1992):",
    explicacao: "GABARITO: E. Art. 10, VIII, da Lei 8.429/92: 'frustrar a licitude de processo licitatório ou de processo seletivo para celebração de parcerias com entidades sem fins lucrativos, ou dispensá-los indevidamente, acarretando perda patrimonial efetiva'.",
    alternativas: [
      { texto: "Receber propina para omitir ato de ofício (enriquecimento ilícito - Art. 9º).", correta: false },
      { texto: "Usar bens públicos em proveito pessoal direto (enriquecimento ilícito - Art. 9º).", correta: false },
      { texto: "Aceitar emprego em empresa privada fiscalizada pelo órgão (enriquecimento ilícito - Art. 9º).", correta: false },
      { texto: "Recusar fé a documentos públicos sem dolo patrimonial (princípios - Art. 11).", correta: false },
      { texto: "Frustrar a licitude de processo licitatório ou dispensá-lo indevidamente, acarretando perda patrimonial efetiva ao erário.", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-019",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "De acordo com o Art. 75 da Lei nº 14.133/2021, a dispensa de licitação em razão do valor aplica-se para contratação que envolva valores inferiores aos limites legais atualizados. Na dispensa de licitação:",
    explicacao: "GABARITO: B. Na dispensa de licitação a competição é faticamente viável, mas a lei autoriza a Administração a não licitar por razões de conveniência, celeridade e custo-benefício (distinta da inexigibilidade, na qual a competição é inviável).",
    alternativas: [
      { texto: "A competição é absolutamente inviável por não haver mercado fornecedor.", correta: false },
      { texto: "A competição é viável, mas a lei faculta ou autoriza a não realização do certame formal com base em critérios de conveniência e custo operacional.", correta: true },
      { texto: "O gestor público pode contratar parentes até o segundo grau sem cotação de preços.", correta: false },
      { texto: "O contrato deve ser firmado exclusivamente com empresas estatais estrangeiras.", correta: false },
      { texto: "A publicação do extrato do contrato no Portal Nacional de Contratações Públicas (PNCP) é expressamente proibida.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-020",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O deslocamento do servidor público federal, no âmbito do mesmo quadro, com ou sem mudança de sede, por interesse da administração ou a pedido, denomina-se:",
    explicacao: "GABARITO: A. Art. 36 da Lei 8.112/90: Remoção.",
    alternativas: [
      { texto: "Remoção.", correta: true },
      { texto: "Redistribuição.", correta: false },
      { texto: "Recondução.", correta: false },
      { texto: "Transferência extinta.", correta: false },
      { texto: "Permuta compulsória.", correta: false },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-02-021",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos da Lei nº 8.429/1992, as sanções de improbidade administrativa aplicam-se àquele que:",
    explicacao: "GABARITO: D. Art. 1º, caput e § 6º, c/c Art. 2º da Lei 8.429/92: aplicam-se a agentes públicos (servidores, empregados públicos, agentes políticos) e a particulares que induzam ou concorram dolosamente para a prática do ato ímprobo.",
    alternativas: [
      { texto: "Apenas aos ocupantes de cargos vitalícios do Poder Judiciário.", correta: false },
      { texto: "Exclusivamente aos servidores federais concursados da União.", correta: false },
      { texto: "Somente às empresas estatais com ações negociadas em bolsa.", correta: false },
      { texto: "Aos agentes públicos de qualquer esfera ou Poder, bem como ao particular que induza ou concorra dolosamente para a prática do ato de improbidade.", correta: true },
      { texto: "Apenas a deputados e senadores em exercício de mandato legislativo.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-022",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São penalidades disciplinares expressamente previstas na Lei nº 8.112/1990:",
    explicacao: "GABARITO: C. Art. 127 da Lei 8.112/90: advertência, suspensão, demissão, cassação de aposentadoria ou disponibilidade, destituição de cargo em comissão e destituição de função comissionada.",
    alternativas: [
      { texto: "Prisão administrativa e confisco patrimonial.", correta: false },
      { texto: "Rebaixamento de cargo e transferência compulsória punitiva.", correta: false },
      { texto: "Advertência, suspensão, demissão, cassação de aposentadoria ou disponibilidade e destituição de cargo em comissão.", correta: true },
      { texto: "Multa pessoal de trânsito e cassação da CNH.", correta: false },
      { texto: "Trabalhos forçados e perda de direitos políticos municipais.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-02-023",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_14133,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Portal Nacional de Contratações Públicas (PNCP), instituído pela Lei nº 14.133/2021, constitui:",
    explicacao: "GABARITO: A. Art. 174 da Lei 14.133/2021: sítio eletrônico oficial centralizado para divulgação obrigatória dos atos e editais de licitações e contratos da administração direta, autárquica e fundacional.",
    alternativas: [
      { texto: "Sítio eletrônico oficial centralizado para divulgação obrigatória de todos os atos exigidos pela Lei de Licitações e Contratos.", correta: true },
      { texto: "Aplicativo privado de comércio exterior mantido por bancos de investimento.", correta: false },
      { texto: "Tribunal arbitral exclusivo para julgamento de disputas contratuais militares.", correta: false },
      { texto: "Sistema de pagamento de diárias a parlamentares estaduais.", correta: false },
      { texto: "Registro público de notas e títulos cartorários.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-02-024",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A acumulação remunerada de cargos públicos é vedada como regra pela CF/88 e pela Lei nº 8.112/1990. Ressalva-se a acumulação, quando houver compatibilidade de horários, de:",
    explicacao: "GABARITO: E. Art. 37, XVI, CF e Art. 118 da Lei 8.112/90: a) de dois cargos de professor; b) a de um cargo de professor com outro técnico ou científico; c) a de dois cargos ou empregos privativos de profissionais de saúde, com profissões regulamentadas.",
    alternativas: [
      { texto: "Dois cargos de delegado de polícia estadual.", correta: false },
      { texto: "Três cargos privativos de diplomata de carreira.", correta: false },
      { texto: "Dois cargos de policial rodoviário federal.", correta: false },
      { texto: "Quatro cargos comissionados municipais.", correta: false },
      { texto: "Dois cargos de professor, ou um cargo de professor com outro técnico ou científico, ou dois cargos/empregos privativos de profissionais de saúde.", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-02-025",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O acordo de não persecução civil (ANPC) na ação de improbidade administrativa, nos termos da Lei nº 8.429/1992:",
    explicacao: "GABARITO: B. Art. 17-B da Lei 8.429/92 (redação da Lei 14.230/2021): o Ministério Público poderá celebrar acordo de não persecução civil, desde que dele advenham ao menos o integral ressarcimento do dano e a reversão à pessoa jurídica lesada da vantagem indevida obtida.",
    alternativas: [
      { texto: "É expressamente proibido no direito brasileiro.", correta: false },
      { texto: "Pode ser celebrado pelo Ministério Público, exigindo no mínimo o ressarcimento integral do dano patrimonial e a perda da vantagem patrimonial indevida.", correta: true },
      { texto: "Depende de autorização unânime do plenário da Câmara de Vereadores.", correta: false },
      { texto: "Isenta o infrator de qualquer devolução financeira aos cofres públicos.", correta: false },
      { texto: "Só pode ser proposto por réus estrangeiros não residentes no país.", correta: false },
    ],
  },
];
