import { TAXONOMIA } from "./taxonomia.mjs";

export const transito02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-tran-02-001",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Dirigir veículo automotor na via pública sem a devida Permissão para Dirigir ou Habilitação, gerando perigo de dano, configura crime de trânsito punido com detenção de seis meses a um ano, ou multa.",
    explicacao: "GABARITO: CERTO. Art. 309 do CTB: Dirigir veículo automotor, em via pública, sem a devida Permissão para Dirigir ou Habilitação ou, ainda, se cassado o direito de dirigir, gerando perigo de dano: Penas - detenção, de seis meses a um ano, ou multa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-002",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de embriaguez ao volante (Art. 306 do CTB) é considerado de perigo concreto pelo Superior Tribunal de Justiça, sendo indispensável a demonstração de direção anormal ou perigosa na via pública para a consumação do delito.",
    explicacao: "GABARITO: ERRADO. Segundo a jurisprudência pacificada do STJ (Tema Repetitivo 484) e STF, o crime do art. 306 do CTB é de PERIGO ABSTRATO, consumando-se com a simples condução de veículo automotor com capacidade psicomotora alterada em razão de álcool ou outra substância psicoativa, dispensando-se a demonstração de direção anormal.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-tran-02-003",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Deixar o condutor envolvido em acidente com vítima de prestar ou providenciar imediato socorro à vítima, podendo fazê-lo, constitui infração de trânsito de natureza gravíssima sujeita à penalidade de multa multiplicada por cinco e suspensão do direito de dirigir.",
    explicacao: "GABARITO: CERTO. Art. 176, I, do CTB: Deixar o condutor envolvido em sinistro com vítima de prestar ou providenciar socorro constitui infração gravíssima com multa (cinco vezes) e suspensão do direito de dirigir.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-004",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de confiar ou entregar a direção de veículo automotor a pessoa não habilitada, com habilitação cassada ou com o direito de dirigir suspenso (Art. 310 do CTB) prescinde da ocorrência de resultado lesivo ou de perigo concreto de dano.",
    explicacao: "GABARITO: CERTO. Súmula 575 do STJ: 'Constitui crime de perigo abstrato a conduta de permitir, confiar ou entregar a direção de veículo automotor a pessoa não habilitada, com habilitação cassada ou com o direito de dirigir suspenso, para os fins do art. 310 do Código de Trânsito Brasileiro'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-005",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "No crime de homicídio culposo na direção de veículo automotor, a pena é aumentada de um terço à metade se o agente estiver conduzindo veículo de transporte de passageiros no exercício de sua profissão ou atividade.",
    explicacao: "GABARITO: CERTO. Art. 302, § 1º, IV, do CTB: No homicídio culposo cometido na direção de veículo automotor, a pena é aumentada de 1/3 à metade se o agente estiver conduzindo veículo de transporte de passageiros, no exercício de sua profissão ou atividade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-006",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O condutor que recusar submeter-se a qualquer dos procedimentos previstos para atestar a influência de álcool ou substância psicoativa no organismo não comete infração administrativa se não for flagrado cambaleante ou desorientado.",
    explicacao: "GABARITO: ERRADO. Art. 165-A do CTB: Recusar-se a ser submetido a teste, exame clínico, perícia ou outro procedimento que permita certificar influência de álcool ou substância psicoativa constitui infração autônoma gravíssima, com multa multiplicada por 10 e suspensão do direito de dirigir por 12 meses.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-tran-02-007",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Ao condutor de veículo nos crimes de trânsito de lesão corporal culposa e homicídio culposo não se imporá a prisão em flagrante nem se exigirá fiança se prestar pronto e integral socorro à vítima ou, não podendo fazê-lo pessoalmente, solicitar auxílio da autoridade pública.",
    explicacao: "GABARITO: CERTO. Art. 301 do CTB: Ao condutor de veículo, nos casos de sinistros de trânsito de que resulte vítima, não se imporá a prisão em flagrante, nem se exigirá fiança, se prestar pronto e integral socorro àquela, ou não podendo fazê-lo pessoalmente, solicitar auxílio da autoridade pública.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-008",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A penalidade de advertência por escrito poderá ser imposta a infrações de natureza leve ou média, passíveis de serem punidas com multa, caso o infrator não tenha cometido nenhuma outra infração nos últimos doze meses.",
    explicacao: "GABARITO: CERTO. Art. 267 do CTB: Deverá ser imposta a penalidade de advertência por escrito para as infrações de natureza leve ou média, puníveis com multa, caso o infrator não tenha cometido nenhuma outra infração nos últimos 12 (doze) meses.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-009",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A prática de 'racha' ou competição automobilística não autorizada na via pública que resulte em lesão corporal de natureza grave qualifica o crime, elevando a pena para reclusão de três a seis anos, sem prejuízo de outras sanções.",
    explicacao: "GABARITO: CERTO. Art. 308, § 1º, do CTB: Se da prática do crime de racha resultar lesão corporal de natureza grave, a pena privativa de liberdade é de reclusão de 3 a 6 anos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-010",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia Civil",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A inovação artificiosa em local de acidente automobilístico com vítima (Art. 312 do CTB) constitui crime formal de menor potencial ofensivo, punido com detenção de seis meses a um ano ou multa.",
    explicacao: "GABARITO: CERTO. Art. 312 do CTB: Inovar artificiosamente, em caso de sinistro automobilístico com vítima, na pendência do respectivo procedimento policial ou judicial, o estado de lugar, de coisa ou de pessoa: Penas - detenção, de seis meses a um ano, ou multa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-tran-02-011",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com o sistema de pontuação de infrações do Código de Trânsito Brasileiro (Art. 259), a pontuação atribuída às infrações de natureza leve, média, grave e gravíssima é, respectivamente, de:",
    explicacao: "GABARITO: C. Art. 259 do CTB: I - gravíssima: 7 pontos; II - grave: 5 pontos; III - média: 4 pontos; IV - leve: 3 pontos. Portanto, na ordem leve, média, grave e gravíssima: 3, 4, 5 e 7 pontos.",
    alternativas: [
      { texto: "2, 4, 6 e 8 pontos.", correta: false },
      { texto: "3, 5, 7 e 9 pontos.", correta: false },
      { texto: "3, 4, 5 e 7 pontos.", correta: true },
      { texto: "1, 3, 5 e 7 pontos.", correta: false },
      { texto: "4, 5, 6 e 7 pontos.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-012",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "João conduzia veículo automotor com capacidade psicomotora alterada em razão de influência alcoólica e acabou atropelando e matando um pedestre que atravessava a faixa. Comprovada a ausência de intenção homicida direta, João responderá por homicídio culposo na direção de veículo qualificado pela embriaguez (Art. 302, § 3º, do CTB), cuja pena cominada em abstrato é de:",
    explicacao: "GABARITO: B. Art. 302, § 3º, do CTB: Se o agente conduz veículo automotor sob a influência de álcool ou de qualquer outra substância psicoativa que determine dependência: Penas - reclusão, de cinco a oito anos, e suspensão ou proibição do direito de se obter a permissão ou a habilitação para dirigir veículo automotor.",
    alternativas: [
      { texto: "Detenção, de 2 a 4 anos.", correta: false },
      { texto: "Reclusão, de 5 a 8 anos.", correta: true },
      { texto: "Reclusão, de 6 a 20 anos.", correta: false },
      { texto: "Detenção, de 4 a 8 anos.", correta: false },
      { texto: "Reclusão, de 2 a 5 anos.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-013",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A suspensão do direito de dirigir é uma penalidade administrativa aplicada por autoridade executiva de trânsito. Segundo o Art. 261 do CTB, o condutor que exerce atividade remunerada ao veículo (EAR) terá o processo de suspensão instaurado quando atingir o limite fixo de:",
    explicacao: "GABARITO: E. Art. 261, § 5º, do CTB: No caso do condutor que exerce atividade remunerada em veículo, a penalidade de suspensão será instaurada quando o infrator atingir o limite de 40 (quarenta) pontos, independentemente da natureza das infrações cometidas.",
    alternativas: [
      { texto: "20 pontos, com duas infrações gravíssimas.", correta: false },
      { texto: "30 pontos, com uma infração gravíssima.", correta: false },
      { texto: "35 pontos, com infrações graves.", correta: false },
      { texto: "50 pontos, após curso de reciclagem.", correta: false },
      { texto: "40 pontos, independentemente da gravidade das infrações.", correta: true },
    ],
  },
  {
    idSlug: "b9-tran-02-014",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de fuga do local do acidente (Art. 305 do CTB) consiste em afastar-se o condutor do veículo do local do sinistro para fugir à responsabilidade penal ou civil que lhe possa ser atribuída. Sobre esse tipo penal, o Plenário do Supremo Tribunal Federal (STF no RE 971.608/RG) fixou a tese de que:",
    explicacao: "GABARITO: D. No RE 971.608/RG (Tema 907), o STF declarou a CONSTITUCIONALIDADE do art. 305 do CTB, afirmando que a regra não viola o princípio da não autoincriminação (nemo tenetur se detegere), tutelando a administração da justiça e a identificação dos envolvidos.",
    alternativas: [
      { texto: "O tipo penal é inconstitucional por violar a garantia da ampla defesa.", correta: false },
      { texto: "A norma foi revogada tacitamente pelo Pacto de San José da Costa Rica.", correta: false },
      { texto: "Aplica-se somente aos casos de sinistros sem vítimas fatais.", correta: false },
      { texto: "O Art. 305 do CTB é constitucional e não ofende a garantia da não autoincriminação.", correta: true },
      { texto: "Trata-se de infração meramente civil, sem repercussão na esfera criminal.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-015",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o CTB, constitui medida administrativa a ser adotada pelo agente da autoridade de trânsito:",
    explicacao: "GABARITO: A. Art. 269 do CTB: São medidas administrativas: retenção do veículo, remoção do veículo, recolhimento da CNH/CRLV, transbordo do excesso de carga, teste de alcoolemia, etc. Advertência por escrito, multa e suspensão são PENALIDADES (Art. 256).",
    alternativas: [
      { texto: "A remoção do veículo.", correta: true },
      { texto: "A aplicação de multa pecuniária.", correta: false },
      { texto: "A advertência por escrito.", correta: false },
      { texto: "A cassação da Carteira Nacional de Habilitação.", correta: false },
      { texto: "A frequência obrigatória em curso de reciclagem.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-016",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O crime de violação da suspensão ou da proibição de se obter a permissão ou a habilitação para dirigir veículo automotor (Art. 307 do CTB) prevê ainda, como efeito administrativo automático:",
    explicacao: "GABARITO: C. Art. 307, parágrafo único, do CTB: Nas mesmas penas incorre o condenado que deixa de entregar a habilitação. A autoridade judicial imporá nova cassação ou nova suspensão pelo mesmo prazo.",
    alternativas: [
      { texto: "A perda definitiva de todos os veículos de sua propriedade.", correta: false },
      { texto: "A conversão compulsória da pena privativa de liberdade em multa triplicada.", correta: false },
      { texto: "A imposição de nova penalidade de suspensão ou cassação pelo mesmo prazo.", correta: true },
      { texto: "O cancelamento do registro de pessoa física (CPF) junto aos órgãos fiscais.", correta: false },
      { texto: "A apreensão do veículo em leilão sumário após 24 horas.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-tran-02-017",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Transitar em velocidade superior à máxima permitida para o local em mais de 50% (cinquenta por cento) constitui infração:",
    explicacao: "GABARITO: D. Art. 218, III, do CTB: Transitar em velocidade superior à máxima permitida em mais de 50% é infração gravíssima, punida com multa (três vezes) e suspensão imediata do direito de dirigir.",
    alternativas: [
      { texto: "Leve, sujeita a advertência verbal.", correta: false },
      { texto: "Média, com acréscimo de quatro pontos.", correta: false },
      { texto: "Grave, com retenção do veículo até regularização.", correta: false },
      { texto: "Gravíssima, com penalidade de multa multiplicada por 3 e suspensão do direito de dirigir.", correta: true },
      { texto: "Administrativa atípica, dependente de termo de ajustamento de conduta.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-018",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos crimes cometidos na direção de veículos automotores, são circunstâncias que sempre agravam a penalidade quando não constituem ou qualificam o crime:",
    explicacao: "GABARITO: B. Art. 298 do CTB: São circunstâncias que agravam a penalidade: com dano potencial para duas ou mais pessoas; utilizando veículo sem placas ou falsificadas; sem permissão ou habilitação; quando a profissão exigir cuidados especiais com transporte; etc.",
    alternativas: [
      { texto: "Ter o agente confessado espontaneamente a autoria do fato em juízo.", correta: false },
      { texto: "Ter o condutor praticado o fato com dano potencial para duas ou mais pessoas ou com grande risco para a coletividade.", correta: true },
      { texto: "Conduzir veículo próprio devidamente licenciado e com revisões em dia.", correta: false },
      { texto: "Estar o agente acompanhado de passageiro portador de título eleitoral regular.", correta: false },
      { texto: "Trafegar em velocidade compatível com a sinalização semafórica.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-019",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Estacionar o veículo sobre a faixa de pedestres, ciclovia ou ciclofaixa constitui infração de trânsito de natureza:",
    explicacao: "GABARITO: C. Art. 181, VIII, do CTB: Estacionar no passeio ou sobre faixa destinada a pedestre, sobre ciclovia ou ciclofaixa é infração grave, com penalidade de multa e medida administrativa de remoção do veículo.",
    alternativas: [
      { texto: "Leve.", correta: false },
      { texto: "Média.", correta: false },
      { texto: "Grave.", correta: true },
      { texto: "Gravíssima.", correta: false },
      { texto: "Infracional de mera advertência.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-020",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia Civil",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito da ação penal nos crimes de trânsito de lesão corporal culposa (Art. 303 do CTB), assinale a afirmativa correta:",
    explicacao: "GABARITO: A. Art. 291, § 1º, do CTB: Aplica-se a Lei 9.099/95 (exigência de representação) aos crimes de lesão culposa no trânsito, SALVO se o agente estiver sob influência de álcool/droga, participando de racha ou em velocidade superior a 50 km/h do limite da via (casos em que a ação torna-se pública incondicionada).",
    alternativas: [
      { texto: "A ação penal é pública incondicionada se o agente estiver sob a influência de álcool ou praticando racha.", correta: true },
      { texto: "A ação penal é privada em todas as hipóteses por envolver interesse patrimonial direto.", correta: false },
      { texto: "Depende de representação da vítima mesmo quando o motorista estiver comprovadamente embriagado.", correta: false },
      { texto: "Exige queixa-crime subsidiária proposta pelo Ministério Público Estadual.", correta: false },
      { texto: "É incondicionada apenas nos casos de lesão corporal levíssima sem perícia médica.", correta: false },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-tran-02-021",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Conduzir veículo automotor sem possuir os equipamentos obrigatórios ou com equipamentos ineficientes ou inoperantes é infração de natureza:",
    explicacao: "GABARITO: B. Art. 230, IX, do CTB: Conduzir veículo sem equipamento obrigatório ou estando este ineficiente ou inoperante constitui infração grave com multa e retenção do veículo para regularização.",
    alternativas: [
      { texto: "Leve.", correta: false },
      { texto: "Grave.", correta: true },
      { texto: "Média.", correta: false },
      { texto: "Gravíssima.", correta: false },
      { texto: "Atípica administrativamente.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-022",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "De acordo com o Art. 256 do CTB, a autoridade de trânsito, na esfera das competências estabelecidas neste Código e dentro de sua circunscrição, deverá aplicar as seguintes penalidades, EXCETO:",
    explicacao: "GABARITO: E. Art. 256 do CTB elenca: advertência por escrito, multa, suspensão do direito de dirigir, cassação da CNH/Permissão e frequência em curso de reciclagem. Prisão administrativa não é penalidade de trânsito.",
    alternativas: [
      { texto: "Advertência por escrito.", correta: false },
      { texto: "Multa.", correta: false },
      { texto: "Suspensão do direito de dirigir.", correta: false },
      { texto: "Cassação da Carteira Nacional de Habilitação.", correta: false },
      { texto: "Prisão administrativa em estabelecimento penal.", correta: true },
    ],
  },
  {
    idSlug: "b9-tran-02-023",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Constitui crime de trânsito previsto no Art. 311 do CTB:",
    explicacao: "GABARITO: D. Art. 311 do CTB: Trafegar em velocidade incompatível com a segurança nas proximidades de escolas, hospitais, estações de embarque e desembarque de passageiros, logradouros estreitos, ou onde haja grande movimentação ou concentração de pessoas, gerando perigo de dano: Penas - detenção, de seis meses a um ano, ou multa.",
    alternativas: [
      { texto: "Deixar de sinalizar a via quando o veículo estiver imobilizado no leito carroçável.", correta: false },
      { texto: "Ultrapassar veículo pelo acostamento em trecho de aclive sem visibilidade.", correta: false },
      { texto: "Transitar na contramão de direção em vias com sinalização de sentido único.", correta: false },
      { texto: "Trafegar em velocidade incompatível com a segurança nas proximidades de escolas, hospitais ou estações de passageiros, gerando perigo de dano.", correta: true },
      { texto: "Conduzir veículo de passageiros sem a realização da inspeção técnica periódica semestral.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-tran-02-024",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A utilização de aparelho celular pelo condutor, segurando-o ou manuseando-o enquanto dirige veículo automotor, constitui infração de trânsito:",
    explicacao: "GABARITO: A. Art. 252, parágrafo único, do CTB: A hipótese de segurar ou manusear telefone celular enquanto dirige caracteriza infração gravíssima com imposição de multa de 7 pontos.",
    alternativas: [
      { texto: "Gravíssima.", correta: true },
      { texto: "Grave.", correta: false },
      { texto: "Média.", correta: false },
      { texto: "Leve.", correta: false },
      { texto: "Mera inobservância de norma administrativa sem pontuação.", correta: false },
    ],
  },
  {
    idSlug: "b9-tran-02-025",
    disciplina_id: TAXONOMIA.disciplinas.transito,
    assunto_id: TAXONOMIA.assuntos.ctb_crimes_infracoes,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do Art. 304 do CTB, deixar o condutor do veículo, na ocasião do acidente, de prestar imediato socorro à vítima, ou, não podendo fazê-lo diretamente, por justa causa, deixar de solicitar auxílio da autoridade pública, tipifica crime que:",
    explicacao: "GABARITO: C. Art. 304, parágrafo único, do CTB: Incide nas penas deste artigo o condutor do veículo, ainda que a sua omissão seja suprida por terceiros ou que se trate de vítima com morte instantânea ou com ferimentos leves.",
    alternativas: [
      { texto: "Fica extinto caso transeuntes prestem assistência médica antes da chegada da polícia.", correta: false },
      { texto: "Não se configura se a vítima sofrer morte instantânea atestada em juízo.", correta: false },
      { texto: "Incide nas penas cominadas ainda que sua omissão seja suprida por terceiros ou que se trate de vítima com morte instantânea.", correta: true },
      { texto: "Exige dolo de matar para a caracterização do tipo de trânsito em comento.", correta: false },
      { texto: "Depende de perícia técnica conclusiva sobre a culpabilidade exclusiva no choque mecânico.", correta: false },
    ],
  },
];
