import { TAXONOMIA } from "./taxonomia.mjs";

export const adm01Questoes = [
  {
    idSlug: "adm-001",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O Poder de Polícia, conceituado pelo art. 78 do Código Tributário Nacional e amplamente densificado pela doutrina administrativa, caracteriza-se por atributos específicos. A autoexecutoriedade, como atributo do poder de polícia:",
    explicacao: "GABARITO: B. A autoexecutoriedade consiste na prerrogativa da Administração Pública de executar diretamente seus atos materiais sem necessidade de prévia autorização judicial, estando presente quando expressamente prevista em lei ou em situações fáticas de urgência (ex.: interdição cautelar de estabelecimento em chamas ou apreensão de alimentos estragados). Nem todos os atos de polícia são autoexecutórios (a cobrança de multa exige execução fiscal).",
    alternativas: [
      { letra: "A", texto: "está presente de forma irrestrita em absolutamente todos os atos de polícia, inclusive na cobrança direta forçada de multas pecuniárias sem ação de execução.", correta: false },
      { letra: "B", texto: "permite à Administração executar diretamente suas medidas materiais sem prévia autorização judicial, estando presente quando expressa em lei ou diante de situações urgentes de salvaguarda do interesse público.", correta: true },
      { letra: "C", texto: "impede qualquer controle judicial a posteriori sobre a proporcionalidade da medida policial adotada.", correta: false },
      { letra: "D", texto: "depende sempre de homologação prévia da Câmara de Vereadores ou da Assembleia Legislativa.", correta: false },
      { letra: "E", texto: "aplica-se unicamente aos atos de polícia disciplinar interna em face de servidores concursados.", correta: false }
    ]
  },
  {
    idSlug: "adm-002",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O ciclo de polícia é tradicionalmente decomposto pela doutrina em quatro fases: ordem de polícia (legislação), consentimento de polícia (licença/autorização), fiscalização de polícia e sanção de polícia. A sanção de polícia e a fiscalização de polícia podem ser exercidas por guardas municipais no âmbito da segurança viária e proteção de bens municipais.",
    explicacao: "GABARITO: CERTO. STF (RE 658.570/MG - Tema 532 e ADPF 995): As guardas municipais possuem competência para fiscalizar o trânsito e aplicar sanções administrativas de trânsito, integrando o ciclo de polícia administrativa.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-003",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito da responsabilidade civil do Estado pela morte ou suicídio de detento em estabelecimento prisional, o Supremo Tribunal Federal, em sede de repercussão geral (Tema 592, RE 841.526/RS), fixou a seguinte tese:",
    explicacao: "GABARITO: C. STF (RE 841.526/RS - Tema 592): 'Em caso de inobservância do seu dever específico de proteção previsto no art. 5º, XLIX, da CF/88, o Estado é responsável pela morte de detento. A responsabilidade é objetiva, mas o nexo de causalidade pode ser rompido caso o Estado comprove que a morte não poderia ser evitada mesmo com o cumprimento de todas as cautelas exigíveis.'",
    alternativas: [
      { letra: "A", texto: "o Estado responde de forma subjetiva, exigindo-se que a família da vítima comprove o dolo direto do diretor do presídio.", correta: false },
      { letra: "B", texto: "aplica-se a teoria do risco integral, sendo absolutamente vedado ao Estado alegar qualquer causa excludente de nexo de causalidade.", correta: false },
      { letra: "C", texto: "em caso de inobservância do seu dever específico de proteção (art. 5º, XLIX, CF), o Estado responde objetivamente pela morte do custodiado, cabendo-lhe comprovar que a morte não poderia ser evitada para romper o nexo causal.", correta: true },
      { letra: "D", texto: "o Estado é isento de qualquer responsabilidade civil em caso de rebelião ou motim carcerário.", correta: false },
      { letra: "E", texto: "a indenização só é devida se houver prévia condenação criminal do policial penal responsável pela guarda.", correta: false }
    ]
  },
  {
    idSlug: "adm-004",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Segundo a jurisprudência pacífica do STF e do STJ, a ação indenizatória por danos causados por agente público (policial militar em serviço) deve ser ajuizada diretamente contra o Estado ou a pessoa jurídica de direito público, sendo vedado o ajuizamento da ação diretamente contra o servidor (Teoria da Dupla Garantia / Tema 940 do STF), ressalvado o direito de regresso em caso de culpa ou dolo.",
    explicacao: "GABARITO: CERTO. STF (Tema 940 / RE 1.027.633): A ação por danos causados por agente público deve ser proposta contra o Estado ou a concessionária, vedada a propositura direta contra o agente ou a formação de litisconsórcio passivo facultativo originário com ele.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-005",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Sobre a extinção dos atos administrativos, a anulação e a revogação diferenciam-se essencialmente pelo motivo e pelos efeitos temporais gerados. A anulação de um ato administrativo:",
    explicacao: "GABARITO: A. A anulação decorre de vício de legalidade/legitimidade, pode ser praticada pela própria Administração (autotutela - Súmulas 346 e 473 do STF) ou pelo Poder Judiciário, e opera efeitos retroativos (ex tunc). Já a revogação funda-se em mérito (conveniência e oportunidade), é privativa da Administração e opera efeitos prospectivos (ex nunc).",
    alternativas: [
      { letra: "A", texto: "funda-se em vício de ilegalidade, pode ser realizada pela Administração ou pelo Judiciário e produz efeitos retroativos (ex tunc).", correta: true },
      { letra: "B", texto: "funda-se em critérios de conveniência e oportunidade e gera sempre efeitos prospectivos (ex nunc).", correta: false },
      { letra: "C", texto: "é privativa do Poder Judiciário, sendo vedado à autoridade administrativa anular seus próprios atos.", correta: false },
      { letra: "D", texto: "pode recair sobre atos que já exauriram plenamente todos os seus efeitos materiais.", correta: false },
      { letra: "E", texto: "gera direito subjetivo automático de indenização a quem praticou a fraude originária.", correta: false }
    ]
  },
  {
    idSlug: "adm-006",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A teoria dos motivos determinantes preceitua que a validade do ato administrativo fica vinculada aos motivos fáticos e jurídicos explicitados pela autoridade ao praticá-lo; assim, se tais motivos forem comprovadamente falsos ou inexistentes, o ato é nulo, ainda que se trate de ato originalmente discricionário.",
    explicacao: "GABARITO: CERTO. Teoria dos Motivos Determinantes: Uma vez declarados os motivos pela autoridade, a validade do ato subordina-se à veracidade e legalidade desses motivos.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-007",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Com as alterações substanciais introduzidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa (Lei nº 8.429/1992), a caracterização dos atos de improbidade administrativa passou a exigir:",
    explicacao: "GABARITO: D. Lei 8.429/1992 (com redação da Lei 14.230/2021, art. 1º, §§ 1º e 2º): A nova legislação revogou a modalidade culposa em todas as figuras de improbidade (inclusive dano ao erário do art. 10), exigindo dolo específico caracterizado pela vontade livre e consciente de alcançar o resultado ilícito tipificado nos arts. 9º, 10 e 11.",
    alternativas: [
      { letra: "A", texto: "comprovação de culpa grave apenas nas hipóteses de violação a princípios da administração pública.", correta: false },
      { letra: "B", texto: "responsabilização objetiva quando o ato for praticado por autoridade policial de carreira.", correta: false },
      { letra: "C", texto: "culpa simples em caso de lesão culposa ao erário decorrente de imprudência na condução de viatura.", correta: false },
      { letra: "D", texto: "a comprovação do dolo específico (vontade livre e consciente de alcançar o resultado ilícito) em todas as modalidades (enriquecimento ilícito, dano ao erário e princípios), restando eliminada a modalidade culposa.", correta: true },
      { letra: "E", texto: "apenas a constatação objetiva de dano financeiro, independentemente de elemento subjetivo.", correta: false }
    ]
  },
  {
    idSlug: "adm-008",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal, ao julgar o Tema 1199 da Repercussão Geral (ARE 843.989/PR), decidiu que a revogação da modalidade culposa do ato de improbidade administrativa introduzida pela Lei nº 14.230/2021 aplica-se aos atos praticados na vigência da lei anterior sem condenação transitada em julgado, mas não produz efeitos rescisórios sobre decisões com trânsito em julgado.",
    explicacao: "GABARITO: CERTO. STF (Tema 1199 / ARE 843.989/PR): A nova lei retroage para beneficiar réus em ações de improbidade por ato culposo em curso (sem trânsito em julgado), sendo mantida a intangibilidade da coisa julgada.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-009",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito da independência entre as instâncias administrativa e penal e a repercussão da sentença criminal no Processo Administrativo Disciplinar (PAD), é correto afirmar que:",
    explicacao: "GABARITO: C. Art. 126 da Lei 8.112/1990 e art. 66 do CPP: A regra geral é a incomunicabilidade das instâncias. Contudo, a absolvição criminal proferida com fundamento na comprovação inequívoca da inexistência material do fato ou na negativa cabal de autoria vincula a Administração e impede a punição disciplinar pelo mesmo fato.",
    alternativas: [
      { letra: "A", texto: "a absolvição penal por insuficiência de provas vincula a esfera administrativa e obriga a anulação da demissão.", correta: false },
      { letra: "B", texto: "a condenação criminal irrecorrível não produz qualquer efeito sobre o cargo público do policial.", correta: false },
      { letra: "C", texto: "a sentença criminal que absolve o servidor com base na inequívoca inexistência do fato ou na negativa de autoria vincula a esfera administrativa e impede a sanção disciplinar.", correta: true },
      { letra: "D", texto: "o arquivamento de inquérito policial por prescrição penal extingue compulsoriamente o PAD disciplinar.", correta: false },
      { letra: "E", texto: "a autoridade administrativa não pode instaurar PAD antes do oferecimento da denúncia pelo MP.", correta: false }
    ]
  },
  {
    idSlug: "adm-010",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos da Súmula Vinculante nº 5 do Supremo Tribunal Federal, a falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição Federal.",
    explicacao: "GABARITO: CERTO. Súmula Vinculante nº 5 do STF: 'A falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-011",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Súmula Vinculante nº 13 do Supremo Tribunal Federal veda a prática do nepotismo na Administração Pública direta e indireta. Conforme a jurisprudência consolidada do STF, a vedação ao nepotismo:",
    explicacao: "GABARITO: B. STF (Súmula Vinculante 13 e Rcl 29.033): A nomeação de parentes para cargos estritamente políticos (Ministros de Estado, Secretários Estaduais/Municipais) não viola, em regra, a Súmula Vinculante 13, salvo hipótese de manifesta ausência de qualificação técnica ou evidente fraude à lei (nepotismo cruzado). Para cargos em comissão puramente administrativos, a vedação é absoluta até 3º grau.",
    alternativas: [
      { letra: "A", texto: "aplica-se apenas aos parentes em linha reta até o 1º grau (pais e filhos).", correta: false },
      { letra: "B", texto: "alcança cargos comissionados e de confiança administrativos até o 3º grau de parentesco, ressalvados, em regra, os cargos de natureza genuinamente política (como Secretários de Estado/Município), desde que ausente fraude ou manifesta inaptidão.", correta: true },
      { letra: "C", texto: "não se aplica aos órgãos do Poder Legislativo municipal.", correta: false },
      { letra: "D", texto: "proíbe que parentes prestem concurso público para o mesmo órgão.", correta: false },
      { letra: "E", texto: "depende de lei ordinária municipal específica para ter eficácia em cada cidade.", correta: false }
    ]
  },
  {
    idSlug: "adm-012",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O excesso de poder ocorre quando o agente público atua fora dos limites de sua competência legal, enquanto o desvio de poder (ou desvio de finalidade) se configura quando o agente atua dentro de sua competência, mas visando a uma finalidade diversa do interesse público ou daquela prevista na lei.",
    explicacao: "GABARITO: CERTO. Excesso de poder (vício na competência) e desvio de finalidade (vício na finalidade) são as duas espécies clássicas do gênero abuso de poder.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-013",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Corpo de Bombeiros",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "São elementos constitutivos (ou requisitos de validade) indispensáveis de todo e qualquer ato administrativo:",
    explicacao: "GABARITO: A. Elementos/requisitos do ato administrativo (mnemônico CO-FI-FO-M-OB): Competência, Finalidade, Forma, Motivo e Objeto (art. 2º da Lei da Ação Popular - Lei nº 4.717/1965).",
    alternativas: [
      { letra: "A", texto: "Competência, Finalidade, Forma, Motivo e Objeto.", correta: true },
      { letra: "B", texto: "Imperatividade, Presunção de Legitimidade e Tipicidade.", correta: false },
      { letra: "C", texto: "Discricionariedade, Eficácia, Executoriedade e Validade.", correta: false },
      { letra: "D", texto: "Doutrina, Jurisprudência, Costume e Analogia.", correta: false },
      { letra: "E", texto: "Publicidade, Rentabilidade, Lucratividade e Autonomia.", correta: false }
    ]
  },
  {
    idSlug: "adm-014",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A convalidação de ato administrativo é cabível quando houver vícios sanáveis que não acarretem lesão ao interesse público nem prejuízo a terceiros, recaindo tipicamente sobre vícios de competência (em razão da pessoa, desde que não exclusiva) e vícios de forma (desde que a forma não seja essencial à validade do ato).",
    explicacao: "GABARITO: CERTO. Art. 55 da Lei 9.784/1999: Convalidação é o suprimento de defeitos sanáveis em atos administrativos com vícios leves de competência e forma.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-015",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Durante perseguição policial em via pública, agentes da Polícia Militar efetuaram disparos de arma de fogo contra veículo ocupado por criminosos armados. Um dos projéteis ricocheteou e atingiu fatalmente um transeunte que caminhava na calçada. À luz da teoria da responsabilidade civil extracontratual do Estado adotada no art. 37, § 6º, da CF/88:",
    explicacao: "GABARITO: D. Trata-se de conduta comissiva lícita de agentes estatais que causou dano especial e anormal a terceiro inocente. O Estado responde de forma objetiva (Teoria do Risco Administrativo), bastando a comprovação da conduta, do dano e do nexo de causalidade, não se admitindo falar em culpa exclusiva da vítima ou fortuito para elidir a indenização devida aos herdeiros do transeunte.",
    alternativas: [
      { letra: "A", texto: "o Estado não responde civilmente porque a atuação policial visava à legítima defesa de terceiros.", correta: false },
      { letra: "B", texto: "a responsabilidade do Estado depende da demonstração de negligência ou imperícia na perícia balística.", correta: false },
      { letra: "C", texto: "a indenização deve ser cobrada unicamente dos assaltantes em fuga em ação penal privada.", correta: false },
      { letra: "D", texto: "o Estado responde objetivamente pelos danos patrimoniais e morais causados à família da vítima, fundada no risco administrativo da atividade estatal comissiva.", correta: true },
      { letra: "E", texto: "trata-se de caso fortuito absoluto que rompe integralmente o nexo causal com o Estado.", correta: false }
    ]
  },
  {
    idSlug: "adm-016",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O poder regulamentar (ou poder normativo) é a prerrogativa conferida aos Chefes do Poder Executivo para expedir decretos e regulamentos destinados à fiel execução das leis, não podendo inovar originariamente na ordem jurídica criando obrigações ou deveres sem amparo em lei formal.",
    explicacao: "GABARITO: CERTO. Art. 84, IV, da CF/88: O poder regulamentar é de índole secundária (intra legem), sendo vedada a inovação primária autônoma, ressalvadas as hipóteses restritas de decreto autônomo do art. 84, VI.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-017",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do regime jurídico dos servidores públicos civis (Lei nº 8.112/1990), o retorno do servidor estável ao cargo anteriormente ocupado, decorrente de inabilitação em estágio probatório relativo a outro cargo ou de reintegração do anterior ocupante, denomina-se:",
    explicacao: "GABARITO: B. Lei 8.112/1990, art. 29: 'Recondução é o retorno do servidor estável ao cargo anteriormente ocupado e decorrerá de: I - inabilitação em estágio probatório relativo a outro cargo; II - reintegração do anterior ocupante.'",
    alternativas: [
      { letra: "A", texto: "Readaptação.", correta: false },
      { letra: "B", texto: "Recondução.", correta: true },
      { letra: "C", texto: "Reversão.", correta: false },
      { letra: "D", texto: "Aproveitamento.", correta: false },
      { letra: "E", texto: "Reintegração.", correta: false }
    ]
  },
  {
    idSlug: "adm-018",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal Federal",
    cargo_nome: "Policial Penal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Considere que um servidor policial estável, em decorrência da extinção do seu órgão de lotação, tenha sido posto em disponibilidade com remuneração proporcional ao tempo de contribuição. Nessa situação, o retorno compulsório do servidor em disponibilidade à atividade pública em cargo de atribuições e vencimentos compatíveis denomina-se aproveitamento, ensejando a cassação da disponibilidade caso o servidor não entre em exercício no prazo legal, salvo motivo de força maior devidamente comprovado.",
    explicacao: "GABARITO: CERTO. Art. 30 a 32 da Lei nº 8.112/1990: O retorno à atividade de servidor em disponibilidade é o aproveitamento. O art. 32 determina que será cassada a disponibilidade se o servidor não entrar em exercício no prazo legal, ressalvada a hipótese de doença comprovada por junta médica oficial.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-019",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O princípio da autotutela administrativa consagra o poder-dever da Administração Pública de controlar seus próprios atos. Esse princípio está consagrado nas Súmulas 346 e 473 do STF no sentido de que:",
    explicacao: "GABARITO: A. Súmula 473 do STF: 'A administração pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos; ou revogá-los, por motivo de conveniência ou oportunidade, respeitados os direitos adquiridos, e ressalvada, em todos os casos, a apreciação judicial.'",
    alternativas: [
      { letra: "A", texto: "a Administração pode anular seus próprios atos quando ilegais e revogá-los por conveniência e oportunidade, ressalvados direitos adquiridos e controle judicial.", correta: true },
      { letra: "B", texto: "a Administração só pode rever atos mediante decisão prévia e unânime do Tribunal de Contas.", correta: false },
      { letra: "C", texto: "os atos administrativos são imutáveis e jamais podem ser desfeitos pela própria autoridade emissora.", correta: false },
      { letra: "D", texto: "a autotutela autoriza o confisco de bens privados sem contraditório prévio.", correta: false },
      { letra: "E", texto: "o Judiciário é impedido de apreciar qualquer anulação efetuada pela Administração.", correta: false }
    ]
  },
  {
    idSlug: "adm-020",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 23 da Lei nº 8.429/1992 (com redação da Lei nº 14.230/2021), a ação para a aplicação das sanções por ato de improbidade administrativa prescreve em 8 (oito) anos, contados a partir da data da ocorrência do fato ou, no caso de infrações permanentes, do dia em que tiver cessado a permanência.",
    explicacao: "GABARITO: CERTO. Art. 23 da Lei 8.429/1992 (Lei 14.230/2021): Fixou o prazo prescricional geral e unificado de 8 anos.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-021",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O Poder Hierárquico confere à Administração Pública as prerrogativas de ordenar, fiscalizar, delegar e avocar atribuições no âmbito interno da estrutura funcional. Sobre a hierarquia administrativa:",
    explicacao: "GABARITO: C. Não há hierarquia entre o Poder Executivo e o Poder Judiciário, nem entre a Administração Direta e as pessoas da Administração Indireta (autarquias/fundações há apenas vinculação/tutela ministerial), nem nas funções estritamente jurisdicionais dos juízes.",
    alternativas: [
      { letra: "A", texto: "existe relação de subordinação hierárquica entre o Ministério Público e o Comandante-Geral da PM.", correta: false },
      { letra: "B", texto: "há hierarquia entre a União e os Municípios para fins disciplinares de segurança.", correta: false },
      { letra: "C", texto: "a hierarquia é típica da função administrativa e interna aos órgãos da mesma pessoa jurídica, não existindo subordinação entre a Administração Direta e Indireta (onde há apenas vinculação ou tutela).", correta: true },
      { letra: "D", texto: "permite ao superior determinar a prática de crimes ao subordinado sem que este possa questionar.", correta: false },
      { letra: "E", texto: "impede a delegação de qualquer competência decisória na esfera pública.", correta: false }
    ]
  },
  {
    idSlug: "adm-022",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A presunção de legitimidade e veracidade dos atos administrativos é um atributo juris tantum (relativo), o que significa que o ato é considerado emitido conforme a lei e com fatos verdadeiros até que o administrado prove o contrário, operando inversão do ônus da prova.",
    explicacao: "GABARITO: CERTO. A presunção de legitimidade milita em favor da Administração, cabendo ao particular comprovar eventual ilegalidade ou falsidade do ato.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-023",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal, ao fixar tese no Tema 362 da Repercussão Geral (RE 599.628/SP), analisou a responsabilidade civil do Estado decorrente de danos causados a terceiros por preso foragido. O STF estabeleceu que:",
    explicacao: "GABARITO: B. STF (RE 599.628/SP - Tema 362): 'Nos termos do art. 37, § 6º, da CF/88, não se caracteriza a responsabilidade civil objetiva do Estado por danos decorrentes de crime praticado por pessoa foragida do sistema prisional, quando não demonstrado o nexo causal direto entre o momento da fuga e a conduta delituosa praticada.' (Se o crime ocorre meses ou anos após a fuga, rompe-se o nexo causal direto).",
    alternativas: [
      { letra: "A", texto: "o Estado responde objetivamente por todos os crimes praticados pelo foragido até o fim de sua vida.", correta: false },
      { letra: "B", texto: "não se caracteriza a responsabilidade civil objetiva do Estado quando não restar demonstrado o nexo causal direto e imediato entre o momento da fuga e a conduta criminosa praticada.", correta: true },
      { letra: "C", texto: "a família do foragido deve arcar integralmente com as indenizações cíveis.", correta: false },
      { letra: "D", texto: "o policial penal de plantão no dia da fuga responde de forma objetiva e solidária com o criminoso.", correta: false },
      { letra: "E", texto: "o Estado é sempre isento de responsabilidade em caso de evasão prisional.", correta: false }
    ]
  },
  {
    idSlug: "adm-024",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos da jurisprudência consolidada dos Tribunais Superiores, a demissão ou exclusão a bem da disciplina de servidor público ou militar exige a observância prévia e obrigatória do contraditório e da ampla defesa em processo administrativo formal.",
    explicacao: "GABARITO: CERTO. Súmula Vinculante nº 21 do STF e art. 5º, LV, da CF/88: É nula a demissão/exclusão sem processo administrativo em que sejam assegurados o contraditório e a ampla defesa.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-025",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O art. 37, caput, da Constituição Federal elenca expressamente os cinco princípios fundamentais da Administração Pública direta e indireta, conhecidos pelo mnemônico LIMPE, quais sejam:",
    explicacao: "GABARITO: B. Art. 37, caput, da CF/88: Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.",
    alternativas: [
      { letra: "A", texto: "Liberdade, Igualdade, Moderação, Prudência e Economia.", correta: false },
      { letra: "B", texto: "Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência.", correta: true },
      { letra: "C", texto: "Lucratividade, Isonomia, Motivação, Pontualidade e Exação.", correta: false },
      { letra: "D", texto: "Lealdade, Informalidade, Manutenção, Patrimonialismo e Ética.", correta: false },
      { letra: "E", texto: "Legalidade, Imediatidade, Mediação, Ponderação e Eficácia.", correta: false }
    ]
  },
  {
    idSlug: "adm-026",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal, ao julgar o Tema 532 da Repercussão Geral (RE 658.570/MG), assentou a constitucionalidade da competência das Guardas Municipais para a fiscalização de trânsito e aplicação de multas nas vias municipais.",
    explicacao: "GABARITO: CERTO. STF (Tema 532 / RE 658.570/MG): É constitucional a atribuição às Guardas Municipais do exercício de poder de polícia de trânsito, inclusive para imposição de sanções administrativas.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-027",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Corpo de Bombeiros",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A interdição imediata de um estabelecimento comercial ou casa de shows que não possui condições mínimas de segurança contra incêndio e pânico, realizada pelo Corpo de Bombeiros Militar, é manifestação do poder de polícia dotada do seguinte atributo:",
    explicacao: "GABARITO: C. A interdição física cautelar é exemplo clássico de autoexecutoriedade do poder de polícia, permitindo a execução material coercitiva imediata sem necessidade de ingressar previamente em juízo para obter liminar.",
    alternativas: [
      { letra: "A", texto: "Renúncia fiscal tácita.", correta: false },
      { letra: "B", texto: "Incompetência territorial relativa.", correta: false },
      { letra: "C", texto: "Autoexecutoriedade.", correta: true },
      { letra: "D", texto: "Preclusão consumativa administrativa.", correta: false },
      { letra: "E", texto: "Tipicidade processual estrita.", correta: false }
    ]
  },
  {
    idSlug: "adm-028",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_8112,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A estabilidade do servidor público concursado é adquirida após 3 (três) anos de efetivo exercício, condicionada à aprovação em avaliação especial de desempenho por comissão instituída para essa finalidade (art. 41 da CF/88 com redação da EC nº 19/1998).",
    explicacao: "GABARITO: CERTO. Art. 41 da CF/88: Exige 3 anos de efetivo exercício e avaliação especial de desempenho para a aquisição da estabilidade.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "adm-029",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.improbidade_administrativa,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 9º da Lei nº 8.429/1992, constitui ato de improbidade administrativa que importa enriquecimento ilícito auferir qualquer tipo de vantagem patrimonial indevida em razão do exercício de cargo, mandato, função, emprego ou atividade pública, notadamente:",
    explicacao: "GABARITO: D. Art. 9º, I, da Lei 8.429/1992: Receber vantagem econômica indevida para tolerar a exploração de jogos de azar, narcotráfico ou qualquer atividade ilícita é ato gravíssimo de enriquecimento ilícito.",
    alternativas: [
      { letra: "A", texto: "chegar com atraso justificado a uma escala de serviço operacional.", correta: false },
      { letra: "B", texto: "recusar-se a participar de evento esportivo de confraternização da unidade.", correta: false },
      { letra: "C", texto: "requerer certidão funcional para fins de aposentadoria voluntária.", correta: false },
      { letra: "D", texto: "receber dinheiro ou qualquer outra vantagem econômica para tolerar a exploração de jogos de azar, prostituição ou narcotráfico.", correta: true },
      { letra: "E", texto: "apresentar atestado médico de 2 dias por gripe sazonal.", correta: false }
    ]
  },
  {
    idSlug: "adm-030",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O princípio da impessoalidade veda a promoção pessoal de autoridades ou servidores públicos sobre suas realizações administrativas, dispondo o art. 37, § 1º, da CF/88 que a publicidade dos atos, programas, obras e campanhas dos órgãos públicos deverá ter caráter educativo, informativo ou de orientação social, dela não podendo constar nomes, símbolos ou imagens que caracterizem promoção pessoal.",
    explicacao: "GABARITO: CERTO. Art. 37, § 1º, da CF/88: Proíbe expressamente a utilização de publicidade institucional para promoção pessoal de autoridades.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  }
];
