import { TAXONOMIA } from "./taxonomia.mjs";

export const crim01Questoes = [
  {
    idSlug: "crim-001",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na evolução histórica do pensamento criminológico, a Escola Clássica (representada primordialmente por Cesare Beccaria e Francesco Carrara) sustentava como premissa antropológica fundamental que:",
    explicacao: "GABARITO: B. A Escola Clássica fundamenta-se no livre-arbítrio (o criminoso é um indivíduo livre e racional que escolhe delinquir com base no cálculo hedônico/utilitário) e concebe o crime como um ente jurídico (infração à lei), defendendo a pena retributiva proporcional ao mal causado.",
    alternativas: [
      { letra: "A", texto: "o delinquente é um ser atávico e biologicamente determinado ao crime desde o nascimento.", correta: false },
      { letra: "B", texto: "o criminoso é dotado de livre-arbítrio e racionalidade, sendo o crime concebido como um ente jurídico resultante de uma escolha consciente.", correta: true },
      { letra: "C", texto: "o delito decorre exclusivamente do processo de rotulação e estigmatização pelas agências penais.", correta: false },
      { letra: "D", texto: "o método de investigação deve ser empírico-indutivo e baseado na medição craniométrica.", correta: false },
      { letra: "E", texto: "a pena tem função estritamente de medida de segurança por tempo indeterminado.", correta: false }
    ]
  },
  {
    idSlug: "crim-002",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Escola Positiva da Criminologia, rompendo com o método dedutivo-normativo da Escola Clássica, introduziu o método indutivo-experimental (empírico) no estudo do crime, dividindo-se nas fases antropológica (Cesare Lombroso), sociológica (Enrico Ferri) e jurídica (Raffaele Garofalo).",
    explicacao: "GABARITO: CERTO. A Escola Positiva (Positivismo Criminológico) substituiu a abstração jurídica pelo empirismo científico através de sua tríade: Lombroso (antropologia/criminoso nato), Ferri (fatores sociológicos) e Garofalo (conceito de crime natural e temibilidade).",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-003",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Teoria da Anomia, desenvolvida inicialmente no campo sociológico por Émile Durkheim e posteriormente adaptada à criminologia por Robert K. Merton, sustenta que o desvio criminal surge quando:",
    explicacao: "GABARITO: C. Na teoria de Merton, a anomia resulta do descompasso e da tensão estrutural entre as metas culturais de sucesso impostas pela sociedade (ex.: sucesso financeiro) e a ausência ou restrição de meios legítimos/institucionalizados para que todos possam alcançá-las.",
    alternativas: [
      { letra: "A", texto: "o cérebro do delinquente apresenta anomalias congênitas nos lobos frontais.", correta: false },
      { letra: "B", texto: "a vítima precipita intencionalmente a agressão através de comportamento imprudente.", correta: false },
      { letra: "C", texto: "há uma dissociação ou tensão estrutural entre as metas culturais prescritas pela sociedade e a falta de acesso a meios institucionais legítimos para atingi-las.", correta: true },
      { letra: "D", texto: "a polícia adota a estratégia de policiamento de tolerância zero em áreas periféricas.", correta: false },
      { letra: "E", texto: "o infrator aprende técnicas de delinquência em contato exclusivo com a elite financeira.", correta: false }
    ]
  },
  {
    idSlug: "crim-004",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Teoria Ecológica ou da Desorganização Social, desenvolvida pela Escola de Chicago (Clifford Shaw, Henry McKay, Robert Park e Ernest Burgess), explicou a concentração da criminalidade urbana a partir:",
    explicacao: "GABARITO: A. A Escola de Chicago (Teoria Ecológica) demonstrou que as taxas de criminalidade estavam correlacionadas à deterioração física, instabilidade residencial e desorganização social das zonas de transição urbana (modelo das zonas concêntricas), enfraquecendo os mecanismos informais de controle social.",
    alternativas: [
      { letra: "A", texto: "da desorganização social e deterioração das áreas de transição urbana (zonas concêntricas), onde o enfraquecimento do controle social informal facilita a delinquência.", correta: true },
      { letra: "B", texto: "da predisposição genética transmitida hereditariamente por famílias criminosas.", correta: false },
      { letra: "C", texto: "da pura e simples ausência de normas penais incriminadoras no ordenamento jurídico.", correta: false },
      { letra: "D", texto: "da incapacidade de reabilitação médica dos portadores de psicopatia clínica.", correta: false },
      { letra: "E", texto: "da influência exclusiva do clima tropical na agressividade biológica humana.", correta: false }
    ]
  },
  {
    idSlug: "crim-005",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A Teoria da Associação Diferencial, formulada por Edwin Sutherland, postula que o comportamento criminoso é aprendido em interação e comunicação íntima com outras pessoas, abrangendo tanto a aprendizagem de técnicas de cometimento do delito quanto a internalização de motivos, impulsos e racionalizações justificadoras, sendo pioneira no estudo dos crimes de colarinho branco (white-collar crimes).",
    explicacao: "GABARITO: CERTO. Sutherland formulou a Teoria da Associação Diferencial (o crime é aprendido por interação social) e cunhou o conceito criminológico de crime de colarinho branco, refutando a ideia de que o crime seria exclusivo das classes vulneráveis.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-006",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Teoria do Labelling Approach (Teoria do Etiquetamento, Rotulação Social ou Reação Social), associada a teóricos como Howard Becker e Edwin Lemert, representou uma mudança paradigmática na Criminologia ao:",
    explicacao: "GABARITO: D. O Labelling Approach transferiu o foco etiológico (causas do crime no indivíduo) para o processo de criminalização e controle social seletivo. Edwin Lemert distinguiu desvio primário (a conduta inicial não rotulada) e desvio secundário (a assimilação da identidade de desviante gerada pelo estigma da punição).",
    alternativas: [
      { letra: "A", texto: "comprovar cientificamente que a causa do crime reside em desequilíbrios bioquímicos cerebrais.", correta: false },
      { letra: "B", texto: "propor que a punição penal severa elimina instantaneamente a reincidência delitiva.", correta: false },
      { letra: "C", texto: "defender a criminalização universal de condutas atípicas para reduzir a impunidade.", correta: false },
      { letra: "D", texto: "deslocar o objeto de estudo da etiologia do criminoso para a reação social e o processo de estigmatização exercido pelas instâncias formais de controle (distinguindo desvio primário de secundário).", correta: true },
      { letra: "E", texto: "afirmar que a prisão é o ambiente mais terapêutico e harmonioso para o indivíduo.", correta: false }
    ]
  },
  {
    idSlug: "crim-007",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Teoria das Janelas Quebradas (Broken Windows Theory), elaborada por James Q. Wilson e George L. Kelling em 1982, serviu de base teórica para a política de segurança pública conhecida como 'tolerância zero', preconizando que a tolerância estatal diante de pequenas desordens e incivilidades no espaço público transmite a mensagem de abandono e incentiva a escalada para crimes mais graves.",
    explicacao: "GABARITO: CERTO. A teoria das janelas quebradas sustenta que a desordem visível e não repreendida gera sensação de impunidade, atraindo delitos maiores e justificando a repressão rigorosa de pequenas infrações.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-008",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na Teoria da Subcultura Delinquente de Albert Cohen, a delinquência juvenil das classes desfavorecidas é caracterizada por condutas marcadamente:",
    explicacao: "GABARITO: A. Albert Cohen caracterizou a subcultura delinquente juvenil como não utilitária (o delito não busca lucro financeiro direto), maliciosa (desejo de afrontar a ordem) e negativista (inversão proposital dos valores da classe média).",
    alternativas: [
      { letra: "A", texto: "não utilitárias, maliciosas e negativistas, que invertem deliberadamente as normas e valores da classe média dominante.", correta: true },
      { letra: "B", texto: "estritamente orientadas ao acúmulo de capital financeiro e investimentos bancários.", correta: false },
      { letra: "C", texto: "decorrentes da busca passiva por conformidade religiosa dogmática.", correta: false },
      { letra: "D", texto: "motivadas exclusivamente por ordens transmitidas por agências estatais de controle.", correta: false },
      { letra: "E", texto: "idênticas aos crimes de sonegação tributária internacional.", correta: false }
    ]
  },
  {
    idSlug: "crim-009",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No estudo da Vitimologia, a classificação pioneira formulada por Benjamin Mendelsohn categoriza a 'vítima perfeitamente inocente' ou 'vítima ideal' como aquela que:",
    explicacao: "GABARITO: B. Na tipologia de Mendelsohn: 1) Vítima completamente inocente (ideal): não tem qualquer participação ou provocação no evento delitivo; 2) Vítima de culpabilidade menor (por ignorância); 3) Vítima tão culpada quanto o infrator (vítima voluntária/duelo); 4) Vítima mais culpada que o infrator (vítima provocadora); 5) Vítima unicamente culpada (vítima agressora/legítima defesa).",
    alternativas: [
      { letra: "A", texto: "provoca deliberadamente o agressor com agressões verbais e físicas.", correta: false },
      { letra: "B", texto: "não tem nenhuma participação, provocação ou colaboração com o resultado danoso provocado pelo agressor.", correta: true },
      { letra: "C", texto: "finge ter sofrido o crime para extorquir indenizações judiciais indevidas.", correta: false },
      { letra: "D", texto: "consente expressamente na prática do roubo para auferir vantagem do seguro.", correta: false },
      { letra: "E", texto: "assume culpabilidade exclusiva ao atacar o suposto ofensor em legítima defesa.", correta: false }
    ]
  },
  {
    idSlug: "crim-010",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A vitimização secundária (ou sobrevitimização / revitimização) consiste no sofrimento adicional imposto à vítima pelas próprias instâncias formais de controle social (polícia, ministério público, poder judiciário, perícia médica), em decorrência de atendimentos burocráticos, estigmatizantes, insensíveis ou repetitivos.",
    explicacao: "GABARITO: CERTO. Vitimização primária: sofrimento direto causado pelo crime. Vitimização secundária (revitimização): dor e constrangimento provocados pelo contato burocrático com o aparato estatal. Vitimização terciária: rejeição e estigmatização sofrida pela vítima perante seu grupo social, familiar ou comunitário.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-011",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No âmbito da Criminologia, a 'vitimização terciária' manifesta-se quando a pessoa vítima de um crime:",
    explicacao: "GABARITO: C. Vitimização terciária: Consiste no abandono, discriminação e estigmatização da vítima pelo seu próprio meio social, amigos, familiares ou comunidade, que passam a julgá-la, isolá-la ou culpabilizá-la pelo crime ocorrido.",
    alternativas: [
      { letra: "A", texto: "sofre lesões físicas imediatas provocadas pelo disparo de arma de fogo do autor.", correta: false },
      { letra: "B", texto: "é inquirida sucessivas vezes na delegacia de polícia sem acolhimento psicológico.", correta: false },
      { letra: "C", texto: "enfrenta o isolamento, a incompreensão, o preconceito e o estigma emanados do seu próprio grupo social, familiar ou de trabalho.", correta: true },
      { letra: "D", texto: "recebe indenização pecuniária integral fixada na sentença condenatória irrecorrível.", correta: false },
      { letra: "E", texto: "decide ingressar nas fileiras da polícia civil por aprovação em concurso público.", correta: false }
    ]
  },
  {
    idSlug: "crim-012",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em criminologia, a expressão 'Cifra Negra' (Dark Number of Crime) refere-se à:",
    explicacao: "GABARITO: A. Cifra negra: É a porcentagem/número de crimes efetivamente praticados na realidade social que não chegam ao conhecimento das autoridades policiais ou instâncias oficiais de persecução penal.",
    alternativas: [
      { letra: "A", texto: "diferença entre o total de crimes efetivamente praticados e os crimes que chegam ao conhecimento oficial dos órgãos de persecução penal.", correta: true },
      { letra: "B", texto: "quantidade de crimes violentos punidos exclusivamente com penas pecuniárias.", correta: false },
      { letra: "C", texto: "estatística de homicídios que obtiveram sentença absolutória no Tribunal do Júri.", correta: false },
      { letra: "D", texto: "porcentagem de presos que exercem atividade laboral remunerada nos presídios.", correta: false },
      { letra: "E", texto: "soma de todos os inquéritos policiais arquivados por atipicidade formal.", correta: false }
    ]
  },
  {
    idSlug: "crim-013",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Enquanto a Cifra Dourada designa a criminalidade do colarinho branco e os delitos praticados pela elite socioeconômica e política que não chegam a ser punidos, a Cifra Cinza corresponde aos crimes que são registrados perante a polícia, mas se resolvem na própria delegacia ou mediante conciliação sem instauração de processo judicial formal.",
    explicacao: "GABARITO: CERTO. Cifra dourada = crimes de colarinho branco/econômicos impunes; Cifra cinza = crimes registrados na polícia que não chegam à esfera judicial (ex.: conciliação, acordo, desinteresse posterior).",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-014",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na tipologia das cifras criminais modernas, a 'Cifra Amarela' e a 'Cifra Rosa' representam, respectivamente:",
    explicacao: "GABARITO: B. Cifra amarela: delitos cometidos por agentes públicos com abuso ou violência arbitrária não denunciados pela população por medo de represália. Cifra rosa: delitos de caráter homofóbico/transfóbico contra pessoas LGBTQIA+ subnotificados.",
    alternativas: [
      { letra: "A", texto: "crimes tributários de pequenas empresas e crimes ambientais florestais.", correta: false },
      { letra: "B", texto: "crimes praticados com violência policial ou abuso de poder não notificados por temor da vítima, e crimes motivados por homofobia/transfobia não reportados.", correta: true },
      { letra: "C", texto: "furto de combustíveis fósseis e roubo de gado em zonas rurais.", correta: false },
      { letra: "D", texto: "delitos de trânsito culposos e fraudes bancárias eletrônicas contra idosos.", correta: false },
      { letra: "E", texto: "crimes contra a honra entre parlamentares e ofensas virtuais no exterior.", correta: false }
    ]
  },
  {
    idSlug: "crim-015",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A 'Cifra Verde' refere-se aos delitos ambientais praticados contra a fauna, flora e ordenamento urbano que permanecem ocultos e fora do conhecimento e processamento pelos órgãos fiscalizadores e pelo Poder Judiciário.",
    explicacao: "GABARITO: CERTO. Cifra verde: Representa a criminalidade ecológica/ambiental não registrada ou impune.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-016",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.prevencao_criminal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na classificação dos modelos de prevenção criminal, a 'Prevenção Primária' atua:",
    explicacao: "GABARITO: D. A Prevenção Primária atua nas raízes profundas da criminalidade (educação, saúde, trabalho, habitação, qualidade de vida, socialização familiar), tendo caráter de longo prazo e dirigindo-se a toda a população indistintamente.",
    alternativas: [
      { letra: "A", texto: "exclusivamente dentro dos presídios para evitar a reincidência do apenado.", correta: false },
      { letra: "B", texto: "no momento exato em que o delito está em andamento por meio do flagrante delito.", correta: false },
      { letra: "C", texto: "apenas em relação a grupos com elevado risco policial já identificados criminalmente.", correta: false },
      { letra: "D", texto: "nas causas estruturais e sociais do delito, mediante políticas públicas de educação, moradia, emprego e lazer, dirigidas a toda a sociedade a longo prazo.", correta: true },
      { letra: "E", texto: "na fixação de penas corporais perpétuas na legislação processual penal.", correta: false }
    ]
  },
  {
    idSlug: "crim-017",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.prevencao_criminal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Prevenção Secundária opera a médio e curto prazo, orientando-se a grupos específicos e setores com maior vulnerabilidade ou risco criminógeno, manifestando-se por meio do policiamento ostensivo, programas de vigilância em áreas críticas e medidas preventivas em bairros violentos.",
    explicacao: "GABARITO: CERTO. A Prevenção Secundária atua sobre focos de risco concretos (policiamento direcionado, iluminação de áreas de risco, prevenção situacional e grupos vulneráveis).",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-018",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.prevencao_criminal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A 'Prevenção Terciária' no modelo criminológico clássico é aquela voltada a:",
    explicacao: "GABARITO: A. A Prevenção Terciária destina-se especificamente à população carcerária e aos egressos do sistema prisional, visando à sua ressocialização, reabilitação e impedimento da reincidência delitiva.",
    alternativas: [
      { letra: "A", texto: "evitar a reincidência criminal por meio da ressocialização, assistência educacional e laborativa aos apenados e egressos do sistema prisional.", correta: true },
      { letra: "B", texto: "garantir o ensino básico obrigatório a crianças de zero a seis anos de idade.", correta: false },
      { letra: "C", texto: "aumentar o efetivo de guardas municipais em praças públicas centrais.", correta: false },
      { letra: "D", texto: "instalar câmeras de monitoramento facial em aeroportos internacionais.", correta: false },
      { letra: "E", texto: "conceder anistia geral e irrestrita a todos os condenados por roubo armado.", correta: false }
    ]
  },
  {
    idSlug: "crim-019",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Teoria da Escolha Racional (Rational Choice Theory), de Ronald Clarke e Derek Cornish, e a Teoria das Atividades Rotineiras (Routine Activity Theory), de Lawrence Cohen e Marcus Felson, inserem-se nas teorias de prevenção situacional do crime, afirmando que a oportunidade criminosa decorre da convergência no tempo e no espaço de três elementos:",
    explicacao: "GABARITO: C. Na Teoria das Atividades Rotineiras de Cohen e Felson, a oportunidade delitiva requer a convergência simultânea de: 1) Um ofensor motivado; 2) Um alvo adequado/vulnerável; 3) A ausência de um guardião capaz (policiamento, iluminação, trancas, cidadãos vigilantes).",
    alternativas: [
      { letra: "A", texto: "defeito cromossômico, surto psicótico agudo e consumo de bebida alcoólica.", correta: false },
      { letra: "B", texto: "pobreza extrema, ausência de escola pública e clima chuvoso.", correta: false },
      { letra: "C", texto: "um delinquente motivado, um alvo vulnerável/adequado e a ausência de um guardião capaz (controle/proteção eficaz).", correta: true },
      { letra: "D", texto: "uma vítima culpada, um juiz omisso e a revogação de tipos penais.", correta: false },
      { letra: "E", texto: "um mandado de prisão vencido, um veículo roubado e um celular desligado.", correta: false }
    ]
  },
  {
    idSlug: "crim-020",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A Criminologia Crítica (ou Dialética / Radical), inspirada no materialismo histórico e na teoria marxista, concebe o Direito Penal não como instrumento neutro de pacificação social, mas como aparato de classe destinado à preservação das relações desiguais de produção e à dominação das classes subordinadas.",
    explicacao: "GABARITO: CERTO. A Criminologia Crítica (Alessandro Baratta, Taylor, Walton e Young) desmistifica a neutralidade do sistema penal, demonstrando sua seletividade estrutural e função mantenedora das desigualdades socioeconômicas.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-021",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na Criminologia, o 'Controle Social Informal' é exercido cotidianamente por instâncias não estatais, entre as quais se destacam:",
    explicacao: "GABARITO: B. Controle social informal: Família, escola, igreja, comunidade, vizinhança, profissão, clubes e opinião pública. Controle social formal: Polícia, Ministério Público, Judiciário e Sistema Penitenciário.",
    alternativas: [
      { letra: "A", texto: "as polícias civis e militares, o Ministério Público e o Poder Judiciário.", correta: false },
      { letra: "B", texto: "a família, a escola, a religião/igreja, o ambiente de trabalho e a comunidade.", correta: true },
      { letra: "C", texto: "as varas de execução penal e as penitenciárias de segurança máxima.", correta: false },
      { letra: "D", texto: "os tribunais de contas e os conselhos disciplinares de servidores públicos.", correta: false },
      { letra: "E", texto: "o conselho de sentença no tribunal do júri popular.", correta: false }
    ]
  },
  {
    idSlug: "crim-022",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.vitimologia_cifras,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A 'Cifra Branca' corresponde às condutas criminosas registradas formalmente, investigadas e com autoria identificada que resultam em condenação judicial transitada em julgado.",
    explicacao: "GABARITO: CERTO. Cifra branca: Representa a criminalidade oficial, registrada, desvendada e processada pelo sistema de justiça penal.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "crim-023",
    disciplina_id: TAXONOMIA.disciplinas.criminologia,
    assunto_id: TAXONOMIA.assuntos.escolas_criminologicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Teoria da Neutralização, formulada por Gresham Sykes e David Matza, explica que os infratores juvenis e adultos frequentemente utilizam justificativas morais e psicológicas prévias para cometer delitos sem perder o autorrespeito, entre as quais figuram:",
    explicacao: "GABARITO: A. As técnicas de neutralização de Sykes e Matza são: 1) Negação da responsabilidade ('eu não tive culpa/estava bêbado'); 2) Negação do dano ('eles têm dinheiro de sobra/seguro paga'); 3) Negação da vítima ('ela mereceu/era um canalha'); 4) Condenação dos condenadores ('os policiais também são corruptos'); 5) Apelo a lealdades superiores ('fiz pela minha família/gangue').",
    alternativas: [
      { letra: "A", texto: "a negação da responsabilidade, a negação do dano, a negação da vítima, a condenação dos que condenam e o apelo a lealdades superiores.", correta: true },
      { letra: "B", texto: "a confissão espontânea perante o delegado e a renúncia à ampla defesa.", correta: false },
      { letra: "C", texto: "a busca por medidas cautelares diversas da prisão e a colaboração premiada.", correta: false },
      { letra: "D", texto: "a aceitação incondicional do castigo carcerário como penitência religiosa.", correta: false },
      { letra: "E", texto: "o pedido de indulto natalino assinado pelo Presidente da República.", correta: false }
    ]
  }
];
