import { TAXONOMIA } from "./taxonomia.mjs";

export const lep01Questoes = [
  {
    idSlug: "lep-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal Federal",
    cargo_nome: "Agente Federal de Execução Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "De acordo com a Lei de Execução Penal (Lei nº 7.210/1984), a execução penal tem por objetivo efetivar as disposições de sentença ou decisão criminal e proporcionar condições para a harmônica integração social do condenado e do internado.",
    explicacao: "GABARITO: CERTO. Art. 1º da LEP: 'A execução penal tem por objetivo efetivar as disposições de sentença ou decisão criminal e proporcionar condições para a harmônica integração social do condenado e do internado.' Trata-se da dupla finalidade da execução penal: retributiva/preventiva e ressocializadora.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Ao condenado e ao internado serão assegurados todos os direitos não atingidos pela sentença ou pela lei, sendo vedada qualquer espécie de discriminação de natureza racial, social, religiosa ou política.",
    explicacao: "GABARITO: CERTO. Inteligência do art. 3º da Lei nº 7.210/1984, que consagra o princípio da legalidade e da não discriminação no cumprimento das penas privativas de liberdade e restritivas de direitos.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Oficial Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A classificação dos condenados à pena privativa de liberdade, segundo seus antecedentes e personalidade, para orientar a individualização da execução penal, será realizada pela:",
    explicacao: "GABARITO: D. Nos termos do art. 6º da LEP, a classificação para a individualização da execução penal é incumbência da Comissão Técnica de Classificação (CTC), existente em cada estabelecimento penal.",
    alternativas: [
      { letra: "A", texto: "Defensoria Pública Estadual.", correta: false },
      { letra: "B", texto: "Vara de Execuções Penais privativamente.", correta: false },
      { letra: "C", texto: "Secretaria de Segurança Pública Estadual.", correta: false },
      { letra: "D", texto: "Comissão Técnica de Classificação existente no estabelecimento.", correta: true },
      { letra: "E", texto: "Procuradoria-Geral de Justiça.", correta: false }
    ]
  },
  {
    idSlug: "lep-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A Comissão Técnica de Classificação que atua no âmbito da execução da pena privativa de liberdade será presidida pelo diretor do estabelecimento e composta por, no mínimo, dois chefes de serviço, um psiquiatra, um psicólogo e um assistente social.",
    explicacao: "GABARITO: CERTO. Art. 7º da LEP: 'A Comissão Técnica de Classificação, existente em cada estabelecimento, será presidida pelo Diretor e composta, no mínimo, por 2 (dois) chefes de serviço, 1 (um) psiquiatra, 1 (um) psicólogo e 1 (um) assistente social, quando se tratar de condenado à pena privativa de liberdade.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 9º-A da LEP (com as alterações do Pacote Anticrime - Lei nº 13.964/2019), o condenado por crime praticado, dolosamente, com violência de natureza grave contra pessoa, ou por qualquer dos crimes previstos na Lei de Crimes Hediondos, será submetido, obrigatoriamente, à:",
    explicacao: "GABARITO: C. O art. 9º-A da LEP determina a identificação do perfil genético mediante extração de DNA de condenados por crimes dolosos praticados com violência grave contra pessoa ou hediondos/equiparados.",
    alternativas: [
      { letra: "A", texto: "remição ficta de pena em dobro.", correta: false },
      { letra: "B", texto: "perda imediata de todo o tempo remido anteriormente.", correta: false },
      { letra: "C", texto: "identificação do perfil genético, mediante extração de DNA, por técnica adequada e indolor.", correta: true },
      { letra: "D", texto: "inclusão automática e perpétua no Regime Disciplinar Diferenciado.", correta: false },
      { letra: "E", texto: "submissão a trabalho forçado intramuros.", correta: false }
    ]
  },
  {
    idSlug: "lep-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A recusa injustificada do condenado em submeter-se ao procedimento de identificação do perfil genético previsto no art. 9º-A da LEP constitui falta disciplinar de natureza grave.",
    explicacao: "GABARITO: CERTO. Art. 9º-A, § 8º, da LEP: 'Constitui falta grave a recusa do condenado em submeter-se ao procedimento de identificação do perfil genético.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Agente de Segurança Penitenciária",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A assistência prestada ao preso e ao internado é dever do Estado, objetivando prevenir o crime e orientar o retorno à convivência em sociedade. Nos termos do art. 11 da LEP, a assistência ao preso compreende:",
    explicacao: "GABARITO: A. O art. 11 da LEP enumera as 6 assistências: material, à saúde, jurídica, educacional, social e religiosa.",
    alternativas: [
      { letra: "A", texto: "material, à saúde, jurídica, educacional, social e religiosa.", correta: true },
      { letra: "B", texto: "apenas médica, jurídica e psicológica.", correta: false },
      { letra: "C", texto: "financeira, patrimonial, habitacional e médica.", correta: false },
      { letra: "D", texto: "política, sindical, jurídica e previdenciária.", correta: false },
      { letra: "E", texto: "exclusivamente alimentar, de vestuário e higiênica.", correta: false }
    ]
  },
  {
    idSlug: "lep-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A assistência jurídica no âmbito da execução penal é destinada a todos os presos e internados, independentemente de possuírem ou não recursos financeiros para constituir advogado particular.",
    explicacao: "GABARITO: ERRADO. Art. 15 da LEP: 'A assistência jurídica é destinada aos presos e aos internados sem recursos financeiros para constituir advogado.' Aqueles que possuem condições contratam defensor particular.",
    alternativas: [{ texto: "Certo", correta: false }, { texto: "Errado", correta: true }]
  },
  {
    idSlug: "lep-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação à assistência educacional prevista na Lei de Execução Penal, assinale a afirmativa correta:",
    explicacao: "GABARITO: B. O art. 17 da LEP estabelece que a instrução de ensino fundamental é obrigatória, integrando-se no sistema escolar da Unidade Federativa.",
    alternativas: [
      { letra: "A", texto: "O ensino de nível superior é obrigatório a todos os apenados em regime fechado.", correta: false },
      { letra: "B", texto: "A instrução de ensino fundamental é obrigatória, integrando-se no sistema escolar da Unidade Federativa.", correta: true },
      { letra: "C", texto: "A formação profissionalizante é vedada no âmbito dos estabelecimentos penais estaduais.", correta: false },
      { letra: "D", texto: "O censo penitenciário não deve apurar o nível de escolaridade dos presos.", correta: false },
      { letra: "E", texto: "O estabelecimento prisional não é obrigado a dispor de biblioteca.", correta: false }
    ]
  },
  {
    idSlug: "lep-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nenhum preso poderá ser obrigado a participar de atividade religiosa, embora seja assegurada a liberdade de culto e a posse de livros de instrução religiosa.",
    explicacao: "GABARITO: CERTO. Art. 24, § 1º e § 2º, da LEP: A posse de livros sagrados e a participação em serviços religiosos são facultadas, mas nenhum apenado pode ser obrigado a praticar ou assistir ato de culto.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A assistência ao egresso consiste na concessão de alojamento e alimentação em estabelecimento adequado pelo prazo de 2 meses, bem como na colaboração para a obtenção de trabalho. Considera-se egresso, para os efeitos da LEP:",
    explicacao: "GABARITO: C. Art. 26 da LEP: 'Considera-se egresso para os efeitos desta Lei: I - o liberado definitivo, pelo prazo de 1 (um) ano a contar da saída do estabelecimento; II - o liberado condicional, durante o período de prova.'",
    alternativas: [
      { letra: "A", texto: "qualquer pessoa indiciada em inquérito policial que não tenha sido presa.", correta: false },
      { letra: "B", texto: "o apenado que empreendeu fuga e se apresentou voluntariamente após 30 dias.", correta: false },
      { letra: "C", texto: "o liberado definitivo, pelo prazo de 1 ano a contar da saída, e o liberado condicional, durante o período de prova.", correta: true },
      { letra: "D", texto: "o preso em cumprimento de Regime Disciplinar Diferenciado.", correta: false },
      { letra: "E", texto: "o condenado que teve sua punibilidade extinta pela prescrição antes do trânsito em julgado.", correta: false }
    ]
  },
  {
    idSlug: "lep-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O trabalho do preso está sujeito ao regime da Consolidação das Leis do Trabalho (CLT), gerando vínculo empregatício pleno e direito a FGTS, horas extras e aviso prévio.",
    explicacao: "GABARITO: ERRADO. Art. 28, § 2º, da LEP: 'O trabalho do preso não está sujeito ao regime da Consolidação das Leis do Trabalho.' É um dever social e condição de dignidade humana com caráter educativo e produtivo, não gerando vínculo celetista.",
    alternativas: [{ texto: "Certo", correta: false }, { texto: "Errado", correta: true }]
  },
  {
    idSlug: "lep-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A remuneração do trabalho do preso, nos termos do art. 29 da LEP, é regulamentada de forma estrita. De acordo com o texto legal, a remuneração não poderá ser inferior a:",
    explicacao: "GABARITO: D. Art. 29, caput, da LEP: 'O trabalho do preso será remunerado, mediante prévia tabela, não podendo ser inferior a 3/4 (três quartos) do salário mínimo.'",
    alternativas: [
      { letra: "A", texto: "1 salário mínimo integral vigente.", correta: false },
      { letra: "B", texto: "1/4 do salário mínimo.", correta: false },
      { letra: "C", texto: "metade (50%) do salário mínimo.", correta: false },
      { letra: "D", texto: "3/4 (três quartos) do salário mínimo.", correta: true },
      { letra: "E", texto: "2 salários mínimos vigentes.", correta: false }
    ]
  },
  {
    idSlug: "lep-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O trabalho externo será admissível para os presos em regime fechado somente em serviços ou obras públicas realizadas por órgãos da Administração Direta ou Indireta, ou entidades privadas, desde que tomadas as devidas cautelas contra a fuga e em favor da disciplina.",
    explicacao: "GABARITO: CERTO. Art. 36 da LEP: 'O trabalho externo será admissível para os presos em regime fechado somente em serviço ou obras públicas realizadas por órgãos da Administração Direta ou Indireta, ou entidades privadas, desde que tomadas as cautelas contra a fuga e em favor da disciplina.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Para a concessão de trabalho externo ao preso condenado em regime fechado, a LEP exige o cumprimento de requisito objetivo temporal prévio. Esse requisito consiste no cumprimento mínimo de:",
    explicacao: "GABARITO: B. Art. 37, caput, da LEP: 'A prestação de trabalho externo, a ser autorizada pela direção do estabelecimento, dependerá de aptidão, disciplina e responsabilidade, além do cumprimento de no mínimo 1/6 (um sexto) da pena.'",
    alternativas: [
      { letra: "A", texto: "1/2 da pena total.", correta: false },
      { letra: "B", texto: "1/6 (um sexto) da pena.", correta: true },
      { letra: "C", texto: "2/3 da pena.", correta: false },
      { letra: "D", texto: "2/5 da pena.", correta: false },
      { letra: "E", texto: "1/3 da pena.", correta: false }
    ]
  },
  {
    idSlug: "lep-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O preso provisório não está obrigado ao trabalho interno ou externo, tratando-se de faculdade sua.",
    explicacao: "GABARITO: CERTO. Art. 31, parágrafo único, da LEP: 'Para o preso provisório, o trabalho não é obrigatório e só poderá ser executado no interior do estabelecimento.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Segundo o art. 61 da Lei nº 7.210/1984, são órgãos da execução penal, EXCETO:",
    explicacao: "GABARITO: E. O Tribunal de Contas da União não é órgão da execução penal. Os órgãos da execução penal elencados no art. 61 são: Conselho Nacional de Política Criminal e Penitenciária, Juízo da Execução, Ministério Público, Conselho Penitenciário, Departamentos Penitenciários, Patronato, Conselho da Comunidade e Defensoria Pública.",
    alternativas: [
      { letra: "A", texto: "Conselho Nacional de Política Criminal e Penitenciária.", correta: false },
      { letra: "B", texto: "Juízo da Execução e Ministério Público.", correta: false },
      { letra: "C", texto: "Conselho Penitenciário e Patronato.", correta: false },
      { letra: "D", texto: "Conselho da Comunidade e Defensoria Pública.", correta: false },
      { letra: "E", texto: "Tribunal de Contas da União.", correta: true }
    ]
  },
  {
    idSlug: "lep-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal Federal",
    cargo_nome: "Policial Penal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Conselho Nacional de Política Criminal e Penitenciária (CNPCP), órgão subordinado ao Ministério da Justiça e Segurança Pública, é integrado por 13 membros designados através de ato do Ministro da Justiça, dentre professores e profissionais da área do Direito Penal, Processual Penal, Penitenciário e ciências correlatas, bem como por representantes da comunidade.",
    explicacao: "GABARITO: CERTO. Art. 62 e 63 da LEP: O CNPCP é com sede na Capital da República e subordinado ao Ministério da Justiça, composto por 13 membros com mandato de 2 anos.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em cada comarca haverá um Conselho da Comunidade composto, no mínimo, por:",
    explicacao: "GABARITO: A. Art. 80 da LEP: 'Haverá, em cada comarca, um Conselho da Comunidade composto, no mínimo, por 1 (um) representante de associação comercial ou industrial, 1 (um) advogado indicado pela Seção da Ordem dos Advogados do Brasil, 1 (um) Defensor Público indicado pelo Defensor Geral e 1 (um) assistente social escolhido pela Delegacia Seccional do Conselho Nacional de Assistentes Sociais.'",
    alternativas: [
      { letra: "A", texto: "1 representante de associação comercial/industrial, 1 advogado indicado pela OAB, 1 Defensor Público e 1 assistente social.", correta: true },
      { letra: "B", texto: "2 magistrados, 2 promotores de justiça e 2 policiais penais.", correta: false },
      { letra: "C", texto: "3 delegados de polícia e 3 vereadores do município.", correta: false },
      { letra: "D", texto: "1 médico legista, 1 perito criminal e 2 agentes prisionais.", correta: false },
      { letra: "E", texto: "exclusivamente por líderes religiosos e assistentes sociais voluntários.", correta: false }
    ]
  },
  {
    idSlug: "lep-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Incumbe ao Conselho da Comunidade visitar, pelo menos mensalmente, os estabelecimentos penais existentes na comarca, entrevistar presos e apresentar relatórios mensais ao Juiz da execução e ao Conselho Penitenciário.",
    explicacao: "GABARITO: CERTO. Art. 81 da LEP: 'Incumbe ao Conselho da Comunidade: I - visitar, pelo menos mensalmente, os estabelecimentos penais existentes na comarca; II - entrevistar presos; III - promover a obtenção de recursos materiais e humanos para melhor assistência ao preso ou internado, em harmonia com a direção do estabelecimento; IV - relatar, mensalmente, ao Juiz da execução e ao Conselho Penitenciário.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-021",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O órgão da execução penal que presta assistência aos albergados e aos egressos, fiscalizando também o cumprimento das penas de prestação de serviços à comunidade e limitação de fim de semana, é denominado:",
    explicacao: "GABARITO: B. Art. 78 e 79 da LEP: O Patronato público ou particular destina-se a prestar assistência aos albergados e aos egressos, além de orientar e fiscalizar o cumprimento das penas restritivas de direitos.",
    alternativas: [
      { letra: "A", texto: "Conselho Nacional de Justiça.", correta: false },
      { letra: "B", texto: "Patronato.", correta: true },
      { letra: "C", texto: "Centro de Detenção Provisória.", correta: false },
      { letra: "D", texto: "Departamento Penitenciário Nacional privativamente.", correta: false },
      { letra: "E", texto: "Comissão de Ética Pública.", correta: false }
    ]
  },
  {
    idSlug: "lep-022",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Compete ao Juízo da Execução aplicar aos casos julgados lei posterior que de qualquer modo favoreça o réu, bem como declarar extinta a punibilidade.",
    explicacao: "GABARITO: CERTO. Art. 66, I e II, da LEP, em consonância com a Súmula 611 do STF: Transitada em julgado a sentença condenatória, compete ao Juízo das Execuções a aplicação de lei mais benigna.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-023",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre a composição e atuação do Conselho Penitenciário estadual, é correto afirmar que:",
    explicacao: "GABARITO: A. Art. 69 e 70 da LEP: O Conselho Penitenciário é órgão consultivo e fiscalizador da execução da pena, incumbindo-lhe emitir parecer sobre indulto e comutação de pena e inspecionar estabelecimentos e serviços penais.",
    alternativas: [
      { letra: "A", texto: "é órgão consultivo e fiscalizador da execução da pena, incumbido de emitir parecer sobre indulto e comutação de penas.", correta: true },
      { letra: "B", texto: "possui competência para proferir sentenças terminativas de execução penal.", correta: false },
      { letra: "C", texto: "é composto unicamente por agentes de segurança pública da ativa.", correta: false },
      { letra: "D", texto: "não tem legitimidade para inspecionar estabelecimentos penais estaduais.", correta: false },
      { letra: "E", texto: "suas decisões sobre progressão de regime vinculam obrigatoriamente o Magistrado.", correta: false }
    ]
  },
  {
    idSlug: "lep-024",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Ministério Público fiscalizará a execução da pena e da medida de segurança, oficiando no processo executivo e nos incidentes da execução, tendo o dever de visitar mensalmente os estabelecimentos penais.",
    explicacao: "GABARITO: CERTO. Art. 67 e 68 da LEP c/c Resolução nº 56/2010 do CNMP: É dever funcional do Ministério Público fiscalizar mensalmente os estabelecimentos prisionais e atuar na defesa da ordem jurídica na execução penal.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-025",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em relação ao exame criminológico na Lei de Execução Penal com as alterações introduzidas pela Lei nº 14.843/2024, assinale a opção correta:",
    explicacao: "GABARITO: E. Com a vigência da Lei nº 14.843/2024, a realização de exame criminológico passou a ser expressamente exigida por lei para a progressão de regime de pena privativa de liberdade, afastando a facultatividade anterior.",
    alternativas: [
      { letra: "A", texto: "O exame criminológico foi formalmente extinto do ordenamento jurídico brasileiro.", correta: false },
      { letra: "B", texto: "O exame criminológico passou a ser vedado para apenados por crimes hediondos.", correta: false },
      { letra: "C", texto: "Apenas o Diretor do Presídio pode determinar a elaboração do exame criminológico, sem controle judicial.", correta: false },
      { letra: "D", texto: "O exame criminológico é de realização proibida antes de decorridos 5 anos de cumprimento da pena.", correta: false },
      { letra: "E", texto: "A realização de exame criminológico passou a ser expressamente exigida por lei para a decisão sobre progressão de regime.", correta: true }
    ]
  }
];
