import { TAXONOMIA } from "./taxonomia.mjs";

export const lep03Questoes = [
  {
    idSlug: "lep-051",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A penitenciária destina-se ao condenado à pena de reclusão, em regime fechado, devendo a sua acomodação ser feita em cela individual.",
    explicacao: "GABARITO: CERTO. Art. 87 e 88 da LEP: A penitenciária destina-se aos condenados em regime fechado e o apenado será alojado em cela individual que conterá dormitório, aparelho sanitário e lavatório, com área mínima de 6 metros quadrados.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-052",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O cumprimento de pena privativa de liberdade em regime semiaberto deve ocorrer em estabelecimento específico previsto na Lei de Execução Penal. Trata-se da:",
    explicacao: "GABARITO: B. Art. 91 da LEP: 'A Colônia Agrícola, Industrial ou Similar destina-se ao cumprimento da pena em regime semi-aberto.'",
    alternativas: [
      { letra: "A", texto: "Penitenciária de Segurança Máxima.", correta: false },
      { letra: "B", texto: "Colônia Agrícola, Industrial ou similar.", correta: true },
      { letra: "C", texto: "Casa do Albergado.", correta: false },
      { letra: "D", texto: "Cadeia Pública da comarca.", correta: false },
      { letra: "E", texto: "Hospital de Custódia e Tratamento Psiquiátrico.", correta: false }
    ]
  },
  {
    idSlug: "lep-053",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Casa do Albergado destina-se ao cumprimento de pena privativa de liberdade em regime aberto e da pena de limitação de fim de semana, devendo situar-se em centro urbano, separada dos demais estabelecimentos e sem obstáculos físicos contra a fuga.",
    explicacao: "GABARITO: CERTO. Art. 93 e 94 da LEP: A Casa do Albergado destina-se ao regime aberto e limitação de fim de semana, situa-se em centro urbano e é caracterizada pela ausência de obstáculos físicos contra a fuga.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-054",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A Cadeia Pública destina-se, nos termos do art. 102 da Lei de Execução Penal, ao recolhimento de:",
    explicacao: "GABARITO: C. Art. 102 da LEP: 'A cadeia pública destina-se ao recolhimento de presos provisórios.' Cada comarca deve ter pelo menos uma cadeia pública.",
    alternativas: [
      { letra: "A", texto: "condenados definitivamente a penas superiores a 15 anos.", correta: false },
      { letra: "B", texto: "apenados em cumprimento de livramento condicional.", correta: false },
      { letra: "C", texto: "presos provisórios.", correta: true },
      { letra: "D", texto: "inimputáveis submetidos a medida de segurança de internação.", correta: false },
      { letra: "E", texto: "condenados em cumprimento de regime aberto exclusivamente.", correta: false }
    ]
  },
  {
    idSlug: "lep-055",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na hipótese de falta de vagas em estabelecimento adequado ao cumprimento de regime prisional fixado na sentença (semiaberto ou aberto), é lícito manter o apenado em regime mais gravoso por prazo indeterminado enquanto aguarda vaga.",
    explicacao: "GABARITO: ERRADO. Súmula Vinculante 56 do STF: 'A falta de estabelecimento penal adequado não autoriza a manutenção do condenado em regime prisional mais gravoso.' Devem ser aplicadas as medidas alternativas fixadas no RE 641.320/RS (como prisão domiciliar com monitoração eletrônica).",
    alternativas: [{ texto: "Certo", correta: false }, { texto: "Errado", correta: true }]
  },
  {
    idSlug: "lep-056",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 112 da LEP, alterado pela Lei nº 13.964/2019 (Pacote Anticrime), a pena privativa de liberdade será executada em forma progressiva. Qual é o percentual de cumprimento de pena exigido para progressão de regime de apenado primário, condenado por crime cometido sem violência à pessoa ou grave ameaça?",
    explicacao: "GABARITO: A. Art. 112, I, da LEP: 16% (dezesseis por cento) da pena, se o apenado for primário e o crime tiver sido cometido sem violência à pessoa ou grave ameaça.",
    alternativas: [
      { letra: "A", texto: "16% (dezesseis por cento).", correta: true },
      { letra: "B", texto: "20% (vinte por cento).", correta: false },
      { letra: "C", texto: "25% (vinte e cinco por cento).", correta: false },
      { letra: "D", texto: "30% (trinta por cento).", correta: false },
      { letra: "E", texto: "40% (quarenta por cento).", correta: false }
    ]
  },
  {
    idSlug: "lep-057",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Para o apenado reincidente na prática de crime cometido sem violência à pessoa ou grave ameaça, o percentual legal exigido para a progressão de regime é de 20% (vinte por cento) da pena.",
    explicacao: "GABARITO: CERTO. Art. 112, II, da LEP: 20% (vinte por cento) da pena, se o apenado for reincidente em crime cometido sem violência à pessoa ou grave ameaça.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-058",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Assinale a alternativa que indica corretamente o percentual legal para progressão de regime de apenado primário condenado por crime cometido com violência contra a pessoa ou grave ameaça (ex: roubo simples tentado):",
    explicacao: "GABARITO: C. Art. 112, III, da LEP: 25% (vinte e cinco por cento) da pena, se o apenado for primário e o crime tiver sido cometido com violência à pessoa ou grave ameaça.",
    alternativas: [
      { letra: "A", texto: "16% da pena.", correta: false },
      { letra: "B", texto: "20% da pena.", correta: false },
      { letra: "C", texto: "25% da pena.", correta: true },
      { letra: "D", texto: "30% da pena.", correta: false },
      { letra: "E", texto: "50% da pena.", correta: false }
    ]
  },
  {
    idSlug: "lep-059",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O apenado reincidente na prática de crime cometido com violência à pessoa ou grave ameaça necessita cumprir 30% (trinta por cento) da pena para obter a progressão de regime.",
    explicacao: "GABARITO: CERTO. Art. 112, IV, da LEP: 30% (trinta por cento) da pena, se o apenado for reincidente em crime cometido com violência à pessoa ou grave ameaça.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-060",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O percentual de 40% (quarenta por cento) de cumprimento da pena para progressão de regime, nos termos do art. 112, V, da LEP, é exigido para o apenado:",
    explicacao: "GABARITO: D. Art. 112, V, da LEP: 40% (quarenta por cento) da pena, se o apenado for condenado pela prática de crime hediondo ou equiparado, se for primário.",
    alternativas: [
      { letra: "A", texto: "reincidente em crime hediondo com resultado morte.", correta: false },
      { letra: "B", texto: "primário em crime comum sem violência à pessoa.", correta: false },
      { letra: "C", texto: "reincidente específico em tráfico de drogas.", correta: false },
      { letra: "D", texto: "condenado pela prática de crime hediondo ou equiparado, se for primário.", correta: true },
      { letra: "E", texto: "que exerce o comando individual de organização criminosa.", correta: false }
    ]
  },
  {
    idSlug: "lep-061",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal Federal",
    cargo_nome: "Agente Federal de Execução Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Exige-se o cumprimento de 50% (cinquenta por cento) da pena para a progressão de regime do condenado pela prática de crime hediondo ou equiparado com resultado morte, se for primário, sendo vedado o livramento condicional.",
    explicacao: "GABARITO: CERTO. Art. 112, VI, 'a', da LEP: 50% da pena para o condenado por crime hediondo ou equiparado, com resultado morte, se for primário, vedado o livramento condicional.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-062",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos do art. 112, VII e VIII, da LEP, os percentuais de 60% e 70% de cumprimento da pena para progressão de regime são destinados, respectivamente, a:",
    explicacao: "GABARITO: A. Art. 112, VII e VIII, da LEP: 60% para reincidente na prática de crime hediondo ou equiparado; e 70% para reincidente em crime hediondo ou equiparado com resultado morte (com livramento condicional vedado).",
    alternativas: [
      { letra: "A", texto: "reincidente em crime hediondo/equiparado (60%) e reincidente em crime hediondo/equiparado com resultado morte (70%).", correta: true },
      { letra: "B", texto: "primário em crime doloso (60%) e reincidente em furto qualificado (70%).", correta: false },
      { letra: "C", texto: "líder de milícia privada (60%) e condenado por genocídio tentado (70%).", correta: false },
      { letra: "D", texto: "apenado em RDD (60%) e apenado em penitenciária federal (70%).", correta: false },
      { letra: "E", texto: "condenado por corrupção passiva (60%) e lavagem de capitais (70%).", correta: false }
    ]
  },
  {
    idSlug: "lep-063",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "É inadmissível a chamada progressão de regime 'per saltum', sendo vedada a transferência direta do condenado do regime fechado para o regime aberto sem prévia passagem pelo regime semiaberto.",
    explicacao: "GABARITO: CERTO. Súmula 491 do STJ: 'É inadmissível a chamada progressão per saltum de regime prisional.' O apenado deve progredir gradativamente do fechado para o semiaberto e deste para o aberto.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-064",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em relação à regressão de regime prisional, o condenado que cumpre pena no regime semiaberto ou aberto poderá ser transferido para regime mais rigoroso (art. 118 da LEP) quando:",
    explicacao: "GABARITO: C. Art. 118, I e II, da LEP: O condenado fica sujeito à transferência para regime mais rigoroso quando praticar fato definido como crime doloso ou falta grave, ou sofrer condenação por crime anterior cuja nova pena torne incabível o regime atual.",
    alternativas: [
      { letra: "A", texto: "exercer seu direito de petição contra a administração penitenciária.", correta: false },
      { letra: "B", texto: "recusar-se a participar de culto religioso.", correta: false },
      { letra: "C", texto: "praticar fato definido como crime doloso ou falta grave.", correta: true },
      { letra: "D", texto: "cometer falta leve pela primeira vez.", correta: false },
      { letra: "E", texto: "for absolvido por negativa de autoria em ação penal superveniente.", correta: false }
    ]
  },
  {
    idSlug: "lep-065",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Diferentemente do que ocorre na progressão de regime prisional, a regressão de regime admite o salto direto (regressão per saltum), podendo o condenado que cumpre pena em regime aberto regredir diretamente para o regime fechado caso cometa falta grave.",
    explicacao: "GABARITO: CERTO. Jurisprudência pacífica do STF e STJ: O princípio da indeclinabilidade dos regimes intermediários veda a progressão per saltum, mas admite a regressão per saltum (do aberto direto para o fechado), consoante exegese do art. 118 da LEP.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-066",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Lei nº 13.769/2018 inseriu o § 3º no art. 112 da LEP, prevendo requisitos especiais de progressão de regime para a mulher gestante ou que for mãe ou responsável por crianças ou pessoas com deficiência. Para usufruir da fração benéfica de 1/8 (um oitavo), exige-se cumulativamente que:",
    explicacao: "GABARITO: B. Art. 112, § 3º, da LEP: não ter cometido crime com violência ou grave ameaça a pessoa; não ter cometido o crime contra seu filho ou dependente; ter cumprido ao menos 1/8 da pena no regime anterior; ser primária e ter bom comportamento carcerário; e não ter integrado organização criminosa.",
    alternativas: [
      { letra: "A", texto: "o crime tenha sido praticado com violência contra o próprio cônjuge.", correta: false },
      { letra: "B", texto: "não tenha cometido crime com violência ou grave ameaça nem contra seu filho/dependente, seja primária e não integre organização criminosa.", correta: true },
      { letra: "C", texto: "tenha prestado trabalho externo por no mínimo 3 anos.", correta: false },
      { letra: "D", texto: "possua filhos maiores de 18 anos plenamente capazes.", correta: false },
      { letra: "E", texto: "tenha ressarcido a vítima em décuplo.", correta: false }
    ]
  },
  {
    idSlug: "lep-067",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O cometimento de novo crime doloso ou falta grave pela mulher apenada que obteve progressão especial de 1/8 acarretará a revogação da progressão especial concedida com base no § 3º do art. 112 da LEP.",
    explicacao: "GABARITO: CERTO. Art. 112, § 4º, da LEP: 'O cometimento de novo crime doloso ou falta grave implicará a revogação do benefício previsto no § 3º deste artigo.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-068",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O Centro de Observação Criminológica, segundo a Lei nº 7.210/1984, destina-se a:",
    explicacao: "GABARITO: E. Art. 96 e 97 da LEP: 'No Centro de Observação realizar-se-ão os exames gerais e o criminológico, cujos resultados serão encaminhados à Comissão Técnica de Classificação.'",
    alternativas: [
      { letra: "A", texto: "abrigar presos provisórios de alta periculosidade exclusivamente.", correta: false },
      { letra: "B", texto: "executar medidas de segurança em regime ambulatorial.", correta: false },
      { letra: "C", texto: "alojar presas gestantes em período de puerpério.", correta: false },
      { letra: "D", texto: "promover o cumprimento de penas restritivas de direitos.", correta: false },
      { letra: "E", texto: "realizar os exames gerais e o exame criminológico dos apenados.", correta: true }
    ]
  },
  {
    idSlug: "lep-069",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Hospital de Custódia e Tratamento Psiquiátrico destina-se aos inimputáveis e semi-imputáveis a quem tenha sido aplicada medida de segurança detentiva de internação.",
    explicacao: "GABARITO: CERTO. Art. 99 da LEP: 'O Hospital de Custódia e Tratamento Psiquiátrico destina-se aos inimputáveis e semi-imputáveis referidos no artigo 26 e seu parágrafo único do Código Penal.'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-070",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O estabelecimento penal destinado a mulheres deverá ser dotado de berçário onde as condenadas possam amamentar seus filhos, no mínimo, até:",
    explicacao: "GABARITO: A. Art. 89 da LEP c/c art. 83, § 2º, da LEP: Os estabelecimentos penais femininos serão dotados de berçário onde as presas possam amamentar seus filhos, no mínimo, até 6 (seis) meses de idade.",
    alternativas: [
      { letra: "A", texto: "6 (seis) meses de idade.", correta: true },
      { letra: "B", texto: "1 ano de idade.", correta: false },
      { letra: "C", texto: "2 anos de idade.", correta: false },
      { letra: "D", texto: "3 anos de idade.", correta: false },
      { letra: "E", texto: "4 anos de idade.", correta: false }
    ]
  },
  {
    idSlug: "lep-071",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal Federal",
    cargo_nome: "Policial Penal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O condenado por integrar organização criminosa armada ou que mantenha vínculo com facção criminosa não poderá progredir de regime se houver elementos probatórios que indiquem a manutenção do vínculo associativo.",
    explicacao: "GABARITO: CERTO. Art. 112, § 1º, da LEP (inserido pela Lei nº 13.964/2019): Em todos os casos, o apenado só terá direito à progressão de regime se ostentar bom comportamento carcerário, e, caso condenado por integrar organização criminosa ou associação, a progressão dependerá da ausência de vínculo com a organização criminosa.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-072",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Mário, condenado primário pela prática de latrocínio tentado (crime hediondo com violência grave sem morte consumada), pretende obter progressão de regime prisional. Sob a égide da Lei nº 13.964/2019, o percentual de pena a ser cumprido por Mário é de:",
    explicacao: "GABARITO: C. Art. 112, V, da LEP: 40% da pena se o apenado for condenado por crime hediondo ou equiparado e for primário (desde que não tenha ocorrido resultado morte, hipótese em que seria 50%).",
    alternativas: [
      { letra: "A", texto: "16% da pena.", correta: false },
      { letra: "B", texto: "25% da pena.", correta: false },
      { letra: "C", texto: "40% da pena.", correta: true },
      { letra: "D", texto: "50% da pena.", correta: false },
      { letra: "E", texto: "70% da pena.", correta: false }
    ]
  },
  {
    idSlug: "lep-073",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A decisão judicial que determina a regressão cautelar de regime prisional pode ser proferida sem prévia oitiva do apenado, resguardando-se a oitiva prévia para a decisão de regressão definitiva.",
    explicacao: "GABARITO: CERTO. Jurisprudência do STJ: É admitida a regressão cautelar de regime prisional sem prévia oitiva do condenado quando este pratica falta grave ou novo crime doloso, devendo a audiência de justificação ser realizada antes da homologação da regressão definitiva.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "lep-074",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O preso que cumpre pena privativa de liberdade em regime fechado tem direito ao banho de sol diário. De acordo com as normas gerais da LEP e os parâmetros do RDD, o período mínimo diário assegurado para banho de sol no regime fechado padrão e no RDD é de:",
    explicacao: "GABARITO: A. No regime fechado padrão e no RDD (art. 52, IV, LEP), é assegurado banho de sol por no mínimo 2 (duas) horas diárias.",
    alternativas: [
      { letra: "A", texto: "2 (duas) horas diárias.", correta: true },
      { letra: "B", texto: "30 minutos diários.", correta: false },
      { letra: "C", texto: "4 horas diárias.", correta: false },
      { letra: "D", texto: "1 hora a cada dois dias.", correta: false },
      { letra: "E", texto: "6 horas diárias aos fins de semana.", correta: false }
    ]
  },
  {
    idSlug: "lep-075",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.penas_extincao_punibilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A concessão da prisão domiciliar prevista no art. 117 da LEP destina-se originariamente ao beneficiário de regime aberto, podendo, segundo entendimento consolidado da jurisprudência, ser estendida excepcionalmente a apenados dos regimes fechado e semiaberto em casos de grave doença que não possa ser tratada no estabelecimento prisional.",
    explicacao: "GABARITO: CERTO. Art. 117 da LEP c/c jurisprudência pacífica do STF/STJ: Embora a prisão domiciliar seja legalmente restrita ao regime aberto, admite-se excepcionalmente a concessão humanitária a presos dos regimes semiaberto e fechado acometidos de enfermidade grave sem tratamento na unidade prisional.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  }
];
