import { TAXONOMIA } from "./taxonomia.mjs";

export const penal01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-penal-01-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O Código Penal brasileiro adota expressamente a teoria da atividade para o tempo do crime (considera-se praticado o crime no momento da ação ou omissão, ainda que outro seja o momento do resultado) e a teoria da ubiqüidade para o lugar do crime.",
    explicacao: "GABARITO: CERTO. Art. 4º do CP (tempo do crime = teoria da atividade) e Art. 6º do CP (lugar do crime = teoria da ubiquidade/mista: considera-se praticado o crime no lugar em que ocorreu a ação ou omissão, bem como onde se produziu ou deveria produzir-se o resultado). Mnemônico: LUTA (Lugar Ubiquidade, Tempo Atividade).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Durante diligência em área de vegetação densa, um agente de polícia avistou vulto atrás de uma árvore e, acreditando piamente tratar-se de um animal silvestre perigoso prestes a atacar, efetuou disparo defensivo que veio a ferir um colega camuflado. Sob a teoria geral do delito (art. 20, caput, do CP), o erro sobre elemento constitutivo do tipo legal de crime (erro de tipo essencial) exclui o dolo da conduta, mas permite a punição a título de crime culposo, se houver previsão legal.",
    explicacao: "GABARITO: CERTO. Art. 20, caput, do Código Penal: 'O erro sobre elemento constitutivo do tipo legal de crime exclui o dolo, mas permite a punição por crime culposo, se previsto em lei.' Trata-se do erro de tipo essencial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Na desistência voluntária e no arrependimento eficaz (Art. 15 do CP), o agente responde apenas pelos atos já praticados (tentativa abandonada / ponte de ouro), afastando-se a imputação da tentativa do crime inicialmente pretendido.",
    explicacao: "GABARITO: CERTO. Art. 15 do CP: 'O agente que, voluntariamente, desiste de prosseguir na execução ou impede que o resultado se produza, só responde pelos atos já praticados.' Conhecido na doutrina como ponte de ouro de Von Liszt.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa até o trânsito em julgado da sentença condenatória, por ato voluntário do agente, a pena será reduzida de um a dois terços (arrependimento posterior).",
    explicacao: "GABARITO: ERRADO. Art. 16 do CP (arrependimento posterior): a reparação do dano ou restituição da coisa deve ocorrer até o RECEBIMENTO DA DENÚNCIA OU DA QUEIXA, e não até o trânsito em julgado.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-01-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em operação da PRF, três suspeitos foram interceptados logo após a execução coordenada de roubo de carga em rodovia interestadual, cada qual exercendo funções distintas na empreitada delitiva. Sob a ótica do concurso de pessoas e da teoria monista (ou unitária) adotada como regra geral pelo art. 29 do Código Penal brasileiro, todos os envolvidos respondem pela mesma infração penal, incidindo nas penas a esta cominadas na medida de sua respectiva culpabilidade.",
    explicacao: "GABARITO: CERTO. Art. 29, caput, do CP: o ordenamento jurídico brasileiro adotou a teoria monista (unitária ou igualitária) mitigada pela culpabilidade individual, preconizando que quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A legítima defesa putativa, decorrente de erro plenamente justificado pelas circunstâncias sobre situação de fato que, se existisse, tornaria a ação legítima, constitui hipótese de descriminante putativa tratada pelo Código Penal como erro de tipo permissivo.",
    explicacao: "GABARITO: CERTO. Art. 20, § 1º, do CP: 'É isento de pena quem, por erro plenamente justificado pelas circunstâncias, supõe situação de fato que, se existisse, tornaria a ação legítima.' A teoria limitada da culpabilidade adotada pelo CP trata o erro sobre situação fática justificante como erro de tipo permissivo.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante tumulto em unidade penitenciária, um policial penal utilizou moderadamente os meios disponíveis para repelir agressão injusta e atual deflagrada por detento armado. Contudo, após desarmar e imobilizar totalmente o agressor que já estava rendido no solo, o agente desferiu reiterados golpes desnecessários, causando-lhe lesões corporais graves. Nessa situação hipotética, o policial penal responderá penalmente pelo excesso doloso praticado.",
    explicacao: "GABARITO: CERTO. Art. 23, parágrafo único, do Código Penal: 'O agente, em qualquer das hipóteses deste artigo, responderá pelo excesso doloso ou culposo.' Tendo ultrapassado os limites da moderação e da proporcionalidade após cessada a agressão atual, o agente responde pelo resultado decorrente do excesso.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Ficam sujeitos à lei brasileira, embora cometidos no estrangeiro (extraterritorialidade incondicionada), os crimes contra a vida ou a liberdade do Presidente da República e os crimes contra a administração pública praticados por quem está a seu serviço.",
    explicacao: "GABARITO: CERTO. Art. 7º, I, 'a' e 'c', do CP: extraterritorialidade incondicionada da lei penal brasileira, aplicando-se a lei brasileira mesmo que o agente seja absolvido ou condenado no exterior.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No crime continuado (Art. 71 do CP), quando o agente, mediante mais de uma ação ou omissão, pratica dois ou mais crimes da mesma espécie e, pelas condições de tempo, lugar, maneira de execução e outras semelhantes, devem os subseqüentes ser havidos como continuação do primeiro, aplica-se-lhe a pena de um só dos crimes, se idênticas, ou a mais grave, se diversas, aumentada, em qualquer caso, de um sexto a dois terços.",
    explicacao: "GABARITO: CERTO. Art. 71, caput, do CP consagra a teoria da ficção jurídica no crime continuado com o sistema de exasperação da pena.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A coação física irresistível (vis absoluta) exclui a própria conduta por ausência de voluntariedade (afastando o fato típico), ao passo que a coação moral irresistível (vis compulsiva) exclui a culpabilidade pela inexigibilidade de conduta diversa.",
    explicacao: "GABARITO: CERTO. Coação física irresistível elimina a conduta/fato típico. Coação moral irresistível (art. 22 do CP) mantém o fato típico e ilícito, mas isenta de pena o coacto por inexigibilidade de conduta diversa (exclui a culpabilidade), respondendo apenas o autor da coação.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-01-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do Art. 17 do Código Penal, não se pune a tentativa quando, por ineficácia absoluta do meio ou por absoluta impropriedade do objeto, é impossível consumar-se o crime. Trata-se do denominado:",
    explicacao: "GABARITO: B. Art. 17 do CP: crime impossível (tentativa inidônea / quase-crime / tentativa inadequada). A teoria objetiva temperada (ou intermediária) foi adotada pelo Código Penal.",
    alternativas: [
      { texto: "Crime putativo por erro de tipo.", correta: false },
      { texto: "Crime impossível (tentativa inidônea).", correta: true },
      { texto: "Arrependimento eficaz.", correta: false },
      { texto: "Crime progressivo qualificado.", correta: false },
      { texto: "Delito putativo por obra do agente provocador consumado.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "No aberratio ictus (erro na execução com resultado único), previsto no Art. 73, primeira parte, do Código Penal, quando o agente, por acidente ou erro no uso dos meios de execução, atinge pessoa diversa da pretendida:",
    explicacao: "GABARITO: D. Art. 73 do CP: responde o agente como se tivesse praticado o crime contra aquela que queria atingir (aplica-se a regra do art. 20, § 3º - consideram-se as qualidades e condições da vítima virtual/pretendida, e não da vítima real atingida por erro).",
    alternativas: [
      { texto: "Responde por homicídio culposo exclusivamente.", correta: false },
      { texto: "O fato é atípico em razão da ausência de dolo em relação à vítima fatal.", correta: false },
      { texto: "Consideram-se estritamente as qualidades da vítima real atingida para fins de fixação da pena.", correta: false },
      { texto: "Responde como se tivesse praticado o crime contra a pessoa visada, considerando-se as qualidades e condições da vítima que pretendia atingir.", correta: true },
      { texto: "Aplica-se a pena do concurso material obrigatório entre tentativa branca e lesão corporal culposa.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No concurso formal próprio ou perfeito (Art. 70, primeira parte, do CP), quando o agente, mediante uma só ação ou omissão, pratica dois ou mais crimes idênticos ou não:",
    explicacao: "GABARITO: A. Art. 70, primeira parte, do CP: aplica-se-lhe a mais grave das penas cabíveis ou, se iguais, somente uma delas, mas aumentada, em qualquer caso, de um sexto até metade (sistema de exasperação).",
    alternativas: [
      { texto: "Aplica-se a mais grave das penas cabíveis ou, se iguais, somente uma delas, aumentada de um sexto até metade (sistema de exasperação).", correta: true },
      { texto: "Somam-se cumulativamente todas as penas privativas de liberdade cominadas (sistema de cúmulo material).", correta: false },
      { texto: "O agente é isento de pena quanto ao segundo crime praticado.", correta: false },
      { texto: "Aplica-se unicamente a pena de multa com perdão judicial.", correta: false },
      { texto: "O crime de menor potencial ofensivo absorve o crime mais grave.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A lei penal temporária ou excepcional, nos termos do Art. 3º do Código Penal:",
    explicacao: "GABARITO: C. Art. 3º do CP: 'A lei excepcional ou temporária, embora decorrido o período de sua duração ou cessadas as circunstâncias que a determinaram, aplica-se ao fato praticado durante sua vigência' (autorrevogabilidade e ultratividade gravosa).",
    alternativas: [
      { texto: "Não se aplica aos fatos praticados durante sua vigência após cessada a situação de emergência.", correta: false },
      { texto: "Revoga permanentemente todos os tipos penais anteriores do Código Penal.", correta: false },
      { texto: "Aplica-se ao fato praticado durante sua vigência, embora decorrido o período de sua duração ou cessadas as circunstâncias que a determinaram (ultratividade).", correta: true },
      { texto: "Depende de referendo popular confirmatório para possuir eficácia retroativa.", correta: false },
      { texto: "Só produz efeitos se benéfica ao réu em qualquer hipótese.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos crimes omissivos impróprios (comissivos por omissão), o dever de agir incumbe a quem tenha por lei obrigação de cuidado, proteção ou vigilância, a quem de outra forma assumiu a responsabilidade de impedir o resultado, ou a quem:",
    explicacao: "GABARITO: E. Art. 13, § 2º, 'c', do CP: 'com seu comportamento anterior, criou o risco da ocorrência do resultado' (figura do garante ou garantidor por ingerência).",
    alternativas: [
      { texto: "Possua formação universitária em segurança pública.", correta: false },
      { texto: "Presenciou o fato a uma distância inferior a dez metros.", correta: false },
      { texto: "Resida no mesmo condomínio residencial da vítima.", correta: false },
      { texto: "Seja titular de conta bancária conjunta com o autor do dano.", correta: false },
      { texto: "Com seu comportamento anterior, criou o risco da ocorrência do resultado.", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-01-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A embriaguez voluntária ou culposa pelo álcool ou por substância de efeitos análogos, nos termos do Art. 28, II, do Código Penal e da teoria da actio libera in causa:",
    explicacao: "GABARITO: B. Art. 28, II, do CP: não excluem a imputabilidade penal a emoção ou a paixão e a embriaguez voluntária ou culposa. Aplica-se a teoria da 'actio libera in causa' (a ação foi livre no ato de ingerir a substância). Apenas a embriaguez completa decorrente de caso fortuito ou força maior isenta de pena.",
    alternativas: [
      { texto: "Exclui sempre a culpabilidade do agente.", correta: false },
      { texto: "Não exclui a imputabilidade penal do agente.", correta: true },
      { texto: "Transforma o crime doloso obrigatoriamente em culposo.", correta: false },
      { texto: "Extingue a punibilidade se o agente for primário.", correta: false },
      { texto: "Reduz a pena compulsoriamente pela metade.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-01-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos do Art. 29, § 1º, do Código Penal, se a participação do agente for de menor importância:",
    explicacao: "GABARITO: D. Art. 29, § 1º, do CP: 'Se a participação for de menor importância, a pena pode ser diminuída de um sexto a um terço.'",
    alternativas: [
      { texto: "A pena será extinta pelo perdão judicial.", correta: false },
      { texto: "O agente responderá apenas por contravenção penal.", correta: false },
      { texto: "A pena será substituída compulsoriamente por admoestação verbal.", correta: false },
      { texto: "A pena pode ser diminuída de um sexto a um terço.", correta: true },
      { texto: "A pena será triplicada em relação ao autor principal.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Entende-se em legítima defesa quem, usando moderadamente dos meios necessários, repele injusta agressão, humana, atual ou iminente, a direito seu ou de outrem. Conforme a Lei nº 13.964/2019 (Pacote Anticrime), inclui-se expressamente como hipótese legal de legítima defesa:",
    explicacao: "GABARITO: A. Art. 25, parágrafo único, do CP (incluído pela Lei 13.964/2019): 'Observados os requisitos previstos no caput deste artigo, considera-se também em legítima defesa o agente de segurança pública que repele agressão ou risco de agressão a vítima mantida refém durante a prática de crimes.'",
    alternativas: [
      { texto: "O agente de segurança pública que repele agressão ou risco de agressão a vítima mantida refém durante a prática de crimes.", correta: true },
      { texto: "O policial que atira em suspeito desarmado em fuga para evitar que ele escape.", correta: false },
      { texto: "O cidadão que espanca o ladrão já imobilizado e desmaiado.", correta: false },
      { texto: "O proprietário que instala cerca elétrica letal sem qualquer sinalização visual.", correta: false },
      { texto: "O comerciante que reage com disparos contra quem praticou furto famélico dias antes.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.aplicacao_lei_penal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Ninguém pode ser punido por fato que lei posterior deixa de considerar crime, cessando em virtude dela a execução e os efeitos penais da sentença condenatória. Trata-se do instituto da:",
    explicacao: "GABARITO: C. Art. 2º, caput, do CP: Abolitio criminis (faz cessar a execução da pena e todos os efeitos penais principais e secundários da condenação, permanecendo apenas os efeitos civis).",
    alternativas: [
      { texto: "Novatio legis in pejus.", correta: false },
      { texto: "Lex mitior temporalis.", correta: false },
      { texto: "Abolitio criminis.", correta: true },
      { texto: "Prescrição da pretensão punitiva.", correta: false },
      { texto: "Decadência do direito de queixa.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O erro sobre a ilicitude do fato (erro de proibição), quando inevitável (escusável), nos termos do Art. 21 do Código Penal:",
    explicacao: "GABARITO: E. Art. 21, caput, do CP: o erro sobre a ilicitude do fato, se inevitável, isenta de pena (exclui a culpabilidade pela falta de potencial consciência da ilicitude); se evitável, poderá diminuí-la de um sexto a um terço.",
    alternativas: [
      { texto: "Exclui a tipicidade formal do crime.", correta: false },
      { texto: "Elimina o dolo e permite punição culposa automática.", correta: false },
      { texto: "Exclui a ilicitude da conduta.", correta: false },
      { texto: "Agrava a pena base em um terço.", correta: false },
      { texto: "Isenta o agente de pena (exclui a culpabilidade).", correta: true },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-01-021",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Durante um motim com foco de incêndio em pavilhão prisional, um policial penal devidamente equipado e encarregado da guarda e contenção recusou-se a intervir para retirar internos em situação de risco iminente, pretendendo amparar sua inação na excludente do estado de necessidade. Nos termos do art. 24, § 1º, do Código Penal, não pode alegar estado de necessidade quem:",
    explicacao: "GABARITO: B. Art. 24, § 1º, do CP: 'Não pode alegar estado de necessidade quem tinha o dever legal de enfrentar o perigo' (hipótese típica aplicável aos agentes de segurança pública e bombeiros no exercício de suas atribuições).",
    alternativas: [
      { texto: "For ocupante de cargo efetivo há menos de três anos.", correta: false },
      { texto: "Tinha o dever legal de enfrentar o perigo.", correta: true },
      { texto: "Não tiver arma de fogo de porte pessoal no momento do fato.", correta: false },
      { texto: "Já tiver respondido a sindicância administrativa pretérita.", correta: false },
      { texto: "For o responsável pela guarda patrimonial das chaves da unidade.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-022",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quando o agente, mediante mais de uma ação ou omissão, pratica dois ou mais crimes, idênticos ou não, aplicam-se-lhe cumulativamente as penas privativas de liberdade em que haja incorrido. Trata-se do concurso:",
    explicacao: "GABARITO: A. Art. 69 do CP: concurso material (cúmulo material).",
    alternativas: [
      { texto: "Material (real).", correta: true },
      { texto: "Formal próprio.", correta: false },
      { texto: "Continuado comum.", correta: false },
      { texto: "Aparente de normas.", correta: false },
      { texto: "Formal impróprio cumulativo.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-01-023",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Uma equipe da Polícia Militar surpreendeu um indivíduo que, portando uma chave falsa, já havia forçado e danificado a fechadura da porta de uma residência para nela ingressar e furtar bens. Ao avistar os policiais, o agente tentou fugir, sendo imediatamente detido sem conseguir consumar a subtração. Sob a ótica do art. 14, II, do Código Penal, diz-se o crime tentado quando:",
    explicacao: "GABARITO: C. Art. 14, II, do CP: 'tentado, quando, iniciada a execução, não se consuma por circunstâncias alheias à vontade do agente.'",
    alternativas: [
      { texto: "O agente se arrepende e repara o dano antes da instauração do inquérito policial.", correta: false },
      { texto: "O sujeito desiste voluntariamente antes mesmo de iniciar qualquer ato executório.", correta: false },
      { texto: "Iniciada a execução, o crime não se consuma por circunstâncias alheias à vontade do agente.", correta: true },
      { texto: "O resultado naturalístico ocorre em momento anterior à ação principal.", correta: false },
      { texto: "A lei penal superveniente deixa de considerar a conduta como ilícito típico.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-01-024",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.teoria_crime,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "São elementos integrantes da culpabilidade segundo a concepção finalista tripartite da teoria do crime:",
    explicacao: "GABARITO: E. A teoria finalista adota a culpabilidade puramente normativa, composta por: 1) Imputabilidade penal; 2) Potencial consciência da ilicitude; 3) Exigibilidade de conduta diversa (o dolo e a culpa migraram para o fato típico).",
    alternativas: [
      { texto: "Conduta, nexo causal e dolo natural.", correta: false },
      { texto: "Tipicidade, antijuridicidade e punibilidade.", correta: false },
      { texto: "Ilicitude, causalidade adequada e resultado naturalístico.", correta: false },
      { texto: "Coação moral relativa e culpa consciente.", correta: false },
      { texto: "Imputabilidade penal, potencial consciência da ilicitude e exigibilidade de conduta diversa.", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-01-025",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.concurso_pessoas_crimes,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Um particular associou-se conscientemente a um Guarda Municipal para subtrair rádios comunicadores da corporação, ciente da qualidade funcional pública de seu comparsa. Ao analisar a imputação do crime funcional de peculato a ambos, incide a regra do art. 30 do Código Penal, segundo a qual as circunstâncias e condições de caráter pessoal não se comunicam entre os coautores, SALVO quando:",
    explicacao: "GABARITO: B. Art. 30 do CP: 'Não se comunicam as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime.' Sendo a qualidade de funcionário público elementar do peculato (art. 312 do CP), ela se estende ao particular que tinha ciência dessa condição.",
    alternativas: [
      { texto: "O comparsa prestar confissão espontânea perante a autoridade judiciária.", correta: false },
      { texto: "Forem elementares do tipo legal do crime.", correta: true },
      { texto: "O delito for praticado mediante grave ameaça a terceiros.", correta: false },
      { texto: "A pena cominada for exclusivamente privativa de liberdade em regime fechado.", correta: false },
      { texto: "O fato for tipificado em lei penal especial não codificada.", correta: false },
    ],
  },
];
