import { TAXONOMIA } from "./taxonomia.mjs";

export const adm01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-adm-01-001",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O poder de polícia administrativa caracteriza-se como a atividade da administração pública que limita ou disciplina direito, interesse ou liberdade, regulando a prática de ato ou a abstenção de fato em razão do interesse público concernente à segurança, à higiene e à ordem.",
    explicacao: "GABARITO: CERTO. Art. 78 do CTN e doutrina de Direito Administrativo: definição clássica de poder de polícia administrativa, limitador de direitos e liberdades em prol do interesse da coletividade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-002",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante correição extraordinária, constatou-se que determinado delegado determinou a remoção compulsória de um escrivão com o intuito exclusivo de perseguição pessoal, ao passo que, em outra unidade, um agente expediu portaria de instauração de inquérito privativa de autoridade policial. Sob a teoria do abuso de poder, a primeira conduta configura desvio de finalidade (vício de finalidade) e a segunda consubstancia excesso de poder (vício de competência).",
    explicacao: "GABARITO: CERTO. O abuso de poder é gênero que compreende duas espécies: o excesso de poder (quando o agente público atua além dos limites de sua competência legal) e o desvio de finalidade ou poder (quando o ato é praticado para alcançar fim diverso daquele fixado em lei ou para atender a interesses particulares e escusos).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-003",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "São atributos do ato administrativo a presunção de legitimidade e veracidade, a autoexecutoriedade, a tipicidade e a imperatividade, estando todos eles presentes indistintamente em qualquer espécie de ato administrativo, inclusive nos enunciativos e negociais.",
    explicacao: "GABARITO: ERRADO. Nem todos os atos administrativos possuem imperatividade e autoexecutoriedade. Por exemplo, os atos negociais (licença, autorização) e enunciativos (certidões, atestados) não gozam de imperatividade nem de autoexecutoriedade.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-01-004",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Ao constatar que a portaria de promoção funcional de determinados policiais continha vício insanável de legalidade quanto aos critérios objetivos de antiguidade, a própria Administração Pública declarou a anulação do ato no exercício da autotutela. Nesse contexto, a anulação produz efeitos retroativos (ex tunc) e independe de prévia autorização judicial.",
    explicacao: "GABARITO: CERTO. Súmula 473 do STF: 'A administração pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos...' A anulação tem eficácia retroativa (ex tunc) e decorre do princípio da autotutela administrativa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-005",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante patrulhamento ostensivo de rotina, uma viatura da Polícia Militar colidiu contra um veículo particular estacionado regularmente em via pública, causando avarias materiais ao proprietário. Nessa hipótese, sob a sistemática da responsabilidade civil extracontratual do Estado (art. 37, § 6º, da CF/88), a pessoa jurídica de direito público responde objetivamente pelo dano perante a vítima, resguardado o direito de regresso contra o policial condutor mediante comprovação de dolo ou culpa.",
    explicacao: "GABARITO: CERTO. Art. 37, § 6º, da CF/88: o Estado responde objetivamente pelos danos que seus agentes causarem a terceiros nessa qualidade (teoria do risco administrativo). Na ação regressiva contra o agente público causador direto do dano, a responsabilidade é de natureza subjetiva, exigindo-se a demonstração de dolo ou culpa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-006",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Segundo a tese de repercussão geral firmada pelo STF (Tema 940), a ação de indenização por danos causados por agente público deve ser proposta diretamente em face da pessoa jurídica de direito público ou da pessoa jurídica de direito privado prestadora de serviço público, sendo vedado o ajuizamento da ação diretamente contra o agente público causador do dano.",
    explicacao: "GABARITO: CERTO. STF no Tema 940 (RE 1.027.633): consagrou a teoria da dupla garantia. O particular lesado deve acionar a pessoa jurídica estatal/concessionária, cabendo a esta mover ação regressiva contra o servidor se houver dolo ou culpa, descabendo litisconsórcio passivo inicial facultativo ou ação direta contra o servidor.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-007",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme tese fixada pelo STF no Tema 532 da Repercussão Geral, é constitucional a delegação do poder de polícia sancionatório (aplicação de multas de trânsito) a pessoas jurídicas de direito privado integrantes da administração pública indireta de capital social majoritariamente público que prestem exclusivamente serviço público de atuação própria do Estado e em regime não concorrencial.",
    explicacao: "GABARITO: CERTO. STF no Tema 532 (RE 633.782): admite a delegação das fases de consentimento, fiscalização e sanção (aplicação de multas) a entidades estatais de direito privado (empresas públicas ou SEM) prestadoras de serviços públicos exclusivos em regime não concorrencial (ex: CET/SP, BHTrans, etc.).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-008",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "São elementos (ou requisitos de validade) essenciais do ato administrativo: competência, finalidade, forma, motivo e objeto.",
    explicacao: "GABARITO: CERTO. Os cinco elementos de validade do ato administrativo são: Competência, Finalidade, Forma, Motivo e Objeto (mnemônico clássico: COFIFOMOB).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-009",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O poder hierárquico confere à autoridade superior as prerrogativas de dar ordens, fiscalizar, delegar e avocar competências, bem como aplicar sanções disciplinares aos servidores subordinados.",
    explicacao: "GABARITO: CERTO. O poder hierárquico estrutura a subordinação funcional interna na Administração Pública, permitindo controle, comando, delegação/avocação e apuração disciplinar interna.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-010",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A culpa exclusiva da vítima e a força maior absoluta constituem causas excludentes do nexo causal na responsabilidade civil do Estado baseada na teoria do risco administrativo, afastando o dever de indenizar.",
    explicacao: "GABARITO: CERTO. A teoria do risco administrativo admite excludentes do nexo causal: culpa exclusiva da vítima, fato exclusivo de terceiro e caso fortuito/força maior.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-01-011",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A revogação do ato administrativo fundamenta-se em juízo de conveniência e oportunidade (mérito administrativo). Sobre a revogação, é correto afirmar que:",
    explicacao: "GABARITO: D. A revogação extingue ato administrativo válido e perfeito por motivos supervenientes de conveniência e oportunidade, operando efeitos prospectivos (ex nunc) e sendo privativa da Administração (o Judiciário não revoga atos do Executivo no mérito).",
    alternativas: [
      { texto: "Opera efeitos retroativos (ex tunc), desfazendo todos os atos jurídicos perfeitos passados.", correta: false },
      { texto: "Pode ser pronunciada pelo Poder Judiciário no exercício de sua função jurisdicional sobre atos do Executivo.", correta: false },
      { texto: "Aplica-se exclusivamente a atos administrativos vinculados e consumados.", correta: false },
      { texto: "Produz efeitos prospectivos (ex nunc) e incide apenas sobre atos discricionários válidos, sendo privativa da Administração Pública.", correta: true },
      { texto: "Depende de demonstração de vício insanável de competência do agente público.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-012",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O ciclo do poder de polícia desdobra-se em quatro fases distintas: ordem de polícia (legislação), consentimento de polícia, fiscalização de polícia e sanção de polícia. É exemplo de ato típico da fase de 'consentimento de polícia':",
    explicacao: "GABARITO: B. O consentimento de polícia consiste na anuência prévia da Administração para o exercício de atividade privada condicionada (ex: concessão de licença para dirigir ou porte de arma de fogo).",
    alternativas: [
      { texto: "A lavratura de auto de infração por excesso de velocidade.", correta: false },
      { texto: "A expedição de porte de arma de fogo ou Carteira Nacional de Habilitação.", correta: true },
      { texto: "A edição de decreto regulamentando limites de ruído urbano.", correta: false },
      { texto: "A apreensão de mercadorias contrabandeadas em blitz rodoviária.", correta: false },
      { texto: "A interdição cautelar de estabelecimento comercial com alimentos vencidos.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-013",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em caso de danos causados a terceiros por disparos de arma de fogo realizados por policial de folga que se identificou como autoridade policial e interveio em assalto utilizando armamento da corporação, a jurisprudência pacífica do STF estabelece que:",
    explicacao: "GABARITO: C. O STF entende que o Estado responde objetivamente pelos danos causados por policial, mesmo de folga, quando este atua invocando a qualidade de policial e/ou utilizando armamento institucional da corporação.",
    alternativas: [
      { texto: "O Estado está isento de responsabilidade por se tratar de ato puramente privado do servidor.", correta: false },
      { texto: "A vítima deve ajuizar a ação indenizatória pessoalmente contra o policial militar em vara cível.", correta: false },
      { texto: "A responsabilidade civil do Estado é objetiva, pois o agente público atuou ostentando a sua condição funcional com arma pública.", correta: true },
      { texto: "A reparação dependerá de prévia condenação do servidor em processo penal transitado em julgado.", correta: false },
      { texto: "Aplica-se a responsabilidade subjetiva do Estado com necessidade de prova de culpa anônima do serviço.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-014",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A convalidação (ou sanatória) do ato administrativo é o ato pelo qual a Administração corrige vício existente em ato ilegal anterior. São elementos passíveis de convalidação quando o defeito for sanável:",
    explicacao: "GABARITO: A. Apenas os vícios de competência (quanto à pessoa, desde que não exclusiva) e forma (desde que a forma não seja essencial à validade do ato) admitem convalidação.",
    alternativas: [
      { texto: "Competência (quanto à pessoa, não exclusiva) e forma (não essencial).", correta: true },
      { texto: "Motivo e objeto ilícito.", correta: false },
      { texto: "Finalidade desviada e motivo falso.", correta: false },
      { texto: "Objeto juridicamente impossível e finalidade privada.", correta: false },
      { texto: "Competência em razão da matéria privativa e motivo inexistente.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-015",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O poder regulamentar (ou normativo) da administração pública confere ao Chefe do Poder Executivo a prerrogativa de expedir decretos e regulamentos para:",
    explicacao: "GABARITO: E. Art. 84, IV, da CF/88: 'sancionar, promulgar e fazer publicar as leis, bem como expedir decretos e regulamentos para sua fiel execução'. O regulamento de execução não pode inovar na ordem jurídica criando direitos ou obrigações primárias não previstos em lei.",
    alternativas: [
      { texto: "Criar novas figuras penais e agravar sanções processuais sem prévia lei.", correta: false },
      { texto: "Modificar a estrutura de tributos e majorar alíquotas de impostos ordinários.", correta: false },
      { texto: "Revogar leis complementares aprovadas pelo Congresso Nacional.", correta: false },
      { texto: "Restringir direitos fundamentais sem autorização constitucional expressa.", correta: false },
      { texto: "A fiel execução das leis, explicitando seu conteúdo sem criar direitos ou obrigações novas não previstas no texto legal primário.", correta: true },
    ],
  },
  {
    idSlug: "b9-adm-01-016",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em uma via pública urbana, um motorista teve pertences furtados do interior de seu veículo após breve parada no acostamento, sob a alegação de que não havia patrulhamento ostensivo permanente naquele trecho no momento exato da ocorrência. Em relação à pretensão indenizatória ajuizada contra a Fazenda Pública, a jurisprudência dominante do STJ e do STF estabelece que em hipóteses de dano decorrente de omissão estatal genérica (falta do serviço):",
    explicacao: "GABARITO: B. Em caso de omissão genérica do Estado (falta do serviço / faute du service), a jurisprudência majoritária exige a responsabilidade subjetiva (comprovação de culpa administrativa, ineficiência ou atraso intolerável do serviço). Por outro lado, na omissão específica (dever legal de custódia e garantia, como na morte de custodiado em presídio), a responsabilidade é objetiva.",
    alternativas: [
      { texto: "O Estado responde de forma objetiva sob a modalidade do risco integral, prescindindo de culpa.", correta: false },
      { texto: "Aplica-se a responsabilidade subjetiva (teoria da faute du service), exigindo a demonstração de que o Estado descumpriu culposamente um dever razoável e exigível de agir.", correta: true },
      { texto: "A responsabilidade civil é integralmente afastada pela ocorrência de caso fortuito interno.", correta: false },
      { texto: "A reparação deve ser exigida exclusivamente do policial responsável pelo setor de policiamento.", correta: false },
      { texto: "O dever de indenizar independe de demonstração de nexo de causalidade entre a omissão e o prejuízo.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-01-017",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A teoria dos motivos determinantes estabelece que:",
    explicacao: "GABARITO: C. A teoria dos motivos determinantes vincula a validade do ato administrativo à veracidade e legalidade dos motivos expressamente declarados pela autoridade ao praticá-lo.",
    alternativas: [
      { texto: "A Administração Pública nunca precisa justificar seus atos discricionários.", correta: false },
      { texto: "Os motivos do ato administrativo podem ser modificados a qualquer tempo em juízo.", correta: false },
      { texto: "A validade do ato administrativo está vinculada à veracidade dos motivos externados pela autoridade, de modo que a inexistência ou falsidade do motivo vicia o ato de nulidade.", correta: true },
      { texto: "O motivo é dispensável nos atos vinculados.", correta: false },
      { texto: "A vontade subjetiva do governante prevalece sobre a fundamentação fática do processo.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-018",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O poder que permite à Administração Pública aplicar penalidades administrativas aos seus servidores e aos particulares sujeitos à disciplina interna de órgãos e estabelecimentos públicos (como concessionárias e presidiários) é o poder:",
    explicacao: "GABARITO: A. O poder disciplinar alcança servidores públicos e particulares com vínculo especial de sujeição perante o Estado (ex: contratados, alunos de escola pública, presos).",
    alternativas: [
      { texto: "Disciplinar.", correta: true },
      { texto: "De polícia.", correta: false },
      { texto: "Regulamentar.", correta: false },
      { texto: "Hierárquico originário.", correta: false },
      { texto: "Constituinte decorrente.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-019",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Sobre a classificação dos atos administrativos quanto à sua formação de vontade, o ato que resulta da manifestação de dois ou mais órgãos diferentes, cujas vontades se unem para formar um único ato, é denominado ato:",
    explicacao: "GABARITO: D. Ato composto: resulta da manifestação de um único órgão, mas depende de aprovação/visto de outro para produzir efeitos. Ato complexo: resulta da conjugação de vontade de dois ou mais órgãos independentes que se fundem para formar um único ato (ex: nomeação de Ministro do STF após sabatina do Senado).",
    alternativas: [
      { texto: "Simples.", correta: false },
      { texto: "Composto.", correta: false },
      { texto: "Enunciativo.", correta: false },
      { texto: "Complexo.", correta: true },
      { texto: "Geral.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-020",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O prazo prescricional para a pretensão de indenização contra a Fazenda Pública por responsabilidade civil do Estado, nos termos do Decreto nº 20.910/1932, é de:",
    explicacao: "GABARITO: E. Art. 1º do Decreto 20.910/1932: as dívidas passivas da União, Estados e Municípios prescrevem em cinco anos (prescrição quinquenal).",
    alternativas: [
      { texto: "Um ano.", correta: false },
      { texto: "Dois anos.", correta: false },
      { texto: "Três anos.", correta: false },
      { texto: "Quatro anos.", correta: false },
      { texto: "Cinco anos.", correta: true },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-01-021",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Durante fiscalização de trânsito em perímetro urbano, agentes de segurança pública constataram que determinado estabelecimento comercial interditou irregularmente a via pública com estruturas metálicas sem autorização. Diante do risco iminente à fluidez e segurança dos transeuntes, a equipe policial procedeu à remoção imediata dos obstáculos. O atributo do poder de polícia que legitima a intervenção direta da Administração sem ordem judicial prévia é a:",
    explicacao: "GABARITO: B. A autoexecutoriedade permite que a Administração execute diretamente suas decisões e medidas materiais de polícia sem necessidade de autorização prévia do Poder Judiciário, notadamente em situações urgentes ou expressamente previstas em lei.",
    alternativas: [
      { texto: "Tipicidade estrita vinculada.", correta: false },
      { texto: "Autoexecutoriedade das medidas administrativas de polícia.", correta: true },
      { texto: "Presunção absoluta de constitucionalidade.", correta: false },
      { texto: "Irrevogabilidade do mérito administrativo.", correta: false },
      { texto: "Indelegabilidade originária das funções estatais.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-022",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A 'caducidade' como forma de extinção do ato administrativo ocorre quando:",
    explicacao: "GABARITO: A. Caducidade é a extinção do ato administrativo válido em razão da superveniência de norma jurídica que tornou inadmissível a situação anteriormente permitida.",
    alternativas: [
      { texto: "Surge legislação superveniente que torna a situação jurídica antes permitida incompatível com o novo ordenamento.", correta: true },
      { texto: "O destinatário do ato descumpre culposamente as condições impostas pela Administração (caso de cassação).", correta: false },
      { texto: "A autoridade constata que o ato nasceu com vício insanável de competência (caso de anulação).", correta: false },
      { texto: "A Administração extingue o ato por mera conveniência e oportunidade (caso de revogação).", correta: false },
      { texto: "O beneficiário renuncia expressamente aos direitos decorrentes da licença (caso de renúncia).", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-023",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.responsabilidade_civil_estado,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A teoria do risco integral difere da teoria do risco administrativo porque a teoria do risco integral:",
    explicacao: "GABARITO: C. Na teoria do risco integral o Estado é obrigado a indenizar em qualquer circunstância, não se admitindo a invocação de excludentes de nexo de causalidade (adotada no Brasil em danos nucleares, atentados terroristas contra aeronaves e crimes de guerra).",
    alternativas: [
      { texto: "Exige prova de culpa gravíssima do servidor público causador do dano.", correta: false },
      { texto: "Permite a aplicação de todas as causas excludentes de responsabilidade civil.", correta: false },
      { texto: "Não admite excludentes de responsabilidade (como caso fortuito, força maior e culpa exclusiva da vítima), obrigando o Estado a indenizar.", correta: true },
      { texto: "Aplica-se unicamente a acidentes de trânsito envolvendo veículos particulares.", correta: false },
      { texto: "Depende de autorização do Tribunal de Contas da União.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-adm-01-024",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.atos_administrativos,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A certidão expedida por escrivão de polícia atestando antecedentes funcionais de um servidor público é classificada doutrinariamente como ato administrativo:",
    explicacao: "GABARITO: B. Os atos enunciativos são aqueles em que a Administração se limita a atestar ou certificar um fato preexistente ou emitir uma opinião técnica (ex: certidões, atestados, certidões de antecedentes, pareceres).",
    alternativas: [
      { texto: "Normativo.", correta: false },
      { texto: "Enunciativo.", correta: true },
      { texto: "Punitivo.", correta: false },
      { texto: "Negocial discricionário.", correta: false },
      { texto: "Ordinatório interno.", correta: false },
    ],
  },
  {
    idSlug: "b9-adm-01-025",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.poderes_administrativos,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quando um agente público, embora legalmente competente para praticar o ato, age movido por interesses pessoais de vingança política ou com o objetivo de favorecer parentes, resta configurado:",
    explicacao: "GABARITO: D. Desvio de finalidade (ou desvio de poder) ocorre quando o agente competente pratica o ato visando a fim diverso do previsto na lei ou contrário ao interesse público.",
    alternativas: [
      { texto: "Excesso de poder estrito.", correta: false },
      { texto: "Usurpação de função pública.", correta: false },
      { texto: "Incompetência ratione loci.", correta: false },
      { texto: "Desvio de finalidade (desvio de poder).", correta: true },
      { texto: "Exercício regular de direito discricionário.", correta: false },
    ],
  },
];
