import { TAXONOMIA } from "./taxonomia.mjs";

export const const02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-const-02-001",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A organização político-administrativa da República Federativa do Brasil compreende a União, os Estados, o Distrito Federal e os Municípios, todos autônomos, nos termos da Constituição Federal.",
    explicacao: "GABARITO: CERTO. Artigo 18, caput, da CF/88: 'A organização político-administrativa da República Federativa do Brasil compreende a União, os Estados, o Distrito Federal e os Municípios, todos autônomos, nos termos desta Constituição.'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-002",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Compete privativamente à União legislar sobre direito penal, processual penal, civil, comercial e do trabalho, podendo lei complementar federal autorizar os Estados a legislar sobre questões específicas dessas matérias.",
    explicacao: "GABARITO: CERTO. Art. 22, I e parágrafo único, da CF/88: competência privativa da União com possibilidade de delegação de questões específicas aos Estados via lei complementar.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-003",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No âmbito da legislação concorrente (Art. 24 da CF), a superveniência de lei federal sobre normas gerais revoga integralmente a lei estadual anterior que com ela for contrária.",
    explicacao: "GABARITO: ERRADO. Art. 24, § 4º, CF: 'A superveniência de lei federal sobre normas gerais SUSPENDE a eficácia da lei estadual, no que lhe for contrário' (suspensão de eficácia, e não revogação).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-const-02-004",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.controle_constitucionalidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "São legitimados universais para propor Ação Direta de Inconstitucionalidade (ADI) e Ação Declaratória de Constitucionalidade (ADC) perante o Supremo Tribunal Federal o Presidente da República, a Mesa do Senado Federal, a Mesa da Câmara dos Deputados, o Procurador-Geral da República e o Conselho Federal da OAB, dispensados de demonstrar pertinência temática.",
    explicacao: "GABARITO: CERTO. Art. 103 da CF e jurisprudência pacífica do STF: os legitimados neutros/universais não precisam demonstrar pertinência temática (Presidente, Mesas da Câmara e Senado, PGR, Conselho Federal da OAB e partidos políticos com representação no Congresso). Já os Governadores, Mesas de Assembleias e confederações sindicais/entidades de classe de âmbito nacional são legitimados especiais e exigem pertinência.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-005",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_executivo,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Com o objetivo de reestruturar rotinas operacionais no Ministério da Justiça e Segurança Pública, o Presidente da República editou decreto autônomo dispondo sobre a organização e funcionamento da administração federal, sem gerar aumento de despesa nem criar ou extinguir órgãos públicos. Nessa situação, a edição do ato encontra respaldo direto no poder regulamentar constitucional do Chefe do Executivo.",
    explicacao: "GABARITO: CERTO. Art. 84, VI, 'a', da CF/88 (inserido pela EC 32/2001): compete privativamente ao Presidente da República dispor mediante decreto sobre a organização e funcionamento da administração federal, quando não implicar aumento de despesa nem criação ou extinção de órgãos públicos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-006",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_legislativo,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "As Comissões Parlamentares de Inquérito (CPIs), criadas pela Câmara dos Deputados e pelo Senado Federal, possuem poderes de investigação próprios das autoridades judiciais, podendo determinar a quebra de sigilo bancário, telefônico e telemático, bem como a decretação de prisão preventiva de investigados.",
    explicacao: "GABARITO: ERRADO. Art. 58, § 3º, CF: as CPIs têm poderes investigatórios próprios de autoridades judiciais (podem determinar quebra de sigilo fiscal, bancário e telefônico/dados), mas NÃO possuem poderes que a CF reservou exclusivamente a juízes, como decretar prisão preventiva, busca domiciliar ou interceptação telefônica (escuta).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-const-02-007",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_judiciario,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O Conselho Nacional de Justiça (CNJ) é órgão integrante do Poder Judiciário dotado de competência exclusivamente administrativa, financeira e disciplinar, sem qualquer atribuição jurisdicional.",
    explicacao: "GABARITO: CERTO. Art. 92, I-A, e Art. 103-B da CF/88: o CNJ compõe a estrutura do Judiciário e exerce controle da atuação administrativa, financeira e disciplinar, mas não exerce jurisdição.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-008",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.controle_constitucionalidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No controle difuso de constitucionalidade, qualquer juiz ou tribunal pode declarar a inconstitucionalidade de lei ou ato normativo federal, estadual ou municipal no caso concreto, devendo os órgãos colegiados dos tribunais observar a cláusula de reserva de plenário (Art. 97 da CF).",
    explicacao: "GABARITO: CERTO. Art. 97 da CF (cláusula de reserva de plenário) e Súmula Vinculante nº 10 do STF: somente pelo voto da maioria absoluta de seus membros ou do órgão especial podem os tribunais declarar a inconstitucionalidade de lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-009",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A intervenção federal nos Estados ou no Distrito Federal para pôr termo a grave comprometimento da ordem pública é de decretação espontânea e privativa do Presidente da República, prescindindo de solicitação ou requisição de qualquer outro Poder.",
    explicacao: "GABARITO: CERTO. Art. 34, III, e Art. 36, caput, CF: no caso de grave comprometimento da ordem pública (art. 34, III) e para repelir invasão estrangeira/estadual, o Presidente decreta a intervenção de ofício (espontaneamente), ouvidos os Conselhos da República e de Defesa Nacional, submetendo o decreto ao Congresso em 24h.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-010",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_judiciario,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Compete ao Superior Tribunal de Justiça (STJ) processar e julgar, originariamente, nos crimes comuns, os Governadores dos Estados e do Distrito Federal, e, nestes e nos de responsabilidade, os desembargadores dos Tribunais de Justiça dos Estados e do DF.",
    explicacao: "GABARITO: CERTO. Art. 105, I, 'a', da CF/88: competência originária criminal do STJ para Governadores (crimes comuns) e desembargadores dos TJs e TRFs (crimes comuns e de responsabilidade).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-const-02-011",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.controle_constitucionalidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Arguição de Descumprimento de Preceito Fundamental (ADPF), regulamentada pela Lei nº 9.882/1999 com esteio no Art. 102, § 1º, da CF/88, tem como característica fundamental o princípio da:",
    explicacao: "GABARITO: D. Art. 4º, § 1º, da Lei 9.882/1999: 'Não será admitida arguição de descumprimento de preceito fundamental quando houver qualquer outro meio eficaz de sanar a lesividade' (Princípio da Subsidiariedade).",
    alternativas: [
      { texto: "Bilateralidade estrita.", correta: false },
      { texto: "Unicidade recursal mandatória.", correta: false },
      { texto: "Taxatividade orçamentária prévia.", correta: false },
      { texto: "Subsidiariedade, não sendo admitida quando houver outro meio eficaz de sanar a lesividade.", correta: true },
      { texto: "Hierarquia exclusiva sobre leis complementares federais.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-012",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Compete concorrentemente à União, aos Estados e ao Distrito Federal legislar sobre:",
    explicacao: "GABARITO: B. Art. 24, I, da CF/88: 'Compete à União, aos Estados e ao Distrito Federal legislar concorrentemente sobre: I - direito tributário, financeiro, penitenciário, econômico e urbanístico'.",
    alternativas: [
      { texto: "Direito penal, marítimo e aeronáutico.", correta: false },
      { texto: "Direito tributário, financeiro, penitenciário, econômico e urbanístico.", correta: true },
      { texto: "Direito processual civil e processual penal.", correta: false },
      { texto: "Direito eleitoral, agrário e de desapropriação.", correta: false },
      { texto: "Direito espacial e telecomunicações.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-013",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_executivo,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos crimes de responsabilidade, o Presidente da República será submetido a julgamento perante:",
    explicacao: "GABARITO: A. Art. 86, caput, c/c Art. 52, I, CF: admitida a acusação por 2/3 da Câmara dos Deputados, o julgamento por crime de responsabilidade compete privativamente ao Senado Federal, presidido pelo Presidente do STF.",
    alternativas: [
      { texto: "O Senado Federal, após juízo de admissibilidade por dois terços da Câmara dos Deputados.", correta: true },
      { texto: "O Supremo Tribunal Federal em sessão plenária secreta.", correta: false },
      { texto: "O Superior Tribunal de Justiça mediante requisição do PGR.", correta: false },
      { texto: "O Congresso Nacional reunido em sessão conjunta unicameral.", correta: false },
      { texto: "O Tribunal de Contas da União presidido por ministro militar.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-014",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_judiciario,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Supremo Tribunal Federal é composto por onze Ministros, nomeados pelo Presidente da República, após aprovação da escolha pela maioria absoluta do Senado Federal, dentre cidadãos que preencham os seguintes requisitos:",
    explicacao: "GABARITO: C. Art. 101 da CF/88: brasileiros natos (art. 12, § 3º, IV), com mais de trinta e cinco e menos de setenta anos de idade, de notável saber jurídico e reputação ilibada.",
    alternativas: [
      { texto: "Mais de trinta e menos de sessenta e cinco anos de idade e título de doutor em direito.", correta: false },
      { texto: "Mais de quarenta anos de idade e dez anos ininterruptos de magistratura estadual.", correta: false },
      { texto: "Mais de trinta e cinco e menos de setenta anos de idade, com notável saber jurídico e reputação ilibada.", correta: true },
      { texto: "Mais de trinta anos e formação militar de oficialato superior.", correta: false },
      { texto: "Mais de vinte e cinco anos com prévia aprovação em concurso público de provas e títulos.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-015",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_legislativo,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O processo legislativo compreende a elaboração de diversos atos normativos. Não será objeto de deliberação a proposta de emenda constitucional tendente a abolir (cláusulas pétreas):",
    explicacao: "GABARITO: E. Art. 60, § 4º, CF/88: I - a forma federativa de Estado; II - o voto direto, secreto, universal e periódico; III - a separação dos Poderes; IV - os direitos e garantias individuais.",
    alternativas: [
      { texto: "O regime presidencialista de governo e a moeda nacional.", correta: false },
      { texto: "A unicameralidade do Poder Legislativo municipal.", correta: false },
      { texto: "O sistema eleitoral proporcional e a justiça militar estadual.", correta: false },
      { texto: "O monopólio do petróleo e o regime próprio de previdência social.", correta: false },
      { texto: "A forma federativa de Estado, o voto direto, secreto, universal e periódico, a separação dos Poderes e os direitos e garantias individuais.", correta: true },
    ],
  },
  {
    idSlug: "b9-const-02-016",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.controle_constitucionalidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A decisão definitiva de mérito proferida pelo STF nas Ações Diretas de Inconstitucionalidade (ADI) e nas Ações Declaratórias de Constitucionalidade (ADC) produz:",
    explicacao: "GABARITO: B. Art. 102, § 2º, CF/88: eficácia contra todos (erga omnes) e efeito vinculante relativamente aos demais órgãos do Poder Judiciário e à administração pública direta e indireta, nas esferas federal, estadual e municipal.",
    alternativas: [
      { texto: "Efeito inter partes exclusivo, vinculado apenas às partes litigantes.", correta: false },
      { texto: "Eficácia contra todos (erga omnes) e efeito vinculante relativamente aos demais órgãos do Judiciário e à administração pública de todas as esferas federativas.", correta: true },
      { texto: "Efeito vinculante sobre o próprio Poder Legislativo em sua função típica de legislar.", correta: false },
      { texto: "Efeito meramente consultivo que depende de homologação do Senado Federal.", correta: false },
      { texto: "Eficácia territorial restrita ao Distrito Federal.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-const-02-017",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Distrito Federal, vedada sua divisão em Municípios, reger-se-á por:",
    explicacao: "GABARITO: C. Art. 32, caput, da CF/88: 'O Distrito Federal, vedada sua divisão em Municípios, reger-se-á por lei orgânica, votada em dois turnos com interstício mínimo de dez dias, e aprovada por dois terços da Câmara Legislativa...'",
    alternativas: [
      { texto: "Constituição Estadual promulgada por convenção municipal.", correta: false },
      { texto: "Decreto-Lei expedido pelo Governador e aprovado pelo STJ.", correta: false },
      { texto: "Lei Orgânica, votada em dois turnos com interstício mínimo de dez dias e aprovada por dois terços da Câmara Legislativa.", correta: true },
      { texto: "Regimento Interno do Senado Federal.", correta: false },
      { texto: "Estatuto Político aprovado por referendo popular anual.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-018",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_executivo,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Durante uma missão oficial conjunta no exterior de representação da República, o avião presidencial sofreu pane mecânica que impossibilitou o retorno imediato tanto do Presidente quanto do Vice-Presidente da República. Diante do impedimento temporário e concomitante de ambos para despachar em território nacional, a ordem constitucional de substituição prevista no art. 80 da CF/88 estabelece que o exercício da Presidência da República recairá sucessivamente sobre:",
    explicacao: "GABARITO: A. Art. 80 da CF/88: 'Em caso de impedimento do Presidente e do Vice-Presidente, ou vacância dos respectivos cargos, serão sucessivamente chamados ao exercício da Presidência o Presidente da Câmara dos Deputados, o do Senado Federal e o do Supremo Tribunal Federal.'",
    alternativas: [
      { texto: "O Presidente da Câmara dos Deputados, o do Senado Federal e o do Supremo Tribunal Federal.", correta: true },
      { texto: "O Ministro da Justiça e Segurança Pública, o Comandante Militar e o Procurador-Geral da República.", correta: false },
      { texto: "O Presidente do Superior Tribunal de Justiça, o Presidente do Tribunal de Contas da União e o Governador do Distrito Federal.", correta: false },
      { texto: "O Decano do Supremo Tribunal Federal, o Presidente do Tribunal Superior Eleitoral e o Ministro das Relações Exteriores.", correta: false },
      { texto: "O Presidente do Senado Federal, o Presidente da Câmara dos Deputados e o Ministro Chefe da Casa Civil.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-019",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_judiciario,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Após sucessivos pronunciamentos judiciais divergentes em instâncias inferiores sobre a legitimidade de procedimentos em investigações policiais, o Supremo Tribunal Federal editou enunciado de Súmula Vinculante visando pacificar a controvérsia. Sob a ótica do art. 103-A da Constituição Federal de 1988, a eficácia vinculante do referido enunciado incide de modo obrigatório sobre:",
    explicacao: "GABARITO: D. Art. 103-A da CF/88: a súmula vinculante terá efeito vinculante em relação aos demais órgãos do Poder Judiciário e à administração pública direta e indireta, nas esferas federal, estadual e municipal (não vinculando o Poder Legislativo em sua atividade típica de legislar).",
    alternativas: [
      { texto: "Apenas os tribunais federais de primeira e segunda instâncias.", correta: false },
      { texto: "Exclusivamente os Ministérios Públicos dos Estados e da União.", correta: false },
      { texto: "O Poder Legislativo em sua atividade legislativa primária.", correta: false },
      { texto: "Os demais órgãos do Poder Judiciário e a administração pública direta e indireta, nas esferas federal, estadual e municipal.", correta: true },
      { texto: "Apenas as forças de segurança pública e forças armadas.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-020",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Compete aos Municípios, nos termos do Art. 30 da Constituição Federal de 1988:",
    explicacao: "GABARITO: E. Art. 30, I e V, CF/88: legislar sobre assuntos de interesse local e organizar e prestar, diretamente ou sob regime de concessão ou permissão, os serviços públicos de interesse local, incluído o de transporte coletivo.",
    alternativas: [
      { texto: "Emitir papel-moeda e autorizar reservas cambiais.", correta: false },
      { texto: "Declarar estado de sítio em caso de comoção social.", correta: false },
      { texto: "Conceder anistia de crimes políticos federais.", correta: false },
      { texto: "Fiscalizar as fronteiras aduaneiras e o espaço aéreo.", correta: false },
      { texto: "Legislar sobre assuntos de interesse local e prestar os serviços públicos de transporte coletivo municipal.", correta: true },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-const-02-021",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_legislativo,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Senado Federal compõe-se de representantes dos Estados e do Distrito Federal, eleitos segundo o princípio:",
    explicacao: "GABARITO: B. Art. 46 da CF/88: 'O Senado Federal compõe-se de representantes dos Estados e do Distrito Federal, eleitos segundo o princípio majoritário.' Cada Estado e o DF elegem três Senadores para mandato de 8 anos.",
    alternativas: [
      { texto: "Proporcional com quociente eleitoral.", correta: false },
      { texto: "Majoritário.", correta: true },
      { texto: "Distrital misto obrigatório.", correta: false },
      { texto: "Sufrágio censitário indireto.", correta: false },
      { texto: "Delegatório corporativo.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-022",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_judiciario,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São garantias constitucionais da magistratura previstas expressamente no Art. 95 da Constituição Federal:",
    explicacao: "GABARITO: A. Art. 95 da CF: vitaliciedade (após 2 anos de efetivo exercício), inamovibilidade (salvo por motivo de interesse público) e irredutibilidade de subsídio.",
    alternativas: [
      { texto: "Vitaliciedade, inamovibilidade e irredutibilidade de subsídio.", correta: true },
      { texto: "Estabilidade aos dez anos, imunidade tributária e foro privilegiado perpétuo.", correta: false },
      { texto: "Aposentadoria compulsória aos sessenta anos com proventos dobrados.", correta: false },
      { texto: "Inviolabilidade absoluta para a prática de qualquer crime comum.", correta: false },
      { texto: "Livre exercício de atividade político-partidária concomitante.", correta: false },
    ],
  },
  {
    idSlug: "b9-const-02-023",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.controle_constitucionalidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A ação direta de inconstitucionalidade por omissão (ADO) tem por objetivo tornar efetiva norma constitucional desprovida de regulamentação. Declarada a inconstitucionalidade por omissão de Poder competente, o STF:",
    explicacao: "GABARITO: C. Art. 103, § 2º, CF: 'Declarada a inconstitucionalidade por omissão de medida para tornar efetiva norma constitucional, será dada ciência ao Poder competente para a adoção das providências necessárias e, em se tratando de órgão administrativo, para fazê-lo em trinta dias.'",
    alternativas: [
      { texto: "Assumirá a função legislativa editando imediatamente uma emenda constitucional.", correta: false },
      { texto: "Decretará a intervenção militar automática na respectiva Casa Legislativa.", correta: false },
      { texto: "Dará ciência ao Poder competente para a adoção das providências necessárias e, tratando-se de órgão administrativo, para fazê-lo em 30 dias.", correta: true },
      { texto: "Extinguirá o mandato de todos os parlamentares em exercício.", correta: false },
      { texto: "Aplicará multa pessoal diária aos cidadãos eleitores.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-const-02-024",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Os bens da União incluem expressamente, nos termos do Art. 20 da Constituição Federal de 1988:",
    explicacao: "GABARITO: E. Art. 20, III e IV, CF: os lagos, rios e quaisquer correntes de água em terrenos de seu domínio, ou que banhem mais de um Estado, e as terras devolutas indispensáveis à defesa das fronteiras.",
    alternativas: [
      { texto: "As praças públicas e jardins municipais.", correta: false },
      { texto: "As rodovias vicinais privadas e vicinais municipais.", correta: false },
      { texto: "Os edifícios das prefeituras e câmaras de vereadores.", correta: false },
      { texto: "As calçadas e ciclovias urbanas estaduais.", correta: false },
      { texto: "Os rios que banhem mais de um Estado ou que sirvam de limite com outros países e as terras devolutas indispensáveis à defesa das fronteiras.", correta: true },
    ],
  },
  {
    idSlug: "b9-const-02-025",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.poder_executivo,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O Presidente da República, na vigência de seu mandato, nos termos do Art. 86, § 4º, da CF/88, não pode ser responsabilizado por:",
    explicacao: "GABARITO: D. Art. 86, § 4º, CF: 'O Presidente da República, na vigência de seu mandato, não pode ser responsabilizado por atos estranhos ao exercício de suas funções' (imunidade penal temporária relativa).",
    alternativas: [
      { texto: "Crimes de responsabilidade praticados em razão do cargo.", correta: false },
      { texto: "Crimes comuns conexos à administração pública federal.", correta: false },
      { texto: "Infrações fiscais orçamentárias julgadas pelo Congresso.", correta: false },
      { texto: "Atos estranhos ao exercício de suas funções cometidos antes ou fora do mandato.", correta: true },
      { texto: "Violações expressas a tratados internacionais ratificados.", correta: false },
    ],
  },
];
