import { TAXONOMIA } from "./taxonomia.mjs";

export const penal02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-penal-02-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O feminicídio constitui circunstância qualificadora do crime de homicídio, caracterizando-se quando o crime é praticado contra a mulher por razões da condição de sexo feminino, o que envolve violência doméstica e familiar e/ou menosprezo ou discriminação à condição de mulher.",
    explicacao: "GABARITO: CERTO. Art. 121, § 2º, VI e § 2º-A, do CP: o feminicídio qualifica o homicídio quando praticado contra a mulher por razões da condição de sexo feminino (violência doméstica/familiar ou menosprezo/discriminação).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante diligência externa, investigadores de polícia presenciaram um indivíduo subtrair o celular de uma pedestre mediante grave ameaça com simulacro de arma. A equipe realizou perseguição imediata a pé por cerca de 150 metros e capturou o assaltante, recuperando o bem cerca de dois minutos após a subtração. Nessa situação hipotética, consoante a jurisprudência pacífica do STJ e do STF (Teoria da Amotio), o delito de roubo consumou-se plenamente, sendo desnecessária a posse mansa, pacífica ou desvigiada da coisa.",
    explicacao: "GABARITO: CERTO. Súmula 582 do STJ: 'Consuma-se o crime de roubo com a inversão da posse do bem mediante emprego de violência ou grave ameaça, ainda que por breve tempo e em seguida à perseguição imediata ao agente e recuperação da coisa roubada, sendo prescindível a posse mansa e pacífica ou desvigiada.'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Um Escrivão de Polícia Federal, por negligência inescusável na guarda da repartição, deixou aberta a sala de custódia, ensejando que terceiro furtasse equipamento de informática da União. Instaurada a ação penal pelo peculato culposo, o servidor ressarciu espontaneamente e por completo o dano patrimonial antes do trânsito em julgado da sentença condenatória. Nessa situação, o ressarcimento tempestivo do prejuízo acarreta a extinção da punibilidade do servidor.",
    explicacao: "GABARITO: CERTO. Art. 312, § 3º, primeira parte, do Código Penal: no peculato culposo, a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade. Se for posterior à sentença irrecorrível, reduz a pena de metade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante fiscalização de trânsito em rodovia federal, um Policial Rodoviário Federal abordou um motorista de caminhão e, em razão estrita de sua função pública, impôs e exigiu expressamente daquele condutor o pagamento de R$ 1.000,00 sob a ameaça de reter indevidamente o veículo. Nessa situação hipotética, ao exigir formalmente a vantagem indevida, a conduta do agente amolda-se ao crime de corrupção passiva.",
    explicacao: "GABARITO: ERRADO. O verbo nuclear EXIGIR configura o crime de CONCUSSÃO (art. 316 do CP). O delito de CORRUPÇÃO PASSIVA (art. 317 do CP) possui como condutas típicas SOLICITAR, RECEBER ou ACEITAR PROMESSA de vantagem indevida.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-02-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O estelionato (Art. 171 do CP) passou a ser processado, como regra geral introduzida pela Lei nº 13.964/2019, mediante ação penal pública condicionada à representação do ofendido, ressalvadas as hipóteses em que a vítima seja a administração pública, criança/adolescente, pessoa com deficiência mental ou idoso/vulnerável.",
    explicacao: "GABARITO: CERTO. Art. 171, § 5º, do CP (redação da Lei 13.964/2019 e alterações posteriores): o estelionato agora é crime de ação pública condicionada à representação, salvo nas exceções expressas em lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Um Comandante de Batalhão da Polícia Militar tomou conhecimento formal de que seu irmão se envolvera em ilícito penal e causara danos à propriedade pública. Movido exclusivamente por sentimento de afeto familiar e compaixão pessoal, o oficial ordenou verbalmente que o boletim de ocorrência não fosse confeccionado nem encaminhado à Polícia Judiciária. Nessa situação hipotética, o oficial cometeu o delito funcional de prevaricação.",
    explicacao: "GABARITO: CERTO. Art. 319 do Código Penal: o crime de prevaricação consiste em 'retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal.' Deixar de instaurar/encaminhar os procedimentos para beneficiar parente por afeto pessoal amolda-se à prevaricação.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O homicídio praticado contra autoridade ou agente de segurança pública integrante dos órgãos do Art. 144 da CF, no exercício da função ou em decorrência dela, ou contra seu cônjuge, companheiro ou parente consanguíneo até o terceiro grau, em razão dessa condição, constitui homicídio qualificado (homicídio funcional).",
    explicacao: "GABARITO: CERTO. Art. 121, § 2º, VII, do Código Penal (homicídio funcional/hediondo).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O crime de corrupção ativa (Art. 333 do CP) é crime praticado por particular contra a administração pública em geral, consumando-se com a simples oferta ou promessa de vantagem indevida a funcionário público, prescindindo da aceitação deste.",
    explicacao: "GABARITO: CERTO. Art. 333 do CP: crime formal que se consuma no momento em que a vantagem indevida é oferecida ou prometida ao funcionário, sendo irrelevante se o funcionário aceita ou recusa a proposta.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Na receptação culposa (Art. 180, § 3º, do CP), o agente adquire ou recebe coisa que, por sua natureza ou pela desproporção entre o valor e o preço, ou pela condição de quem a oferece, deve presumir-se obtida por meio criminoso.",
    explicacao: "GABARITO: CERTO. Art. 180, § 3º, do CP: definição legal da receptação culposa com a cláusula 'deve presumir-se'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O crime de desacato (Art. 331 do CP) consiste em desacatar funcionário público no exercício da função ou em razão dela, tendo o Superior Tribunal de Justiça e o Supremo Tribunal Federal pacificado o entendimento de que o tipo penal é plenamente compatível com a Convenção Americana sobre Direitos Humanos (Pacto de San José da Costa Rica) e com a Constituição Federal de 1988.",
    explicacao: "GABARITO: CERTO. HC 379.269/STJ (3ª Seção) e ADPF 496/STF: pacificaram que o crime de desacato não viola a liberdade de expressão nem o Pacto de San José da Costa Rica, permanecendo em vigor no ordenamento jurídico brasileiro.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-02-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "O policial que, por indulgência, deixa de responsabilizar subordinado que cometeu infração no exercício do cargo ou, quando lhe falte competência, não leva o fato ao conhecimento da autoridade competente, pratica o crime de:",
    explicacao: "GABARITO: B. Art. 320 do Código Penal: Condescendência criminosa. O elemento subjetivo específico é a 'indulgência' (tolerância, complacência indevida).",
    alternativas: [
      { texto: "Prevaricação por omissão imprópria.", correta: false },
      { texto: "Condescendência criminosa.", correta: true },
      { texto: "Advocacia administrativa qualificada.", correta: false },
      { texto: "Corrupção passiva privilegiada.", correta: false },
      { texto: "Favorecimento pessoal.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em investigação conduzida pela Polícia Federal sobre sequestro com pedido de resgate de empresário, apurou-se que a vítima permaneceu em cativeiro sob o controle de uma associação criminosa por período superior a 48 horas ininterruptas, além de contar com 65 anos de idade. No enquadramento típico do art. 159 do Código Penal (extorsão mediante sequestro), essas circunstâncias caracterizam:",
    explicacao: "GABARITO: D. Art. 159, § 1º, do CP: Extorsão mediante sequestro qualificada (se o sequestro dura mais de 24 horas, se o sequestrado é menor de 18 ou maior de 60 anos, ou se é cometido em concurso de 4 ou mais pessoas/bando).",
    alternativas: [
      { texto: "Causa de aumento de pena genérica de um sexto na terceira fase da dosimetria.", correta: false },
      { texto: "Delito autônomo de cárcere privado majorado em concurso material com extorsão simples.", correta: false },
      { texto: "Crime tentado com aplicação obrigatória do arrependimento eficaz.", correta: false },
      { texto: "Extorsão mediante sequestro qualificada com pena autônoma mais gravosa.", correta: true },
      { texto: "Roubo circunstanciado pela privação momentânea da liberdade individual.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_pessoa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Se o agente comete o crime de homicídio impelido por motivo de relevante valor social ou moral, ou sob o domínio de violenta emoção, logo em seguida a injusta provocação da vítima, o juiz pode reduzir a pena de um sexto a um terço. Trata-se do:",
    explicacao: "GABARITO: A. Art. 121, § 1º, do Código Penal: homicídio privilegiado.",
    alternativas: [
      { texto: "Homicídio privilegiado.", correta: true },
      { texto: "Homicídio qualificado-privilegiado subjetivo.", correta: false },
      { texto: "Perdão judicial obrigatório.", correta: false },
      { texto: "Descriminante putativa mitigada.", correta: false },
      { texto: "Arrependimento eficaz superveniente.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Para os efeitos penais, considera-se funcionário público quem, embora transitoriamente ou sem remuneração, exerce cargo, emprego ou função pública (Art. 327, caput, do CP). Equipara-se a funcionário público quem:",
    explicacao: "GABARITO: C. Art. 327, § 1º, do CP: 'Equipara-se a funcionário público quem exerce cargo, emprego ou função em entidade paraestatal, e quem trabalha para empresa prestadora de serviço contratada ou conveniada para a execução de atividade típica da Administração Pública.'",
    alternativas: [
      { texto: "Trabalha exclusivamente no setor privado sem qualquer vínculo estatal.", correta: false },
      { texto: "É filiado a partido político com representação no Congresso Nacional.", correta: false },
      { texto: "Trabalha para empresa prestadora de serviço contratada ou conveniada para a execução de atividade típica da Administração Pública.", correta: true },
      { texto: "Atua como advogado particular em causas perante a Justiça Federal.", correta: false },
      { texto: "É síndico eleito de condomínio residencial privado.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de apropriação indébita (Art. 168 do CP) diferencia-se substancialmente do estelionato (Art. 171 do CP) porque, na apropriação indébita:",
    explicacao: "GABARITO: E. Na apropriação indébita, a posse ou detenção da coisa é obtida legitimamente e sem fraude, surgindo o dolo de assenhoreamento posteriormente (animus rem sibi habendi superveniente). No estelionato, a fraude é antecedente e empregada para obter a posse da coisa.",
    alternativas: [
      { texto: "O agente emprega violência real contra a vítima para subtrair a coisa.", correta: false },
      { texto: "O sujeito passivo é sempre e exclusivamente a pessoa jurídica de direito público.", correta: false },
      { texto: "A vítima entrega a coisa sob coação moral irresistível.", correta: false },
      { texto: "O crime só se consuma com a venda a terceiros de boa-fé.", correta: false },
      { texto: "O agente recebe a posse ou detenção prévia da coisa de forma legítima e desprovida de fraude, nascendo o dolo de apossamento em momento posterior.", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-02-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Ao receber ordem formal e expressa de transferência de cela emanada legalmente por policial penal de plantão, um custodiado investiu fisicamente contra o servidor com socos e pontapés, visando impedir a execução da medida de segurança. A conduta do detento que se opõe à execução de ato legal mediante violência física contra funcionário competente configura o crime de:",
    explicacao: "GABARITO: B. Art. 329 do Código Penal: Resistência ('Opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio').",
    alternativas: [
      { texto: "Desobediência passiva.", correta: false },
      { texto: "Resistência.", correta: true },
      { texto: "Desacato institucional.", correta: false },
      { texto: "Coação processual imprópria.", correta: false },
      { texto: "Exercício arbitrário das próprias razões.", correta: false },
    ],
  },

  // 17-20. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-02-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Subtrair coisa móvel alheia, para si ou para outrem, durante o repouso noturno, acarreta no crime de furto (Art. 155, § 1º, do CP):",
    explicacao: "GABARITO: A. Art. 155, § 1º, do CP: 'A pena aumenta-se de 1/3 (um terço), se o crime é praticado durante o repouso noturno.'",
    alternativas: [
      { texto: "O aumento da pena em um terço.", correta: true },
      { texto: "A duplicação automática da pena privativa de liberdade.", correta: false },
      { texto: "A conversão obrigatória em crime hediondo inafiançável.", correta: false },
      { texto: "A desclassificação do fato para roubo impróprio.", correta: false },
      { texto: "O perdão judicial se o valor for inferior a meio salário mínimo.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_pessoa,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No crime de lesão corporal (Art. 129 do CP), resulta em lesão corporal GRAVÍSSIMA (§ 2º) quando da conduta decorre:",
    explicacao: "GABARITO: D. Art. 129, § 2º, do CP: são lesões gravíssimas: I - Incapacidade permanente para o trabalho; II - Enfermidade incurável; III - Perda ou inutilização do membro, sentido ou função; IV - Deformidade permanente; V - Aborto. Debilidade permanente de membro, sentido ou função é lesão GRAVE (§ 1º, III).",
    alternativas: [
      { texto: "Incapacidade para as ocupações habituais por mais de 30 dias.", correta: false },
      { texto: "Perigo de vida simples.", correta: false },
      { texto: "Debilidade permanente de membro, sentido ou função.", correta: false },
      { texto: "Deformidade permanente ou perda/inutilização de membro, sentido ou função.", correta: true },
      { texto: "Aceleração de parto sem morte do feto.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O funcionário público que apropria-se de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo, ou o desvia, em proveito próprio ou alheio, comete o crime de:",
    explicacao: "GABARITO: C. Art. 312, caput, do Código Penal: Peculato (peculato-apropriação e peculato-desvio).",
    alternativas: [
      { texto: "Corrupção passiva própria.", correta: false },
      { texto: "Concussão.", correta: false },
      { texto: "Peculato.", correta: true },
      { texto: "Prevaricação patrimonial.", correta: false },
      { texto: "Excesso de exação.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Um Guarda Municipal interveio diretamente junto ao setor de fiscalização de posturas do município para acelerar a liberação de alvará de funcionamento de estabelecimento comercial de um parente próximo, valendo-se ostensivamente de sua condição de servidor público municipal para interceder em favor do pleito. O ato de patrocinar interesse privado perante a Administração Pública valendo-se da qualidade funcional configura:",
    explicacao: "GABARITO: B. Art. 321 do Código Penal: Advocacia administrativa ('Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário').",
    alternativas: [
      { texto: "Tráfico de influência em repartição pública.", correta: false },
      { texto: "Advocacia administrativa.", correta: true },
      { texto: "Exploração de prestígio perante a autoridade.", correta: false },
      { texto: "Corrupção passiva imprópria qualificada.", correta: false },
      { texto: "Usurpação de função pública municipal.", correta: false },
    ],
  },

  // 21-23. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-02-021",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Adquirir, receber, transportar, conduzir ou ocultar, em proveito próprio ou alheio, coisa que sabe ser produto de crime, ou influir para que terceiro, de boa-fé, a adquira, receba ou oculte, tipifica o crime de:",
    explicacao: "GABARITO: E. Art. 180, caput, do CP: Receptação própria (primeira parte) e Receptação imprópria (segunda parte).",
    alternativas: [
      { texto: "Furto qualificado por concurso de agentes.", correta: false },
      { texto: "Estelionato tentado.", correta: false },
      { texto: "Apropriação de coisa achada.", correta: false },
      { texto: "Favorecimento real qualificado.", correta: false },
      { texto: "Receptação dolosa simples.", correta: true },
    ],
  },
  {
    idSlug: "b9-penal-02-022",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Desobedecer a ordem legal de funcionário público tipifica o crime de:",
    explicacao: "GABARITO: A. Art. 330 do Código Penal: Desobediência.",
    alternativas: [
      { texto: "Desobediência.", correta: true },
      { texto: "Resistência qualificada.", correta: false },
      { texto: "Desacato comissivo.", correta: false },
      { texto: "Motim de presos.", correta: false },
      { texto: "Insubmissão administrativa.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-023",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_pessoa,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Deixar de prestar assistência, quando possível fazê-lo sem risco pessoal, à criança abandonada ou extraviada, ou à pessoa inválida ou ferida, ao desamparo ou em grave e iminente perigo; ou não pedir, nesses casos, o socorro da autoridade pública, tipifica o crime de:",
    explicacao: "GABARITO: C. Art. 135 do Código Penal: Omissão de socorro.",
    alternativas: [
      { texto: "Abandono de incapaz.", correta: false },
      { texto: "Maus-tratos qualificados.", correta: false },
      { texto: "Omissão de socorro.", correta: true },
      { texto: "Periclitação da vida.", correta: false },
      { texto: "Condescendência social culposa.", correta: false },
    ],
  },

  // 24-25. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-penal-02-024",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Exercer função pública antes de satisfeitas as exigências legais, ou continuar a exercê-la, sem autorização, depois de saber oficialmente que foi exonerado, removido, substituído ou suspenso, configura o crime de:",
    explicacao: "GABARITO: D. Art. 324 do Código Penal: Exercício funcional ilegalmente antecipado ou prolongado.",
    alternativas: [
      { texto: "Usurpação de função pública.", correta: false },
      { texto: "Prevaricação putativa.", correta: false },
      { texto: "Abuso de poder funcional.", correta: false },
      { texto: "Exercício funcional ilegalmente antecipado ou prolongado.", correta: true },
      { texto: "Desobediência funcional qualificada.", correta: false },
    ],
  },
  {
    idSlug: "b9-penal-02-025",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_contra_patrimonio,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São imunes de pena (escusas absolutórias previstas no Art. 181 do Código Penal) nos crimes contra o patrimônio cometidos sem violência ou grave ameaça quem comete o fato em prejuízo:",
    explicacao: "GABARITO: B. Art. 181 do CP: 'É isento de pena quem comete qualquer dos crimes previstos neste título, em prejuízo: I - do cônjuge, na constância da sociedade conjugal; II - de ascendente ou descendente, seja o parentesco legítimo ou ilegítimo, seja civil ou natural.'",
    alternativas: [
      { texto: "De irmão germano ou unilateral exclusivamente.", correta: false },
      { texto: "Do cônjuge, na constância da sociedade conjugal, ou de ascendente ou descendente.", correta: true },
      { texto: "De tio ou sobrinho que com ele coabite.", correta: false },
      { texto: "De pessoa estranha que esteja sob sua curatela provisória.", correta: false },
      { texto: "De qualquer parente consanguíneo até o quarto grau na linha colateral.", correta: false },
    ],
  },
];
