import { TAXONOMIA } from "./taxonomia.mjs";

export const port02Questoes = [
  // 1-10: CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-port-02-001",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.concordancia,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Julgue a correção gramatical da assertiva: 'Houveram muitos incidentes na fronteira durante a operação conjunta das forças de segurança.'",
    explicacao: "GABARITO: ERRADO. O verbo 'haver' no sentido de existir, ocorrer ou acontecer é impessoal, devendo permanecer invariavelmente na 3ª pessoa do singular: 'Houve muitos incidentes...'.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-port-02-002",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.concordancia,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No trecho: 'A maioria dos motoristas fiscalizados apresentaram a documentação em dia.', a concordância verbal no plural é gramaticalmente aceitável, configurando caso de concordância atrativa com o adjunto no plural ('dos motoristas').",
    explicacao: "GABARITO: CERTO. Com expressões partitivas ('a maioria de', 'a maior parte de') seguidas de substantivo no plural, a concordância é facultativa: pode concordar no singular com o núcleo 'maioria' ('apresentou') ou no plural por atração com o adjunto ('apresentaram').",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-003",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No período: 'O delegado assistiu o paciente durante a prestação do socorro imediato.', o verbo 'assistir' foi empregado com regência transitiva direta, indicando o sentido de prestar assistência, socorrer ou ajudar.",
    explicacao: "GABARITO: CERTO. O verbo 'assistir' no sentido de ajudar/socorrer admite regência transitiva direta (assistir o paciente) ou indireta (assistir ao paciente). No sentido de ver/presenciar, é transitivo indireto (assistir ao filme). No sentido de caber/pertencer, rege preposição a (assiste ao réu o direito...).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-004",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O emprego do sinal indicativo de crase é obrigatório no trecho: 'A autoridade policial referiu-se àquela testemunha presencial dos fatos.'",
    explicacao: "GABARITO: CERTO. O verbo 'referir-se' rege a preposição 'a' (quem se refere, refere-se a algo/alguém). A fusão da preposição 'a' com a vogal 'a' inicial do pronome demonstrativo 'àquela' exige o acento grave indicativo de crase.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-005",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.pontuacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Na oração: 'O perito criminal, que analisou as marcas de frenagem, concluiu que o veículo trafegava em excesso de velocidade.', a supressão das duas vírgulas que isolam a oração adjetiva alteraria o seu sentido de explicativo para restritivo, embora mantivesse a correção gramatical.",
    explicacao: "GABARITO: CERTO. A oração adjetiva entre vírgulas é explicativa (aplica-se à totalidade do termo antecedente). Sem as vírgulas, torna-se adjetiva restritiva (restringe a conclusão apenas àquele perito específico dentre outros possíveis). A estrutura permanece gramaticalmente correta, mas muda a semântica.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-006",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.pontuacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "É gramaticalmente correto o emprego de vírgula para separar o sujeito do seu respectivo predicado quando o sujeito for composto por muitos termos coordenados.",
    explicacao: "GABARITO: ERRADO. É regra basilar da sintaxe de pontuação que não se separa o sujeito do predicado por vírgula, independentemente da extensão do sujeito.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-port-02-007",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.sintaxe_periodo,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na oração: 'Tratava-se de questões de alta complexidade técnica.', a partícula 'se' classifica-se como índice de indeterminação do sujeito, tornando o verbo transitivo indireto invariável na 3ª pessoa do singular.",
    explicacao: "GABARITO: CERTO. Com verbos transitivos indiretos (tratar de), intransitivos ou de ligação, o pronome 'se' funciona como índice de indeterminação do sujeito (IIS), exigindo o verbo obrigatoriamente no singular.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-008",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.sintaxe_periodo,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Em: 'Apuraram-se as denúncias anônimas.', a partícula 'se' atua como pronome apassivador (partícula apassivadora), sendo o termo 'as denúncias anônimas' o sujeito paciente da oração em voz passiva sintética.",
    explicacao: "GABARITO: CERTO. O verbo 'apurar' é transitivo direto; acompanhado de 'se' com sujeito paciente no plural ('as denúncias anônimas'), constrói-se a voz passiva sintética ('as denúncias anônimas foram apuradas').",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-009",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.ortografia_acentuacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Os vocábulos 'polícia', 'inquérito' e 'tático' são acentuados graficamente com base na mesma regra de acentuação.",
    explicacao: "GABARITO: ERRADO. 'Inquérito' e 'tático' são proparoxítonas (todas são acentuadas). Já 'polícia' é paroxítona terminada em ditongo crescente oral (ou proparoxítona eventual/aparente segundo parcela da gramática, mas regida pela regra das paroxítonas no padrão oficial). Não compartilham a mesma regra estrita.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-port-02-010",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.ortografia_acentuacao,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Com o advento do Novo Acordo Ortográfico, as formas verbais 'veem' (do verbo ver) e 'leem' (do verbo ler) deixaram de receber acento circunflexo no hiato 'ee'.",
    explicacao: "GABARITO: CERTO. O Acordo Ortográfico eliminou o acento circunflexo nos hiatos 'ee' (creem, deem, leem, veem) e 'oo' (voo, enjoo, perdoo).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-16: FGV (Múltipla Escolha - 5 alts)
  {
    idSlug: "b9-port-02-011",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.concordancia,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Assinale a opção em que a concordância verbal e nominal atende rigorosamente à norma-padrão da língua portuguesa:",
    explicacao: "GABARITO: C. Em 'Seguem anexos ao inquérito os laudos periciais', o adjetivo 'anexos' concorda em gênero e número com o sujeito 'os laudos periciais'. Em A: 'Faz dez anos' (tempo decorrido = impessoal). Em B: 'Havia muitas pessoas' (haver impessoal). Em D: 'Vende-se casas' -> 'Vendem-se casas'. Em E: 'Menos' é invariável.",
    alternativas: [
      { texto: "Fazem dez anos que a delegacia especializada foi instalada na capital.", correta: false },
      { texto: "Haviam muitas testemunhas aguardando na sala de oitivas da delegacia.", correta: false },
      { texto: "Seguem anexos ao inquérito policial os laudos periciais e as cópias dos mandados.", correta: true },
      { texto: "Vende-se apartamentos funcionais para os novos agentes de segurança pública.", correta: false },
      { texto: "Havia menas viaturas disponíveis para o patrulhamento preventivo noturno.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-012",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Assinale a frase em que o uso do acento grave indicativo de crase é facultativo:",
    explicacao: "GABARITO: B. Diante de pronomes possessivos femininos no singular ('minha', 'tua', 'sua', 'nossa'), o uso do artigo é facultativo, tornando o acento grave de crase facultativo após preposição 'a'.",
    alternativas: [
      { texto: "O agente entregou o relatório à perita oficial do caso.", correta: false },
      { texto: "O delegado solicitou apoio à minha equipe de investigação.", correta: true },
      { texto: "Os policiais dirigiram-se à pé até o esconderijo dos criminosos.", correta: false },
      { texto: "O mandado foi cumprido à uma hora da madrugada.", correta: false },
      { texto: "A autoridade policial estava disposta à colaborar com os peritos.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-013",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.sintaxe_periodo,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em relação à colocação pronominal, assinale a oração que está em conformidade com as regras da norma culta:",
    explicacao: "GABARITO: D. A palavra negativa 'Não' é fator atrativo obrigatório de próclise ('Não se constataram'). Em A: não se inicia período com pronome oblíquo átono ('Disseram-me'). Em B: futuro do presente exige mesóclise na ausência de atrativo ('Apresentar-se-á'). Em C: advérbio 'Jamais' atrai próclise ('Jamais me esquecerei'). Em E: 'Em se tratando' é próclise obrigatória em oração gerundial regida da preposição 'em'.",
    alternativas: [
      { texto: "Me disseram que o comando geral autorizou a deflagração da operação.", correta: false },
      { texto: "O oficial apresentará-se ao tribunal para prestar esclarecimentos amanhã.", correta: false },
      { texto: "Jamais esquecerei-me das instruções de tiro recebidas no curso de formação.", correta: false },
      { texto: "Não se constataram indícios de adulteração no chassi da motocicleta.", correta: true },
      { texto: "Tratando-se em de segurança pública, os investimentos devem ser prioritários.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-014",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.pontuacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Assinale a opção em que a pontuação está inteiramente correta segundo o padrão culto:",
    explicacao: "GABARITO: A. O adjunto adverbial de tempo deslocado de grande extensão ('Durante a madrugada de ontem,') está devidamente isolado por vírgula, e a oração principal segue a ordem direta sem rupturas indevidas.",
    alternativas: [
      { texto: "Durante a madrugada de ontem, os policiais civis cumpriram três mandados de prisão preventiva.", correta: true },
      { texto: "Os policiais civis, cumpriram três mandados de prisão preventiva durante a madrugada de ontem.", correta: false },
      { texto: "Durante a madrugada de ontem os policiais civis cumpriram, três mandados de prisão preventiva.", correta: false },
      { texto: "Os policiais civis cumpriram, três mandados de prisão preventiva, durante a madrugada de ontem.", correta: false },
      { texto: "Durante a madrugada de ontem os policiais civis cumpriram três mandados, de prisão preventiva.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-015",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Considerando a regência do verbo 'implicar', assinale a frase redigida em estrita observância à norma-padrão:",
    explicacao: "GABARITO: E. O verbo 'implicar' no sentido de acarretar, produzir como consequência ou exigir é transitivo direto (não rege a preposição 'em'): 'implicará sanções severas'.",
    alternativas: [
      { texto: "A conduta do servidor implicará em demissão a bem do serviço público.", correta: false },
      { texto: "O descumprimento das normas implicará em graves penalidades disciplinares.", correta: false },
      { texto: "A recusa injustificada implicará em preclusão do direito de defesa.", correta: false },
      { texto: "A ausência de provas materiais implicará na nulidade do processo penal.", correta: false },
      { texto: "A falsificação do documento público implicará severas sanções penais ao agente.", correta: true },
    ],
  },
  {
    idSlug: "b9-port-02-016",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.ortografia_acentuacao,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a alternativa em que todas as palavras estão grafadas corretamente segundo as normas ortográficas vigentes:",
    explicacao: "GABARITO: B. As palavras 'reivindicar', 'beneficência', 'estupro' e 'supérfluo' estão ortograficamente perfeitas. Em A: 'excessão' (o correto é exceção); em C: 'paralisar' (o correto é com 's', e não com 'z'); em D: 'previlégio' (o correto é privilégio); em E: 'enchuto' (o correto é enxuto).",
    alternativas: [
      { texto: "Exceção, reinvidicar, obsessão, pretensão.", correta: false },
      { texto: "Reivindicar, beneficência, estupro, supérfluo.", correta: true },
      { texto: "Paralizar, espontâneo, conscencioso, ascensão.", correta: false },
      { texto: "Privilégio, previlégio, presunçoso, concisão.", correta: false },
      { texto: "Enchuto, chiste, mexerico, assessoria.", correta: false },
    ],
  },

  // 17-19: VUNESP (Múltipla Escolha - 5 alts)
  {
    idSlug: "b9-port-02-017",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.ortografia_acentuacao,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a alternativa que preenche correta e respectivamente as lacunas do texto:\n'O policial não compreendeu o ______ daquela decisão e perguntou ______ a operação havia sido cancelada.'",
    explicacao: "GABARITO: A. O primeiro 'porquê' é substantivo (vem precedido do artigo 'o', significa motivo/razão, com acento circunflexo e junto). O segundo 'por que' é pronome interrogativo indireto (separado e sem acento, equivalente a 'por qual razão').",
    alternativas: [
      { texto: "porquê — por que", correta: true },
      { texto: "por que — porque", correta: false },
      { texto: "porque — por quê", correta: false },
      { texto: "por quê — por que", correta: false },
      { texto: "porquê — por quê", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-018",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O sinal indicativo de crase está empregado corretamente em:",
    explicacao: "GABARITO: C. Em 'às pressas' (locução adverbial de modo feminina), a crase é obrigatória. Em A: antes de verbo ('fazer') não ocorre crase. Em B: antes de palavra masculina ('pé') não ocorre crase. Em D: antes de pronome indefinido ('todos') não ocorre crase. Em E: antes de pronome pessoal ('ela') não ocorre crase.",
    alternativas: [
      { texto: "O patrulhamento começou à fazer efeito imediato no bairro.", correta: false },
      { texto: "Os policiais perseguiram o suspeito à pé pelas vielas.", correta: false },
      { texto: "A equipe tática deslocou-se às pressas para conter a rebelião.", correta: true },
      { texto: "O comando prestou homenagens à todos os veteranos da corporação.", correta: false },
      { texto: "O agente dirigiu a palavra à ela de forma respeitosa.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-019",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.concordancia,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a alternativa que apresenta a correta concordância nominal:",
    explicacao: "GABARITO: D. 'Bastantes' funciona como pronome adjetivo indefinido modificando o substantivo 'provas', devendo flexionar-se no plural (= muitas provas). Em A: 'meio-dia e meia' (hora). Em B: 'É necessária a cautela' (com artigo 'a'). Em C: 'estavam sós' (= sozinhos). Em E: 'Elas mesmas' (concorda com elas).",
    alternativas: [
      { texto: "A diligência policial encerrou-se ao meio-dia e meio.", correta: false },
      { texto: "É necessário a cautela na preservação do local do crime.", correta: false },
      { texto: "Os peritos criminais estavam só na cena do crime.", correta: false },
      { texto: "Havia bastantes provas materiais para subsidiar o indiciamento do réu.", correta: true },
      { texto: "Elas mesmo organizaram os arquivos do cartório policial.", correta: false },
    ],
  },

  // 20-21: AOCP (Múltipla Escolha - 5 alts)
  {
    idSlug: "b9-port-02-020",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.sintaxe_periodo,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na oração: 'O policial militar foi condecorado pelo governador do Estado.', a expressão 'pelo governador do Estado' exerce a função sintática de:",
    explicacao: "GABARITO: B. Na voz passiva analítica ('foi condecorado'), o termo preposicionado que pratica a ação verbal classifica-se como agente da passiva.",
    alternativas: [
      { texto: "Objeto indireto.", correta: false },
      { texto: "Agente da passiva.", correta: true },
      { texto: "Complemento nominal.", correta: false },
      { texto: "Adjunto adnominal.", correta: false },
      { texto: "Aposto explicativo.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-021",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.pontuacao,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Em: 'Senhor Delegado, os mandados de busca foram integralmente cumpridos.', a vírgula foi empregada para isolar:",
    explicacao: "GABARITO: E. 'Senhor Delegado' é o chamamento/invocação direta do interlocutor, configurando vocativo, o qual deve ser obrigatoriamente isolado por vírgula.",
    alternativas: [
      { texto: "Um aposto explicativo.", correta: false },
      { texto: "Uma oração subordinada adjetiva restritiva.", correta: false },
      { texto: "Um adjunto adverbial de modo.", correta: false },
      { texto: "O sujeito paciente da oração.", correta: false },
      { texto: "Um vocativo.", correta: true },
    ],
  },

  // 22-25: IBFC (Múltipla Escolha - 5 alts)
  {
    idSlug: "b9-port-02-022",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.ortografia_acentuacao,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A palavra que deve ser obrigatoriamente acentuada pela regra das proparoxítonas é:",
    explicacao: "GABARITO: C. 'Carcerário' / 'Carcerária' / 'Cárcere': 'Cárcere' é proparoxítona (antepenúltima sílaba tônica), devendo ser acentuada. 'Juiz' é oxítona terminada em 'z' (não acentuada); 'Rubrica' é paroxítona (não acentuada); 'Item' é paroxítona terminada em 'em' (não acentuada); 'Pudico' é paroxítona.",
    alternativas: [
      { texto: "Juiz.", correta: false },
      { texto: "Rubrica.", correta: false },
      { texto: "Cárcere.", correta: true },
      { texto: "Pudico.", correta: false },
      { texto: "Item.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-023",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.regencia_crase,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quanto à regência do verbo 'obedecer', assinale a frase correta de acordo com a norma culta:",
    explicacao: "GABARITO: A. O verbo 'obedecer' (e desobedecer) é transitivo indireto, regendo obrigatoriamente a preposição 'a' ('obedecer aos superiores', 'obedecer às normas').",
    alternativas: [
      { texto: "O soldado deve obedecer aos superiores hierárquicos e às normas disciplinares.", correta: true },
      { texto: "O soldado deve obedecer os superiores hierárquicos e as normas disciplinares.", correta: false },
      { texto: "O soldado deve obedecer com os superiores hierárquicos e pelas normas disciplinares.", correta: false },
      { texto: "O soldado deve obedecer sobre os superiores hierárquicos.", correta: false },
      { texto: "O soldado deve obedecer em todas normas sem questionar.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-024",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.concordancia,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Assinale a opção em que a concordância verbal está correta:",
    explicacao: "GABARITO: D. 'Mais de um policial foi condecorado': com a expressão 'mais de um', o verbo concorda no singular (salvo se houver reciprocidade ou repetição). Em A: 'Fazem dois anos' -> 'Faz dois anos'. Em B: 'Haviam viaturas' -> 'Havia viaturas'. Em C: 'Sobrou muitos cartuchos' -> 'Sobraram muitos cartuchos'. Em E: 'Falta dez minutos' -> 'Faltam dez minutos'.",
    alternativas: [
      { texto: "Fazem dois anos que ingressei na corporação.", correta: false },
      { texto: "Haviam três viaturas posicionadas no cruzamento.", correta: false },
      { texto: "Sobrou muitos cartuchos deflagrados no local do tiroteio.", correta: false },
      { texto: "Mais de um policial foi condecorado pelo ato de bravura.", correta: true },
      { texto: "Falta dez minutos para o término do plantão policial.", correta: false },
    ],
  },
  {
    idSlug: "b9-port-02-025",
    disciplina_id: TAXONOMIA.disciplinas.portugues,
    assunto_id: TAXONOMIA.assuntos.sintaxe_periodo,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Na frase: 'O escrivão redigiu o termo de depoimento com rapidez e perícia.', os termos 'com rapidez e perícia' expressam circunstância adverbial de:",
    explicacao: "GABARITO: B. A expressão indica o modo como a ação verbal de redigir foi executada pelo escrivão, constituindo adjunto adverbial de modo.",
    alternativas: [
      { texto: "Tempo.", correta: false },
      { texto: "Modo.", correta: true },
      { texto: "Lugar.", correta: false },
      { texto: "Causa.", correta: false },
      { texto: "Finalidade.", correta: false },
    ],
  },
];
