import { TAXONOMIA } from "./taxonomia.mjs";

export const rlm01Questoes = [
  // 1-12. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-rlm-01-001",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considere a proposição P: 'Se o agente cumpre o mandado com diligência, então a prova pericial é preservada e o suspeito é encaminhado à custódia'. A proposição P é logicamente equivalente a: 'Se a prova pericial não for preservada ou o suspeito não for encaminhado à custódia, então o agente não cumpriu o mandado com diligência'.",
    explicacao: "GABARITO: CERTO. Pela equivalência da contrapositiva (p -> q <=> ~q -> ~p), se q é (A e B), sua negação é (~A ou ~B) pelas Leis de De Morgan. Portanto, ~q -> ~p é (~A ou ~B) -> ~p.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-002",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A negação lógica da proposição 'Todos os policiais rodoviários federais realizam plantões noturnos e participam de cursos táticos' é expressa por 'Nenhum policial rodoviário federal realiza plantões noturnos e participa de cursos táticos'.",
    explicacao: "GABARITO: ERRADO. A negação do quantificador universal 'Todo A é B' é particular: 'Existe pelo menos um A que não é B' (ou 'Algum A não é B'). Dizer 'Nenhum A é B' é incorreto.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-rlm-01-003",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A tabela-verdade da proposição composta [(P -> Q) ^ P] -> Q possui apenas valores lógicos Vadeiros (V) na sua coluna final, configurando, portanto, uma tautologia.",
    explicacao: "GABARITO: CERTO. Trata-se da regra de inferência Modus Ponens. Se (P -> Q) e P são verdadeiros, Q é obrigatoriamente verdadeiro. A condicional resultante é sempre verdadeira, logo, uma tautologia.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-004",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A negação lógica da proposição condicional 'Se o perito conclui o laudo dactiloscópico, então o inquérito é relatado' é equivalente a 'O perito conclui o laudo dactiloscópico e o inquérito não é relatado'.",
    explicacao: "GABARITO: CERTO. A negação de uma condicional (P -> Q) é dada pela regra do MANE (Mantém a primeira E Nega a segunda): ~(P -> Q) <=> P ^ ~Q.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-005",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em uma delegacia com 60 policiais, sabe-se que 35 operam armamento pesado de fuzil, 28 possuem habilitação para pilotagem tática de embarcações e 12 dominam ambas as especialidades. Nessa situação, o número de policiais que não dominam nenhuma dessas duas especialidades é igual a 9.",
    explicacao: "GABARITO: CERTO. Pelo princípio da inclusão-exclusão: Total(Fuzil U Barco) = 35 + 28 - 12 = 51. O número de policiais sem nenhuma especialidade é 60 - 51 = 9.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-006",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para formar uma equipe tática especial composta por exatamente 4 agentes e 2 escrivães, a partir de um grupo disponível de 8 agentes e 5 escrivães, a quantidade de equipes distintas que podem ser formadas é superior a 650.",
    explicacao: "GABARITO: CERTO. C(8,4) * C(5,2) = [ (8*7*6*5)/(4*3*2*1) ] * [ (5*4)/(2*1) ] = 70 * 10 = 700 equipes. Como 700 > 650, o item está correto.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-007",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.probabilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Em uma blitz da PRF, a probabilidade de um veículo abordado apresentar irregularidade documental é de 0,20. Ao abordar aleatoriamente 3 veículos de forma independente, a probabilidade de que pelo menos um apresente irregularidade documental é igual a 0,488.",
    explicacao: "GABARITO: CERTO. A probabilidade complementar (nenhum apresentar irregularidade) é (1 - 0,20)^3 = 0,80^3 = 0,512. Logo, P(pelo menos 1) = 1 - 0,512 = 0,488 (48,8%).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-008",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A sentença 'Entregue imediatamente o relatório de inteligência ao delegado!' é uma proposição lógica simples cujo valor lógico pode ser classificado em verdadeiro ou falso.",
    explicacao: "GABARITO: ERRADO. Sentenças imperativas, interrogativas, exclamativas e sentenças abertas não são proposições lógicas, pois não possuem valor lógico valorativo (V ou F).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-rlm-01-009",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A proposição 'Ou o suspeito confessou o crime ou foi liberado sob fiança' é uma disjunção exclusiva (p v_ q), sendo falsa caso ambas as proposições simples componentes sejam simultaneamente verdadeiras.",
    explicacao: "GABARITO: CERTO. Na disjunção exclusiva (ou... ou), a proposição composta só é verdadeira quando exatamente uma das componentes for verdadeira. Se ambas forem verdadeiras (ou ambas falsas), a proposição é falsa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-010",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Se for verdadeira a afirmação 'Nenhum atirador de elite é imprudente' e verdadeira a afirmação 'Alguns policiais táticos são imprudentes', conclui-se necessariamente que 'Alguns policiais táticos não são atiradores de elite'.",
    explicacao: "GABARITO: CERTO. Seja A = conjunto dos atiradores, I = imprudentes, T = policiais táticos. Temos A n I = vazio (disjuntos). Existe x pertencente a T n I. Como x está em I e I é disjunto de A, x não pode estar em A. Logo, esse x é um policial tático que não é atirador de elite.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-011",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O número de anagramas distintos da palavra 'POLICIA' (desconsiderando acento gráfico) que começam com a letra P e terminam com a letra A é igual a 120.",
    explicacao: "GABARITO: ERRADO. As letras da palavra POLICIA são: P, O, L, I, C, I, A (total 7 letras, com repetição da letra I duas vezes). Fixando P na 1ª posição e A na última, restam 5 letras no meio: O, L, I, C, I. O número de permutações com repetição é P_5^(2) = 5! / 2! = 120 / 2 = 60. O item diz 120, logo está ERRADO.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b9-rlm-01-012",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.probabilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Em uma urna há 6 distintivos prateados e 4 distintivos dourados. Retirando-se simultaneamente e ao acaso 2 distintivos, a probabilidade de que ambos sejam dourados é de 2/15.",
    explicacao: "GABARITO: CERTO. Casos favoráveis: C(4,2) = 6. Casos possíveis: C(10,2) = 45. Probabilidade = 6/45 = 2/15.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 13-19. FGV (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-rlm-01-013",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Considere verdadeiras as três premissas a seguir:\n1. Se o suspeito estava na cidade, então ele participou do assalto.\n2. Se o suspeito participou do assalto ou comprou o veículo, então ele possui comparsas.\n3. O suspeito não possui comparsas.\n\nA partir dessas premissas, é logicamente CORRETO concluir que:",
    explicacao: "GABARITO: D. Da premissa 3 (~C), aplicando Modus Tollens na premissa 2, temos ~(P ou V), o que pelas Leis de De Morgan implica que ~P (não participou do assalto) E ~V (não comprou o veículo). De ~P, aplicando Modus Tollens na premissa 1, conclui-se que o suspeito não estava na cidade (~S). Logo, o suspeito não estava na cidade e não participou do assalto.",
    alternativas: [
      { texto: "O suspeito estava na cidade e comprou o veículo.", correta: false },
      { texto: "O suspeito participou do assalto mas não comprou o veículo.", correta: false },
      { texto: "O suspeito comprou o veículo mas não possui comparsas.", correta: false },
      { texto: "O suspeito não estava na cidade e não participou do assalto.", correta: true },
      { texto: "O suspeito possui comparsas fora da cidade.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-014",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Assinale a alternativa que apresenta uma proposição logicamente equivalente à sentença: 'Se chove torrencialmente na rodovia, então a pista fica escorregadia':",
    explicacao: "GABARITO: B. Pela equivalência P -> Q <=> ~P v Q (regra do Neymar: Nega a primeira OU Mantém a segunda), a sentença é equivalente a 'Não chove torrencialmente na rodovia ou a pista fica escorregadia'.",
    alternativas: [
      { texto: "Se a pista fica escorregadia, então chove torrencialmente na rodovia.", correta: false },
      { texto: "Não chove torrencialmente na rodovia ou a pista fica escorregadia.", correta: true },
      { texto: "Chove torrencialmente na rodovia e a pista não fica escorregadia.", correta: false },
      { texto: "Se não chove torrencialmente na rodovia, a pista não fica escorregadia.", correta: false },
      { texto: "Chove torrencialmente na rodovia ou a pista fica escorregadia.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-015",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em um grupo de 100 agentes de segurança pública, 70 praticam tiro defensivo, 50 praticam defesa pessoal e 40 praticam condicionamento tático. Todos praticam pelo menos uma das três modalidades. Sabendo que exatamente 20 agentes praticam as três modalidades, quantos agentes praticam EXATAMENTE duas modalidades?",
    explicacao: "GABARITO: A. Seja T = 70, D = 50, C = 40. Pela fórmula dos três conjuntos: Total = T + D + C - (soma das interseções duplas) + interseção tripla. 100 = 70 + 50 + 40 - S2 + 20 => 100 = 180 - S2 => S2 = 80. Sabe-se que a soma das interseções 2 a 2 (S2) inclui a interseção tripla 3 vezes. Os que praticam EXATAMENTE duas modalidades = S2 - 3*(tripla) = 80 - 3*(20) = 80 - 60 = 20 agentes.",
    alternativas: [
      { texto: "20", correta: true },
      { texto: "30", correta: false },
      { texto: "40", correta: false },
      { texto: "50", correta: false },
      { texto: "10", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-016",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Um sistema criptográfico de acesso a um cofre de evidências da Polícia Federal exige uma senha formada por 3 letras distintas escolhidas entre as vogais (A, E, I, O, U) seguidas por 3 algarismos distintos escolhidos entre os dígitos ímpares (1, 3, 5, 7, 9). O número total de senhas diferentes possíveis é:",
    explicacao: "GABARITO: C. Letras: arranjo de 5 vogais 3 a 3 = 5 * 4 * 3 = 60. Algarismos: arranjo de 5 dígitos ímpares 3 a 3 = 5 * 4 * 3 = 60. Total de senhas = 60 * 60 = 3.600.",
    alternativas: [
      { texto: "1.200", correta: false },
      { texto: "2.400", correta: false },
      { texto: "3.600", correta: true },
      { texto: "7.200", correta: false },
      { texto: "14.400", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-017",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.probabilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Dois atiradores de elite da polícia realizam disparos simultâneos e independentes contra um mesmo alvo em situação de refém. A probabilidade de o Atirador 1 acertar o alvo é 0,90 e a probabilidade de o Atirador 2 acertar o alvo é 0,80. A probabilidade de o alvo ser atingido por pelo menos um dos disparos é:",
    explicacao: "GABARITO: E. A probabilidade de ambos errarem é P(erro) = (1 - 0,90) * (1 - 0,80) = 0,10 * 0,20 = 0,02. Portanto, P(pelo menos 1 acertar) = 1 - 0,02 = 0,98 (98%).",
    alternativas: [
      { texto: "0,72", correta: false },
      { texto: "0,85", correta: false },
      { texto: "0,90", correta: false },
      { texto: "0,94", correta: false },
      { texto: "0,98", correta: true },
    ],
  },
  {
    idSlug: "b9-rlm-01-018",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A negação da proposição 'O mandado foi expedido e o investigado fugiu' é logicamente equivalente a:",
    explicacao: "GABARITO: A. Pela 1ª Lei de De Morgan: ~(P ^ Q) <=> ~P v ~Q ('O mandado não foi expedido OU o investigado não fugiu').",
    alternativas: [
      { texto: "O mandado não foi expedido ou o investigado não fugiu.", correta: true },
      { texto: "O mandado não foi expedido e o investigado não fugiu.", correta: false },
      { texto: "Se o mandado não foi expedido, o investigado fugiu.", correta: false },
      { texto: "O mandado foi expedido mas o investigado não fugiu.", correta: false },
      { texto: "O investigado não fugiu se o mandado foi expedido.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-019",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Considere a afirmação: 'Nenhum militar do batalhão foi reprovado no teste de aptidão física'. A negação lógica dessa afirmação é:",
    explicacao: "GABARITO: D. A negação de 'Nenhum A é B' é 'Pelo menos um A é B' (ou 'Existe algum A que é B'). Logo: 'Pelo menos um militar do batalhão foi reprovado no teste de aptidão física'.",
    alternativas: [
      { texto: "Todos os militares do batalhão foram reprovados no teste de aptidão física.", correta: false },
      { texto: "Nenhum militar do batalhão foi aprovado no teste de aptidão física.", correta: false },
      { texto: "Todos os militares do batalhão foram aprovados no teste de aptidão física.", correta: false },
      { texto: "Pelo menos um militar do batalhão foi reprovado no teste de aptidão física.", correta: true },
      { texto: "A maioria dos militares do batalhão foi aprovada com louvor.", correta: false },
    ],
  },

  // 20-23. VUNESP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-rlm-01-020",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Se Carlos é policial civil, então Débora é perita criminal. Se Débora é perita criminal, então Eduardo é médico legista. Sabe-se que Eduardo NÃO é médico legista. Logo, conclui-se corretamente que:",
    explicacao: "GABARITO: B. Se Eduardo não é médico legista (~E), pela contrapositiva da 2ª premissa (D -> E), Débora não é perita criminal (~D). Daí, pela contrapositiva da 1ª premissa (C -> D), Carlos não é policial civil (~C). Logo: Débora não é perita criminal e Carlos não é policial civil.",
    alternativas: [
      { texto: "Carlos é policial civil e Débora não é perita criminal.", correta: false },
      { texto: "Carlos não é policial civil e Débora não é perita criminal.", correta: true },
      { texto: "Débora é perita criminal mas Carlos não é policial.", correta: false },
      { texto: "Carlos e Eduardo são médicos legistas.", correta: false },
      { texto: "Débora é policial civil e Carlos é perito criminal.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-021",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Uma viatura de patrulhamento ostensivo deve ser tripulada por 3 policiais militares escolhidos entre 7 soldados disponíveis no pelotão. A quantidade de guarnições distintas que podem ser formadas é:",
    explicacao: "GABARITO: C. Trata-se de combinação simples: C(7,3) = (7 * 6 * 5) / (3 * 2 * 1) = 35 guarnições.",
    alternativas: [
      { texto: "21", correta: false },
      { texto: "28", correta: false },
      { texto: "35", correta: true },
      { texto: "42", correta: false },
      { texto: "210", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-022",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em uma delegacia regional, 80 inquéritos foram instaurados no semestre. Desses, 45 apuram crimes contra a pessoa, 38 apuram crimes contra o patrimônio e 15 apuram ambos os tipos criminais conexos. O número de inquéritos que não apuram crimes contra a pessoa nem contra o patrimônio é:",
    explicacao: "GABARITO: A. Total(Pessoa U Patrimônio) = 45 + 38 - 15 = 68. O número de inquéritos restantes é 80 - 68 = 12.",
    alternativas: [
      { texto: "12", correta: true },
      { texto: "18", correta: false },
      { texto: "22", correta: false },
      { texto: "26", correta: false },
      { texto: "30", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-023",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.probabilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Um dado comum de 6 faces não viciado é lançado duas vezes consecutivas em um exercício de simulação balística. A probabilidade de a soma dos dois números obtidos ser igual a 8 é:",
    explicacao: "GABARITO: D. Espaço amostral = 6 * 6 = 36 pares. Pares cuja soma é 8: (2,6), (3,5), (4,4), (5,3), (6,2) -> total 5 pares favoráveis. Probabilidade = 5/36.",
    alternativas: [
      { texto: "1/6", correta: false },
      { texto: "1/9", correta: false },
      { texto: "1/12", correta: false },
      { texto: "5/36", correta: true },
      { texto: "7/36", correta: false },
    ],
  },

  // 24-26. AOCP (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-rlm-01-024",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Dadas as proposições simples p: 'O alarme soou' e q: 'As celas foram trancadas', a representação simbólica da proposição 'Se o alarme soou, então as celas foram trancadas' é:",
    explicacao: "GABARITO: B. A condicional 'se... então' é representada pelo conectivo lógico seta (->): p -> q.",
    alternativas: [
      { texto: "p ^ q", correta: false },
      { texto: "p -> q", correta: true },
      { texto: "p v q", correta: false },
      { texto: "p <-> q", correta: false },
      { texto: "~p -> ~q", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-025",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Cinco policiais militares em fila indiana devem se posicionar para uma revista operacional. Sabendo que o sargento comandante da equipe deve obrigatoriamente ocupar o primeiro lugar da fila, de quantas maneiras distintas esses 5 policiais podem ser organizados?",
    explicacao: "GABARITO: C. O sargento tem 1 opção (a primeira posição). Os demais 4 policiais podem permutar livremente nas 4 posições restantes: P4 = 4! = 4 * 3 * 2 * 1 = 24 maneiras.",
    alternativas: [
      { texto: "120", correta: false },
      { texto: "60", correta: false },
      { texto: "24", correta: true },
      { texto: "12", correta: false },
      { texto: "5", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-026",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A negação lógica da proposição 'Lucas é guarda municipal ou Marcos é agente de trânsito' é:",
    explicacao: "GABARITO: E. Pela 2ª Lei de De Morgan: ~(p v q) <=> ~p ^ ~q ('Lucas não é guarda municipal E Marcos não é agente de trânsito').",
    alternativas: [
      { texto: "Lucas é guarda municipal e Marcos é agente de trânsito.", correta: false },
      { texto: "Lucas não é guarda municipal ou Marcos não é agente de trânsito.", correta: false },
      { texto: "Se Lucas não é guarda municipal, Marcos é agente de trânsito.", correta: false },
      { texto: "Lucas é guarda municipal se, e somente se, Marcos for agente de trânsito.", correta: false },
      { texto: "Lucas não é guarda municipal e Marcos não é agente de trânsito.", correta: true },
    ],
  },

  // 27-30. IBFC (Múltipla Escolha - 5 alternativas)
  {
    idSlug: "b9-rlm-01-027",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Uma proposição composta com duas proposições simples componentes (p e q) possui uma tabela-verdade com exatamente quantas linhas?",
    explicacao: "GABARITO: A. O número de linhas da tabela-verdade é dado por 2^n, onde n é o número de proposições simples. Para n = 2, temos 2^2 = 4 linhas.",
    alternativas: [
      { texto: "4 linhas.", correta: true },
      { texto: "2 linhas.", correta: false },
      { texto: "6 linhas.", correta: false },
      { texto: "8 linhas.", correta: false },
      { texto: "16 linhas.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-028",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.probabilidade,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Ao sortear ao acaso uma viatura numerada de 1 a 20 em um pátio do batalhão, qual é a probabilidade de a viatura escolhida ter número múltiplo de 4?",
    explicacao: "GABARITO: B. Múltiplos de 4 entre 1 e 20: {4, 8, 12, 16, 20} -> 5 números. Probabilidade = 5/20 = 1/4 = 25%.",
    alternativas: [
      { texto: "20%", correta: false },
      { texto: "25%", correta: true },
      { texto: "30%", correta: false },
      { texto: "35%", correta: false },
      { texto: "40%", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-029",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A proposição contrapositiva de 'Se o agente penitenciário inspeciona o perímetro, então a segurança da muralha é mantida' é:",
    explicacao: "GABARITO: C. A contrapositiva de (p -> q) é (~q -> ~p): 'Se a segurança da muralha não é mantida, então o agente penitenciário não inspeciona o perímetro'.",
    alternativas: [
      { texto: "Se o agente penitenciário não inspeciona o perímetro, então a segurança da muralha não é mantida.", correta: false },
      { texto: "Se a segurança da muralha é mantida, então o agente penitenciário inspeciona o perímetro.", correta: false },
      { texto: "Se a segurança da muralha não é mantida, então o agente penitenciário não inspeciona o perímetro.", correta: true },
      { texto: "O agente penitenciário inspeciona o perímetro ou a segurança da muralha não é mantida.", correta: false },
      { texto: "A segurança da muralha é mantida e o agente não inspeciona o perímetro.", correta: false },
    ],
  },
  {
    idSlug: "b9-rlm-01-030",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Considere verdadeiras as premissas: 'Todo guarda municipal utiliza colete balístico' e 'Alguns guardas municipais são socorristas habilitados'. Conclui-se logicamente que:",
    explicacao: "GABARITO: D. Se todo guarda usa colete balístico e alguns guardas são socorristas, então esses guardas socorristas usam colete balístico. Portanto: 'Alguns socorristas habilitados utilizam colete balístico'.",
    alternativas: [
      { texto: "Nenhum socorrista habilitado utiliza colete balístico.", correta: false },
      { texto: "Todos os socorristas habilitados são guardas municipais.", correta: false },
      { texto: "Todo guarda municipal é socorrista habilitado.", correta: false },
      { texto: "Alguns socorristas habilitados utilizam colete balístico.", correta: true },
      { texto: "Nenhum guarda municipal deixa de ser socorrista habilitado.", correta: false },
    ],
  },
];
