import { TAXONOMIA } from "./taxonomia.mjs";

export const rlmInfo01Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "rlm-inf-01-001",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considere a proposição lógica: 'O suspeito foi detido em flagrante ou a arma do crime foi apreendida pela perícia.' Sabendo que a primeira proposição simples é verdadeira e a segunda é falsa, o valor lógico da proposição composta é verdadeiro.",
    explicacao: "GABARITO: CERTO. Na disjunção inclusiva (conectivo 'ou' - v), a proposição composta 'P v Q' é verdadeira se pelo menos uma das proposições simples componentes for verdadeira (V v F = V).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-002",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A negação lógica da proposição condicional 'Se o motorista ultrapassou o limite de velocidade, então ele foi multado' é equivalente a: 'O motorista ultrapassou o limite de velocidade e não foi multado'.",
    explicacao: "GABARITO: CERTO. Regra de negação da condicional (~(P -> Q) <=> P ^ ~Q - mnemônico 'MANÉ': Mantém a primeira e Nega a segunda). Logo, a negação é 'P e não Q'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-003",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos_conjuntos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considere as premissas: 'Todo policial civil é servidor público' e 'Nenhum criminoso é servidor público'. Conclui-se logicamente que 'Nenhum criminoso é policial civil'.",
    explicacao: "GABARITO: CERTO. Diagramas lógicos: O conjunto 'Policial Civil' (PC) está totalmente contido no conjunto 'Servidor Público' (SP). Como o conjunto 'Criminoso' (C) é disjunto de SP (interseção vazia), C é necessariamente disjunto de PC. Logo, nenhum criminoso é policial civil.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-004",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A proposição 'Se o alarme do presídio toca, então os agentes reforçam a guarda' é logicamente equivalente à contrapositiva: 'Se os agentes não reforçam a guarda, então o alarme do presídio não tocou'.",
    explicacao: "GABARITO: CERTO. Princípio da contraposição lógica: P -> Q <=> ~Q -> ~P. A inversão com negação de ambas as proposições mantém a equivalência lógica estrita.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-005",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Para compor uma equipe pericial multidisciplinar de 4 peritos a partir de um grupo de 6 peritos criminais federais e 4 papiloscopistas, havendo a exigência de que a equipe contenha exatamente 2 peritos criminais e 2 papiloscopistas, o número total de equipes distintas que podem ser formadas é igual a 90.",
    explicacao: "GABARITO: CERTO. Combinação simples: C(6,2) = (6*5)/2 = 15; C(4,2) = (4*3)/2 = 6. Pelo princípio fundamental da contagem: 15 * 6 = 90 equipes possíveis.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-006",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A tabela-verdade de uma proposição composta constituída por 3 proposições simples distintas possui exatamente 8 linhas.",
    explicacao: "GABARITO: CERTO. O número de linhas de uma tabela-verdade com n proposições simples independentes é dado por 2^n. Para n = 3: 2^3 = 8 linhas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-007",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A negação da proposição com quantificador universal 'Todos os guardas municipais utilizam colete balístico' é dada por 'Nenhum guarda municipal utiliza colete balístico'.",
    explicacao: "GABARITO: ERRADO. A negação do quantificador universal 'Todo A é B' faz-se com um quantificador existencial negando o predicado ('Pelo menos um A não é B', 'Existe algum A que não é B' ou 'Algum A não é B'). 'Nenhum' é o contrário, e não a negação contraditória lógica.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "rlm-inf-01-008",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em uma urna há 10 fichas numeradas de 1 a 10 relativas a chamados de emergência. A probabilidade de se retirar ao acaso uma ficha cujo número seja simultaneamente par e primo é igual a 10%.",
    explicacao: "GABARITO: CERTO. O único número que é par e primo entre 1 e 10 é o número 2 (1 elemento favorável em 10 possíveis). Probabilidade = 1/10 = 0,10 = 10%.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-009",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A proposição lógica 'P ou não P' (P v ~P) constitui um exemplo clássico de tautologia, uma vez que sua tabela-verdade assume exclusivamente valor lógico verdadeiro em todas as suas linhas.",
    explicacao: "GABARITO: CERTO. P v ~P representa o princípio do terceiro excluído: se P é V, ~P é F (V v F = V); se P é F, ~P é V (F v V = V). Sendo sempre verdadeira, trata-se de tautologia.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-010",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos_conjuntos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em um presídio, 60 agentes trabalham no setor de custódia, 40 no setor de escolta e 15 em ambos os setores. O total de agentes que trabalham em pelo menos um desses dois setores é igual a 85.",
    explicacao: "GABARITO: CERTO. Teoria dos conjuntos: n(A U B) = n(A) + n(B) - n(A ∩ B) = 60 + 40 - 15 = 85 agentes.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 11-16. FGV (Múltipla Escolha)
  {
    idSlug: "rlm-inf-01-011",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Considere a proposição: 'O mandado de busca foi expedido e o suspeito foi localizado em sua residência.' A negação lógica dessa proposição (Leis de De Morgan) é:",
    explicacao: "GABARITO: A. Lei de De Morgan para conjunção: ~(P ^ Q) <=> ~P v ~Q. A negação de 'P e Q' é 'não P OU não Q'. Logo: 'O mandado de busca não foi expedido OU o suspeito não foi localizado em sua residência'.",
    alternativas: [
      { texto: "O mandado de busca não foi expedido OU o suspeito não foi localizado em sua residência.", correta: true },
      { texto: "O mandado de busca não foi expedido E o suspeito não foi localizado em sua residência.", correta: false },
      { texto: "Se o mandado de busca foi expedido, então o suspeito não foi localizado.", correta: false },
      { texto: "O mandado de busca foi expedido MAS o suspeito não foi localizado.", correta: false },
      { texto: "O suspeito foi localizado embora o mandado não tenha sido expedido.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-012",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Uma viatura da polícia possui 5 policiais a bordo. De quantas maneiras distintas esses 5 policiais podem se sentar nos 5 bancos da viatura?",
    explicacao: "GABARITO: B. Permutação simples de 5 elementos: P(5) = 5! = 5 * 4 * 3 * 2 * 1 = 120 maneiras.",
    alternativas: [
      { texto: "25.", correta: false },
      { texto: "120.", correta: true },
      { texto: "60.", correta: false },
      { texto: "24.", correta: false },
      { texto: "720.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-013",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A proposição bicondicional 'P se e somente se Q' (P <-> Q) é logicamente VERDADEIRA quando:",
    explicacao: "GABARITO: C. Na bicondicional (P <-> Q), o resultado é verdadeiro quando ambas as proposições simples têm o MESMO valor lógico (ambas verdadeiras ou ambas falsas: V <-> V = V; F <-> F = V).",
    alternativas: [
      { texto: "P é verdadeira e Q é falsa.", correta: false },
      { texto: "P é falsa e Q é verdadeira.", correta: false },
      { texto: "P e Q possuem valores lógicos idênticos (ambas V ou ambas F).", correta: true },
      { texto: "apenas quando P e Q forem proposições quantificadas universais.", correta: false },
      { texto: "exclusivamente quando P for verdadeira e Q assumir valor indeterminado.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-014",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Em um posto de fiscalização rodoviária, a probabilidade de um veículo abordado apresentar irregularidades nos pneus é de 20%. Se 1 veículo for selecionado aleatoriamente, a probabilidade de ele NÃO apresentar irregularidades é de:",
    explicacao: "GABARITO: D. Evento complementar: P(A') = 1 - P(A) = 1 - 0,20 = 0,80 = 80%.",
    alternativas: [
      { texto: "20%.", correta: false },
      { texto: "40%.", correta: false },
      { texto: "50%.", correta: false },
      { texto: "80%.", correta: true },
      { texto: "100%.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-015",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos_conjuntos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sejam os conjuntos A = {peritos em balística}, B = {peritos em documentoscopia} e C = {peritos em informática forense}. Se a interseção A ∩ B ∩ C contém 3 peritos, e cada par de interseção dupla (A∩B, A∩C, B∩C) contém exatamente 7 peritos (incluindo os 3 da tripla), quantos peritos dominam exatamente duas especialidades?",
    explicacao: "GABARITO: E. Em cada par de interseção: o total de 7 peritos inclui os 3 que dominam as três áreas. Logo, os que dominam EXATAMENTE duas áreas em cada par são 7 - 3 = 4 peritos. Como são 3 pares: 4 + 4 + 4 = 12 peritos.",
    alternativas: [
      { texto: "3.", correta: false },
      { texto: "6.", correta: false },
      { texto: "9.", correta: false },
      { texto: "21.", correta: false },
      { texto: "12.", correta: true },
    ],
  },
  {
    idSlug: "rlm-inf-01-016",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A proposição equivalente à condicional 'Se chover forte na serra, então haverá deslizamento de encosta' pode ser expressa na forma disjuntiva (regra da equivalência P -> Q <=> ~P v Q) por:",
    explicacao: "GABARITO: A. Equivalência da condicional por disjunção: P -> Q <=> ~P v Q ('Não P ou Q'). Logo: 'Não choveu forte na serra OU haverá deslizamento de encosta'.",
    alternativas: [
      { texto: "Não chove forte na serra OU há deslizamento de encosta.", correta: true },
      { texto: "Chove forte na serra E há deslizamento de encosta.", correta: false },
      { texto: "Não chove forte na serra E não há deslizamento de encosta.", correta: false },
      { texto: "Se não houver deslizamento, então chove forte na serra.", correta: false },
      { texto: "Haverá deslizamento somente se não chover forte.", correta: false },
    ],
  },
  // 17-20. VUNESP (Múltipla Escolha)
  {
    idSlug: "rlm-inf-01-017",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Dadas as proposições P: 'O policial está de serviço' (V) e Q: 'O policial está armado' (V), o valor lógico da conjunção 'P e Q' é:",
    explicacao: "GABARITO: B. A conjunção 'e' (^) é verdadeira quando ambas as proposições componentes forem verdadeiras (V ^ V = V).",
    alternativas: [
      { texto: "Falso.", correta: false },
      { texto: "Verdadeiro.", correta: true },
      { texto: "Indeterminado.", correta: false },
      { texto: "Contraditório.", correta: false },
      { texto: "Inconclusivo.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-018",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Quantos números de telefone funcionais de 4 dígitos podem ser formados utilizando apenas os algarismos 1, 2, 3, 4 e 5, sem repetição de dígitos?",
    explicacao: "GABARITO: C. Arranjo simples de 5 elementos tomados 4 a 4: A(5,4) = 5 * 4 * 3 * 2 = 120 números distintos.",
    alternativas: [
      { texto: "20.", correta: false },
      { texto: "60.", correta: false },
      { texto: "120.", correta: true },
      { texto: "625.", correta: false },
      { texto: "24.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-019",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.diagramas_logicos_conjuntos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Se 'Algum guarda municipal é faixa preta de judô' e 'Todos os faixas pretas de judô são disciplinados', conclui-se necessariamente que:",
    explicacao: "GABARITO: D. Diagramas lógicos: A interseção entre 'Guarda Municipal' e 'Faixa Preta' não é vazia. Como todos os faixas pretas estão dentro de 'Disciplinados', esses guardas faixas pretas são necessariamente disciplinados. Logo: 'Algum guarda municipal é disciplinado'.",
    alternativas: [
      { texto: "Todos os guardas municipais são disciplinados.", correta: false },
      { texto: "Nenhum guarda municipal é disciplinado.", correta: false },
      { texto: "Todos os disciplinados são guardas municipais.", correta: false },
      { texto: "Algum guarda municipal é disciplinado.", correta: true },
      { texto: "Nenhum faixa preta de judô é guarda municipal.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-020",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A negação lógica de 'O réu confessou o crime ou a testemunha mentiu' é:",
    explicacao: "GABARITO: E. Lei de De Morgan para disjunção: ~(P v Q) <=> ~P ^ ~Q. Nega-se a primeira, troca-se 'ou' por 'e' e nega-se a segunda: 'O réu NÃO confessou o crime E a testemunha NÃO mentiu'.",
    alternativas: [
      { texto: "O réu confessou o crime e a testemunha mentiu.", correta: false },
      { texto: "Se o réu não confessou, então a testemunha não mentiu.", correta: false },
      { texto: "O réu confessou o crime se e somente se a testemunha mentiu.", correta: false },
      { texto: "O réu mentiu ou a testemunha confessou o crime.", correta: false },
      { texto: "O réu não confessou o crime e a testemunha não mentiu.", correta: true },
    ],
  },
  // 21-23. AOCP (Múltipla Escolha)
  {
    idSlug: "rlm-inf-01-021",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A proposição condicional (P -> Q) assume valor lógico FALSO exclusivamente quando:",
    explicacao: "GABARITO: A. A condicional 'P -> Q' só é FALSA no caso 'V -> F' (antecedente verdadeiro e consequente falso - caso 'Vera Fischer'). Em todos os demais casos (V->V, F->V, F->F), é verdadeira.",
    alternativas: [
      { texto: "o antecedente (P) é verdadeiro e o consequente (Q) é falso.", correta: true },
      { texto: "o antecedente (P) é falso e o consequente (Q) é verdadeiro.", correta: false },
      { texto: "ambas as proposições P e Q são falsas.", correta: false },
      { texto: "ambas as proposições P e Q são verdadeiras.", correta: false },
      { texto: "P é falsa independentemente do valor de Q.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-022",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Ao lançar um dado cúbico comum de 6 faces não viciado, qual é a probabilidade de se obter uma face com número maior que 4?",
    explicacao: "GABARITO: B. Números maiores que 4 no dado de 6 faces: {5, 6} (2 casos favoráveis em 6 possíveis). Probabilidade = 2/6 = 1/3 ≈ 33,33%.",
    alternativas: [
      { texto: "1/6.", correta: false },
      { texto: "2/6 (ou 1/3).", correta: true },
      { texto: "3/6 (ou 1/2).", correta: false },
      { texto: "4/6 (ou 2/3).", correta: false },
      { texto: "5/6.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-023",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.equivalencias_negacoes_logicas,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A negação da proposição 'Nenhum hidrante está danificado' é:",
    explicacao: "GABARITO: C. A negação de 'Nenhum A é B' faz-se com o quantificador existencial afirmativo: 'Pelo menos um hidrante está danificado', 'Existe algum hidrante danificado' ou 'Algum hidrante está danificado'.",
    alternativas: [
      { texto: "Todos os hidrantes estão danificados.", correta: false },
      { texto: "Todos os hidrantes estão funcionando.", correta: false },
      { texto: "Pelo menos um hidrante está danificado.", correta: true },
      { texto: "Nenhum hidrante está funcionando.", correta: false },
      { texto: "Apenas um hidrante não está danificado.", correta: false },
    ],
  },
  // 24-25. IBFC (Múltipla Escolha)
  {
    idSlug: "rlm-inf-01-024",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.logica_proposicional_conectivos,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Na disjunção exclusiva ('ou P ou Q', símbolo ⊻), a proposição composta será VERDADEIRA se:",
    explicacao: "GABARITO: D. Na disjunção exclusiva (ou... ou), a proposição só é verdadeira quando EXATAMENTE UMA das proposições simples for verdadeira (valores lógicos diferentes: V ⊻ F = V; F ⊻ V = V; V ⊻ V = F; F ⊻ F = F).",
    alternativas: [
      { texto: "ambas as proposições forem verdadeiras ao mesmo tempo.", correta: false },
      { texto: "ambas as proposições forem falsas ao mesmo tempo.", correta: false },
      { texto: "o antecedente for falso e o consequente verdadeiro.", correta: false },
      { texto: "apenas uma das proposições for verdadeira e a outra falsa.", correta: true },
      { texto: "houver relação de causa e efeito temporal.", correta: false },
    ],
  },
  {
    idSlug: "rlm-inf-01-025",
    disciplina_id: TAXONOMIA.disciplinas.rlm,
    assunto_id: TAXONOMIA.assuntos.analise_combinatoria_probabilidade,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De quantas maneiras distintas podem ser escolhidos 2 policiais penais entre um grupo de 5 disponíveis para uma ronda noturna?",
    explicacao: "GABARITO: E. A ordem da escolha não importa (dupla de ronda), tratando-se de combinação simples: C(5,2) = (5 * 4) / (2 * 1) = 20 / 2 = 10 maneiras.",
    alternativas: [
      { texto: "25.", correta: false },
      { texto: "20.", correta: false },
      { texto: "15.", correta: false },
      { texto: "5.", correta: false },
      { texto: "10.", correta: true },
    ],
  },
];
