import { TAXONOMIA } from "./taxonomia.mjs";

export const adm03Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "adm-03-001",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A administração pública direta e indireta de qualquer dos Poderes da União, dos Estados, do Distrito Federal e dos Municípios obedecerá aos princípios de legalidade, impessoalidade, moralidade, publicidade e eficiência.",
    explicacao: "GABARITO: CERTO. Art. 37, caput, da CF/88: Princípios expressos que regem a Administração Pública em todos os níveis federativos (mnemônico LIMPE: Legalidade, Impessoalidade, Moralidade, Publicidade e Eficiência).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-002",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "São formas de provimento de cargo público previstas na Lei nº 8.112/1990: a nomeação, a promoção, a readaptação, a reversão, o aproveitamento, a reintegração e a recondução.",
    explicacao: "GABARITO: CERTO. Art. 8º da Lei nº 8.112/1990: São formas de provimento de cargo público: I - nomeação; II - promoção; V - readaptação; VI - reversão; VII - aproveitamento; VIII - reintegração; IX - recondução. (Ascensão e transferência foram declaradas inconstitucionais pelo STF - Súmula Vinculante 43).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-003",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos da Nova Lei de Licitações e Contratos Administrativos (Lei nº 14.133/2021), são modalidades de licitação: pregão, concorrência, concurso, leilão e diálogo competitivo.",
    explicacao: "GABARITO: CERTO. Art. 28 da Lei nº 14.133/2021: São modalidades de licitação: I - pregão; II - concorrência; III - concurso; IV - leilão; V - diálogo competitivo. (As modalidades tomada de preços e convite foram extintas).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-004",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Um policial penal estável foi demitido após processo administrativo disciplinar (PAD). Anos depois, comprovou-se em ação anulatória na Justiça que o ato demissional foi eivado de vício formal insanável, tendo a sentença judicial transitada em julgado determinado a anulação da penalidade. Nessa hipótese, o retorno do servidor ao cargo público anteriormente ocupado dá-se mediante o instituto da reintegração, com direito à indenização e ao ressarcimento integral de todos os vencimentos e vantagens retroativos ao período do afastamento ilegal.",
    explicacao: "GABARITO: CERTO. Nos termos do regime jurídico estatutário (art. 28 da Lei nº 8.112/1990 e legislação correlata dos entes federados), a reintegração é a reinvestidura do servidor público estável no cargo anteriormente ocupado quando invalidada a sua demissão por decisão judicial ou administrativa, assegurando-se o ressarcimento integral de todas as vantagens financeiras e funcionais devidas durante o afastamento.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-005",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A inexigibilidade de licitação (art. 74 da Lei nº 14.133/2021) ocorre nas hipóteses em que a competição é inviável, ao passo que a dispensa de licitação (art. 75) refere-se a hipóteses em que a licitação seria teoricamente viável, mas a lei autoriza ou impõe a contratação direta por conveniência e oportunidade socioeconômica.",
    explicacao: "GABARITO: CERTO. A inexigibilidade baseia-se na inviabilidade fática ou jurídica de competição (rol exemplificativo). A dispensa ocorre quando a competição é viável, mas a lei expressamente autoriza a não realização da disputa (rol taxativo).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-006",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O servidor público habilitado em concurso público adquire estabilidade no serviço público ao completar 2 (dois) anos de efetivo exercício, sendo desnecessária qualquer avaliação especial de desempenho.",
    explicacao: "GABARITO: ERRADO. Art. 41 da CF/88 (redação da EC 19/98): São estáveis após 3 (três) anos de efetivo exercício os servidores nomeados para cargo de provimento efetivo em virtude de concurso público. Como condição para a aquisição da estabilidade, é obrigatória a avaliação especial de desempenho por comissão instituída para essa finalidade.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "adm-03-007",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A proibição de que constem nomes, símbolos ou imagens que caracterizem promoção pessoal de autoridades ou servidores públicos em publicidade institucional dos órgãos públicos decorre expressamente do princípio da impessoalidade.",
    explicacao: "GABARITO: CERTO. Art. 37, § 1º, da CF/88: 'A publicidade dos atos, programas, obras, serviços e campanhas dos órgãos públicos deverá ter caráter educativo, informativo ou de orientação social, dela não podendo constar nomes, símbolos ou imagens que caracterizem promoção pessoal de autoridades ou servidores públicos'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "adm-03-008",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na Lei nº 14.133/2021, o diálogo competitivo é modalidade de licitação restrita a contratações que envolvam inovação tecnológica ou técnica, impossibilidade de o órgão ter sua necessidade satisfeita sem adaptação de soluções disponíveis, ou quando as especificações técnicas não possam ser definidas com precisão suficiente pela administração.",
    explicacao: "GABARITO: CERTO. Art. 32 da Lei nº 14.133/2021: O diálogo competitivo é restrito a contratações em que a Administração visa desenvolver alternativas ou soluções técnicas inovadoras que não se encontrem padronizadas no mercado.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "adm-03-009",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.112/1990, o retorno à atividade de servidor público aposentado por invalidez, quando junta médica oficial declarar insubsistentes os motivos da aposentadoria, denomina-se:",
    explicacao: "GABARITO: A. Art. 25, I, da Lei nº 8.112/1990: Reversão é o retorno à atividade de servidor aposentado: I - por invalidez, quando junta médica oficial declarar insubsistentes os motivos da aposentadoria.",
    alternativas: [
      { texto: "Reversão.", correta: true },
      { texto: "Reintegração.", correta: false },
      { texto: "Recondução.", correta: false },
      { texto: "Readaptação.", correta: false },
      { texto: "Aproveitamento.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-010",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 14.133/2021, o critério de julgamento das propostas na modalidade PREGÃO será, obrigatoriamente:",
    explicacao: "GABARITO: B. Art. 34, § 1º, da Lei nº 14.133/2021: O julgamento por menor preço ou maior desconto e o julgamento por melhor técnica e preço ou melhor conteúdo artístico observarão parâmetros objetivos... No caso do pregão (art. 6º, XLI), o critério de julgamento poderá ser de menor preço ou de maior desconto.",
    alternativas: [
      { texto: "melhor técnica ou conteúdo artístico.", correta: false },
      { texto: "menor preço ou maior desconto.", correta: true },
      { texto: "maior lance sem valor de reserva.", correta: false },
      { texto: "maior retorno econômico exclusivo.", correta: false },
      { texto: "melhor índice de sustentabilidade socioambiental.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-011",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A investidura em cargo público ocorre com o ato formal da:",
    explicacao: "GABARITO: C. Art. 7º da Lei nº 8.112/1990: 'A investidura em cargo público ocorrerá com a posse'. A nomeação é forma de provimento; o exercício é o efetivo desempenho das atribuições; mas a investidura aperfeiçoa-se com a POSSE.",
    alternativas: [
      { texto: "homologação do resultado do concurso.", correta: false },
      { texto: "publicação da nomeação no Diário Oficial.", correta: false },
      { texto: "posse.", correta: true },
      { texto: "entrada em efetivo exercício.", correta: false },
      { texto: "conclusão do estágio probatório.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-012",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Súmula Vinculante nº 13 do Supremo Tribunal Federal, que veda a nomeação de cônjuge, companheiro ou parente em linha reta, colateral ou por afinidade, até o terceiro grau, para o exercício de cargo em comissão ou de confiança, concretiza diretamente os princípios constitucionais da:",
    explicacao: "GABARITO: D. STF, Súmula Vinculante 13: A proibição do nepotismo decorre diretamente dos princípios da impessoalidade, moralidade, igualdade e eficiência previstos no art. 37, caput, da CF/88.",
    alternativas: [
      { texto: "soberania nacional e continuidade do serviço público.", correta: false },
      { texto: "autotutela e presunção de veracidade.", correta: false },
      { texto: "motivação obrigatória e publicidade irrestrita.", correta: false },
      { texto: "impessoalidade, moralidade, eficiência e isonomia.", correta: true },
      { texto: "hierarquia estrita e reserva legal.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-013",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.112/1990, a investidura do servidor em cargo de atribuições e responsabilidades compatíveis com a limitação que tenha sofrido em sua capacidade física ou mental, verificada em inspeção médica oficial, denomina-se:",
    explicacao: "GABARITO: E. Art. 24 da Lei nº 8.112/1990: Readaptação é a investidura do servidor em cargo de atribuições e responsabilidades compatíveis com a limitação que tenha sofrido em sua capacidade física ou mental verificada em inspeção médica.",
    alternativas: [
      { texto: "Recondução funcional.", correta: false },
      { texto: "Remoção compulsória.", correta: false },
      { texto: "Redistribuição por interesse público.", correta: false },
      { texto: "Disponibilidade remunerada.", correta: false },
      { texto: "Readaptação.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "adm-03-014",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da legislação estatutária e constitucional, o prazo de validade do concurso público será de até:",
    explicacao: "GABARITO: A. Art. 37, III, da CF/88 e art. 12 da Lei nº 8.112/90: 'O prazo de validade do concurso público será de até 2 (dois) anos, prorrogável uma vez, por igual período'.",
    alternativas: [
      { texto: "2 anos, prorrogável uma vez, por igual período.", correta: true },
      { texto: "4 anos, improrrogáveis.", correta: false },
      { texto: "1 ano, prorrogável indefinidamente a critério da administração.", correta: false },
      { texto: "5 anos, coincidente com o plano plurianual.", correta: false },
      { texto: "6 meses, com prorrogação máxima de 3 meses.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-015",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A modalidade de licitação obrigatória para a alienação de bens imóveis ou de bens móveis inservíveis ou legalmente apreendidos, na Lei nº 14.133/2021, é o:",
    explicacao: "GABARITO: B. Art. 28, IV, e art. 31 da Lei nº 14.133/2021: O leilão é a modalidade de licitação para alienação de bens imóveis ou de bens móveis inservíveis ou legalmente apreendidos a quem oferecer o maior lance.",
    alternativas: [
      { texto: "Pregão presencial.", correta: false },
      { texto: "Leilão.", correta: true },
      { texto: "Concurso artístico.", correta: false },
      { texto: "Diálogo competitivo.", correta: false },
      { texto: "Tomada de preços.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-016",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O retorno do servidor estável ao cargo anteriormente ocupado em decorrência de inabilitação em estágio probatório relativo a outro cargo público denomina-se:",
    explicacao: "GABARITO: C. Art. 29, I, da Lei nº 8.112/1990: Recondução é o retorno do servidor estável ao cargo anteriormente ocupado e decorre de: I - inabilitação em estágio probatório relativo a outro cargo; II - reintegração do anterior ocupante.",
    alternativas: [
      { texto: "Promoção.", correta: false },
      { texto: "Reversão compulsória.", correta: false },
      { texto: "Recondução.", correta: true },
      { texto: "Transferência horizontal.", correta: false },
      { texto: "Exoneração a pedido.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "adm-03-017",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.112/1990, são penalidades disciplinares aplicáveis aos servidores públicos federais, EXCETO:",
    explicacao: "GABARITO: D. Art. 127 da Lei nº 8.112/1990: São penalidades disciplinares: I - advertência; II - suspensão; III - demissão; IV - cassação de aposentadoria ou disponibilidade; V - destituição de cargo em comissão; VI - destituição de função comissionada. A prisão disciplinar NÃO existe na Lei 8.112/90.",
    alternativas: [
      { texto: "Advertência.", correta: false },
      { texto: "Suspensão.", correta: false },
      { texto: "Demissão.", correta: false },
      { texto: "Prisão administrativa disciplinar de até 30 dias.", correta: true },
      { texto: "Cassação de aposentadoria ou disponibilidade.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-018",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.principios_administracao_publica,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O princípio da administração pública que estabelece que o administrador público só pode fazer o que a lei expressamente autoriza ou determina denomina-se:",
    explicacao: "GABARITO: A. Princípio da Legalidade estrita na Administração Pública (art. 37, caput, da CF/88): enquanto o particular pode fazer tudo o que a lei não proíbe (art. 5º, II), a Administração só pode agir quando autorizada pela lei.",
    alternativas: [
      { texto: "Princípio da Legalidade.", correta: true },
      { texto: "Princípio da Supremacia Privada.", correta: false },
      { texto: "Princípio da Publicidade Relativa.", correta: false },
      { texto: "Princípio da Ampla Liberdade Contratual.", correta: false },
      { texto: "Princípio da Informalidade Processual.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "adm-03-019",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.licitacoes_contratos_14133,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O Portal Nacional de Contratações Públicas (PNCP), instituído pela Lei nº 14.133/2021, é um sítio eletrônico oficial que tem por finalidade:",
    explicacao: "GABARITO: B. Art. 174 da Lei nº 14.133/2021: O Portal Nacional de Contratações Públicas (PNCP) é o sítio eletrônico oficial destinado à divulgação centralizada e obrigatória dos atos de licitações, editais, contratos e termos aditivos da administração pública.",
    alternativas: [
      { texto: "cobrar taxas de inscrição de fornecedores cadastrados.", correta: false },
      { texto: "divulgar de forma centralizada e obrigatória os atos exigidos pela Nova Lei de Licitações e Contratos.", correta: true },
      { texto: "substituir integralmente a atuação dos Tribunais de Contas.", correta: false },
      { texto: "realizar julgamentos criminais de prefeitos e secretários.", correta: false },
      { texto: "conceder empréstimos bancários a licitantes vencedores.", correta: false },
    ],
  },
  {
    idSlug: "adm-03-020",
    disciplina_id: TAXONOMIA.disciplinas.administrativo,
    assunto_id: TAXONOMIA.assuntos.agentes_publicos_estatuto,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal (art. 37, XVI), é VEDADA a acumulação remunerada de cargos públicos, EXCETO, quando houver compatibilidade de horários:",
    explicacao: "GABARITO: C. Art. 37, XVI, da CF/88: É vedada a acumulação remunerada de cargos públicos, exceto, quando houver compatibilidade de horários: a) a de dois cargos de professor; b) a de um cargo de professor com outro técnico ou científico; c) a de dois cargos ou empregos privativos de profissionais de saúde, com profissões regulamentadas.",
    alternativas: [
      { texto: "a de três cargos de confiança na mesma secretaria.", correta: false },
      { texto: "a de policial penal com guarda municipal de cidades vizinhas.", correta: false },
      { texto: "a de dois cargos de professor; a de um cargo de professor com outro técnico ou científico; e a de dois cargos de profissionais de saúde.", correta: true },
      { texto: "a de militar da ativa com qualquer cargo executivo eletivo.", correta: false },
      { texto: "qualquer combinação desde que a soma das remunerações não ultrapasse o teto constitucional.", correta: false },
    ],
  },
];
