import { TAXONOMIA } from "./taxonomia.mjs";

export const const01Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "cst-01-001",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Policiais militares em patrulhamento preventivo escutam gritos de socorro e sons de agressão física contínua vindos do interior de uma residência particular durante a madrugada. Nessa hipótese, os policiais podem adentrar o imóvel imediatamente e sem mandado judicial, haja vista que a garantia constitucional da inviolabilidade domiciliar comporta exceção expressa para prestar socorro ou em caso de flagrante delito, independentemente do horário.",
    explicacao: "GABARITO: CERTO. Nos termos do art. 5º, XI, da CF/88 e da jurisprudência pacífica, a inviolabilidade domiciliar não protege situações de desastre, necessidade de socorro ou flagrante delito, situações nas quais o ingresso forçado é legítimo a qualquer hora do dia ou da noite, mesmo sem consentimento do morador ou ordem judicial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-01-002",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme tese de repercussão geral fixada pelo STF (Tema 280), a entrada forçada em domicílio sem mandado judicial é lícita, mesmo em período noturno, quando amparada em fundadas razões, devidamente justificadas a posteriori, que indiquem que dentro da casa ocorre situação de flagrante delito.",
    explicacao: "GABARITO: CERTO. STF, Tema 280 (RE 603.616/RO): 'A entrada forçada em domicílio sem mandado judicial só é lícita, mesmo em período noturno, quando amparada em fundadas razões, devidamente justificadas a posteriori, que indiquem que dentro da casa ocorre situação de flagrante delito sob pena de responsabilidade disciplinar, civil e penal do agente ou da autoridade e de nulidade dos atos praticados'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-01-003",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A prática do racismo constitui crime inafiançável e imprescritível, sujeito à pena de reclusão, nos termos da lei.",
    explicacao: "GABARITO: CERTO. Art. 5º, XLII, da CF/88: 'a prática do racismo constitui crime inafiançável e imprescritível, sujeito à pena de reclusão, nos termos da lei'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-01-004",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No âmbito da execução penal, caso um sentenciado cometa falta disciplinar de natureza grave dentro do estabelecimento prisional, o diretor da unidade prisional detém competência para determinar regressão cautelar de regime e aplicar sanções disciplinares administrativas, mas não possui autoridade para expedir mandado prisional autônomo, visto que a privação de liberdade no ordenamento brasileiro subordina-se à reserva de jurisdição, salvo o flagrante delito e as hipóteses constitucionais militares.",
    explicacao: "GABARITO: CERTO. O art. 5º, LXI, da CF/88 consagra o princípio da reserva de jurisdição para a decretação da prisão (ordem escrita e fundamentada de autoridade judiciária competente), com exceção unicamente do flagrante delito e das transgressões/crimes propriamente militares definidos em lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-01-005",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O mandado de segurança coletivo pode ser impetrado por partido político sem representação no Congresso Nacional, desde que legalmente registrado no Tribunal Superior Eleitoral.",
    explicacao: "GABARITO: ERRADO. Art. 5º, LXX, 'a', da CF/88: O mandado de segurança coletivo pode ser impetrado por partido político COM representação no Congresso Nacional (ou seja, que possua ao menos um deputado federal ou senador).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "cst-01-006",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme jurisprudência pacífica do STF, a cláusula de reserva de jurisdição impede que Comissões Parlamentares de Inquérito (CPIs) determinem a quebra de sigilo fiscal e bancário de investigados, ato privativo de magistrado togado.",
    explicacao: "GABARITO: ERRADO. As CPIs possuem poderes de investigação próprios das autoridades judiciais (art. 58, § 3º, da CF) e PODEM determinar a quebra de sigilo bancário, fiscal e telefônico (dados). Não podem, contudo, determinar interceptação telefônica (escuta), busca e apreensão domiciliar ou expedir mandados de prisão preventiva/temporária, que permanecem sob reserva absoluta de jurisdição.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "cst-01-007",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder.",
    explicacao: "GABARITO: CERTO. Art. 5º, LXVIII, da CF/88: 'conceder-se-á habeas corpus sempre que alguém sofrer ou se achar ameaçado de sofrer violência ou coação em sua liberdade de locomoção, por ilegalidade ou abuso de poder'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-01-008",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_sociais_nacionalidade,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "São brasileiros natos os nascidos no estrangeiro de pai brasileiro ou de mãe brasileira, desde que venham a residir na República Federativa do Brasil e optem, em qualquer tempo, depois de atingida a maioridade, pela nacionalidade brasileira.",
    explicacao: "GABARITO: CERTO. Art. 12, I, 'c', da CF/88: São brasileiros natos os nascidos no estrangeiro de pai brasileiro ou de mãe brasileira, desde que sejam registrados em repartição brasileira competente ou venham a residir na República Federativa do Brasil e optem, em qualquer tempo, depois de atingida a maioridade, pela nacionalidade brasileira.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "cst-01-009",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 5º da Constituição Federal de 1988, a extradição de brasileiro:",
    explicacao: "GABARITO: B. Art. 5º, LI, da CF/88: 'nenhum brasileiro será extraditado, salvo o naturalizado, em caso de crime comum, praticado antes da naturalização, ou de comprovado envolvimento em tráfico ilícito de entorpecentes e drogas afins, na forma da lei'. O brasileiro nato NUNCA pode ser extraditado pelo Brasil.",
    alternativas: [
      { texto: "é permitida para o nato se o crime for hediondo ou terrorismo.", correta: false },
      { texto: "não é admitida para o brasileiro nato, admitindo-se para o naturalizado em caso de crime comum praticado antes da naturalização ou de comprovado envolvimento em tráfico ilícito de entorpecentes a qualquer tempo.", correta: true },
      { texto: "é plenamente permitida para o nato mediante reciprocidade diplomática.", correta: false },
      { texto: "é vedada para qualquer brasileiro, seja ele nato ou naturalizado, de forma absoluta.", correta: false },
      { texto: "depende exclusivamente de decisão discricionária do Ministro da Justiça.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-010",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito do direito de reunião pacífica (art. 5º, XVI, da CF/88), o Plenário do Supremo Tribunal Federal fixou a tese de que:",
    explicacao: "GABARITO: C. STF, Tema 855 (RE 806.339/SE): 'A exigência constitucional de aviso prévio relativamente ao direito de reunião é satisfeita com a veiculação de informação que permita ao poder público zelar pela fluidez do trânsito e garantir a segurança dos manifestantes e da coletividade, não se exigindo notificação formal'.",
    alternativas: [
      { texto: "o direito de reunião depende de autorização prévia emitida pelo comando da Polícia Militar local.", correta: false },
      { texto: "é indispensável requerimento formal protocolado com antecedência mínima de 15 dias na Prefeitura.", correta: false },
      { texto: "a exigência de aviso prévio é satisfeita pela veiculação de informação pública que permita ao poder público zelar pela segurança e fluidez do trânsito, inexistindo a necessidade de notificação formal aos órgãos estatais.", correta: true },
      { texto: "as reuniões em locais públicos com fins políticos são proibidas após as 18 horas.", correta: false },
      { texto: "a autoridade policial pode dissolver qualquer reunião que não tenha recolhido taxa de ocupação de solo.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-011",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal, o remédio constitucional adequado para assegurar o conhecimento de informações relativas à pessoa do impetrante, constantes de registros ou bancos de dados de entidades governamentais ou de caráter público, é o:",
    explicacao: "GABARITO: D. Art. 5º, LXXII, 'a', da CF/88: Conceder-se-á habeas data para assegurar o conhecimento de informações relativas à pessoa do impetrante, constantes de registros ou bancos de dados de entidades governamentais ou de caráter público.",
    alternativas: [
      { texto: "Habeas Corpus.", correta: false },
      { texto: "Mandado de Segurança.", correta: false },
      { texto: "Mandado de Injunção.", correta: false },
      { texto: "Habeas Data.", correta: true },
      { texto: "Ação Popular.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-012",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Sobre a vedação constitucional de penas no Brasil (art. 5º, XLVII, da CF/88), é CORRETO afirmar que não haverá penas de:",
    explicacao: "GABARITO: A. Art. 5º, XLVII, da CF/88: 'não haverá penas: a) de morte, salvo em caso de guerra declarada, nos termos do art. 84, XIX; b) de caráter perpétuo; c) de trabalhos forçados; d) de banimento; e) cruéis'.",
    alternativas: [
      { texto: "morte (salvo em caso de guerra declarada), de caráter perpétuo, de trabalhos forçados, de banimento e cruéis.", correta: true },
      { texto: "multa e prestação pecuniária.", correta: false },
      { texto: "perda de bens e valores em favor da União.", correta: false },
      { texto: "privação ou restrição da liberdade.", correta: false },
      { texto: "suspensão ou interdição de direitos.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-013",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_sociais_nacionalidade,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o art. 12, § 3º, da Constituição Federal, são cargos privativos de brasileiro nato, EXCETO:",
    explicacao: "GABARITO: E. Art. 12, § 3º, da CF/88: São privativos de brasileiro nato os cargos: I - de Presidente e Vice-Presidente da República; II - de Presidente da Câmara dos Deputados; III - de Presidente do Senado Federal; IV - de Ministro do Supremo Tribunal Federal; V - da carreira diplomática; VI - de oficial das Forças Armadas; VII - de Ministro de Estado da Defesa. O cargo de Ministro da Justiça pode ser ocupado por brasileiro naturalizado.",
    alternativas: [
      { texto: "Presidente da Câmara dos Deputados.", correta: false },
      { texto: "Ministro do Supremo Tribunal Federal.", correta: false },
      { texto: "Oficial das Forças Armadas.", correta: false },
      { texto: "Ministro de Estado da Defesa.", correta: false },
      { texto: "Ministro de Estado da Justiça e Segurança Pública.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "cst-01-014",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal, a lei penal:",
    explicacao: "GABARITO: B. Art. 5º, XL, da CF/88: 'a lei penal não retroagirá, salvo para beneficiar o réu'. Princípio da irretroatividade da lei penal mais gravosa e retroatividade da lex mitior.",
    alternativas: [
      { texto: "sempre retroagirá para alcançar fatos anteriores.", correta: false },
      { texto: "não retroagirá, salvo para beneficiar o réu.", correta: true },
      { texto: "retroagirá apenas para crimes hediondos.", correta: false },
      { texto: "nunca retroagirá em nenhuma hipótese.", correta: false },
      { texto: "retroagirá somente se a vítima expressamente autorizar.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-015",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Qualquer cidadão é parte legítima para propor ação popular que vise a anular ato lesivo ao patrimônio público ou de entidade de que o Estado participe, à moralidade administrativa, ao meio ambiente e ao patrimônio histórico e cultural. Salvo comprovada má-fé, o autor:",
    explicacao: "GABARITO: C. Art. 5º, LXXIII, da CF/88: Qualquer cidadão é parte legítima para propor ação popular... ficando o autor, salvo comprovada má-fé, isento de custas judiciais e do ônus da sucumbência.",
    alternativas: [
      { texto: "deverá depositar 10% do valor da causa antecipadamente.", correta: false },
      { texto: "arcará com os honorários em caso de improcedência mesmo de boa-fé.", correta: false },
      { texto: "ficará isento de custas judiciais e do ônus da sucumbência.", correta: true },
      { texto: "deverá obter prévia anuência do Ministério Público.", correta: false },
      { texto: "será punido criminalmente se o pedido for julgado extinto sem resolução de mérito.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-016",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A criação de associações e, na forma da lei, a de cooperativas independem de autorização, sendo vedada a interferência estatal em seu funcionamento. As associações só poderão ser compulsoriamente dissolvidas ou ter suas atividades suspensas por decisão judicial, exigindo-se, no primeiro caso (dissolução compulsória):",
    explicacao: "GABARITO: D. Art. 5º, XIX, da CF/88: 'as associações só poderão ser compulsoriamente dissolvidas ou ter suas atividades suspensas por decisão judicial, exigindo-se, no primeiro caso, o trânsito em julgado'.",
    alternativas: [
      { texto: "parecer unânime da comissão de direitos humanos.", correta: false },
      { texto: "decisão cautelar monocrática de tribunal de contas.", correta: false },
      { texto: "autorização do Ministério da Justiça.", correta: false },
      { texto: "o trânsito em julgado da decisão judicial.", correta: true },
      { texto: "quórum de dois terços dos associados presentes em assembleia.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "cst-01-017",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O mandado de injunção será concedido sempre que a falta de norma regulamentadora torne inviável o exercício dos direitos e liberdades constitucionais e das prerrogativas inerentes à:",
    explicacao: "GABARITO: A. Art. 5º, LXXI, da CF/88: 'conceder-se-á mandado de injunção sempre que a falta de norma regulamentadora torne inviável o exercício dos direitos e liberdades constitucionais e das prerrogativas inerentes à nacionalidade, à soberania e à cidadania'.",
    alternativas: [
      { texto: "nacionalidade, à soberania e à cidadania.", correta: true },
      { texto: "propriedade privada e liberdade de locomoção corporal.", correta: false },
      { texto: "atividade policial ostensiva e previdência militar.", correta: false },
      { texto: "isenção tributária de templos religiosos.", correta: false },
      { texto: "concessão de asilo político a estrangeiros.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-018",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Segundo a Constituição Federal de 1988, a lei considerará crimes inafiançáveis e insuscetíveis de graça ou anistia a prática da tortura, o tráfico ilícito de entorpecentes e drogas afins, o terrorismo e os definidos como:",
    explicacao: "GABARITO: B. Art. 5º, XLIII, da CF/88: 'a lei considerará crimes inafiançáveis e insuscetíveis de graça ou anistia a prática da tortura, o tráfico ilícito de entorpecentes e drogas afins, o terrorismo e os definidos como crimes hediondos, por eles respondendo os mandantes, os executores e os que, podendo evitá-los, se omitirem'.",
    alternativas: [
      { texto: "crimes de menor potencial ofensivo.", correta: false },
      { texto: "crimes hediondos.", correta: true },
      { texto: "crimes culposos de trânsito.", correta: false },
      { texto: "crimes contra a honra de servidor.", correta: false },
      { texto: "crimes puramente patrimoniais.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "cst-01-019",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Constitui crime inafiançável e imprescritível a ação de grupos armados, civis ou militares, contra a ordem constitucional e o Estado Democrático, nos termos expressos do art. 5º, XLIV, da CF/88. Assim, no ordenamento constitucional brasileiro, são crimes IMPRESCRITÍVEIS:",
    explicacao: "GABARITO: C. Na CF/88, são imprescritíveis apenas dois grupos de condutas: a prática do RACISMO (art. 5º, XLII - incluindo injúria racial pelo STF) e a AÇÃO DE GRUPOS ARMADOS, civis ou militares, contra a ordem constitucional e o Estado Democrático (art. 5º, XLIV).",
    alternativas: [
      { texto: "a tortura e o tráfico de drogas.", correta: false },
      { texto: "o homicídio qualificado e o latrocínio.", correta: false },
      { texto: "o racismo e a ação de grupos armados contra a ordem constitucional e o Estado Democrático.", correta: true },
      { texto: "a corrupção passiva e o peculato.", correta: false },
      { texto: "o estupro de vulnerável e o terrorismo.", correta: false },
    ],
  },
  {
    idSlug: "cst-01-020",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.direitos_fundamentais_art5,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 5º, LVII, da Constituição Federal de 1988, 'ninguém será considerado culpado até...':",
    explicacao: "GABARITO: D. Art. 5º, LVII, da CF/88: 'ninguém será considerado culpado até o trânsito em julgado de sentença penal condenatória'. Trata-se do princípio do estado ou presunção de inocência / não culpabilidade.",
    alternativas: [
      { texto: "o indiciamento formal pela autoridade policial competente.", correta: false },
      { texto: "o oferecimento da denúncia pelo Ministério Público.", correta: false },
      { texto: "a prolação da sentença condenatória de primeiro grau.", correta: false },
      { texto: "o trânsito em julgado de sentença penal condenatória.", correta: true },
      { texto: "o julgamento do recurso em segundo grau de jurisdição.", correta: false },
    ],
  },
];
