import { TAXONOMIA } from "./taxonomia.mjs";

export const legEsp03Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "leg-esp-03-001",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Nos termos da Lei nº 13.869/2019 (Lei de Abuso de Autoridade), os crimes nela definidos são todos de ação penal pública incondicionada, admitindo-se, contudo, a ação penal privada subsidiária da pública se a denúncia não for oferecida no prazo legal.",
    explicacao: "GABARITO: CERTO. Art. 3º da Lei nº 13.869/2019: Os crimes previstos nesta Lei são de ação penal pública incondicionada. § 1º Será admitida ação privada subsidiária da pública se a ação penal não for intentada no prazo legal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-002",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A divergência na interpretação de lei ou na avaliação de fatos e provas não configura abuso de autoridade (crime de hermenêutica).",
    explicacao: "GABARITO: CERTO. Art. 1º, § 2º, da Lei nº 13.869/2019: A divergência na interpretação de lei ou na avaliação de fatos e provas não configura, por si só, abuso de autoridade. O tipo exige dolo específico de prejudicar outrem ou beneficiar a si mesmo ou a terceiro, ou ainda por mero capricho ou satisfação pessoal (§ 1º).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-003",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para a configuração de organização criminosa nos moldes do art. 1º, § 1º, da Lei nº 12.850/2013, exige-se a associação de 4 ou mais pessoas estruturalmente ordenada e caracterizada pela divisão de tarefas, com o objetivo de obter vantagem de qualquer natureza mediante a prática de infrações penais cujas penas máximas sejam superiores a 4 anos ou que sejam de caráter transnacional.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 1º, da Lei nº 12.850/2013: Considera-se organização criminosa a associação de 4 (quatro) ou mais pessoas estruturalmente ordenada e caracterizada pela divisão de tarefas, ainda que informalmente, com objetivo de obter vantagem de qualquer natureza mediante a prática de infrações penais cujas penas máximas sejam superiores a 4 anos ou que sejam de caráter transnacional.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-004",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O delegado de polícia e o membro do Ministério Público têm legitimidade para firmar acordo de colaboração premiada com o investigado, cabendo ao juiz homologar o termo, sendo vedado ao magistrado participar das negociações preliminares entre as partes.",
    explicacao: "GABARITO: CERTO. Art. 4º, § 6º, da Lei nº 12.850/2013 e ADI 5508/STF: O juiz não participará das negociações realizadas entre as partes para a formalização do acordo de colaboração, que ocorrerá entre o delegado de polícia, o investigado e o defensor (com manifestação do MP), ou diretamente entre o MP e o investigado/defensor.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-005",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O porte ilegal de arma de fogo de uso permitido (art. 14 do Estatuto do Desarmamento) é crime de mera conduta e de perigo abstrato, consumando-se mesmo que a arma esteja desmuniciada ou desmontada, desde que o agente traga consigo munição correspondente de pronto acesso.",
    explicacao: "GABARITO: CERTO. Conforme jurisprudência pacífica do STF e do STJ, o porte de arma de fogo desmuniciada configura crime de perigo abstrato (art. 14 da Lei nº 10.826/2003), mormente quando acompanhada de munição ou em condições de pronto municiamento, tutelando-se a segurança e a incolumidade pública coletivas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-006",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.crimes_hediondos_8072,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de roubo circunstanciado pelo emprego de arma de fogo de uso permitido ou restrito e o roubo qualificado pelo resultado lesão corporal grave ou morte (latrocínio) integram o rol legal taxativo dos crimes hediondos da Lei nº 8.072/1990.",
    explicacao: "GABARITO: CERTO. Art. 1º, II, da Lei nº 8.072/1990 (redação dada pela Lei nº 13.964/2019): São hediondos o roubo circunstanciado pela restrição de liberdade da vítima, pelo emprego de arma de fogo ou pelo emprego de arma de fogo de uso proibido ou restrito, bem como o roubo qualificado pelo resultado lesão corporal grave ou morte (latrocínio).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-007",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Ao agente que adquire, guarda, traz consigo ou transporta drogas para consumo pessoal (art. 28 da Lei nº 11.343/2006) não se imporá prisão em flagrante, devendo ser conduzido imediatamente ao juízo competente ou, na falta deste, assumir o compromisso de a ele comparecer para lavratura de termo circunstanciado.",
    explicacao: "GABARITO: CERTO. Art. 48, § 2º, da Lei nº 11.343/2006: Tratando-se das condutas do art. 28, não se imporá prisão em flagrante, devendo o autor do fato ser imediatamente encaminhado ao juízo competente ou, na falta deste, assumir o compromisso de a ele comparecer, lavrando-se termo circunstanciado.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-008",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O reconhecimento do tráfico privilegiado (art. 33, § 4º, da Lei nº 11.343/2006) não afasta a natureza hedionda do delito, aplicando-se integralmente as vedações de liberdade provisória e os prazos especiais de prescrição dos crimes hediondos.",
    explicacao: "GABARITO: ERRADO. Conforme expressamente disposto no art. 112, § 5º, da LEP (incluído pelo Pacote Anticrime) e Súmula Vinculante 59/STF, o crime de tráfico privilegiado (art. 33, § 4º, da Lei 11.343/06) NÃO é considerado hediondo ou equiparado a hediondo.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "leg-esp-03-009",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Policial militar efetua busca pessoal em cidadão na via pública e, por mero capricho e menosprezo, filma a abordagem e divulga o vídeo do rosto da pessoa constrangida em rede social privada. Nos termos da Lei nº 13.869/2019, tal conduta:",
    explicacao: "GABARITO: A. Art. 28 da Lei nº 13.869/2019: Divulgar gravação ou trecho de gravação sem relação com a prova dos fatos, expondo a intimidade ou a vida privada ou ferindo a honra do investigado ou conduzido: Pena - detenção, de 1 a 4 anos, e multa.",
    alternativas: [
      { texto: "configura crime de abuso de autoridade (art. 28 da Lei nº 13.869/2019).", correta: true },
      { texto: "constitui mero ilícito ético-disciplinar sem relevância criminal.", correta: false },
      { texto: "é acobertada pelo direito constitucional à ampla publicidade dos atos administrativos.", correta: false },
      { texto: "só configuraria crime se a vítima fosse autoridade judiciária.", correta: false },
      { texto: "constitui infração sujeita apenas à retratação pública no batalhão.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-010",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No curso de investigação de organização criminosa, a infiltração de agentes de polícia na internet (art. 10-A da Lei nº 12.850/2013) exige:",
    explicacao: "GABARITO: C. Art. 10-A da Lei nº 12.850/2013 (incluído pela Lei nº 13.964/2019): A infiltração de agentes na internet será autorizada pelo juiz, precedida de manifestação do Ministério Público, pelo prazo de até 6 meses, prorrogável se comprovada sua necessidade, até o limite de 720 dias.",
    alternativas: [
      { texto: "apenas despacho discricionário do delegado de polícia dispensada manifestação judicial.", correta: false },
      { texto: "autorização do provedor de internet sem necessidade de decisão judicial.", correta: false },
      { texto: "autorização judicial prévia fundamentada, ouvido o Ministério Público, pelo prazo de até 6 meses, prorrogável.", correta: true },
      { texto: "exclusivo requerimento da vítima da infração cibernética.", correta: false },
      { texto: "autorização da Agência Nacional de Telecomunicações (ANATEL).", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-011",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Supremo Tribunal Federal, ao julgar as ADIs 5.948 e 5.538, fixou entendimento vinculante sobre o porte de arma de fogo pelos integrantes das Guardas Municipais de todo o país, decidindo que:",
    explicacao: "GABARITO: B. O STF declarou inconstitucionais as restrições de porte de arma para guardas municipais com base em critérios populacionais do município (antigo art. 6º, III e IV, da Lei 10.826/03), assegurando o porte de arma de fogo a todos os integrantes das guardas municipais em serviço e fora dele, em todo o território nacional.",
    alternativas: [
      { texto: "as guardas municipais não podem utilizar armas de fogo em nenhuma hipótese.", correta: false },
      { texto: "é inconstitucional a restrição do porte de arma aos guardas municipais com base no número de habitantes do município, sendo admitido o porte em serviço e fora dele.", correta: true },
      { texto: "o porte só é permitido para municípios com população superior a 500 mil habitantes.", correta: false },
      { texto: "o porte é restrito aos comandantes das guardas municipais das capitais.", correta: false },
      { texto: "a guarda municipal só pode utilizar armamento de calibre de uso restrito do Exército.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-012",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.crimes_hediondos_8072,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 8.072/1990 e do art. 112 da Lei de Execução Penal (com a redação dada pelo Pacote Anticrime - Lei nº 13.964/2019), o condenado primário por crime hediondo ou equiparado com resultado morte terá direito à progressão de regime após o cumprimento de:",
    explicacao: "GABARITO: D. Art. 112, VI, 'a', da Lei nº 7.210/1984 (LEP): A progressão de regime dar-se-á com 50% da pena se o apenado for condenado pela prática de crime hediondo ou equiparado, se for primário (sem resultado morte); e com 50% (sem resultado morte). Mas havendo resultado MORTE (art. 112, VI, 'a' e art. 112, VIII), a fração para primário com resultado morte é de 50% e é vedado o livramento condicional (art. 112, VI, 'a' - 50% se for condenado pela prática de crime hediondo ou equiparado com resultado morte, se for primário, vedado o livramento condicional).",
    alternativas: [
      { texto: "16% da pena privativa de liberdade.", correta: false },
      { texto: "25% da pena privativa de liberdade.", correta: false },
      { texto: "40% da pena privativa de liberdade.", correta: false },
      { texto: "50% da pena privativa de liberdade, vedado o livramento condicional.", correta: true },
      { texto: "80% da pena privativa de liberdade.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-013",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito da destruição de drogas apreendidas na vigência da Lei nº 11.343/2006 (art. 50, § 3º e art. 50-A), assinale a afirmativa correta.",
    explicacao: "GABARITO: E. Art. 50, § 3º, e art. 50-A da Lei nº 11.343/2006: As drogas apreendidas em flagrante delito serão destruídas por incineração, no prazo de 15 dias na presença do MP e autoridade sanitária, guardando-se amostra para o laudo definitivo. Em caso de plantação ilícita (art. 50-A) ou apreensão sem flagrante (art. 50-A, § 1º), a destruição ocorre em até 30 dias.",
    alternativas: [
      { texto: "A destruição de drogas depende obrigatoriamente do trânsito em julgado da sentença condenatória.", correta: false },
      { texto: "As drogas apreendidas devem ser leiloadas pela autoridade policial para financiar o fundo de segurança.", correta: false },
      { texto: "A incineração não exige a guarda de amostra para contraperícia.", correta: false },
      { texto: "Apenas o juiz federal pode presenciar o ato de incineração.", correta: false },
      { texto: "As drogas apreendidas em flagrante serão incineradas no prazo de 15 dias, na presença do MP e autoridade sanitária, preservando-se amostra necessária à confecção do laudo definitivo.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "leg-esp-03-014",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com o art. 22 da Lei nº 13.869/2019, invadir ou adentrar, clandestina ou astuciosamente, ou à revelia da vontade do ocupante, imóvel alheio ou suas dependências, sem determinação judicial ou fora das condições estabelecidas em lei, sujeita o autor à pena de:",
    explicacao: "GABARITO: A. Art. 22 da Lei nº 13.869/2019: Invadir ou adentrar imóvel alheio sem determinação judicial ou fora das condições estabelecidas em lei: Pena - detenção, de 1 a 4 anos, e multa. Incorre na mesma pena quem cumpre mandado de busca e apreensão domiciliar após as 21h ou antes das 5h (§ 1º, III).",
    alternativas: [
      { texto: "detenção, de 1 a 4 anos, e multa.", correta: true },
      { texto: "reclusão, de 6 a 12 anos.", correta: false },
      { texto: "prisão simples, de 10 a 30 dias.", correta: false },
      { texto: "advertência por escrito do corregedor-geral.", correta: false },
      { texto: "multa civil de 5 salários mínimos.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-015",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A conduta de 'possuir ou manter sob sua guarda arma de fogo, acessório ou munição, de uso permitido, em desacordo com determinação legal ou regulamentar, no interior de sua residência ou dependência desta, ou, ainda, no seu local de trabalho, desde que seja o titular ou o responsável legal pelo estabelecimento ou empresa' (art. 12 da Lei nº 10.826/2003) tipifica:",
    explicacao: "GABARITO: C. Art. 12 da Lei nº 10.826/2003: Trata-se do crime de posse irregular de arma de fogo de uso permitido, punido com detenção de 1 a 3 anos e multa, caracterizado por ocorrer no interior da residência ou dependências ou local de trabalho do titular.",
    alternativas: [
      { texto: "Porte ilegal de arma de fogo de uso restrito.", correta: false },
      { texto: "Comércio ilegal de arma de fogo.", correta: false },
      { texto: "Posse irregular de arma de fogo de uso permitido.", correta: true },
      { texto: "Disparo de arma de fogo em via pública.", correta: false },
      { texto: "Tráfico internacional de armas.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-016",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.crimes_hediondos_8072,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Assinale a alternativa que apresenta apenas delitos considerados hediondos ou a eles equiparados segundo a Lei nº 8.072/1990 e a Constituição Federal.",
    explicacao: "GABARITO: B. São hediondos e equiparados: Tortura, Tráfico Ilícito de Entorpecentes e Terrorismo (equiparados - 3T) e Homicídio qualificado, Latrocínio, Estupro, Epidemia com resultado morte (hediondos expressos na Lei 8.072/90).",
    alternativas: [
      { texto: "Furto simples, desacato e estelionato comum.", correta: false },
      { texto: "Estupro de vulnerável, latrocínio e homicídio qualificado.", correta: true },
      { texto: "Injúria simples, calúnia e difamação.", correta: false },
      { texto: "Desobediência, corrupção passiva simples e peculato culposo.", correta: false },
      { texto: "Dano qualificado, ameaça e perturbação da tranquilidade.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "leg-esp-03-017",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei nº 13.869/2019, são efeitos da condenação por crime de abuso de autoridade: tornar certa a obrigação de indenizar o dano, a inabilitação para o exercício de cargo pelo prazo de 1 a 5 anos e a perda do cargo, função ou mandato público. Em relação à inabilitação e à perda do cargo, esses efeitos:",
    explicacao: "GABARITO: D. Art. 4º, parágrafo único, da Lei nº 13.869/2019: Os efeitos previstos nos incisos II (inabilitação de 1 a 5 anos) e III (perda do cargo) são condicionados à ocorrência de reincidência em crime de abuso de autoridade e NÃO são automáticos, devendo ser declarados motivadamente na sentença.",
    alternativas: [
      { texto: "são automáticos e independem de fundamentação judicial.", correta: false },
      { texto: "só se aplicam aos agentes políticos com foro por prerrogativa.", correta: false },
      { texto: "são perpétuos e impedem qualquer reingresso no serviço público.", correta: false },
      { texto: "são condicionados à reincidência em crime de abuso de autoridade e não são automáticos, devendo ser declarados motivadamente na sentença.", correta: true },
      { texto: "só se aplicam se a pena privativa de liberdade for superior a 8 anos.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-018",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Papiloscopista Policial",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A respeito do crime de associação para o tráfico de drogas (art. 35 da Lei nº 11.343/2006), a jurisprudência sumulada e pacífica do Superior Tribunal de Justiça e do Supremo Tribunal Federal exige para sua configuração:",
    explicacao: "GABARITO: E. A jurisprudência consolidada do STJ e do STF exige o dolo de associação com estabilidade e permanência (animus associativo estável) entre duas ou mais pessoas para a prática reiterada ou não dos crimes de tráfico. O mero concurso eventual e episódico de agentes não tipifica o art. 35.",
    alternativas: [
      { texto: "a participação mínima de 4 pessoas com divisão hierárquica de tarefas.", correta: false },
      { texto: "a comprovação de apreensão física de grande quantidade de drogas em poder de todos os associados.", correta: false },
      { texto: "o cometimento do crime em área de fronteira internacional.", correta: false },
      { texto: "o concurso meramente eventual e esporádico de dois agentes em uma única venda.", correta: false },
      { texto: "o dolo específico de associação estável e permanente entre duas ou mais pessoas para a prática dos crimes previstos nos arts. 33 e 34 da Lei de Drogas.", correta: true },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "leg-esp-03-019",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Disparar arma de fogo ou acionar munição em lugar habitado ou em suas adjacências, em via pública ou em direção a ela, desde que essa conduta não tenha por finalidade a prática de outro crime (art. 15 da Lei nº 10.826/2003):",
    explicacao: "GABARITO: A. Art. 15 da Lei nº 10.826/2003: Disparo de arma de fogo: Pena - reclusão, de 2 a 4 anos, e multa. Trata-se de crime subsidiário expressamente previsto ('desde que essa conduta não tenha por finalidade a prática de outro crime').",
    alternativas: [
      { texto: "configura o crime de disparo de arma de fogo, punido com reclusão de 2 a 4 anos e multa.", correta: true },
      { texto: "é mera contravenção penal se não atingir pessoa ou patrimônio.", correta: false },
      { texto: "configura tentativa de homicídio simples em qualquer circunstância.", correta: false },
      { texto: "é conduta atípica se os tiros forem disparados para o alto em comemorações.", correta: false },
      { texto: "sujeita o agente apenas à perda da posse da arma pelo prazo de 30 dias.", correta: false },
    ],
  },
  {
    idSlug: "leg-esp-03-020",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.abuso_autoridade_13869,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Submeter o preso, internado ou apreendido ao uso de algemas quando manifestamente não houver resistência à prisão, ameaça de fuga ou perigo à integridade física própria ou alheia (art. 13 da Lei nº 13.869/2019 e Súmula Vinculante 11 do STF) constitui:",
    explicacao: "GABARITO: B. A utilização de algemas fora das hipóteses excepcionais justificadas por escrito (resistência, perigo à integridade física própria ou alheia, ou fundado receio de fuga - Súmula Vinculante 11 do STF) e com dolo específico configura crime de abuso de autoridade na Lei nº 13.869/2019.",
    alternativas: [
      { texto: "procedimento padrão obrigatório de segurança em todas as conduções.", correta: false },
      { texto: "crime de abuso de autoridade, caso praticado com a finalidade específica de prejudicar, beneficiar a si ou a terceiro, ou por mero capricho.", correta: true },
      { texto: "infração disciplinar que enseja exoneração sumária sem direito à ampla defesa.", correta: false },
      { texto: "fato atípico se o conduzido já tiver passagens anteriores pela polícia.", correta: false },
      { texto: "conduta permitida discricionariamente pelo agente condutor em qualquer caso.", correta: false },
    ],
  },
];
