import { TAXONOMIA } from "./taxonomia.mjs";

export const procPenal02Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "proc-pen-02-001",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Perito Criminal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Considera-se cadeia de custódia o conjunto de todos os procedimentos utilizados para manter e documentar a história cronológica do vestígio coletado em locais ou em vítimas de crimes, para rastrear sua posse e manuseio a partir de seu reconhecimento até o descarte.",
    explicacao: "GABARITO: CERTO. Art. 158-A do CPP (incluído pela Lei nº 13.964/2019): Considera-se cadeia de custódia o conjunto de todos os procedimentos utilizados para manter e documentar a história cronológica do vestígio coletado em locais ou em vítimas de crimes, para rastrear sua posse e manuseio a partir de seu reconhecimento até o descarte.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-002",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Perito Criminal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O início da cadeia de custódia dá-se com a preservação do local de crime ou com procedimentos policiais ou periciais nos quais seja detectada a existência de vestígio, sendo a etapa do reconhecimento o ato de distinguir um elemento como de potencial interesse para a produção da prova pericial.",
    explicacao: "GABARITO: CERTO. Art. 158-A, § 1º e art. 158-B, I, do CPP: O início da cadeia de custódia dá-se com a preservação do local de crime ou com procedimentos policiais ou periciais nos quais seja detectada a existência de vestígio. O reconhecimento é o ato de distinguir um elemento como de potencial interesse pericial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-003",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante investigação conduzida pela Polícia Civil sobre organização criminosa armada, a autoridade policial colheu depoimentos testemunhais e relatórios de inteligência na fase do inquérito policial. Em juízo, as testemunhas não foram localizadas para depor em contraditório. Nesse cenário, o magistrado sentenciante pode fundamentar a condenação dos réus em perícia grafotécnica definitiva realizada no inquérito (prova não repetível), mesmo que os relatórios de inteligência policiais isolados não pudessem sustentar, por si sós, o édito condenatório.",
    explicacao: "GABARITO: CERTO. De acordo com o art. 155, caput, do CPP, o juiz não pode fundamentar sua decisão exclusivamente nos elementos informativos do inquérito, mas há expressa ressalva quanto às provas cautelares, não repetíveis (como a perícia técnica) e antecipadas, as quais possuem pleno valor probatório mesmo quando realizadas na fase investigatória preliminar.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-004",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A busca domiciliar dependerá de mandado judicial, salvo em caso de flagrante delito ou desastre, ou para prestar socorro, ou durante o dia, com o consentimento do morador.",
    explicacao: "GABARITO: CERTO. Art. 5º, XI, da CF e art. 240 do CPP: A casa é asilo inviolável do indivíduo, ninguém nela podendo penetrar sem consentimento do morador, salvo em caso de flagrante delito ou desastre, ou para prestar socorro, ou, durante o dia, por determinação judicial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-005",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A busca pessoal independerá de mandado judicial no caso de prisão ou quando houver fundada suspeita de que a pessoa esteja na posse de arma proibida ou de objetos ou papéis que constituam corpo de delito.",
    explicacao: "GABARITO: CERTO. Art. 244 do CPP: A busca pessoal independerá de mandado, no caso de prisão ou quando houver fundada suspeita de que a pessoa esteja na posse de arma proibida ou de objetos ou papéis que constituam corpo de delito, ou quando a medida for determinada no curso de busca domiciliar.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-006",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O reconhecimento de pessoas realizado na fase policial ou em juízo sem a estrita observância das formalidades do art. 226 do CPP constitui mera irregularidade processual, sendo plenamente suficiente, por si só, para lastrear uma condenação penal.",
    explicacao: "GABARITO: ERRADO. Conforme tese fixada pelo STJ (HC 598.886/SC) e pelo STF (RHC 206.846), as formalidades do art. 226 do CPP constituem garantia fundamental do imputado. O reconhecimento realizado em desacordo com as regras legais é inválido e não pode, isoladamente, fundamentar a condenação penal.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "proc-pen-02-007",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "São inadmissíveis no processo penal as provas obtidas por meios ilícitos, bem como as provas derivadas das ilícitas, salvo quando não evidenciado o nexo de causalidade ou quando as derivadas puderem ser obtidas por uma fonte independente.",
    explicacao: "GABARITO: CERTO. Art. 157, § 1º, do CPP: São inadmissíveis as provas derivadas das ilícitas, salvo quando não evidenciado o nexo de causalidade entre umas e outras, ou quando as derivadas puderem ser obtidas por uma fonte independente (teoria dos frutos da árvore envenenada e exceção da fonte independente).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-008",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A entrada forçada em domicílio sem mandado judicial, mesmo em caso de crime permanente (como o tráfico de drogas na modalidade ter em depósito), exige a demonstração prévia de fundadas razões (justa causa), sob pena de nulidade da apreensão e ilicitude das provas.",
    explicacao: "GABARITO: CERTO. STF, Tema 280 da Repercussão Geral (RE 603.616): A entrada forçada em domicílio sem mandado judicial só é lícita, mesmo em período noturno, quando amparada em fundadas razões, devidamente justificadas pelas circunstâncias do caso concreto, que indiquem estar ocorrendo situação de flagrante delito no interior da residência.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "proc-pen-02-009",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Perito Criminal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O art. 158-B do Código de Processo Penal discrimina as 10 etapas sequenciais que integram a cadeia de custódia da prova pericial. Assinale a alternativa que indica a etapa definida como 'o ato de embalar cada vestígio coletado de forma individualizada, de acordo com suas características físicas, químicas ou biológicas'.",
    explicacao: "GABARITO: B. Art. 158-B, V, do CPP: Acondicionamento é o procedimento por meio do qual cada vestígio coletado é embalado de forma individualizada, de acordo com suas características físicas, químicas ou biológicas, para posterior análise, com controle do lacre.",
    alternativas: [
      { texto: "Fixação.", correta: false },
      { texto: "Acondicionamento.", correta: true },
      { texto: "Isolamento.", correta: false },
      { texto: "Reconhecimento.", correta: false },
      { texto: "Descarte.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-010",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Quando a infração deixar vestígios, será indispensável o exame de corpo de delito, direto ou indireto, não podendo supri-lo a confissão do acusado (art. 158 do CPP). Não sendo possível a realização do exame direto por haverem desaparecido os vestígios, a prova testemunhal:",
    explicacao: "GABARITO: A. Art. 167 do CPP: Não sendo possível o exame de corpo de delito, por haverem desaparecido os vestígios, a prova testemunhal poderá suprir-lhe a falta.",
    alternativas: [
      { texto: "poderá suprir-lhe a falta.", correta: true },
      { texto: "é absolutamente vedada para suprir o exame de corpo de delito.", correta: false },
      { texto: "exigirá a confissão sob tortura do investigado.", correta: false },
      { texto: "só será admitida se prestada por autoridade policial militar.", correta: false },
      { texto: "gera nulidade absoluta do processo se acolhida.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-011",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação ao mandado de busca e apreensão domiciliar (art. 243 e 245 do CPP), assinale a afirmativa correta.",
    explicacao: "GABARITO: C. Art. 245, caput, do CPP: As buscas domiciliares serão executadas de dia, salvo se o morador consentir que se realizem à noite, e, antes de penetrarem na casa, os executores mostrarão e lerão o mandado ao morador, ou a quem o represente, intimando-o a abrir a porta.",
    alternativas: [
      { texto: "As buscas domiciliares podem ser executadas à noite sem consentimento do morador, desde que com mandado judicial genérico.", correta: false },
      { texto: "O mandado de busca dispensa a indicação da casa ou do motivo da diligência.", correta: false },
      { texto: "As buscas domiciliares serão executadas de dia, salvo consentimento do morador para realização noturna, devendo os executores exibir e ler o mandado ao morador.", correta: true },
      { texto: "A recusa do morador em abrir a porta impede a execução da ordem judicial em qualquer circunstância.", correta: false },
      { texto: "O auto de busca domiciliar não precisa ser assinado por testemunhas presenciais.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-012",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre a atuação dos peritos oficiais e não oficiais no processo penal brasileiro (art. 159 do CPP), assinale a afirmativa correta.",
    explicacao: "GABARITO: D. Art. 159 do CPP: O exame de corpo de delito e outras perícias serão realizados por perito oficial, portador de diploma de curso superior. § 1º Na falta de perito oficial, o exame será realizado por 2 (duas) pessoas idôneas, portadoras de diploma de curso superior preferencialmente na área específica.",
    alternativas: [
      { texto: "O exame pericial oficial deve ser realizado obrigatoriamente por 3 peritos concursados.", correta: false },
      { texto: "Na falta de perito oficial, o exame pode ser realizado por uma única pessoa leiga sem diploma de nível superior.", correta: false },
      { texto: "O assistente técnico indicado pelas partes pode atuar antes da conclusão dos exames pelos peritos oficiais.", correta: false },
      { texto: "A perícia oficial é realizada por 1 perito oficial; na sua falta, por 2 pessoas idôneas, portadoras de diploma de curso superior preferencialmente na área.", correta: true },
      { texto: "O laudo pericial vincula de forma absoluta o magistrado, que não pode rejeitá-lo no todo ou em parte.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-013",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A respeito da prova testemunhal no processo penal (arts. 202 a 225 do CPP), assinale a afirmativa correta.",
    explicacao: "GABARITO: E. Art. 206 do CPP: A testemunha não poderá eximir-se da obrigação de depor. Poderão, entretanto, recusar-se a fazê-lo o ascendente ou descendente, o afim em linha reta, o cônjuge, ainda que desquitado, o irmão e o pai, a mãe, ou o filho adotivo do acusado, salvo quando não for possível, por outro modo, obter-se ou integrar-se a prova do fato e de suas circunstâncias.",
    alternativas: [
      { texto: "Toda testemunha é obrigada a prestar compromisso de dizer a verdade, sem qualquer exceção legal.", correta: false },
      { texto: "O juiz não pode de ofício ouvir testemunhas não arroladas pelas partes.", correta: false },
      { texto: "Menores de 14 anos prestam compromisso legal de dizer a verdade sob pena de falso testemunho.", correta: false },
      { texto: "As testemunhas prestarão depoimento em conjunto na mesma sala de audiência.", correta: false },
      { texto: "O cônjuge do acusado, ainda que desquitado, e seus ascendentes e descendentes podem recusar-se a depor, salvo quando não for possível obter a prova por outro meio.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "proc-pen-02-014",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos do art. 158-C do CPP, a coleta dos vestígios deverá ser realizada preferencialmente por:",
    explicacao: "GABARITO: A. Art. 158-C do CPP: A coleta dos vestígios deverá ser realizada preferencialmente por perito oficial, que dará o encaminhamento necessário para a central de custódia, mesmo quando for necessária a realização de exames complementares.",
    alternativas: [
      { texto: "perito oficial.", correta: true },
      { texto: "qualquer pessoa presente no local do fato.", correta: false },
      { texto: "advogado constituído pelo réu.", correta: false },
      { texto: "jornalista credenciado pela imprensa.", correta: false },
      { texto: "juiz corregedor da comarca.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-015",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "A busca pessoal em mulher (art. 249 do CPP):",
    explicacao: "GABARITO: B. Art. 249 do CPP: A busca em mulher será feita por outra mulher, se não importar retardamento ou prejuízo da diligência.",
    alternativas: [
      { texto: "é expressamente proibida em qualquer situação.", correta: false },
      { texto: "será feita por outra mulher, se não importar retardamento ou prejuízo da diligência.", correta: true },
      { texto: "exige sempre a presença de um juiz de direito no local.", correta: false },
      { texto: "só pode ser realizada no interior de delegacia especializada.", correta: false },
      { texto: "dispensa qualquer justificativa se realizada por policial masculino.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-016",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "De acordo com o art. 158-D do CPP, o recipiente para acondicionamento do vestígio coletado deverá ser selado com lacres, com numeração individualizada, de forma a garantir a inviolabilidade e a idoneidade do vestígio durante o transporte. O rompimento do lacre:",
    explicacao: "GABARITO: C. Art. 158-D, § 2º, do CPP: O recipiente só poderá ser aberto pelo perito que vai proceder à análise e, motivadamente, por pessoa autorizada. § 3º Após a realização da perícia, o material deverá ser novamente acondicionado com novo lacre, constando no laudo pericial a numeração inicial e a final.",
    alternativas: [
      { texto: "pode ser feito livremente por qualquer policial na delegacia.", correta: false },
      { texto: "invalida automaticamente todo o processo penal sem direito a contraprova.", correta: false },
      { texto: "só poderá ser feito pelo perito que vai proceder à análise e, motivadamente, por pessoa autorizada, devendo ser registrado no laudo.", correta: true },
      { texto: "exige a presença física do juiz e do promotor de justiça.", correta: false },
      { texto: "impede a realização de qualquer exame laboratorial subsequente.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "proc-pen-02-017",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No que concerne ao interrogatório do acusado no processo penal brasileiro (arts. 185 a 200 do CPP), assinale a afirmativa correta.",
    explicacao: "GABARITO: D. Art. 186 do CPP: Depois de devidamente qualificado e cientificado do inteiro teor da acusação, o acusado será informado pelo juiz, antes de iniciar o interrogatório, do seu direito de permanecer calado e de não responder a perguntas que lhe forem formuladas. Parágrafo único: O silêncio, que não importará em confissão, não poderá ser interpretado em prejuízo da defesa.",
    alternativas: [
      { texto: "O interrogatório é ato privativo e exclusivo da acusação, não constituindo meio de defesa.", correta: false },
      { texto: "O silêncio do réu no interrogatório implica confissão ficta dos fatos narrados na denúncia.", correta: false },
      { texto: "O acusado é obrigado a prestar juramento de dizer a verdade sob pena de falso testemunho.", correta: false },
      { texto: "O réu tem o direito de permanecer em silêncio e seu exercício não pode ser valorado em seu prejuízo.", correta: true },
      { texto: "O interrogatório não admite a participação de defensor técnico constituído.", correta: false },
    ],
  },
  {
    idSlug: "proc-pen-02-018",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A obtenção de dados e conversas privadas armazenadas em aplicativo de mensagens instantâneas (como o WhatsApp) em aparelho celular apreendido durante a prisão em flagrante:",
    explicacao: "GABARITO: A. Conforme pacífica jurisprudência do STJ e do STF, o acesso aos dados e mensagens armazenados em celular apreendido durante prisão em flagrante depende de prévia e expressa autorização judicial (ou consentimento livre e voluntário do titular), sendo ilícita a devassa direta pela autoridade policial sem respaldo judicial.",
    alternativas: [
      { texto: "depende de prévia autorização judicial, sendo ilícita a devassa direta realizada pelos policiais sem respaldo judicial.", correta: true },
      { texto: "é permitida de forma irrestrita e automática pela autoridade policial como efeito da apreensão do bem.", correta: false },
      { texto: "só pode ser autorizada pelo juízo das garantias no prazo de 10 dias após a sentença.", correta: false },
      { texto: "constitui prerrogativa discricionária do Ministério Público sem necessidade de ordem judicial.", correta: false },
      { texto: "não goza de nenhuma proteção constitucional por se tratar de crime em andamento.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "proc-pen-02-019",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.provas_processo_penal,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O exame de corpo de delito poderá ser feito (art. 161 do CPP):",
    explicacao: "GABARITO: E. Art. 161 do CPP: O exame de corpo de delito poderá ser feito em qualquer dia e a qualquer hora.",
    alternativas: [
      { texto: "exclusivamente em dias úteis durante o horário forense.", correta: false },
      { texto: "apenas no período diurno, entre 6h e 18h.", correta: false },
      { texto: "somente após a citação formal do réu no processo.", correta: false },
      { texto: "exclusivamente aos finais de semana e feriados.", correta: false },
      { texto: "em qualquer dia e a qualquer hora.", correta: true },
    ],
  },
  {
    idSlug: "proc-pen-02-020",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.busca_apreensao_procedimentos,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com o art. 240, § 1º, do CPP, proceder-se-á à busca domiciliar, quando fundadas razões a autorizarem, para, entre outras finalidades:",
    explicacao: "GABARITO: B. Art. 240, § 1º, do CPP: Proceder-se-á à busca domiciliar para: prender criminosos; apreender coisas achadas ou obtidas por meios criminosos; apreender instrumentos de falsificação ou de contrafação e armas e munições; colher elementos de convicção.",
    alternativas: [
      { texto: "promover a demolição administrativa do imóvel para obras públicas.", correta: false },
      { texto: "prender criminosos, apreender coisas obtidas por meios criminosos e colher elementos de convicção.", correta: true },
      { texto: "cobrar tributos municipais em atraso diretamente dos moradores.", correta: false },
      { texto: "recadastrar os eleitores da zona territorial.", correta: false },
      { texto: "fiscalizar a instalação de antenas de televisão aberta.", correta: false },
    ],
  },
];
