import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const legEsp01 = [
  // 1 to 10: Lei de Drogas (11.343/06)
  {
    idSlug: "b10-leg-01-001",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "De acordo com o entendimento firmado pelo Supremo Tribunal Federal no julgamento do RE 635.659, o porte de maconha para consumo pessoal (art. 28 da Lei nº 11.343/2006) foi despenalizado e descriminalizado no âmbito do Direito Penal, passando a configurar ilícito de natureza estritamente administrativa, fixando-se como critério objetivo de presunção relativa de porte para uso próprio a posse de até 40 gramas ou de 6 plantas fêmeas.",
    explicacao: "GABARITO: CERTO. O STF declarou a inconstitucionalidade sem pronúncia de nulidade da tipificação penal do porte de maconha/cannabis para consumo próprio (art. 28 da Lei 11.343/06), fixando a natureza de ilícito administrativo e estabelecendo o critério quantitativo de até 40g ou 6 plantas fêmeas como presunção relativa de usuário.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-002",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de tráfico de drogas previsto no art. 33, caput, da Lei nº 11.343/2006 é classificado pela doutrina como crime de conteúdo variado ou tipo misto alternativo, de sorte que a realização de mais de uma conduta típica em relação à mesma substância entorpecente, no mesmo contexto fático, configura crime único.",
    explicacao: "GABARITO: CERTO. O art. 33 da Lei de Drogas prevê múltiplos núcleos verbais (tipo misto alternativo). A prática de múltiplos verbos sobre a mesma droga no mesmo contexto fático caracteriza crime único.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-003",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para a incidência da causa de diminuição de pena do tráfico privilegiado (art. 33, § 4º, da Lei nº 11.343/2006), exige-se o preenchimento cumulativo de quatro requisitos: primariedade, bons antecedentes, não dedicação a atividades criminosas e não integração a organização criminosa.",
    explicacao: "GABARITO: CERTO. Os requisitos do art. 33, § 4º, são cumulativos: agente primário, de bons antecedentes, que não se dedique às atividades criminosas nem integre organização criminosa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-004",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O tráfico privilegiado de entorpecentes é equiparado a crime hediondo para fins de fixação de regime inicial fechado e vedação de indulto.",
    explicacao: "GABARITO: ERRADO. O Pacote Anticrime (Lei 13.964/19) incluiu expressamente o § 5º no art. 112 da LEP e o § 2º no art. 2º da Lei 8.072/90 dispondo que o tráfico privilegiado NÃO é crime hediondo nem equiparado.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-leg-01-005",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Mévio e Tício ajustaram verbalmente a compra e venda de 100g de cocaína em um único evento festivo. Abordados pela polícia civil no momento da entrega, verificou-se que nunca haviam praticado crimes juntos anteriormente e não possuíam qualquer estrutura estável. Nesse caso, quanto ao crime de associação para o tráfico (art. 35 da Lei nº 11.343/2006):",
    explicacao: "GABARITO: B. A jurisprudência pacífica do STF e STJ exige o animus associativo estável e permanente para o crime do art. 35 da Lei de Drogas. O mero concurso eventual de agentes não configura associação para o tráfico.",
    alternativas: [
      { texto: "Ambos devem responder por associação para o tráfico, pois o tipo prescinde de estabilidade e permanência.", correta: false },
      { texto: "Não se configura o crime de associação para o tráfico, uma vez que a jurisprudência sumulada do STJ e STF exige o dolo de associação estável e duradoura.", correta: true },
      { texto: "Configura-se associação para o tráfico apenas para Tício, que forneceu a substância entorpecente.", correta: false },
      { texto: "A associação resta caracterizada se demonstrado o lucro compartilhado, dispensada a habitualidade.", correta: false },
      { texto: "Ambos respondem por organização criminosa nos termos da Lei nº 12.850/2013.", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-006",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A incidência da majorante do tráfico interestadual de drogas (art. 40, V, da Lei nº 11.343/2006) prescinde da efetiva transposição da divisa interestadual, sendo suficiente a demonstração inequívoca de que a substância tinha como destino outro estado da Federação.",
    explicacao: "GABARITO: CERTO. Súmula 587 do STJ: 'Para a incidência da majorante prevista no art. 40, V, da Lei n. 11.343/2006, é desnecessária a efetiva transposição de fronteiras entre estados da Federação, sendo suficiente a demonstração inequívoca da destinação interestadual das drogas'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-007",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A majorante da transnacionalidade do tráfico de drogas (art. 40, I, da Lei nº 11.343/2006) e a competência da Justiça Federal configuram-se mesmo que o entorpecente não tenha ultrapassado os limites territoriais do Brasil, desde que comprovada a procedência exterior ou a destinação ao exterior.",
    explicacao: "GABARITO: CERTO. Súmula 607 do STJ: 'A majorante do tráfico transnacional de drogas (art. 40, inciso I, da Lei n. 11.343/2006) configura-se com a prova da destinação internacional das drogas, ainda que não consumada a transposição de fronteiras'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-008",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Agente de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O laudo de constatação preliminar de substância entorpecente firmado por perito oficial ou pessoa idônea é suficiente para a lavratura do auto de prisão em flagrante e oferecimento da denúncia pelo Ministério Público.",
    explicacao: "GABARITO: ERRADO. O laudo preliminar é suficiente para a lavratura do auto de prisão em flagrante e instauração do inquérito (art. 50, § 1º, da Lei 11.343/06), mas a condenação e instrução exigem a juntada do laudo toxicológico definitivo.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-leg-01-009",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Para o autor da conduta de adquirir, guardar ou transportar drogas para consumo pessoal (art. 28 da Lei nº 11.343/2006), a lei não prevê pena privativa de liberdade em nenhuma hipótese.",
    explicacao: "GABARITO: CERTO. O art. 28 prevê unicamente penas de advertência sobre os efeitos das drogas, prestação de serviços à comunidade e medida educativa de comparecimento a programa ou curso educativo.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-010",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "2104a0a6-1d8a-5f25-89b9-01eb94f91057",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A incineração de drogas apreendidas cuja prisão em flagrante tenha sido lavrada deverá ser executada pelo delegado de polícia no prazo de quinze dias, na presença do Ministério Público e da autoridade sanitária.",
    explicacao: "GABARITO: CERTO. Art. 50, § 3º, da Lei 11.343/06: a incineração das drogas apreendidas em flagrante será executada pelo delegado de polícia no prazo de 15 dias, na presença do MP e da autoridade sanitária.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11 to 20: Estatuto do Desarmamento (10.826/03)
  {
    idSlug: "b10-leg-01-011",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A posse irregular de arma de fogo de uso permitido no interior da residência ou em local de trabalho do qual o agente seja o titular ou responsável legal configura o delito do art. 12 do Estatuto do Desarmamento, afiançável pela autoridade policial.",
    explicacao: "GABARITO: CERTO. Art. 12 da Lei 10.826/03 comina pena de detenção de 1 a 3 anos e multa. Como a pena máxima não ultrapassa 4 anos, cabe fiança fixada pelo Delegado de Polícia (art. 322 do CPP).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-012",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A conduta de portar arma de fogo com numeração, marca ou qualquer outro sinal de identificação raspado, suprimido ou adulterado subsume-se ao tipo do art. 16, § 1º, IV, da Lei nº 10.826/2003, independentemente de a arma originariamente ser de uso permitido, restrito ou proibido.",
    explicacao: "GABARITO: CERTO. A conduta de supressão ou raspagem de numeração equipara a arma ao tratamento do art. 16, sendo irrelevante o calibre originário para a tipificação nesta figura equiparada.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-013",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O porte ilegal de arma de fogo de uso permitido (art. 14 da Lei nº 10.826/2003) é classificado pela doutrina e jurisprudência como crime de perigo abstrato e de mera conduta, prescindindo da demonstração de lesão efetiva ao bem jurídico tutelado.",
    explicacao: "GABARITO: CERTO. Jurisprudência pacífica do STF e STJ afirma a constitucionalidade e a natureza de perigo abstrato dos crimes de porte ilegal de arma de fogo e munição.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-014",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Caim foi abordado em via pública portando consigo apenas um projétil de munição intacto de calibre .380 (uso permitido), desacompanhado de arma de fogo. Submetida a perícia, a munição estava apta a deflagração. Segundo a jurisprudência recente do STF e do STJ sobre a posse/porte de pequena quantidade de munição desacompanhada de arma de fogo:",
    explicacao: "GABARITO: C. O STF e o STJ admitem a aplicação do princípio da insignificância ao porte/posse de pequena quantidade de munição desacompanhada de arma de fogo capaz de deflagrá-la, desde que não haja outros elementos que indiquem periculosidade concreta do agente.",
    alternativas: [
      { texto: "Configura invariavelmente crime de perigo abstrato insuscetível de aplicação do princípio da insignificância em qualquer hipótese.", correta: false },
      { texto: "Aplica-se a imunidade penal do art. 13 do Código Penal por ausência de resultado naturalístico.", correta: false },
      { texto: "Admite-se excepcionalmente o reconhecimento da atipicidade material da conduta com base no princípio da insignificância, diante da inexpressiva lesividade ao bem jurídico e ausência de arma acessível.", correta: true },
      { texto: "Configura contravenção penal de porte de arma branca por analogia in bonam partem.", correta: false },
      { texto: "Exige-se a punição por crime tentado de porte de arma de fogo de uso permitido.", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-015",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A conduta de disparar arma de fogo em lugar habitado ou em suas adjacências, em via pública ou em direção a ela (art. 15 da Lei nº 10.826/2003) é subsidiária, não se aplicando se a conduta tiver como finalidade a prática de outro crime.",
    explicacao: "GABARITO: CERTO. Art. 15, caput, in fine, da Lei 10.826/03 expressamente ressalva: 'desde que essa conduta não tenha por finalidade a prática de outro crime' (subsidiariedade expressa).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-016",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O crime de comércio ilegal de arma de fogo (art. 17 da Lei nº 10.826/2003) é considerado hediondo pela Lei nº 8.072/1990.",
    explicacao: "GABARITO: CERTO. O art. 1º, parágrafo único, II, da Lei 8.072/90 (incluído pela Lei 13.964/19) qualifica como hediondo o crime de comércio ilegal de arma de fogo (art. 17) e o tráfico internacional de arma de fogo (art. 18).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-017",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Agente de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O proprietário ou diretor responsável de empresa de segurança privada e de transporte de valores que deixar de registrar ocorrência policial de perda, furto ou roubo de arma de fogo nas primeiras 24 horas pratica crime omissivo próprio punido com detenção.",
    explicacao: "GABARITO: CERTO. Art. 13, parágrafo único, da Lei 10.826/03: comina pena de detenção de 1 a 2 anos e multa para quem deixar de registrar ocorrência nas primeiras 24 horas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-018",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de posse ou porte ilegal de arma de fogo de uso proibido (art. 16, caput, da Lei nº 10.826/2003) é considerado crime hediondo, mas a posse ou porte de arma de fogo de uso restrito não é hediondo.",
    explicacao: "GABARITO: CERTO. Após a Lei 13.964/19 (Pacote Anticrime), o art. 1º, parágrafo único, II, da Lei 8.072/90 passou a considerar hediondo apenas o crime de posse ou porte ilegal de arma de fogo de uso PROIBIDO (não mais o de uso restrito).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-019",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O SINARM (Sistema Nacional de Armas), instituído no Ministério da Justiça e Segurança Pública no âmbito da Polícia Federal, tem circunscrição em todo o território nacional.",
    explicacao: "GABARITO: CERTO. Art. 1º da Lei 10.826/03: 'O Sistema Nacional de Armas - Sinarm, instituído no Ministério da Justiça, no âmbito da Polícia Federal, com circunscrição em todo o território nacional...'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-020",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "dc244c93-245b-53ce-b721-bcdc9eae0e5f",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A autorização para o porte de arma de fogo de uso permitido, em todo o território nacional, é de competência da:",
    explicacao: "GABARITO: D. Art. 10 da Lei 10.826/03: a autorização para o porte de arma de fogo de uso permitido é de competência da Polícia Federal e somente será concedida após autorização do Sinarm.",
    alternativas: [
      { texto: "Polícia Militar de cada Unidade Federativa.", correta: false },
      { texto: "Polícia Civil no âmbito estadual.", correta: false },
      { texto: "Guarda Municipal do município de residência do requerente.", correta: false },
      { texto: "Polícia Federal, com autorização do Sinarm.", correta: true },
      { texto: "Secretaria de Segurança Pública Estadual exclusivamente.", correta: false },
    ],
  },

  // 21 to 30: Lei de Abuso de Autoridade (13.869/19)
  {
    idSlug: "b10-leg-01-021",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 13.869/2019, para a caracterização de qualquer crime de abuso de autoridade, é indispensável a comprovação do dolo específico de prejudicar outrem ou beneficiar a si mesmo ou a terceiro, ou por mero capricho ou satisfação pessoal.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 1º, da Lei 13.869/19 exige elemento subjetivo especial (finalidade específica de prejudicar outrem, beneficiar a si ou a terceiro, ou mero capricho/satisfação pessoal). Sem dolo específico, a conduta é atípica perante a lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-022",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A divergência na interpretação de lei ou na avaliação de fatos e provas não configura abuso de autoridade.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 2º, da Lei 13.869/19 veda expressamente o chamado 'crime de hermenêutica'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-023",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Os crimes previstos na Lei nº 13.869/2019 são de ação penal pública incondicionada, admitindo-se ação penal privada subsidiária da pública caso o Ministério Público não ofereça denúncia no prazo legal.",
    explicacao: "GABARITO: CERTO. Art. 3º, caput e § 1º, da Lei 13.869/19: os crimes são de ação penal pública incondicionada, com previsão de ação privada subsidiária se a denúncia não for intentada no prazo legal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-024",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre os efeitos da condenação previstos na Lei nº 13.869/2019 (Abuso de Autoridade), é correto afirmar que:",
    explicacao: "GABARITO: E. Art. 4º, parágrafo único: a perda do cargo e a inabilitação para o exercício de função pública são efeitos não automáticos e condicionados à ocorrência de reincidência em crime de abuso de autoridade.",
    alternativas: [
      { texto: "A perda do cargo público é efeito automático da condenação em primeiro grau.", correta: false },
      { texto: "A inabilitação para o exercício de cargo público aplica-se pelo prazo fixo de dez anos.", correta: false },
      { texto: "A obrigação de indenizar o dano causado é condicionada à reincidência específica.", correta: false },
      { texto: "A perda do cargo público independe de reincidência e é de aplicação cogente.", correta: false },
      { texto: "A inabilitação para o exercício de cargo, mandato ou função pública e a perda do cargo são efeitos não automáticos e condicionados à reincidência em crime de abuso de autoridade.", correta: true },
    ],
  },
  {
    idSlug: "b10-leg-01-025",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Constitui crime de abuso de autoridade cumprir mandado de busca e apreensão domiciliar após as 21h ou antes das 5h.",
    explicacao: "GABARITO: CERTO. Art. 22, § 1º, III, da Lei 13.869/19: incorre na pena de detenção de 1 a 4 anos quem cumpre mandado de busca e apreensão domiciliar após as 21h (vinte e uma horas) ou antes das 5h (cinco horas).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-026",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Pode ser sujeito ativo do crime de abuso de autoridade qualquer agente público, servidor ou não, da administração direta, indireta ou fundacional de qualquer dos Poderes da União, dos Estados, do DF e dos Municípios.",
    explicacao: "GABARITO: CERTO. Art. 2º da Lei 13.869/19 adota conceito amplo de agente público para fins da incidência da lei.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-027",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A autoridade policial que deixar injustificadamente de comunicar prisão em flagrante à autoridade judiciária no prazo legal pratica crime punido pela Lei de Abuso de Autoridade.",
    explicacao: "GABARITO: CERTO. Art. 12, I, da Lei 13.869/19 tipifica a conduta de deixar injustificadamente de comunicar prisão em flagrante à autoridade judiciária no prazo legal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-028",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Divulgar gravação ou trecho de gravação sem relação com a prova que se pretenda produzir, expondo a intimidade ou a vida privada do investigado, é crime tipificado na Lei de Abuso de Autoridade.",
    explicacao: "GABARITO: CERTO. Art. 28 da Lei 13.869/19: divulgar gravação ou trecho dela sem relação com a prova que se pretenda produzir, expondo a intimidade do investigado.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-029",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Agente de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Submeter a pessoa presa ao uso de algemas quando manifestamente não houver resistência à prisão, ameaça de fuga ou perigo à integridade física própria ou alheia, com o fim de constrangê-la, configura crime de abuso de autoridade.",
    explicacao: "GABARITO: CERTO. Art. 13, II, da Lei 13.869/19 c/c Súmula Vinculante 11 do STF: tipifica o constrangimento mediante uso indevido de algemas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-leg-01-030",
    disciplina_id: "f54b2f9a-3916-5409-a431-a93ce24510e9",
    assunto_id: "a8ddf09b-39eb-5a8b-b538-0c5dc1eaf457",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre as penas restritivas de direitos substitutivas das privativas de liberdade na Lei nº 13.869/2019:",
    explicacao: "GABARITO: A. Art. 5º da Lei 13.869/19: as penas restritivas de direitos são prestação de serviços à comunidade e suspensão do exercício do cargo por 1 a 6 meses com perda dos vencimentos, podendo ser aplicadas autônoma ou cumulativamente.",
    alternativas: [
      { texto: "Podem ser aplicadas de forma autônoma ou cumulativa a prestação de serviços à comunidade e a suspensão do cargo por 1 a 6 meses com perda de vencimentos.", correta: true },
      { texto: "A suspensão do cargo é sem prejuízo da remuneração integral do servidor.", correta: false },
      { texto: "Apenas a prestação pecuniária pode substituir a pena corporal.", correta: false },
      { texto: "Não se admite substituição por restritiva de direitos para crimes com violência presumida.", correta: false },
      { texto: "A interdição temporária de direitos só é cabível após o trânsito em julgado de sentença condenatória no STF.", correta: false },
    ],
  },
];

// Write to leg_esp_01.mjs
const file01Content = `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const legEsp01Questoes = ${JSON.stringify(legEsp01, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, "leg_esp_01.mjs"), file01Content, "utf8");
console.log("leg_esp_01.mjs gerado com sucesso! (30 questões)");
