import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const temasPoliciais01 = [
  // 1 to 5: SUSP - Lei 13.675/2018 e Gestão da Segurança Pública
  {
    idSlug: "b10-temas-01-001",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos da Lei 13.675/2018 (SUSP), a integração dos órgãos de segurança pública pressupõe atuação conjunta, coordenada e sistêmica, com interoperabilidade de sistemas e compartilhamento recíproco de bancos de dados de inteligência e operacionais.",
    explicacao: "GABARITO: CERTO. Art. 5º e 6º da Lei 13.675/2018 consagram a integração, interoperabilidade e compartilhamento de dados no SUSP.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-002",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "De acordo com a Lei 13.675/2018, são integrantes estratégicos do Sistema Único de Segurança Pública (SUSP), entre outros:",
    explicacao: "GABARITO: A. Art. 9º, § 1º da Lei 13.675/2018: a União, os Estados, o Distrito Federal e os Municípios são os entes e integrantes estratégicos do SUSP.",
    alternativas: [
      { texto: "A União, os Estados, o Distrito Federal e os Municípios.", correta: true },
      { texto: "Exclusivamente as Forças Armadas no exercício de GLO.", correta: false },
      { texto: "Apenas a Polícia Federal e a Polícia Rodoviária Federal.", correta: false },
      { texto: "Somente os órgãos do Poder Judiciário e Ministério Público.", correta: false },
      { texto: "As empresas de segurança privada devidamente cadastradas.", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-003",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Sistema Nacional de Informações de Segurança Pública, Prisionais, de Rastreabilidade de Armas e Munições, de Material Genético, de Digitais e de Drogas (Sinesp) tem por objetivo armazenar, tratar e integrar dados dos órgãos de segurança pública de todo o território nacional.",
    explicacao: "GABARITO: CERTO. Art. 35 e ss. da Lei 13.675/2018 disciplinam a abrangência do Sinesp.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-004",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Rede Integrada de Bancos de Perfis Genéticos (RIBPG) permite a troca de informações periciais e o cruzamento de vestígios biológicos coletados em locais de crime não solucionados em âmbito interestadual.",
    explicacao: "GABARITO: CERTO. A RIBPG integra laboratórios de perícia oficiais para identificação e elucidação criminal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-005",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A promoção dos direitos humanos, a valorização da vida e o respeito à dignidade da pessoa humana são princípios fundamentais e norteadores expressos na Política Nacional de Segurança Pública e Defesa Social (PNSPDS).",
    explicacao: "GABARITO: CERTO. Art. 4º da Lei 13.675/2018 consagra a dignidade humana e os direitos humanos como princípios basilares.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 6 to 10: Lei Orgânica Nacional das Polícias Civis e Militares (Leis 14.735/23 e 14.751/23)
  {
    idSlug: "b10-temas-01-006",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme a Lei Geral das Polícias Civis (Lei 14.735/2023), a Polícia Civil é instituição permanente, essencial à segurança pública, dirigida por Delegado de Polícia de carreira e organizada com base na hierarquia e na disciplina.",
    explicacao: "GABARITO: CERTO. Art. 2º da Lei 14.735/2023 traz a definição institucional e a chefia privativa por Delegado de Polícia de carreira.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-007",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Lei 14.735/2023 (Lei Orgânica Nacional das Polícias Civis) estabeleceu como garantia funcional expressa dos policiais civis:",
    explicacao: "GABARITO: C. Art. 30 da Lei 14.735/2023: porte de arma de fogo em todo o território nacional, com validade da carteira de identidade funcional, inclusive para aposentados (salvo restrição médica/disciplinar).",
    alternativas: [
      { texto: "Inviolabilidade absoluta de domicílio mesmo sem ordem judicial ou flagrante.", correta: false },
      { texto: "Imunidade penal total por atos praticados durante o plantão policial.", correta: false },
      { texto: "Porte de arma de fogo com validade em todo o território nacional.", correta: true },
      { texto: "Dispensa de submissão a sindicâncias ou processos administrativos disciplinares.", correta: false },
      { texto: "Aposentadoria compulsória automática aos 45 anos de idade.", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-008",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Lei Orgânica Nacional das Polícias Militares e Corpos de Bombeiros Militares (Lei 14.751/2023) estabelece que as Polícias Militares são forças auxiliares e reserva do Exército, subordinadas aos Governadores dos Estados e do Distrito Federal.",
    explicacao: "GABARITO: CERTO. Em perfeita harmonia com o art. 144, § 6º da CF/88 e a Lei 14.751/2023.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-009",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O traslado de preso provisório ou condenado para audiências e estabelecimentos penais federais de segurança máxima exige escolta armada e decisão fundamentada do juízo competente.",
    explicacao: "GABARITO: CERTO. A transferência e inclusão de presos em presídios federais de segurança máxima é medida excepcional e requer autorização judicial prévia.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-010",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O Regime Jurídico dos Policiais Civis da União e do Distrito Federal (Lei 4.878/1965) estabelece deveres e vedações disciplinares específicas inerentes à natureza estrita do serviço policial.",
    explicacao: "GABARITO: CERTO. A Lei 4.878/1965 é o estatuto disciplinar policial da União e do DF.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11 to 15: Inteligência Policial, Sigilo e Cadeia de Custódia
  {
    idSlug: "b10-temas-01-011",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na Doutrina Nacional de Inteligência de Segurança Pública (DNISP), a 'Inteligência' visa à produção de conhecimentos úteis para a tomada de decisão das autoridades, enquanto a 'Contrainteligência' tem como escopo a proteção dos conhecimentos e a neutralização de ações adversas.",
    explicacao: "GABARITO: CERTO. Inteligência produz conhecimento; Contrainteligência protege ativos, pessoas e dados contra espionagem, sabotagem e vazamentos.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-012",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei de Acesso à Informação (Lei 12.527/2011), informações imprescindíveis à segurança da sociedade ou do Estado podem ser classificadas nos seguintes graus e prazos máximos de sigilo:",
    explicacao: "GABARITO: B. Ultrassecreta (até 25 anos), Secreta (até 15 anos) e Reservada (até 5 anos), conforme art. 24, § 1º da Lei 12.527/2011.",
    alternativas: [
      { texto: "Confidencial (10 anos), Restrita (5 anos) e Pública (imediata).", correta: false },
      { texto: "Ultrassecreta (25 anos), Secreta (15 anos) e Reservada (5 anos).", correta: true },
      { texto: "Máxima (30 anos), Intermediária (20 anos) e Básica (10 anos).", correta: false },
      { texto: "Estratégica (50 anos), Operacional (25 anos) e Tática (10 anos).", correta: false },
      { texto: "Nacional (40 anos), Estadual (20 anos) e Municipal (5 anos).", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-013",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Ciclo de Produção do Conhecimento de Inteligência estrutura-se nas etapas de Planejamento, Reunião de dados, Processamento (análise/integração) e Difusão do conhecimento produzido.",
    explicacao: "GABARITO: CERTO. Fases clássicas do ciclo de produção do conhecimento de inteligência.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-014",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O princípio da compartimentação na atividade de inteligência estabelece que o acesso a dados e relatórios sigilosos deve ser estritamente restrito a quem possua a real 'necessidade de conhecer' para o desempenho de sua atribuição funcional.",
    explicacao: "GABARITO: CERTO. A 'necessidade de conhecer' (need to know) é o pilar da segurança orgânica e compartimentação de inteligência.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-temas-01-015",
    disciplina_id: "246bf132-8dfb-5928-ba69-bcda8dc9d123",
    assunto_id: "4bf5fa62-23c3-56ae-a2bf-463870ae83f0",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A preservação da integridade da cadeia de custódia de vestígios criminais, introduzida no CPP pelo Pacote Anticrime, impõe o rastreamento documental cronológico de todas as fases pelas quais passou a evidência probatória.",
    explicacao: "GABARITO: CERTO. Arts. 158-A a 158-F do CPP estabelecem a sistemática e etapas da cadeia de custódia.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
];

const fileTemasContent = `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const temasPoliciais01Questoes = ${JSON.stringify(temasPoliciais01, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, "temas_policiais_01.mjs"), fileTemasContent, "utf8");
console.log("temas_policiais_01.mjs gerado com sucesso! (15 questões)");
