import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const const01 = [
  // 1 to 10: Artigo 5º - Direitos Individuais e Coletivos
  {
    idSlug: "b10-const-01-001",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O ingresso forçado em domicílio sem mandado judicial é legítimo, a qualquer hora do dia ou da noite, apenas quando respaldado em fundadas razões, justificadas pelas circunstâncias do caso concreto, que indiquem a ocorrência de flagrante delito no interior da residência.",
    explicacao: "GABARITO: CERTO. Tese do Tema 280/STF (RE 603.616): a entrada forçada em domicílio sem mandado exige fundadas razões (justa causa) prévias devidamente justificadas a posteriori.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-002",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Conforme jurisprudência do STF consolidada na Súmula Vinculante 11, o uso de algemas é lícito apenas em casos de resistência, fundado receio de fuga ou perigo à integridade física própria ou alheia, devendo a excepcionalidade ser justificada por escrito.",
    explicacao: "GABARITO: CERTO. Súmula Vinculante 11 do STF: PRF (Perigo, Resistência, Fuga) justificado por escrito sob pena de nulidade e responsabilidade disciplinar, civil e penal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-003",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Súmula Vinculante 14 do STF, é direito do defensor, no interesse do representado, ter amplo acesso aos elementos de prova que:",
    explicacao: "GABARITO: B. SV 14/STF: o defensor tem acesso amplo aos elementos já documentados que digam respeito ao direito de defesa; diligências em andamento podem ser mantidas sob sigilo.",
    alternativas: [
      { texto: "Estejam em fase de planejamento prévio pela autoridade policial.", correta: false },
      { texto: "Já se encontrem documentados em procedimento investigatório e digam respeito ao exercício do direito de defesa.", correta: true },
      { texto: "Digam respeito a escutas telefônicas ainda em curso operacional.", correta: false },
      { texto: "Envolvam delações premiadas ainda não homologadas pelo Poder Judiciário.", correta: false },
      { texto: "Sejam classificados como segredo de Estado de natureza ultrassecreta.", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-004",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Escrivão de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "São inadmissíveis no processo as provas obtidas por meios ilícitos, aplicando-se a teoria dos frutos da árvore envenenada para invalidar as provas derivadas, salvo quando não evidenciado o nexo de causalidade ou quando as derivadas puderem ser obtidas por fonte independente.",
    explicacao: "GABARITO: CERTO. Art. 5º, LVI, da CF c/c art. 157, §§ 1º e 2º, do CPP.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-005",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A interceptação telefônica para fins de investigação criminal ou instrução processual penal depende de ordem judicial fundamentada e de prévia autorização expressa do titular da linha telefônica investigada.",
    explicacao: "GABARITO: ERRADO. Art. 5º, XII, da CF e Lei 9.296/96: exige ordem judicial fundamentada, mas NÃO depende do consentimento do investigado (o que inviabilizaria a medida).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },

  // 6 to 15: Remédios Constitucionais e Direitos Fundamentais
  {
    idSlug: "b10-const-01-006",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O habeas corpus constitui ação constitucional gratuita destinada a tutelar a liberdade de locomoção contra ilegalidade ou abuso de poder, não sendo cabível para impugnar aplicação exclusiva de pena de multa ou processo administrativo que não comine privação de liberdade.",
    explicacao: "GABARITO: CERTO. Súmula 693/STF: não cabe HC contra decisão condenatória a pena de multa.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-007",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Para assegurar o conhecimento de informações relativas à pessoa do impetrante, constantes de registros ou bancos de dados de entidades governamentais ou de caráter público, a ação constitucional adequada é o:",
    explicacao: "GABARITO: A. Art. 5º, LXXII, 'a', da CF: Habeas Data.",
    alternativas: [
      { texto: "Habeas Data.", correta: true },
      { texto: "Mandado de Segurança Coletivo.", correta: false },
      { texto: "Mandado de Injunção.", correta: false },
      { texto: "Ação Popular.", correta: false },
      { texto: "Habeas Corpus Preventivo.", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-008",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O direito à inviolabilidade do sigilo de dados bancários e fiscais não é absoluto, admitindo que órgãos de fiscalização tributária e o COAF acessem movimentações financeiras diretamente na forma da lei complementar, sem que isso configure quebra indevida de sigilo, mas sim transferência de sigilo.",
    explicacao: "GABARITO: CERTO. STF (ADI 2.390 e RE 601.314): a LC 105/2001 opera a transferência de sigilo para o Fisco/COAF, sendo constitucional.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-009",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O civilmente identificado não será submetido a identificação criminal, salvo nas hipóteses previstas em lei ordinária, tais como quando o documento apresentar rasura ou tiver indício de falsificação.",
    explicacao: "GABARITO: CERTO. Art. 5º, LVIII, da CF/88 regulamentado pela Lei nº 12.037/2009 (hipóteses de identificação criminal mesmo com documento civil).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-010",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "No ordenamento constitucional brasileiro, não haverá penas de morte, salvo em caso de guerra declarada, nos termos do art. 84, XIX, da Constituição.",
    explicacao: "GABARITO: CERTO. Art. 5º, XLVII, 'a', da CF admite pena de morte unicamente em caso de guerra declarada.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11 to 20: Artigo 144 da CF/88 - Segurança Pública
  {
    idSlug: "b10-const-01-011",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Polícia Federal, instituída por lei como órgão permanente, organizado e mantido pela União e estruturado em carreira, destina-se a exercer, com exclusividade, as funções de polícia judiciária da União.",
    explicacao: "GABARITO: CERTO. Art. 144, § 1º, IV, da CF/88.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-012",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Segundo a jurisprudência consolidada do Supremo Tribunal Federal, o rol de órgãos de segurança pública elencados no art. 144 da Constituição Federal é de natureza:",
    explicacao: "GABARITO: D. O rol do art. 144 é taxativo (numerus clausus) no âmbito dos Estados e DF, sendo vedado aos legisladores estaduais criar novas polícias ou atribuir status de órgão de segurança pública a entidades não previstas na CF.",
    alternativas: [
      { texto: "Meramente exemplificativa, podendo os Estados criar novos órgãos policiais livremente.", correta: false },
      { texto: "Programática, dependendo de lei ordinária para definir sua existência.", correta: false },
      { texto: "Supletiva às diretrizes municipais de fiscalização urbana.", correta: false },
      { texto: "Taxativa (numerus clausus), de observância obrigatória pelos Estados-membros.", correta: true },
      { texto: "Transitória até a unificação completa das forças armadas e de segurança.", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-013",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "À Polícia Rodoviária Federal, órgão permanente estruturado em carreira, compete, na forma da lei, o patrulhamento ostensivo das rodovias e ferrovias federais.",
    explicacao: "GABARITO: ERRADO. À PRF compete o patrulhamento das rodovias federais (art. 144, § 2º). O patrulhamento das ferrovias federais cabe à Polícia Ferroviária Federal (art. 144, § 3º).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-const-01-014",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Às polícias civis, dirigidas por delegados de polícia de carreira, incumbem, ressalvada a competência da União, as funções de polícia judiciária e a apuração de infrações penais, exceto as militares.",
    explicacao: "GABARITO: CERTO. Art. 144, § 4º, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-015",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A Polícia Militar e o Corpo de Bombeiros Militar são forças auxiliares e reserva do Exército, subordinando-se, juntamente com a Polícia Civil e a Polícia Penal estadual, aos Governadores dos Estados e do Distrito Federal.",
    explicacao: "GABARITO: CERTO. Art. 144, § 6º, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 16 to 25: Defesa do Estado, Direitos Políticos e Administração Pública
  {
    idSlug: "b10-const-01-016",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Conforme recente jurisprudência do STF (ADPF 995 e Tema 1019), as Guardas Municipais:",
    explicacao: "GABARITO: C. O STF pacificou que as Guardas Municipais integram o Sistema de Segurança Pública e possuem atribuições de policiamento preventivo e comunitário na proteção de bens, serviços, instalações e da população local.",
    alternativas: [
      { texto: "São proibidas de portar arma de fogo em qualquer hipótese.", correta: false },
      { texto: "Possuem competência privativa para investigação de crimes comuns de trânsito.", correta: false },
      { texto: "Integram o Sistema de Segurança Pública, exercendo atividades de policiamento preventivo e comunitário.", correta: true },
      { texto: "Subordinam-se diretamente ao Comando Militar do Exército.", correta: false },
      { texto: "São equiparadas formalmente a órgãos da magistratura municipal.", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-017",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Emenda Constitucional nº 104/2019 criou a Polícia Penal (federal, estaduais e distrital), atribuindo-lhe a função institucional de segurança dos estabelecimentos penais e vinculando-a ao órgão administrador do sistema penal da respectiva unidade federativa.",
    explicacao: "GABARITO: CERTO. Art. 144, § 5º-A, da CF.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-018",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "2b0a1f05-8be5-5d9c-850d-df6948ad8557",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal fixou a tese de que o exercício do direito de greve sob qualquer forma ou modalidade é vedado aos policiais civis e a todos os servidores públicos que atuem diretamente na área de segurança pública.",
    explicacao: "GABARITO: CERTO. Tema 541/STF (ARE 654.432): é vedada a greve a todas as carreiras de segurança pública (art. 144).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-019",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A manifestação do pensamento é livre a todos os cidadãos, sendo expressamente vedado o anonimato na ordem constitucional brasileira.",
    explicacao: "GABARITO: CERTO. Art. 5º, IV, da CF: 'é livre a manifestação do pensamento, sendo vedado o anonimato'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-020",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O mandado de segurança coletivo pode ser validamente impetrado por partido político:",
    explicacao: "GABARITO: B. Art. 5º, LXX, 'a', da CF: partido político com representação no Congresso Nacional (pelo menos um Deputado ou Senador).",
    alternativas: [
      { texto: "Apenas se possuir registro no TSE há mais de cinco anos.", correta: false },
      { texto: "Com representação no Congresso Nacional.", correta: true },
      { texto: "Apenas quando coligado com outras três agremiações partidárias.", correta: false },
      { texto: "Somente se detiver a maioria absoluta da Câmara dos Deputados.", correta: false },
      { texto: "Desde que autorizado expressamente por decisão unânime do STF.", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-021",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Durante a vigência do Estado de Defesa decretado pelo Presidente da República, a prisão por crime contra o Estado, determinada pelo executor da medida, será por este comunicada imediatamente ao juiz competente, que a relaxará, se não for legal, facultado ao preso requerer exame de corpo de delito.",
    explicacao: "GABARITO: CERTO. Art. 136, § 3º, I, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-022",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A criação de associações e, na forma da lei, a de cooperativas independem de autorização estatal, sendo vedada a interferência estatal em seu funcionamento.",
    explicacao: "GABARITO: CERTO. Art. 5º, XVIII, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-023",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O preso tem direito à identificação dos responsáveis por sua prisão ou por seu interrogatório policial, como garantia de transparência e inibição de eventuais abusos de autoridade.",
    explicacao: "GABARITO: CERTO. Art. 5º, LXIV, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-024",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A lei penal não retroagirá, salvo para beneficiar o réu (princípio da irretroatividade da lei penal mais gravosa).",
    explicacao: "GABARITO: CERTO. Art. 5º, XL, da Constituição Federal.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-const-01-025",
    disciplina_id: "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    assunto_id: "9753e899-73fb-54f6-8c4d-616c68e14674",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Conforme o art. 5º, XLIII, da CF/88, a prática da tortura, o tráfico ilícito de entorpecentes e drogas afins, o terrorismo e os crimes hediondos são considerados pela Constituição como inafiançáveis e insuscetíveis de:",
    explicacao: "GABARITO: D. Art. 5º, XLIII, da CF: inafiançáveis e insuscetíveis de graça ou anistia (3TH). Obs.: indulto é equiparado a graça pelo STF.",
    alternativas: [
      { texto: "Prescrição e decadência.", correta: false },
      { texto: "Progressão de regime prisional.", correta: false },
      { texto: "Julgamento em primeira instância.", correta: false },
      { texto: "Graça ou anistia.", correta: true },
      { texto: "Defesa técnica por advogado.", correta: false },
    ],
  },
];

const fileConstContent = `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const const01Questoes = ${JSON.stringify(const01, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, "const_01.mjs"), fileConstContent, "utf8");
console.log("const_01.mjs gerado com sucesso! (25 questões)");
