// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 23

export const m17_questoes = [
  {
    "id": "c41bfcca-202f-5bee-b056-ae2df73464dc",
    "idSlug": "l13-info-sec-001-principios-seguranca-nao-repudio-assinatura",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O princípio da irretratabilidade ou não repúdio na segurança da informação garante que o emissor de uma mensagem ou autor de uma transação digital não possa negar falsamente a sua autoria, sendo tipicamente implementado por meio de assinaturas digitais amparadas em certificados de chave pública emitidos por Autoridades Certificadoras confiáveis.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A assinatura digital associa a chave privada do signatário ao resumo criptográfico do documento, garantindo autenticidade, integridade e não repúdio (irretratabilidade).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1bbb2fdf10ea3d42c0ea9231c65d0d8eb7b1d685ce9af43ee93d59427d1dfc8f",
    "conceito_principal": "Princípios da Segurança da Informação: Não repúdio / Irretratabilidade",
    "habilidade_cobrada": "Compreender a aplicação prática da assinatura digital na garantia de não repúdio",
    "tese_ou_regra": "O não repúdio impede a negação de autoria em comunicações e transações digitais",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5df308fd-7ec5-5741-960a-6271fd7eae13",
        "questao_id": "c41bfcca-202f-5bee-b056-ae2df73464dc",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "07a5a562-81c5-5c5c-b7af-ee6242526b28",
        "questao_id": "c41bfcca-202f-5bee-b056-ae2df73464dc",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bb7f0357-3cfd-5184-ad61-f555a798aafb",
    "idSlug": "l13-info-sec-002-criptografia-simetrica-assimetrica-aes-rsa",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na criptografia assimétrica, utilizam-se pares de chaves matematicamente correlacionadas (chave pública e chave privada); quando o objetivo é assegurar o sigilo e a confidencialidade da comunicação policial, o remetente cifra a mensagem utilizando a chave pública do destinatário, a qual só poderá ser decifrada mediante o uso da chave privada exclusiva deste último.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Para confidencialidade em criptografia assimétrica: cifra-se com a chave pública do destinatário e decifra-se com a chave privada correspondente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "63b69b1d5d0729e017ea067e398db55cabd0c454f7a88194c81ad8737af4c463",
    "conceito_principal": "Criptografia Assimétrica para garantia de confidencialidade",
    "habilidade_cobrada": "Identificar o mecanismo correto de cifragem e decifragem com chaves públicas e privadas",
    "tese_ou_regra": "Mensagens confidenciais são cifradas com a chave pública do destinatário",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "917b145a-a3f2-5b67-bccc-da309ee35345",
        "questao_id": "bb7f0357-3cfd-5184-ad61-f555a798aafb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "75400bb7-f900-50ea-8198-687fa7d77ab1",
        "questao_id": "bb7f0357-3cfd-5184-ad61-f555a798aafb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0f711d3d-39d6-542e-bc82-de07415e0af8",
    "idSlug": "l13-info-sec-003-ransomware-extorsao-cifragem-sequestro-dados",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O ransomware é um tipo de malware malicioso que infecta sistemas corporativos e estações de trabalho, realizando a cifragem não autorizada dos arquivos do usuário ou o bloqueio do acesso ao sistema operacional, exigindo subsequentemente o pagamento de resgate (geralmente em criptomoedas) para o fornecimento da respectiva chave de decifragem.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Conceito exato de ransomware (sequestro digital de dados mediante criptografia e cobrança de resgate).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c6360cf066d702cf802593abaaae574bce79af81bd6a40f293c6fa04e1fac44f",
    "conceito_principal": "Malwares e ameaças cibernéticas: Ransomware",
    "habilidade_cobrada": "Reconhecer as características operacionais e o modus operandi de ataques de ransomware",
    "tese_ou_regra": "Ransomware sequestra arquivos corporativos mediante criptografia forçada e extorsão",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "8b65f35b-a8bf-54a8-aca4-3dc0766831d2",
        "questao_id": "0f711d3d-39d6-542e-bc82-de07415e0af8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "35fb053d-66b7-5fae-979a-adf9d27b76e8",
        "questao_id": "0f711d3d-39d6-542e-bc82-de07415e0af8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ab27f14a-a54d-5b02-af9d-971221358e9f",
    "idSlug": "l13-info-sec-004-ataque-ddos-botnet-esgotamento-recursos",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Os ataques de negação de serviço distribuídos (DDoS) empregam frequentemente redes de dispositivos previamente comprometidos (botnets ou computadores zumbis) para inundar servidores ou enlaces de comunicação com volumes massivos de requisições ilegítimas, com o objetivo precípuo de esgotar recursos computacionais e violar a disponibilidade dos serviços digitais atingidos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Ataques DDoS atacam diretamente o pilar da disponibilidade, sobrecarregando a infraestrutura por meio de tráfego distribuído.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3d9238b2732cafa0993563ecb3957d621e639a344ef816102e74ca30ffe6a7fc",
    "conceito_principal": "Ataque de Negação de Serviço Distribuído (DDoS) e violação de disponibilidade",
    "habilidade_cobrada": "Identificar as táticas de botnets em ataques cibernéticos contra serviços governamentais",
    "tese_ou_regra": "O ataque DDoS satura links e servidores, comprometendo a disponibilidade de sistemas",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "82d29bc9-7c45-5d63-8aae-36f58c733e0e",
        "questao_id": "ab27f14a-a54d-5b02-af9d-971221358e9f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "4f7ba789-8797-53c1-a409-948eaf066bf7",
        "questao_id": "ab27f14a-a54d-5b02-af9d-971221358e9f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
    "idSlug": "l13-info-sec-005-protocolos-transporte-tcp-vs-udp",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Na arquitetura TCP/IP, a camada de transporte é responsável pela comunicação fim a fim entre processos. A respeito dos protocolos TCP (Transmission Control Protocol) e UDP (User Datagram Protocol), assinale a afirmativa correta.",
    "explicacao": "GABARITO: C. O TCP é orientado à conexão, realiza o handshake em 3 vias (SYN, SYN-ACK, ACK), oferece controle de fluxo, retransmissão de pacotes perdidos e entrega ordenada. O UDP é não orientado à conexão, sem garantia de entrega, priorizando velocidade e baixa latência (adequado para DNS, VoIP e streaming).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9cb6554f250d1f42876295a33ae4fc3afc0763f650541da9adb316417042b2ac",
    "conceito_principal": "Diferenciação técnica entre os protocolos TCP e UDP na camada de transporte",
    "habilidade_cobrada": "Comparar os mecanismos de confiabilidade, controle de fluxo e handshake da pilha TCP/IP",
    "tese_ou_regra": "TCP provê transporte confiável e orientado à conexão; UDP provê transporte rápido sem handshake",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "4801da9c-7df9-5750-a9c9-5f0471541af7",
        "questao_id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
        "letra": "A",
        "texto": "O protocolo UDP é orientado à conexão e realiza o three-way handshake antes de transmitir dados, garantindo a integridade sequencial dos datagramas.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. O UDP é não orientado à conexão e não faz handshake."
      },
      {
        "id": "9438ac0c-07b1-53e0-8012-a6d33a0fde14",
        "questao_id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
        "letra": "B",
        "texto": "O protocolo TCP não possui mecanismo de controle de fluxo nem de retransmissão de pacotes corrompidos, sendo inadequado para transferência de arquivos críticos.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O TCP garante entrega confiável com controle de fluxo e retransmissão."
      },
      {
        "id": "bfe3792d-d4f4-5d5d-9098-383dfed3420d",
        "questao_id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
        "letra": "C",
        "texto": "O TCP estabelece uma conexão confiável com confirmação de entrega e controle de congestionamento, enquanto o UDP é não orientado à conexão e prioriza menor latência na transmissão.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Características essenciais que diferenciam TCP de UDP."
      },
      {
        "id": "82064e03-8bd8-513b-967b-ad3ea496ce02",
        "questao_id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
        "letra": "D",
        "texto": "Tanto o TCP quanto o UDP operam exclusivamente na camada de aplicação do modelo de referência OSI.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Operam na camada de transporte (camada 4 do OSI)."
      },
      {
        "id": "4218e2f8-a46e-5f15-bbaf-ca5b1bba0cf9",
        "questao_id": "662ef59e-2f8a-5b60-80ae-aa78c32c821c",
        "letra": "E",
        "texto": "O protocolo de resolução de nomes DNS opera exclusivamente sobre TCP na porta 80.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O DNS opera tipicamente sobre UDP na porta 53."
      }
    ]
  },
  {
    "id": "0ccda3ea-aaad-5261-ba37-b828f3dd7471",
    "idSlug": "l13-info-sec-006-firewall-stateful-inspection-tabela-estados",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Diferentemente dos firewalls stateless de filtragem simples de pacotes (que analisam apenas cabeçalhos isolados), os firewalls com inspeção de estados (stateful inspection) mantêm uma tabela de controle do estado das conexões ativas, permitindo avaliar se um pacote de dados pertence a uma sessão legítima previamente estabelecida antes de autorizar sua passagem.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Firewalls stateful acompanham o ciclo de vida completo da conexão (ex.: SYN, ESTABLISHED, FIN), bloqueando pacotes forjados que não pertençam a fluxos autorizados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ffc620b95e2a78c870e4c51e6ef45d0ab78ed19510c33284fe594ee420b54b34",
    "conceito_principal": "Firewall com inspeção de estados (Stateful Inspection)",
    "habilidade_cobrada": "Analisar as diferenças funcionais entre filtragem estática e dinâmica de pacotes de rede",
    "tese_ou_regra": "O firewall stateful monitora o contexto e a tabela de sessões ativas para filtrar o tráfego",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "079955a4-d3da-5aa6-9961-61e697c58bc6",
        "questao_id": "0ccda3ea-aaad-5261-ba37-b828f3dd7471",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c66fc658-f893-59cf-8ff8-86979bd78882",
        "questao_id": "0ccda3ea-aaad-5261-ba37-b828f3dd7471",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5fe4a530-8ea9-5def-b389-129c631700db",
    "idSlug": "l13-info-sec-007-hash-sha256-resumo-unidirecional-integridade",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Funções de hash criptográfico, como o SHA-256, são algoritmos unidirecionais (one-way) que transformam uma entrada de dados de comprimento arbitrário em um resumo de tamanho fixo (digest), de modo que qualquer alteração mínima no arquivo original gera um hash substancialmente distinto (efeito avalanche), permitindo a verificação da integridade das evidências digitais.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O hash criptográfico é essencial na computação forense e segurança da informação para garantir a integridade e detectar adulterações.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "132dc041a02a01a1e50dc395754388088196a5a1026eeb9ab03c3b2eddc03484",
    "conceito_principal": "Funções de Hash Criptográfico (SHA-256) e preservação da integridade forense",
    "habilidade_cobrada": "Reconhecer o funcionamento e as propriedades dos algoritmos de hashing em perícia digital",
    "tese_ou_regra": "O hash criptográfico gera saída de tamanho fixo e é computacionalmente irreversível",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "89beb939-9dbf-5251-aac6-e371d933f7a2",
        "questao_id": "5fe4a530-8ea9-5def-b389-129c631700db",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6ee4cfc0-713e-5bff-b091-44747451479e",
        "questao_id": "5fe4a530-8ea9-5def-b389-129c631700db",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "98871b7d-f9f2-54cf-b88c-7aceceed2e20",
    "idSlug": "l13-info-sec-008-vpn-tunelamento-ipsec-comunicacao-segura",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Uma Rede Privada Virtual (VPN) permite criar uma conexão segura e criptografada (túnel) através de uma rede pública desprotegida, como a Internet, viabilizando o tráfego confidencial e autenticado de dados policiais entre unidades remotas e servidores centrais da corporação.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A VPN utiliza tunelamento e criptografia para prover confidencialidade e integridade através de redes públicas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "87284ddaca155a50405976506f28748acf886b49a0ec9e3e26bf0d30e5b1becc",
    "conceito_principal": "Rede Privada Virtual (VPN) e tunelamento seguro de dados",
    "habilidade_cobrada": "Identificar os mecanismos de acesso remoto seguro em redes corporativas policiais",
    "tese_ou_regra": "A VPN estabelece um canal criptografado sobre redes públicas para tráfego seguro",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "5894a3aa-aee4-5de7-9d1e-7c71d18c9b66",
        "questao_id": "98871b7d-f9f2-54cf-b88c-7aceceed2e20",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "31228d17-8e0b-5f31-a3f1-bbfe2fc5aea0",
        "questao_id": "98871b7d-f9f2-54cf-b88c-7aceceed2e20",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f88ea17d-a16a-5df8-b9f7-5cea0024c5a4",
    "idSlug": "l13-info-sec-009-phishing-engenharia-social-spear-phishing",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O spear phishing é uma variante dirigida e personalizada do phishing tradicional na qual os criminosos utilizam dados previamente coletados sobre um alvo específico (como um policial ou autoridade pública) para criar mensagens altamente convincentes, buscando induzir a vítima a clicar em links maliciosos ou revelar credenciais institucionais de acesso.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Spear phishing é ataque direcionado com engenharia social avançada e contextualização específica para a vítima.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4cd31cd431f16a426f3ff959561d69bdd5bfea8a53a43ae2e2cdd630cc957772",
    "conceito_principal": "Engenharia Social e técnicas de Spear Phishing",
    "habilidade_cobrada": "Distinguir as variantes de ataques de phishing em ambientes corporativos e investigativos",
    "tese_ou_regra": "O spear phishing customiza mensagens com dados reais da vítima para elevar a taxa de sucesso da fraude",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "71863e92-cd33-5ad2-ae96-a4042ad4b015",
        "questao_id": "f88ea17d-a16a-5df8-b9f7-5cea0024c5a4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "db1a3f44-930e-5452-a1ef-a1743a40ebdf",
        "questao_id": "f88ea17d-a16a-5df8-b9f7-5cea0024c5a4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
    "idSlug": "l13-info-sec-010-modelos-nuvem-iaas-paas-saas",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "A computação em nuvem (Cloud Computing) oferece serviços estruturados em diferentes modelos operacionais. No modelo de Infraestrutura como Serviço (IaaS), qual é o escopo de responsabilidade típico do cliente usuário?",
    "explicacao": "GABARITO: B. No modelo IaaS (ex.: AWS EC2, Azure VMs), o provedor gerencia a infraestrutura física, virtualização e rede; o cliente é responsável por instalar, configurar e gerenciar o sistema operacional, middlewares, bancos de dados, aplicações e controles de segurança.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e82e37aa607f27e026adf5d13417301ac1a7b90d337d2d707115b14fcd4e6663",
    "conceito_principal": "Modelos de serviço em Cloud Computing: IaaS, PaaS e SaaS",
    "habilidade_cobrada": "Diferenciar a matriz de responsabilidades compartilhadas nos modelos de nuvem",
    "tese_ou_regra": "No IaaS o cliente administra sistemas operacionais, softwares e configurações de segurança",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c72c5f25-7fee-5655-b423-17c074d1b805",
        "questao_id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
        "letra": "A",
        "texto": "O cliente utiliza apenas a interface web de um aplicativo final, sem acesso ao sistema operacional ou à configuração de servidores.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Essa é a definição do modelo SaaS (Software as a Service)."
      },
      {
        "id": "a4e59e91-3b43-5416-adb4-2476b3504d14",
        "questao_id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
        "letra": "B",
        "texto": "O cliente aluga recursos básicos de processamento, armazenamento e rede, cabendo a ele instalar e manter o sistema operacional, aplicativos e regras de segurança.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. No IaaS a responsabilidade do cliente abrange do SO até a camada de aplicação."
      },
      {
        "id": "8d2af7ef-a074-53aa-80f0-a508998579ca",
        "questao_id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
        "letra": "C",
        "texto": "O provedor de nuvem assume a responsabilidade exclusiva pelo desenvolvimento do código-fonte e pelas senhas dos usuários finais.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A aplicação e o controle de acesso pertencem ao contratante."
      },
      {
        "id": "26a365e7-61b5-5621-b30c-503e2f745f66",
        "questao_id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
        "letra": "D",
        "texto": "O cliente recebe apenas um ambiente de execução gerenciado (runtime), sem controle sobre portas de rede ou sistemas de arquivos virtuais.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Essa é a característica do PaaS (Platform as a Service)."
      },
      {
        "id": "2bba8df5-6fad-5a97-a4a0-b353ad019d80",
        "questao_id": "040b4481-311f-5c77-ac50-11b1e1e116c8",
        "letra": "E",
        "texto": "O modelo IaaS não admite o provisionamento de máquinas virtuais com sistemas operacionais Linux ou Windows.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Máquinas virtuais heterogêneas são a base do IaaS."
      }
    ]
  },
  {
    "id": "0de92383-c0c0-58aa-ae4d-ec8bc9adcd54",
    "idSlug": "l13-info-sec-011-ids-vs-ips-prevencao-deteccao-intrusao",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Enquanto um Sistema de Detecção de Intrusão (IDS) opera de forma passiva, monitorando o tráfego de rede e gerando alertas quando identifica padrões de atividade maliciosa, um Sistema de Prevenção de Intrusão (IPS) atua em linha (in-line), sendo capaz de bloquear ativamente e em tempo real os pacotes de dados suspeitos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. IDS detecta e alerta (passivo); IPS detecta, alerta e reage bloqueando o tráfego malicioso em tempo real (ativo).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9b0c52b260465b4962c2cc1bb30f79ed00414b0d9f6ab1f82bd3c556590c1a2b",
    "conceito_principal": "Sistemas de Segurança de Rede: IDS (Detecção) vs IPS (Prevenção)",
    "habilidade_cobrada": "Distinguir a postura operacional passiva do IDS da postura ativa em linha do IPS",
    "tese_ou_regra": "O IPS bloqueia ativamente ameaças em tempo real, enquanto o IDS apenas sinaliza alertas",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "aba86da0-21e6-5720-87a2-0a2704d85a71",
        "questao_id": "0de92383-c0c0-58aa-ae4d-ec8bc9adcd54",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b82e69c5-8aec-5224-8f88-919a39fb9db6",
        "questao_id": "0de92383-c0c0-58aa-ae4d-ec8bc9adcd54",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "cfad1362-5df0-55df-b31e-37ba17664ec2",
    "idSlug": "l13-info-sec-012-switch-vs-roteador-camada-osi-mac-ip",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em uma rede local de computadores, o switch opera tipicamente na camada de enlace (camada 2 do modelo OSI), encaminhando quadros (frames) com base nos endereços físicos MAC, enquanto o roteador opera na camada de rede (camada 3), encaminhando pacotes com base nos endereços lógicos IP entre diferentes sub-redes.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Switch camada 2 comuta frames via tabela MAC; Roteador camada 3 comuta e roteia pacotes via tabela de roteamento IP.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c3d3199cd23aa7207657b8efe1857f006d778ba16403e61a9aaaeca182aab773",
    "conceito_principal": "Dispositivos de rede: Switch (Camada 2 / MAC) vs Roteador (Camada 3 / IP)",
    "habilidade_cobrada": "Correlacionar equipamentos de conectividade com as respectivas camadas do modelo OSI",
    "tese_ou_regra": "Switches operam com endereços MAC na camada 2; roteadores operam com endereços IP na camada 3",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "a1654688-20d7-51f6-b96e-51064c94b005",
        "questao_id": "cfad1362-5df0-55df-b31e-37ba17664ec2",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b83c7285-f24d-53ab-b208-f52cb0100b72",
        "questao_id": "cfad1362-5df0-55df-b31e-37ba17664ec2",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d506b18c-0faa-5c80-b913-723fce489472",
    "idSlug": "l13-info-sec-013-worm-vs-virus-autorreplicacao-independente",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Ao contrário dos vírus tradicionais, que necessitam de um arquivo hospedeiro e da ação explícita do usuário para serem executados e propagados, os worms são programas autônomos capazes de se autorreplicar automaticamente através de redes de computadores, explorando vulnerabilidades de sistemas operacionais e serviços.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A distinção clássica: vírus precisa de hospedeiro/execução humana; worm é autônomo e propaga-se sozinho pela rede.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "309bcf6e78c910973142817e8723108d35258a64e366c08456aa86ab18f9677f",
    "conceito_principal": "Diferença conceitual entre Vírus e Worm",
    "habilidade_cobrada": "Reconhecer os mecanismos de propagação autônoma de malwares em redes corporativas",
    "tese_ou_regra": "Worms propagam-se ativamente pela rede sem necessidade de hospedeiro ou ação do usuário",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2094b5f8-3818-5979-9707-cba2fec04b5b",
        "questao_id": "d506b18c-0faa-5c80-b913-723fce489472",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "4c65182b-1746-50b6-b21c-f6e601501afc",
        "questao_id": "d506b18c-0faa-5c80-b913-723fce489472",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9988526e-b19a-5bdb-9a86-4a54d5cb0d42",
    "idSlug": "l13-info-sec-014-protocolos-email-smtp-pop3-imap",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na arquitetura de correio eletrônico, o protocolo SMTP é utilizado para o envio e transferência de mensagens entre servidores, enquanto o protocolo IMAP permite que o cliente de e-mail acesse e sincronize pastas e mensagens diretamente no servidor de forma bidirecional, permitindo múltiplos acessos simultâneos sem baixar compulsoriamente os dados para o disco local.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. SMTP = envio; IMAP = sincronização bidirecional no servidor; POP3 = download local com remoção típica do servidor.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "40e48643d827dd96c715ff9f5d030c8f9d61c9b981d2caf695207d6a2df07ac8",
    "conceito_principal": "Protocolos de Correio Eletrônico: SMTP, IMAP e POP3",
    "habilidade_cobrada": "Identificar as funções e características operacionais dos protocolos de e-mail",
    "tese_ou_regra": "SMTP realiza o envio de mensagens; IMAP sincroniza caixas de correio remotamente no servidor",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "8a1ff7f6-1be1-50c3-870f-aa7d2ee600bf",
        "questao_id": "9988526e-b19a-5bdb-9a86-4a54d5cb0d42",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "28e3ff40-8015-5e38-b18d-bfa1498926b2",
        "questao_id": "9988526e-b19a-5bdb-9a86-4a54d5cb0d42",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
    "idSlug": "l13-info-sec-015-certificacao-digital-icp-brasil-a1-a3",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "No âmbito da Infraestrutura de Chaves Públicas Brasileira (ICP-Brasil), os certificados digitais do tipo A (Assinatura) possuem padrões distintos quanto ao armazenamento da chave privada. A esse respeito, assinale a afirmativa correta.",
    "explicacao": "GABARITO: A. O certificado digital A1 tem chave privada gerada e armazenada em software (disco rígido/computador) com validade máxima de 1 ano. O certificado A3 armazena a chave privada em hardware criptográfico inviolável (token USB ou smartcard) com validade de até 3 ou 5 anos, não permitindo a exportação da chave privada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a793506299fd57d11dae6c776365cbcdaa7122a7ce7377f14b25ea5c36ff79e9",
    "conceito_principal": "Certificados Digitais ICP-Brasil: Padrões A1 e A3",
    "habilidade_cobrada": "Comparar a segurança e o armazenamento de chaves criptográficas na ICP-Brasil",
    "tese_ou_regra": "Certificados A1 residem em software; certificados A3 residem em hardware criptográfico seguro",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0dc7f9fa-8ad1-58d1-8f0b-587cbb290d15",
        "questao_id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
        "letra": "A",
        "texto": "O certificado A1 armazena a chave privada em software no próprio computador, enquanto o certificado A3 utiliza hardware criptográfico portátil (token ou cartão inteligente) inviolável.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Definição regulamentar dos padrões A1 e A3 na ICP-Brasil."
      },
      {
        "id": "f41ad473-3070-5b73-a772-810a4d6d0764",
        "questao_id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
        "letra": "B",
        "texto": "O certificado A3 é armazenado exclusivamente na nuvem pública em formato de texto sem proteção por PIN ou senha.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O A3 reside em token físico protegido por senha/PIN."
      },
      {
        "id": "9352673d-f09f-5968-9f11-97461eb610cd",
        "questao_id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
        "letra": "C",
        "texto": "O certificado A1 possui validade perpétua e não pode ser revogado por Autoridades Certificadoras.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Validade típica de 1 ano e sujeito à revogação via LCR."
      },
      {
        "id": "bed5adcd-5e55-5a28-b395-a745c8296390",
        "questao_id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
        "letra": "D",
        "texto": "A assinatura digital realizada com certificado A1 não possui validade jurídica no território nacional.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Ambas possuem plena validade jurídica pela MP 2.200-2/2001."
      },
      {
        "id": "cb9fc2ee-24a4-5e0a-9405-74472cfcaf32",
        "questao_id": "de35d274-7e92-5d91-8d13-d9d21b681bf0",
        "letra": "E",
        "texto": "Certificados do tipo A destinam-se exclusivamente à cifragem de links de comunicação sigilosa (SSL/TLS) em servidores web.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Tipo A é para assinatura; tipo S é para sigilo/criptografia de dados."
      }
    ]
  },
  {
    "id": "c2e757a7-9e0f-5f67-93ac-b2cc4056fd95",
    "idSlug": "l13-info-sec-016-ipv4-vs-ipv6-tamanho-enderecos-esgotamento",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O protocolo IPv4 utiliza endereços de 32 bits, representados convencionalmente em notação decimal por quatro octetos separados por pontos, ao passo que o IPv6 utiliza endereços de 128 bits, grafados em notação hexadecimal separada por dois-pontos, expandindo exponencialmente a quantidade de dispositivos endereçáveis na Internet.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. IPv4 = 32 bits (cerca de 4,3 bilhões de endereços); IPv6 = 128 bits (3,4 x 10^38 endereços).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b650acbb296d914302562f1a08662f4f70dbd0ecf3f9234ab4899d0caa525787",
    "conceito_principal": "Arquitetura de Endereçamento IP: IPv4 (32 bits) vs IPv6 (128 bits)",
    "habilidade_cobrada": "Identificar as diferenças estruturais e dimensionais entre IPv4 e IPv6",
    "tese_ou_regra": "IPv4 possui 32 bits e IPv6 possui 128 bits em representação hexadecimal",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "8fb68704-afb6-5719-a41a-7e0a3864d983",
        "questao_id": "c2e757a7-9e0f-5f67-93ac-b2cc4056fd95",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7f061ed8-5cec-5925-9b6b-d428b01788b2",
        "questao_id": "c2e757a7-9e0f-5f67-93ac-b2cc4056fd95",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5d8b9ffd-6cbb-5f86-ade7-2b2e0c9491ce",
    "idSlug": "l13-info-sec-017-spyware-keylogger-screenlogger-captura-dados",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Os programas espiões (spywares) do tipo keylogger registram as teclas digitadas pelo usuário no teclado físico do computador, ao passo que os screenloggers realizam capturas periódicas de tela (prints) na região em torno do cursor do mouse, visando burlar teclados virtuais bancários para roubo de senhas.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Keylogger captura toques de teclado; screenlogger captura imagens da tela e cliques do mouse.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d5895d6e7517543a63df237bc74dd19ee334ab14bf9f2624eca0fe8e3282e68a",
    "conceito_principal": "Spywares: Keylogger vs Screenlogger",
    "habilidade_cobrada": "Identificar as formas de espionagem digital e furto de credenciais por spywares",
    "tese_ou_regra": "Keyloggers monitoram teclas digitadas; screenloggers capturam imagens da tela nos cliques",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "a22e9db2-9a62-5d91-b6c5-eafaea7c5898",
        "questao_id": "5d8b9ffd-6cbb-5f86-ade7-2b2e0c9491ce",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f61fbbc7-b671-5f80-91c7-d69c1e9fb74f",
        "questao_id": "5d8b9ffd-6cbb-5f86-ade7-2b2e0c9491ce",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "68f9d48e-46f1-5f8b-b538-6888be241ce3",
    "idSlug": "l13-info-sec-018-dns-resolucao-nomes-porta-53-udp",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O Domain Name System (DNS) é um serviço hierárquico e distribuído responsável por traduzir nomes de domínio legíveis por humanos (como www.pf.gov.br) nos respectivos endereços IP numéricos utilizados pelo roteamento da Internet, utilizando preferencialmente a porta 53 sobre o protocolo UDP em suas consultas habituais.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. DNS converte nomes FQDN em endereços IP, operando primordialmente em UDP porta 53 para consultas rápidas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "01da0f1594fd9be857e01527c717483cb08d1b3ea0967bd1f860e36c88e95af2",
    "conceito_principal": "Serviço de Resolução de Nomes DNS e sua camada de transporte",
    "habilidade_cobrada": "Compreender a dinâmica de tradução de domínios e a infraestrutura básica da Web",
    "tese_ou_regra": "O DNS mapeia nomes em endereços IP utilizando primordialmente UDP na porta 53",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "78f57d3d-7386-5d4e-841b-e9784356a9f1",
        "questao_id": "68f9d48e-46f1-5f8b-b538-6888be241ce3",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "eea1773a-bbba-590c-8799-6378ff58592d",
        "questao_id": "68f9d48e-46f1-5f8b-b538-6888be241ce3",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9abad2c4-d2a8-5338-a65f-9572911373dc",
    "idSlug": "l13-info-sec-019-trojan-cavalo-troia-carga-util-oculta",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O Trojan Horse (Cavalo de Troia) apresenta-se à vítima disfarçado de aplicativo legítimo, útil ou inofensivo (como um jogo, leitor de PDF ou protetor de tela), mas embute funções ocultas maliciosas que são ativadas em segundo plano para abrir portas de comunicação (backdoors) e permitir o controle remoto do computador invadido.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Conceito clássico de Cavalo de Troia: software aparentemente benigno que esconde carga útil maliciosa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3173e14cd91f312768705a314cb6297160ebb4777b7e28cc0277759fc8aadb8c",
    "conceito_principal": "Cavalo de Troia (Trojan Horse) e Backdoors",
    "habilidade_cobrada": "Identificar o mecanismo de disfarce e instalação de portas dos fundos em estações policiais",
    "tese_ou_regra": "O Trojan disfarça-se de programa inofensivo para executar comandos maliciosos e abrir backdoors",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "c54ee270-bceb-5c66-b475-5683d586ef7f",
        "questao_id": "9abad2c4-d2a8-5338-a65f-9572911373dc",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "53360216-b68b-5661-bb26-8b03313b78a9",
        "questao_id": "9abad2c4-d2a8-5338-a65f-9572911373dc",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
    "idSlug": "l13-info-sec-020-https-tls-handshake-cifragem-hibrida",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Ao navegar em um portal institucional seguro utilizando o protocolo HTTPS (porta 443 com TLS 1.3), como se processa a segurança da comunicação entre o navegador do policial e o servidor web?",
    "explicacao": "GABARITO: D. O HTTPS utiliza um sistema criptográfico híbrido: na fase de handshake TLS, utiliza criptografia assimétrica e certificados digitais para autenticar o servidor e negociar uma chave secreta de sessão de forma segura; estabelecida a sessão, os dados trafegados são cifrados com criptografia simétrica (como AES-GCM), que é muito mais rápida e eficiente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9829c4882e07a0791afdeedff109aed850c883758076b60c8ecbd3f4d22345e6",
    "conceito_principal": "Protocolo HTTPS / TLS e modelo de criptografia híbrida na Web",
    "habilidade_cobrada": "Analisar o ciclo de negociação e estabelecimento de túneis seguros via TLS",
    "tese_ou_regra": "O TLS combina criptografia assimétrica no handshake e criptografia simétrica na sessão",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "7be3f9b6-3684-5028-9f95-a700e625b06c",
        "questao_id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
        "letra": "A",
        "texto": "Todas as páginas e arquivos transmitidos são cifrados exclusivamente com a chave privada da autoridade certificadora sem nenhuma chave de sessão.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Chaves privadas de ACs não participam da cifragem do corpo da mensagem."
      },
      {
        "id": "78647633-f4ce-516d-b07e-1f6c916564ad",
        "questao_id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
        "letra": "B",
        "texto": "O HTTPS dispensa o uso de certificados digitais, confiando unicamente no endereço IP físico da placa de rede.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O TLS exige certificado digital X.509 para autenticação do servidor."
      },
      {
        "id": "a33dd602-ad01-5fa9-ac53-1e4a6005524f",
        "questao_id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
        "letra": "C",
        "texto": "A transmissão ocorre em texto claro, sendo a criptografia ativada somente quando o usuário envia dados de senhas bancárias.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Todo o túnel HTTPS é criptografado ininterruptamente."
      },
      {
        "id": "440f4ff8-bf00-5839-b0f9-482b8f8736fa",
        "questao_id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
        "letra": "D",
        "texto": "O protocolo emprega criptografia assimétrica no handshake para autenticar o servidor e negociar chaves efêmeras, utilizando em seguida criptografia simétrica veloz para cifrar o tráfego da sessão.",
        "correta": true,
        "ordem": 4,
        "explicacao_especifica": "Correta. Mecanismo híbrido padrão do TLS/HTTPS."
      },
      {
        "id": "408731cf-b14c-5cfa-abe7-e888f26e9214",
        "questao_id": "991daa96-26f1-5edf-b37e-a4c446b3d837",
        "letra": "E",
        "texto": "O HTTPS impede tecnicamente que o usuário seja vítima de ataques de engenharia social ou sites clones clonados.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. HTTPS garante o canal cifrado com o servidor do certificado, mas não impede phishing."
      }
    ]
  },
  {
    "id": "05b9f51d-5555-58f9-8d8d-a68bd19e95d1",
    "idSlug": "l13-info-sec-021-dmz-zona-desmilitarizada-servicos-publicos",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em arquitetura de segurança corporativa, uma Zona Desmilitarizada (DMZ) é uma sub-rede física ou lógica isolada por firewalls que abriga servidores voltados para o acesso público externo (como servidores web e de e-mail), impedindo que um invasor externo que comprometa a DMZ obtenha acesso direto e irrestrito à rede interna confidencial da organização.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A DMZ isola os serviços expostos à Internet, funcionando como barreira intermediária de proteção à rede interna segura.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1606556d88b150fedb5650c85a647b42ee11c08fd6d30f5288a61550ad8444d3",
    "conceito_principal": "Zona Desmilitarizada (DMZ) em redes corporativas",
    "habilidade_cobrada": "Reconhecer a função de isolamento perimetral da DMZ em topologias seguras",
    "tese_ou_regra": "A DMZ isola servidores públicos para evitar que invasões comprometam a rede interna corporativa",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "6dd6156d-caf7-568a-8d16-df4e52fca6f4",
        "questao_id": "05b9f51d-5555-58f9-8d8d-a68bd19e95d1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "def35910-e2df-51ef-97c4-dd125a98504a",
        "questao_id": "05b9f51d-5555-58f9-8d8d-a68bd19e95d1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e0036f46-e990-57dd-92b2-6ce528fd1181",
    "idSlug": "l13-info-sec-022-sql-injection-sanitizacao-parametrizacao",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "afa6fc9a-58eb-5b53-bf8a-f56021b629e4",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O ataque de Injeção de SQL (SQL Injection) ocorre quando uma aplicação web concatena entradas fornecidas pelo usuário diretamente em comandos de banco de dados sem a devida sanitização ou validação, permitindo que o invasor altere a lógica da consulta original para extrair, modificar ou excluir registros sigilosos; a principal medida defensiva contra essa vulnerabilidade é a utilização de consultas parametrizadas (Prepared Statements).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Prepared Statements separam o código SQL dos dados de entrada, neutralizando comandos injetados maliciosamente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6d3bfaf5ed6343e69c34ad77d318e5d7276c37a0ae0961d9e26d75c5880b06ba",
    "conceito_principal": "Ataque de SQL Injection e mitigação por Prepared Statements",
    "habilidade_cobrada": "Analisar as vulnerabilidades em aplicações web e as técnicas de codificação segura",
    "tese_ou_regra": "Consultas parametrizadas impedem a execução de instruções SQL inseridas por atacantes",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "0b4d0c5f-d11c-5675-98da-96440c1e7132",
        "questao_id": "e0036f46-e990-57dd-92b2-6ce528fd1181",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "66cf19d2-6ee5-5067-8232-efea59108e0e",
        "questao_id": "e0036f46-e990-57dd-92b2-6ce528fd1181",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "734c38d4-a55c-5bfa-a70c-d495cbdcf405",
    "idSlug": "l13-info-sec-023-dhcp-atribuicao-dinamica-ip-mascara-gateway",
    "disciplina_id": "4598b6df-6e9d-5916-aa39-bb82ec4f41a6",
    "assunto_id": "0f3e684d-8133-528d-97ac-a8b175acb75d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O protocolo DHCP (Dynamic Host Configuration Protocol) opera na camada de aplicação e tem por objetivo automatizar a distribuição dinâmica e centralizada de parâmetros de rede para os computadores e viaturas conectadas, incluindo endereço IP, máscara de sub-rede, gateway padrão e endereços dos servidores DNS.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O DHCP simplifica a administração de rede atribuindo parâmetros de configuração IP dinamicamente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ea2d20ebf5f430933f5e34ed91e9ff140b87763b2211be98b03fe6b0a2b27a99",
    "conceito_principal": "Protocolo DHCP e autoconfiguração de parâmetros TCP/IP",
    "habilidade_cobrada": "Reconhecer as atribuições automáticas de endereçamento IP e gateways pelo DHCP",
    "tese_ou_regra": "O DHCP distribui endereços IP, máscaras, gateways e DNS automaticamente aos hosts",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "bdf4793c-9f87-5b3c-b1a8-ed035dd3fd74",
        "questao_id": "734c38d4-a55c-5bfa-a70c-d495cbdcf405",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f6eabfdf-0905-56f2-babf-58b76f14c426",
        "questao_id": "734c38d4-a55c-5bfa-a70c-d495cbdcf405",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  }
];
