// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 15

export const m22_questoes = [
  {
    "id": "6cc15ce3-109d-5e28-9f03-d69349dd634b",
    "idSlug": "l13-port-red-001-pontuacao-proibicao-virgula-sujeito-predicado",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Constitui erro gramatical grave a inserção de vírgula simples separando o sujeito de seu respectivo predicado ou o verbo transitivo de seus complementos diretos e indiretos, exceto se houver termos explicativos ou orações interferentes devidamente intercalados entre duas vírgulas.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Regra pétrea de pontuação: não se separa sujeito de predicado nem verbo de seus complementos por vírgula simples.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "31bb0471939a1d363378e62f78151254fd1844495c62a7b68b4672ce96fb75f5",
    "conceito_principal": "Proibição da vírgula entre sujeito e predicado e entre verbo e complementos",
    "habilidade_cobrada": "Reconhecer a estruturação sintática canônica dos termos da oração",
    "tese_ou_regra": "A sintaxe proíbe o isolamento do sujeito em relação ao predicado por vírgula simples",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "a814bf6e-79b0-541e-8382-92aa2c734532",
        "questao_id": "6cc15ce3-109d-5e28-9f03-d69349dd634b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "48c98a1e-47cf-50e2-8728-dee6556911d2",
        "questao_id": "6cc15ce3-109d-5e28-9f03-d69349dd634b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "04a43234-8405-57c7-8798-cedc98be06ec",
    "idSlug": "l13-port-red-002-oracoes-adjetivas-explicativa-com-virgula",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na frase 'Os policiais rodoviários federais, que concluíram o curso de pilotagem defensiva, foram destacados para a operação especial', a oração adjetiva entre vírgulas é explicativa e indica que a totalidade dos policiais rodoviários concluiu o referido curso; a supressão das vírgulas transformaria a oração em restritiva, alterando o sentido para indicar que apenas uma parcela deles realizou o treinamento.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A vírgula na oração subordinada adjetiva define o caráter semântico: com vírgula = explicativa (generaliza o todo); sem vírgula = restritiva (limita a uma parte).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1cb3f2063fde12b331e3bd491307b83d27196c0b81f4d224b1b78ca7629ac527",
    "conceito_principal": "Distinção Semântica e Sintática entre Orações Adjetivas Explicativas e Restritivas",
    "habilidade_cobrada": "Analisar as alterações de sentido decorrentes da inserção ou supressão de vírgulas",
    "tese_ou_regra": "Vírgulas em orações adjetivas conferem valor explicativo generalizante; sua ausência restringe",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "a8f353cf-900b-5feb-8680-2e185d224ba4",
        "questao_id": "04a43234-8405-57c7-8798-cedc98be06ec",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c3e083fd-a51d-5bf8-84f5-22cf4d875d6e",
        "questao_id": "04a43234-8405-57c7-8798-cedc98be06ec",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b1d63d5f-6531-5197-a129-608ec91bb4a5",
    "idSlug": "l13-port-red-003-redacao-oficial-manual-pr-fechos-respeitosamente-atenciosamente",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "De acordo com o Manual de Redação da Presidência da República (3ª edição), os fechos para comunicações oficiais foram padronizados em duas únicas modalidades: 'Respeitosamente', para autoridades de hierarquia superior (inclusive o Presidente da República), e 'Atenciosamente', para autoridades de mesma hierarquia ou de hierarquia inferior.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Padronização exata do MRPR: 'Respeitosamente' (hierarquia superior) e 'Atenciosamente' (mesma hierarquia ou inferior).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "bc1e97ccceac89eb89eb57614ca065b4869fd4f9100d77840767067bd671f4ec",
    "conceito_principal": "Fechos de Comunicação Oficial segundo o Manual de Redação da Presidência da República",
    "habilidade_cobrada": "Identificar o fecho adequado de acordo com a hierarquia da autoridade destinatária",
    "tese_ou_regra": "O MRPR padroniza 'Respeitosamente' para superiores e 'Atenciosamente' para pares e subordinados",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "0cf1308c-45be-594c-aa42-c548ae7733f9",
        "questao_id": "b1d63d5f-6531-5197-a129-608ec91bb4a5",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "4fa3be4b-d097-5303-9003-3b4746114529",
        "questao_id": "b1d63d5f-6531-5197-a129-608ec91bb4a5",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "cce2e11c-7415-576b-b166-566b62632577",
    "idSlug": "l13-port-red-004-coesao-anafora-vs-catafora-pronomes",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "No mecanismo de coesão textual referencial, a anáfora ocorre quando um pronome retoma um termo ou ideia previamente expresso no texto (ex.: 'O delegado colheu as provas; estas foram anexadas aos autos'), enquanto a catáfora antecipa uma informação que ainda será apresentada na sequência da narrativa.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Anáfora = retomada de termo antecedente; Catáfora = projeção/antecipação de termo subsequente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fee0354b9b24f84b35ed0da2bf54f63f334f1b515d2cbdfafefcbaf9c1d1f5d6",
    "conceito_principal": "Mecanismos de Coesão Referencial: Anáfora vs Catáfora",
    "habilidade_cobrada": "Reconhecer o movimento endofórico de pronomes na costura textual",
    "tese_ou_regra": "A anáfora retoma termos anteriores e a catáfora introduz termos posteriores",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "d5e19cf3-57d6-5a2e-8d12-99f6db8eaea8",
        "questao_id": "cce2e11c-7415-576b-b166-566b62632577",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "63a1a13c-341b-50a6-b5c3-e8da96f86f23",
        "questao_id": "cce2e11c-7415-576b-b166-566b62632577",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
    "idSlug": "l13-port-red-005-conjuncoes-adversativas-vs-concessivas",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Considere o período: 'Embora a tempestade tenha danificado os transmissores de rádio, a equipe tática manteve o cerco ao esconderijo'. O conectivo sublinhado ('Embora') estabelece no período uma relação semântica de:",
    "explicacao": "GABARITO: B. 'Embora' é uma conjunção subordinativa concessiva por excelência, introduzindo uma oração que expressa um obstáculo que não impede a realização da oração principal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9eb9239c17096547e745a84f9b5b43ff30492e99f4d2c0fa77c807ff3517327f",
    "conceito_principal": "Valores Semânticos das Conjunções: Concessão ('Embora')",
    "habilidade_cobrada": "Identificar o nexo semântico de orações subordinadas concessivas",
    "tese_ou_regra": "A conjunção 'embora' introduz uma concessão que não invalida a oração principal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "e4f05337-edbe-543e-baa1-c3fc230672ea",
        "questao_id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
        "letra": "A",
        "texto": "Causa explicativa direta.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Conjunção causal seria 'porque', 'já que'."
      },
      {
        "id": "2cc6521a-84e8-58ee-ac3b-f8dc1f23f31a",
        "questao_id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
        "letra": "B",
        "texto": "Concessão (fato que opõe obstáculo sem impedir o desfecho principal).",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. 'Embora' introduz ideia concessiva."
      },
      {
        "id": "a1da49c6-89a5-5351-b592-3c8995bc3b7e",
        "questao_id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
        "letra": "C",
        "texto": "Consequência proporcional.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Consecutiva seria 'tanto... que'."
      },
      {
        "id": "c65aa547-7504-5388-b19d-9ba963846ac3",
        "questao_id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
        "letra": "D",
        "texto": "Condição hipotética vinculante.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Condicional seria 'se', 'caso'."
      },
      {
        "id": "d0183615-332a-58cf-a28b-1948b1ea4d32",
        "questao_id": "dc0daa93-0ffe-5cff-a44f-dc6e9773e206",
        "letra": "E",
        "texto": "Finalidade teleológica.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Final seria 'a fim de que', 'para que'."
      }
    ]
  },
  {
    "id": "7efd0d82-9135-56d7-a2c3-ba597c54771b",
    "idSlug": "l13-port-red-006-redacao-oficial-pronomes-tratamento-concordancia",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Nas comunicações oficiais endereçadas a autoridades tratadas por 'Vossa Excelência' ou 'Vossa Senhoria', a concordância verbal e pronominal deve ser feita compulsoriamente na terceira pessoa do singular (ex.: 'Vossa Excelência designou seus assessores'), e a concordância de gênero dos adjetivos deve ajustar-se ao sexo da pessoa a quem se refere (ex.: 'Vossa Excelência está atarefado' / 'Vossa Excelência está atarefada').",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Pronomes de tratamento exigem verbo e possessivos em 3ª pessoa ('seus', e não 'vossos') e adjetivos concordam com o gênero real da autoridade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "06a73a4ade78456416d82cced6c24c480ad6a6e8935485f557b6541ae866918b",
    "conceito_principal": "Concordância com Pronomes de Tratamento na Redação Oficial",
    "habilidade_cobrada": "Aplicar a concordância gramatical de 3ª pessoa e a concordância ideológica de gênero",
    "tese_ou_regra": "Pronomes de tratamento regem 3ª pessoa e adjetivos concordam com o sexo da autoridade",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "4d32922d-699f-59d9-842b-98059d793d02",
        "questao_id": "7efd0d82-9135-56d7-a2c3-ba597c54771b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e4a113af-6581-5be6-a6d4-6c55571f98ec",
        "questao_id": "7efd0d82-9135-56d7-a2c3-ba597c54771b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9b3df638-c1e7-56a5-b048-d5dc1157be44",
    "idSlug": "l13-port-red-007-pontuacao-adjunto-adverbial-deslocado",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O adjunto adverbial de grande extensão (composto por três ou mais palavras), quando deslocado para o início da oração ou intercalado entre os termos principais, deve ser obrigatoriamente isolado por vírgula (ex.: 'Durante as primeiras horas da madrugada, os agentes cumpriram o mandado judicial').",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Adjunto adverbial de grande extensão antecipado ou intercalado exige vírgula obrigatória; se for de curta extensão (uma ou duas palavras), a vírgula é facultativa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ffc3b71db81718128a1276bc51cbb716027dc6e83e58f751d49ad520dcd4e666",
    "conceito_principal": "Pontuação de Adjunto Adverbial Deslocado (Obrigatoriedade por Extensão)",
    "habilidade_cobrada": "Julgar a obrigatoriedade da vírgula no deslocamento de expressões adverbiais longas",
    "tese_ou_regra": "Adjuntos adverbiais de grande extensão deslocados exigem vírgula obrigatória",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "8412837a-4d0f-5b87-9bb3-f199db46768f",
        "questao_id": "9b3df638-c1e7-56a5-b048-d5dc1157be44",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "175d8acb-9f8f-55d0-baa8-d81dd2e2d31e",
        "questao_id": "9b3df638-c1e7-56a5-b048-d5dc1157be44",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a64944de-a377-5af3-85ec-5c9570f5c400",
    "idSlug": "l13-port-red-008-redacao-oficial-principios-impessoalidade-clareza",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O princípio da impessoalidade na Redação Oficial impõe que os textos governamentais sejam isentos de impressões subjetivas, opiniões pessoais ou marcas de individualismo do redator, devendo refletir a manifestação formal da instituição pública perante a sociedade ou outros órgãos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A impessoalidade decorre do art. 37 da CF/88 e é pilar estruturante da redação oficial (ausência de subjetividade e caráter institucional).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ed6d5b37f5a5e0a47e3b73a0f696ebf4b1f38d2e07891473063c3fb0d9e7d027",
    "conceito_principal": "Princípio da Impessoalidade no Manual de Redação da Presidência da República",
    "habilidade_cobrada": "Reconhecer a natureza pública e despersonalizada dos expedientes policiais e administrativos",
    "tese_ou_regra": "A redação oficial traduz a vontade do órgão público, vedando marcas de subjetividade pessoal",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "28c2ef36-47e9-5ac9-9d86-1c80c0f0a60d",
        "questao_id": "a64944de-a377-5af3-85ec-5c9570f5c400",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a98b8e03-8e6c-504f-a168-49a7f094876c",
        "questao_id": "a64944de-a377-5af3-85ec-5c9570f5c400",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "52907dfd-270b-5698-80e8-536368a676f6",
    "idSlug": "l13-port-red-009-tipologia-textual-dissertativo-argumentativo-expositivo",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Enquanto o texto dissertativo-expositivo tem por meta precípua apresentar informações, dados e conceitos de forma neutra e informativa sem a intenção explícita de convencer o leitor, o texto dissertativo-argumentativo estrutura-se em torno da defesa de uma tese fundamentada por argumentos lógicos com o objetivo de persuadir o interlocutor.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Expositivo = apenas expõe fatos/conceitos; Argumentativo = defende tese para persuadir e influenciar a opinião do leitor.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3365954012d9b2e839ce89a904443ccf1a04712f3131e9dbf42e10b1525b51e5",
    "conceito_principal": "Tipologia Textual: Dissertação Expositiva vs Dissertação Argumentativa",
    "habilidade_cobrada": "Diferenciar a finalidade comunicativa entre expor dados e persuadir o leitor",
    "tese_ou_regra": "A dissertação argumentativa mobiliza recursos persuasivos para sustentar uma tese",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0e831c32-1234-5afd-8182-1c56ae93a2af",
        "questao_id": "52907dfd-270b-5698-80e8-536368a676f6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ae3f144b-448f-597a-b552-3363925690aa",
        "questao_id": "52907dfd-270b-5698-80e8-536368a676f6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
    "idSlug": "l13-port-red-010-redacao-oficial-padrao-oficio-estrutura",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "O Manual de Redação da Presidência da República uniformizou a diagramação dos expedientes sob o denominado 'Padrão Ofício' (que engloba o aviso, o ofício e o memorando). Assinale a alternativa que descreve corretamente um elemento obrigatório da estrutura do Padrão Ofício.",
    "explicacao": "GABARITO: C. O Padrão Ofício contém cabeçalho com brasão e identificação do órgão, identificação do expediente (tipo, número, ano, sigla), local e data, endereçamento, assunto (síntese precisa do teor do documento), texto numerado a partir do 2º parágrafo, fecho e assinatura com cargo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "efe67b1046c2c4fd8540ec40e52d216418f2301ca60d8596123c08af46e1c789",
    "conceito_principal": "Estrutura e Elementos Constitutivos do Padrão Ofício (MRPR)",
    "habilidade_cobrada": "Identificar as diretrizes formais de padronização documental na Administração Pública",
    "tese_ou_regra": "O campo 'Assunto' no Padrão Ofício resume o conteúdo para triagem e arquivo",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2e7ba1ec-66fd-5ce0-ab1d-db25b931f92c",
        "questao_id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
        "letra": "A",
        "texto": "O vocativo deve empregar obrigatoriamente termos pomposos e arcaicos como 'Digníssimo' e 'Ilustríssimo Senhor'.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. O MRPR aboliu o uso de 'Digníssimo' e 'Ilustríssimo'."
      },
      {
        "id": "f1c0065b-9511-5475-9615-77cb908aa085",
        "questao_id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
        "letra": "B",
        "texto": "O campo 'Assunto' deve ser redigido como uma narrativa em primeira pessoa do plural com mais de cinco parágrafos.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O campo assunto deve ser conciso e sintético."
      },
      {
        "id": "4d24fff6-2b19-5846-8934-2a3a466207c5",
        "questao_id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
        "letra": "C",
        "texto": "O campo 'Assunto' fornece uma síntese clara do teor do documento, orientando a tramitação ágil e a indexação arquivística.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Finalidade estrita do campo 'Assunto' no Padrão Ofício."
      },
      {
        "id": "e591ed64-6397-518e-ab00-3754c864b073",
        "questao_id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
        "letra": "D",
        "texto": "Todos os parágrafos do texto devem ser numerados, inclusive o primeiro parágrafo introdutório.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O primeiro parágrafo não é numerado; a numeração inicia no 2º parágrafo."
      },
      {
        "id": "18d54cad-8cc1-5585-af49-3cd260ed238c",
        "questao_id": "bcdb4eaf-a706-5607-9324-deccd7a4ac51",
        "letra": "E",
        "texto": "A assinatura do signatário deve vir acompanhada da foto oficial do servidor público emitente.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A assinatura leva apenas nome e cargo/função."
      }
    ]
  },
  {
    "id": "1256d918-db04-53f2-98a8-fdf8669af67b",
    "idSlug": "l13-port-red-011-pontuacao-dois-pontos-e-travessao-apostos",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Os dois-pontos podem ser legitimamente utilizados para introduzir uma enumeração explicativa, uma citação direta ou um aposto discriminativo, a exemplo da oração: 'A perícia recolheu três elementos fundamentais: o estojo deflagrado, a impressão digital e o aparelho celular'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Dois-pontos introduzem apostos explicativos/enumerativos e citações.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3265856fc18cf5140aba52adc574d75afe427c8372a39f83f6e9e1bfc88aeeac",
    "conceito_principal": "Emprego dos Dois-Pontos em Enumerações e Apostos",
    "habilidade_cobrada": "Identificar a função sintático-discursiva dos dois-pontos na pontuação",
    "tese_ou_regra": "Os dois-pontos abrem espaço discursivo para enumerações e esclarecimentos imediatos",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "338ef06e-4eec-5ea7-bbbd-b38850c07e15",
        "questao_id": "1256d918-db04-53f2-98a8-fdf8669af67b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ba91ad6e-29a9-522b-a516-1c01dce27436",
        "questao_id": "1256d918-db04-53f2-98a8-fdf8669af67b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f8359e03-db11-50fb-b9ca-af61a1956e9b",
    "idSlug": "l13-port-red-012-redacao-oficial-abolicao-dignissimo-ilustrissimo",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Segundo as normas vigentes de Redação Oficial no Poder Executivo Federal, foram abolidos os superlativos 'Digníssimo' (D.D.) e 'Ilustríssimo' (Ilmo.), reservando-se o tratamento 'Vossa Excelência' para as autoridades de cúpula e 'Vossa Senhoria' para as demais autoridades e cidadãos, adotando-se no vocativo a fórmula direta 'Senhor + Cargo'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O MRPR aboliu formalmente 'Digníssimo' e 'Ilustríssimo', simplificando o vocativo para 'Senhor [Cargo]' (ex.: 'Senhor Ministro', 'Senhor Diretor').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c4330897232913b23bbc1f05a4c944a6fe81b0839636c23d1c5f9c03726d6f94",
    "conceito_principal": "Abolição de Fórmulas Arcaicas ('Digníssimo'/'Ilustríssimo') no MRPR",
    "habilidade_cobrada": "Aplicar os padrões modernos de concisão e formalidade em expedientes oficiais",
    "tese_ou_regra": "A redação oficial moderna dispensa tratamentos laudatórios como Ilustríssimo e Digníssimo",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "9f0bb987-ed52-5aff-b830-875d0cf79d4c",
        "questao_id": "f8359e03-db11-50fb-b9ca-af61a1956e9b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e2b786d3-8ff3-5d88-811a-e17918b88f52",
        "questao_id": "f8359e03-db11-50fb-b9ca-af61a1956e9b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9a725428-6886-5591-8304-ca4430bd7b13",
    "idSlug": "l13-port-red-013-pontuacao-oracoes-adverbiais-antepostas",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Quando uma oração subordinada adverbial antecede a oração principal, o emprego da vírgula para separá-las é obrigatório (ex.: 'Assim que a ordem judicial foi emitida, a equipe iniciou o cumprimento dos mandados'); se a oração adverbial vier posposta à principal, o uso da vírgula torna-se facultativo na maioria dos contextos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Oração subordinada adverbial anteposta = vírgula obrigatória; posposta = vírgula facultativa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "782d5dec233187a5ebef81b383e2de0618fa4c0177a80bcc7aae49fd7f7e3bfa",
    "conceito_principal": "Pontuação de Orações Subordinadas Adverbiais Antepostas e Pospostas",
    "habilidade_cobrada": "Julgar a obrigatoriedade da vírgula na inversão de orações complexas",
    "tese_ou_regra": "Orações adverbiais antepostas exigem vírgula obrigatória para delimitar a inversão sintática",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c8574c0f-66d2-50d6-98ae-fd5bf461caef",
        "questao_id": "9a725428-6886-5591-8304-ca4430bd7b13",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "933b4633-a18b-5e79-9b4a-8ce2007c43fc",
        "questao_id": "9a725428-6886-5591-8304-ca4430bd7b13",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7b886f55-5d25-5b6c-b639-3eae1cd528ed",
    "idSlug": "l13-port-red-014-coesao-sequencial-operadores-argumentativos",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Os operadores argumentativos de oposição 'contudo', 'todavia', 'no entanto' e 'entretanto' são conjunções coordenativas adversativas que estabelecem contraste e quebra de expectativa entre orações coordenadas, preservando a coerência e a progressão textual.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Conjunções adversativas estabelecem contraste e oposição de ideias entre enunciados coordenados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "84fc7de0b0eb90b9fe5b5d7f1ef8934de510f84478a512ab35b4c5d7e076cb79",
    "conceito_principal": "Operadores Argumentativos Adversativos na Coesão Sequencial",
    "habilidade_cobrada": "Reconhecer as conjunções que sinalizam contraposição e ressalva discursiva",
    "tese_ou_regra": "Conjunções adversativas operam o contraste semântico garantindo a progressão do texto",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "9b871834-d970-52d3-bcca-f5b572685afb",
        "questao_id": "7b886f55-5d25-5b6c-b639-3eae1cd528ed",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b7b60c68-ae09-5568-a2a5-421c7f73f5d0",
        "questao_id": "7b886f55-5d25-5b6c-b639-3eae1cd528ed",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "91e6e4a4-2467-51f7-93b3-801f34584605",
    "idSlug": "l13-port-red-015-redacao-oficial-concisao-clareza-clareamento",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "aae93c82-cbf2-5cb0-ae75-d341448be61d",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "facil",
    "enunciado": "De acordo com o Manual de Redação da Presidência da República, qual é o atributo da redação oficial que consiste em transmitir o máximo de informações com o mínimo de palavras, eliminando repetições desnecessárias, floreios retóricos e passagens redundantes?",
    "explicacao": "GABARITO: B. A concisão é a virtude textual que visa expressar o pensamento de maneira direta e breve, evitando prolixidade e palavras supérfluas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "966f228a18ce14b51ed8f68653e15ff8cf7bd1a312104298797c9ad61733ae03",
    "conceito_principal": "Atributos da Redação Oficial: Concisão e Clareza Textual",
    "habilidade_cobrada": "Identificar as qualidades essenciais da escrita pública segundo o MRPR",
    "tese_ou_regra": "A concisão elimina redundâncias e expressa o conteúdo com economia de palavras",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "52c5b4d2-92c6-5f92-a5bf-54ecc0deb6f8",
        "questao_id": "91e6e4a4-2467-51f7-93b3-801f34584605",
        "letra": "A",
        "texto": "Prolixidade barroca.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Prolixidade é um vício de linguagem combatido pelo manual."
      },
      {
        "id": "4515fe82-46a8-5931-89dd-7cc987e3fb45",
        "questao_id": "91e6e4a4-2467-51f7-93b3-801f34584605",
        "letra": "B",
        "texto": "Concisão.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Definição exata de concisão no MRPR."
      },
      {
        "id": "5f2926de-9424-5fc7-aa8f-b2a7bf88ae16",
        "questao_id": "91e6e4a4-2467-51f7-93b3-801f34584605",
        "letra": "C",
        "texto": "Subjetividade avaliativa.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A redação oficial é rigorosamente impessoal e objetiva."
      },
      {
        "id": "f54192a6-0ba6-57c7-b86f-497b9fcdb47e",
        "questao_id": "91e6e4a4-2467-51f7-93b3-801f34584605",
        "letra": "D",
        "texto": "Ornamentação estilística.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O texto oficial deve ser sóbrio e sem floreios."
      },
      {
        "id": "0f48b237-e17b-5639-a91e-b6f020474ace",
        "questao_id": "91e6e4a4-2467-51f7-93b3-801f34584605",
        "letra": "E",
        "texto": "Eloquência dramática.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Incompatível com o padrão comunicativo estatal."
      }
    ]
  }
];
