import { TAXONOMIA } from "./taxonomia.mjs";

export const legEsp01Questoes = [
  // 1-12. CEBRASPE (Certo/Errado)
  {
    idSlug: "b9-legesp-01-001",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A Lei nº 11.343/2006 estabelece que quem adquirir, guardar, tiver em depósito, transportar ou trouxer consigo drogas, sem autorização ou em desacordo com determinação legal ou regulamentar, para consumo pessoal, estará sujeito a penas de advertência, prestação de serviços à comunidade e medida educativa de comparecimento a programa ou curso educativo.",
    explicacao: "GABARITO: CERTO. Art. 28, caput, da Lei 11.343/2006: o porte para consumo pessoal não prevê pena privativa de liberdade, mas medidas educativas e prestação de serviços.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-002",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Para determinar se a droga destinava-se a consumo pessoal, o juiz atenderá à natureza e à quantidade da substância apreendida, ao local e às condições em que se desenvolveu a ação, às circunstâncias sociais e pessoais, bem como à conduta e aos antecedentes do agente.",
    explicacao: "GABARITO: CERTO. Art. 28, § 2º, da Lei 11.343/2006: enumera os critérios judiciais para distinção entre consumo pessoal e tráfico.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-003",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O tráfico privilegiado (Art. 33, § 4º, da Lei nº 11.343/2006) exige que o agente seja primário, tenha bons antecedentes, não se dedique às atividades criminosas nem integre organização criminosa, podendo a pena ser reduzida de um sexto a dois terços.",
    explicacao: "GABARITO: CERTO. Art. 33, § 4º, da Lei de Drogas. O STF fixou que o tráfico privilegiado não possui natureza hedionda (HC 118.533/MS).",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-004",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A associação para o tráfico (Art. 35 da Lei nº 11.343/2006) exige a associação de duas ou mais pessoas para o fim de praticar, reiteradamente ou não, os crimes previstos nos arts. 33, caput e § 1º, e 34 da Lei de Drogas.",
    explicacao: "GABARITO: CERTO. Art. 35 da Lei 11.343/2006. Embora o texto legal diga 'reiteradamente ou não', a jurisprudência exige estabilidade e permanência do vínculo associativo, não bastando concurso eventual de agentes.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-005",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O porte ilegal de arma de fogo de uso permitido (Art. 14 da Lei nº 10.826/2003) consiste em portar, deter, adquirir, fornecer, receber, ter em depósito, transportar, ceder, emprestar, remeter, empregar, manter sob guarda ou ocultar arma de fogo, acessório ou munição, de uso permitido, sem autorização e em desacordo com determinação legal ou regulamentar.",
    explicacao: "GABARITO: CERTO. Art. 14, caput, da Lei 10.826/2003. Tipo penal misto alternativo, de perigo abstrato.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-006",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A posse irregular de arma de fogo de uso permitido no interior de residência ou dependência desta, ou no local de trabalho, desde que o agente seja titular ou responsável legal do estabelecimento, configura crime previsto no Art. 12 da Lei nº 10.826/2003.",
    explicacao: "GABARITO: CERTO. Art. 12 do Estatuto do Desarmamento. Diferencia-se do porte (art. 14) pelo âmbito espacial: residência/dependência ou local de trabalho do titular/responsável.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-007",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O disparo de arma de fogo em via pública ou em direção a ela (Art. 15 da Lei nº 10.826/2003) somente se configura se houver vítima determinada e efetiva lesão corporal ou morte.",
    explicacao: "GABARITO: ERRADO. Art. 15 da Lei 10.826/2003 é crime de perigo abstrato, não exigindo vítima determinada nem resultado naturalístico de lesão ou morte; se houver resultado mais grave, pode haver concurso ou absorção conforme o caso.",
    alternativas: [{ texto: "Certo", correta: false }, { texto: "Errado", correta: true }],
  },
  {
    idSlug: "b9-legesp-01-008",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em inquérito da Polícia Federal, apurou-se a associação estável e estruturada de 3 indivíduos com divisão informal de tarefas, voltada à prática reiterada de fraudes financeiras com penas máximas de 8 anos. Sob a ótica estrita da Lei nº 12.850/2013, o grupo não atende ao requisito numérico mínimo para ser classificado como organização criminosa, embora possa tipificar o delito de associação criminosa do Código Penal.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 1º, da Lei nº 12.850/2013: o conceito legal de organização criminosa exige expressamente a associação de 4 (quatro) ou mais pessoas. A reunião estável de 3 pessoas com finalidade criminosa enquadra-se no crime de associação criminosa do art. 288 do Código Penal.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-009",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A colaboração premiada, nos termos da Lei nº 12.850/2013, constitui negócio jurídico processual e meio de obtenção de prova, pressupondo utilidade e interesse públicos.",
    explicacao: "GABARITO: CERTO. Art. 3º-A da Lei 12.850/2013 (incluído pela Lei 13.964/2019): natureza jurídica da colaboração premiada.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-010",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Na ação controlada prevista na Lei nº 12.850/2013, a autoridade policial poderá retardar a intervenção administrativa ou policial, desde que mantida sob observação e acompanhamento para que a medida legal se concretize no momento mais eficaz à formação de provas e obtenção de informações, sendo exigida prévia autorização judicial em todos os casos.",
    explicacao: "GABARITO: ERRADO. Art. 8º da Lei 12.850/2013 exige comunicação prévia ao juiz competente, que poderá estabelecer limites; não se exige autorização judicial prévia como regra geral. Atenção: em tráfico de drogas, a Lei 11.343/2006 prevê disciplina própria que envolve autorização judicial.",
    alternativas: [{ texto: "Certo", correta: false }, { texto: "Errado", correta: true }],
  },
  {
    idSlug: "b9-legesp-01-011",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de tráfico de drogas (Art. 33, caput, da Lei nº 11.343/2006) é tipo misto alternativo, de modo que a prática de mais de um núcleo verbal, no mesmo contexto fático e envolvendo a mesma droga, configura crime único.",
    explicacao: "GABARITO: CERTO. O art. 33, caput, contém múltiplos verbos nucleares; praticados em um mesmo contexto fático sobre o mesmo objeto material, configuram crime único, e não concurso de crimes.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },
  {
    idSlug: "b9-legesp-01-012",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A posse ou o porte ilegal de arma de fogo de uso restrito, sem autorização e em desacordo com determinação legal ou regulamentar, configura crime mais gravemente apenado que a posse ou o porte de arma de uso permitido.",
    explicacao: "GABARITO: CERTO. Art. 16 da Lei 10.826/2003 prevê pena de reclusão de 3 a 6 anos e multa para arma de uso restrito, mais gravosa que os arts. 12 e 14.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }],
  },

  // 13-19. FGV
  {
    idSlug: "b9-legesp-01-013",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A Lei nº 11.343/2006 prevê causa de aumento de pena de um sexto a dois terços para o tráfico de drogas quando:",
    explicacao: "GABARITO: B. Art. 40, III, da Lei 11.343/2006: pena aumentada se a infração for cometida nas dependências ou imediações de estabelecimentos prisionais, de ensino, hospitais, sedes de entidades estudantis/sociais/culturais/recreativas/esportivas/beneficentes, locais de trabalho coletivo, recintos de espetáculos/diversões ou serviços de tratamento de dependentes, entre outros.",
    alternativas: [
      { texto: "O agente confessar espontaneamente a prática do crime.", correta: false },
      { texto: "A infração for cometida nas dependências ou imediações de estabelecimento de ensino ou hospitalar.", correta: true },
      { texto: "A substância for apreendida em quantidade inferior a 10 gramas.", correta: false },
      { texto: "O agente for usuário eventual e primário.", correta: false },
      { texto: "A droga for destinada exclusivamente a consumo compartilhado sem finalidade econômica.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-014",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O crime de omissão de cautela, previsto no Art. 13 da Lei nº 10.826/2003, consiste em:",
    explicacao: "GABARITO: D. Art. 13 da Lei 10.826/2003: deixar de observar cautelas necessárias para impedir que menor de 18 anos ou pessoa com deficiência mental se apodere de arma de fogo que esteja sob sua posse ou propriedade.",
    alternativas: [
      { texto: "Disparar arma de fogo em via pública sem intenção de atingir pessoa determinada.", correta: false },
      { texto: "Portar arma de fogo com registro vencido fora de casa.", correta: false },
      { texto: "Vender munição de uso permitido em estabelecimento autorizado.", correta: false },
      { texto: "Deixar de observar cautelas necessárias para impedir que menor de 18 anos ou pessoa com deficiência mental se apodere de arma sob sua posse/propriedade.", correta: true },
      { texto: "Transportar arma registrada em mudança residencial comunicada à Polícia Federal.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-015",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 12.850/2013, a infiltração de agentes de polícia em tarefas de investigação:",
    explicacao: "GABARITO: A. Art. 10 da Lei 12.850/2013: depende de representação do delegado ou requerimento do MP, após manifestação técnica do delegado quando solicitada no curso de inquérito, e de autorização judicial circunstanciada, motivada e sigilosa.",
    alternativas: [
      { texto: "Depende de autorização judicial circunstanciada, motivada e sigilosa.", correta: true },
      { texto: "Pode ser determinada verbalmente pelo escrivão de polícia responsável pelo cartório.", correta: false },
      { texto: "Dispensa controle judicial quando realizada em crimes transnacionais.", correta: false },
      { texto: "Só pode ser executada por particulares colaboradores sem vínculo policial.", correta: false },
      { texto: "É proibida no ordenamento jurídico brasileiro.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-016",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Aquele que induz, instiga ou auxilia alguém ao uso indevido de droga pratica crime previsto no Art. 33, § 2º, da Lei nº 11.343/2006, cuja pena é de:",
    explicacao: "GABARITO: C. Art. 33, § 2º, da Lei 11.343/2006: detenção de 1 a 3 anos e multa de 100 a 300 dias-multa.",
    alternativas: [
      { texto: "Reclusão de 5 a 15 anos e multa.", correta: false },
      { texto: "Advertência verbal exclusivamente.", correta: false },
      { texto: "Detenção de 1 a 3 anos e multa.", correta: true },
      { texto: "Reclusão de 2 a 8 anos, sem multa.", correta: false },
      { texto: "Prestação de serviços à comunidade por até 5 meses, apenas.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-017",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de comércio ilegal de arma de fogo (Art. 17 da Lei nº 10.826/2003) caracteriza-se quando o agente, sem autorização ou em desacordo com determinação legal ou regulamentar:",
    explicacao: "GABARITO: E. Art. 17 da Lei 10.826/2003: adquirir, alugar, receber, transportar, conduzir, ocultar, ter em depósito, desmontar, montar, remontar, adulterar, vender, expor à venda, ou de qualquer forma utilizar arma de fogo, acessório ou munição, no exercício de atividade comercial ou industrial.",
    alternativas: [
      { texto: "Mantém arma registrada no interior da própria residência.", correta: false },
      { texto: "Deixa menor de idade apoderar-se de arma por descuido.", correta: false },
      { texto: "Dispara arma em via pública durante comemoração.", correta: false },
      { texto: "Entrega arma voluntariamente à Polícia Federal dentro de campanha pública.", correta: false },
      { texto: "Utiliza arma, acessório ou munição no exercício de atividade comercial ou industrial, sem autorização legal.", correta: true },
    ],
  },
  {
    idSlug: "b9-legesp-01-018",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A condenação com trânsito em julgado pelo crime de organização criminosa cometido por funcionário público acarreta:",
    explicacao: "GABARITO: B. Art. 2º, § 6º, da Lei 12.850/2013: a condenação com trânsito em julgado acarretará ao funcionário público a perda do cargo, função, emprego ou mandato eletivo e a interdição para o exercício de função ou cargo público pelo prazo de 8 anos subsequentes ao cumprimento da pena.",
    alternativas: [
      { texto: "Apenas advertência administrativa escrita.", correta: false },
      { texto: "Perda do cargo, função, emprego ou mandato eletivo e interdição para função/cargo público por 8 anos após o cumprimento da pena.", correta: true },
      { texto: "Suspensão remunerada por 30 dias.", correta: false },
      { texto: "Extinção automática da punibilidade dos demais corréus.", correta: false },
      { texto: "Conversão obrigatória da pena privativa de liberdade em multa.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-019",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A destruição de drogas apreendidas sem a ocorrência de prisão em flagrante, nos termos da Lei nº 11.343/2006, será feita por incineração, no prazo máximo de:",
    explicacao: "GABARITO: D. Art. 50-A da Lei 11.343/2006: sem prisão em flagrante, a destruição será feita por incineração no prazo máximo de 30 dias contado da data da apreensão, mediante determinação da autoridade judiciária e ouvido o Ministério Público.",
    alternativas: [
      { texto: "24 horas contado da lavratura do boletim de ocorrência.", correta: false },
      { texto: "5 dias contado da autuação administrativa.", correta: false },
      { texto: "10 dias contado da perícia preliminar.", correta: false },
      { texto: "30 dias contado da data da apreensão.", correta: true },
      { texto: "90 dias após o trânsito em julgado da sentença.", correta: false },
    ],
  },

  // 20-24. VUNESP
  {
    idSlug: "b9-legesp-01-020",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos do Estatuto do Desarmamento, o registro de arma de fogo de uso permitido será expedido pela:",
    explicacao: "GABARITO: A. Art. 5º da Lei 10.826/2003: o certificado de registro de arma de fogo será expedido pela Polícia Federal e precedido de autorização do Sinarm.",
    alternativas: [
      { texto: "Polícia Federal.", correta: true },
      { texto: "Receita Federal.", correta: false },
      { texto: "Defensoria Pública.", correta: false },
      { texto: "Guarda Municipal local.", correta: false },
      { texto: "Secretaria de Fazenda estadual.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-021",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de promover, constituir, financiar ou integrar, pessoalmente ou por interposta pessoa, organização criminosa (Art. 2º da Lei nº 12.850/2013) tem pena de:",
    explicacao: "GABARITO: C. Art. 2º, caput, da Lei 12.850/2013: reclusão de 3 a 8 anos e multa, sem prejuízo das penas correspondentes às demais infrações penais praticadas.",
    alternativas: [
      { texto: "Detenção de 6 meses a 2 anos.", correta: false },
      { texto: "Reclusão de 1 a 4 anos, sem multa.", correta: false },
      { texto: "Reclusão de 3 a 8 anos e multa.", correta: true },
      { texto: "Reclusão de 5 a 15 anos e multa.", correta: false },
      { texto: "Prestação de serviços e advertência judicial.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-022",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Durante diligência da Polícia Civil, dois indivíduos conhecidos foram flagrados consumindo substância entorpecente em praça pública. Restou comprovado no inquérito que um deles havia adquirido a substância e a forneceu gratuitamente ao amigo, de forma eventual e sem qualquer objetivo de lucro, exclusivamente para que juntos a consumissem naquele momento. Nessa situação fática, a conduta de oferecer droga, eventualmente e sem objetivo de lucro, a pessoa de seu relacionamento, para juntos a consumirem (art. 33, § 3º, da Lei nº 11.343/2006):",
    explicacao: "GABARITO: E. Art. 33, § 3º, da Lei nº 11.343/2006: comina pena de detenção de 6 meses a 1 ano e pagamento de 700 a 1.500 dias-multa, sem prejuízo das medidas socioeducativas do art. 28, constituindo infração de menor potencial ofensivo.",
    alternativas: [
      { texto: "Equipara-se integralmente às penas do tráfico comum de drogas (reclusão de 5 a 15 anos).", correta: false },
      { texto: "Configura conduta atípica sob o prisma penal em virtude do consentimento do usuário.", correta: false },
      { texto: "Impede a lavratura de termo circunstanciado por constituir crime hediondo inafiançável.", correta: false },
      { texto: "Gera causa de aumento obrigatória de metade a dois terços sobre a pena base do usuário.", correta: false },
      { texto: "É apenada com detenção de 6 meses a 1 ano e multa, sem prejuízo das medidas do art. 28.", correta: true },
    ],
  },
  {
    idSlug: "b9-legesp-01-023",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "No Estatuto do Desarmamento, o crime de posse ou porte ilegal de arma de fogo de uso restrito (Art. 16) é equiparado, quanto à hediondez, a crime hediondo quando:",
    explicacao: "GABARITO: B. Art. 1º, parágrafo único, II, da Lei 8.072/1990, com redação atual, inclui como hediondo o crime de posse ou porte ilegal de arma de fogo de uso proibido, previsto no art. 16 da Lei 10.826/2003. A redação deve ser lida com atenção: o tratamento hediondo recai sobre arma de uso proibido.",
    alternativas: [
      { texto: "Envolver exclusivamente arma de pressão por ação de gás comprimido.", correta: false },
      { texto: "Envolver arma de fogo de uso proibido.", correta: true },
      { texto: "Ocorrer no interior de residência rural isolada.", correta: false },
      { texto: "For praticado por agente primário sem antecedentes.", correta: false },
      { texto: "A arma estiver desmontada e sem munição.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-024",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A captação ambiental de sinais eletromagnéticos, ópticos ou acústicos, prevista na Lei nº 12.850/2013, poderá ser autorizada pelo juiz, a requerimento da autoridade policial ou do Ministério Público, quando:",
    explicacao: "GABARITO: D. Art. 8º-A da Lei 12.850/2013: será autorizada quando a prova não puder ser feita por outros meios disponíveis e igualmente eficazes e houver elementos probatórios razoáveis de autoria e participação em infrações criminais cujas penas máximas sejam superiores a 4 anos ou conexas.",
    alternativas: [
      { texto: "For pretendida para apurar exclusivamente contravenção penal de menor potencial ofensivo.", correta: false },
      { texto: "Substituir a prova testemunhal meramente por conveniência administrativa.", correta: false },
      { texto: "For requerida verbalmente por pessoa anônima sem controle judicial.", correta: false },
      { texto: "A prova não puder ser feita por outros meios disponíveis e igualmente eficazes e houver elementos probatórios razoáveis de autoria/participação.", correta: true },
      { texto: "Tiver como único fundamento notícia jornalística sem lastro investigativo.", correta: false },
    ],
  },

  // 25-27. AOCP
  {
    idSlug: "b9-legesp-01-025",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O crime de tráfico de drogas, previsto no Art. 33, caput, da Lei nº 11.343/2006, possui pena de:",
    explicacao: "GABARITO: A. Art. 33, caput, da Lei 11.343/2006: reclusão de 5 a 15 anos e pagamento de 500 a 1.500 dias-multa.",
    alternativas: [
      { texto: "Reclusão de 5 a 15 anos e multa.", correta: true },
      { texto: "Detenção de 6 meses a 1 ano e advertência.", correta: false },
      { texto: "Reclusão de 1 a 4 anos, sem multa.", correta: false },
      { texto: "Detenção de 2 a 4 anos e multa.", correta: false },
      { texto: "Prestação de serviços comunitários e curso educativo.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-026",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "São condutas equiparadas ao crime de posse ou porte ilegal de arma de fogo de uso restrito, nos termos do Art. 16, § 1º, da Lei nº 10.826/2003:",
    explicacao: "GABARITO: C. Art. 16, § 1º, III, da Lei 10.826/2003: possuir, detiver, fabricar ou empregar artefato explosivo ou incendiário, sem autorização ou em desacordo com determinação legal ou regulamentar.",
    alternativas: [
      { texto: "Renovar o certificado de registro antes do prazo regulamentar.", correta: false },
      { texto: "Entregar arma voluntariamente a campanha pública de desarmamento.", correta: false },
      { texto: "Possuir, deter, fabricar ou empregar artefato explosivo ou incendiário sem autorização legal.", correta: true },
      { texto: "Guardar arma registrada em cofre residencial certificado.", correta: false },
      { texto: "Comunicar furto da arma à autoridade policial em 24 horas.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-027",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Constitui meio de obtenção de prova previsto expressamente no Art. 3º da Lei nº 12.850/2013:",
    explicacao: "GABARITO: E. Art. 3º da Lei 12.850/2013 prevê, entre outros, colaboração premiada, captação ambiental, ação controlada, infiltração de agentes, acesso a registros e cooperação entre instituições.",
    alternativas: [
      { texto: "Sorteio popular de jurados em rede social.", correta: false },
      { texto: "Execução antecipada da pena sem condenação.", correta: false },
      { texto: "Confisco administrativo sem decisão judicial.", correta: false },
      { texto: "Interrogatório compulsório sem direito ao silêncio.", correta: false },
      { texto: "Colaboração premiada.", correta: true },
    ],
  },

  // 28-30. IBFC
  {
    idSlug: "b9-legesp-01-028",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.lei_drogas_11343,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos crimes definidos nos arts. 33, caput e § 1º, e 34 a 37 da Lei de Drogas, as penas poderão ser aumentadas de um sexto a dois terços se:",
    explicacao: "GABARITO: B. Art. 40, V, da Lei 11.343/2006: a pena aumenta se caracterizado o tráfico entre Estados da Federação ou entre estes e o Distrito Federal (interestadualidade), além de outras hipóteses previstas no dispositivo.",
    alternativas: [
      { texto: "A droga for apreendida em residência particular, em qualquer quantidade.", correta: false },
      { texto: "Caracterizado o tráfico entre Estados da Federação ou entre estes e o Distrito Federal.", correta: true },
      { texto: "O agente for primário e tiver bons antecedentes.", correta: false },
      { texto: "O laudo preliminar for assinado por perito não oficial.", correta: false },
      { texto: "A droga for destinada exclusivamente a consumo próprio.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-029",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.estatuto_desarmamento_10826,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O Estatuto do Desarmamento prevê o crime de supressão ou alteração de marca, numeração ou qualquer sinal de identificação de arma de fogo ou artefato. Tal conduta está prevista no contexto do Art. 16, § 1º, e configura:",
    explicacao: "GABARITO: D. Art. 16, § 1º, I, da Lei 10.826/2003: suprimir ou alterar marca, numeração ou qualquer sinal de identificação de arma de fogo ou artefato.",
    alternativas: [
      { texto: "Mera infração administrativa sem natureza penal.", correta: false },
      { texto: "Omissão de cautela simples.", correta: false },
      { texto: "Contravenção penal de menor potencial ofensivo.", correta: false },
      { texto: "Conduta equiparada ao crime de posse ou porte ilegal de arma de fogo de uso restrito.", correta: true },
      { texto: "Causa de diminuição obrigatória do crime de disparo de arma de fogo.", correta: false },
    ],
  },
  {
    idSlug: "b9-legesp-01-030",
    disciplina_id: TAXONOMIA.disciplinas.legislacao_especial,
    assunto_id: TAXONOMIA.assuntos.organizacoes_criminosas_12850,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Segundo a Lei nº 12.850/2013, a pena do crime de organização criminosa é aumentada até a metade se na atuação da organização criminosa houver:",
    explicacao: "GABARITO: A. Art. 2º, § 2º, da Lei 12.850/2013: as penas aumentam-se até a metade se na atuação da organização criminosa houver emprego de arma de fogo.",
    alternativas: [
      { texto: "Emprego de arma de fogo.", correta: true },
      { texto: "Ausência de divisão informal de tarefas.", correta: false },
      { texto: "Número inferior a quatro integrantes.", correta: false },
      { texto: "Finalidade exclusivamente recreativa.", correta: false },
      { texto: "Prática de infrações penais com pena máxima igual ou inferior a 2 anos.", correta: false },
    ],
  },
];
