import { DISCIPLINAS, ASSUNTOS, criarQuestaoCE, criarQuestaoME, writeModuleFile } from "./helpers.mjs";

// ==============================================================
// M09: CRIMINOLOGIA - TEORIAS E PREVENÇÃO (23 questões)
// ==============================================================
const m09_data = [
  {
    tipo: "CE",
    slug: "l13-crim-teo-001-escola-classica-beccaria",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A Escola Clássica da Criminologia, influenciada pelos ideais iluministas e representada por Cesare Beccaria e Francesco Carrara, fundamentava a responsabilidade penal no livre-arbítrio e concebia o crime como um ente jurídico resultante da quebra do pacto social, e não como um fenômeno biopsicopatológico determinista.",
    explicacao: "GABARITO: CERTO. A Escola Clássica (século XVIII/XIX) baseia-se no jusnaturalismo e no iluminismo, sustentando o livre-arbítrio moral do indivíduo e a natureza jurídica do delito (infração da lei pactuada), diferenciando-se frontalmente do determinismo biológico da Escola Positiva.",
    gabaritoCerto: true,
    conceito: "Escola Clássica da Criminologia e livre-arbítrio",
    habilidade: "Identificar os postulados fundamentais da Escola Clássica (Beccaria e Carrara)",
    tese: "Escola Clássica concebe o crime como ente jurídico fundamentado no livre-arbítrio",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-002-escola-positiva-lombroso-ferri",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "Cesare Lombroso, na fase antropológica da Escola Positiva, defendeu a teoria do criminoso nato baseada no atavismo e em estigmas corporais, enquanto Enrico Ferri enfatizou a sociologia criminal e a multicausalidade delitiva, e Raffaele Garofalo consolidou a vertente jurídica com a noção de delito natural.",
    explicacao: "GABARITO: CERTO. A Escola Positiva estruturou-se na tríade: Lombroso (antropologia criminal e criminoso nato atávico), Ferri (sociologia criminal e fatores endógenos/exógenos) e Garofalo (jurídica/psicológica, formulando o conceito de delito natural violador dos sentimentos de piedade e probidade).",
    gabaritoCerto: true,
    conceito: "Tríade da Escola Positiva Criminológica",
    habilidade: "Distinguir as contribuições de Lombroso, Ferri e Garofalo na Escola Positiva",
    tese: "Positivismo criminológico: método empírico-indutivo e determinismo",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-003-escola-chicago-desorganizacao",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "A Escola de Chicago (ou Teoria Ecológica) sustentou que a criminalidade urbana decorre primordialmente de deficiências genéticas e atávicas dos grupos populacionais periféricos, desconsiderando a desorganização social, a deterioração do espaço urbano e o enfraquecimento do controle social informal.",
    explicacao: "GABARITO: ERRADO. A Escola de Chicago (Park, Burgess, Shaw e McKay) foca na ecologia urbana e na sociologia, apontando a desorganização social das zonas de transição urbana e o colapso dos mecanismos informais de controle comunitário como causas do crime, refutando teses genético-biológicas.",
    gabaritoCerto: false,
    conceito: "Escola de Chicago e Teoria Ecológica da Criminalidade",
    habilidade: "Reconhecer o modelo ecológico e a desorganização social urbana",
    tese: "A criminalidade na Escola de Chicago vincula-se ao espaço urbano e enfraquecimento comunitário",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-004-associacao-diferencial-sutherland",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "Segundo a Teoria da Associação Diferencial formulada por Edwin Sutherland, o comportamento criminoso não é herdado biologicamente nem resulta de desvios psicológicos, mas é aprendido em processos de comunicação e interação no interior de grupos íntimos, explicando inclusive a delinquência de colarinho branco (white-collar crime).",
    explicacao: "GABARITO: CERTO. Sutherland formulou a Teoria da Associação Diferencial demonstrando que a conduta criminosa é aprendida por socialização em ambientes onde as definições favoráveis à violação da lei superam as desfavoráveis, aplicando-se transversalmente a todas as classes sociais.",
    gabaritoCerto: true,
    conceito: "Teoria da Associação Diferencial e crimes de colarinho branco",
    habilidade: "Aplicar a teoria da aprendizagem social de Sutherland ao fenômeno criminal",
    tese: "O crime é comportamento aprendido em interação social direta",
    nivel: "aplicar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-teo-005-teoria-anomia-merton-meios",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Robert K. Merton, ao desenvolver a Teoria Estrutural-Funcionalista da Anomia, postulou que o comportamento desviante surge da tensão estrutural entre as metas culturais socialmente impostas (como o sucesso financeiro) e os meios institucionais legítimos disponíveis para alcançá-las. Assinale a modalidade de adaptação individual mertoniana em que o indivíduo aceita as metas culturais de sucesso financeiro, mas rejeita os meios institucionais legítimos, recorrendo a práticas criminosas.",
    explicacao: "GABARITO: C. A tipologia mertoniana de modos de adaptação individual define a 'Inovação' como a aceitação das metas culturais associada à rejeição/ausência dos meios institucionais legítimos, constituindo o padrão típico dos crimes patrimoniais e de fraude.",
    alternativas: [
      { letra: "A", texto: "Conformismo.", correta: false, explicacao_especifica: "Conformismo aceita tanto as metas culturais quanto os meios legítimos." },
      { letra: "B", texto: "Ritualismo.", correta: false, explicacao_especifica: "Ritualismo rejeita as metas de grande sucesso, mas apega-se rigidamente aos meios e normas." },
      { letra: "C", texto: "Inovação.", correta: true, explicacao_especifica: "Inovação aceita as metas de êxito econômico, mas recorre a meios ilícitos por falta de acesso institucional." },
      { letra: "D", texto: "Evasão ou Retraimento.", correta: false, explicacao_especifica: "Retraimento/Evasão rejeita tanto as metas culturais quanto os meios institucionais (ex.: eremitas, toxicômanos crônicos)." },
      { letra: "E", texto: "Rebelião.", correta: false, explicacao_especifica: "Rebelião rejeita metas e meios vigentes visando substituí-los por uma nova ordem estrutural." }
    ],
    conceito: "Teoria da Anomia de Robert Merton e modos de adaptação",
    habilidade: "Identificar os tipos de adaptação anômica na criminologia sociológica",
    tese: "Inovação representa a assimilação de metas culturais com emprego de meios ilícitos",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-006-labelling-approach-rotulacao",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "A Teoria da Rotulação Social (Labelling Approach ou Etiquetamento), expoente da Criminologia da Reação Social, sustenta que o desvio não é uma qualidade intrínseca do ato praticado, mas uma etiqueta atribuída pelas agências estatais de controle social formal a determinados indivíduos por meio de processos seletivos e estigmatizantes.",
    explicacao: "GABARITO: CERTO. A teoria do Labelling Approach (Howard Becker, Erving Goffman, Edwin Lemert) desloca o objeto da criminologia etiológica (por que se comete o crime) para a reação social (como e quem o sistema seleciona e estigmatiza como delinquente).",
    gabaritoCerto: true,
    conceito: "Teoria do Etiquetamento / Labelling Approach",
    habilidade: "Compreender os fundamentos da criminologia da reação social",
    tese: "O delito é uma construção social decorrente de processos de criminalização seletiva",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-007-desvio-primario-secundario-lemert",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "Na sistemática formulada por Edwin Lemert, o desvio primário consiste na infração normativa inicial que não afeta a autoimagem do sujeito nem gera rotulação permanente, ao passo que o desvio secundário surge da resposta social e institucional estigmatizante, fazendo com que o indivíduo assuma a identidade e o papel social de criminoso.",
    explicacao: "GABARITO: CERTO. Lemert dividiu o desvio em primário (violação sem consolidação do status de criminoso) e secundário (a estigmatização pelo sistema de justiça formal consolida a carreira criminosa como autodefesa e incorporação do rótulo).",
    gabaritoCerto: true,
    conceito: "Desvio primário versus desvio secundário em Lemert",
    habilidade: "Distinguir a dinâmica da estigmatização e consolidação da carreira criminosa",
    tese: "A reação punitiva estatal é fator catalisador do desvio secundário",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-008-criminologia-critica-marxista",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A Criminologia Crítica (ou Radical), influenciada pelo materialismo histórico, concebe o Direito Penal não como instrumento neutro de defesa do bem comum, mas como mecanismo de controle social classista destinado a proteger os interesses econômicos e a propriedade da classe hegemônica, criminalizando as condutas das classes subalternas.",
    explicacao: "GABARITO: CERTO. A Criminologia Crítica (Alessandro Baratta, Taylor, Walton e Young) desvela a seletividade penal e as desigualdades estruturais, apontando que o sistema penal atua funcionalmente na reprodução das relações de dominação do capitalismo.",
    gabaritoCerto: true,
    conceito: "Criminologia Crítica e seletividade estrutural",
    habilidade: "Analisar as premissas da Criminologia Radical e controle de classes",
    tese: "O sistema penal atua como instrumento de manutenção da estratificação social",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-009-janelas-quebradas-wilson-kelling",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "medio",
    enunciado: "A Teoria das Janelas Quebradas (Broken Windows Theory), desenvolvida por James Q. Wilson e George Kelling, sustenta que a desordem urbana tolerada e os pequenos delitos não reprimidos sinalizam a ausência de controle social, criando um ambiente propício para a escalada de infrações penais graves.",
    explicacao: "GABARITO: CERTO. A teoria prega que pequenos sinais de incivilidade e desordem (como vidraças quebradas, pichações e vadiagem), se ignorados pelo poder público e pela comunidade, geram sensação de impunidade e incentivam o cometimento de delitos progressivamente mais violentos.",
    gabaritoCerto: true,
    conceito: "Teoria das Janelas Quebradas e controle da desordem",
    habilidade: "Avaliar o impacto da desordem urbana na criminalidade segundo Wilson e Kelling",
    tese: "Pequenas desordens urbanas não reprimidas fomentam o aumento da criminalidade violenta",
    nivel: "aplicar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-teo-010-modelos-prevencao-primaria-secundaria",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "FGV", orgao: "Guarda Municipal", cargo: "Guarda Civil Municipal",
    dificuldade: "medio",
    enunciado: "No âmbito das políticas públicas de segurança e criminologia moderna, a prevenção do delito é classificada em primária, secundária e terciária. Assinale a opção que exemplifica CORRETAMENTE uma medida de prevenção secundária.",
    explicacao: "GABARITO: B. A prevenção secundária atua nos grupos de risco e locais de vulnerabilidade imediata, manifestando-se por meio de policiamento ostensivo dirigido, vigilância em áreas de risco e iluminação de pontos críticos. A primária atua nas causas estruturais (educação, saúde), e a terciária no apenado (reintegração social).",
    alternativas: [
      { letra: "A", texto: "Ampliação da oferta de educação infantil e políticas públicas de pleno emprego em longo prazo.", correta: false, explicacao_especifica: "Medida típica de prevenção primária (atuação indireta na raiz social)." },
      { letra: "B", texto: "Intensificação do policiamento preventivo ostensivo em áreas de concentração de roubos e programas direcionados a jovens em situação de risco iminente.", correta: true, explicacao_especifica: "Prevenção secundária atua sobre grupos e setores de risco a curto e médio prazos." },
      { letra: "C", texto: "Cursos de capacitação profissional e assistência jurídica a egressos do sistema prisional para evitar a reincidência.", correta: false, explicacao_especifica: "Trata-se de prevenção terciária (foco no sentenciado/egresso)." },
      { letra: "D", texto: "Concessão de remição de pena pelo trabalho aos apenados em cumprimento de pena no regime fechado.", correta: false, explicacao_especifica: "Execução penal voltada à prevenção terciária." },
      { letra: "E", texto: "Reforma urbana nacional e saneamento básico universal.", correta: false, explicacao_especifica: "Prevenção primária de longo alcance social." }
    ],
    conceito: "Classificação tripartite da prevenção criminal",
    habilidade: "Diferenciar prevenção criminal primária, secundária e terciária",
    tese: "Prevenção secundária foca nos fatores e grupos de risco em momento iminente ao delito",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-011-prevencao-terciaria-reincidencia",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "facil",
    enunciado: "A prevenção terciária volta-se diretamente ao apenado e ao egresso do sistema prisional, tendo como objetivo central evitar a reincidência por meio de programas de ressocialização, assistência psicológica, capacitação laboral e acompanhamento pós-penitenciário.",
    explicacao: "GABARITO: CERTO. A prevenção terciária opera após a prática delitiva consumada e condenada, atuando sobre o recluso para propiciar condições dignas de reinserção comunitária e mitigar os efeitos da prisionização.",
    gabaritoCerto: true,
    conceito: "Prevenção criminal terciária e ressocialização",
    habilidade: "Reconhecer o escopo da prevenção terciária na execução penal",
    tese: "Prevenção terciária destina-se ao sentenciado para conter a reincidência",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-012-teoria-subcultura-delinquente-cohen",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "Albert Cohen, ao estudar a subcultura delinquente juvenil, demonstrou que as gangues juvenis de periferia pautam sua conduta por valores não utilitários, maliciosos e negativistas, invertendo expressamente as normas e valores da classe média tradicional por meio de um processo de reação formativa.",
    explicacao: "GABARITO: CERTO. Segundo a teoria da Subcultura Delinquente de Albert Cohen, a delinquência juvenil de gangues apresenta como traços distintivos o caráter não utilitário (roubo pelo status, não pelo lucro), malicioso e negativista, gerando normas próprias que subvertem a moral hegemônica.",
    gabaritoCerto: true,
    conceito: "Teoria da Subcultura Delinquente de Albert Cohen",
    habilidade: "Identificar as características do comportamento delinquente juvenil de gangues",
    tese: "Subcultura juvenil caracteriza-se por condutas não utilitárias e inversão de valores",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-013-teoria-atividades-rotineiras-felson",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "medio",
    enunciado: "A Teoria das Atividades Rotineiras (Routine Activity Theory), desenvolvida por Marcus Felson e Lawrence Cohen, postula que a ocorrência de um crime predatório direto depende da convergência no tempo e no espaço de três elementos: um agressor motivado, um alvo vulnerável ou valioso e a ausência de um guardião capaz.",
    explicacao: "GABARITO: CERTO. A teoria das Atividades Rotineiras (criminologia ambiental/situacional) baseia-se no triângulo do crime: 1) provável ofensor motivado; 2) alvo ou vítima adequada/vulnerável; 3) ausência de guardião capaz (formal como a polícia ou informal como moradores/vigilantes).",
    gabaritoCerto: true,
    conceito: "Teoria das Atividades Rotineiras de Felson e Cohen",
    habilidade: "Compreender a convergência espaciotemporal dos elementos do delito situacional",
    tese: "O crime predatório exige ofensor motivado, alvo adequado e ausência de guardião",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-014-teoria-eficacia-coletiva-sampson",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "dificil",
    enunciado: "O conceito de eficácia coletiva, formulado por Robert Sampson, refere-se à coesão social existente entre vizinhos combinada com a disposição compartilhada de intervir pelo bem comum, demonstrando que bairros com alta eficácia coletiva apresentam menores taxas de criminalidade, independentemente do nível de renda.",
    explicacao: "GABARITO: CERTO. A eficácia coletiva sintetiza confiança mútua e controle social informal voluntário comunitário. Comunidades coesas e engajadas inibem o crime mesmo diante de adversidades econômicas estruturais.",
    gabaritoCerto: true,
    conceito: "Eficácia Coletiva de Robert Sampson",
    habilidade: "Reconhecer o papel da coesão social comunitária no controle informal do crime",
    tese: "A eficácia coletiva atua como moderador dos índices de criminalidade local",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-teo-015-modelos-reacao-social-dissuasorio-restaurador",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A Criminologia contemporânea identifica diferentes modelos de reação social e resposta ao delito, tais como o modelo dissuasório (clássico), o modelo ressocializador e o modelo integrador ou restaurativo. Sobre as características do Modelo Integrador (Justiça Restaurativa), assinale a afirmativa CORRETA.",
    explicacao: "GABARITO: D. O modelo integrador/restaurativo foca na reparação dos danos materiais e emocionais causados à vítima, na responsabilização ativa do ofensor e no restabelecimento da harmonia comunitária, superando a mera retribuição punitiva estatal.",
    alternativas: [
      { letra: "A", texto: "Prioriza a imposição de penas privativas de liberdade severas e a neutralização física do infrator.", correta: false, explicacao_especifica: "Característica do modelo dissuasório/punitivo estrito." },
      { letra: "B", texto: "Centra-se exclusivamente no tratamento médico-psiquiátrico compulsório do condenado pelo Estado.", correta: false, explicacao_especifica: "Característica do modelo ressocializador tecnicista/terapêutico." },
      { letra: "C", texto: "Exclui a participação da vítima do processo decisório para evitar a revitimização institucional.", correta: false, explicacao_especifica: "O modelo restaurativo valoriza e coloca a vítima e a comunidade no centro do processo dialógico." },
      { letra: "D", texto: "Busca a solução do conflito mediante a participação ativa da vítima, do ofensor e da comunidade, promovendo a reparação do dano e a pacificação social.", correta: true, explicacao_especifica: "A Justiça Restaurativa foca na reconciliação, assunção de responsabilidade e restauração dos laços rompidos." },
      { letra: "E", texto: "Condiciona a eficácia do acordo à homologação tácita sem necessidade de concordância voluntária das partes.", correta: false, explicacao_especifica: "A voluntariedade das partes é requisito indispensável nos procedimentos restaurativos." }
    ],
    conceito: "Modelos de reação social ao delito: Justiça Restaurativa",
    habilidade: "Distinguir o modelo restaurativo dos modelos dissuasório e ressocializador",
    tese: "A Justiça Restaurativa promove a participação tripartite (vítima, ofensor e comunidade)",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-016-teoria-autocontrole-gottfredson-hirschi",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "A Teoria Geral do Crime, elaborada por Michael Gottfredson e Travis Hirschi, elege o baixo autocontrole individual, moldado predominantemente na infância pela socialização familiar ineficaz, como o fator primordial e universal para a prática de condutas desviantes e criminosas ao longo da vida.",
    explicacao: "GABARITO: CERTO. A Teoria do Autocontrole (ou Teoria Geral do Crime de 1990) sustenta que a incapacidade de adiar gratificações e o comportamento impulsivo e insensível resultam de falhas na supervisão e afeto parental nos primeiros anos de vida.",
    gabaritoCerto: true,
    conceito: "Teoria do Baixo Autocontrole de Gottfredson e Hirschi",
    habilidade: "Identificar o papel da socialização primária no desenvolvimento do autocontrole",
    tese: "O baixo autocontrole é o fator nuclear explanatório das tendências delitivas",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-017-teoria-conflito-vold-turk",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "Ao contrário das teorias do consenso, as teorias do conflito (como as de George Vold e Austin Turk) afirmam que as leis e os padrões de criminalização representam o resultado de disputas perpétuas de poder entre grupos sociais antagônicos, servindo a norma penal para legitimar a dominação dos grupos vitoriosos.",
    explicacao: "GABARITO: CERTO. As teorias conflitistas rejeitam a premissa de que a sociedade repousa sobre valores compartilhados universalmente, compreendendo o ordenamento penal como cristalização dos interesses da facção detentora momentânea do poder político e econômico.",
    gabaritoCerto: true,
    conceito: "Teorias do Conflito versus Teorias do Consenso",
    habilidade: "Diferenciar os modelos teóricos de consenso e conflito social na criminologia",
    tese: "O Direito Penal reflete as relações de força e poder entre grupos em conflito",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-018-criminologia-clinica-personalidade",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "A Criminologia Clínica utiliza métodos multidisciplinares (médico, psiquiátrico, psicológico e social) para realizar o diagnóstico, o prognóstico e a proposição de tratamento individualizado do condenado, visando compreender a dinâmica da passagem ao ato delituoso e estimar a periculosidade ou probabilidade de reincidência.",
    explicacao: "GABARITO: CERTO. A vertente clínica analisa a personalidade e a trajetória do indivíduo de forma empírica e personalizada, auxiliando nas decisões sobre individualização executória e progressão de regime.",
    gabaritoCerto: true,
    conceito: "Criminologia Clínica e exame criminológico",
    habilidade: "Reconhecer as finalidades diagnósticas e prognósticas da Criminologia Clínica",
    tese: "A Criminologia Clínica foca na dinâmica biopsicossocial do autor da infração",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-019-teoria-neutralizacao-sykes-matza",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Gresham Sykes e David Matza, com a Teoria das Técnicas de Neutralização, sustentam que os delinquentes juvenis compartilham os valores morais dominantes da sociedade, mas utilizam justificativas psicológicas prévias (como negação da responsabilidade, negação do dano ou apelo a lealdades superiores) para silenciar a culpa e legitimar temporariamente sua conduta delitiva.",
    explicacao: "GABARITO: CERTO. As técnicas de neutralização permitem ao delinquente 'flutuar' (drift) entre a ordem normativa legítima e o ato ilícito sem romper totalmente com a moral convencional, recorrendo a racionalizações que desculpam seu comportamento.",
    gabaritoCerto: true,
    conceito: "Técnicas de Neutralização de Sykes e Matza",
    habilidade: "Identificar os mecanismos cognitivos de neutralização da culpa no infrator",
    tese: "O infrator recorre a técnicas de neutralização para justificar a transgressão",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-teo-020-criminologia-positivista-criticas",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Vunesp", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "A Criminologia Positivista do final do século XIX representou um marco metodológico ao introduzir as ciências naturais e o método indutivo empírico no estudo do crime. Contudo, foi alvo de severas críticas da criminologia moderna. Assinale a alternativa que expressa a principal crítica dirigida à Escola Positiva.",
    explicacao: "GABARITO: A. A Escola Positiva foi intensamente criticada por seu determinismo mecanicista e reducionismo biológico, desconsiderando a influência das estruturas socioeconômicas, dos processos de criminalização seletiva e a dignidade e autonomia do ser humano.",
    alternativas: [
      { letra: "A", texto: "Seu determinismo biológico e a crença de que o delinquente é um ser atávico ontologicamente distinto dos cidadãos normais.", correta: true, explicacao_especifica: "O reducionismo e o determinismo biológico constituíram o cerne das críticas contemporâneas ao positivismo lombrosiano." },
      { letra: "B", texto: "A defesa intransigente do livre-arbítrio absoluto e da proporcionalidade matemática entre gravidade do crime e pena.", correta: false, explicacao_especifica: "Livre-arbítrio e retribuição proporcional são postulados da Escola Clássica, combatidos pela Escola Positiva." },
      { letra: "C", texto: "O foco exclusivo nas cifras ocultas da criminalidade e nas pesquisas de vitimização.", correta: false, explicacao_especifica: "Cifras negras e vitimização são temas desenvolvidos a partir de meados do século XX." },
      { letra: "D", texto: "A proposição da abolição irrestrita de todo o sistema penal e das penitenciárias estatais.", correta: false, explicacao_especifica: "Trata-se de bandeira do Abolicionismo Penal, e não do Positivismo." },
      { letra: "E", texto: "A negação absoluta da utilização do método empírico observacional no estudo criminológico.", correta: false, explicacao_especifica: "O Positivismo fundou-se exatamente no método empírico e na observação das ciências naturais." }
    ],
    conceito: "Crítica à Escola Positiva e determinismo biológico",
    habilidade: "Avaliar os limites e superações do modelo positivista criminológico",
    tese: "A criminologia moderna refuta o determinismo atávico e a diferenciação ontológica do delinquente",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-021-criminologia-ambiental-cpted",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Guarda Municipal", cargo: "Guarda Civil Municipal",
    dificuldade: "medio",
    enunciado: "O programa CPTED (Crime Prevention Through Environmental Design - Prevenção do Crime Através do Design Ambiental) fundamenta-se na criminologia situacional e busca reduzir as oportunidades para o crime e o medo da violência mediante o planejamento arquitetônico, a vigilância natural, o reforço territorial e o controle de acessos.",
    explicacao: "GABARITO: CERTO. O CPTED (proposto por C. Ray Jeffery e consolidado por Oscar Newman com o conceito de 'espaço defensável') demonstra como modificações físicas no ambiente urbano inibem a prática criminosa pela ampliação da visibilidade e sentimento de pertencimento comunitário.",
    gabaritoCerto: true,
    conceito: "Prevenção situacional e CPTED no espaço urbano",
    habilidade: "Aplicar princípios de design ambiental na prevenção criminal situacional",
    tese: "O desenho urbano adequado inibe a oportunidade criminosa pelo reforço da vigilância natural",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-022-criminologia-feminista-invisibilidade",
    assuntoId: ASSUNTOS.CRIM_ESCOLAS_TEORIAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A Criminologia Feminista denuncia o androcentrismo histórico da criminologia tradicional, que invisibilizou as especificidades da criminalidade feminina e os padrões estruturais da violência de gênero, criticando a dupla vitimização suportada pela mulher nas instituições do sistema de justiça criminal.",
    explicacao: "GABARITO: CERTO. A Criminologia Feminista desvela como as teorias tradicionais foram formuladas por homens e para explicar delitos masculinos, negligenciando as assimetrias de poder nas relações de gênero e o tratamento estereotipado conferido à mulher como autora e como vítima.",
    gabaritoCerto: true,
    conceito: "Criminologia Feminista e crítica ao androcentrismo",
    habilidade: "Compreender as contribuições da perspectiva de gênero para a teoria criminológica",
    tese: "A abordagem feminista analisa a violência de gênero e o viés patriarcal das agências penais",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-teo-023-lei-e-ordem-tolerancia-zero",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "O movimento de 'Lei e Ordem' (Law and Order) e as políticas de 'Tolerância Zero' fundamentam-se no modelo punitivo dissuasório estrito, defendendo o recrudescimento de penas, a ampliação da repressão policial indiscriminada e o encarceramento massivo como instrumentos prioritários e exclusivos de segurança pública.",
    explicacao: "GABARITO: CERTO. O movimento de Lei e Ordem aposta na capacidade intimidatória da pena e na rigidez penal como dissuasão geral, traduzindo-se na prática em leis penais simbólicas mais severas e repressão concentrada.",
    gabaritoCerto: true,
    conceito: "Movimento de Lei e Ordem e Tolerância Zero",
    habilidade: "Identificar as premissas político-criminais da política de tolerância zero",
    tese: "O modelo dissuasório foca no rigor punitivo e na certeza da sanção privativa de liberdade",
    nivel: "compreender"
  }
];

// ==============================================================
// M10: CRIMINOLOGIA - VITIMOLOGIA, CIFRAS E CONTROLE SOCIAL (22 questões)
// ==============================================================
const m10_data = [
  {
    tipo: "CE",
    slug: "l13-crim-vit-001-vitimologia-mendelsohn-classificacao",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Na clássica classificação vitimológica de Benjamin Mendelsohn, a vítima completamente inocente (ou ideal) não concorre de nenhum modo para a eclosão do evento delitivo, ao passo que a vítima mais culpada que o infrator (ou vítima provocadora) desencadeia diretamente a reação agressiva que a atinge.",
    explicacao: "GABARITO: CERTO. Benjamin Mendelsohn formulou a tipologia baseada na culpabilidade da vítima em relação ao autor: 1) Vítima inocente/ideal; 2) Vítima de culpabilidade menor/ignorância; 3) Vítima tão culpada quanto o infrator (ex: estelionato com dolo bilateral); 4) Vítima mais culpada que o infrator (provocadora); 5) Vítima unicamente culpada (agressora em legítima defesa de terceiro).",
    gabaritoCerto: true,
    conceito: "Classificação vitimológica de Benjamin Mendelsohn",
    habilidade: "Identificar as categorias de vítimas segundo o grau de participação e culpabilidade",
    tese: "A tipologia de Mendelsohn mensura a correlação de culpa entre ofensor e vítima",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-002-vitimizacao-primaria-secundaria-terciaria",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "facil",
    enunciado: "A vitimização secundária (ou sobrevitimização) decorre do sofrimento adicional infligido à vítima pelo próprio funcionamento das agências estatais de controle social (polícia, Ministério Público e Judiciário) durante o processo de investigação e persecução criminal, por meio de inquirições reiteradas e tratamento burocrático insensível.",
    explicacao: "GABARITO: CERTO. Vitimização primária decorre do crime em si; vitimização secundária (sobrevitimização/revitimização institucional) decorre da atuação insensível e desumana do aparato estatal; vitimização terciária decorre da estigmatização, abandono e preconceito da própria comunidade ou familiares.",
    gabaritoCerto: true,
    conceito: "Graus de vitimização: primária, secundária e terciária",
    habilidade: "Distinguir as diferentes esferas de sofrimento vivenciadas pela vítima",
    tese: "A vitimização secundária é gerada pela burocracia e revitimização institucional",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-003-cifra-negra-cifra-dourada",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "A cifra negra da criminalidade expressa a discrepância percentual entre os crimes efetivamente ocorridos na sociedade e aqueles que chegam ao conhecimento oficial dos órgãos de segurança pública, enquanto a cifra dourada designa a criminalidade de colarinho branco, caracterizada por crimes econômicos e financeiros de alto escalão marcados por baixa taxa de persecução e responsabilização.",
    explicacao: "GABARITO: CERTO. Cifra negra é a criminalidade real não registrada oficialmente. Cifra dourada (Sutherland) refere-se aos crimes econômico-financeiros, corrupção e desvios de poder das elites que gozam de imunidade fática e baixa visibilidade nas estatísticas penais ordinárias.",
    gabaritoCerto: true,
    conceito: "Cifras criminais: Negra e Dourada",
    habilidade: "Identificar as características da cifra negra e da cifra dourada na criminologia",
    tese: "Cifra negra indica subnotificação geral; cifra dourada indica criminalidade de elite impune",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-crim-vit-004-cifras-cinza-amarela-rosa",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A doutrina criminológica moderna utiliza convenções cromáticas para classificar diferentes fenômenos de subnotificação e impunidade no sistema de justiça penal. A respeito das cifras criminais, assinale a opção que define CORRETAMENTE a 'Cifra Cinza'.",
    explicacao: "GABARITO: C. A Cifra Cinza corresponde às infrações penais que chegam a ser registradas perante a autoridade policial (boletim de ocorrência), mas que, por conciliação preliminar, composição civil dos danos, desistência ou arquivamento interno, não chegam à fase do processo judicial penal.",
    alternativas: [
      { letra: "A", texto: "Crimes cometidos com violência policial arbitrária que não são investigados pelas corregedorias.", correta: false, explicacao_especifica: "Isso costuma ser associado à cifra amarela (violência estatal) ou negra institucional." },
      { letra: "B", texto: "Delitos praticados contra a ordem econômico-tributária e o sistema financeiro nacional.", correta: false, explicacao_especifica: "Trata-se da Cifra Dourada." },
      { letra: "C", texto: "Crimes que chegam ao conhecimento da polícia e geram registro de ocorrência, mas não avançam para o processo penal judicial, extinguindo-se na fase policial ou por acordo pré-processual.", correta: true, explicacao_especifica: "Cifra Cinza: fato registrado na polícia que não vira processo judicial (ex: composição de danos na Lei 9.099/95)." },
      { letra: "D", texto: "Crimes com motivação homofóbica ou transfóbica cuja notificação é ocultada pela vítima por vergonha.", correta: false, explicacao_especifica: "Associado doutrinariamente à Cifra Rosa (crimes de preconceito/gênero subnotificados)." },
      { letra: "E", texto: "Infrações ambientais e biopirataria cometidas no ambiente amazônico sem fiscalização.", correta: false, explicacao_especifica: "Associado à Cifra Verde (crimes contra o meio ambiente não reportados)." }
    ],
    conceito: "Cifras criminais cromáticas e Cifra Cinza",
    habilidade: "Definir a Cifra Cinza no itinerário da persecução penal",
    tese: "Cifra cinza representa delitos registrados na polícia que não chegam à esfera judicial",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-005-vitimizacao-indireta-terceiros",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "A vitimização indireta atinge pessoas intimamente ligadas à vítima direta, como familiares e dependentes de vítimas de homicídio ou desaparecimento forçado, que suportam danos psicológicos, sociais e econômicos decorrentes da violência sofrida pelo ente querido.",
    explicacao: "GABARITO: CERTO. A vitimização indireta (ou reflexa) abrange os familiares, filhos e cônjuges que sofrem as repercussões traumáticas e o luto desestruturador causado pelo crime violento perpetrado contra o ofendido direto.",
    gabaritoCerto: true,
    conceito: "Vitimização indireta ou reflexa",
    habilidade: "Reconhecer os impactos da vitimização reflexa nos familiares",
    tese: "Os danos do delito violento estendem-se reflexamente ao núcleo familiar da vítima",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-006-pesquisas-vitimizacao-estatisticas",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "As pesquisas empíricas de vitimização por amostragem populacional constituem uma ferramenta indispensável para a criminologia, pois permitem dimensionar a cifra negra e revelar as motivações reais que levam as vítimas a não reportarem os crimes às autoridades policiais.",
    explicacao: "GABARITO: CERTO. As pesquisas de vitimização (surveys) revelam o volume real da criminalidade oculta e diagnosticam os gargalos de confiança da população nas forças de segurança (medo de represália, descrença na eficácia policial, etc.).",
    gabaritoCerto: true,
    conceito: "Pesquisas de vitimização e aferição da cifra negra",
    habilidade: "Compreender a utilidade metodológica das pesquisas de vitimização",
    tese: "Pesquisas de vitimização superam os limites dos registros formais de ocorrência",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-007-controle-social-formal-informal",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Guarda Municipal", cargo: "Guarda Civil Municipal",
    dificuldade: "facil",
    enunciado: "O controle social informal é exercido pela família, escola, igreja, comunidade e redes de vizinhança, atuando preventivamente na internalização de valores e normas sociais, enquanto o controle social formal é exercido de modo coercitivo pelas agências estatais institucionalizadas (Polícia, Ministério Público, Judiciário e Administração Penitenciária).",
    explicacao: "GABARITO: CERTO. O controle social divide-se em informal (agências da sociedade civil que socializam o indivíduo sem poder punitivo estatal) e formal (aparato estatal coercitivo previsto em lei para apuração e sanção de condutas ilícitas).",
    gabaritoCerto: true,
    conceito: "Controle social formal versus controle social informal",
    habilidade: "Diferenciar os mecanismos de controle social formal e informal",
    tese: "Controle informal atua pela socialização; controle formal atua pela coerção legal",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-008-selecionabilidade-controle-formal",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A seleção operada pelo controle social formal é multifásica, iniciando-se na seleção primária com a elaboração legislativa das normas abstratas pelo Parlamento (criminalização primária) e concretizando-se na seleção secundária com a atuação fiscalizatória da polícia e do sistema judicial sobre indivíduos específicos (criminalização secundária).",
    explicacao: "GABARITO: CERTO. Criminalização primária é o ato político legislativo que tipifica abstratamente o crime; criminalização secundária é a ação das agências de coerção que elegem quais pessoas concretas serão perseguidas e punidas.",
    gabaritoCerto: true,
    conceito: "Processos de criminalização primária e secundária",
    habilidade: "Analisar as etapas da persecução e seleção penal formal",
    tese: "A criminalização primária é abstrata; a criminalização secundária é executiva e seletiva",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-vit-009-vitimodogmatica-autorresponsabilidade",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A vitimodogmática é um ramo interdisciplinar que analisa em que medida o comportamento negligente, temerário ou consentido da própria vítima pode influenciar a tipicidade penal, a ilicitude ou a graduação da pena do autor do fato, fundamentando-se no princípio da autorresponsabilidade da vítima. Assinale a situação em que a vitimodogmática é comumente invocada para afastar a tipicidade pela teoria da imputação objetiva.",
    explicacao: "GABARITO: E. Na teoria da imputação objetiva (Claus Roxin), a autocolocação consciente da vítima em risco (ou consentimento livre em ação perigosa executada pelo autor ou por ela mesma) exclui a imputação do resultado ao agente quando a vítima atua no âmbito de sua esfera de autorresponsabilidade.",
    alternativas: [
      { letra: "A", texto: "No estupro de vulnerável praticado contra menor de 14 anos.", correta: false, explicacao_especifica: "No estupro de vulnerável é absolutamente irrelevante qualquer consentimento da vítima (Súmula 593 do STJ)." },
      { letra: "B", texto: "No homicídio qualificado praticado mediante emboscada.", correta: false, explicacao_especifica: "A emboscada impede qualquer autocolocação em risco consciente pela vítima." },
      { letra: "C", texto: "No crime de extorsão mediante sequestro com resultado morte.", correta: false, explicacao_especifica: "Não há falar em autorresponsabilidade da vítima em sequestro." },
      { letra: "D", texto: "No crime de tortura praticado por agente público sob custódia.", correta: false, explicacao_especifica: "O preso encontra-se sob custódia e garantia do Estado, inexistindo autorresponsabilidade excludente." },
      { letra: "E", texto: "Na autocolocação consciente em perigo, em que a vítima, plenamente capaz, aceita participar voluntariamente de atividade arriscada sem incremento ilícito de risco pelo autor.", correta: true, explicacao_especifica: "A auto-responsabilidade e participação voluntária em risco consentido é o fundamento típico da exclusão da imputação objetiva pela vitimodogmática." }
    ],
    conceito: "Vitimodogmática e Teoria da Imputação Objetiva",
    habilidade: "Aplicar a vitimodogmática na exclusão da imputação de resultados lesivos",
    tese: "A autocolocação da vítima em risco consciente afasta a imputação objetiva",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-010-von-hentig-vitimologia-fatores",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "Hans von Hentig, em sua obra clássica 'The Criminal and His Victim', foi pioneiro em estudar a interação dinâmica entre criminoso e vítima, demonstrando que a vulnerabilidade vitimária pode ser influenciada por fatores biopsicológicos (idade, sexo, deficiências) e socioculturais (isolamento, minorias marginalizadas).",
    explicacao: "GABARITO: CERTO. Von Hentig concebeu a vítima como um dos elementos ativos da díade criminosa, categorizando vítimas por fatores etários (crianças, idosos), biológicos (doentes, débeis) e sociais (imigrantes, excluídos).",
    gabaritoCerto: true,
    conceito: "Contribuição de Hans von Hentig à Vitimologia",
    habilidade: "Identificar os fatores predisponentes da vitimização segundo von Hentig",
    tese: "A vulnerabilidade vitimária resulta da conjunção de variáveis biológicas e sociais",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-011-cifra-amarela-violencia-policial",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "dificil",
    enunciado: "A cifra amarela da criminalidade compreende as infrações penais e abusos praticados por agentes de segurança pública que deixam de ser notificados formalmente pelas vítimas devido ao medo de retaliação e à descrença nos órgãos de fiscalização e corregedoria.",
    explicacao: "GABARITO: CERTO. A doutrina criminológica brasileira reconhece a cifra amarela como a cifra dos crimes e abusos de autoridade praticados por agentes estatais não denunciados em virtude de temor de perseguição e opressão.",
    gabaritoCerto: true,
    conceito: "Cifra Amarela e crimes praticados pelo Estado",
    habilidade: "Reconhecer o conceito de cifra amarela e suas causas estruturais",
    tese: "Cifra amarela reflete a subnotificação de abusos cometidos por agentes estatais",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-012-cifra-rosa-crimes-homofobia",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A denominada cifra rosa abrange os crimes de intolerância, discriminação e agressão praticados contra a população LGBTQIA+ que deixam de ser registrados nas delegacias em razão do preconceito, da vergonha da exposição da orientação sexual ou do receio de revitimização institucional.",
    explicacao: "GABARITO: CERTO. A cifra rosa espelha a invisibilidade estatística dos delitos homotransfóbicos gerada pelo medo da discriminação secundária no momento do atendimento policial.",
    gabaritoCerto: true,
    conceito: "Cifra Rosa e crimes de intolerância de gênero/sexualidade",
    habilidade: "Identificar a subnotificação de crimes contra minorias sexuais",
    tese: "Cifra rosa designa a criminalidade oculta motivada por homotransfobia",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-013-vitima-indefesa-vulnerabilidade",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "facil",
    enunciado: "Vítimas portadoras de transtornos mentais, crianças de tenra idade e pessoas em estado de coma são classificadas como vítimas particularmente vulneráveis ou indefesas, sobre as quais recai dever especial de tutela e proteção do ordenamento jurídico, afastando qualquer hipótese de corresponsabilidade vitimária.",
    explicacao: "GABARITO: CERTO. Essas pessoas possuem vulnerabilidade absoluta intrínseca, não havendo participação culposa ou provocação apta a atenuar a responsabilidade do agressor.",
    gabaritoCerto: true,
    conceito: "Vítima vulnerável e ausência de culpabilidade",
    habilidade: "Analisar o estatuto protetivo das vítimas vulneráveis",
    tese: "Pessoas hipervulneráveis gozam de proteção prioritária e irrestrita",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-crim-vit-014-desvio-e-rotulacao-estereotipo",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "O conceito de estereótipo criminológico do delinquente revela como os agentes do sistema de justiça penal orientam suas abordagens com base em características fenotípicas, socioeconômicas e de vestimenta. Sobre os efeitos desse processo na seleção policial, assinale a opção correta.",
    explicacao: "GABARITO: B. A atuação baseada em estereótipos (suspeição subjetiva generalizada) canaliza a repressão policial para indivíduos com perfis marginalizados, confirmando artificialmente as taxas de criminalidade dessas camadas em detrimento da apuração de crimes em estratos favorecidos.",
    alternativas: [
      { letra: "A", texto: "Garante a neutralidade absoluta e a universalidade objetiva das abordagens policiais.", correta: false, explicacao_especifica: "O estereótipo gera viés confirmatório e seletividade discriminatória." },
      { letra: "B", texto: "Concentra as abordagens e averiguações sobre populações vulneráveis e periféricas, gerando viés confirmatório nas estatísticas oficiais de prisões.", correta: true, explicacao_especifica: "A seletividade policial estereotipada alimenta o funil penal concentrado nas classes subalternas." },
      { letra: "C", texto: "Elimina por completo a incidência de cifras negras nos crimes violentos.", correta: false, explicacao_especifica: "A seletividade não reduz a cifra negra; distorce o perfil dos apenados." },
      { letra: "D", texto: "Impede a ocorrência de vitimização terciária no ambiente comunitário.", correta: false, explicacao_especifica: "Não tem relação com a eliminação da vitimização terciária." },
      { letra: "E", texto: "Substitui a atuação do controle social formal pelos órgãos de controle informal.", correta: false, explicacao_especifica: "Trata-se de mecanismo operado pelo próprio controle social formal." }
    ],
    conceito: "Estereótipo criminológico e seletividade policial",
    habilidade: "Compreender os mecanismos de seletividade no controle social formal",
    tese: "O perfilamento baseado em estereótipos direciona a ação repressiva a grupos específicos",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-015-vitimizacao-institucional-acolhimento",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A criação de Delegacias Especializadas de Atendimento à Mulher (DEAM), as salas de escuta protegida para crianças e adolescentes (Lei nº 13.431/2017) e o protocolo de depoimento especial têm como finalidade precípua combater a vitimização secundária nas delegacias e tribunais.",
    explicacao: "GABARITO: CERTO. Tais mecanismos institucionais foram concebidos especificamente para evitar que a vítima seja submetida a múltiplos depoimentos traumáticos, constrangimentos ou julgamento moral depreciativo por agentes estatais.",
    gabaritoCerto: true,
    conceito: "Mecanismos institucionais de combate à sobrevitimização",
    habilidade: "Identificar práticas de proteção e escuta especializada no sistema policial",
    tese: "A escuta protegida visa prevenir a revitimização institucional de vulneráveis",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-016-vitima-rebelde-falsa-mendelsohn",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Na tipologia de Mendelsohn, a 'pseudovítima' ou vítima simuladora (falsa) é aquela que inventa deliberadamente uma acusação de crime inexistente para prejudicar outrem ou obter vantagem indevida, respondendo criminalmente por denunciação caluniosa ou comunicação falsa de crime.",
    explicacao: "GABARITO: CERTO. A pseudovítima ou vítima imaginária/simuladora é o sujeito que forja a condição de vítima para fraudar seguros, vingar-se de desafetos ou ocultar condutas próprias ilícitas.",
    gabaritoCerto: true,
    conceito: "Pseudovítima / Vítima simuladora em Vitimologia",
    habilidade: "Diferenciar vítimas reais de vítimas simuladoras no contexto investigativo",
    tese: "A falsa vítima comete crime contra a administração da justiça",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-017-vitimizacao-terciaria-estigma",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "facil",
    enunciado: "A vitimização terciária caracteriza-se pela falta de amparo, segregação, vergonha e culpabilização impostas à vítima pelo seu próprio meio social, amigos e familiares após a ocorrência de determinados delitos, como crimes contra a dignidade sexual.",
    explicacao: "GABARITO: CERTO. A vitimização terciária manifesta-se quando a sociedade e o grupo social de pertença estigmatizam e discriminam a vítima (ex: questionando seu comportamento ou vestimenta), gerando isolamento e sofrimento interpessoal.",
    gabaritoCerto: true,
    conceito: "Vitimização terciária e estigmatização comunitária",
    habilidade: "Identificar as manifestações da vitimização terciária na vida social",
    tese: "A vitimização terciária decorre do abandono e culpabilização pela comunidade",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-018-cifra-branca-crimes-elucidados",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "facil",
    enunciado: "A cifra branca corresponde à totalidade dos crimes que foram oficialmente registrados, investigados pela polícia e cujas autorias e materialidades foram plenamente elucidadas pelas autoridades competentes.",
    explicacao: "GABARITO: CERTO. A cifra branca expressa a estatística dos crimes notificados, processados e esclarecidos com sucesso pelo sistema penal de persecução criminal.",
    gabaritoCerto: true,
    conceito: "Cifra Branca da criminalidade",
    habilidade: "Reconhecer o conceito de cifra branca na estatística criminal",
    tese: "Cifra branca reflete a criminalidade formalmente esclarecida e processada",
    nivel: "recordar"
  },
  {
    tipo: "ME",
    slug: "l13-crim-vit-019-itinerario-carcerario-prisionizacao",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Vunesp", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "Donald Clemmer cunhou o termo 'prisionização' (prisonization) para descrever um fenômeno psicossocial específico que ocorre no interior dos estabelecimentos prisionais. Assinale a alternativa que define com exatidão esse fenômeno.",
    explicacao: "GABARITO: D. Prisionização é o processo de aculturação e assimilação gradual, pelo detento, dos códigos informais, costumes, gírias e valores da subcultura prisional hegemônica, dificultando sua posterior reinserção na vida em liberdade.",
    alternativas: [
      { letra: "A", texto: "A perda imediata e irrecorrível dos direitos políticos e civis por ato judicial.", correta: false, explicacao_especifica: "Efeito jurídico da condenação, não o conceito criminológico de prisionização." },
      { letra: "B", texto: "A concessão automática de benefícios de saída temporária a todos os apenados.", correta: false, explicacao_especifica: "Benefício da LEP sob condições estritas." },
      { letra: "C", texto: "O acolhimento psicológico de apoio à vítima no momento da audiência de custódia.", correta: false, explicacao_especifica: "Medida de proteção à vítima, sem relação com prisionização." },
      { letra: "D", texto: "A assimilação e internalização, pelo apenado, das normas, hábitos, gírias e valores informais da subcultura carcerária.", correta: true, explicacao_especifica: "Conceito clássico de Clemmer: adaptação e incorporação da subcultura prisional pelo recluso." },
      { letra: "E", texto: "A fuga física de estabelecimentos de segurança máxima mediante motim coletivo.", correta: false, explicacao_especifica: "Trata-se de infração disciplinar/fuga." }
    ],
    conceito: "Fenômeno da Prisionização de Donald Clemmer",
    habilidade: "Compreender a dinâmica de assimilação da subcultura carcerária",
    tese: "A prisionização enfraquece os laços sociais externos e consolida o código carcerário",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-020-desvitimizacao-processo-reparacao",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "O processo de desvitimização abrange as medidas terapêuticas, jurídicas e sociais implementadas para restaurar a dignidade da vítima, reparar as perdas sofridas e auxiliar na superação do trauma, permitindo-lhe abandonar a identidade fixada de vítima e retomar plenamente sua vida social.",
    explicacao: "GABARITO: CERTO. A desvitimização representa o objetivo final das práticas protetivas e da justiça restaurativa, trabalhando o empoderamento e o reestabelecimento da integridade física e emocional do ofendido.",
    gabaritoCerto: true,
    conceito: "Processo de Desvitimização em Criminologia",
    habilidade: "Identificar os objetivos e métodos da desvitimização no suporte à vítima",
    tese: "A desvitimização reconstrói a autonomia e supera o trauma delitivo",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-021-controle-social-socializacao-falhas",
    assuntoId: ASSUNTOS.CRIM_PREVENCAO_REACAO,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "medio",
    enunciado: "O controle social formal só é legitimamente acionado quando o controle social informal (família, escola e comunidade) falha na contenção dos impulsos desviantes, atuando o Direito Penal como ultima ratio em decorrência do princípio da intervenção mínima.",
    explicacao: "GABARITO: CERTO. O controle formal estatal é subsidiário e fragmentário, intervindo apenas quando as demais instâncias informais de controle social se mostram insuficientes para a tutela de bens jurídicos vitais.",
    gabaritoCerto: true,
    conceito: "Subsidiariedade do controle social formal",
    habilidade: "Articular controle social formal com o princípio da intervenção mínima penal",
    tese: "O controle penal formal atua como ultima ratio diante da ineficácia do controle informal",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-crim-vit-022-cifra-verde-crimes-ambientais",
    assuntoId: ASSUNTOS.CRIM_VITIMOLOGIA_CIFRAS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "A chamada cifra verde compreende o conjunto de condutas criminosas lesivas ao meio ambiente (poluição, desmatamento ilegal, biopirataria) que não são detectadas ou notificadas aos órgãos ambientais e de polícia judiciária, em razão da dispersão dos danos, da ausência de uma vítima individual direta e da precariedade de fiscalização em regiões remotas.",
    explicacao: "GABARITO: CERTO. A Cifra Verde reflete a gigantesca subnotificação dos crimes ambientais provocada pelo caráter difuso do bem jurídico ambiental e pela vastidão das fronteiras e biomas naturais.",
    gabaritoCerto: true,
    conceito: "Cifra Verde e crimes ambientais ocultos",
    habilidade: "Reconhecer as causas da subnotificação em matéria penal ambiental",
    tese: "A cifra verde mede a criminalidade ambiental não detectada ou apurada",
    nivel: "compreender"
  }
];

function converterItem(item, disciplinaId) {
  if (item.tipo === "CE") {
    return criarQuestaoCE({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      gabaritoCerto: item.gabaritoCerto,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  } else {
    return criarQuestaoME({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      alternativas: item.alternativas,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  }
}

// 1. Gerar M09
const m09_questoes = m09_data.map(item => converterItem(item, DISCIPLINAS.CRIMINOLOGIA));
writeModuleFile("m09_criminologia_teorias.mjs", "m09_questoes", m09_questoes);

// 2. Gerar M10
const m10_questoes = m10_data.map(item => converterItem(item, DISCIPLINAS.CRIMINOLOGIA));
writeModuleFile("m10_criminologia_vitimologia.mjs", "m10_questoes", m10_questoes);

console.log("[OK] Grupo C2 (M09: 23 questões, M10: 22 questões) concluído com sucesso!");
