// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 25

export const m01_questoes = [
  {
    "id": "7dd18336-d656-532b-8fb9-021bd649741d",
    "idSlug": "pen-ger-001-retroatividade-lex-mitior",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "daca98a7-4f3f-5498-b313-6ab5c0da1539",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Em matéria de aplicação da lei penal no tempo, a norma penal superveniente que de qualquer modo favoreça o agente aplica-se retroativamente aos fatos anteriores, ainda que já decididos por sentença condenatória transitada em julgado, cabendo a sua aplicação ao juízo da execução penal.",
    "explicacao": "GABARITO: CERTO. Conforme o Art. 2º, parágrafo único, do Código Penal e o Art. 5º, XL, da CF/88, a lei posterior que favorece o agente retroage sempre (lex mitior). Já transitada em julgado a sentença, a competência para aplicar a lei mais benigna é do Juízo da Execução Penal (Súmula 611 do STF).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "be982a514589f45973de3be7e1a70bce0b8ccf19e231d76b2dc8cd48d75e1a27",
    "conceito_principal": "Princípio da retroatividade da lei penal mais benigna",
    "habilidade_cobrada": "Identificar a aplicação da lex mitior e a competência do juízo da execução",
    "tese_ou_regra": "Art. 2º, parágrafo único, do CP e Súmula 611 do STF",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "3e249a70-56f5-51ed-9a12-6517618e9615",
        "questao_id": "7dd18336-d656-532b-8fb9-021bd649741d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "464a609f-950a-58f4-a22b-22bec307ff23",
        "questao_id": "7dd18336-d656-532b-8fb9-021bd649741d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "65f9e5c8-61d7-5443-80a2-174515edd1c0",
    "idSlug": "pen-ger-002-crime-permanente-sumula711",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "daca98a7-4f3f-5498-b313-6ab5c0da1539",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Durante a consumação de um crime de extorsão mediante sequestro (crime permanente), entrou em vigor lei penal que exasperou a pena privativa de liberdade cominada abstratamente ao delito. Nessa hipótese, segundo a jurisprudência sumulada do STF, a novel legislação mais gravosa é inaplicável ao caso concreto, em respeito à irretroatividade da lei penal prejudicial.",
    "explicacao": "GABARITO: ERRADO. Assertiva ERRADA. De acordo com a Súmula 711 do STF: 'A lei penal mais grave aplica-se ao crime continuado ou ao crime permanente, se a sua vigência é anterior à cessação da continuidade ou da permanência'. Como o crime continuava se consumando sob a vigência da nova lei, esta incide legitimamente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "df8847cc06fe081bd53b65d5137b42578717c7738692d2e84e243ec91a636534",
    "conceito_principal": "Aplicação da lei penal no tempo em crimes permanentes e continuados",
    "habilidade_cobrada": "Aplicar a Súmula 711 do STF a caso de crime permanente",
    "tese_ou_regra": "Súmula 711/STF e teoria da atividade",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "34267106-cb20-563c-a6c7-196bea145fb4",
        "questao_id": "65f9e5c8-61d7-5443-80a2-174515edd1c0",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "637f800d-202f-5f53-b2c9-004b28c62487",
        "questao_id": "65f9e5c8-61d7-5443-80a2-174515edd1c0",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "d0f6594d-dc33-5ad8-8ad6-081f6aa4ca98",
    "idSlug": "pen-ger-003-lugar-crime-ubiquidade",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "daca98a7-4f3f-5498-b313-6ab5c0da1539",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Considera-se praticado o crime, de acordo com o Código Penal brasileiro, no lugar em que ocorreu a ação ou omissão, no todo ou em parte, bem como onde se produziu ou deveria produzir-se o resultado, adotando-se, quanto ao lugar do crime, a teoria da ubiqüidade (mista).",
    "explicacao": "GABARITO: CERTO. Conforme o Art. 6º do CP: 'Considera-se praticado o crime no lugar em que ocorreu a ação ou omissão, no todo ou em parte, bem como onde se produziu ou deveria produzir-se o resultado'. Trata-se da teoria da ubiqüidade ou mista para o lugar do crime, ao passo que para o tempo do crime adotou-se a teoria da atividade (Art. 4º do CP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "61dbf91d0b6d8ed395281b68252374daeed1de5957068fcb6e0d938c4cfd0841",
    "conceito_principal": "Lugar do crime no Código Penal",
    "habilidade_cobrada": "Distinguir a teoria da ubiqüidade (lugar) da teoria da atividade (tempo)",
    "tese_ou_regra": "Art. 6º do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2aed99a8-27ca-5cfd-aefb-500f37d9ec4c",
        "questao_id": "d0f6594d-dc33-5ad8-8ad6-081f6aa4ca98",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a891f1aa-32e9-52e7-8839-ad8f962f955b",
        "questao_id": "d0f6594d-dc33-5ad8-8ad6-081f6aa4ca98",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "302025c2-a43e-55c7-b514-30e280e6dce0",
    "idSlug": "pen-ger-004-extraterritorialidade-incondicionada",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "daca98a7-4f3f-5498-b313-6ab5c0da1539",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Delegado de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Ficam sujeitos à lei brasileira, embora cometidos no estrangeiro, os crimes contra a vida ou a liberdade do Presidente da República e os crimes contra a administração pública praticados por quem está a seu serviço, hipóteses de extraterritorialidade incondicionada em que o agente é punido segundo a lei brasileira ainda que absolvido ou condenado no estrangeiro.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 7º, I, 'a' e 'c', do CP estabelece a extraterritorialidade incondicionada (princípio da defesa/real e princípio da personalidade ativa institucional). Nos termos do Art. 7º, § 1º, do CP, nesses casos o agente é punido segundo a lei brasileira, ainda que absolvido ou condenado no exterior.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b18c7f34ba7a7dafdaa68034a14f10b190f46454c82318e2bf8ac8791b5c6c76",
    "conceito_principal": "Extraterritorialidade incondicionada da lei penal brasileira",
    "habilidade_cobrada": "Analisar as hipóteses do Art. 7º, I, do CP e sua disciplina jurídica",
    "tese_ou_regra": "Art. 7º, I, 'a' e 'c' c/c § 1º do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "2ecaf2bb-0e9a-5f4e-860b-8582494b0c91",
        "questao_id": "302025c2-a43e-55c7-b514-30e280e6dce0",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c6bd265e-8717-5394-a48e-638170a39ebd",
        "questao_id": "302025c2-a43e-55c7-b514-30e280e6dce0",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "fc06e7dc-52ee-5b65-b9ff-fbc836fe8283",
    "idSlug": "pen-ger-005-insignificancia-requisitos-stf",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A aplicação do princípio da insignificância como causa excludente da tipicidade formal exige, segundo jurisprudência pacífica do STF, a presença cumulativa de quatro vetores: mínima ofensividade da conduta, nenhuma periculosidade social da ação, reduzidíssimo grau de reprovabilidade do comportamento e inexpressividade da lesão jurídica provocada.",
    "explicacao": "GABARITO: ERRADO. Assertiva ERRADA. O princípio da insignificância afasta a tipicidade MATERIAL (não a tipicidade formal). Os 4 vetores cumulativos fixados pelo STF (HC 84.412/SP) estão corretos, mas a exclusão opera sobre a tipicidade material por ausência de lesão relevante ao bem jurídico tutelado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3834ce81c208a0da4df25b46339b03482a8038044a156e2683df616c9588c9fc",
    "conceito_principal": "Princípio da insignificância e tipicidade material",
    "habilidade_cobrada": "Identificar a natureza da excludente operada pelo princípio da bagatela",
    "tese_ou_regra": "HC 84.412/STF e diferenciação entre tipicidade formal e material",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "d73240a0-4e08-5ef9-a2ac-96ece3884e70",
        "questao_id": "fc06e7dc-52ee-5b65-b9ff-fbc836fe8283",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "544321c7-ed67-5e0f-b489-f1f52b02763b",
        "questao_id": "fc06e7dc-52ee-5b65-b9ff-fbc836fe8283",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "f67c4660-5c47-52d2-882e-7a17a7784ae6",
    "idSlug": "pen-ger-006-concausa-superveniente-absolutamente",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em uma investigação conduzida pela Polícia Civil, apurou-se que um indivíduo desferiu disparo de arma de fogo na perna da vítima, provocando lesão corporal leve. Socorrida e internada em hospital, a vítima veio a falecer três dias depois exclusivamente em decorrência do desabamento da ala médica em razão de forte temporal. Nessa situação, a causa superveniente relativamente independente exclui a imputação do resultado morte ao autor do disparo, respondendo ele apenas pelos atos anteriormente praticados.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 13, § 1º, do Código Penal disciplina que a superveniência de causa relativamente independente exclui a imputação quando, por si só, produziu o resultado, imputando-se, contudo, os fatos anteriores a quem os praticou. O desabamento hospitalar constitui concausa superveniente que produziu por si só o evento letal (rompimento da imputação do resultado morte), subsistindo a responsabilidade do autor apenas pelos atos anteriores executados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5f0c118a983724fe259e8e181274499a59a68e595abe61c80b9d525e6b8c82ee",
    "conceito_principal": "Nexo causal e concausas relativamente independentes supervenientes",
    "habilidade_cobrada": "Aplicar a regra do Art. 13, § 1º, do CP a caso concreto policial",
    "tese_ou_regra": "Art. 13, § 1º, do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "78483956-1a68-5d3a-8dea-361647354bf7",
        "questao_id": "f67c4660-5c47-52d2-882e-7a17a7784ae6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c3377c06-5bb2-5242-879e-3307acea5fa5",
        "questao_id": "f67c4660-5c47-52d2-882e-7a17a7784ae6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6568a927-431c-506e-837f-5e445bf47c7c",
    "idSlug": "pen-ger-007-dolo-eventual-culpa-consciente",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Distingue-se o dolo eventual da culpa consciente pelo elemento volitivo: no dolo eventual, o agente antevê o resultado lesivo e assume o risco de produzi-lo (teoria do assentimento), demonstrando indiferença; na culpa consciente, o agente prevê o resultado, mas sinceramente confia em suas habilidades ou em fatores externos para evitá-lo.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 18, I, do CP adotou a teoria do assentimento para o dolo eventual ('assumiu o risco de produzi-lo'). Na culpa consciente, há previsão do resultado, porém o agente rejeita a produção do evento danoso, acreditando convictamente que ele não ocorrerá.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "091e3b7f844223da0ce00b06d07e29717e20f302c5e579f9d34a8d08796564fe",
    "conceito_principal": "Distinção entre dolo eventual e culpa consciente",
    "habilidade_cobrada": "Diferenciar a assunção do risco (dolo eventual) da previsão com repulsa (culpa consciente)",
    "tese_ou_regra": "Art. 18, I e II, do Código Penal e Teoria do Assentimento",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "b9531703-360a-5953-a648-849ecbf65a7d",
        "questao_id": "6568a927-431c-506e-837f-5e445bf47c7c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "fc7406da-a44c-5c2f-b906-fdcc185bc36a",
        "questao_id": "6568a927-431c-506e-837f-5e445bf47c7c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bff44299-fbdc-5645-9227-bce06d55974d",
    "idSlug": "pen-ger-008-desistencia-voluntaria-arrependimento-eficaz",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O agente que, voluntariamente, desiste de prosseguir na execução ou impede que o resultado se produza, responde apenas pelos atos já praticados, configurando-se hipótese legal de desistência voluntária ou de arrependimento eficaz ('ponte de ouro').",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. Trata-se da redação exata do Art. 15 do Código Penal. Na desistência voluntária (tentativa inacabada), o agente cessa a execução; no arrependimento eficaz (tentativa acabada), o agente esgota os atos executórios, mas atua positivamente impedindo o resultado consumativo. Em ambos, afasta-se a tentativa e o agente responde apenas pelos atos já praticados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f539833c556849dce4e86b717c33b2bf78c74dab071858db48cda52d03588eda",
    "conceito_principal": "Desistência voluntária e arrependimento eficaz",
    "habilidade_cobrada": "Aplicar a regra do Art. 15 do CP e seus efeitos penais",
    "tese_ou_regra": "Art. 15 do Código Penal (Ponte de Ouro de von Liszt)",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "1ba9d356-b0ab-5463-b727-5edaeebcbaae",
        "questao_id": "bff44299-fbdc-5645-9227-bce06d55974d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "bf6623b5-4e6a-564f-b7cb-af1fa20e5b45",
        "questao_id": "bff44299-fbdc-5645-9227-bce06d55974d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8e1e8678-e037-5d2a-a424-a3c4addba092",
    "idSlug": "pen-ger-009-arrependimento-posterior-requisitos",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Nos crimes cometidos sem violência ou grave ameaça à pessoa, reparado o dano ou restituída a coisa, até a prolação da sentença condenatória de primeiro grau, por ato voluntário do autor, a pena será reduzida de um a dois terços.",
    "explicacao": "GABARITO: ERRADO. Assertiva ERRADA. O limite temporal para o arrependimento posterior previsto no Art. 16 do CP é até o RECEBIMENTO DA DENÚNCIA OU DA QUEIXA (e não até a sentença condenatória). Requisitos: crime sem violência/grave ameaça, reparação integral/restituição voluntária e antes do recebimento da peça acusatória.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2bcebe13c883e100e04af760cb003eaaf78ab001b8cb6339b3f84b79a728891b",
    "conceito_principal": "Arrependimento posterior e marco temporal",
    "habilidade_cobrada": "Identificar o marco processual limite para concessão da causa de diminuição do Art. 16 do CP",
    "tese_ou_regra": "Art. 16 do Código Penal",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "b2f569b1-b37c-571c-be40-e99865cfb194",
        "questao_id": "8e1e8678-e037-5d2a-a424-a3c4addba092",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "7a30570f-9d36-56bf-a196-98fe401797e3",
        "questao_id": "8e1e8678-e037-5d2a-a424-a3c4addba092",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "2564647e-bf88-53e5-9f33-28547f506974",
    "idSlug": "pen-ger-010-crime-impossivel-sumula145",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Não se pune a tentativa quando, por ineficácia absoluta do meio ou por absoluta impropriedade do objeto, é impossível consumar-se o crime. De acordo com o STF (Súmula 145), não há crime quando a preparação do flagrante pela polícia torna impossível a sua consumação.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 17 do CP adotou a teoria objetiva temperada para o crime impossível (tentativa inidônea). A Súmula 145 do STF estabelece que o flagrante preparado/provocado induz crime impossível por absoluta ineficácia do meio em atingir a consumação pretendida.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "35ec6badb2d8eb3ac5b0deeaf0ca923ae2b6c06791f5cca9c57bdf6369c03311",
    "conceito_principal": "Crime impossível e flagrante preparado",
    "habilidade_cobrada": "Correlacionar o Art. 17 do CP com a Súmula 145 do STF",
    "tese_ou_regra": "Art. 17 do CP e Súmula 145/STF",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "42fb036b-3869-50fc-b8ef-a8d3a6a76249",
        "questao_id": "2564647e-bf88-53e5-9f33-28547f506974",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3f8ca8ce-f59f-5860-aa57-abbeba53232c",
        "questao_id": "2564647e-bf88-53e5-9f33-28547f506974",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "c750c812-83ad-5a57-9b5f-0c36160a5f6c",
    "idSlug": "pen-ger-011-legitima-defesa-agente-seguranca",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Considera-se presente a legítima defesa o agente de segurança pública que repele agressão ou risco de agressão a vítima mantida refém durante a prática de crimes.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 25, parágrafo único, do Código Penal (incluído pela Lei 13.964/2019 - Pacote Anticrime) estabelece expressamente que 'considera-se também em legítima defesa o agente de segurança pública que repele agressão ou risco de agressão a vítima mantida refém durante a prática de crimes'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f95456d46c906be132424fb9ca946e9972edd48b18ef44650099dd5f82c32ca3",
    "conceito_principal": "Legítima defesa funcional do agente de segurança pública",
    "habilidade_cobrada": "Conhecer a inovação do Pacote Anticrime no Art. 25, parágrafo único, do CP",
    "tese_ou_regra": "Art. 25, parágrafo único, do Código Penal",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "9cbfe397-f354-57f3-9e8b-a99a0c2724b0",
        "questao_id": "c750c812-83ad-5a57-9b5f-0c36160a5f6c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b904fe70-9c8a-5aa3-9166-8c08254c2b69",
        "questao_id": "c750c812-83ad-5a57-9b5f-0c36160a5f6c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "21a5ced9-c294-5f42-bfc6-3b9816745ca5",
    "idSlug": "pen-ger-012-estado-necessidade-perigo-atual-iminente",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Corpo de Bombeiros Militar",
    "cargo_nome": "Oficial Bombeiro Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Ao contrário da legítima defesa, que admite expressamente a reação contra agressão injusta atual ou iminente, o estado de necessidade, segundo a literalidade do Código Penal brasileiro, exige que o perigo seja atual, não tendo a lei mencionado a figura do perigo iminente.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 24 do CP exige expressamente perigo 'atual' ('quem pratica o fato para salvar de perigo atual...'), enquanto o Art. 25 do CP prevê legítima defesa contra agressão 'atual ou iminente'. Embora parte da doutrina amplie para perigo iminente, a literalidade do texto legal restringe o estado de necessidade ao perigo atual.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "88d1a074ee5987bed923f29412e22b425f75ab4cbebe9f19263e05fac723db61",
    "conceito_principal": "Requisitos temporais do estado de necessidade versus legítima defesa",
    "habilidade_cobrada": "Diferenciar a exigência de perigo atual (Art. 24) e agressão atual ou iminente (Art. 25)",
    "tese_ou_regra": "Arts. 24 e 25 do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "5cd7549a-6f13-5ddb-9e82-24b60e78e001",
        "questao_id": "21a5ced9-c294-5f42-bfc6-3b9816745ca5",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "dcd717aa-eac7-57b3-a958-013858b9851d",
        "questao_id": "21a5ced9-c294-5f42-bfc6-3b9816745ca5",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "13b34385-e596-5ee9-b62f-3bc9024835aa",
    "idSlug": "pen-ger-013-estrito-cumprimento-dever-terceiros",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O policial penal que, no exercício estrito de suas funções regulamentares, cumpre mandado judicial de transferência de custodiado atua sob o manto do estrito cumprimento do dever legal, excludente da culpabilidade que isenta o agente de pena.",
    "explicacao": "GABARITO: ERRADO. Assertiva ERRADA. O estrito cumprimento do dever legal é causa de EXCLUSÃO DA ILICITUDE (ou antijuridicidade), prevista no Art. 23, III, do CP, e não causa excludente da culpabilidade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "12813c8276074ddb68943de4fc0ab50f8b06ae332359eaebca8d5b181c7e4dc6",
    "conceito_principal": "Natureza jurídica do estrito cumprimento do dever legal",
    "habilidade_cobrada": "Classificar as excludentes de ilicitude e diferenciá-las das dirimentes de culpabilidade",
    "tese_ou_regra": "Art. 23 do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "20355936-595f-58b1-b97b-2721d960e677",
        "questao_id": "13b34385-e596-5ee9-b62f-3bc9024835aa",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "933f34c1-cf9a-5a6f-9b44-334f264264e6",
        "questao_id": "13b34385-e596-5ee9-b62f-3bc9024835aa",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "bc688aad-e16a-5300-91dc-a316606d83d4",
    "idSlug": "pen-ger-014-excesso-punivel-modalidades",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O agente que, em qualquer das hipóteses de exclusão da ilicitude, excede os limites da necessidade ou moderação responde pelo excesso doloso ou culposo.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 23, parágrafo único, do CP dispõe: 'O agente, em qualquer das hipóteses deste artigo, responderá pelo excesso doloso ou culposo'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "139283b4100d9eb82bb0ee1b6a702a0246ae779fa009010cc597f3ec2f8e7a13",
    "conceito_principal": "Excesso punível nas excludentes de ilicitude",
    "habilidade_cobrada": "Reconhecer a responsabilidade penal a título de dolo ou culpa pelo excesso",
    "tese_ou_regra": "Art. 23, parágrafo único, do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "511d9e5c-229d-5b65-92b4-426fa7865a03",
        "questao_id": "bc688aad-e16a-5300-91dc-a316606d83d4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d45f789a-34bc-5c6f-a7ac-8cdd4141d84d",
        "questao_id": "bc688aad-e16a-5300-91dc-a316606d83d4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "54aa948a-44e4-5feb-a7a7-3780006ab4d0",
    "idSlug": "pen-ger-015-erro-tipo-essencial-escusavel",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O erro sobre elemento constitutivo do tipo legal de crime (erro de tipo essencial) exclui o dolo, mas permite a punição por crime culposo, se previsto em lei, quando o erro for inescusável (vencível).",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. De acordo com o Art. 20, caput, do CP: 'O erro sobre elemento constitutivo do tipo legal de crime exclui o dolo, mas permite a punição por crime culposo, se previsto em lei'. Se o erro for escusável (invencível), exclui dolo e culpa; se inescusável, exclui o dolo mas subsiste a culpa se houver previsão típica.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b36a6e4727ebb87f5e270042f27daf22c4a0db3c094c86f36715652c887835ce",
    "conceito_principal": "Erro de tipo essencial vencível e invencível",
    "habilidade_cobrada": "Identificar as consequências dogmáticas do erro de tipo no dolo e na culpa",
    "tese_ou_regra": "Art. 20, caput, do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0d201b01-8b4b-56a9-8f8e-e6d8f56721d0",
        "questao_id": "54aa948a-44e4-5feb-a7a7-3780006ab4d0",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "1b655adb-7b32-5b68-9668-f49c8656ccbc",
        "questao_id": "54aa948a-44e4-5feb-a7a7-3780006ab4d0",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "547cd839-7697-57f1-a7cf-093d285668f2",
    "idSlug": "pen-ger-016-erro-proibicao-direto-efeitos",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O erro sobre a ilicitude do fato, se inevitável (escusável), isenta de pena o agente por exclusão da culpabilidade; se evitável (inescusável), não exclui a culpabilidade, podendo a pena ser diminuída de um sexto a um terço.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. Nos termos do Art. 21, caput, do CP: 'O desconhecimento da lei é inescusável. O erro sobre a ilicitude do fato, se inevitável, isenta de pena; se evitável, poderá diminuí-la de um sexto a um terço'. Trata-se de erro de proibição, que atinge o elemento normativo da culpabilidade (potencial consciência da ilicitude).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "35fe5ccd7e657f582a4ccc2901050895f13a6921079cba37b3a36d81f888ea6a",
    "conceito_principal": "Erro de proibição e reflexos na culpabilidade",
    "habilidade_cobrada": "Diferenciar erro de proibição inevitável (isenta de pena) e evitável (causa de diminuição)",
    "tese_ou_regra": "Art. 21 do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "ac728e43-2195-51d8-8ce7-d72bf0681ad8",
        "questao_id": "547cd839-7697-57f1-a7cf-093d285668f2",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b3914feb-2928-5414-bddc-859448d93dd4",
        "questao_id": "547cd839-7697-57f1-a7cf-093d285668f2",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d412d68f-56b4-5cf6-ba66-3f41cab07911",
    "idSlug": "pen-ger-017-coacao-moral-irresistivel-efeitos",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Se o fato é cometido sob coação moral irresistível ou em estrita obediência a ordem, não manifestamente ilegal, de superior hierárquico, só é punível o autor da coação ou da ordem, afastando-se a culpabilidade do coagido pela inexigibilidade de conduta diversa.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 22 do Código Penal disciplina a coação moral irresistível e a obediência hierárquica a ordem não manifestamente ilegal como causas excludentes da culpabilidade (fundadas na inexigibilidade de conduta diversa), transferindo a responsabilidade criminal integralmente ao coator ou emissor da ordem.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d819e8e075a1abc58acbb7d06d166533842904db96fefb0273664cfa76f09816",
    "conceito_principal": "Coação moral irresistível e obediência hierárquica",
    "habilidade_cobrada": "Identificar as hipóteses de inexigibilidade de conduta diversa do Art. 22 do CP",
    "tese_ou_regra": "Art. 22 do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b24547d2-7f96-57fc-ae0b-bd2373395b93",
        "questao_id": "d412d68f-56b4-5cf6-ba66-3f41cab07911",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7fa6a594-7db1-51a2-89d3-01b800043d02",
        "questao_id": "d412d68f-56b4-5cf6-ba66-3f41cab07911",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "430e3b12-a79d-52b0-b116-c87f40635e8d",
    "idSlug": "pen-ger-018-embriaguez-actio-libera-in-causa",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "9d987ff6-bcd4-5ea7-8594-c1123af1384b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A embriaguez voluntária ou culposa, pelo álcool ou substância de efeitos análogos, exclui a imputabilidade penal do agente, desde que seja completa no momento da ação delituosa.",
    "explicacao": "GABARITO: ERRADO. Assertiva ERRADA. O Art. 28, II, do CP estabelece expressamente que 'não excluem a imputabilidade penal: a embriaguez, voluntária ou culposa, pelo álcool ou substância de efeitos análogos'. Aplica-se a teoria da actio libera in causa (a ação era livre no ato de ingerir a substância). Somente a embriaguez completa proveniente de caso fortuito ou força maior exclui a imputabilidade (Art. 28, § 1º, CP).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9d65b376d19b7873c3887e068c14ff03bbbbaff3373f35c3371b7eebfa0cf844",
    "conceito_principal": "Imputabilidade penal e embriaguez não acidental",
    "habilidade_cobrada": "Aplicar a teoria da actio libera in causa prevista no Art. 28, II, do CP",
    "tese_ou_regra": "Art. 28, II c/c § 1º do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c22adbdc-77a9-5ac3-aaa9-f835195aed97",
        "questao_id": "430e3b12-a79d-52b0-b116-c87f40635e8d",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "0733db13-1937-59e8-b66d-24a3a9e78e2b",
        "questao_id": "430e3b12-a79d-52b0-b116-c87f40635e8d",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "a6077e8c-ddb9-5e52-857f-9015b5e79889",
    "idSlug": "pen-ger-019-concurso-pessoas-teoria-monista",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "a432cde8-af56-5530-8700-5bdf6e425b6b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Agente de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O Código Penal brasileiro adotou, como regra geral para o concurso de pessoas, a teoria monista (unitária), segundo a qual todos aqueles que concorrem para o crime incidem nas penas a este cominadas, na medida de sua culpabilidade.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 29, caput, do CP consagra a teoria monista/unitária temperada ou mitigada pela regra da culpabilidade individual: 'Quem, de qualquer modo, concorre para o crime incide nas penas a este cominadas, na medida de sua culpabilidade'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e490b6a683ac2b78bc0c5f16e70fe67aa60d309f415be3871c55f7fd506a7ad6",
    "conceito_principal": "Teoria monista mitigada no concurso de pessoas",
    "habilidade_cobrada": "Reconhecer a adoção da teoria monista pelo Código Penal brasileiro",
    "tese_ou_regra": "Art. 29, caput, do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0412d510-01f6-570b-bd1e-75f719adc359",
        "questao_id": "a6077e8c-ddb9-5e52-857f-9015b5e79889",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "fbda2049-70cc-598a-b0a0-75fd713c044b",
        "questao_id": "a6077e8c-ddb9-5e52-857f-9015b5e79889",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f3aa78d1-3274-567f-b222-163dec0f5b05",
    "idSlug": "pen-ger-020-participacao-menor-importancia",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "a432cde8-af56-5530-8700-5bdf6e425b6b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Escrivão de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "No concurso de pessoas, se a participação for de menor importância, a pena pode ser diminuída de um sexto a um terço, benefício aplicável exclusivamente ao partícipe, não alcançando o coautor que executa atos nucleares do tipo penal.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 29, § 1º, do CP prevê a causa de diminuição da participação de menor importância (1/6 a 1/3). Conforme assentado pela doutrina e jurisprudência pacífica do STF e STJ, essa causa de diminuição é restrita à figura do partícipe (acessoriedade) e não se aplica aos coautores que realizam atos executórios.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a9b16cb003df1da48c430ad0ec7c1e8b941956fcbc89e12f5ead33d465ec3d70",
    "conceito_principal": "Participação de menor importância e inaplicabilidade à coautoria",
    "habilidade_cobrada": "Diferenciar a posição de partícipe e coautor na aplicação do Art. 29, § 1º, do CP",
    "tese_ou_regra": "Art. 29, § 1º, do CP e jurisprudência do STJ",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "116c9adc-b56a-5a3a-9233-acb2dd07d34f",
        "questao_id": "f3aa78d1-3274-567f-b222-163dec0f5b05",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f395cc77-e2c0-5fed-9c75-531f0916fc73",
        "questao_id": "f3aa78d1-3274-567f-b222-163dec0f5b05",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "2e4bd856-e852-5c6f-a9e9-aad542875df6",
    "idSlug": "pen-ger-021-cooperacao-dolosamente-distinta",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "a432cde8-af56-5530-8700-5bdf6e425b6b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Em apuração de crime patrimonial pela Polícia Civil, constatou-se que dois comparsas ajustaram a prática de furto em imóvel desabitado. Durante a execução, contudo, o comparsa que invadiu a casa surpreendeu o morador e, por desígnio próprio e imprevisível ao vigia externo, desferiu golpes que resultaram em roubo impróprio. Nessa hipótese de cooperação dolosamente distinta, tendo o vigia pretendido participar de crime menos grave e não sendo previsível a infração mais severa, ser-lhe-á aplicada exclusivamente a pena do furto.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. Nos termos do Art. 29, § 2º, do Código Penal, na cooperação dolosamente distinta, se algum dos concorrentes quis participar de crime menos grave, ser-lhe-á aplicada a pena deste; a pena somente é exasperada até a metade caso o resultado mais grave fosse previsível. No caso hipotético apresentado, ausente a previsibilidade pelo vigia, este responde apenas pela pena do crime menos grave pretendido (furto).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8912fff7178341243aed9f1998eba2b6e093ef653d809be46a0b20c46374959c",
    "conceito_principal": "Cooperação dolosamente distinta (desvio subjetivo de conduta)",
    "habilidade_cobrada": "Aplicar a regra do Art. 29, § 2º, do CP a hipótese fática policial",
    "tese_ou_regra": "Art. 29, § 2º, do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "72e9f6b2-fd72-53b4-9e7c-ff9e3f32240a",
        "questao_id": "2e4bd856-e852-5c6f-a9e9-aad542875df6",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2bbf9bff-d381-537d-b807-031f88a5e2b8",
        "questao_id": "2e4bd856-e852-5c6f-a9e9-aad542875df6",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a1bb55f8-1c55-5881-a743-324e07ce80bd",
    "idSlug": "pen-ger-022-comunicabilidade-elementares-circunstancias",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "a432cde8-af56-5530-8700-5bdf6e425b6b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Não se comunicam as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime, hipótese em que se estendem aos demais coautores e partícipes que delas tenham conhecimento.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 30 do CP estabelece: 'Não se comunicam as circunstâncias e as condições de caráter pessoal, salvo quando elementares do crime'. Exemplo clássico: a condição de funcionário público no crime de peculato (Art. 312 CP) comunica-se ao particular concorrente se este sabia de tal condição.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8a15a8bed47327697138bdec329eea529d2d5a474af488054997041328abcc15",
    "conceito_principal": "Incomunicabilidade de circunstâncias pessoais e ressalva das elementares",
    "habilidade_cobrada": "Interpretar o Art. 30 do CP e sua aplicação aos crimes funcionais",
    "tese_ou_regra": "Art. 30 do Código Penal",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "ed95c091-802a-52b3-9d9e-5e90c4621491",
        "questao_id": "a1bb55f8-1c55-5881-a743-324e07ce80bd",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ab25d70c-f399-575a-b892-37c457063095",
        "questao_id": "a1bb55f8-1c55-5881-a743-324e07ce80bd",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "37779321-2d5c-59c0-8daf-7d000dfaf8f9",
    "idSlug": "pen-ger-023-autoria-mediata-requisitos",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "a432cde8-af56-5530-8700-5bdf6e425b6b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Configura-se a autoria mediata quando o autor se serve de um executor que atua sem culpabilidade (como um inimputável ou pessoa sob coação moral irresistível) ou em erro de tipo invencível provocado, dominando a vontade finalística da conduta sem executar pessoalmente o verbo nuclear.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. Na autoria mediata, o autor mediato domina o fato utilizando uma pessoa como mero instrumento de sua vontade (inimputável, coagido moralmente de forma irresistível, ou pessoa induzida em erro de tipo escusável pelo mandante).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "05a9782b2ca649ee6fe0d1d0543b33b44b27f46c4c545f1b0cfeac9921c0fbdf",
    "conceito_principal": "Conceito e hipóteses de autoria mediata",
    "habilidade_cobrada": "Compreender o domínio do fato através de instrumento não culpável ou enganado",
    "tese_ou_regra": "Teoria do Domínio do Fato e Arts. 20, § 2º e 22 do CP",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a8aea7e2-6d5d-5a12-8c43-e76378846ee8",
        "questao_id": "37779321-2d5c-59c0-8daf-7d000dfaf8f9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "49c7df88-644a-5255-8a29-40a41b1285f2",
        "questao_id": "37779321-2d5c-59c0-8daf-7d000dfaf8f9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "aafee78e-d961-5de2-a7ac-07457e0a4dfe",
    "idSlug": "pen-ger-024-prescricao-pretensao-punitiva-interrupcao",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "e54c36d6-6d7f-5e1c-891d-4625bbeccd80",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O recebimento da denúncia ou da queixa e a publicação da sentença ou acórdão condenatórios recorríveis são marcos interruptivos da prescrição da pretensão punitiva, operando a interrupção a perda do tempo já decorrido e o reinício integral da contagem do prazo prescricional.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. O Art. 117, I e IV, do Código Penal elenca o recebimento da peça acusatória e a publicação da sentença ou acórdão condenatório recorrível como causas interruptivas da prescrição. Nos termos do § 2º do mesmo artigo, a interrupção da prescrição faz com que todo o prazo prescricional recomece a correr do zero a partir do dia da interrupção.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0cd776b7b974f6cfcef809c81a58185fcb1ad1969e953352828c771e6b286c3a",
    "conceito_principal": "Causas de interrupção da prescrição penal",
    "habilidade_cobrada": "Identificar os marcos interruptivos do Art. 117 do CP e o efeito do reinício do prazo",
    "tese_ou_regra": "Art. 117, I e IV c/c § 2º do Código Penal",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "d526e549-d451-5334-9d36-57c37bf07267",
        "questao_id": "aafee78e-d961-5de2-a7ac-07457e0a4dfe",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "c19b9656-e6b2-5688-99a9-44dd61646612",
        "questao_id": "aafee78e-d961-5de2-a7ac-07457e0a4dfe",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ab067669-663e-5d75-857a-95efffe0d836",
    "idSlug": "pen-ger-025-perdao-judicial-efeitos",
    "disciplina_id": "29f5164e-c850-5fa5-a29b-3c0b5d6e41e6",
    "assunto_id": "e54c36d6-6d7f-5e1c-891d-4625bbeccd80",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A sentença concessiva de perdão judicial é declaratória da extinção da punibilidade, não subsistindo qualquer efeito condenatório, principal ou secundário, nem gerando reincidência para o agente beneficiado.",
    "explicacao": "GABARITO: CERTO. Assertiva CORRETA. Conforme a Súmula 18 do STJ: 'A sentença concessiva do perdão judicial é declaratória da extinção da punibilidade, não subsistindo qualquer efeito condenatório'. Não gera reincidência, não lança o nome no rol dos culpados e não serve como título executivo cível.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1058a60f3db2efe7ccb655683ee550e1573293866e51f9bd3fa987283c2120aa",
    "conceito_principal": "Natureza jurídica e efeitos da sentença de perdão judicial",
    "habilidade_cobrada": "Aplicar a Súmula 18 do STJ e o Art. 107, IX, do CP",
    "tese_ou_regra": "Súmula 18 do STJ e Art. 120 do Código Penal",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5d44e77b-7b09-583d-a426-de035e46cbaf",
        "questao_id": "ab067669-663e-5d75-857a-95efffe0d836",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "51d85b59-3da9-5d3f-98a4-92982811bded",
        "questao_id": "ab067669-663e-5d75-857a-95efffe0d836",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  }
];
