import { TAXONOMIA } from "./taxonomia.mjs";

export const dh02Questoes = [
  {
    idSlug: "dh-029",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "As Regras Mínimas das Nações Unidas para o Tratamento de Reclusos (Regras de Mandela, Resolução 70/175 da ONU, 2015), em sua Regra 1:",
    explicacao: "GABARITO: A. Regra 1 das Regras de Mandela: 'Todos os reclusos serão tratados com o respeito devido ao seu valor intrínseco e à sua dignidade enquanto seres humanos. Nenhum recluso será submetido a tortura ou outras penas ou tratamentos cruéis, desumanos ou degradantes...'.",
    alternativas: [
      { letra: "A", texto: "estabelecem que todos os reclusos serão tratados com o respeito devido ao seu valor intrínseco e dignidade como seres humanos, sendo vedada qualquer forma de tortura ou tratamento cruel.", correta: true },
      { letra: "B", texto: "permitem o confinamento solitário de gestantes por até 60 dias.", correta: false },
      { letra: "C", texto: "dispensam a oferta de alimentação diária nos finais de semana.", correta: false },
      { letra: "D", texto: "autorizam a aplicação de castigos corporais por faltas disciplinares graves.", correta: false },
      { letra: "E", texto: "determinam o uso de grilhões e correntes de ferro em todos os deslocamentos internos.", correta: false }
    ]
  },
  {
    idSlug: "dh-030",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "De acordo com as Regras de Mandela (Regras 43 a 45), o isolamento celular prolongado é definido como o confinamento solitário por mais de 15 dias consecutivos, sendo expressamente proibido, assim como o isolamento em cela escura ou iluminada permanentemente.",
    explicacao: "GABARITO: CERTO. Regras 43 e 44 das Regras de Mandela: O isolamento prolongado (mais de 15 dias consecutivos) e o confinamento solitário indefinido são expressamente proibidos, bem como a colocação de reclusos em celas escuras ou continuamente iluminadas.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-031",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação ao uso de instrumentos de contenção física (como algemas ou correntes) nas Regras de Mandela (Regra 47):",
    explicacao: "GABARITO: C. Regra 47 das Regras de Mandela: É terminantemente proibido o uso de correntes, ferros e outros instrumentos de contenção física inerentemente degradantes ou dolorosos, e o uso de algemas nunca deve ser aplicado como sanção disciplinar.",
    alternativas: [
      { letra: "A", texto: "são recomendados como principal forma de punição disciplinar para indisciplina verbal.", correta: false },
      { letra: "B", texto: "podem ser mantidos durante todo o período de repouso noturno dos presos provisórios.", correta: false },
      { letra: "C", texto: "é expressamente proibido o uso de correntes, ferros ou instrumentos inerentemente dolorosos, não podendo instrumentos de contenção ser aplicados como sanção disciplinar.", correta: true },
      { letra: "D", texto: "devem ser utilizados obrigatoriamente durante as consultas médicas de rotina.", correta: false },
      { letra: "E", texto: "são de uso discricionário dos outros reclusos designados monitores.", correta: false }
    ]
  },
  {
    idSlug: "dh-032",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Conforme as Regras de Mandela (Regra 24 a 35), os serviços de saúde prestados no estabelecimento prisional devem gozar de plena independência clínica em relação à administração penitenciária, assegurando aos reclusos o mesmo padrão de assistência médica disponível na comunidade.",
    explicacao: "GABARITO: CERTO. Regras 24 a 35 das Regras de Mandela: Consagram o princípio da equivalência dos cuidados de saúde e a independência ética e clínica dos profissionais de saúde prisional.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-033",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Sobre a revista íntima e inspeção de visitantes e reclusos nas Regras de Mandela (Regras 50 a 52 e 60):",
    explicacao: "GABARITO: D. Regras 50 a 52 e 60 das Regras de Mandela: As revistas devem respeitar a dignidade humana, ser realizadas em local reservado por pessoa do mesmo gênero e evitar métodos intrusivos/invasivos, devendo a administração priorizar o uso de tecnologias e scanners corporais.",
    alternativas: [
      { letra: "A", texto: "as revistas invasivas com desnudamento total são obrigatórias a todos os visitantes indistintamente.", correta: false },
      { letra: "B", texto: "a revista pode ser realizada em praça pública para dissuasão da criminalidade.", correta: false },
      { letra: "C", texto: "agentes de sexo oposto devem realizar a revista íntima em nome da igualdade formal.", correta: false },
      { letra: "D", texto: "as inspeções corporais invasivas devem ser medidas excepcionais de último recurso, conduzidas com respeito estrito à dignidade e privacidade, preferindo-se o uso de equipamentos eletrônicos não invasivos.", correta: true },
      { letra: "E", texto: "é proibida a revista de advogados e defensores públicos por detectores de metais.", correta: false }
    ]
  },
  {
    idSlug: "dh-034",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_bangkok,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "As Regras das Nações Unidas para o Tratamento de Mulheres Presas e Medidas Não Privativas de Liberdade para Mulheres Infratoras (Regras de Bangkok, 2010):",
    explicacao: "GABARITO: B. Regras de Bangkok: Têm como premissa que as mulheres presas possuem necessidades de gênero específicas (físicas, biológicas, reprodutivas, psicológicas e sociais) que exigem tratamento diferenciado para assegurar a real igualdade substantiva.",
    alternativas: [
      { letra: "A", texto: "estabelecem que mulheres e homens devem ser submetidos a regimes prisionais idênticos sem qualquer consideração de gênero.", correta: false },
      { letra: "B", texto: "reconhecem as necessidades específicas de gênero das mulheres privadas de liberdade, contemplando cuidados em saúde reprodutiva, maternidade, acolhimento de filhos e proteção contra violência.", correta: true },
      { letra: "C", texto: "proíbem as visitas íntimas a mulheres casadas em cumprimento de pena.", correta: false },
      { letra: "D", texto: "exigem o cumprimento da pena em estabelecimentos militares de segurança máxima.", correta: false },
      { letra: "E", texto: "determinam a separação sumária e definitiva da mãe de seu recém-nascido no momento do parto.", correta: false }
    ]
  },
  {
    idSlug: "dh-035",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_bangkok,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "De acordo com a Regra 24 das Regras de Bangkok e a Súmula Vinculante nº 11 do STF (reforçada pelo art. 292, parágrafo único, do CPP), é terminantemente vedado o emprego de algemas em mulheres grávidas durante os atos médico-hospitalares preparatórios para a realização do parto, durante o trabalho de parto e no período de puerpério imediato.",
    explicacao: "GABARITO: CERTO. Regra 24 de Bangkok, art. 292, parágrafo único, do CPP e Lei nº 13.434/2017: É proibido o uso de algemas em mulheres durante o trabalho de parto, trajeto hospitalar e puerpério imediato.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-036",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_bangkok,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme a Regra 22 das Regras de Bangkok, as sanções de isolamento celular ou segregação disciplinar:",
    explicacao: "GABARITO: A. Regra 22 das Regras de Bangkok: 'Sanções disciplinares para mulheres presas não deverão incluir a proibição do contato com a família, especialmente com as crianças. A sanção de isolamento não deve ser aplicada a mulheres grávidas, lactantes ou com crianças no estabelecimento prisional.'",
    alternativas: [
      { letra: "A", texto: "não devem ser aplicadas a gestantes, lactantes, nem a mulheres acompanhadas de bebês no estabelecimento prisional.", correta: true },
      { letra: "B", texto: "devem ser aplicadas automaticamente a qualquer mulher que engravidar na prisão.", correta: false },
      { letra: "C", texto: "podem perdurar por até dois anos sem autorização médica.", correta: false },
      { letra: "D", texto: "devem incluir a proibição total e perpétua de contato telefônico com os filhos.", correta: false },
      { letra: "E", texto: "são executadas privativamente por decisão da defensoria pública.", correta: false }
    ]
  },
  {
    idSlug: "dh-037",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos termos dos Princípios Básicos sobre o Uso da Força e Armas de Fogo pelos Funcionários Responsáveis pela Aplicação da Lei (PBUFAF da ONU, 1990, Princípio 9), os agentes da lei só poderão fazer uso letal intencional de armas de fogo:",
    explicacao: "GABARITO: C. Princípio 9 dos PBUFAF: O uso intencional de armas letais só é permitido quando estritamente inevitável para proteger a vida humana diante de uma ameaça iminente de morte ou lesão grave.",
    alternativas: [
      { letra: "A", texto: "para interromper qualquer fuga de veículo automotor que fure blitz de trânsito.", correta: false },
      { letra: "B", texto: "para dispersar protestos e manifestações pacíficas em praças públicas.", correta: false },
      { letra: "C", texto: "quando for estritamente inevitável para proteger a vida humana contra perigo iminente de morte ou lesão grave.", correta: true },
      { letra: "D", texto: "em caso de desacato verbal praticado sem contato físico.", correta: false },
      { letra: "E", texto: "para proteger patrimônio móvel privado desabitado contra vandalismo.", correta: false }
    ]
  },
  {
    idSlug: "dh-038",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "De acordo com a Portaria Interministerial nº 4.226/2010 (Diretrizes sobre o Uso da Força pelos Agentes de Segurança Pública), o uso da força por agentes de segurança pública deverá obedecer aos princípios da legalidade, necessidade, proporcionalidade, moderação e conveniência.",
    explicacao: "GABARITO: CERTO. Portaria Interministerial SEDH/MJ nº 4.226/2010, Diretriz 2: O uso da força é regido pelos princípios da legalidade, necessidade, proporcionalidade, moderação e conveniência.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-039",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Segundo a Diretriz nº 3 da Portaria Interministerial nº 4.226/2010, no planejamento e na execução operacional das forças de segurança pública:",
    explicacao: "GABARITO: B. Portaria Interministerial nº 4.226/2010, Diretriz 3: O Estado deve priorizar e disponibilizar instrumentos e armamentos de menor potencial ofensivo (IMPO) para que os policiais tenham alternativas escalonadas ao uso de armas de fogo letais.",
    alternativas: [
      { letra: "A", texto: "é proibida a aquisição de equipamentos de menor potencial ofensivo pelas instituições policiais.", correta: false },
      { letra: "B", texto: "deverá ser priorizado o emprego de instrumentos de menor potencial ofensivo, garantindo aos agentes capacitação contínua para sua utilização escalonada.", correta: true },
      { letra: "C", texto: "as armas de fogo letais devem ser a primeira opção de intervenção em qualquer desordem civil.", correta: false },
      { letra: "D", texto: "os agentes de segurança não respondem administrativa ou penalmente por excessos operacionais.", correta: false },
      { letra: "E", texto: "o uso de spray de pimenta é classificado como arma de destruição em massa.", correta: false }
    ]
  },
  {
    idSlug: "dh-040",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Conforme a Portaria Interministerial nº 4.226/2010 (Diretriz 4), não é legítimo o uso de arma de fogo contra pessoa em fuga que esteja desarmada ou que, mesmo armada, não represente risco imediato de morte ou de lesão grave aos agentes de segurança ou a terceiros.",
    explicacao: "GABARITO: CERTO. Portaria Interministerial nº 4.226/2010, Diretriz 4: 'Não é legítimo o uso de arma de fogo: a) contra pessoa em fuga que esteja desarmada ou que, mesmo armada, não represente risco imediato de morte ou de lesão grave...; b) contra veículo que desobedeça a bloqueio policial...'",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-041",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Sempre que o uso da força resultar em ferimentos ou morte de qualquer pessoa, o agente de segurança pública tem o dever imediato de (PBUFAF da ONU, Princípio 5, e Portaria nº 4.226/2010):",
    explicacao: "GABARITO: A. Princípio 5 dos PBUFAF da ONU e Diretriz 5 da Portaria nº 4.226/2010: Determinam o dever de prestar e assegurar socorro e assistência médica imediata às pessoas feridas, bem como comunicar o fato aos seus familiares e formalizar relatório circunstanciado à autoridade competente.",
    alternativas: [
      { letra: "A", texto: "prestar ou providenciar imediata assistência e socorro médico ao ferido e comunicar o fato com brevidade aos parentes e à autoridade competente.", correta: true },
      { letra: "B", texto: "abandonar o local da ocorrência e recolher-se ao quartel sem lavrar ocorrência.", correta: false },
      { letra: "C", texto: "apagar os registros de câmeras corporais para evitar repercussão na imprensa.", correta: false },
      { letra: "D", texto: "aguardar a autorização expressa do juiz corregedor antes de solicitar atendimento do SAMU.", correta: false },
      { letra: "E", texto: "transportar o ferido no porta-malas da viatura mesmo com ambulância disponível.", correta: false }
    ]
  },
  {
    idSlug: "dh-042",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Nos termos da Resolução nº 348/2020 do Conselho Nacional de Justiça (CNJ), a pessoa autodeclarada transgênero, transexual, travesti ou intersexo privada de liberdade tem o direito à autodeclaração de gênero, a ser chamada pelo seu nome social e a optar por cumprir pena em estabelecimento prisional feminino, masculino ou em ala específica destinada ao público LGBTQIA+.",
    explicacao: "GABARITO: CERTO. Resolução CNJ nº 348/2020 e ADPF 527 do STF: Garantem a autodeterminação de gênero da pessoa presa LGBTQIA+, o respeito ao nome social e o direito de escolha pelo local de custódia mais seguro e adequado.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-043",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em relação à abordagem policial e busca pessoal motivada unicamente pela cor da pele ou padrão estético do indivíduo (perfilamento racial / racial profiling), o Superior Tribunal de Justiça (RHC 158.840/SP):",
    explicacao: "GABARITO: C. STJ (RHC 158.840/SP): O perfilamento racial no policiamento ostensivo e na realização de busca pessoal sem justa causa concreta e individualizada é ilícito, discriminatório e contamina de nulidade absoluta todas as provas dele decorrentes.",
    alternativas: [
      { letra: "A", texto: "declarou que o tirocínio policial autoriza buscas baseadas exclusivamente em impressões subjetivas sobre a raça do suspeito.", correta: false },
      { letra: "B", texto: "considerou lícita a seleção de abordagens com base na etnia em áreas de periferia urbana.", correta: false },
      { letra: "C", texto: "reconheceu a ilicitude do perfilamento racial, fixando que a busca pessoal exige justa causa fundada em elementos objetivos, sendo nulas as provas obtidas por critérios discriminatórios.", correta: true },
      { letra: "D", texto: "determinou que a busca pessoal prescinde de justa causa em qualquer situação.", correta: false },
      { letra: "E", texto: "isenta de responsabilidade os agentes envolvidos em abordagens abusivas coletivas.", correta: false }
    ]
  },
  {
    idSlug: "dh-044",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Convenção sobre os Direitos das Pessoas com Deficiência da ONU (2006), aprovada no Brasil nos termos do art. 5º, § 3º, da Constituição Federal (Decreto nº 6.949/2009), possui equivalência formal e material de Emenda Constitucional, impondo a garantia de acessibilidade plena e adaptações razoáveis em delegacias e estabelecimentos prisionais.",
    explicacao: "GABARITO: CERTO. Decreto nº 6.949/2009: A Convenção da ONU sobre os Direitos das Pessoas com Deficiência foi o primeiro tratado de direitos humanos aprovado pelo rito qualificado do art. 5º, § 3º, da CF/88, tendo estatura constitucional.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-045",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "No atendimento a vítimas de violência doméstica, crianças e adolescentes nas delegacias e postos da guarda municipal, o protocolo de escuta protegida e depoimento especial (Lei nº 13.431/2017) tem por objetivo principal:",
    explicacao: "GABARITO: B. Lei nº 13.431/2017: Visa assegurar que crianças e adolescentes vítimas ou testemunhas de violência sejam ouvidos por profissionais especializados em ambiente acolhedor, prevenindo a revitimização (vitimização secundária) decorrente de inquirições sucessivas e traumáticas.",
    alternativas: [
      { letra: "A", texto: "acelerar a aplicação de castigos corporais em sede policial.", correta: false },
      { letra: "B", texto: "evitar a violência institucional e a revitimização da criança ou adolescente por meio de procedimento humanizado e especializado.", correta: true },
      { letra: "C", texto: "promover o confronto direto entre a vítima infantil e o suspeito agressor.", correta: false },
      { letra: "D", texto: "dispensar a presença de psicólogos e assistentes sociais no acolhimento.", correta: false },
      { letra: "E", texto: "publicar os depoimentos em redes sociais institucionais.", correta: false }
    ]
  },
  {
    idSlug: "dh-046",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Nos termos da Resolução nº 287/2019 do CNJ e da Convenção 169 da OIT, ao processar criminalmente ou custodiar pessoa indígena, as autoridades devem garantir a presença de intérprete na sua língua materna, considerar os costumes e a identidade sociocultural da comunidade indígena e comunicar a Fundação Nacional dos Povos Indígenas (FUNAI).",
    explicacao: "GABARITO: CERTO. Resolução CNJ nº 287/2019 e Convenção 169 da OIT: Estabelecem diretrizes específicas para o tratamento de pessoas indígenas acusadas, rés ou condenadas no sistema de justiça criminal, garantindo respeito à sua cultura, intérprete e comunicação ao órgão indigenista.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-047",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Em relação ao direito de contato com o mundo exterior garantido aos presos nas Regras de Mandela (Regra 58):",
    explicacao: "GABARITO: C. Regra 58 das Regras de Mandela: 'Os reclusos serão autorizados, sob supervisão necessária, a comunicar com as suas famílias e amigos, em intervalos regulares: a) Por correspondência escrita e através de meios de telecomunicações, eletrónicos ou digitais...; b) Ao receber visitas.'",
    alternativas: [
      { letra: "A", texto: "o contato com a família e advogados pode ser proibido sumariamente por até 5 anos.", correta: false },
      { letra: "B", texto: "só é permitida a comunicação com parentes em linha reta que residam na mesma cidade da prisão.", correta: false },
      { letra: "C", texto: "os reclusos devem ser autorizados a comunicar-se regularmente com seus familiares e amigos por meio de correspondência e visitas regulares.", correta: true },
      { letra: "D", texto: "as visitas de defensores públicos são limitadas a uma vez a cada semestre.", correta: false },
      { letra: "E", texto: "o envio de cartas para tribunais e órgãos de direitos humanos é terminantemente censurado.", correta: false }
    ]
  },
  {
    idSlug: "dh-048",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O princípio da proporcionalidade no uso da força policial estabelece que o nível de força aplicado pelo agente da lei deve ser moderado e estritamente compatível com a gravidade da ameaça ou da resistência apresentada pelo suspeito.",
    explicacao: "GABARITO: CERTO. Doutrina de uso diferenciado da força e Portaria nº 4.226/2010: A proporcionalidade impõe que a intensidade e a modalidade de força empregada sejam estritamente proporcionais à agressão ou resistência encontrada.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-049",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Quanto à alimentação dos presos, a Regra 22 das Regras de Mandela determina que a administração prisional deve fornecer:",
    explicacao: "GABARITO: A. Regra 22 das Regras de Mandela: 'A todo recluso será fornecido pela administração prisional, em horários regulares, alimentos de valor nutricional adequado para a saúde e resistência, de boa qualidade, bem preparados e servidos.' Água potável deve estar disponível a qualquer momento.",
    alternativas: [
      { letra: "A", texto: "alimentos de valor nutricional adequado à saúde e higidez física, bem preparados e servidos em horários regulares, além de água potável disponível a todo momento.", correta: true },
      { letra: "B", texto: "apenas uma refeição diária para conter despesas de custeio.", correta: false },
      { letra: "C", texto: "alimentos exclusivamente mediante compra pelos próprios presos em cantina privada.", correta: false },
      { letra: "D", texto: "ração militar de combate desidratada como padrão permanente.", correta: false },
      { letra: "E", texto: "água tratada apenas aos reclusos que apresentarem bom comportamento carcerário.", correta: false }
    ]
  },
  {
    idSlug: "dh-050",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "As inspeções internas e externas e os mecanismos independentes de monitoramento das prisões (como conselhos penitenciários, comitês de prevenção à tortura e visitas judiciais) são considerados pelas Regras de Mandela instrumentos obrigatórios para a garantia dos direitos fundamentais dos reclusos.",
    explicacao: "GABARITO: CERTO. Regras 83 a 85 das Regras de Mandela: Estabelecem o sistema de inspeções internas e externas periódicas realizadas por órgãos independentes como pilar essencial na prevenção de abusos e garantia de condições dignas.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-051",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O uso progressivo e diferenciado da força policial compreende a seguinte gradação operacional frente a um cidadão cooperativo ou resistente passivo:",
    explicacao: "GABARITO: B. No modelo de uso diferenciado da força: 1) Presença policial ostensiva; 2) Comunicação verbal / verbalização profissional; 3) Controle de contato / mãos livres; 4) Técnicas de imobilização / armas de menor potencial ofensivo; 5) Força letal (exclusivamente para risco iminente à vida).",
    alternativas: [
      { letra: "A", texto: "disparo imediato de advertência com fuzil, seguido de interrogatório sumário.", correta: false },
      { letra: "B", texto: "presença policial fardada ostensiva, seguida de verbalização e persuasão pacífica, antes de qualquer emprego de força física.", correta: true },
      { letra: "C", texto: "uso de cão de ataque como primeira opção de comunicação.", correta: false },
      { letra: "D", texto: "condução coercitiva sem identificação prévia da autoridade policial.", correta: false },
      { letra: "E", texto: "apreensão sumária de aparelhos celulares de todas as testemunhas presentes.", correta: false }
    ]
  },
  {
    idSlug: "dh-052",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Policial Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O chamado 'disparo de advertência' para o alto em via pública habitada é expressamente desaconselhado pelas normas internacionais de direitos humanos e diretrizes operacionais modernas, em razão do elevado risco de atingir terceiros inocentes em decorrência de ricochete ou balística terminal.",
    explicacao: "GABARITO: CERTO. Doutrina moderna e manuais de uso da força (incluindo diretrizes da SENASP/MJ): Disparos de advertência geram perigo comum e são vedados ou fortemente desaconselhados pela imprevisibilidade da trajetória dos projéteis.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-053",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.regras_mandela,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "De acordo com a Regra 23 das Regras de Mandela, a todo recluso que não exerça trabalho ao ar livre deve ser assegurado, diariamente e se o tempo permitir:",
    explicacao: "GABARITO: D. Regra 23.1 das Regras de Mandela: 'A todo recluso que não participe em trabalho ao ar livre será assegurado pelo menos uma hora por dia de exercício adequado ao ar livre, se o tempo o permitir.' (banho de sol diário).",
    alternativas: [
      { letra: "A", texto: "acesso a piscina térmica individual por 4 horas.", correta: false },
      { letra: "B", texto: "saída para almoço em restaurante conveniado no centro urbano.", correta: false },
      { letra: "C", texto: "dispensa integral do cumprimento da pena privativa de liberdade.", correta: false },
      { letra: "D", texto: "ao menos uma hora de exercício físico diário ao ar livre (banho de sol).", correta: true },
      { letra: "E", texto: "permissão para portar aparelhos transmissores de rádio.", correta: false }
    ]
  },
  {
    idSlug: "dh-054",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.grupos_vulneraveis,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No atendimento a pessoas idosas vítimas de crimes, a autoridade policial deve assegurar prioridade especial no atendimento e na tramitação dos procedimentos investigativos, com preferência ainda mais acentuada aos maiores de 80 anos, conforme o Estatuto da Pessoa Idosa (Lei nº 10.741/2003).",
    explicacao: "GABARITO: CERTO. Art. 3º, § 2º, e art. 71 da Lei nº 10.741/2003: Assegura prioridade na tramitação de procedimentos e preferência especial aos maiores de 80 anos.",
    alternativas: [{ texto: "Certo", correta: true }, { texto: "Errado", correta: false }]
  },
  {
    idSlug: "dh-055",
    disciplina_id: TAXONOMIA.disciplinas.direitos_humanos,
    assunto_id: TAXONOMIA.assuntos.uso_forca_policial,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Convenção Contra a Tortura e Outros Tratamentos ou Penas Cruéis, Desumanos ou Degradantes da ONU (1984) estabelece, em seu Artigo 2º, item 2, que:",
    explicacao: "GABARITO: A. Artigo 2.2 da Convenção da ONU contra a Tortura: 'Em nenhum caso poderão invocar-se circunstâncias excepcionais, tais como estado de guerra ou ameaça de guerra, instabilidade política interna ou qualquer outra emergência pública, como justificação para a tortura.' Trata-se de proibição absoluta inderrogável.",
    alternativas: [
      { letra: "A", texto: "nenhuma circunstância excepcional, mesmo em estado de guerra, instabilidade política ou ameaça de emergência pública, pode ser invocada para justificar a tortura.", correta: true },
      { letra: "B", texto: "a tortura é lícita quando autorizada expressamente pelo Conselho de Ministros.", correta: false },
      { letra: "C", texto: "o cumprimento de ordens de superiores hierárquicos exime totalmente a ilicitude do ato de tortura.", correta: false },
      { letra: "D", texto: "as declarações obtidas sob tortura podem ser aproveitadas em prejuízo do réu se corroboradas por testemunhas.", correta: false },
      { letra: "E", texto: "o crime de tortura prescreve em 2 anos contados da ocorrência do fato.", correta: false }
    ]
  }
];
