import { DISCIPLINAS, ASSUNTOS, criarQuestaoCE, criarQuestaoME, writeModuleFile } from "./helpers.mjs";

// ==============================================================
// M11: DIREITO CONSTITUCIONAL - DIREITOS FUNDAMENTAIS E SEGURANÇA PÚBLICA (20 questões)
// ==============================================================
const m11_data = [
  {
    tipo: "CE",
    slug: "l13-const-dir-001-inviolabilidade-domicilio-stf-tema280",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "A entrada forçada em domicílio sem mandado judicial, mesmo em período noturno, é lícita quando amparada em fundadas razões, devidamente justificadas pelas circunstâncias fáticas prévias, que indiquem a ocorrência de flagrante delito no interior da residência, sob pena de responsabilidade disciplinar, civil e penal do agente e de nulidade dos atos praticados.",
    explicacao: "GABARITO: CERTO. Tese de repercussão geral fixada pelo STF no Tema 280 (RE 603.616): a busca domiciliar sem mandado em flagrante exige justa causa prévia e motivação ex ante.",
    gabaritoCerto: true,
    conceito: "Inviolabilidade domiciliar e justa causa prévia (STF Tema 280)",
    habilidade: "Aplicar a tese do Tema 280 do STF à atuação policial em busca domiciliar",
    tese: "Entrada em domicílio sem mandado exige fundadas razões justificadas ex ante",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-002-direito-reuniao-aviso-previo-stf",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "O exercício da liberdade de reunião em locais abertos ao público independe de autorização do Poder Público, exigindo a Constituição prévio aviso para não frustrar outra reunião convocada para o mesmo local; contudo, o STF pacificou que a ausência de notificação formal prévia não torna a reunião automaticamente ilícita se a autoridade policial tomou conhecimento da manifestação por outros meios.",
    explicacao: "GABARITO: CERTO. STF no Tema 855 (RE 1.291.076) fixou que a exigência constitucional de aviso prévio é satisfeita com a veiculação de informação que permita ao poder público zelar pela segurança e trânsito, não sendo condição de ilicitude do ato.",
    gabaritoCerto: true,
    conceito: "Liberdade de reunião pacífica e flexibilização do aviso prévio",
    habilidade: "Compreender os contornos do direito de reunião segundo a jurisprudência do STF",
    tese: "Aviso prévio em reuniões públicas não condiciona a legitimidade da manifestação",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-003-sigilo-correspondencia-preso-stf",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "A cláusula constitucional da inviolabilidade do sigilo de correspondência não possui caráter absoluto, sendo legítima a interceptação e fiscalização excepcional de cartas endereçadas a pessoas privadas de liberdade pela administração penitenciária quando houver fundada suspeita de prática de infrações penais ou planejamento de ações ilícitas.",
    explicacao: "GABARITO: CERTO. O STF pacificou que a inviolabilidade de correspondência não pode ser utilizada como escudo protetivo para a prática de delitos no interior do sistema carcerário.",
    gabaritoCerto: true,
    conceito: "Relatividade dos direitos fundamentais e correspondência de presos",
    habilidade: "Avaliar a legitimidade da fiscalização penitenciária de correspondências",
    tese: "Direitos fundamentais não são absolutos e admitem ponderação diante de segurança pública",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-004-habeas-data-acesso-informacoes-pessoais",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "facil",
    enunciado: "O habeas data é remédio constitucional adequado para assegurar o conhecimento de registros e informações relativos à pessoa do impetrante constantes de bancos de dados de entidades governamentais ou de caráter público, exigindo-se a comprovação de prévia recusa ou omissão administrativa para configuração do interesse de agir.",
    explicacao: "GABARITO: CERTO. Art. 5º, LXXII da CF/88 e Súmula 2 do STJ: o habeas data exige prova documental da recusa administrativa ou decurso de prazo sem resposta.",
    gabaritoCerto: true,
    conceito: "Habeas Data e requisito de recusa administrativa prévia",
    habilidade: "Reconhecer o cabimento e requisitos processuais do habeas data",
    tese: "O habeas data tutela dados personalíssimos e exige recusa administrativa prévia",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-const-dir-005-mandado-seguranca-coletivo-legitimidade",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Em matéria de garantias constitucionais, o mandado de segurança coletivo pode ser impetrado por partido político com representação no Congresso Nacional, organização sindical, entidade de classe ou associação legalmente constituída. A respeito da legitimidade ativa das associações para impetração de mandado de segurança coletivo, assinale a afirmativa correta segundo a CF/88 e a jurisprudência do STF.",
    explicacao: "GABARITO: A. Art. 5º, LXX, 'b' da CF/88 e Súmula 629 do STF: a associação precisa estar em funcionamento há pelo menos 1 ano, mas a impetração de MS coletivo independe de autorização expressa dos associados (substituição processual).",
    alternativas: [
      { letra: "A", texto: "A associação deve estar constituída e em funcionamento há pelo menos um ano, em defesa de direitos de seus associados, dispensada autorização especial para o MS coletivo.", correta: true, explicacao_especifica: "Correta. Art. 5º, LXX, 'b' da CF/88 e Súmula 629 do STF." },
      { letra: "B", texto: "Exige-se autorização individual expressa e assemblear de cada um dos associados representados.", correta: false, explicacao_especifica: "Incorreta. Em MS coletivo trata-se de substituição processual que prescinde de procuração individual." },
      { letra: "C", texto: "A associação deve ter pelo menos dez anos de fundação e abrangência nacional obrigatória.", correta: false, explicacao_especifica: "Incorreta. O prazo constitucional é de 1 ano e não se exige abrangência nacional." },
      { letra: "D", texto: "Partidos políticos necessitam comprovar um ano de registro no TSE antes de qualquer impetração.", correta: false, explicacao_especifica: "Incorreta. Para partidos basta representação no Congresso Nacional (1 deputado ou 1 senador)." },
      { letra: "E", texto: "É vedada a impetração para tutelar direitos individuais homogêneos de servidores policiais.", correta: false, explicacao_especifica: "Incorreta. É amplamente cabível para tutela de direitos individuais homogêneos." }
    ],
    conceito: "Mandado de segurança coletivo e legitimidade das associações",
    habilidade: "Identificar os requisitos de legitimidade ativa das associações em MS coletivo",
    tese: "Associações com 1 ano de funcionamento impetram MS coletivo sem necessidade de autorização nominal",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-006-art144-rol-orgaos-seguranca-publica",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "Com a promulgação da Emenda Constitucional nº 104/2019, as polícias penais federal, estaduais e distrital foram expressamente inseridas no rol taxativo dos órgãos de segurança pública previsto no artigo 144 da Constituição Federal, vinculando-se ao órgão administrador do sistema penal da respectiva unidade federativa.",
    explicacao: "GABARITO: CERTO. Art. 144, VI e § 5º-A da CF/88: a EC 104/19 criou a Polícia Penal vinculada aos órgãos de administração penitenciária.",
    gabaritoCerto: true,
    conceito: "Inclusão da Polícia Penal no art. 144 da CF/88",
    habilidade: "Reconhecer o desenho constitucional e a subordinação das polícias penais",
    tese: "A polícia penal integra os órgãos de segurança pública do art. 144 da CF",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-007-guardas-municipais-seguranca-stf-adpf",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Guarda Municipal", cargo: "Guarda Civil Municipal",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal, no julgamento da ADPF 1075 e do Tema 1025 de repercussão geral, reconheceu que as Guardas Municipais integram o Sistema Único de Segurança Pública (SUSP) e executam atividade de segurança pública, sendo-lhes legítimo o policiamento preventivo comunitário e a realização de prisões em flagrante delito, ressalvadas as atribuições exclusivas de polícia judiciária.",
    explicacao: "GABARITO: CERTO. O STF declarou a constitucionalidade da integração das Guardas Municipais ao SUSP e sua atuação na preservação da ordem pública e proteção de bens, serviços e instalações.",
    gabaritoCerto: true,
    conceito: "Estatuto Constitucional das Guardas Municipais e SUSP",
    habilidade: "Compreender as competências das Guardas Municipais segundo a jurisprudência recente do STF",
    tese: "Guardas Municipais integram o sistema de segurança pública para policiamento preventivo",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-008-policia-rodoviaria-federal-patrulhamento",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "facil",
    enunciado: "A Polícia Rodoviária Federal, órgão permanente estruturado em carreira e mantido pela União, destina-se, na forma da lei, ao patrulhamento ostensivo das rodovias federais.",
    explicacao: "GABARITO: CERTO. Reprodução literal do art. 144, § 2º da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Destinação constitucional da Polícia Rodoviária Federal",
    habilidade: "Identificar a competência precípua da PRF no texto constitucional",
    tese: "À PRF compete o patrulhamento ostensivo das rodovias federais",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-009-policia-federal-competencias-exclusivas",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "Compete privativamente à Polícia Federal exercer as funções de polícia marítima, aeroportuária e de fronteiras, bem como exercer, com exclusividade, as funções de polícia judiciária da União.",
    explicacao: "GABARITO: CERTO. Art. 144, § 1º, III e IV da CF/88 prevê expressamente a exclusividade nas funções de polícia judiciária da União.",
    gabaritoCerto: true,
    conceito: "Competências constitucionais da Polícia Federal",
    habilidade: "Distinguir as atribuições exclusivas e concorrentes da Polícia Federal",
    tese: "A PF exerce com exclusividade a polícia judiciária da União e controle de fronteiras",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-const-seg-010-policias-militares-bombeiros-subordinacao",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Vunesp", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "medio",
    enunciado: "De acordo com o artigo 144, § 6º da Constituição Federal de 1988, as polícias militares e os corpos de bombeiros militares, forças auxiliares e reserva do Exército, subordinam-se:",
    explicacao: "GABARITO: B. Art. 144, § 6º da CF/88: juntamente com as polícias civis e as polícias penais estaduais/distrital, subordinam-se aos Governadores dos Estados, do Distrito Federal e dos Territórios.",
    alternativas: [
      { letra: "A", texto: "Diretamente ao Ministro da Defesa e aos Comandos Militares de Área em tempo de paz.", correta: false, explicacao_especifica: "Incorreta. São subordinadas aos Governadores estaduais/distrital." },
      { letra: "B", texto: "Aos Governadores dos Estados, do Distrito Federal e dos Territórios, juntamente com as polícias civis e as polícias penais estaduais e distrital.", correta: true, explicacao_especifica: "Correta. Art. 144, § 6º da CF/88 com redação da EC 104/19." },
      { letra: "C", texto: "Exclusivamente ao Ministério Público estadual para todos os atos de gestão e despesa.", correta: false, explicacao_especifica: "Incorreta. O MP exerce controle externo da atividade policial, não subordinação hierárquica." },
      { letra: "D", texto: "Ao Tribunal de Justiça estadual para fixação de escalas e efetivo operacional.", correta: false, explicacao_especifica: "Incorreta. A gestão integra o Poder Executivo Estadual." },
      { letra: "E", texto: "À Secretaria Nacional de Segurança Pública com subordinação direta à União.", correta: false, explicacao_especifica: "Incorreta. As polícias estaduais integram a estrutura dos Estados-membros." }
    ],
    conceito: "Subordinação constitucional das forças de segurança estaduais",
    habilidade: "Identificar o vínculo hierárquico e institucional das Polícias Militares e Corpos de Bombeiros",
    tese: "Polícias militares e corpos de bombeiros subordinam-se aos governadores estaduais",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-011-tribunal-juri-soberania-veredictos",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "A instituição do júri é assegurada pela Constituição com a plenitude de defesa, o sigilo das votações, a soberania dos veredictos e a competência para o julgamento dos crimes dolosos contra a vida, consumados ou tentados.",
    explicacao: "GABARITO: CERTO. Art. 5º, XXXVIII da CF/88 elenca as quatro garantias fundamentais da instituição do júri.",
    gabaritoCerto: true,
    conceito: "Princípios constitucionais do Tribunal do Júri",
    habilidade: "Reconhecer as garantias constitucionais do Tribunal do Júri",
    tese: "Tribunal do Júri possui competência mínima para crimes dolosos contra a vida",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-012-vedacao-provas-ilicitas-derivadas",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "São inadmissíveis, no processo, as provas obtidas por meios ilícitos, aplicando-se a teoria dos frutos da árvore envenenada para contaminar as provas derivadas da ilicitude originária, ressalvadas as hipóteses legais de fonte independente e de descoberta inevitável.",
    explicacao: "GABARITO: CERTO. Art. 5º, LVI da CF/88 c/c art. 157, §§ 1º e 2º do CPP consagram a vedação probatória e as exceções da fonte independente e descoberta inevitável.",
    gabaritoCerto: true,
    conceito: "Inadmissibilidade das provas ilícitas e exceções legais",
    habilidade: "Analisar a extensão da contaminação probatória por ilicitude",
    tese: "Provas ilícitas por derivação são nulas, salvo fonte independente ou descoberta inevitável",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-013-presuncao-inocencia-execucao-pena-stf",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Conforme entendimento fixado pelo STF no julgamento das ADCs 43, 44 e 54, a execução provisória da pena privativa de liberdade antes do trânsito em julgado da sentença penal condenatória é incompatível com o princípio da presunção de inocência (art. 5º, LVII da CF), ressalvada a decretação fundamentada de prisões cautelares.",
    explicacao: "GABARITO: CERTO. O STF pacificou que o cumprimento de pena exige trânsito em julgado, mantendo a higidez das prisões cautelares (preventiva/temporária) quando presentes seus requisitos.",
    gabaritoCerto: true,
    conceito: "Presunção de inocência e trânsito em julgado (STF ADCs 43, 44 e 54)",
    habilidade: "Compreender o alcance do princípio da não culpabilidade na execução da pena",
    tese: "Execução da pena exige trânsito em julgado, mantidas as prisões cautelares fundamentadas",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-014-direito-silencio-nemo-tenetur",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "facil",
    enunciado: "O preso tem direito à informação de seus direitos, entre os quais o de permanecer calado, sendo-lhe assegurada a assistência da família e de advogado, não podendo o silêncio ser interpretado em prejuízo de sua defesa.",
    explicacao: "GABARITO: CERTO. Art. 5º, LXIII da CF/88 e princípio do nemo tenetur se detegere.",
    gabaritoCerto: true,
    conceito: "Direito ao silêncio e aviso de Miranda constitucional",
    habilidade: "Aplicar o direito de advertência formal ao silêncio em abordagens policiais",
    tese: "O silêncio do preso é garantia constitucional e não gera presunção de culpa",
    nivel: "recordar"
  },
  {
    tipo: "ME",
    slug: "l13-const-dir-015-extradicao-brasileiro-nato-naturalizado",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "Sobre as regras constitucionais relativas à extradição e expulsão de nacionais e estrangeiros, assinale a opção correta de acordo com a CF/88:",
    explicacao: "GABARITO: C. Art. 5º, LI da CF/88: nenhum brasileiro será extraditado, salvo o naturalizado, em caso de crime comum praticado antes da naturalização ou de comprovado envolvimento em tráfico de drogas a qualquer tempo.",
    alternativas: [
      { letra: "A", texto: "O brasileiro nato pode ser extraditado em caso de crime doloso contra a vida de chefe de Estado estrangeiro.", correta: false, explicacao_especifica: "Incorreta. Brasileiro nato nunca é extraditado." },
      { letra: "B", texto: "O brasileiro naturalizado jamais poderá ser extraditado em qualquer hipótese por crime praticado após a naturalização.", correta: false, explicacao_especifica: "Incorreta. No tráfico ilícito de drogas, o naturalizado pode ser extraditado a qualquer tempo." },
      { letra: "C", texto: "Nenhum brasileiro será extraditado, salvo o naturalizado, em caso de crime comum antes da naturalização, ou de comprovado envolvimento em tráfico ilícito de entorpecentes a qualquer tempo.", correta: true, explicacao_especifica: "Correta. Redação literal do art. 5º, LI da CF/88." },
      { letra: "D", texto: "A extradição de estrangeiro por crime político ou de opinião é livremente autorizada por ato discricionário do Presidente.", correta: false, explicacao_especifica: "Incorreta. É expressamente vedada pelo art. 5º, LII da CF/88." },
      { letra: "E", texto: "Compete ao Superior Tribunal de Justiça processar e julgar originariamente o pedido de extradição requisitado por Estado estrangeiro.", correta: false, explicacao_especifica: "Incorreta. A competência originária é do STF (art. 102, I, 'g')." }
    ],
    conceito: "Regime constitucional da extradição de brasileiros e estrangeiros",
    habilidade: "Identificar as hipóteses excepcionais de extradição do brasileiro naturalizado",
    tese: "Brasileiro nato é inextraditável; naturalizado pode ser extraditado por crime anterior ou tráfico",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-016-pericia-oficial-autonomia-tecnica",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Perito Criminal",
    dificuldade: "medio",
    enunciado: "Os órgãos de perícia criminal oficial exercem atividade estatal de natureza técnico-científica indispensável à persecução penal, sendo assegurada aos peritos oficiais autonomia técnica, científica e funcional no exercício de suas atribuições periciais.",
    explicacao: "GABARITO: CERTO. Lei nº 12.030/2009 e normas de processo penal garantem a autonomia funcional e técnico-científica aos peritos oficiais.",
    gabaritoCerto: true,
    conceito: "Autonomia técnico-científica dos órgãos periciais oficiais",
    habilidade: "Reconhecer o estatuto de independência técnica da perícia criminal",
    tese: "Peritos criminais oficiais possuem autonomia técnica e funcional na elaboração de laudos",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-017-direito-propriedade-funcao-social",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "facil",
    enunciado: "É garantido o direito de propriedade, devendo a propriedade atender a sua função social, autorizando a Constituição a desapropriação por necessidade ou utilidade pública, ou por interesse social, mediante justa e prévia indenização em dinheiro, ressalvados os casos constitucionais específicos.",
    explicacao: "GABARITO: CERTO. Art. 5º, XXII, XXIII e XXIV da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Direito de propriedade e função social",
    habilidade: "Identificar os requisitos constitucionais da desapropriação ordinária",
    tese: "A propriedade é condicionada ao cumprimento de sua função social",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-dir-018-mandado-injuncao-omissao-legislativa",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Conceder-se-á mandado de injunção sempre que a falta de norma regulamentadora torne inviável o exercício dos direitos e liberdades constitucionais e das prerrogativas inerentes à nacionalidade, à soberania e à cidadania.",
    explicacao: "GABARITO: CERTO. Reprodução literal do art. 5º, LXXI da CF/88 e Lei nº 13.300/2016.",
    gabaritoCerto: true,
    conceito: "Mandado de Injunção e omissão inconstitucional",
    habilidade: "Identificar o cabimento do mandado de injunção",
    tese: "Mandado de injunção combate a inércia legislativa que inviabiliza direitos constitucionais",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-seg-019-seguranca-viaria-competencia-municipios",
    assuntoId: ASSUNTOS.CONST_SEGURANCA_PUBLICA,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "medio",
    enunciado: "No contexto das diretrizes constitucionais introduzidas pela Emenda Constitucional nº 82/2014, considere que determinado Município estruturou órgão executivo próprio para atuar no trânsito local. Nessa hipótese, a segurança viária compreende as atividades de educação, engenharia e fiscalização de trânsito orientadas à preservação da ordem pública e da incolumidade das pessoas e do patrimônio nas vias públicas, competindo a execução aos órgãos e entidades executivos e seus agentes de trânsito estruturados em carreira.",
    explicacao: "GABARITO: CERTO. O Art. 144, § 10 da CF/88 (inserido pela EC 82/2014) consagrou a segurança viária como vertente da segurança pública, compreendendo educação, engenharia e fiscalização executadas pelos órgãos e agentes de trânsito dos Estados, DF e Municípios.",
    gabaritoCerto: true,
    conceito: "Segurança viária no art. 144 da CF/88",
    habilidade: "Reconhecer o escopo e os executores da segurança viária constitucional",
    tese: "A segurança viária engloba educação, engenharia e fiscalização nas vias públicas",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-const-dir-020-habeas-corpus-punicao-disciplinar-militar",
    assuntoId: ASSUNTOS.CONST_DIREITOS_FUNDAMENTAIS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "dificil",
    enunciado: "A Constituição Federal estabelece, no art. 142, § 2º, que não caberá habeas corpus em relação a punições disciplinares militares. A respeito do alcance dessa vedação segundo a jurisprudência sumulada e consolidada do Supremo Tribunal Federal:",
    explicacao: "GABARITO: D. Súmula 690 do STF e jurisprudência pacífica: o Judiciário não analisa o mérito da punição disciplinar militar, mas pode examinar plenamente os aspectos de legalidade (competência, devido processo legal, motivação, limites da pena).",
    alternativas: [
      { letra: "A", texto: "Impede o Poder Judiciário de examinar qualquer aspecto do ato, inclusive incompetência absoluta da autoridade ou manifesta falta de previsão legal.", correta: false, explicacao_especifica: "Incorreta. O controle de legalidade formal e material estrita é sempre cabível." },
      { letra: "B", texto: "Permite ao magistrado substituir a autoridade militar e reapreciar discricionariamente a conveniência da sanção aplicada.", correta: false, explicacao_especifica: "Incorreta. O mérito disciplinar não é passível de reapreciação." },
      { letra: "C", texto: "Aplica-se apenas aos integrantes da Marinha e do Exército, sendo inaplicável a policiais militares.", correta: false, explicacao_especifica: "Incorreta. Aplica-se aos militares estaduais por força do art. 42 da CF/88." },
      { letra: "D", texto: "Não impede que o Poder Judiciário aprecie a legalidade do ato punitivo militar, compreendendo a competência da autoridade, o devido processo legal e a estrita observância das formas legais.", correta: true, explicacao_especifica: "Correta. Súmula 690 do STF e tese consolidada de controle estrito de legalidade." },
      { letra: "E", texto: "Extingue imediatamente o direito à ampla defesa no âmbito do processo administrativo disciplinar militar.", correta: false, explicacao_especifica: "Incorreta. A ampla defesa e o contraditório são garantias inafastáveis." }
    ],
    conceito: "Habeas corpus e controle de legalidade em punições disciplinares militares",
    habilidade: "Diferenciar controle de mérito e controle de legalidade na disciplina militar",
    tese: "Cabe habeas corpus para controle de legalidade em punições disciplinares militares",
    nivel: "analisar"
  }
];

// ==============================================================
// M12: DIREITO CONSTITUCIONAL - ORGANIZAÇÃO DO ESTADO E PODERES (20 questões)
// ==============================================================
const m12_data = [
  {
    tipo: "CE",
    slug: "l13-const-org-001-reparticao-competencias-seguranca-legislativa",
    assuntoId: ASSUNTOS.CONST_ORG_ESTADO,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Compete privativamente à União legislar sobre direito penal, processual penal e material bélico, sendo inconstitucional lei estadual ou municipal que pretenda criar novos tipos penais ou disciplinar de forma divergente a posse e o porte de armas de fogo.",
    explicacao: "GABARITO: CERTO. Art. 22, I e XXI da CF/88 e Súmula Vinculante 38 do STF: competência privativa da União para direito penal e armas/munições.",
    gabaritoCerto: true,
    conceito: "Competência privativa da União em Direito Penal e Armas",
    habilidade: "Identificar vícios formais de inconstitucionalidade em leis estaduais de armas",
    tese: "Compete privativamente à União legislar sobre direito penal e material bélico",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-org-002-competencia-concorrente-procedimentos-materia-processual",
    assuntoId: ASSUNTOS.CONST_ORG_ESTADO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "Compete à União, aos Estados e ao Distrito Federal legislar concorrentemente sobre procedimentos em matéria processual e penitenciário, limitando-se a União ao estabelecimento de normas gerais, sem excluir a competência suplementar dos Estados.",
    explicacao: "GABARITO: CERTO. Art. 24, I, XI e § 1º da CF/88: legislação concorrente sobre direito penitenciário e procedimentos em matéria processual.",
    gabaritoCerto: true,
    conceito: "Competência legislativa concorrente (Art. 24 da CF/88)",
    habilidade: "Distinguir competência privativa processual de competência concorrente procedimental",
    tese: "União fixa normas gerais e Estados suplementam em matéria de procedimento e direito penitenciário",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-003-competencia-stf-habeas-corpus-ministros",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "Compete originariamente ao Supremo Tribunal Federal processar e julgar o habeas corpus quando o coator for Ministro de Estado, Comandante da Marinha, do Exército ou da Aeronáutica, ou quando o coator ou paciente for pessoa sujeita à jurisdição direta da Suprema Corte.",
    explicacao: "GABARITO: CERTO. Art. 102, I, 'd' e 'i' da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Competência originária do STF em Habeas Corpus",
    habilidade: "Identificar as autoridades coatoras submetidas à competência originária do STF",
    tese: "STF julga HC contra atos de Ministros de Estado e autoridades com prerrogativa na Corte",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-004-competencia-stj-governadores-crime-comum",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Em apuração de condutas ilícitas praticadas por altas autoridades públicas estaduais, a delimitação do foro jurisdicional privativo segue a matriz da Carta Magna. Nesse cenário, compete originariamente ao Superior Tribunal de Justiça processar e julgar os Governadores dos Estados e do DF na prática de crimes comuns, cabendo ao mesmo STJ julgar os desembargadores dos Tribunais de Justiça tanto nos crimes comuns quanto nos de responsabilidade.",
    explicacao: "GABARITO: CERTO. Art. 105, I, 'a' da Constituição Federal de 1988: compete ao STJ processar e julgar, originariamente, nos crimes comuns, os Governadores dos Estados e do DF, e, nestes e nos de responsabilidade, os desembargadores dos TJs estaduais e do TJDFT.",
    gabaritoCerto: true,
    conceito: "Competência originária do STJ para Governadores e Desembargadores",
    habilidade: "Reconhecer as regras de foro por prerrogativa de função no STJ",
    tese: "Governadores respondem por crimes comuns perante o STJ",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-const-pod-005-foro-prerrogativa-funcao-stf-marco-temporal",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "FGV", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "A respeito da prerrogativa de foro por função perante os tribunais superiores segundo a jurisprudência atualizada do Supremo Tribunal Federal (Questão de Ordem na AP 937 e julgamentos supervenientes), assinale a afirmativa correta.",
    explicacao: "GABARITO: B. A prerrogativa aplica-se aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas, e, uma vez encerrada a instrução com intimação para alegações finais, o foro se prorroga definitivamente.",
    alternativas: [
      { letra: "A", texto: "Aplica-se a qualquer crime comum cometido pelo parlamentar, independentemente da época do fato ou de relação com o mandato.", correta: false, explicacao_especifica: "Incorreta. Exige-se prática no cargo e em razão dele." },
      { letra: "B", texto: "O foro por prerrogativa de função aplica-se apenas aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas.", correta: true, explicacao_especifica: "Correta. Tese da QO na AP 937 fixada pelo STF." },
      { letra: "C", texto: "A renúncia ao mandato parlamentar em qualquer fase processual sempre transfere os autos ao juízo de primeiro grau.", correta: false, explicacao_especifica: "Incorreta. Após o encerramento da instrução (intimação para alegações finais), a competência é prorrogada e perpetuada no STF." },
      { letra: "D", texto: "A prerrogativa de foro abrange automaticamente os corréus que não possuem qualquer cargo público relevante.", correta: false, explicacao_especifica: "Incorreta. A regra é o desmembramento do processo quanto aos não detentores de foro." },
      { letra: "E", texto: "O STF não admite cisão processual em inquéritos policiais de organizações criminosas complexas.", correta: false, explicacao_especifica: "Incorreta. O desmembramento é a diretriz padrão da Corte." }
    ],
    conceito: "Foro por prerrogativa de função e critérios de contemporaneidade e pertinência temática",
    habilidade: "Aplicar a tese do STF sobre foro por prerrogativa de função aos crimes de titulares de mandato",
    tese: "O foro privilegiado exige contemporaneidade e nexo causal com a função pública",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-con-006-controle-concentrado-adi-adc-legitimados",
    assuntoId: ASSUNTOS.CONST_CONTROLE_CONSTITUCIONALIDADE,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "O Procurador-Geral da República, o Presidente da República, a Mesa do Senado Federal e a Mesa da Câmara dos Deputados são legitimados universais para a propositura de Ação Direta de Inconstitucionalidade (ADI) e Ação Declaratória de Constitucionalidade (ADC), não necessitando demonstrar pertinência temática.",
    explicacao: "GABARITO: CERTO. Art. 103 da CF/88: os legitimados neutros/universais dispensam comprovação de interesse temático específico.",
    gabaritoCerto: true,
    conceito: "Legitimidade ativa universal no controle concentrado de constitucionalidade",
    habilidade: "Classificar os legitimados do art. 103 da CF entre universais e especiais",
    tese: "Legitimados universais no art. 103 dispensam demonstração de pertinência temática",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-con-007-adpf-principio-subsidiariedade",
    assuntoId: ASSUNTOS.CONST_CONTROLE_CONSTITUCIONALIDADE,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "A Arguição de Descumprimento de Preceito Fundamental (ADPF) é cabível para evitar ou reparar lesão a preceito fundamental resultante de ato do Poder Público, inclusive direito pré-constitucional e normas municipais, regendo-se pelo princípio da subsidiariedade, segundo o qual não será admitida quando houver qualquer outro meio de controle concentrado de eficácia equivalente.",
    explicacao: "GABARITO: CERTO. Lei nº 9.882/99, art. 4º, § 1º: a subsidiariedade afasta a ADPF se houver outro instrumento direto no controle abstrato com mesma amplitude.",
    gabaritoCerto: true,
    conceito: "ADPF, direito pré-constitucional e princípio da subsidiariedade",
    habilidade: "Analisar o cabimento residual e protetivo da ADPF",
    tese: "A ADPF tutela preceitos fundamentais contra atos municipais e leis pré-constitucionais",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-con-008-clausula-reserva-plenario-sumula-vinculante-10",
    assuntoId: ASSUNTOS.CONST_CONTROLE_CONSTITUCIONALIDADE,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Viola a cláusula de reserva de plenário (art. 97 da CF) a decisão de órgão fracionário de Tribunal que, embora não declare expressamente a inconstitucionalidade de lei ou ato normativo do poder público, afasta sua incidência, no todo ou em parte.",
    explicacao: "GABARITO: CERTO. Texto literal da Súmula Vinculante nº 10 do Supremo Tribunal Federal.",
    gabaritoCerto: true,
    conceito: "Cláusula de reserva de plenário (Súmula Vinculante 10)",
    habilidade: "Identificar violação à reserva de plenário por órgãos fracionários de tribunais",
    tese: "Órgão fracionário de tribunal não pode afastar lei com base constitucional sem remessa ao pleno",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-009-cpi-poderes-investigacao-reserva-jurisdicao",
    assuntoId: ASSUNTOS.CONST_PODER_LEGISLATIVO,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "As comissões parlamentares de inquérito possuem poderes de investigação próprios das autoridades judiciais, podendo determinar a quebra de sigilo bancário, fiscal e telefônico dos investigados por decisão fundamentada; todavia, estão submetidas à cláusula de reserva de jurisdição, sendo-lhes vedado decretar interceptação telefônica, busca e apreensão domiciliar e prisão preventiva.",
    explicacao: "GABARITO: CERTO. Art. 58, § 3º da CF/88 e jurisprudência pacífica do STF: CPI quebra sigilo de dados telefônicos/bancários, mas não pode interceptar conversa telefônica nem violar domicílio.",
    gabaritoCerto: true,
    conceito: "Poderes instrutórios das CPIs e limites da reserva de jurisdição",
    habilidade: "Diferenciar medidas investigativas admitidas e vedadas a Comissões Parlamentares de Inquérito",
    tese: "CPIs podem quebrar sigilo de dados, mas interceptação telefônica e busca domiciliar exigem ordem judicial",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-const-pod-010-presidente-crime-responsabilidade-camara",
    assuntoId: ASSUNTOS.CONST_PODER_EXECUTIVO,
    banca: "Vunesp", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal de 1988, admitida a acusação contra o Presidente da República por dois terços da Câmara dos Deputados:",
    explicacao: "GABARITO: C. Art. 86 da CF/88: o Presidente será submetido a julgamento perante o STF (crimes comuns) ou perante o Senado Federal (crimes de responsabilidade).",
    alternativas: [
      { letra: "A", texto: "Será ele julgado perante o Congresso Nacional em sessão conjunta obrigatória para qualquer delito.", correta: false, explicacao_especifica: "Incorreta. O julgamento ocorre no STF ou no Senado separadamente." },
      { letra: "B", texto: "Ficará suspenso de suas funções imediatamente pelo prazo improrrogável de 30 dias.", correta: false, explicacao_especifica: "Incorreta. A suspensão ocorre após a instauração pelo Senado ou recebimento de denúncia pelo STF por até 180 dias." },
      { letra: "C", texto: "Será submetido a julgamento perante o Supremo Tribunal Federal, nas infrações penais comuns, ou perante o Senado Federal, nos crimes de responsabilidade.", correta: true, explicacao_especifica: "Correta. Art. 86, caput da Constituição Federal." },
      { letra: "D", texto: "Caberá ao Superior Tribunal de Justiça realizar a instrução criminal preliminar.", correta: false, explicacao_especifica: "Incorreta. O STJ não julga o Presidente da República." },
      { letra: "E", texto: "Deverá ser decretada sua prisão temporária compulsória pelo Procurador-Geral da República.", correta: false, explicacao_especifica: "Incorreta. O Presidente não está sujeito a prisão enquanto não sobrevier condenação (art. 86, § 3º)." }
    ],
    conceito: "Responsabilização política e penal do Presidente da República",
    habilidade: "Identificar o juízo competente e o rito constitucional de responsabilização presidencial",
    tese: "O Presidente responde por crimes comuns perante o STF e por crimes de responsabilidade perante o Senado",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-org-011-intervencao-federal-hipoteses-decreto",
    assuntoId: ASSUNTOS.CONST_ORG_ESTADO,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "A União não intervirá nos Estados nem no Distrito Federal, exceto para manter a integridade nacional, repelir invasão estrangeira, pôr termo a grave comprometimento da ordem pública ou garantir o livre exercício de qualquer dos Poderes nas unidades da Federação.",
    explicacao: "GABARITO: CERTO. Art. 34, I, II, III e IV da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Hipóteses constitucionais de intervenção federal",
    habilidade: "Reconhecer os pressupostos materiais da intervenção federal",
    tese: "A não intervenção é o princípio republicano; a intervenção federal é exceção taxativa",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-org-012-estado-defesa-pressupostos-duracao",
    assuntoId: ASSUNTOS.CONST_ORG_ESTADO,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "O Presidente da República pode, ouvidos o Conselho da República e o Conselho de Defesa Nacional, decretar estado de defesa para preservar ou restabelecer a ordem pública ou a paz social ameaçadas por grave e iminente instabilidade institucional ou atingidas por calamidades de grandes proporções na natureza, por tempo não superior a trinta dias, admitida uma única prorrogação por igual período se persistirem as razões.",
    explicacao: "GABARITO: CERTO. Art. 136, caput e § 2º da CF/88.",
    gabaritoCerto: true,
    conceito: "Estado de Defesa: pressupostos e prazos de vigência",
    habilidade: "Compreender os limites temporais e materiais do Estado de Defesa",
    tese: "O Estado de Defesa dura até 30 dias, prorrogável uma vez por igual período",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-013-cnj-natureza-administrativa-ausencia-funcao-jurisdicional",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "facil",
    enunciado: "O Conselho Nacional de Justiça (CNJ) é órgão de controle da atuação administrativa e financeira do Poder Judiciário e do cumprimento dos deveres funcionais dos juízes, não exercendo competência jurisdicional, sendo suas decisões sujeitas a controle de legalidade originário pelo STF.",
    explicacao: "GABARITO: CERTO. Art. 103-B da CF/88 e pacífica jurisprudência do STF.",
    gabaritoCerto: true,
    conceito: "Natureza administrativa e atribuições do CNJ",
    habilidade: "Identificar as funções fiscalizatórias do CNJ e ausência de atividade judicante",
    tese: "O CNJ é órgão administrativo de cúpula sem função jurisdicional",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-con-014-sumula-vinculante-requisitos-aprovacao",
    assuntoId: ASSUNTOS.CONST_CONTROLE_CONSTITUCIONALIDADE,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "Com a finalidade de assegurar a estabilidade jurisprudencial e a segurança jurídica nas esferas administrativa e judiciária, o Supremo Tribunal Federal dispõe de competência para editar enunciados de súmula vinculante. Para a aprovação válida de súmula com força vinculante erga omnes, a Constituição Federal exige decisão de dois terços dos ministros da Corte Suprema e a prévia existência de reiteradas decisões sobre a matéria constitucional em debate.",
    explicacao: "GABARITO: CERTO. Art. 103-A da CF/88: o STF poderá, de ofício ou por provocação, mediante decisão de dois terços dos seus membros, após reiteradas decisões sobre matéria constitucional, aprovar súmula com efeito vinculante aos demais órgãos judiciais e à administração pública direta e indireta.",
    gabaritoCerto: true,
    conceito: "Requisitos constitucionais da Súmula Vinculante",
    habilidade: "Identificar o quórum qualificado e os pressupostos materiais das Súmulas Vinculantes",
    tese: "Súmula Vinculante exige 2/3 dos ministros do STF e reiteração de julgados constitucionais",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-const-con-015-reclamacao-constitucional-cabimento-stf",
    assuntoId: ASSUNTOS.CONST_CONTROLE_CONSTITUCIONALIDADE,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A reclamação constitucional perante o Supremo Tribunal Federal é cabível para preservar a competência do Tribunal e garantir a autoridade das suas decisões. A respeito do seu cabimento perante a Suprema Corte, assinale a opção correta.",
    explicacao: "GABARITO: A. Art. 103-A, § 3º da CF/88 e art. 988 do CPC: cabe reclamação contra ato administrativo ou judicial que contrariar Súmula Vinculante ou decisão em controle concentrado.",
    alternativas: [
      { letra: "A", texto: "Cabe reclamação para garantir o cumprimento de Súmula Vinculante e de decisões proferidas pelo STF em sede de controle concentrado de constitucionalidade.", correta: true, explicacao_especifica: "Correta. Art. 103-A, § 3º da CF/88 e art. 988, III e IV do CPC." },
      { letra: "B", texto: "Pode ser ajuizada a qualquer tempo mesmo após o trânsito em julgado da decisão judicial reclamada.", correta: false, explicacao_especifica: "Incorreta. Súmula 734 do STF: não cabe reclamação contra decisão transitada em julgado." },
      { letra: "C", texto: "Serve como sucedâneo recursal ordinário para reexame amplo de fatos e provas de inquérito policial.", correta: false, explicacao_especifica: "Incorreta. A reclamação não substitui recursos cabíveis nem reexamina provas." },
      { letra: "D", texto: "É instrumento privativo do Procurador-Geral da República, vedada a propositura pelo cidadão lesado.", correta: false, explicacao_especifica: "Incorreta. Qualquer parte interessada lesada por ato contrário possui legitimidade." },
      { letra: "E", texto: "Não admite concessão de medida liminar suspensiva pelo relator.", correta: false, explicacao_especifica: "Incorreta. O relator pode conceder liminar para suspender o ato impugnado." }
    ],
    conceito: "Reclamação constitucional perante o STF",
    habilidade: "Reconhecer as hipóteses de cabimento e vedações da reclamação constitucional",
    tese: "Reclamação tutela autoridade de súmula vinculante e decisões concentradas do STF",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-016-imunidade-parlamentar-material-nexo-funcional",
    assuntoId: ASSUNTOS.CONST_PODER_LEGISLATIVO,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Os Deputados e Senadores são invioláveis, civil e penalmente, por quaisquer de suas opiniões, palavras e votos. Segundo o STF, a imunidade parlamentar material exercida fora do recinto do Parlamento exige a demonstração de nexo causal direto entre as declarações emitidas e o exercício do mandato eletivo.",
    explicacao: "GABARITO: CERTO. Art. 53 da CF/88 e jurisprudência consolidada do STF: fora do parlamento, a inviolabilidade depende de pertinência com a função parlamentar.",
    gabaritoCerto: true,
    conceito: "Imunidade parlamentar material e nexo funcional extraparlamentar",
    habilidade: "Aplicar os limites jurisprudenciais da inviolabilidade parlamentar",
    tese: "Opiniões emitidas fora do parlamento só gozam de imunidade se tiverem nexo com o mandato",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-017-ministerio-publico-principios-institucionais",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "facil",
    enunciado: "São princípios institucionais do Ministério Público a unidade, a indivisibilidade e a independência funcional, incumbindo-lhe a defesa da ordem jurídica, do regime democrático e dos interesses sociais e individuais indisponíveis.",
    explicacao: "GABARITO: CERTO. Art. 127, caput e § 1º da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Princípios institucionais e missão do Ministério Público",
    habilidade: "Identificar os postulados constitucionais do Ministério Público",
    tese: "Unidade, indivisibilidade e independência funcional regem a atuação do Ministério Público",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-const-pod-018-defensoria-publica-autonomia-funcional",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "Às Defensorias Públicas Estaduais e da União são asseguradas autonomia funcional e administrativa e a iniciativa de sua proposta orçamentária dentro dos limites estabelecidos na lei de diretrizes orçamentárias.",
    explicacao: "GABARITO: CERTO. Art. 134, § 2º da CF/88 (incluído pela EC 45/2004 e reforçado pela EC 74/2013).",
    gabaritoCerto: true,
    conceito: "Autonomia funcional e administrativa da Defensoria Pública",
    habilidade: "Reconhecer as garantias constitucionais conferidas à Defensoria Pública",
    tese: "A Defensoria Pública goza de autonomia funcional, administrativa e orçamentária",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-const-org-019-municipios-competencia-interesse-local",
    assuntoId: ASSUNTOS.CONST_ORG_ESTADO,
    banca: "Cebraspe", orgao: "Guarda Municipal", cargo: "Guarda Civil Municipal",
    dificuldade: "facil",
    enunciado: "Compete aos Municípios legislar sobre assuntos de interesse local e suplementar a legislação federal e a estadual no que couber, competindo-lhes organizar e prestar os serviços públicos de interesse local, como o transporte coletivo municipal.",
    explicacao: "GABARITO: CERTO. Art. 30, I, II e V da Constituição Federal de 1988.",
    gabaritoCerto: true,
    conceito: "Competências legislativas e materiais dos Municípios",
    habilidade: "Identificar as competências constitucionais do ente municipal",
    tese: "Municípios legislam sobre interesse local e suplementam leis estaduais/federais",
    nivel: "recordar"
  },
  {
    tipo: "ME",
    slug: "l13-const-pod-020-advocacia-publica-funcoes-essenciais",
    assuntoId: ASSUNTOS.CONST_PODER_JUDICIARIO,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "No rol das funções essenciais à justiça, a Advocacia-Geral da União (AGU) e as Procuradorias dos Estados têm por função constitucional precípua:",
    explicacao: "GABARITO: A. Art. 131 e 132 da CF/88: representação judicial e consultoria jurídica das respectivas unidades federativas.",
    alternativas: [
      { letra: "A", texto: "Representar judicial e extrajudicialmente os respectivos entes federativos e exercer as atividades de consultoria e assessoramento jurídico do Poder Executivo.", correta: true, explicacao_especifica: "Correta. Art. 131 e 132 da Constituição Federal." },
      { letra: "B", texto: "Exercer privativamente a titularidade da ação penal pública em crimes contra a administração pública.", correta: false, explicacao_especifica: "Incorreta. A titularidade da ação penal pública é privativa do Ministério Público." },
      { letra: "C", texto: "Julgar os litígios administrativos de natureza disciplinar dos servidores policiais com força de coisa julgada.", correta: false, explicacao_especifica: "Incorreta. Coisa julgada em sentido estrito é exclusiva do Poder Judiciário." },
      { letra: "D", texto: "Realizar perícias de áudio e imagem para os inquéritos da Polícia Federal.", correta: false, explicacao_especifica: "Incorreta. Perícia é atribuição da polícia científica/peritos oficiais." },
      { letra: "E", texto: "Promover a defesa técnica criminal dos réus hipossuficientes perante os tribunais do júri.", correta: false, explicacao_especifica: "Incorreta. Esta é função institucional da Defensoria Pública (art. 134 da CF)." }
    ],
    conceito: "Atribuições constitucionais da Advocacia Pública",
    habilidade: "Diferenciar as funções da Advocacia Pública, Ministério Público e Defensoria Pública",
    tese: "À Advocacia Pública cabe a representação judicial e consultoria jurídica do Estado",
    nivel: "compreender"
  }
];

function converterItem(item, disciplinaId) {
  if (item.tipo === "CE") {
    return criarQuestaoCE({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      gabaritoCerto: item.gabaritoCerto,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  } else {
    return criarQuestaoME({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      alternativas: item.alternativas,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  }
}

// 1. Gerar M11
const m11_questoes = m11_data.map(item => converterItem(item, DISCIPLINAS.DIREITO_CONSTITUCIONAL));
writeModuleFile("m11_const_direitos_seguranca.mjs", "m11_questoes", m11_questoes);

// 2. Gerar M12
const m12_questoes = m12_data.map(item => converterItem(item, DISCIPLINAS.DIREITO_CONSTITUCIONAL));
writeModuleFile("m12_const_organizacao_poderes.mjs", "m12_questoes", m12_questoes);

console.log("[OK] Grupo D (M11: 20 questões, M12: 20 questões) concluído com sucesso!");
