// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 15

export const m22_questoes = [
  {
    "id": "953dd287-c43e-51b0-9ba1-dc39fbe66f7a",
    "idSlug": "l13-port-sint-001-crase-obrigatoria-regencia-feminino",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "No período 'O relatório pericial fez referência direta à conduta ilícita dos investigados', o acento grave indicativo de crase é de uso obrigatório, pois o substantivo 'referência' rege a preposição 'a' e o termo subsequente 'conduta' é precedido pelo artigo definido feminino 'a'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Fusão obrigatória: preposição 'a' (exigida por 'referência a') + artigo 'a' ('a conduta').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1537a70202e671b5cd243b19cf3c75264d1eb5bd4e5358e8d535aa6501dd3d53",
    "conceito_principal": "Regras de uso obrigatório do acento indicativo de crase",
    "habilidade_cobrada": "Identificar a fusão da preposição com o artigo diante de substantivos femininos",
    "tese_ou_regra": "Crase é obrigatória quando o termo regente exige 'a' e o termo regido aceita artigo 'a'",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a1ae1b18-c547-5afe-843b-922f963a8063",
        "questao_id": "953dd287-c43e-51b0-9ba1-dc39fbe66f7a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "21ba7670-9b90-5d90-ab7b-54db2647dcfa",
        "questao_id": "953dd287-c43e-51b0-9ba1-dc39fbe66f7a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6a74a1c4-fb08-5fde-bd61-de161abba237",
    "idSlug": "l13-port-sint-002-crase-proibida-masculino-verbos",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Em 'Os agentes procederam a abordagem a pé e começaram a revistar o veículo', ambas as ocorrências da letra 'a' sublinhadas devem receber acento indicativo de crase em razão da regência dos termos antecedentes.",
    "explicacao": "GABARITO: ERRADO. GABARITO: ERRADO. Diante de palavra masculina ('pé') e diante de verbo ('revistar'), o uso de crase é expressamente proibido.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "63fdfe86f46f818f673be45773cb27cc6e17194ddb3866f0c176348ae0a0847b",
    "conceito_principal": "Casos de proibição do uso do acento indicativo de crase",
    "habilidade_cobrada": "Reconhecer contextos em que a ocorrência de crase é vedada pela norma culta",
    "tese_ou_regra": "Não ocorre crase diante de palavras masculinas nem antes de verbos",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "55d04e49-fd77-591e-baf3-bb9c8e0894fe",
        "questao_id": "6a74a1c4-fb08-5fde-bd61-de161abba237",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "9db41aeb-d2ac-55f7-a25e-9c8b9b2ecbf1",
        "questao_id": "6a74a1c4-fb08-5fde-bd61-de161abba237",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "c2a2e394-b988-5a18-acad-42b8277a04e9",
    "idSlug": "l13-port-sint-003-crase-facultativa-possessivo-singular",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na frase 'O escrivão entregou as intimações a sua chefia imediata', o emprego do acento grave no vocábulo 'a' é facultativo, sendo gramaticalmente corretas ambas as formas: 'a sua chefia' e 'à sua chefia'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Diante de pronome possessivo feminino no singular ('sua'), o artigo é facultativo; logo, a crase torna-se facultativa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "25c4e2e7f3daeccd6d7a4508fb4319e90d27d84acee836db46965952c7c01dbe",
    "conceito_principal": "Casos de crase facultativa (pronome possessivo feminino singular)",
    "habilidade_cobrada": "Identificar os contextos normativos de emprego facultativo da crase",
    "tese_ou_regra": "A crase é facultativa diante de pronomes possessivos femininos no singular",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c2e0200b-186c-5605-9f1d-1e929d1a4791",
        "questao_id": "c2a2e394-b988-5a18-acad-42b8277a04e9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "47e51868-77bf-598b-b2ad-64944c59b9b0",
        "questao_id": "c2a2e394-b988-5a18-acad-42b8277a04e9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "441ca519-12ea-54da-9eab-b7a1a2cd5912",
    "idSlug": "l13-port-sint-004-concordancia-particula-apassivadora-se",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na oração 'Apuraram-se os indícios de lavagem de dinheiro durante a operação', o verbo 'apurar' foi corretamente flexionado no plural para concordar com o sujeito paciente 'os indícios de lavagem de dinheiro', atuando o 'se' como partícula apassivadora.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Com verbo transitivo direto + 'se' apassivador, a oração está na voz passiva sintética, e o verbo concorda obrigatoriamente com o sujeito paciente no plural.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "055fec14242995e2444797f16fa794afacfa576ae3a938d5351d3dac71e3135f",
    "conceito_principal": "Concordância verbal com partícula apassivadora 'se' (Voz Passiva Sintética)",
    "habilidade_cobrada": "Analisar a concordância verbal em estruturas de voz passiva sintética",
    "tese_ou_regra": "Com partícula apassivadora, o verbo concorda com o sujeito paciente em número e pessoa",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "0ba47bda-b303-5f7d-8131-34a76e8533cf",
        "questao_id": "441ca519-12ea-54da-9eab-b7a1a2cd5912",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d6f6a2e7-a526-560e-85af-c1fddca88406",
        "questao_id": "441ca519-12ea-54da-9eab-b7a1a2cd5912",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e0321e3f-a95d-5c7f-b525-6048126a659c",
    "idSlug": "l13-port-sint-005-concordancia-indice-indeterminacao-se",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na oração 'Tratam-se de graves infrações penais contra o patrimônio público', a concordância verbal está em estrita conformidade com a norma-padrão da língua portuguesa.",
    "explicacao": "GABARITO: ERRADO. GABARITO: ERRADO. O verbo 'tratar-se de' é transitivo indireto acompanhado de 'se' (índice de indeterminação do sujeito), devendo permanecer obrigatoriamente no singular: 'Trata-se de graves infrações penais...'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "861ed481925bd53a76309f4e40cc58c25ef69377e9d24424a271515031bbdb38",
    "conceito_principal": "Concordância verbal com índice de indeterminação do sujeito",
    "habilidade_cobrada": "Corrigir desvios de concordância em verbos transitivos indiretos com 'se'",
    "tese_ou_regra": "Verbo com índice de indeterminação do sujeito fica invariavelmente na 3ª pessoa do singular",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "14cabebe-8595-5d9c-b858-d3faa98282fe",
        "questao_id": "e0321e3f-a95d-5c7f-b525-6048126a659c",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "2eedbc58-32b7-5308-bf11-5bbf893b01d1",
        "questao_id": "e0321e3f-a95d-5c7f-b525-6048126a659c",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
    "idSlug": "l13-port-sint-006-regencia-verbal-implicar-obedecer-visar",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Assinale a opção em que a regência verbal atende com exatidão aos preceitos da norma-padrão culta da língua portuguesa:",
    "explicacao": "O verbo 'desobedecer' é transitivo indireto e exige a preposição 'a' ('desobedecer à ordem policial'). 'Implicar' (no sentido de acarretar) é transitivo direto (não aceita 'em'). 'Aspirar' (almejar) é transitivo indireto ('ao cargo'). 'Visar' (almejar) exige 'a' ('ao aprimoramento').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "90dd2f83fb48025c14d98cac2cc3b46f36542fe86c93dd592226d9672f102995",
    "conceito_principal": "Regência dos verbos implicar, desobedecer, aspirar, visar e assistir",
    "habilidade_cobrada": "Identificar a transitividade e a exigência preposicional de verbos no padrão culto",
    "tese_ou_regra": "Desobedecer rege preposição 'a' e implicar com sentido de acarretar é transitivo direto",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "c1c442ec-ee47-55c4-809a-94c81a590050",
        "questao_id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
        "letra": "A",
        "texto": "A conduta dolosa do servidor implicou em sua demissão imediata do cargo.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta: 'implicar' no sentido de ter como consequência é VTD (implicou sua demissão, sem 'em')."
      },
      {
        "id": "13543259-f963-59e6-96fb-0f1a79bbf86a",
        "questao_id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
        "letra": "B",
        "texto": "O motorista desobedeceu à ordem de parada emanada pelos policiais rodoviários.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta: o verbo 'desobedecer' é VTI e rege a preposição 'a', gerando crase diante de 'a ordem'."
      },
      {
        "id": "9be6915a-e67d-5d2b-b707-57ed3024298b",
        "questao_id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
        "letra": "C",
        "texto": "O candidato aspirava o cargo de perito criminal desde o início dos estudos.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: 'aspirar' no sentido de almejar/pretender é VTI (aspirava ao cargo)."
      },
      {
        "id": "8ee3bf3d-0c5e-5b94-8a71-652da71979b1",
        "questao_id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
        "letra": "D",
        "texto": "As novas diretrizes visam o aprimoramento das operações policiais integradas.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: 'visar' no sentido de ter por objetivo é VTI (visam ao aprimoramento)."
      },
      {
        "id": "a24c5977-9c22-59da-a587-0064ebd89cc2",
        "questao_id": "ca4aa7f1-008b-57ac-8472-7f2122f7760e",
        "letra": "E",
        "texto": "Os investigadores assistiram o desenrolar das ações sem interferir no perímetro.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: 'assistir' no sentido de presenciar/ver é VTI (assistiram ao desenrolar)."
      }
    ]
  },
  {
    "id": "74fd13db-522f-5721-b35a-ec78c35ffb86",
    "idSlug": "l13-port-sint-007-pontuacao-virgula-oracao-adjetiva-explicativa",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "No trecho 'Os policiais militares, que concluíram o treinamento especializado, receberam novos equipamentos', a oração adjetiva entre vírgulas possui natureza explicativa, indicando que todos os policiais militares do grupo considerado concluíram o treinamento.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A oração subordinada adjetiva isolada por vírgulas é explicativa (aplica-se à totalidade do termo antecedente). Sem vírgulas, seria restritiva (apenas parte dos policiais).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "234917a830e82e5497b1c62a0699407e1ba71d327b7af22d5c7f1d28928c6684",
    "conceito_principal": "Emprego da vírgula e distinção entre orações adjetivas explicativas e restritivas",
    "habilidade_cobrada": "Analisar as alterações semânticas provocadas pela pontuação em orações adjetivas",
    "tese_ou_regra": "Vírgulas em orações adjetivas conferem sentido explicativo generalizante",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "494639d2-c633-5ea7-b408-57a69c39c7e9",
        "questao_id": "74fd13db-522f-5721-b35a-ec78c35ffb86",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "73c27a9e-498a-5940-8403-406b851d4657",
        "questao_id": "74fd13db-522f-5721-b35a-ec78c35ffb86",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5060d8ba-a624-5a36-8e3f-8b371a9e8c4c",
    "idSlug": "l13-port-sint-008-pontuacao-proibicao-virgula-sujeito-predicado",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na frase 'O delegado titular da delegacia especializada, determinou a instauração do inquérito', a vírgula foi empregada de forma incorreta por separar indevidamente o sujeito de seu predicado verbal.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. É regra fundamental da pontuação: não se separa o sujeito do predicado por vírgula simples.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "40cebe39f94b2302a3cfdf67b75e18e5d18a8da6a53a4fd4fff5a1d1eee56c28",
    "conceito_principal": "Proibição de vírgula entre sujeito e predicado",
    "habilidade_cobrada": "Identificar violações sintáticas de pontuação entre termos essenciais da oração",
    "tese_ou_regra": "É proibido o uso de vírgula isolada entre o sujeito e o predicado",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "ba096579-bb0b-572c-b308-b34c5cb2c916",
        "questao_id": "5060d8ba-a624-5a36-8e3f-8b371a9e8c4c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "47219d02-42a9-5a08-ae5c-c4c88a6b0894",
        "questao_id": "5060d8ba-a624-5a36-8e3f-8b371a9e8c4c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "42ea2d29-dad8-5d4f-998e-da9945591068",
    "idSlug": "l13-port-sint-009-pontuacao-adjunto-adverbial-deslocado",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "52c47954-6d8a-52d6-8c4f-7525aaa751a1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em 'Durante a madrugada de fiscalização na rodovia federal, os policiais interceptaram um carregamento clandestino', a vírgula é de uso obrigatório por isolar um adjunto adverbial de tempo de longa extensão antecipado na oração.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Adjuntos adverbiais deslocados de média ou longa extensão (três ou mais palavras) exigem vírgula obrigatória na norma culta.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0f3326229b59685a67b2ada1b0f4a1680bf36d5611956c8774100b20db284820",
    "conceito_principal": "Pontuação e isolamento de adjuntos adverbiais deslocados",
    "habilidade_cobrada": "Aplicar a pontuação correta em termos adverbiais antecipados na frase",
    "tese_ou_regra": "Adjunto adverbial antecipado de grande extensão exige vírgula obrigatória",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "1e994816-6fbd-5dfd-9f1d-f13e5316122b",
        "questao_id": "42ea2d29-dad8-5d4f-998e-da9945591068",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e535be0c-c64f-51a8-835c-67adc4da7028",
        "questao_id": "42ea2d29-dad8-5d4f-998e-da9945591068",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d2b5cf97-672a-5778-b19c-970bbea70514",
    "idSlug": "l13-port-sint-010-colocacao-pronominal-palavras-atrativas-proclise",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na oração 'Não se obtiveram respostas conclusivas no primeiro interrogatório', a próclise do pronome 'se' é obrigatória devido à presença da palavra de sentido negativo 'Não', que atua como fator de atração pronominal.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Palavras negativas (não, nunca, jamais) atraem o pronome oblíquo átono para antes do verbo (próclise obrigatória).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "78b31d0aefc4e19c731173371fb3ea2d026780ff3b6f543ec4ad77c0611ad770",
    "conceito_principal": "Próclise obrigatória por palavras de sentido negativo",
    "habilidade_cobrada": "Identificar palavras atrativas na colocação pronominal",
    "tese_ou_regra": "Palavras negativas exigem a colocação do pronome em próclise",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "7ecdbdc0-3a36-595f-b031-18226d39236d",
        "questao_id": "d2b5cf97-672a-5778-b19c-970bbea70514",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7693709a-e73a-5ed9-93fc-a3afa6dad1c8",
        "questao_id": "d2b5cf97-672a-5778-b19c-970bbea70514",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "59cc1181-9663-5c26-8016-6db57105292d",
    "idSlug": "l13-port-sint-011-colocacao-pronominal-inicio-periodo",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A frase 'Me apresentei ao plantão policial às oito horas da manhã' atende rigorosamente às regras de colocação pronominal preconizadas pela norma-padrão escrita formal da língua portuguesa.",
    "explicacao": "GABARITO: ERRADO. GABARITO: ERRADO. Segundo a norma culta tradicional, é proibido iniciar período com pronome oblíquo átono. A forma correta é 'Apresentei-me ao plantão...'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8669379e97aff021ca11729e58054ea416036d81dc0777917a68bad6f28bdfb5",
    "conceito_principal": "Proibição de próclise em início de período na norma culta",
    "habilidade_cobrada": "Reconhecer desvios de colocação pronominal no início de frases formais",
    "tese_ou_regra": "Não se deve iniciar período sintático com pronome oblíquo átono",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c59adb3e-d9f0-5760-9e09-a80e39a1a3d2",
        "questao_id": "59cc1181-9663-5c26-8016-6db57105292d",
        "letra": "C",
        "texto": "Certo",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Assertiva incorreta."
      },
      {
        "id": "b91819ae-d615-59f3-b265-bdda2591823b",
        "questao_id": "59cc1181-9663-5c26-8016-6db57105292d",
        "letra": "E",
        "texto": "Errado",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Assertiva incorreta conforme a fundamentação exposta."
      }
    ]
  },
  {
    "id": "1565523a-3530-57ec-b8e0-613851b6f999",
    "idSlug": "l13-port-sint-012-sintaxe-funcao-pronome-relativo-que-sujeito",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "No período 'O perito identificou a substância que adulterava o combustível apreendido', o pronome relativo 'que' introduz uma oração subordinada adjetiva restritiva e desempenha a função sintática de sujeito do verbo 'adulterava'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O pronome 'que' retoma 'a substância' ('a substância adulterava o combustível') e exerce a função sintática de sujeito do verbo da oração subordinada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "64ab097c533fafa78c78723deb8763b2eb9017091934a215d21fdd7625eae677",
    "conceito_principal": "Função sintática do pronome relativo 'que' (função de sujeito)",
    "habilidade_cobrada": "Determinar a função sintática exercida por pronomes relativos em orações adjetivas",
    "tese_ou_regra": "O pronome relativo que exerce a função sintática de sujeito do verbo subordinado",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "b4824f0e-e39e-50fc-9299-17e50a17f51c",
        "questao_id": "1565523a-3530-57ec-b8e0-613851b6f999",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "027ff6d4-9b73-5f69-be9a-1619b8364b5d",
        "questao_id": "1565523a-3530-57ec-b8e0-613851b6f999",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "805143a2-c3e4-5f95-9fc2-5b61679e965f",
    "idSlug": "l13-port-sint-013-concordancia-nominal-anexo-mesmo-proprio",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Escrivão de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na frase 'Seguem anexas ao relatório final as cópias dos termos de depoimento', a palavra 'anexas' concorda corretamente em gênero e número com o substantivo feminino plural 'as cópias'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O adjetivo 'anexo' concorda em gênero e número com o substantivo a que se refere ('cópias anexas'). Caso fosse a locução prepositiva 'em anexo', seria invariável.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7f501d67912cbc93dbf0009281b24987e8b2aa132243d6ea2e4d74fb753acba8",
    "conceito_principal": "Concordância nominal do vocábulo 'anexo'",
    "habilidade_cobrada": "Aplicar a concordância correta de adjetivos determinantes de substantivos",
    "tese_ou_regra": "A palavra anexo é adjetivo e concorda em gênero e número com o substantivo modificado",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "abd4c885-e8f0-5399-93ae-d77b1dfd9053",
        "questao_id": "805143a2-c3e4-5f95-9fc2-5b61679e965f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5a60f7ba-a5e1-5512-a28f-1f84293bc6fb",
        "questao_id": "805143a2-c3e4-5f95-9fc2-5b61679e965f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
    "idSlug": "l13-port-sint-014-valores-da-particula-se-funcoes",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Papiloscopista Policial Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Considere a oração: 'Necessita-se de peritos especializados em análise balística para a conclusão do inquérito'. O vocábulo 'se' nessa estrutura sintática classifica-se como:",
    "explicacao": "O verbo 'necessitar' é transitivo indireto (rege a preposição 'de'). A partícula 'se' associada a VTI funciona como Índice de Indeterminação do Sujeito.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ddf6610c987b95ea0fdc4f7fec30b462ebf8835ef6fc3faaf22baee9796bccad",
    "conceito_principal": "Classificação morfossintática da partícula 'se' (Índice de Indeterminação)",
    "habilidade_cobrada": "Diferenciar a partícula apassivadora do índice de indeterminação do sujeito",
    "tese_ou_regra": "A partícula 'se' ligada a verbo transitivo indireto funciona como índice de indeterminação do sujeito",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "2bcbab73-290a-5619-b0ea-77ddb7f4c44c",
        "questao_id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
        "letra": "A",
        "texto": "Partícula apassivadora de voz passiva sintética.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta: partícula apassivadora ocorre com VTD ou VTDI, não com VTI regido por preposição."
      },
      {
        "id": "61a6232e-7596-530e-a2b3-aabbde9fbbb0",
        "questao_id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
        "letra": "B",
        "texto": "Índice de indeterminação do sujeito.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta: associado a verbo transitivo indireto (necessitar de), o 'se' indetermina o sujeito."
      },
      {
        "id": "f57e54b4-5b33-5810-b942-66a681b15554",
        "questao_id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
        "letra": "C",
        "texto": "Pronome reflexivo com função de objeto direto.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta: não há ação reflexiva do sujeito sobre si mesmo."
      },
      {
        "id": "1c663fe9-7219-5b0b-8626-1ecea82d2edf",
        "questao_id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
        "letra": "D",
        "texto": "Conjunção subordinativa integrante.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta: não introduz oração subordinada substantiva."
      },
      {
        "id": "ffc49875-7a4a-5d4b-ac09-bb0005a7920b",
        "questao_id": "29b8a859-e633-56f4-af1f-f3ad2fd3810e",
        "letra": "E",
        "texto": "Partícula de realce expletiva.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta: sua presença é estrutural para a indeterminação sintática."
      }
    ]
  },
  {
    "id": "394deab2-0929-52ad-8d00-fcc7850b0103",
    "idSlug": "l13-port-sint-015-concordancia-sujeito-composto-posposto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na oração 'Compareceu ao local do crime o perito criminal e o delegado de polícia', a concordância verbal no singular com o primeiro núcleo do sujeito composto posposto é facultativa e aceita pela norma culta, sendo igualmente correta a forma 'Compareceram ao local do crime o perito criminal e o delegado de polícia'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Com sujeito composto posposto ao verbo, a concordância é facultativa: o verbo pode concordar com o núcleo mais próximo (singular: compareceu o perito...) ou com a totalidade dos núcleos (plural: compareceram o perito e o delegado...).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7e45c747e8a5fc935fc33fd633ff2bad33e4f857843dc821e322a46e0b2934cd",
    "conceito_principal": "Concordância verbal com sujeito composto posposto ao verbo",
    "habilidade_cobrada": "Reconhecer as opções normativas de concordância atrativa ou gramatical",
    "tese_ou_regra": "Com sujeito composto posposto, admite-se concordância no plural ou no singular com o primeiro núcleo",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "78438cd1-0a23-529c-bc21-a43812aa1a81",
        "questao_id": "394deab2-0929-52ad-8d00-fcc7850b0103",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "abceacce-78a7-5420-a206-763745847bb1",
        "questao_id": "394deab2-0929-52ad-8d00-fcc7850b0103",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  }
];
