import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const transito01 = [
  // 1 to 10: Sistema Nacional de Trânsito (SNT) e Competências
  {
    idSlug: "b10-trans-01-001",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O trânsito em condições seguras é um direito de todos e dever dos órgãos e entidades componentes do Sistema Nacional de Trânsito, a estes cabendo, no âmbito das respectivas competências, adotar as medidas destinadas a assegurar esse direito.",
    explicacao: "GABARITO: CERTO. Art. 1º, § 2º, do Código de Trânsito Brasileiro (Lei nº 9.503/1997).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-002",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Compete à Polícia Rodoviária Federal, no âmbito das rodovias e estradas federais, realizar o patrulhamento ostensivo, executando operações relacionadas com a segurança pública, com o objetivo de preservar a ordem, a incolumidade das pessoas, o patrimônio da União e o de terceiros.",
    explicacao: "GABARITO: CERTO. Art. 20, II, do CTB estabelece a competência da PRF para o patrulhamento ostensivo nas rodovias e estradas federais.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-003",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Com as alterações promovidas pela Lei nº 14.599/2023 no art. 24 do CTB (competências dos órgãos executivos de trânsito municipais):",
    explicacao: "GABARITO: B. A Lei 14.599/2023 consolidou a competência concorrente dos órgãos municipais de trânsito para fiscalizar e autuar a grande maioria das infrações de trânsito (inclusive circulação, parada, estacionamento e condutor), ampliando a atuação integrada.",
    alternativas: [
      { texto: "Os municípios perderam a competência para aplicar penalidades de trânsito em vias urbanas.", correta: false },
      { texto: "Os órgãos e entidades executivos de trânsito dos Municípios passaram a ter competência privativa e concorrente ampla para fiscalizar e autuar diversas infrações que antes eram privativas dos Estados.", correta: true },
      { texto: "Apenas a Polícia Militar passou a poder lavrar autos de infração municipais de estacionamento.", correta: false },
      { texto: "Ficou vedada a celebração de convênios entre Municípios e Detrans.", correta: false },
      { texto: "Os agentes municipais foram proibidos de portar etilômetro.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-004",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O Conselho Nacional de Trânsito (CONTRAN), com sede no Distrito Federal, é o órgão normativo e consultivo máximo do Sistema Nacional de Trânsito.",
    explicacao: "GABARITO: CERTO. Art. 12 do CTB define o CONTRAN como órgão normativo e consultivo máximo do SNT.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 5 to 15: Normas Gerais de Circulação e Conduta (Art. 26 a 67-E)
  {
    idSlug: "b10-trans-01-005",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A circulação de veículos far-se-á sempre pelo lado direito da via, admitindo-se as exceções devidamente sinalizadas.",
    explicacao: "GABARITO: CERTO. Art. 29, I, do CTB estabelece o princípio da circulação pela direita.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-006",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em cruzamentos não sinalizados, a preferência de passagem será: no caso de apenas um fluxo ser proveniente de rodovia, daquele que estiver circulando por ela; no caso de rotatória, daquele que estiver circulando por ela; e nos demais casos, do que vier pela direita do condutor.",
    explicacao: "GABARITO: CERTO. Art. 29, III, 'a', 'b' e 'c', do CTB: regras de preferência em interseção não sinalizada.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-007",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Os veículos destinados a socorro de incêndio e salvamento, os de polícia, os de fiscalização e operação de trânsito e as ambulâncias, além de prioridade no trânsito, gozam de livre circulação, estacionamento e parada quando:",
    explicacao: "GABARITO: A. Art. 29, VII, do CTB: gozam de livre circulação, estacionamento e parada quando em serviço de urgência, de policiamento ostensivo ou de preservação da ordem pública, e devidamente identificados por dispositivos regulamentares de alarme sonoro e iluminação intermitente.",
    alternativas: [
      { texto: "Em serviço de urgência, de policiamento ostensivo ou de preservação da ordem pública, e devidamente identificados por alarme sonoro e iluminação intermitente.", correta: true },
      { texto: "Conduzidos por policiais fardados, mesmo em deslocamentos de rotina administrativa sem sirene acionada.", correta: false },
      { texto: "Transportando qualquer autoridade governamental dos três Poderes.", correta: false },
      { texto: "Estacionados em fila dupla em frente a estabelecimentos comerciais bancários.", correta: false },
      { texto: "Em qualquer situação pelo simples fato de ostentarem placas oficiais.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-008",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O uso do cinto de segurança é obrigatório em todas as vias do território nacional para condutores e passageiros, ressalvadas as hipóteses regulamentadas pelo CONTRAN.",
    explicacao: "GABARITO: CERTO. Art. 65 do CTB determina a obrigatoriedade do cinto de segurança.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-009",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "As crianças com idade inferior a 10 anos que não tenham atingido 1,45 m de altura devem ser transportadas nos bancos traseiros, em dispositivo de retenção adequado à sua idade, peso e altura.",
    explicacao: "GABARITO: CERTO. Art. 64 do CTB (redação dada pela Lei nº 14.071/2020) fixa os critérios de 10 anos e 1,45 m de altura.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-010",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O condutor manterá acesos os faróis do veículo, por meio da utilização da luz baixa, à noite e, mesmo durante o dia, em túneis e sob chuva, neblina ou cerração, bem como nas rodovias de pista simples situadas fora dos perímetros urbanos, no caso de veículos desprovidos de luzes de rodagem diurna (DRL).",
    explicacao: "GABARITO: CERTO. Art. 40, I, do CTB (redação pela Lei 14.071/2020): luz baixa durante o dia é exigida em pista simples fora do perímetro urbano (se sem DRL), além de túneis, chuva, neblina ou cerração.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11 to 18: Habilitação e Renovação de CNH
  {
    idSlug: "b10-trans-01-011",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O exame de aptidão física e mental para renovação da CNH será realizado a cada 10 anos para condutores com idade inferior a 50 anos; a cada 5 anos para condutores com idade igual ou superior a 50 e inferior a 70 anos; e a cada 3 anos para condutores com idade igual ou superior a 70 anos.",
    explicacao: "GABARITO: CERTO. Art. 147, § 2º, I, II e III, do CTB (redação pela Lei nº 14.071/2020): prazos de 10, 5 e 3 anos conforme faixas etárias.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-012",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Os condutores das categorias C, D e E deverão comprovar resultado negativo em exame toxicológico para a obtenção e a renovação da CNH, bem como realizar exame periódico com janela de detecção mínima de 90 dias a cada:",
    explicacao: "GABARITO: B. Art. 148-A, § 2º, do CTB: os condutores das categorias C, D e E com idade inferior a 70 anos serão submetidos a novo exame toxicológico no prazo de 2 anos e 6 meses (exame toxicológico periódico / intermediário).",
    alternativas: [
      { texto: "1 ano.", correta: false },
      { texto: "2 anos e 6 meses (dois anos e meio).", correta: true },
      { texto: "3 anos.", correta: false },
      { texto: "5 anos.", correta: false },
      { texto: "6 meses.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-013",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Para habilitar-se na categoria D, o candidato deverá ter no mínimo 21 anos de idade, estar habilitado no mínimo há dois anos na categoria B ou no mínimo há um ano na categoria C, e não ter cometido mais de uma infração gravíssima nos últimos 12 meses.",
    explicacao: "GABARITO: CERTO. Art. 145 do CTB fixa as condições para categoria D (21 anos, B há 2 anos ou C há 1 ano, não cometer mais de 1 gravíssima em 12 meses).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 14 to 25: Velocidades, Sinalização e Normas Especiais
  {
    idSlug: "b10-trans-01-014",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Onde não existir sinalização regulamentadora de velocidade, a velocidade máxima nas vias urbanas será de 80 km/h nas vias de trânsito rápido, 60 km/h nas vias arteriais, 40 km/h nas vias coletoras e 30 km/h nas vias locais.",
    explicacao: "GABARITO: CERTO. Art. 61, § 1º, I, do CTB estabelece os limites máximos legais nas vias urbanas sem sinalização específica.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-015",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nas rodovias de pista dupla, onde não houver sinalização regulamentadora, a velocidade máxima será de 110 km/h para automóveis, camionetas, caminhonetes e motocicletas, e de 90 km/h para os demais veículos.",
    explicacao: "GABARITO: CERTO. Art. 61, § 1º, II, 'a', 1 e 2, do CTB.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-016",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A velocidade mínima permitida não poderá ser inferior à metade da velocidade máxima estabelecida para a via, respeitadas as condições operacionais de trânsito e da via.",
    explicacao: "GABARITO: CERTO. Art. 62 do CTB: a velocidade mínima é a metade da máxima permitida.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-017",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "As ordens do agente de trânsito prevalecem sobre as normas de circulação e outros sinais de trânsito, inclusive sobre as indicações do semáforo.",
    explicacao: "GABARITO: CERTO. Art. 89 do CTB estabelece a ordem de prevalência da sinalização: as ordens do agente de trânsito sobrepõem-se a todas as demais.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-018",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A Lei nº 14.071/2020 introduziu o art. 44-A no CTB, regulamentando a livre conversão à direita diante de sinal vermelho do semáforo. Essa manobra é permitida:",
    explicacao: "GABARITO: D. Art. 44-A do CTB: é livre o movimento de conversão à direita diante de sinal vermelho do semáforo onde houver sinalização indicativa que permita essa conversão.",
    alternativas: [
      { texto: "Em qualquer cruzamento com semáforo, independentemente de sinalização, desde que não haja pedestres.", correta: false },
      { texto: "Apenas para viaturas policiais e veículos de socorro de urgência.", correta: false },
      { texto: "Exclusivamente no período noturno entre 22h e 6h.", correta: false },
      { texto: "Onde houver sinalização indicativa que permita expressamente essa conversão.", correta: true },
      { texto: "Apenas em rodovias federais com acostamento pavimentado.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-019",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Ao ultrapassar ciclista, o condutor de veículo automotor deve manter a distância lateral mínima de um metro e cinquenta centímetros (1,50 m) e reduzir a velocidade do veículo de forma compatível com a segurança do trânsito.",
    explicacao: "GABARITO: CERTO. Art. 201 e art. 220, XIII, do CTB: distância de 1,50 m ao ultrapassar bicicleta e redução de velocidade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-020",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nas vias urbanas e rurais de pista dupla, os veículos mais lentos e de maior porte devem utilizar a faixa da direita, ficando as faixas da esquerda destinadas à ultrapassagem e aos veículos de maior velocidade.",
    explicacao: "GABARITO: CERTO. Art. 29, IV, do CTB: faixa da direita para lentos/maior porte e faixa da esquerda para ultrapassagens/maior velocidade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-021",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A ultrapassagem pela direita é permitida quando o veículo que estiver à frente indicar, por sinal regulamentar, que vai entrar para a esquerda.",
    explicacao: "GABARITO: CERTO. Art. 29, IX, do CTB: a ultrapassagem pela direita é proibida como regra geral, salvo quando o veículo da frente estiver efetuando manobra para convergir à esquerda.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-022",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "É proibido o trânsito de veículos de tração animal nas vias públicas em qualquer hipótese, sendo privativo das áreas rurais particulares.",
    explicacao: "GABARITO: ERRADO. O trânsito de veículos de tração animal é permitido nas vias públicas pela direita da pista e junto ao acostamento ou bordo (art. 52 do CTB).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-trans-01-023",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O tempo de direção contínua dos motoristas profissionais de transporte de passageiros e de carga é regulamentado pelo CTB, sendo vedado dirigir por mais de 5 horas e meia ininterruptas no caso de transporte de passageiros.",
    explicacao: "GABARITO: CERTO. Art. 67-C do CTB: motorista profissional de passageiros não pode dirigir por mais de 4 horas ininterruptas (carga até 5h30min ininterruptas, art. 67-C, § 1º).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-024",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a opção que indica a conduta permitida ao condutor em relação ao uso de buzina no trânsito brasileiro:",
    explicacao: "GABARITO: C. Art. 41 do CTB: o condutor só pode usar buzina em toques breves para advertência a pedestres/outros condutores ou fora das áreas urbanas para indicar ultrapassagem.",
    alternativas: [
      { texto: "Uso prolongado e sucessivo entre as 22 horas e as 6 horas para desobstrução de via.", correta: false },
      { texto: "Uso contínuo em frente a hospitais para acelerar o fluxo em emergências.", correta: false },
      { texto: "Toque breve como simples advertência a pedestre ou a outro condutor com o objetivo de evitar acidentes.", correta: true },
      { texto: "Uso de buzina estridente e musical para saudar conhecidos em vias públicas.", correta: false },
      { texto: "Buzinar insistentemente em cruzamentos semáforicos ao abrir o sinal verde.", correta: false },
    ],
  },
  {
    idSlug: "b10-trans-01-025",
    disciplina_id: "589019e2-64df-583b-88f5-dc2e0eeb60e6",
    assunto_id: "a059f9e2-aaa6-5d07-ae38-56d8024c3b23",
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Registro Nacional Positivo de Condutores (RNPC), administrado pelo órgão máximo executivo de trânsito da União, tem por finalidade cadastrar condutores que não tenham cometido infração de trânsito sujeita a pontuação nos últimos 12 meses, com vistas à concessão de benefícios fiscais e tarifários.",
    explicacao: "GABARITO: CERTO. Art. 268-A do CTB (introduzido pela Lei nº 14.071/2020) disciplina o RNPC (cadastro positivo de bons condutores).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
];

const file01Content = `import { TAXONOMIA } from "./taxonomia.mjs";\n\nexport const transito01Questoes = ${JSON.stringify(transito01, null, 2)};\n`;
fs.writeFileSync(path.join(__dirname, "transito_01.mjs"), file01Content, "utf8");
console.log("transito_01.mjs gerado com sucesso! (25 questões)");
