import { TAXONOMIA } from "./taxonomia.mjs";

export const procPenal02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b10-procp-02-001",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "Um policial militar de folga e em trajes civis presenciou, no interior de uma agência bancária, um indivíduo sacando uma arma de fogo e anunciando assalto aos caixas. Concomitantemente, um cliente do banco que estava ao lado do assaltante percebeu a distração do infrator. De acordo com a disciplina legal da prisão em flagrante no Código de Processo Penal, a realização da prisão em flagrante constitui dever jurídico funcional para o agente de segurança pública (flagrante obrigatório ou compulsório) e faculdade legal para o cidadão comum (flagrante facultativo).",
    explicacao: "GABARITO: CERTO. Art. 301 do Código de Processo Penal: 'Qualquer do povo poderá e as autoridades policiais e seus agentes deverão prender quem quer que seja encontrado em flagrante delito' (flagrante facultativo para os populares e flagrante obrigatório/compulsório para os agentes de segurança pública).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-002",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O Supremo Tribunal Federal, no julgamento das ADIs 3360 e 4109, fixou que a decretação de prisão temporária (Lei 7.960/1989) exige cumulativamente: i) imprescindibilidade para as investigações; ii) fundadas razões de autoria ou participação em crimes taxativamente previstos; iii) justificação em fatos novos ou contemporâneos; e iv) inadequação de outras medidas cautelares alternativas.",
    explicacao: "GABARITO: CERTO. STF (ADIs 3360 e 4109): Estabeleceu os 5 requisitos cumulativos e a interpretação conforme à Constituição da Lei 7.960/89, afastando a decretação de ofício pelo juiz e exigindo contemporaneidade, imprescindibilidade concreta e não cabimento de cautelares diversas.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-003",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A realização da audiência de custódia no prazo de 24 horas após a realização da prisão é obrigatória para todas as modalidades prisionais (em flagrante, preventiva ou temporária), nos termos do art. 310 do CPP e das resoluções do CNJ.",
    explicacao: "GABARITO: CERTO. Art. 310 do CPP e ADPF 347 do STF: A realização da audiência de custódia no prazo de até 24 horas é direito subjetivo fundamental de qualquer pessoa presa, aplicando-se tanto às prisões em flagrante quanto às prisões decorrentes de mandado judicial (preventiva, temporária, etc.).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-004",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Considera-se em flagrante quase-crime (ou flagrante impróprio) o agente que é perseguido, logo após pela autoridade, pelo ofendido ou por qualquer pessoa, em situação que faça presumir ser autor da infração.",
    explicacao: "GABARITO: CERTO. Art. 302, III, do CPP: 'Considera-se em flagrante delito quem: III - é perseguido, logo após, pela autoridade, pelo ofendido ou por qualquer pessoa, em situação que faça presumir ser autor da infração' (Flagrante impróprio ou quase-flagrante).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-005",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.jurisdicao_competencia_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A competência de foro será, de regra, determinada pelo lugar em que se consumar a infração, ou, no caso de tentativa, pelo lugar em que for praticado o último ato de execução.",
    explicacao: "GABARITO: CERTO. Art. 70, caput, do CPP: 'A competência será, de regra, determinada pelo lugar em que se consumar a infração, ou, no caso de tentativa, pelo lugar em que for praticado o último ato de execução' (Teoria do Resultado para fixação da competência territorial ratione loci).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-006",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O magistrado pode decretar a prisão preventiva de ofício na fase de inquérito policial quando houver grave comoção social e periculosidade comprovada do investigado.",
    explicacao: "GABARITO: ERRADO. Art. 311 do CPP (com redação da Lei 13.964/2019 - Pacote Anticrime): É absolutamente VEDADA a decretação de prisão preventiva de ofício pelo juiz, tanto na fase inquisitorial quanto na fase judicial. Exige-se sempre provocação do Ministério Público ou representação da autoridade policial.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-procp-02-007",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A monitoração eletrônica e a proibição de acesso ou frequência a determinados lugares são medidas cautelares diversas da prisão expressamente previstas no art. 319 do Código de Processo Penal.",
    explicacao: "GABARITO: CERTO. Art. 319, II e IX, do CPP: O rol de medidas cautelares diversas da prisão inclui a monitoração eletrônica (tornozeleira) e a proibição de frequência a determinados lugares.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-008",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Nos termos do Código de Processo Penal, o valor recolhido a título de fiança servirá preferencialmente para o pagamento das custas do processo, da indenização do dano causado pelo crime e da multa, restituindo-se o saldo remanescente, se houver, ao afiançado em caso de absolvição ou extinção da punibilidade.",
    explicacao: "GABARITO: CERTO. Art. 336 e art. 337 do CPP: O valor da fiança garante o pagamento de custas, indenização do dano e multa, operando-se a restituição do saldo líquido corrigido quando proferida sentença absolutória ou declarada extinta a punibilidade.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-009",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Não é válida a prisão em flagrante preparada ou provocada quando a atividade da polícia ou de terceiro induz o cometimento do crime e torna absolutamente impossível a sua consumação.",
    explicacao: "GABARITO: CERTO. Súmula 145 do STF: 'Não há crime, quando a preparação do flagrante pela polícia torna impossível a sua consumação' (Flagrante provocado/preparado constitui crime impossível). Distingue-se do flagrante esperado (que é válido e legal).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-010",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Decretada a prisão preventiva, deverá o órgão emissor da decisão revisar a necessidade de sua manutenção a cada 90 (noventa) dias, mediante decisão fundamentada, sob pena de ilegalidade.",
    explicacao: "GABARITO: CERTO. Art. 316, parágrafo único, do CPP (incluído pela Lei 13.964/2019): 'Decretada a prisão preventiva, deverá o órgão emissor da decisão revisar a necessidade de sua manutenção a cada 90 (noventa) dias, mediante decisão fundamentada, de ofício, sob pena de tornar a prisão ilegal'. O STF esclareceu que a não revisão não gera soltura automática, devendo o juiz ser instado a decidir.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-20. FGV / VUNESP / FCC (Múltipla Escolha)
  {
    idSlug: "b10-procp-02-011",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 312 do Código de Processo Penal, a prisão preventiva poderá ser decretada como garantia da ordem pública, da ordem econômica, por conveniência da instrução criminal ou para assegurar a aplicação da lei penal, quando houver prova da existência do crime e:",
    explicacao: "GABARITO: B. Art. 312, caput, do CPP: A prisão preventiva exige prova da existência do crime e indício suficiente de autoria e de perigo gerado pelo estado de liberdade do imputado (Fumus comissi delicti + Periculum libertatis).",
    alternativas: [
      { texto: "Confissão prévia irretratável prestada na delegacia de polícia.", correta: false },
      { texto: "Indício suficiente de autoria e de perigo gerado pelo estado de liberdade do imputado.", correta: true },
      { texto: "Certidão negativa de antecedentes expedida pelo tribunal de justiça.", correta: false },
      { texto: "Comprovação de ausência de ocupação lícita formal e residência própria.", correta: false },
      { texto: "Manifestação favorável unânime do conselho de sentença.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-012",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Ao efetuar a prisão em flagrante de um indivíduo, a autoridade policial deve entregar ao preso, no prazo de até 24 horas após a prisão, documento com indicação dos motivos da prisão, do condutor e das testemunhas, denominado:",
    explicacao: "GABARITO: D. Art. 306, § 2º, do CPP: 'No mesmo prazo (24 horas), será entregue ao preso, mediante recibo, a nota de culpa, assinada pela autoridade, com o motivo da prisão, o nome do condutor e os das testemunhas'.",
    alternativas: [
      { texto: "Auto de reconhecimento pessoal.", correta: false },
      { texto: "Alvará de soltura condicional.", correta: false },
      { texto: "Laudo pericial cautelar.", correta: false },
      { texto: "Nota de culpa.", correta: true },
      { texto: "Carta precatória inquisitorial.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-013",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O prazo de duração da prisão temporária (Lei 7.960/1989) nos crimes comuns em geral é de:",
    explicacao: "GABARITO: A. Art. 2º da Lei 7.960/1989: A prisão temporária terá o prazo de 5 (cinco) dias, prorrogável por igual período em caso de extrema e comprovada necessidade. Se o crime for hediondo ou equiparado, o prazo será de 30 dias prorrogável por mais 30 (art. 2º, § 4º, da Lei 8.072/1990).",
    alternativas: [
      { texto: "5 dias, prorrogável por igual período em caso de extrema e comprovada necessidade.", correta: true },
      { texto: "10 dias improrrogáveis em qualquer circunstância investigativa.", correta: false },
      { texto: "15 dias renováveis a critério exclusivo do delegado de polícia.", correta: false },
      { texto: "30 dias prorrogável apenas mediante laudo psiquiátrico oficial.", correta: false },
      { texto: "60 dias úteis com concordância expressa da defensoria pública.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-014",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.jurisdicao_competencia_penal,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Em relação à competência no processo penal brasileiro, compete à Justiça Federal processar e julgar:",
    explicacao: "GABARITO: C. Art. 109, IV, da CF/88 e Súmula 151 do STJ: Compete à Justiça Federal processar e julgar os crimes políticos e as infrações penais praticadas em detrimento de bens, serviços ou interesse da União ou de suas entidades autárquicas ou empresas públicas federais.",
    alternativas: [
      { texto: "Qualquer homicídio doloso praticado com arma de fogo de uso restrito das forças armadas.", correta: false },
      { texto: "O crime de estelionato previdenciário cometido contra fundação pública municipal conveniada.", correta: false },
      { texto: "Os crimes praticados em detrimento de bens, serviços ou interesse da União, autarquias federais ou empresas públicas federais.", correta: true },
      { texto: "Crimes de trânsito em rodovias estaduais delegadas a consórcios metropolitanos.", correta: false },
      { texto: "Roubos cometidos contra sociedades de economia mista estaduais em agências bancárias.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-015",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O indivíduo que é encontrado, logo depois, com instrumentos, armas, objetos ou papéis que façam presumir ser ele autor da infração penal encontra-se em situação de flagrante:",
    explicacao: "GABARITO: E. Art. 302, IV, do CPP: 'Considera-se em flagrante delito quem: IV - é encontrado, logo depois, com instrumentos, armas, objetos ou papéis que façam presumir ser ele autor da infração' (Flagrante presumido, ficto ou assimilado).",
    alternativas: [
      { texto: "Próprio (perfeito).", correta: false },
      { texto: "Impróprio (quase-flagrante).", correta: false },
      { texto: "Preparado (provocado).", correta: false },
      { texto: "Forjado (urdido).", correta: false },
      { texto: "Presumido (ficto).", correta: true },
    ],
  },
  {
    idSlug: "b10-procp-02-016",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Nos termos do art. 313 do CPP, será admitida a decretação da prisão preventiva nos crimes dolosos punidos com pena privativa de liberdade máxima superior a:",
    explicacao: "GABARITO: B. Art. 313, I, do CPP: Nos termos do art. 312 deste Código, será admitida a decretação da prisão preventiva: I - nos crimes dolosos punidos com pena privativa de liberdade máxima superior a 4 (quatro) anos.",
    alternativas: [
      { texto: "2 anos.", correta: false },
      { texto: "4 anos.", correta: true },
      { texto: "6 anos.", correta: false },
      { texto: "8 anos.", correta: false },
      { texto: "10 anos.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-017",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A prisão domiciliar (art. 318 do CPP) consiste no recolhimento do indiciado ou acusado em sua residência, só podendo dela ausentar-se com autorização judicial. Poderá o juiz substituir a prisão preventiva pela domiciliar quando o agente for, EXCETO:",
    explicacao: "GABARITO: A. Art. 318, I, do CPP: Exige-se maior de 80 (oitenta) anos, e não 60 anos. As demais hipóteses do art. 318 são: II - extremamente debilitado por motivo de grave doença; III - imprescindível aos cuidados especiais de pessoa menor de 6 anos de idade ou com deficiência; IV - gestante; V - mulher com filho de até 12 anos de idade incompletos; VI - homem, caso seja o único responsável pelos cuidados do filho de até 12 anos incompletos.",
    alternativas: [
      { texto: "Maior de 60 anos com atividade profissional autônoma regular.", correta: true },
      { texto: "Maior de 80 anos.", correta: false },
      { texto: "Extremamente debilitado por motivo de grave doença.", correta: false },
      { texto: "Gestante.", correta: false },
      { texto: "Mulher com filho de até 12 anos de idade incompletos.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-018",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.jurisdicao_competencia_penal,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Nos crimes dolosos contra a vida praticados por militar estadual em serviço contra a vida de civil, a competência para o processo e julgamento é:",
    explicacao: "GABARITO: D. Art. 125, § 4º, da CF/88 e art. 9º, parágrafo único, do Código Penal Militar (com redação da Lei 13.491/2017): Os crimes dolosos contra a vida praticados por militares estaduais contra a vida de civis são da competência do Tribunal do Júri da Justiça Comum Estadual.",
    alternativas: [
      { texto: "Da Auditoria Militar Estadual em sessão secreta de oficiais.", correta: false },
      { texto: "Do Superior Tribunal Militar em grau originário de recurso.", correta: false },
      { texto: "Do juiz auditor militar singular togado monocrático.", correta: false },
      { texto: "Do Tribunal do Júri da Justiça Comum Estadual.", correta: true },
      { texto: "Da Justiça Federal se houver cooperação em operações de GLO.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-019",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A prisão preventiva NÃO será decretada com a finalidade de antecipação de cumprimento de pena ou como decorrência automática da investigação criminal ou da apresentação ou recebimento da denúncia. Esse princípio consagra a:",
    explicacao: "GABARITO: C. Art. 313, § 2º, do CPP (Lei 13.964/2019): 'Não será admitida a decretação da prisão preventiva com a finalidade de antecipação de cumprimento de pena ou como decorrência imediata de investigação criminal ou da apresentação ou recebimento da denúncia'. Veda a prisão preventiva ex lege / automática.",
    alternativas: [
      { texto: "Natureza punitiva sancionatória das cautelares.", correta: false },
      { texto: "Presunção absoluta de culpabilidade primária.", correta: false },
      { texto: "Vedação ao uso da prisão cautelar como antecipação executória de pena.", correta: true },
      { texto: "Incompetência do juiz de garantias em infrações graves.", correta: false },
      { texto: "Legalidade estrita do flagrante forjado policial.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-020",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Recebidos os autos do auto de prisão em flagrante, no prazo de até 24 horas, o juiz deverá, fundamentadamente:",
    explicacao: "GABARITO: B. Art. 310 do CPP: O juiz deverá: I - relaxar a prisão ilegal; II - converter a prisão em flagrante em preventiva, quando presentes os requisitos do art. 312 e se revelarem inadequadas ou insuficientes as medidas cautelares diversas da prisão; ou III - conceder liberdade provisória, com ou sem fiança.",
    alternativas: [
      { texto: "Decretar a prisão temporária de ofício sem oitiva do Ministério Público.", correta: false },
      { texto: "Relaxar a prisão ilegal, convertê-la em preventiva ou conceder liberdade provisória.", correta: true },
      { texto: "Julgar imediatamente o mérito da ação penal condenatória em audiência sumaríssima.", correta: false },
      { texto: "Remeter os autos para a ouvidoria policial sem manifestação jurisdicional.", correta: false },
      { texto: "Suspender os direitos políticos do indiciado até a proliferação da sentença.", correta: false },
    ],
  },

  // 21-30. Módulos Avançados de Prisões e Competência
  {
    idSlug: "b10-procp-02-021",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O descumprimento de qualquer das obrigações impostas por força de outras medidas cautelares diversas da prisão autoriza o juiz, de ofício ou a requerimento, a substituir a medida, impor outra em cumulação ou, em último caso, decretar a prisão preventiva.",
    explicacao: "GABARITO: CERTO. Art. 282, § 4º, do CPP: 'No caso de descumprimento de qualquer das obrigações impostas, o juiz, mediante requerimento do Ministério Público, de seu assistente ou do querelante, ou por representação da autoridade policial, poderá substituir a medida, impor outra em cumulação, ou, em último caso, decretar a prisão preventiva (art. 312, § 1º)'",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-022",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.jurisdicao_competencia_penal,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A conexão e a continência importarão na unidade de processo e julgamento, salvo no concurso entre a jurisdição comum e a militar ou entre a jurisdição comum e a do juízo de menores.",
    explicacao: "GABARITO: CERTO. Art. 79 do CPP: A conexão e continência unem os processos, ressalvando-se: I - no concurso entre a jurisdição comum e a militar; II - no concurso entre a jurisdição comum e a do juízo de menores.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-023",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O uso de algemas é lícito quando demonstrado, de forma motivada por escrito, perigo à integridade física própria ou alheia, fundado receio de fuga ou resistência à prisão, nos termos da Súmula Vinculante 11 do STF.",
    explicacao: "GABARITO: CERTO. Súmula Vinculante 11 do STF (PR-F-R: Perigo, Fuga, Resistência): 'Só é lícito o uso de algemas em casos de resistência e de fundado receio de fuga ou de perigo à integridade física própria ou alheia, por parte do preso ou de terceiros, justificada a excepcionalidade por escrito'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-024",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O flagrante prorrogado (ou diferido / ação controlada) permite à polícia retardar a intervenção policial para o momento mais eficaz do ponto de vista da formação de provas e captura do maior número de integrantes de organizações criminosas.",
    explicacao: "GABARITO: CERTO. Ação controlada (art. 8º da Lei 12.850/2013 e art. 53, II, da Lei 11.343/2006): Trata-se do flagrante postergado/diferido/retardado, plenamente admitido na legislação especial.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-025",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "A decisão que decretar, substituir ou denegar a prisão preventiva será sempre motivada e fundamentada, não se considerando fundamentada a decisão que se limitar à indicação, à reprodução ou à paráfrase de ato normativo ou que empregar conceitos jurídicos indeterminados sem explicar o motivo concreto de sua incidência no caso.",
    explicacao: "GABARITO: CERTO. Art. 315, §§ 1º e 2º, do CPP (redação da Lei 13.964/2019): Exige fundamentação concreta e detalhada para decisões cautelares penais, aplicando-se os mesmos parâmetros do art. 489, § 1º, do CPC.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-026",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 323 do Código de Processo Penal, NÃO será concedida fiança nos seguintes casos, EXCETO:",
    explicacao: "GABARITO: D. O art. 323 do CPP veda a fiança nos crimes de racismo, tortura, tráfico ilícito de entorpecentes, terrorismo e crimes hediondos, bem como ações de grupos armados contra a ordem constitucional. O crime culposo na direção de veículo automotor admite arbitramento de fiança.",
    alternativas: [
      { texto: "Nos crimes de racismo.", correta: false },
      { texto: "Nos crimes de tortura, tráfico ilícito de entorpecentes e terrorismo.", correta: false },
      { texto: "Nos crimes hediondos.", correta: false },
      { texto: "No crime de homicídio culposo na direção de veículo automotor com vítima fatal.", correta: true },
      { texto: "Nos crimes cometidos por grupos armados, civis ou militares, contra a ordem constitucional.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-027",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.jurisdicao_competencia_penal,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "No concurso entre a competência do júri e a de outro órgão da jurisdição comum, prevalecerá a competência:",
    explicacao: "GABARITO: A. Art. 78, I, do CPP: 'Na determinação da competência por conexão ou continência, serão observadas as seguintes regras: I - no concurso entre a competência do júri e a de outro órgão da jurisdição comum, prevalecerá a competência do júri' (Garantia constitucional do art. 5º, XXXVIII, da CF).",
    alternativas: [
      { texto: "Do Tribunal do Júri.", correta: true },
      { texto: "Do juizado especial criminal de trânsito.", correta: false },
      { texto: "Da vara especializada em lavagem de dinheiro.", correta: false },
      { texto: "Do juízo de família e sucessões anexo.", correta: false },
      { texto: "Do juízo que primeiro proferir despacho saneador.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-028",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Quando a infração for inafiançável, a falta de exibição do mandado judicial de prisão no momento da captura não obstará a prisão, desde que:",
    explicacao: "GABARITO: B. Art. 287 do CPP: 'Se a infração for inafiançável, a falta de exibição do mandado não obstará a prisão, e o preso, em tal caso, será imediatamente apresentado ao juiz que tiver expedido o mandado, para realização de audiência de custódia'.",
    alternativas: [
      { texto: "O agente policial possua autorização verbal telefônica do escrivão de plantão.", correta: false },
      { texto: "O preso seja imediatamente apresentado ao juiz que tiver expedido o mandado.", correta: true },
      { texto: "Haja renúncia expressa do indiciado ao direito de ser assistido por advogado.", correta: false },
      { texto: "O mandado seja publicado no diário oficial da união no prazo de 48 horas úteis.", correta: false },
      { texto: "A diligência ocorra exclusivamente no interior de aeroportos internacionais.", correta: false },
    ],
  },
  {
    idSlug: "b10-procp-02-029",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em nenhuma hipótese a prisão em flagrante poderá ser efetuada aos domingos ou durante a noite, exigindo-se autorização judicial expressa para detenções nesses horários.",
    explicacao: "GABARITO: ERRADO. Art. 283 do CPP e art. 5º, XI, da CF: A prisão em flagrante delito pode ser executada em qualquer dia e a qualquer hora, inclusive domingos e feriados e durante o período noturno (em locais públicos ou mesmo com ingresso domiciliar no caso de flagrante delito).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-procp-02-030",
    disciplina_id: TAXONOMIA.disciplinas.processo_penal,
    assunto_id: TAXONOMIA.assuntos.prisoes_cautelares,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A prisão preventiva poderá ser revogada pelo juiz se, no correr do processo, verificar a falta de motivo para que subsista, bem como de novo decretada, se sobrevierem razões que a justifiquem. Isso decorre da característica da:",
    explicacao: "GABARITO: C. Art. 316 do CPP: Consagra a cláusula rebus sic stantibus / provisionalidade / revogabilidade das medidas cautelares penais (as cautelares perduram enquanto persistirem as condições fáticas que as legitimaram).",
    alternativas: [
      { texto: "Indisponibilidade material.", correta: false },
      { texto: "Inquisitoriedade perene.", correta: false },
      { texto: "Provisionalidade (cláusula rebus sic stantibus).", correta: true },
      { texto: "Imutabilidade absolutória.", correta: false },
      { texto: "Unicidade processual estrita.", correta: false },
    ],
  },
];
