import { TAXONOMIA } from "./taxonomia.mjs";

export const penal02Questoes = [
  // 1-10. CEBRASPE (Certo/Errado)
  {
    idSlug: "b10-pen-02-001",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O feminicídio constitui circunstância qualificadora do crime de homicídio, caracterizando-se quando o crime é praticado contra a mulher por razões da condição de sexo feminino, o que envolve violência doméstica e familiar ou menosprezo/discriminação à condição de mulher.",
    explicacao: "GABARITO: CERTO. Art. 121, § 2º, VI e § 2º-A do Código Penal: O feminicídio é homicídio qualificado praticado contra a mulher por razões da condição de sexo feminino, considerando-se que há razões dessa natureza quando o crime envolve: I - violência doméstica e familiar; II - menosprezo ou discriminação à condição de mulher.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-002",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em operação de patrulhamento tático, uma equipe policial avistou um indivíduo que acabara de subtrair a motocicleta de um cidadão mediante grave ameaça com simulacro de arma de fogo. Iniciada incontinenti perseguição tática ininterrupta, os policiais conseguiram interceptar e deter o autor a três quadras do local da abordagem, recuperando o veículo intacto cerca de cinco minutos após a subtração. Nesse cenário fático, de acordo com a jurisprudência sumulada dos Tribunais Superiores, o crime de roubo restou consumado, haja vista a inversão da posse da coisa, sendo juridicamente desnecessária a posse mansa, pacífica ou desvigiada.",
    explicacao: "GABARITO: CERTO. Súmula 582 do STJ: 'Consuma-se o crime de roubo com a inversão da posse do bem mediante emprego de violência ou grave ameaça, ainda que por breve tempo e em seguida à perseguição imediata ao agente e recuperação da coisa roubada, sendo prescindível a posse mansa e pacífica ou desvigiada' (Teoria da Apprehensio ou Amotio).",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-003",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "No crime de peculato culposo, a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade; se lhe é posterior, reduz de metade a pena imposta.",
    explicacao: "GABARITO: CERTO. Art. 312, § 3º, do Código Penal: 'No caso do parágrafo anterior (peculato culposo), a reparação do dano, se precede à sentença irrecorrível, extingue a punibilidade; se lhe é posterior, reduz de metade a pena imposta'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-004",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O policial civil que exige para si, diretamente e em razão de sua função, vantagem indevida de motorista abordado para não lavrar auto de infração comete crime de corrupção passiva.",
    explicacao: "GABARITO: ERRADO. O verbo EXIGIR tipifica o crime de CONCUSSÃO (art. 316 do CP: 'Exigir, para si ou para outrem, direta ou indiretamente, ainda que fora da função ou antes de assumi-la, mas em razão dela, vantagem indevida'). O crime de corrupção passiva (art. 317 do CP) possui os núcleos 'solicitar', 'receber' ou 'aceitar promessa'.",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-02-005",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Oficial da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O crime de prevaricação consuma-se quando o funcionário público retarda ou deixa de praticar, indevidamente, ato de ofício, ou o pratica contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal.",
    explicacao: "GABARITO: CERTO. Art. 319 do Código Penal: 'Retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal: Pena - detenção, de três meses a um ano, e multa'. O elemento subjetivo especial é imprescindível.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-006",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Papiloscopista Policial Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A apropriação indébita distingue-se do estelionato porque, na apropriação indébita, o agente obtém a posse legítima e desvigiada da coisa sem fraude prévia, vindo a inverter o ânimo posteriormente (animus rem sibi habendi), ao passo que no estelionato a fraude é anterior e determinante para a entrega do bem.",
    explicacao: "GABARITO: CERTO. Na apropriação indébita (art. 168 do CP), o dolo é superveniente à posse lícita. No estelionato (art. 171 do CP), o dolo e a fraude são antecedentes e provocam o erro na vítima que entrega voluntariamente o bem.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-007",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "No homicídio praticado contra autoridade ou agente integrante dos órgãos de segurança pública (art. 144 da CF) no exercício da função ou em decorrência dela, incide qualificadora específica, equiparada a crime hediondo nos termos da legislação de regência.",
    explicacao: "GABARITO: CERTO. Art. 121, § 2º, VII, do Código Penal (homicídio funcional) e art. 1º, I, da Lei 8.072/1990: É qualificado e hediondo o homicídio cometido contra agentes de segurança pública (ou seus cônjuges, companheiros ou parentes consanguíneos até o terceiro grau) no exercício da função ou em decorrência dela.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-008",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A conduta de opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio, configura o crime de resistência.",
    explicacao: "GABARITO: CERTO. Art. 329 do Código Penal define o crime de resistência: 'Opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem lhe esteja prestando auxílio'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-009",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "O crime de extorsão mediante sequestro é crime formal e permanente, consumando-se no momento em que a vítima tem sua liberdade de locomoção cerceada, sendo irrelevante para a consumação a efetiva obtenção da vantagem econômica indevida pretendida.",
    explicacao: "GABARITO: CERTO. Súmula 96 do STJ e jurisprudência pacífica: A extorsão mediante sequestro (art. 159 do CP) é crime formal que se consuma com a privação da liberdade da vítima vinculada à exigência do resgate, sendo a obtenção da vantagem mero exaurimento do delito.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-010",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O crime de desacato (art. 331 do CP) continua plenamente em vigor no ordenamento jurídico pátrio, tendo o STF e a Terceira Seção do STJ firmado tese de que a sua tipificação é compatível com a Convenção Americana sobre Direitos Humanos.",
    explicacao: "GABARITO: CERTO. O STF (ADPF 496) e o STJ (HC 379.269/MS - Terceira Seção) pacificaram que o crime de desacato (art. 331 do CP) é constitucional e compatível com o Pacto de San José da Costa Rica, tutelando o respeito e o prestígio da função pública.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },

  // 11-20. FGV / VUNESP / FCC (Múltipla Escolha)
  {
    idSlug: "b10-pen-02-011",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Rodrigo, servidor público estadual lotado no setor de compras de uma autarquia, apropria-se de computadores portáteis pertencentes à repartição dos quais tinha a posse legítima em razão de suas atribuições funcionais, vendendo-os a terceiros. Rodrigo praticou o crime de:",
    explicacao: "GABARITO: A. Art. 312, caput, 1ª parte, do Código Penal tipifica o Peculato-Apropriação: 'Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo, ou desviá-lo, em proveito próprio ou alheio'.",
    alternativas: [
      { texto: "Peculato-apropriação.", correta: true },
      { texto: "Peculato-furto com rompimento de obstáculo.", correta: false },
      { texto: "Corrupção passiva privilegiada.", correta: false },
      { texto: "Concussão consumada por terceiro.", correta: false },
      { texto: "Estelionato qualificado contra a administração.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-012",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Subtrair coisa móvel alheia, para si ou para outrem, mediante rompimento de obstáculo à subtração da coisa ou durante o repouso noturno, tipifica o crime de:",
    explicacao: "GABARITO: B. O art. 155 do Código Penal define o furto; o repouso noturno é causa de aumento de pena (§ 1º) e o rompimento de obstáculo qualifica o delito (§ 4º, I).",
    alternativas: [
      { texto: "Roubo impróprio.", correta: false },
      { texto: "Furto circunstanciado e qualificado.", correta: true },
      { texto: "Dano qualificado por motivo egoístico.", correta: false },
      { texto: "Apropriação indébita com abuso de confiança.", correta: false },
      { texto: "Extorsão patrimonial noturna.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-013",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Oferecer ou prometer vantagem indevida a funcionário público para determiná-lo a praticar, omitir ou retardar ato de ofício constitui o crime de:",
    explicacao: "GABARITO: C. Art. 333 do Código Penal: Corrupção ativa: 'Oferecer ou prometer vantagem indevida a funcionário público, para determiná-lo a praticar, omitir ou retardar ato de ofício'. Crime praticado por particular contra a administração em geral.",
    alternativas: [
      { texto: "Tráfico de influência em órgãos fazendários.", correta: false },
      { texto: "Concussão imprópria.", correta: false },
      { texto: "Corrupção ativa.", correta: true },
      { texto: "Advocacia administrativa.", correta: false },
      { texto: "Condescendência criminosa continuada.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-014",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre os crimes contra a vida no Código Penal brasileiro, assinale a alternativa juridicamente correta:",
    explicacao: "GABARITO: D. No infanticídio (art. 123 do CP: matar, sob o estado puerperal, o próprio filho, durante o parto ou logo após), o estado puerperal é elementar do tipo e se comunica aos coautores e partícipes nos termos do art. 30 do CP.",
    alternativas: [
      { texto: "O homicídio privilegiado não admite a coexistência com nenhuma qualificadora de ordem objetiva.", correta: false },
      { texto: "O perdão judicial concedido no homicídio culposo tem natureza de sentença condenatória com registro de reincidência.", correta: false },
      { texto: "A indução ou instigação ao suicídio ou à automutilação não é punida quando a vítima for menor de 14 anos.", correta: false },
      { texto: "O estado puerperal no infanticídio é circunstância de caráter pessoal que se comunica aos coautores por ser elementar do crime.", correta: true },
      { texto: "O aborto praticado por médico prescinde do consentimento da gestante em qualquer situação de risco à saúde física.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-015",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Adquirir, receber, transportar, conduzir ou ocultar, em proveito próprio ou alheio, coisa que sabe ser produto de crime, ou influir para que terceiro, de boa-fé, a adquira, receba ou oculte, configura o delito de:",
    explicacao: "GABARITO: B. Art. 180, caput, do Código Penal define o crime de Receptação dolosa (própria na primeira parte e imprópria na segunda parte).",
    alternativas: [
      { texto: "Favorecimento real qualificado.", correta: false },
      { texto: "Receptação.", correta: true },
      { texto: "Fraude processual.", correta: false },
      { texto: "Lavagem de capitais básica.", correta: false },
      { texto: "Apropriação de coisa havida por erro.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-016",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "O funcionário público que, por indulgência, deixa de responsabilizar subordinado que cometeu infração no exercício do cargo comete o crime de:",
    explicacao: "GABARITO: C. Art. 320 do Código Penal: 'Deixar o funcionário, por indulgência, de responsabilizar subordinado que cometeu infração no exercício do cargo ou, quando lhe falte competência, não levar o fato ao conhecimento da autoridade competente: Pena - detenção, de quinze dias a um mês, ou multa' (Condescendência criminosa).",
    alternativas: [
      { texto: "Prevaricação ministerial.", correta: false },
      { texto: "Corrupção passiva privilegiada.", correta: false },
      { texto: "Condescendência criminosa.", correta: true },
      { texto: "Advocacia administrativa funcional.", correta: false },
      { texto: "Abandono de função continuado.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-017",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A lesão corporal praticada contra ascendente, descendente, irmão, cônjuge ou companheiro, ou com quem conviva ou tenha convivido, ou ainda prevalecendo-se o agente das relações domésticas, de coabitação ou de hospitalidade:",
    explicacao: "GABARITO: A. Art. 129, § 9º, do Código Penal (com alterações legislativas): trata-se da lesão corporal no contexto de violência doméstica e familiar, com pena agravada específica (detenção de 3 meses a 3 anos). Além disso, a Súmula 542 do STJ estabelece que a ação penal é pública incondicionada.",
    alternativas: [
      { texto: "Constitui modalidade de lesão corporal qualificada por violência doméstica, com ação penal pública incondicionada.", correta: true },
      { texto: "Depende obrigatoriamente de representação da vítima perante autoridade policial no prazo decadencial de 30 dias.", correta: false },
      { texto: "Admite a aplicação do instituto da transação penal previsto na Lei 9.099/95 sem restrições.", correta: false },
      { texto: "Configura infração de menor potencial ofensivo sujeita a suspensão condicional do processo.", correta: false },
      { texto: "Isenta de pena se houver reconciliação prévia do casal perante o assistente social forense.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-018",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Delegado de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Sobre o crime de usurpação de função pública (art. 328 do CP) e desobediência (art. 330 do CP), assinale a afirmativa correta:",
    explicacao: "GABARITO: E. A usurpação de função pública qualifica-se se o agente aufere vantagem econômica ou moral com a prática dos atos funcionais indevidos (art. 328, parágrafo único, do CP). O crime de desobediência exige ordem legal emanada de funcionário público competente.",
    alternativas: [
      { texto: "A usurpação de função pública é crime próprio, somente podendo ser praticado por funcionário público de carreira afim.", correta: false },
      { texto: "O crime de desobediência admite a modalidade culposa quando o particular alega desconhecimento da ordem.", correta: false },
      { texto: "O descumprimento de ordem de parada em blitz de trânsito jamais tipifica crime por ausência de previsão expressa.", correta: false },
      { texto: "A desobediência absorve o crime de resistência em virtude do princípio da subsidiariedade tácita.", correta: false },
      { texto: "A usurpação de função pública qualifica-se se do fato o agente aufere vantagem de qualquer natureza.", correta: true },
    ],
  },
  {
    idSlug: "b10-pen-02-019",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O agente que, logo depois de subtraída a coisa, emprega violência contra pessoa ou grave ameaça a fim de assegurar a impunidade do crime ou a detenção da coisa para si ou para terceiro comete:",
    explicacao: "GABARITO: C. Art. 157, § 1º, do Código Penal define o roubo impróprio: 'Na mesma pena incorre quem, logo depois de subtraída a coisa, emprega violência contra pessoa ou grave ameaça, a fim de assegurar a impunidade do crime ou a detenção da coisa para si ou para terceiro'.",
    alternativas: [
      { texto: "Furto qualificado por violência superveniente.", correta: false },
      { texto: "Extorsão indireta com dolo eventual.", correta: false },
      { texto: "Roubo impróprio.", correta: true },
      { texto: "Concussão continuada.", correta: false },
      { texto: "Exercício arbitrário das próprias razões.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-020",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "facil",
    enunciado: "Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário público, tipifica o crime de:",
    explicacao: "GABARITO: B. Art. 321 do Código Penal define o crime de Advocacia Administrativa: 'Patrocinar, direta ou indiretamente, interesse privado perante a administração pública, valendo-se da qualidade de funcionário: Pena - detenção, de um a três meses, ou multa'.",
    alternativas: [
      { texto: "Tráfico de influência.", correta: false },
      { texto: "Advocacia administrativa.", correta: true },
      { texto: "Prevaricação patrimonial.", correta: false },
      { texto: "Corrupção passiva bilateral.", correta: false },
      { texto: "Violação de sigilo profissional.", correta: false },
    ],
  },

  // 21-30. Módulos Avançados de Penal Especial
  {
    idSlug: "b10-pen-02-021",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A calúnia consiste em imputar falsamente a alguém fato definido como crime, sendo admitida, como regra geral, a exceção da verdade para comprovar a veracidade da imputação.",
    explicacao: "GABARITO: CERTO. Art. 138 do Código Penal define a calúnia e o § 3º estabelece que 'Admite-se a prova da verdade, salvo: I - se, constituindo o fato imputado crime de ação privada, o ofendido não foi condenado por sentença irrecorrível; II - se o fato é imputado a qualquer das pessoas indicadas no nº I do art. 141; III - se do crime imputado, embora de ação pública, o ofendido foi absolvido por sentença irrecorrível'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-022",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "No crime de estelionato (art. 171 do CP), a ação penal é pública condicionada à representação do ofendido como regra geral, ressalvadas as hipóteses em que a vítima seja a administração pública, criança ou adolescente, pessoa com deficiência mental ou maior de 70 anos.",
    explicacao: "GABARITO: CERTO. Art. 171, § 5º, do CP (inserido pelo Pacote Anticrime, Lei 13.964/2019): Somente se procede mediante representação, salvo se a vítima for: I - a administração pública, direta ou indireta; II - criança ou adolescente; III - pessoa com deficiência mental; ou IV - maior de 70 (setenta) anos ou incapaz.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-023",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "O particular que solicita, exige, cobra ou obtém, para si ou para outrem, vantagem ou promessa de vantagem, a pretexto de influir em ato praticado por funcionário público no exercício da função comete crime de tráfico de influência.",
    explicacao: "GABARITO: CERTO. Art. 332 do Código Penal: Tráfico de influência: 'Solicitar, exigir, cobrar ou obter, para si ou para outrem, vantagem ou promessa de vantagem, a pretexto de influir em ato praticado por funcionário público no exercício da função: Pena - reclusão, de 2 a 5 anos, e multa'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-024",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "O latrocínio é espécie de roubo qualificado pelo resultado morte (art. 157, § 3º, II, do CP), sendo da competência do juízo singular da vara criminal comum, e não do Tribunal do Júri.",
    explicacao: "GABARITO: CERTO. Súmula 603 do STF: 'A competência para o processo e julgamento por latrocínio é do juiz singular e não do tribunal do júri'. Trata-se de crime contra o patrimônio com resultado morte, e não crime doloso contra a vida.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-025",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Considera-se funcionário público por equiparação, para os efeitos penais, quem exerce cargo, emprego ou função em entidade paraestatal, bem como quem trabalha para empresa prestadora de serviço contratada ou conveniada para a execução de atividade típica da Administração Pública.",
    explicacao: "GABARITO: CERTO. Art. 327, § 1º, do Código Penal: 'Equipara-se a funcionário público quem exerce cargo, emprego ou função em entidade paraestatal, e quem trabalha para empresa prestadora de serviço contratada ou conveniada para a execução de atividade típica da Administração Pública'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-026",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Investigador de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Perseguir alguém, reiteradamente e por qualquer meio, ameaçando-lhe a integridade física ou psicológica, restringindo-lhe a capacidade de locomoção ou, de qualquer forma, invadindo ou perturbando sua esfera de liberdade ou privacidade, tipifica o crime de:",
    explicacao: "GABARITO: D. Art. 147-A do Código Penal tipifica expressamente o crime de Perseguição (Stalking), incluído pela Lei 14.132/2021.",
    alternativas: [
      { texto: "Violência psicológica contra a mulher.", correta: false },
      { texto: "Constrangimento ilegal qualificado.", correta: false },
      { texto: "Ameaça continuada simples.", correta: false },
      { texto: "Perseguição (stalking).", correta: true },
      { texto: "Perturbação do sossego público majorada.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-027",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_patrimonio,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O crime de dano (art. 163 do CP) é qualificado quando cometido:",
    explicacao: "GABARITO: A. Art. 163, parágrafo único, do CP: O dano é qualificado se cometido: I - com violência à pessoa ou grave ameaça; II - com emprego de substância inflamável ou explosiva, se o fato não constitui crime mais grave; III - contra o patrimônio da União, de Estado, do DF, de Município ou de autarquia, fundação pública, empresa pública ou sociedade de economia mista; IV - por motivo egoístico ou com prejuízo considerável para a vítima.",
    alternativas: [
      { texto: "Contra o patrimônio da União, de Estado, de Município, de autarquia ou de empresa pública.", correta: true },
      { texto: "Por negligência exclusiva do agente sem dolo específico.", correta: false },
      { texto: "Contra bens móveis de valor insignificante sob vigilância eletrônica.", correta: false },
      { texto: "Exclusivamente durante os feriados nacionais civis ou religiosos.", correta: false },
      { texto: "Em estado de embriaguez voluntária com prejuízo financeiro reduzido.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-028",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "Dar às verbas ou rendas públicas aplicação diversa da estabelecida em lei configura o crime de:",
    explicacao: "GABARITO: B. Art. 315 do Código Penal: 'Emprego irregular de verbas ou rendas públicas: Dar às verbas ou rendas públicas aplicação diversa da estabelecida em lei: Pena - detenção, de um a três meses, ou multa'.",
    alternativas: [
      { texto: "Peculato-desvio qualificado.", correta: false },
      { texto: "Emprego irregular de verbas ou rendas públicas.", correta: true },
      { texto: "Prevaricação financeira continuada.", correta: false },
      { texto: "Estelionato administrativo funcional.", correta: false },
      { texto: "Fraude à execução orçamentária autárquica.", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-029",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_pessoa,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Perito Criminal Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "facil",
    enunciado: "A violação de domicílio (art. 150 do CP) não se configura quando o ingresso for efetuado durante o dia, com observância das formalidades legais, para efetuar prisão ou outra diligência policial legalmente autorizada.",
    explicacao: "GABARITO: CERTO. Art. 150, § 3º, II, do CP e art. 5º, XI, da CF/88: Não constitui crime a entrada ou permanência em casa alheia ou em suas dependências a qualquer hora do dia ou da noite, quando algum crime está sendo ali praticado ou na iminência de o ser, ou durante o dia, por determinação judicial ou com as formalidades legais.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "b10-pen-02-030",
    disciplina_id: TAXONOMIA.disciplinas.penal,
    assunto_id: TAXONOMIA.assuntos.crimes_adm_publica,
    banca_nome: "Inédita / Estilo FCC",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A falsa imputação de crime que dá causa à instauração de inquérito policial, procedimento investigatório criminal, processo judicial, processo administrativo disciplinar, inquérito civil ou ação de improbidade administrativa contra alguém, sabendo-o inocente, configura o crime de:",
    explicacao: "GABARITO: E. Art. 339 do Código Penal tipifica o crime de Denunciação Caluniosa (com redação ampliada pela Lei 14.110/2020 para incluir PAD, PIC, inquérito civil e ação de improbidade administrativa).",
    alternativas: [
      { texto: "Comunicação falsa de crime ou contravenção.", correta: false },
      { texto: "Falso testemunho em fase instrutória.", correta: false },
      { texto: "Autoacusação falsa perante autoridade.", correta: false },
      { texto: "Fraude processual qualificada por dolo.", correta: false },
      { texto: "Denunciação caluniosa.", correta: true },
    ],
  },
];
