import { TAXONOMIA } from "./taxonomia.mjs";

export const const02Questoes = [
  // 1-8. CEBRASPE (Certo/Errado)
  {
    idSlug: "cst-02-001",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio, por meio dos órgãos expressamente enumerados no art. 144 da Constituição Federal.",
    explicacao: "GABARITO: CERTO. Art. 144, caput, da CF/88: 'A segurança pública, dever do Estado, direito e responsabilidade de todos, é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio, através dos seguintes órgãos: I - polícia federal; II - polícia rodoviária federal; III - polícia ferroviária federal; IV - polícias civis; V - polícias militares e corpos de bombeiros militares; VI - polícias penais federal, estaduais e distrital'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-002",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Com o advento da Emenda Constitucional nº 104/2019, as polícias penais, vinculadas ao órgão administrador do sistema penal da unidade federativa a que pertencem, passaram a integrar expressamente o rol dos órgãos de segurança pública do art. 144 da CF/88, incumbindo-lhes a segurança dos estabelecimentos penais.",
    explicacao: "GABARITO: CERTO. Art. 144, VI e § 5º-A, da CF/88 (inseridos pela EC 104/2019): Às polícias penais, vinculadas ao órgão administrador do sistema penal da unidade federativa a que pertencem, cabe a segurança dos estabelecimentos penais.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-003",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Conforme entendimento fixado pelo Plenário do STF na ADPF 995, as Guardas Municipais integram o Sistema de Segurança Pública (SUSP), sendo constitucional a realização de policiamento preventivo e comunitário e a atuação na preservação da ordem pública no âmbito municipal.",
    explicacao: "GABARITO: CERTO. STF, ADPF 995: O Plenário declarou que as Guardas Municipais integram o Sistema Único de Segurança Pública (SUSP) e possuem atribuição para realizar segurança pública urbana preventiva e comunitária, proteção de bens, serviços e instalações e apoio à ordem pública.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-004",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Considerando a disciplina constitucional das funções essenciais de segurança pública, se durante uma operação conjunta for apurada a prática concomitante de crime de homicídio doloso comum praticado por civil e crime de concussão praticado por policial militar em serviço contra o patrimônio da corporação, a competência de polícia judiciária para apurar a infração penal militar caberá à própria autoridade de polícia judiciária militar, incumbindo à Polícia Civil a investigação do homicídio comum.",
    explicacao: "GABARITO: CERTO. Conforme o art. 144, § 4º, da CF/88 e o Código de Processo Penal Militar, à Polícia Civil incumbem as funções de polícia judiciária e a apuração de infrações penais comuns (exceto as militares e as de competência da União), cabendo à autoridade de polícia judiciária militar a investigação dos crimes militares próprios e impróprios.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-005",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Às polícias militares cabem a polícia ostensiva e a preservação da ordem pública; aos corpos de bombeiros militares, além das atribuições definidas em lei, incumbe a execução de atividades de defesa civil.",
    explicacao: "GABARITO: CERTO. Art. 144, § 5º, da CF/88: 'Às polícias militares cabem a polícia ostensiva e a preservação da ordem pública; aos corpos de bombeiros militares, além das atribuições definidas em lei, incumbe a execução de atividades de defesa civil'.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-006",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Rodoviária Federal",
    cargo_nome: "Policial Rodoviário Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "A Polícia Rodoviária Federal, órgão permanente, estruturado em carreira, destina-se, na forma da lei, ao patrulhamento ostensivo das rodovias e ferrovias federais.",
    explicacao: "GABARITO: ERRADO. Art. 144, § 2º, da CF/88: A Polícia Rodoviária Federal destina-se ao patrulhamento ostensivo das rodovias federais. O patrulhamento das ferrovias federais incumbe à Polícia Ferroviária Federal (art. 144, § 3º).",
    alternativas: [
      { texto: "Certo", correta: false },
      { texto: "Errado", correta: true },
    ],
  },
  {
    idSlug: "cst-02-007",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado_poderes,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "dificil",
    enunciado: "Compete privativamente à União legislar sobre direito penal, processual penal, trânsito e transporte, bem como sobre diretrizes para a segurança pública e organização das polícias civis e militares.",
    explicacao: "GABARITO: CERTO. Art. 22, I, XI e XXI, da CF/88: Compete privativamente à União legislar sobre: I - direito civil, comercial, penal, processual... XI - trânsito e transporte; XXI - normas gerais de organização, efetivos, material bélico, garantias, convocação, mobilização, inatividades e pensões das polícias militares e corpos de bombeiros militares.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  {
    idSlug: "cst-02-008",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo CEBRASPE",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "certo_errado",
    dificuldade: "medio",
    enunciado: "Em situação de grave calamidade pública decorrente de inundações em um Estado da federação, o Governador do Estado determinou a mobilização extraordinária do Corpo de Bombeiros Militar para ações integradas de defesa civil e socorro humanitário. Sob a ótica constitucional, o CBM é força auxiliar e reserva do Exército Brasileiro, subordinando-se operacional e administrativamente ao Governador do Estado.",
    explicacao: "GABARITO: CERTO. O art. 144, § 5º e § 6º, da CF/88 estabelece que os corpos de bombeiros militares e as polícias militares são forças auxiliares e reserva do Exército, mas sua subordinação orgânica, administrativa e operacional dá-se perante os Governadores dos Estados, do Distrito Federal e dos Territórios.",
    alternativas: [
      { texto: "Certo", correta: true },
      { texto: "Errado", correta: false },
    ],
  },
  // 9-13. FGV (Múltipla Escolha)
  {
    idSlug: "cst-02-009",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Federal",
    cargo_nome: "Agente de Polícia Federal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o art. 144, § 1º, da Constituição Federal, à Polícia Federal, instituída por lei como órgão permanente, estruturado em carreira, destina-se a:",
    explicacao: "GABARITO: A. Art. 144, § 1º, da CF/88: À Polícia Federal destina-se: apurar infrações penais contra a ordem política e social ou em detrimento de bens, serviços e interesses da União ou de suas entidades autárquicas e empresas públicas; prevenir e reprimir o tráfico ilícito de entorpecentes e drogas afins, o contrabando e o descaminho; exercer as funções de polícia marítima, aeroportuária e de fronteiras; e exercer com exclusividade as funções de polícia judiciária da União.",
    alternativas: [
      { texto: "exercer com exclusividade as funções de polícia judiciária da União, prevenir e reprimir o tráfico ilícito de entorpecentes, o contrabando e o descaminho, e exercer as funções de polícia marítima, aeroportuária e de fronteiras.", correta: true },
      { texto: "patrulhar ostensivamente as rodovias e estradas estaduais.", correta: false },
      { texto: "atuar como força auxiliar do Exército em operações de garantia da lei e da ordem municipal.", correta: false },
      { texto: "fiscalizar exclusivamente as prisões e penitenciárias federais de segurança máxima.", correta: false },
      { texto: "subordinar-se diretamente aos Governadores dos Estados da federação.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-010",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Delegado de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "dificil",
    enunciado: "A respeito do direito de greve dos servidores públicos que atuam na área de segurança pública, o Supremo Tribunal Federal, ao julgar o Recurso Extraordinário com repercussão geral (Tema 541 / ARE 654.432), fixou a tese de que:",
    explicacao: "GABARITO: B. STF, Tema 541: 'O exercício do direito de greve, sob qualquer forma ou modalidade, é vedado aos policiais civis e a todos os servidores públicos que atuem diretamente na área de segurança pública'.",
    alternativas: [
      { texto: "é assegurado plenamente aos policiais civis desde que mantido 30% do efetivo em atividade.", correta: false },
      { texto: "o exercício do direito de greve, sob qualquer forma ou modalidade, é vedado aos policiais civis e a todos os servidores públicos que atuem diretamente na área de segurança pública.", correta: true },
      { texto: "apenas os militares são proibidos de fazer greve, sendo a greve permitida para policiais civis e guardas municipais.", correta: false },
      { texto: "a greve é permitida se houver atraso salarial superior a sessenta dias.", correta: false },
      { texto: "a proibição de greve aplica-se somente à Polícia Federal e à PRF.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-011",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos do art. 144, § 8º, da Constituição Federal de 1988, os Municípios poderão constituir guardas municipais destinadas à:",
    explicacao: "GABARITO: C. Art. 144, § 8º, da CF/88: 'Os Municípios poderão constituir guardas municipais destinadas à proteção de seus bens, serviços e instalações, conforme dispuser a lei'.",
    alternativas: [
      { texto: "investigação exclusiva de crimes funcionais de servidores públicos.", correta: false },
      { texto: "realização de perícias médico-legais e papiloscópicas.", correta: false },
      { texto: "proteção de seus bens, serviços e instalações, conforme dispuser a lei.", correta: true },
      { texto: "guarda de fronteiras internacionais e repressão ao contrabando.", correta: false },
      { texto: "subordinação direta ao Comando do Exército Brasileiro.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-012",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado_poderes,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o art. 142, § 3º, IV, da Constituição Federal, ao militar são proibidas:",
    explicacao: "GABARITO: D. Art. 142, § 3º, IV, da CF/88 (aplicável aos militares estaduais por força do art. 42, § 1º): 'ao militar são proibidas a sindicalização e a greve'.",
    alternativas: [
      { texto: "a realização de cursos de nível superior e pós-graduação.", correta: false },
      { texto: "o casamento com pessoa de nacionalidade estrangeira.", correta: false },
      { texto: "a aquisição de imóveis residenciais fora do Estado.", correta: false },
      { texto: "a sindicalização e a greve.", correta: true },
      { texto: "a participação em votações eleitorais obrigatórias.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-013",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo FGV",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Oficial Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A segurança viária, exercida para a preservação da ordem pública e da incolumidade das pessoas e do seu patrimônio nas vias públicas (art. 144, § 10, da CF/88):",
    explicacao: "GABARITO: E. Art. 144, § 10, da CF/88: A segurança viária compreende a educação, engenharia e fiscalização de trânsito, além de outras atividades previstas em lei, que assegurem ao cidadão o direito à mobilidade urbana eficiente, e compete, no âmbito dos Estados, do Distrito Federal e dos Municípios, aos respectivos órgãos ou entidades executivos e seus agentes de trânsito.",
    alternativas: [
      { texto: "é de competência privativa da Polícia Federal e das Forças Armadas.", correta: false },
      { texto: "exclui a educação e a engenharia de trânsito, restringindo-se à aplicação de multas.", correta: false },
      { texto: "não integra o capítulo de segurança pública da Carta Magna.", correta: false },
      { texto: "é exercida unicamente em rodovias federais pedagiadas.", correta: false },
      { texto: "compreende a educação, engenharia e fiscalização de trânsito, competindo aos órgãos ou entidades executivos e seus agentes de trânsito nos Estados, DF e Municípios.", correta: true },
    ],
  },
  // 14-16. VUNESP (Múltipla Escolha)
  {
    idSlug: "cst-02-014",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal de 1988, a remuneração dos servidores policiais integrantes dos órgãos de segurança pública será fixada na forma de:",
    explicacao: "GABARITO: A. Art. 144, § 9º, c/c art. 39, § 4º, da CF/88: A remuneração dos servidores policiais integrantes dos órgãos de segurança pública será fixada na forma de subsídio, em parcela única.",
    alternativas: [
      { texto: "subsídio, fixado em parcela única, vedado o acréscimo de qualquer gratificação, adicional ou abono ordinário.", correta: true },
      { texto: "comissão variável calculada sobre o volume de prisões efetuadas.", correta: false },
      { texto: "diárias de alimentação e transporte sem vencimento básico.", correta: false },
      { texto: "salário comercial regido obrigatoriamente pela CLT.", correta: false },
      { texto: "honorários de sucumbência administrativa.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-015",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Civil",
    cargo_nome: "Escrivão de Polícia",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Assinale a alternativa que indica CORRETAMENTE a autoridade que dirige a Polícia Civil de um Estado:",
    explicacao: "GABARITO: B. Art. 144, § 4º, da CF/88: 'Às polícias civis, dirigidas por delegados de polícia de carreira...' Portanto, a direção cabe a Delegado de Polícia de carreira.",
    alternativas: [
      { texto: "Coronel da Polícia Militar da ativa.", correta: false },
      { texto: "Delegado de Polícia de carreira.", correta: true },
      { texto: "Promotor de Justiça Titular da Vara Criminal.", correta: false },
      { texto: "Juiz Corregedor de Polícia.", correta: false },
      { texto: "Procurador-Geral do Estado.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-016",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.organizacao_estado_poderes,
    banca_nome: "Inédita / Estilo VUNESP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Nos termos da Constituição Federal, a competência para legislar concorrentemente sobre direito penitenciário, financeiro, penitenciário, econômico e urbanístico cabe a:",
    explicacao: "GABARITO: C. Art. 24, I, da CF/88: 'Compete à União, aos Estados e ao Distrito Federal legislar concorrentemente sobre: I - direito tributário, financeiro, penitenciário, econômico e urbanístico'.",
    alternativas: [
      { texto: "União e Municípios exclusivamente.", correta: false },
      { texto: "Municípios e Territórios.", correta: false },
      { texto: "União, Estados e Distrito Federal.", correta: true },
      { texto: "Conselho Nacional de Justiça privativamente.", correta: false },
      { texto: "apenas ao Congresso Nacional por lei complementar.", correta: false },
    ],
  },
  // 17-18. AOCP (Múltipla Escolha)
  {
    idSlug: "cst-02-017",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Polícia Penal",
    cargo_nome: "Policial Penal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "O preenchimento do quadro de servidores das polícias penais será feito, exclusivamente, por meio de:",
    explicacao: "GABARITO: D. Art. 144, § 5º-A, da CF/88: 'O preenchimento do quadro de servidores das polícias penais será feito, exclusivamente, por meio de concurso público e por meio da transformação dos cargos dos atuais agentes penitenciários e dos cargos de agentes penitenciários ou de cargos equivalentes'.",
    alternativas: [
      { texto: "livre nomeação e exoneração pelo Governador do Estado.", correta: false },
      { texto: "indicação política com sabatina pela Assembleia Legislativa.", correta: false },
      { texto: "contrato temporário de prestação de serviços por prazo indeterminado.", correta: false },
      { texto: "concurso público e por meio da transformação dos cargos dos atuais agentes penitenciários ou equivalentes.", correta: true },
      { texto: "requisição compulsória de militares da reserva remunerada.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-018",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo AOCP",
    orgao_nome: "Guarda Municipal",
    cargo_nome: "Guarda Civil Municipal",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "A criação de Guardas Municipais é uma faculdade conferida pela Constituição Federal de 1988 a qual ente da federação?",
    explicacao: "GABARITO: A. Art. 144, § 8º, da CF/88: 'Os Municípios poderão constituir guardas municipais destinadas à proteção de seus bens, serviços e instalações, conforme dispuser a lei'. Trata-se de prerrogativa dos Municípios.",
    alternativas: [
      { texto: "Aos Municípios.", correta: true },
      { texto: "Apenas aos Estados-membros com mais de 5 milhões de habitantes.", correta: false },
      { texto: "Privativamente à União para atuação em Brasília.", correta: false },
      { texto: "Aos Territórios Federais sob intervenção.", correta: false },
      { texto: "Aos Consórcios Internacionais de Segurança.", correta: false },
    ],
  },
  // 19-20. IBFC (Múltipla Escolha)
  {
    idSlug: "cst-02-019",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Polícia Militar",
    cargo_nome: "Soldado da Polícia Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Conforme o art. 144 da Constituição Federal de 1988, as Polícias Militares e os Corpos de Bombeiros Militares são considerados:",
    explicacao: "GABARITO: B. Art. 144, § 6º, da CF/88: 'As polícias militares e os corpos de bombeiros militares, forças auxiliares e reserva do Exército...'",
    alternativas: [
      { texto: "órgãos da Justiça Militar da União.", correta: false },
      { texto: "forças auxiliares e reserva do Exército.", correta: true },
      { texto: "divisões subordinadas ao Ministério da Marinha.", correta: false },
      { texto: "instituições autônomas e desvinculadas dos Governos Estaduais.", correta: false },
      { texto: "corporações privadas de segurança patrimonial.", correta: false },
    ],
  },
  {
    idSlug: "cst-02-020",
    disciplina_id: TAXONOMIA.disciplinas.constitucional,
    assunto_id: TAXONOMIA.assuntos.seguranca_publica_art144,
    banca_nome: "Inédita / Estilo IBFC",
    orgao_nome: "Corpo de Bombeiros Militar",
    cargo_nome: "Bombeiro Militar",
    ano: 2026,
    tipo: "multipla_escolha",
    dificuldade: "medio",
    enunciado: "Além das atribuições definidas em lei, aos Corpos de Bombeiros Militares incumbe a execução de atividades de:",
    explicacao: "GABARITO: C. Art. 144, § 5º, parte final, da CF/88: 'aos corpos de bombeiros militares, além das atribuições definidas em lei, incumbe a execução de atividades de defesa civil'.",
    alternativas: [
      { texto: "policiamento de fronteiras marítimas.", correta: false },
      { texto: "investigação exclusiva de crimes fazendários.", correta: false },
      { texto: "defesa civil.", correta: true },
      { texto: "guarda de presídios federais.", correta: false },
      { texto: "patrulhamento das ferrovias nacionais.", correta: false },
    ],
  },
];
