import { DISCIPLINAS, ASSUNTOS, criarQuestaoCE, criarQuestaoME, writeModuleFile } from "./helpers.mjs";

// ==============================================================
// M13: DIREITO ADMINISTRATIVO - PRINCÍPIOS, PODERES E ATOS (20 questões)
// ==============================================================
const m13_data = [
  {
    tipo: "CE",
    slug: "l13-adm-prin-001-limp-legalidade-estrita-particular",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "facil",
    enunciado: "Enquanto para os particulares o princípio da legalidade (art. 5º, II da CF) significa que é permitido fazer tudo o que a lei não proíbe, para a Administração Pública o princípio da legalidade estrita (art. 37, caput da CF) impõe que o administrador público só pode agir quando e como a lei autoriza ou determina.",
    explicacao: "GABARITO: CERTO. Princípio clássico do Direito Administrativo que diferencia a autonomia da vontade privada da vinculação positiva à lei na função administrativa.",
    gabaritoCerto: true,
    conceito: "Princípio da legalidade na Administração Pública",
    habilidade: "Distinguir o princípio da legalidade aplicável aos particulares e à Administração",
    tese: "A Administração Pública só pode agir secundum legem e intra legem",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-prin-002-impessoalidade-vedacao-promocao-pessoal",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A publicidade dos atos, programas, obras, serviços e campanhas dos órgãos públicos deverá ter caráter educativo, informativo ou de orientação social, dela não podendo constar nomes, símbolos ou imagens que caracterizem promoção pessoal de autoridades ou servidores públicos, sob pena de violação ao princípio da impessoalidade e eventual ato de improbidade administrativa.",
    explicacao: "GABARITO: CERTO. Art. 37, § 1º da CF/88 e jurisprudência pacífica do STF e STJ.",
    gabaritoCerto: true,
    conceito: "Princípio da impessoalidade e vedação à promoção pessoal",
    habilidade: "Reconhecer as vedações constitucionais de autopromoção na publicidade oficial",
    tese: "A publicidade estatal não pode conter símbolos que personalizem o governante ou servidor",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-prin-003-autotutela-sumula-473-stf-revogacao-anulacao",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A Administração Pública pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos; ou revogá-los, por motivo de conveniência ou oportunidade, respeitados os direitos adquiridos e ressalvada, em todos os casos, a apreciação judicial.",
    explicacao: "GABARITO: CERTO. Enunciado clássico da Súmula 473 do Supremo Tribunal Federal e art. 53 da Lei nº 9.784/99.",
    gabaritoCerto: true,
    conceito: "Princípio da autotutela administrativa (Súmula 473 STF)",
    habilidade: "Diferenciar as hipóteses de anulação e revogação de atos administrativos",
    tese: "A Administração anula atos ilegais e revoga atos inconvenientes por autotutela",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-pod-004-poder-policia-atributos-autoexecutoriedade",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "medio",
    enunciado: "O poder de polícia administrativa manifesta-se por meio de atributos como a discricionariedade, a autoexecutoriedade e a coercibilidade; a autoexecutoriedade autoriza a Administração a executar diretamente suas decisões sem prévia autorização judicial, estando presente quando expressamente prevista em lei ou quando se tratar de medida urgente de defesa da ordem pública.",
    explicacao: "GABARITO: CERTO. Doutrina administrativista consagrada (Hely Lopes Meirelles, Maria Sylvia Zanella Di Pietro): a autoexecutoriedade depende de previsão legal expressa ou urgência fática.",
    gabaritoCerto: true,
    conceito: "Atributos do poder de polícia administrativa",
    habilidade: "Identificar os requisitos e limites do atributo da autoexecutoriedade",
    tese: "A autoexecutoriedade dispensa chancela judicial prévia em situações de urgência ou expressa lei",
    nivel: "aplicar"
  },
  {
    tipo: "ME",
    slug: "l13-adm-pod-005-abuso-poder-excesso-desvio-finalidade",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "FGV", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "O abuso de poder é gênero que compreende duas espécies fundamentais: o excesso de poder e o desvio de finalidade (ou desvio de poder). Assinale a opção que descreve corretamente a ocorrência de desvio de finalidade em ato administrativo.",
    explicacao: "GABARITO: C. O desvio de finalidade ocorre quando o agente atua dentro de sua competência legal, mas busca um fim alheio ao interesse público ou diverso daquele fixado pela lei (vício no elemento finalidade).",
    alternativas: [
      { letra: "A", texto: "O agente público pratica ato que extravasa os limites quantitativos ou materiais de sua competência funcional.", correta: false, explicacao_especifica: "Incorreta. Isso caracteriza excesso de poder (vício na competência)." },
      { letra: "B", texto: "O ato administrativo padece de ausência de motivação fática quando esta era expressamente exigida pela norma.", correta: false, explicacao_especifica: "Incorreta. Vício no elemento motivo/forma." },
      { letra: "C", texto: "O agente atua formalmente dentro de sua esfera de atribuições, mas pratica o ato visando a interesse privado, perseguição a desafeto ou objetivo diverso daquele determinado pela lei.", correta: true, explicacao_especifica: "Correta. Conceito clássico de desvio de poder/finalidade." },
      { letra: "D", texto: "O ato é editado por autoridade desprovida de investidura regular no cargo público.", correta: false, explicacao_especifica: "Incorreta. Trata-se de usurpação de função ou funcionário de fato (vício de competência)." },
      { letra: "E", texto: "A autoridade aplica sanção disciplinar exatamente conforme a gradação objetiva imposta pela lei sem qualquer margem de arbítrio.", correta: false, explicacao_especifica: "Incorreta. Trata-se de ato vinculado perfeitamente lícito." }
    ],
    conceito: "Espécies de abuso de poder: desvio de finalidade vs excesso de poder",
    habilidade: "Diferenciar desvio de finalidade e excesso de poder na atuação administrativa",
    tese: "Desvio de finalidade vicia o fim legal do ato mesmo com competência formal do agente",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-pod-006-poder-hierarquico-delegacao-avocacao",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "medio",
    enunciado: "O poder hierárquico confere à autoridade superior a faculdade de distribuir funções, fiscalizar, dar ordens, avocar e delegar competências; segundo a Lei nº 9.784/1999, não podem ser objeto de delegação a edição de atos de caráter normativo, a decisão de recursos administrativos e as matérias de competência exclusiva do órgão ou autoridade.",
    explicacao: "GABARITO: CERTO. Art. 13 da Lei nº 9.784/99 (mnemônico CE-NO-RA: Competência Exclusiva, atos Normativos e Recursos Administrativos).",
    gabaritoCerto: true,
    conceito: "Limites da delegação de competência (art. 13 Lei 9.784/99)",
    habilidade: "Identificar as matérias indelegáveis no processo administrativo federal",
    tese: "Atos normativos, recursos e competências exclusivas não admitem delegação",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-pod-007-poder-disciplinar-vinculacao-abertura-pad",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "O poder disciplinar é a faculdade atribuída à Administração Pública de apurar infrações e aplicar penalidades funcionais a servidores públicos e a particulares que com ela possuam vínculo jurídico específico, caracterizando-se a instauração do processo disciplinar como um dever vinculado da autoridade que toma ciência de falta funcional.",
    explicacao: "GABARITO: CERTO. Art. 143 da Lei nº 8.112/90: a autoridade que tiver ciência de irregularidade no serviço público é obrigada a promover a sua apuração imediata.",
    gabaritoCerto: true,
    conceito: "Poder disciplinar e obrigatoriedade da apuração",
    habilidade: "Compreender a natureza vinculada da instauração de apuração disciplinar",
    tese: "A instauração de procedimento apuratório é dever vinculado da autoridade competente",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-008-elementos-ato-administrativo-competencia-finalidade",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "facil",
    enunciado: "São elementos ou requisitos de validade indispensáveis a todo ato administrativo a competência, a finalidade, a forma, o motivo e o objeto, sendo a competência, a finalidade e a forma requisitos vinculados por excelência na legislação brasileira.",
    explicacao: "GABARITO: CERTO. Art. 2º da Lei nº 4.717/65 (Lei da Ação Popular) e doutrina administrativa consolidada.",
    gabaritoCerto: true,
    conceito: "Elementos de validade do ato administrativo (COM-FI-FOR-M-OB)",
    habilidade: "Identificar os elementos vinculados e discricionários dos atos administrativos",
    tese: "Competência, finalidade e forma são elementos sempre vinculados pela lei",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-009-teoria-motivos-determinantes-vinculacao-motivo",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "De acordo com a teoria dos motivos determinantes, a validade do ato administrativo vincula-se aos motivos fáticos e jurídicos apresentados pela Administração como justificativa para sua edição, de modo que, se tais motivos forem inexistentes, falsos ou juridicamente inadequados, o ato será nulo, ainda que se trate de ato originalmente discricionário cuja motivação não fosse obrigatória.",
    explicacao: "GABARITO: CERTO. Teoria dos motivos determinantes amplamente acolhida pela jurisprudência do STF e STJ.",
    gabaritoCerto: true,
    conceito: "Teoria dos motivos determinantes",
    habilidade: "Aplicar a teoria dos motivos determinantes ao controle de nulidade de atos discricionários motivados",
    tese: "Motivação falsa ou inexistente invalida o ato administrativo discricionário",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-adm-ato-010-atributos-ato-administrativo-presuncao-legitimidade",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Vunesp", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "medio",
    enunciado: "Dentre os atributos do ato administrativo, a presunção de legitimidade e veracidade opera relevantes efeitos de ordem processual e substantiva. A esse respeito, assinale a afirmativa correta.",
    explicacao: "GABARITO: B. A presunção de legitimidade e veracidade tem caráter relativo (iuris tantum), transferindo o ônus da prova da ilegalidade ou inveracidade para quem impugna o ato administrativo.",
    alternativas: [
      { letra: "A", texto: "Possui caráter absoluto (iuris et de iure), impedindo que o particular conteste em juízo a higidez dos fatos certificados pelo policial.", correta: false, explicacao_especifica: "Incorreta. A presunção é relativa (iuris tantum)." },
      { letra: "B", texto: "Tem natureza relativa (iuris tantum), invertendo o ônus da prova em desfavor do administrado que alega a irregularidade do ato.", correta: true, explicacao_especifica: "Correta. Os atos presumem-se válidos e verdadeiros até prova em contrário produzida pelo particular." },
      { letra: "C", texto: "Exige que a Administração Pública ajuíze ação judicial declaratória prévia antes de executar qualquer multa de trânsito.", correta: false, explicacao_especifica: "Incorreta. A presunção de legitimidade permite a execução direta do ato administrativo." },
      { letra: "D", texto: "Aplica-se unicamente aos atos administrativos enunciativos, sendo vedada em atos punitivos.", correta: false, explicacao_especifica: "Incorreta. É atributo comum a todas as categorias de atos administrativos." },
      { letra: "E", texto: "Desaparece automaticamente sempre que o administrado interpõe recurso administrativo tempestivo.", correta: false, explicacao_especifica: "Incorreta. A presunção se mantém vigente durante o curso recursal, ressalvado efeito suspensivo concedido." }
    ],
    conceito: "Presunção de legitimidade e veracidade dos atos administrativos",
    habilidade: "Identificar os efeitos da presunção iuris tantum sobre a distribuição do ônus probatório",
    tese: "A presunção de legitimidade dos atos públicos é relativa e inverte o ônus da prova",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-011-convalidação-requisitos-vicios-sanaveis",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A convalidação (ou sanatória) é o ato administrativo pelo qual a Administração supre vício de ato ilegal com efeitos retroativos (ex tunc), sendo juridicamente admitida apenas quando o vício residir na competência (desde que não exclusiva) ou na forma (quando não essencial à validade do ato), desde que não cause lesão ao interesse público nem prejuízo a terceiros.",
    explicacao: "GABARITO: CERTO. Art. 55 da Lei nº 9.784/99: convalidação opera ex tunc sobre competência não privativa e forma não essencial.",
    gabaritoCerto: true,
    conceito: "Convalidação de atos administrativos e requisitos do art. 55 da Lei 9.784/99",
    habilidade: "Distinguir vícios sanáveis e insanáveis para fins de convalidação",
    tese: "Convalidação retroage e só incide sobre competência não exclusiva e forma não solene",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-prin-012-seguranca-juridica-prazo-decadencial-5-anos",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "O direito da Administração de anular os atos administrativos de que decorram efeitos favoráveis para os destinatários decai em cinco anos, contados da data em que foram praticados, salvo comprovada má-fé, em homenagem ao princípio da segurança jurídica e da proteção à confiança legítima.",
    explicacao: "GABARITO: CERTO. Art. 54 da Lei Federal nº 9.784/99.",
    gabaritoCerto: true,
    conceito: "Decadência quinquenal da autotutela e proteção da confiança",
    habilidade: "Reconhecer o prazo decadencial de anulação de atos favoráveis e a ressalva de má-fé",
    tese: "A autotutela decai em 5 anos para atos favoráveis, ressalvada má-fé do beneficiário",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-pod-013-policia-judiciaria-vs-policia-administrativa",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "facil",
    enunciado: "A polícia administrativa atua preponderantemente de forma preventiva, incidindo sobre bens, direitos e atividades para condicionar seu uso ao bem-estar coletivo, ao passo que a polícia judiciária atua preponderantemente de forma repressiva, incidindo diretamente sobre indivíduos para apurar infrações penais e colher elementos de autoria e materialidade.",
    explicacao: "GABARITO: CERTO. Distinção doutrinária clássica entre polícia administrativa e polícia judiciária.",
    gabaritoCerto: true,
    conceito: "Distinção entre polícia administrativa e polícia judiciária",
    habilidade: "Diferenciar a natureza, objeto e incidência das polícias administrativa e judiciária",
    tese: "Polícia administrativa incide sobre atividades/bens; polícia judiciária incide sobre pessoas na persecução criminal",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-014-imperatividade-atos-negociais-enunciativos",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A imperatividade é o atributo pelo qual os atos administrativos se impõem a terceiros independentemente de sua concordância; todavia, a imperatividade não está presente em todos os atos administrativos, inexistindo, por exemplo, nos atos negociais (como licenças e autorizações) e nos atos meramente enunciativos (como certidões e pareceres).",
    explicacao: "GABARITO: CERTO. Doutrina administrativista majoritária (Di Pietro e Celso Antônio Bandeira de Mello): nem todo ato possui imperatividade.",
    gabaritoCerto: true,
    conceito: "Atributo da imperatividade e suas exceções",
    habilidade: "Reconhecer os atos administrativos desprovidos do atributo da imperatividade",
    tese: "Imperatividade não existe em atos negociais e enunciativos",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-adm-prin-015-nepotismo-sumula-vinculante-13-cargos-politicos",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A Súmula Vinculante nº 13 do Supremo Tribunal Federal veda a nomeação de cônjuge, companheiro ou parente em linha reta, colateral ou por afinidade, até o terceiro grau, para cargo em comissão ou de confiança. A respeito da incidência dessa súmula em cargos de natureza eminentemente política (ex.: Secretários de Estado ou Ministros de Estado), assinale a afirmativa correta segundo o STF.",
    explicacao: "GABARITO: E. A Súmula Vinculante 13 não se aplica automaticamente à nomeação para cargos políticos, salvo se restar demonstrada inequívoca falta de qualificação técnica ou intuito de fraude/nepotismo cruzado.",
    alternativas: [
      { letra: "A", texto: "Aplica-se indistintamente com anulação automática de toda nomeação ministerial de parentes.", correta: false, explicacao_especifica: "Incorreta. Cargos políticos possuem excepcionalidade reconhecida pelo STF." },
      { letra: "B", texto: "Não se aplica a nenhum cargo da administração pública municipal, apenas à esfera federal.", correta: false, explicacao_especifica: "Incorreta. Aplica-se a todos os poderes de todos os entes federativos." },
      { letra: "C", texto: "Autoriza o nepotismo cruzado quando envolve poderes distintos no mesmo município.", correta: false, explicacao_especifica: "Incorreta. A SV 13 veda expressamente designações recíprocas (nepotismo cruzado)." },
      { letra: "D", texto: "Impede o cônjuge de ser aprovado em concurso público de provas e títulos.", correta: false, explicacao_especifica: "Incorreta. O concurso público é forma constitucional de provimento efetivo e não constitui nepotismo." },
      { letra: "E", texto: "A vedação não alcança, em regra, a nomeação para cargos políticos (como Secretários de Estado ou Municipais), ressalvados os casos de patente inaptidão técnica ou fraude manifesta à lei.", correta: true, explicacao_especifica: "Correta. Jurisprudência pacífica do Plenário do STF (Rcl 29.033 e Rcl 22.339)." }
    ],
    conceito: "Súmula Vinculante 13 e aplicação a agentes e cargos políticos",
    habilidade: "Analisar as exceções da Súmula Vinculante 13 fixadas pelo STF para cargos políticos",
    tese: "Cargos políticos não se submetem à SV 13 em regra, salvo falta de qualificação técnica ou fraude",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-016-cassacao-caducidade-contraposicao-extincao",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "A cassação é a forma de extinção do ato administrativo decorrente do descumprimento superveniente, pelo beneficiário, das condições legais ou regulamentares que permitiam a manutenção do ato, como ocorre quando o titular de uma licença policial passa a utilizá-la para fins ilícitos.",
    explicacao: "GABARITO: CERTO. Doutrina de Direito Administrativo: cassação decorre de culpa/ilegalidade superveniente do particular beneficiário.",
    gabaritoCerto: true,
    conceito: "Extinção do ato administrativo por cassação",
    habilidade: "Identificar as causas de cassação, caducidade e anulação de atos administrativos",
    tese: "A cassação extingue o ato quando o beneficiário descumpre requisitos de manutenção",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-pod-017-poder-regulamentar-decreto-autonomo-art84",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "O Chefe do Poder Executivo dispõe de competência para editar decretos autônomos para dispor sobre a organização e funcionamento da administração federal quando não implicar aumento de despesa nem criação ou extinção de órgãos públicos, bem como para a extinção de funções ou cargos públicos quando vagos.",
    explicacao: "GABARITO: CERTO. Art. 84, VI, 'a' e 'b' da CF/88 (introduzido pela EC 32/2001).",
    gabaritoCerto: true,
    conceito: "Decreto autônomo e limites do art. 84, VI da CF/88",
    habilidade: "Identificar as matérias passíveis de disciplina por decreto autônomo",
    tese: "Decreto autônomo organiza a administração sem criar órgãos/despesas e extingue cargos vagos",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-prin-018-continuidade-servico-publico-greve-policiais",
    assuntoId: ASSUNTOS.ADM_PRINCIPIOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "medio",
    enunciado: "O princípio da continuidade do serviço público fundamenta a tese consolidada pelo STF no Tema 541 (ARE 654.432), segundo a qual o exercício do direito de greve, sob qualquer forma ou modalidade, é expressamente vedado a todos os servidores públicos que atuem diretamente na área de segurança pública.",
    explicacao: "GABARITO: CERTO. Tese do STF no Tema 541 de repercussão geral: proibição absoluta de greve para policiais civis, federais, rodoviários e agentes penitenciários.",
    gabaritoCerto: true,
    conceito: "Vedação ao direito de greve para carreiras de segurança pública (STF Tema 541)",
    habilidade: "Aplicar a tese vinculante do STF sobre a inconstitucionalidade da greve policial",
    tese: "É inconstitucional a greve de servidores públicos da segurança pública",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-ato-019-silencio-administrativo-efeitos",
    assuntoId: ASSUNTOS.ADM_ATOS,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "O silêncio administrativo não consubstancia, em regra, ato administrativo, mas fato administrativo omissivo, não gerando deferimento tácito de pretensões do particular, salvo quando houver expressa e específica previsão legislativa atribuindo efeito confirmatório à inércia do órgão público.",
    explicacao: "GABARITO: CERTO. Doutrina clássica: o silêncio da administração é fato omissivo e depende de lei expressa para produzir efeitos positivos.",
    gabaritoCerto: true,
    conceito: "Natureza jurídica do silêncio administrativo",
    habilidade: "Compreender os efeitos materiais e processuais da omissão administrativa",
    tese: "Silêncio administrativo é fato omissivo e só gera deferimento se previsto em lei",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-adm-pod-020-reserva-administracao-merito-controle-judicial",
    assuntoId: ASSUNTOS.ADM_PODERES,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A respeito dos limites do controle jurisdicional sobre o mérito do ato administrativo discricionário, assinale a opção que reflete com exatidão a orientação predominante no Supremo Tribunal Federal e no Superior Tribunal de Justiça.",
    explicacao: "GABARITO: A. O Poder Judiciário não pode substituir os critérios de conveniência e oportunidade do administrador público, mas pode anular atos discricionários que violem os princípios da proporcionalidade, razoabilidade, legalidade e moralidade.",
    alternativas: [
      { letra: "A", texto: "O Judiciário não pode substituir a valoração de conveniência e oportunidade do administrador, mas pode anular atos discricionários que transgridam a razoabilidade, a proporcionalidade ou a legalidade.", correta: true, explicacao_especifica: "Correta. Jurisprudência pacífica do STF e STJ sobre controle de legalidade ampla e proporcionalidade." },
      { letra: "B", texto: "O mérito administrativo é imune a qualquer fiscalização judicial, mesmo quando verificada manifesta desproporção ou arbitrariedade flagrante.", correta: false, explicacao_especifica: "Incorreta. A desproporcionalidade manifesta enseja vício de legalidade passível de anulação judicial." },
      { letra: "C", texto: "O juiz pode alterar a sanção disciplinar imposta pela autoridade administrativa por mera divergência de política punitiva.", correta: false, explicacao_especifica: "Incorreta. O Judiciário não comuta nem altera sanções discricionárias legais; limita-se a anular quando ilegais." },
      { letra: "D", texto: "A discricionariedade confere ao gestor policial imunidade perante a ação de improbidade administrativa.", correta: false, explicacao_especifica: "Incorreta. Atos discricionários dolosos lesivos ao erário submetem-se plenamente à LIA." },
      { letra: "E", texto: "O mandado de segurança é a única via admitida para o exame do mérito administrativo pelo Poder Judiciário.", correta: false, explicacao_especifica: "Incorreta. Ações ordinárias e populares também exercem controle de validade dos atos." }
    ],
    conceito: "Controle judicial do mérito e limites da discricionariedade",
    habilidade: "Analisar o alcance do controle judicial de atos discricionários sob a ótica da proporcionalidade",
    tese: "O Judiciário controla a razoabilidade e legalidade do ato discricionário sem substituir seu mérito legítimo",
    nivel: "analisar"
  }
];

// ==============================================================
// M14: DIREITO ADMINISTRATIVO - AGENTES, LICITAÇÕES E RESPONSABILIDADE (20 questões)
// ==============================================================
const m14_data = [
  {
    tipo: "CE",
    slug: "l13-adm-resp-001-responsabilidade-civil-objetiva-art37-par6",
    assuntoId: ASSUNTOS.ADM_RESP_CIVIL,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "As pessoas jurídicas de direito público e as de direito privado prestadoras de serviços públicos responderão pelos danos que seus agentes, nessa qualidade, causarem a terceiros, assegurado o direito de regresso contra o responsável nos casos de dolo ou culpa, adotando o ordenamento a teoria do risco administrativo.",
    explicacao: "GABARITO: CERTO. Art. 37, § 6º da Constituição Federal de 1988: responsabilidade estatal objetiva e ação regressiva subjetiva.",
    gabaritoCerto: true,
    conceito: "Responsabilidade civil objetiva do Estado (Teoria do Risco Administrativo)",
    habilidade: "Identificar os requisitos da responsabilidade estatal e do direito de regresso",
    tese: "O Estado responde objetivamente por danos de seus agentes; a ação regressiva exige dolo ou culpa",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-resp-002-stf-tema-940-vedacao-acao-direta-agente-publico",
    assuntoId: ASSUNTOS.ADM_RESP_CIVIL,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "Segundo a tese vinculante fixada pelo STF no Tema 940 de repercussão geral (RE 1.027.633), a ação por danos causados por agente público deve ser ajuizada necessariamente contra o Estado ou a pessoa jurídica de direito privado prestadora do serviço público, sendo o servidor público parte ilegítima para figurar no polo passivo da ação indenizatória movida pelo terceiro prejudicado (princípio da dupla garantia).",
    explicacao: "GABARITO: CERTO. STF Tema 940: veda o ajuizamento da ação indenizatória direta do particular em face do agente público.",
    gabaritoCerto: true,
    conceito: "Tese da Dupla Garantia no Tema 940 do STF",
    habilidade: "Aplicar a tese de ilegitimidade passiva do servidor público perante a vítima direta",
    tese: "Ação indenizatória deve ser proposta contra o ente estatal, cabendo a este ação regressiva contra o agente",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-imp-003-lei-improbidade-14230-dolo-especifico-obrigatorio",
    assuntoId: ASSUNTOS.ADM_IMPROBIDADE_8429,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Com as alterações promovidas pela Lei nº 14.230/2021 na Lei de Improbidade Administrativa (Lei nº 8.429/1992), passou-se a exigir a comprovação de dolo específico para a caracterização de qualquer ato de improbidade administrativa, tendo sido expressamente revogada a modalidade culposa anteriormente prevista para os atos que causam prejuízo ao erário.",
    explicacao: "GABARITO: CERTO. Art. 1º, §§ 1º, 2º e 3º da Lei nº 8.429/92 (redação da Lei 14.230/21): extinção da improbidade culposa e exigência de dolo específico.",
    gabaritoCerto: true,
    conceito: "Exigência de dolo específico na Lei de Improbidade Administrativa (Lei 14.230/21)",
    habilidade: "Reconhecer a extinção da improbidade administrativa culposa após a reforma de 2021",
    tese: "Atos de improbidade exigem dolo específico com vontade livre e consciente de alcançar fim ilícito",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-imp-004-stf-tema-1199-retroatividade-lei-improbidade",
    assuntoId: ASSUNTOS.ADM_IMPROBIDADE_8429,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "No julgamento do Tema 1.199 de repercussão geral (ARE 843.989), o STF decidiu que a revogação da modalidade culposa de improbidade administrativa pela Lei nº 14.230/2021 é irretroativa em relação às condenações transitadas em julgado, aplicando-se, contudo, aos atos de improbidade culposos praticados antes da lei nova desde que ainda não haja trânsito em julgado.",
    explicacao: "GABARITO: CERTO. Tese do Tema 1.199 do STF: a lei nova retroage para processos em curso sem trânsito em julgado, resguardando a coisa julgada material.",
    gabaritoCerto: true,
    conceito: "Retroatividade da Lei 14.230/21 fixada no STF Tema 1199",
    habilidade: "Aplicar os critérios de modulação temporal da Lei de Improbidade Administrativa",
    tese: "A revogação da improbidade culposa retroage para processos sem trânsito em julgado",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-adm-lic-005-lei-14133-modalidades-licitacao-dialogo-competitivo",
    assuntoId: ASSUNTOS.ADM_LICITACOES_14133,
    banca: "FGV", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "A Lei nº 14.133/2021 (Nova Lei de Licitações e Contratos Administrativos) reestruturou o rol das modalidades licitatórias aplicáveis à Administração Pública direta e indireta. Assinale a opção que apresenta com exatidão as modalidades expressamente previstas no art. 28 da referida lei.",
    explicacao: "GABARITO: C. Art. 28 da Lei nº 14.133/2021: pregão, concorrência, concurso, leilão e diálogo competitivo (foram extintos a tomada de preços e o convite).",
    alternativas: [
      { letra: "A", texto: "Pregão, concorrência, tomada de preços, convite e leilão.", correta: false, explicacao_especifica: "Incorreta. Tomada de preços e convite foram extintos pela nova lei." },
      { letra: "B", texto: "Concorrência, tomada de preços, leilão, concurso e pregão.", correta: false, explicacao_especifica: "Incorreta. Tomada de preços não existe na Lei 14.133/21." },
      { letra: "C", texto: "Pregão, concorrência, concurso, leilão e diálogo competitivo.", correta: true, explicacao_especifica: "Correta. Rol taxativo do art. 28 da Lei nº 14.133/2021." },
      { letra: "D", texto: "Diálogo competitivo, tomada de preços, concurso, leilão e consulta pública.", correta: false, explicacao_especifica: "Incorreta. Consulta pública não é modalidade de licitação." },
      { letra: "E", texto: "Concorrência restrita, convite eletrônico, pregão presencial e leilão.", correta: false, explicacao_especifica: "Incorreta. Nomenclaturas não previstas no art. 28." }
    ],
    conceito: "Modalidades de licitação da Nova Lei de Licitações (Lei nº 14.133/2021)",
    habilidade: "Identificar o rol moderno de modalidades licitatórias da Lei 14.133/2021",
    tese: "A Lei 14.133/21 prevê pregão, concorrência, concurso, leilão e diálogo competitivo",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-lic-006-lei-14133-inexigibilidade-vs-dispensa",
    assuntoId: ASSUNTOS.ADM_LICITACOES_14133,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "Na Nova Lei de Licitações (Lei nº 14.133/2021), a inexigibilidade de licitação decorre da inviabilidade fática ou jurídica de competição (art. 74), enquanto a dispensa de licitação abrange hipóteses em que a competição seria teoricamente viável, mas a lei autoriza ou determina a contratação direta por conveniência, segurança ou valor reduzido (art. 75).",
    explicacao: "GABARITO: CERTO. Distinção essencial entre inexigibilidade (inviabilidade de competição) e dispensa (competição viável, mas contratação direta autorizada).",
    gabaritoCerto: true,
    conceito: "Distinção entre dispensa e inexigibilidade na Lei 14.133/2021",
    habilidade: "Classificar as hipóteses de contratação direta na Nova Lei de Licitações",
    tese: "Inexigibilidade pressupõe inviabilidade de disputa; dispensa pressupõe disputa viável com exceção legal",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-age-007-lei-8112-estabilidade-estagio-probatorio",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "medio",
    enunciado: "O servidor público federal investido em cargo de provimento efetivo adquire a estabilidade após três anos de efetivo exercício, ficando condicionado à aprovação em avaliação especial de desempenho por comissão instituída para essa finalidade, conforme estabelecido pelo art. 41 da Constituição Federal e Súmula 21 do STF.",
    explicacao: "GABARITO: CERTO. Art. 41 da CF/88 (redação da EC 19/98) e Súmula 21 do STF: prazo de 3 anos e necessidade de avaliação especial.",
    gabaritoCerto: true,
    conceito: "Estabilidade no serviço público e estágio probatório",
    habilidade: "Reconhecer o prazo e os requisitos constitucionais para a aquisição da estabilidade",
    tese: "A estabilidade no cargo efetivo exige 3 anos de exercício e aprovação em avaliação especial",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-age-008-lei-8112-demissao-pad-ampla-defesa",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "medio",
    enunciado: "A demissão de servidor estável ou em estágio probatório fundada na prática de infração disciplinar grave exige a prévia instauração de processo administrativo disciplinar (PAD), assegurados o contraditório e a ampla defesa, sendo nula a penalidade expulsória aplicada sumariamente por ato discricionário da chefia.",
    explicacao: "GABARITO: CERTO. Art. 41, § 1º da CF/88, Súmula 20 do STF e Lei nº 8.112/90.",
    gabaritoCerto: true,
    conceito: "Garantia de PAD para aplicação de penalidade de demissão",
    habilidade: "Identificar as garantias do devido processo legal no regime disciplinar dos servidores",
    tese: "A demissão funcional exige formalização de PAD com contraditório e ampla defesa",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-age-009-reintegracao-reconducao-reversao-readaptacao",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "A reintegração é a reinvestidura do servidor estável no cargo anteriormente ocupado quando invalidada a sua demissão por decisão judicial ou administrativa, com ressarcimento de todas as vantagens, acarretando a recondução do eventual ocupante da vaga ao cargo de origem, sem direito a indenização.",
    explicacao: "GABARITO: CERTO. Art. 28 da Lei nº 8.112/90 e art. 41, § 2º da Constituição Federal.",
    gabaritoCerto: true,
    conceito: "Formas de provimento e vacância: reintegração e recondução",
    habilidade: "Diferenciar reintegração, recondução, reversão e readaptação na Lei 8.112/90",
    tese: "A reintegração repara a demissão ilegal com ressarcimento integral e reconduz o substituto",
    nivel: "analisar"
  },
  {
    tipo: "ME",
    slug: "l13-adm-imp-010-sancoes-lei-improbidade-perda-bens-funcao",
    assuntoId: ASSUNTOS.ADM_IMPROBIDADE_8429,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 8.429/1992, com as alterações da Lei nº 14.230/2021, a sanção de perda da função pública cominada em ação de improbidade administrativa:",
    explicacao: "GABARITO: D. Art. 12, § 1º da Lei nº 8.429/92 (redação da Lei 14.230/21): a perda da função pública atinge apenas o vínculo de mesma qualidade e natureza que o agente público detinha na época do ato ímprobo, salvo hipótese de enriquecimento ilícito grave com extensão justificada.",
    alternativas: [
      { letra: "A", texto: "Atinge automaticamente todo e qualquer cargo público ocupado no momento da sentença, ainda que de outro poder ou esfera federativa sem nexo com o ato.", correta: false, explicacao_especifica: "Incorreta. A regra nova restringe a perda ao vínculo de mesma natureza." },
      { letra: "B", texto: "Aplica-se independentemente de trânsito em julgado imediatamente após a prolação da sentença condenatória de primeiro grau.", correta: false, explicacao_especifica: "Incorreta. O art. 20 exige expressamente o trânsito em julgado para a perda da função pública." },
      { letra: "C", texto: "Impede vitaliciamente o cidadão de prestar novos concursos públicos em qualquer esfera.", correta: false, explicacao_especifica: "Incorreta. A lei prevê suspensão de direitos políticos e proibição de contratar por prazos determinados." },
      { letra: "D", texto: "Atinge apenas o vínculo de mesma qualidade e natureza que o agente detinha com o poder público na época do cometimento da infração, dependendo de trânsito em julgado.", correta: true, explicacao_especifica: "Correta. Art. 12, § 1º e art. 20 da Lei nº 8.429/92." },
      { letra: "E", texto: "Pode ser decretada de ofício pelo Ministério Público sem necessidade de intervenção do Poder Judiciário.", correta: false, explicacao_especifica: "Incorreta. As sanções da LIA são privativas da jurisdição civil." }
    ],
    conceito: "Sanção de perda da função pública na Lei 14.230/21",
    habilidade: "Compreender os limites da sanção de perda da função pública após a reforma da LIA",
    tese: "A perda da função pública atinge o cargo da época e pressupõe trânsito em julgado",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-resp-011-omissao-estatal-responsabilidade-subjetiva-faute-du-service",
    assuntoId: ASSUNTOS.ADM_RESP_CIVIL,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "Em se tratando de danos causados por omissão genérica do Poder Público, a jurisprudência dominante do STF e do STJ orienta que a responsabilidade civil do Estado é, em regra, subjetiva, exigindo a demonstração da culpa administrativa (falta do serviço — faute du service), caracterizada quando o serviço não funcionou, funcionou mal ou funcionou tardiamente.",
    explicacao: "GABARITO: CERTO. Doutrina e jurisprudência consolidada sobre a responsabilidade subjetiva por omissão genérica estatal.",
    gabaritoCerto: true,
    conceito: "Responsabilidade civil do Estado por conduta omissiva genérica",
    habilidade: "Distinguir responsabilidade objetiva por ação e subjetiva por omissão genérica",
    tese: "A omissão genérica do Estado enseja responsabilidade civil subjetiva fundada na falta do serviço",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-resp-012-morte-custodia-responsabilidade-objetiva-stf-tema592",
    assuntoId: ASSUNTOS.ADM_RESP_CIVIL,
    banca: "Cebraspe", orgao: "Polícia Penal", cargo: "Policial Penal",
    dificuldade: "dificil",
    enunciado: "Segundo a tese vinculante fixada pelo STF no Tema 592 de repercussão geral, em caso de morte de pessoa presa sob custódia estatal, a responsabilidade civil do Estado é objetiva em virtude do dever constitucional de vigilância e proteção da integridade física do custodiado (art. 5º, XLIX da CF), cabendo ao Estado comprovar que a morte decorreu de causa natural ou que adotou todas as medidas necessárias para evitar o suicídio/homicídio.",
    explicacao: "GABARITO: CERTO. STF Tema 592 (RE 841.526): responsabilidade objetiva do Estado pela integridade física do preso sob sua custódia.",
    gabaritoCerto: true,
    conceito: "Responsabilidade civil objetiva por morte de preso em custódia (STF Tema 592)",
    habilidade: "Aplicar a tese de responsabilidade estatal pela integridade física dos presos",
    tese: "O Estado responde objetivamente por danos e mortes ocorridas no sistema prisional sob sua custódia",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-lic-013-lei-14133-criterios-julgamento-menor-preco",
    assuntoId: ASSUNTOS.ADM_LICITACOES_14133,
    banca: "Cebraspe", orgao: "Polícia Militar", cargo: "Soldado da Polícia Militar",
    dificuldade: "facil",
    enunciado: "Na Lei nº 14.133/2021, são critérios de julgamento das propostas licitatórias o menor preço, o maior desconto, a melhor técnica ou conteúdo artístico, a técnica e preço, o maior lance (no caso de leilão) e o maior retorno econômico.",
    explicacao: "GABARITO: CERTO. Art. 33 da Lei nº 14.133/2021.",
    gabaritoCerto: true,
    conceito: "Critérios de julgamento na Lei 14.133/2021",
    habilidade: "Identificar os tipos e critérios de julgamento da Nova Lei de Licitações",
    tese: "A Lei 14.133/21 estabelece seis critérios formais de julgamento das propostas",
    nivel: "recordar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-age-014-acumulacao-cargos-policiais-regra-geral",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "É vedada a acumulação remunerada de cargos públicos, ressalvadas as hipóteses constitucionais expressas de dois cargos de professor, um de professor com outro técnico ou científico, e dois cargos privativos de profissionais de saúde, desde que haja compatibilidade de horários, sendo vedada a acumulação de cargo policial com outro cargo público efetivo.",
    explicacao: "GABARITO: CERTO. Art. 37, XVI da CF/88: o cargo policial é cargo de dedicação exclusiva que não se enquadra nas ressalvas de magistério ou saúde.",
    gabaritoCerto: true,
    conceito: "Regime constitucional de vedação à acumulação de cargos públicos",
    habilidade: "Analisar as hipóteses restritivas de acumulação remunerada de cargos",
    tese: "Cargos policiais não admitem acumulação remunerada ordinária com outros cargos efetivos",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-adm-lic-015-contratacao-direta-seguranca-nacional-dispensa",
    assuntoId: ASSUNTOS.ADM_LICITACOES_14133,
    banca: "Vunesp", orgao: "Polícia Militar", cargo: "Oficial da Polícia Militar",
    dificuldade: "medio",
    enunciado: "Em matéria de contratações públicas para órgãos de segurança pública e defesa, a Lei nº 14.133/2021 prevê hipóteses específicas de dispensa de licitação. Assinale a afirmativa que apresenta hipótese legal de dispensa autorizada pelo art. 75 da referida lei.",
    explicacao: "GABARITO: B. Art. 75, IV, 'b' e 'f' da Lei nº 14.133/2021: contratação de materiais bélicos de uso exclusivo das Forças Armadas e forças de segurança ou quando houver comprometimento da segurança nacional.",
    alternativas: [
      { letra: "A", texto: "Para aquisição de bens de luxo destinados exclusivamente ao gabinete do Comandante-Geral da corporação.", correta: false, explicacao_especifica: "Incorreta. Bens de luxo são expressamente vedados na administração pelo art. 20 da lei." },
      { letra: "B", texto: "Nos casos de emergência ou de calamidade pública, para aquisição dos bens necessários ao atendimento da situação emergencial pelo prazo máximo de um ano.", correta: true, explicacao_especifica: "Correta. Art. 75, VIII da Lei nº 14.133/2021." },
      { letra: "C", texto: "Sempre que a autoridade policial preferir fornecedor sediado no mesmo município da delegacia de polícia.", correta: false, explicacao_especifica: "Incorreta. Viola o princípio da isonomia e competitividade." },
      { letra: "D", texto: "Em qualquer compra de viaturas blindadas, independentemente do valor ou de justificação de preço de mercado.", correta: false, explicacao_especifica: "Incorreta. Exige procedimento de dispensa formal com justificativa de preço e razão da escolha." },
      { letra: "E", texto: "Para terceirização integral das atividades-fim de investigação criminal da Polícia Judiciária.", correta: false, explicacao_especifica: "Incorreta. Atividade-fim de polícia de estado é indelegável a particulares." }
    ],
    conceito: "Dispensa de licitação em situações de emergência e segurança pública",
    habilidade: "Identificar as hipóteses de dispensa de licitação no art. 75 da Lei 14.133/2021",
    tese: "Contratação emergencial por dispensa é limitada aos bens estritamente necessários ao socorro da situação",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-age-016-prescricao-disciplinar-art142-lei8112",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Federal", cargo: "Agente de Polícia Federal",
    dificuldade: "dificil",
    enunciado: "Nos termos da Lei nº 8.112/1990, a ação disciplinar prescreverá em 5 anos quanto às infrações puníveis com demissão, cassação de aposentadoria ou disponibilidade e destituição de cargo em comissão; o prazo de prescrição começa a correr da data em que o fato se tornou conhecido da autoridade competente para instaurar o procedimento, interrompendo-se com a publicação da portaria de instauração do PAD.",
    explicacao: "GABARITO: CERTO. Art. 142, I, § 1º e § 3º da Lei Federal nº 8.112/90.",
    gabaritoCerto: true,
    conceito: "Prescrição da pretensão punitiva disciplinar na Lei 8.112/90",
    habilidade: "Calcular o termo inicial e as causas interruptivas da prescrição disciplinar",
    tese: "Prescrição disciplinar para demissão corre em 5 anos a contar do conhecimento pela autoridade",
    nivel: "analisar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-imp-017-prescricao-intercorrente-lei-14230",
    assuntoId: ASSUNTOS.ADM_IMPROBIDADE_8429,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Investigador de Polícia",
    dificuldade: "dificil",
    enunciado: "A Lei nº 14.230/2021 introduziu na Lei de Improbidade Administrativa a prescrição intercorrente, fixando que, ajuizada a ação civil de improbidade, o prazo prescricional de quatro anos para a prolação de sentença ou acórdão condenatório interrompe-se pelos marcos legais, extinguindo-se o processo caso ultrapassado o prazo sem julgamento.",
    explicacao: "GABARITO: CERTO. Art. 23, §§ 4º, 5º e 8º da Lei nº 8.429/92 (redação da Lei 14.230/21).",
    gabaritoCerto: true,
    conceito: "Prescrição intercorrente na Lei de Improbidade Administrativa",
    habilidade: "Compreender os prazos e efeitos da prescrição intercorrente na LIA",
    tese: "A Lei 14.230/21 fixou prazo de prescrição intercorrente de 4 anos entre os marcos processuais",
    nivel: "compreender"
  },
  {
    tipo: "CE",
    slug: "l13-adm-resp-018-excludentes-responsabilidade-culpa-exclusiva",
    assuntoId: ASSUNTOS.ADM_RESP_CIVIL,
    banca: "Cebraspe", orgao: "Polícia Rodoviária Federal", cargo: "Policial Rodoviário Federal",
    dificuldade: "medio",
    enunciado: "Na responsabilidade civil objetiva do Estado fundada na teoria do risco administrativo, a comprovação inequívoca de culpa exclusiva da vítima ou de caso fortuito/força maior absoluta rompe o nexo de causalidade entre a conduta estatal e o dano sofrido, excluindo o dever de indenizar do ente público.",
    explicacao: "GABARITO: CERTO. Doutrina clássica de responsabilidade civil extracontratual do Estado: a teoria do risco administrativo admite excludentes de nexo causal.",
    gabaritoCerto: true,
    conceito: "Causas excludentes da responsabilidade civil objetiva do Estado",
    habilidade: "Identificar as excludentes de nexo de causalidade na teoria do risco administrativo",
    tese: "Culpa exclusiva da vítima e força maior excluem a responsabilidade estatal por ruptura do nexo",
    nivel: "aplicar"
  },
  {
    tipo: "CE",
    slug: "l13-adm-lic-019-portal-nacional-contratacoes-publicas-pncp",
    assuntoId: ASSUNTOS.ADM_LICITACOES_14133,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Escrivão de Polícia Civil",
    dificuldade: "medio",
    enunciado: "A Lei nº 14.133/2021 criou o Portal Nacional de Contratações Públicas (PNCP), sítio eletrônico oficial centralizado destinado à divulgação obrigatória dos editais de licitação, atas de registro de preços, contratos e termos aditivos celebrados por todos os entes federativos da Administração direta, autárquica e fundacional.",
    explicacao: "GABARITO: CERTO. Art. 174 da Lei nº 14.133/2021: o PNCP é instrumento central de transparência e publicidade obrigatória das licitações.",
    gabaritoCerto: true,
    conceito: "Portal Nacional de Contratações Públicas (PNCP) e publicidade",
    habilidade: "Reconhecer o papel e a obrigatoriedade de publicação no PNCP na Nova Lei de Licitações",
    tese: "A publicação de atos licitatórios e contratos no PNCP é condição de eficácia na Lei 14.133/21",
    nivel: "compreender"
  },
  {
    tipo: "ME",
    slug: "l13-adm-age-020-processo-disciplinar-sumula-vinculante-5-advogado",
    assuntoId: ASSUNTOS.ADM_AGENTES_8112,
    banca: "Cebraspe", orgao: "Polícia Civil", cargo: "Delegado de Polícia Civil",
    dificuldade: "dificil",
    enunciado: "A respeito da defesa técnica no âmbito do Processo Administrativo Disciplinar (PAD), o Supremo Tribunal Federal editou a Súmula Vinculante nº 5. De acordo com o referido enunciado vinculante:",
    explicacao: "GABARITO: A. Súmula Vinculante 5 do STF: a falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição.",
    alternativas: [
      { letra: "A", texto: "A falta de defesa técnica por advogado no processo administrativo disciplinar não ofende a Constituição.", correta: true, explicacao_especifica: "Correta. Texto literal da Súmula Vinculante nº 5 do STF." },
      { letra: "B", texto: "É obrigatória a presença de advogado constituído em todos os atos do PAD sob pena de nulidade absoluta e automática.", correta: false, explicacao_especifica: "Incorreta. A SV 5 pacificou que a presença de advogado é facultativa." },
      { letra: "C", texto: "A Defensoria Pública deve obrigatoriamente patrocinar todo servidor público processado disciplinarmente que receba até cinco salários mínimos.", correta: false, explicacao_especifica: "Incorreta. Não há essa exigência na súmula vinculante." },
      { letra: "D", texto: "A comissão processante não é obrigada a intimar o servidor para prestar depoimento pessoal.", correta: false, explicacao_especifica: "Incorreta. O interrogatório/depoimento e a oportunidade de defesa pessoal são garantias inafastáveis." },
      { letra: "E", texto: "O servidor fica impedido de nomear procurador leigo para apresentar sua defesa escrita.", correta: false, explicacao_especifica: "Incorreta. O servidor pode defender-se pessoalmente ou constituir procurador." }
    ],
    conceito: "Súmula Vinculante nº 5 e defesa técnica no processo disciplinar",
    habilidade: "Aplicar a Súmula Vinculante 5 do STF à condução de procedimentos disciplinares policiais",
    tese: "A ausência de advogado no processo administrativo disciplinar não invalida o procedimento",
    nivel: "analisar"
  }
];

function converterItem(item, disciplinaId) {
  if (item.tipo === "CE") {
    return criarQuestaoCE({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      gabaritoCerto: item.gabaritoCerto,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  } else {
    return criarQuestaoME({
      slug: item.slug,
      disciplinaId,
      assuntoId: item.assuntoId,
      bancaNome: item.banca,
      orgaoNome: item.orgao,
      cargoNome: item.cargo,
      ano: 2026,
      dificuldade: item.dificuldade,
      enunciado: item.enunciado,
      explicacao: item.explicacao,
      alternativas: item.alternativas,
      conceitoPrincipal: item.conceito,
      habilidadeCobrada: item.habilidade,
      teseOuRegra: item.tese,
      nivelCognitivo: item.nivel,
    });
  }
}

// 1. Gerar M13
const m13_questoes = m13_data.map(item => converterItem(item, DISCIPLINAS.DIREITO_ADMINISTRATIVO));
writeModuleFile("m13_adm_principios_poderes.mjs", "m13_questoes", m13_questoes);

// 2. Gerar M14
const m14_questoes = m14_data.map(item => converterItem(item, DISCIPLINAS.DIREITO_ADMINISTRATIVO));
writeModuleFile("m14_adm_agentes_licitacoes.mjs", "m14_questoes", m14_questoes);

console.log("[OK] Grupo E (M13: 20 questões, M14: 20 questões) concluído com sucesso!");
