// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 20

export const m12_questoes = [
  {
    "id": "122dd9ee-a39e-5b74-9d44-f04021ceed3e",
    "idSlug": "l13-const-org-001-reparticao-competencias-seguranca-legislativa",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "66dd36a8-5e55-5f5c-8ae8-36501eab3e3b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Compete privativamente à União legislar sobre direito penal, processual penal e material bélico, sendo inconstitucional lei estadual ou municipal que pretenda criar novos tipos penais ou disciplinar de forma divergente a posse e o porte de armas de fogo.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 22, I e XXI da CF/88 e Súmula Vinculante 38 do STF: competência privativa da União para direito penal e armas/munições.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f911a91eedaf648e67d284453696f9fff159919dfa8f06a39059a2f1d766538a",
    "conceito_principal": "Competência privativa da União em Direito Penal e Armas",
    "habilidade_cobrada": "Identificar vícios formais de inconstitucionalidade em leis estaduais de armas",
    "tese_ou_regra": "Compete privativamente à União legislar sobre direito penal e material bélico",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "54020e46-4452-5a35-ba16-cba91ae8b40c",
        "questao_id": "122dd9ee-a39e-5b74-9d44-f04021ceed3e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a54ce0c5-fc00-5207-a4a7-ee6afae5f6f6",
        "questao_id": "122dd9ee-a39e-5b74-9d44-f04021ceed3e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "30ff9293-1d7d-55ac-985b-f04dfd1349a8",
    "idSlug": "l13-const-org-002-competencia-concorrente-procedimentos-materia-processual",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "66dd36a8-5e55-5f5c-8ae8-36501eab3e3b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Compete à União, aos Estados e ao Distrito Federal legislar concorrentemente sobre procedimentos em matéria processual e penitenciário, limitando-se a União ao estabelecimento de normas gerais, sem excluir a competência suplementar dos Estados.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 24, I, XI e § 1º da CF/88: legislação concorrente sobre direito penitenciário e procedimentos em matéria processual.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "59e342c1e891739ae997a97f7e661450b3b662c5ab86f4c1908b8b4782f78237",
    "conceito_principal": "Competência legislativa concorrente (Art. 24 da CF/88)",
    "habilidade_cobrada": "Distinguir competência privativa processual de competência concorrente procedimental",
    "tese_ou_regra": "União fixa normas gerais e Estados suplementam em matéria de procedimento e direito penitenciário",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "48189c47-7d7f-5dae-a46c-4a8f4b93eedf",
        "questao_id": "30ff9293-1d7d-55ac-985b-f04dfd1349a8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6b089fb4-2310-5b52-b449-c8de5de3fb5d",
        "questao_id": "30ff9293-1d7d-55ac-985b-f04dfd1349a8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "96953f9d-dd6b-5202-a790-ee35022b0dab",
    "idSlug": "l13-const-pod-003-competencia-stf-habeas-corpus-ministros",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Compete originariamente ao Supremo Tribunal Federal processar e julgar o habeas corpus quando o coator for Ministro de Estado, Comandante da Marinha, do Exército ou da Aeronáutica, ou quando o coator ou paciente for pessoa sujeita à jurisdição direta da Suprema Corte.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 102, I, 'd' e 'i' da Constituição Federal de 1988.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "146f0da316ff3144ac6dcba0c3b3aec0ab8251a7bea4cdcb1d40685132efbf9f",
    "conceito_principal": "Competência originária do STF em Habeas Corpus",
    "habilidade_cobrada": "Identificar as autoridades coatoras submetidas à competência originária do STF",
    "tese_ou_regra": "STF julga HC contra atos de Ministros de Estado e autoridades com prerrogativa na Corte",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b6369fb1-def1-55c8-a927-2ab800529c16",
        "questao_id": "96953f9d-dd6b-5202-a790-ee35022b0dab",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9dea4552-f6f8-525e-acc0-e1dad3e2cdcc",
        "questao_id": "96953f9d-dd6b-5202-a790-ee35022b0dab",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "c5239816-e5f8-5197-bf37-2fbd292bbdb9",
    "idSlug": "l13-const-pod-004-competencia-stj-governadores-crime-comum",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em apuração de condutas ilícitas praticadas por altas autoridades públicas estaduais, a delimitação do foro jurisdicional privativo segue a matriz da Carta Magna. Nesse cenário, compete originariamente ao Superior Tribunal de Justiça processar e julgar os Governadores dos Estados e do DF na prática de crimes comuns, cabendo ao mesmo STJ julgar os desembargadores dos Tribunais de Justiça tanto nos crimes comuns quanto nos de responsabilidade.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 105, I, 'a' da Constituição Federal de 1988: compete ao STJ processar e julgar, originariamente, nos crimes comuns, os Governadores dos Estados e do DF, e, nestes e nos de responsabilidade, os desembargadores dos TJs estaduais e do TJDFT.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8958b48ab91b024dfa81efdb5bae5e0afa49edd9b1debc8526d4253a4871e25b",
    "conceito_principal": "Competência originária do STJ para Governadores e Desembargadores",
    "habilidade_cobrada": "Reconhecer as regras de foro por prerrogativa de função no STJ",
    "tese_ou_regra": "Governadores respondem por crimes comuns perante o STJ",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "143c5d4a-827a-5f1d-a0a5-3e3043259061",
        "questao_id": "c5239816-e5f8-5197-bf37-2fbd292bbdb9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ee8b3888-dc62-53bf-a75a-d7d74619220a",
        "questao_id": "c5239816-e5f8-5197-bf37-2fbd292bbdb9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b50d636e-151d-5778-ad99-90bbedc48f85",
    "idSlug": "l13-const-pod-005-foro-prerrogativa-funcao-stf-marco-temporal",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A respeito da prerrogativa de foro por função perante os tribunais superiores segundo a jurisprudência atualizada do Supremo Tribunal Federal (Questão de Ordem na AP 937 e julgamentos supervenientes), assinale a afirmativa correta.",
    "explicacao": "GABARITO: B. A prerrogativa aplica-se aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas, e, uma vez encerrada a instrução com intimação para alegações finais, o foro se prorroga definitivamente.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c3d76f85cb0166ed00d84f3968f5a9541d4706c1fd4384f008faa2af06a67739",
    "conceito_principal": "Foro por prerrogativa de função e critérios de contemporaneidade e pertinência temática",
    "habilidade_cobrada": "Aplicar a tese do STF sobre foro por prerrogativa de função aos crimes de titulares de mandato",
    "tese_ou_regra": "O foro privilegiado exige contemporaneidade e nexo causal com a função pública",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "8b739476-5432-5063-98e6-2da4d3ac5f80",
        "questao_id": "b50d636e-151d-5778-ad99-90bbedc48f85",
        "letra": "A",
        "texto": "Aplica-se a qualquer crime comum cometido pelo parlamentar, independentemente da época do fato ou de relação com o mandato.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Exige-se prática no cargo e em razão dele."
      },
      {
        "id": "16e55c77-c003-576d-bc9d-492f7acda582",
        "questao_id": "b50d636e-151d-5778-ad99-90bbedc48f85",
        "letra": "B",
        "texto": "O foro por prerrogativa de função aplica-se apenas aos crimes cometidos durante o exercício do cargo e relacionados às funções desempenhadas.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Tese da QO na AP 937 fixada pelo STF."
      },
      {
        "id": "f14a57cc-bf24-52eb-89bc-db19e7b3cc32",
        "questao_id": "b50d636e-151d-5778-ad99-90bbedc48f85",
        "letra": "C",
        "texto": "A renúncia ao mandato parlamentar em qualquer fase processual sempre transfere os autos ao juízo de primeiro grau.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Após o encerramento da instrução (intimação para alegações finais), a competência é prorrogada e perpetuada no STF."
      },
      {
        "id": "244077ae-6329-5fdb-aa02-59f69cae8eca",
        "questao_id": "b50d636e-151d-5778-ad99-90bbedc48f85",
        "letra": "D",
        "texto": "A prerrogativa de foro abrange automaticamente os corréus que não possuem qualquer cargo público relevante.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A regra é o desmembramento do processo quanto aos não detentores de foro."
      },
      {
        "id": "7f725866-c6c7-52a1-94e6-830f1c1ee48e",
        "questao_id": "b50d636e-151d-5778-ad99-90bbedc48f85",
        "letra": "E",
        "texto": "O STF não admite cisão processual em inquéritos policiais de organizações criminosas complexas.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O desmembramento é a diretriz padrão da Corte."
      }
    ]
  },
  {
    "id": "4c1e9e17-5022-5c60-979f-eddfffaf937a",
    "idSlug": "l13-const-con-006-controle-concentrado-adi-adc-legitimados",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "f5742ead-d502-5d7b-953f-2117f3fba269",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O Procurador-Geral da República, o Presidente da República, a Mesa do Senado Federal e a Mesa da Câmara dos Deputados são legitimados universais para a propositura de Ação Direta de Inconstitucionalidade (ADI) e Ação Declaratória de Constitucionalidade (ADC), não necessitando demonstrar pertinência temática.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 103 da CF/88: os legitimados neutros/universais dispensam comprovação de interesse temático específico.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1321c896c7b556f81f43396344963d64d1ffb42df3121c0ff71ad681c4fb63c5",
    "conceito_principal": "Legitimidade ativa universal no controle concentrado de constitucionalidade",
    "habilidade_cobrada": "Classificar os legitimados do art. 103 da CF entre universais e especiais",
    "tese_ou_regra": "Legitimados universais no art. 103 dispensam demonstração de pertinência temática",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "48af8477-0f43-505a-8403-05266883fc3d",
        "questao_id": "4c1e9e17-5022-5c60-979f-eddfffaf937a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "eb037fbf-1bc0-5330-8bc2-e49985af28de",
        "questao_id": "4c1e9e17-5022-5c60-979f-eddfffaf937a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0a6ab701-3168-5f72-95f8-c2e0ee505bd8",
    "idSlug": "l13-const-con-007-adpf-principio-subsidiariedade",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "f5742ead-d502-5d7b-953f-2117f3fba269",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A Arguição de Descumprimento de Preceito Fundamental (ADPF) é cabível para evitar ou reparar lesão a preceito fundamental resultante de ato do Poder Público, inclusive direito pré-constitucional e normas municipais, regendo-se pelo princípio da subsidiariedade, segundo o qual não será admitida quando houver qualquer outro meio de controle concentrado de eficácia equivalente.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Lei nº 9.882/99, art. 4º, § 1º: a subsidiariedade afasta a ADPF se houver outro instrumento direto no controle abstrato com mesma amplitude.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "78a86669fc19d4336e941f1833e76765bb37c9a260d0b5aa472523c857a3470e",
    "conceito_principal": "ADPF, direito pré-constitucional e princípio da subsidiariedade",
    "habilidade_cobrada": "Analisar o cabimento residual e protetivo da ADPF",
    "tese_ou_regra": "A ADPF tutela preceitos fundamentais contra atos municipais e leis pré-constitucionais",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "fd9d7b9a-4e72-57c3-8ce7-467c720dd0bc",
        "questao_id": "0a6ab701-3168-5f72-95f8-c2e0ee505bd8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5501e5a9-6e98-5f85-a026-d0ea8659efbb",
        "questao_id": "0a6ab701-3168-5f72-95f8-c2e0ee505bd8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "35e33776-f0ae-57e8-bdd2-d62e9da62c7c",
    "idSlug": "l13-const-con-008-clausula-reserva-plenario-sumula-vinculante-10",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "f5742ead-d502-5d7b-953f-2117f3fba269",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Viola a cláusula de reserva de plenário (art. 97 da CF) a decisão de órgão fracionário de Tribunal que, embora não declare expressamente a inconstitucionalidade de lei ou ato normativo do poder público, afasta sua incidência, no todo ou em parte.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Texto literal da Súmula Vinculante nº 10 do Supremo Tribunal Federal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d48ec31611222d37d79b964cdb69dc9159415742e0f7a0fd3b7cc4d52342d6d9",
    "conceito_principal": "Cláusula de reserva de plenário (Súmula Vinculante 10)",
    "habilidade_cobrada": "Identificar violação à reserva de plenário por órgãos fracionários de tribunais",
    "tese_ou_regra": "Órgão fracionário de tribunal não pode afastar lei com base constitucional sem remessa ao pleno",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "b8fbe4a7-c941-53ff-835b-cab0ffcf91bf",
        "questao_id": "35e33776-f0ae-57e8-bdd2-d62e9da62c7c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "bc9b8232-ddde-5d73-b5e2-8b184e2a85d9",
        "questao_id": "35e33776-f0ae-57e8-bdd2-d62e9da62c7c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0df803cb-924d-5b94-9c8d-29fb7e892722",
    "idSlug": "l13-const-pod-009-cpi-poderes-investigacao-reserva-jurisdicao",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "7a887c87-f2d3-504f-8ccf-3f7fe67c1812",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "As comissões parlamentares de inquérito possuem poderes de investigação próprios das autoridades judiciais, podendo determinar a quebra de sigilo bancário, fiscal e telefônico dos investigados por decisão fundamentada; todavia, estão submetidas à cláusula de reserva de jurisdição, sendo-lhes vedado decretar interceptação telefônica, busca e apreensão domiciliar e prisão preventiva.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 58, § 3º da CF/88 e jurisprudência pacífica do STF: CPI quebra sigilo de dados telefônicos/bancários, mas não pode interceptar conversa telefônica nem violar domicílio.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e75b98e5e99e50e0ca39c4cacd59226774e8802be6d8a5e40bf21a267cc90c93",
    "conceito_principal": "Poderes instrutórios das CPIs e limites da reserva de jurisdição",
    "habilidade_cobrada": "Diferenciar medidas investigativas admitidas e vedadas a Comissões Parlamentares de Inquérito",
    "tese_ou_regra": "CPIs podem quebrar sigilo de dados, mas interceptação telefônica e busca domiciliar exigem ordem judicial",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "0e3b1ba2-1454-561c-ab0f-c94106dd3d69",
        "questao_id": "0df803cb-924d-5b94-9c8d-29fb7e892722",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3615c44d-9fb0-5d8b-84d0-3f3f1b3e1a69",
        "questao_id": "0df803cb-924d-5b94-9c8d-29fb7e892722",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
    "idSlug": "l13-const-pod-010-presidente-crime-responsabilidade-camara",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "65d20117-d7d7-5139-9eeb-cb59ee770070",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Nos termos da Constituição Federal de 1988, admitida a acusação contra o Presidente da República por dois terços da Câmara dos Deputados:",
    "explicacao": "GABARITO: C. Art. 86 da CF/88: o Presidente será submetido a julgamento perante o STF (crimes comuns) ou perante o Senado Federal (crimes de responsabilidade).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a3c3a68caaa22779691e8bb78d81441050ee6b13bcf2116a7712162c0ee41472",
    "conceito_principal": "Responsabilização política e penal do Presidente da República",
    "habilidade_cobrada": "Identificar o juízo competente e o rito constitucional de responsabilização presidencial",
    "tese_ou_regra": "O Presidente responde por crimes comuns perante o STF e por crimes de responsabilidade perante o Senado",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "61c8b345-8907-5761-be92-bf1d32b4b55a",
        "questao_id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
        "letra": "A",
        "texto": "Será ele julgado perante o Congresso Nacional em sessão conjunta obrigatória para qualquer delito.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. O julgamento ocorre no STF ou no Senado separadamente."
      },
      {
        "id": "5c301c39-4816-5099-a159-cdcd753ed3c0",
        "questao_id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
        "letra": "B",
        "texto": "Ficará suspenso de suas funções imediatamente pelo prazo improrrogável de 30 dias.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A suspensão ocorre após a instauração pelo Senado ou recebimento de denúncia pelo STF por até 180 dias."
      },
      {
        "id": "24b88d5a-9d10-5c27-991f-4d28491ccf5e",
        "questao_id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
        "letra": "C",
        "texto": "Será submetido a julgamento perante o Supremo Tribunal Federal, nas infrações penais comuns, ou perante o Senado Federal, nos crimes de responsabilidade.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Art. 86, caput da Constituição Federal."
      },
      {
        "id": "a46f9cc1-bacb-54b6-9729-6d34b52827a2",
        "questao_id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
        "letra": "D",
        "texto": "Caberá ao Superior Tribunal de Justiça realizar a instrução criminal preliminar.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O STJ não julga o Presidente da República."
      },
      {
        "id": "9abcb364-750b-535a-8df6-006782f918b3",
        "questao_id": "f5fa77c5-4e7f-5492-b9a7-fb63966ab247",
        "letra": "E",
        "texto": "Deverá ser decretada sua prisão temporária compulsória pelo Procurador-Geral da República.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O Presidente não está sujeito a prisão enquanto não sobrevier condenação (art. 86, § 3º)."
      }
    ]
  },
  {
    "id": "d5933d4f-ed68-5275-9f58-02ca047a3a09",
    "idSlug": "l13-const-org-011-intervencao-federal-hipoteses-decreto",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "66dd36a8-5e55-5f5c-8ae8-36501eab3e3b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A União não intervirá nos Estados nem no Distrito Federal, exceto para manter a integridade nacional, repelir invasão estrangeira, pôr termo a grave comprometimento da ordem pública ou garantir o livre exercício de qualquer dos Poderes nas unidades da Federação.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 34, I, II, III e IV da Constituição Federal de 1988.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a5e5bcb9f45804653c907f7bb8f8f84ec5e0d0a93cd9354b22bc7f987542e27b",
    "conceito_principal": "Hipóteses constitucionais de intervenção federal",
    "habilidade_cobrada": "Reconhecer os pressupostos materiais da intervenção federal",
    "tese_ou_regra": "A não intervenção é o princípio republicano; a intervenção federal é exceção taxativa",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "cdd20886-030d-5d73-9038-3dac8d78128d",
        "questao_id": "d5933d4f-ed68-5275-9f58-02ca047a3a09",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2204ef45-08cb-5a29-a524-b6fbff76fae6",
        "questao_id": "d5933d4f-ed68-5275-9f58-02ca047a3a09",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "1285881c-322e-551e-a353-371643a55c38",
    "idSlug": "l13-const-org-012-estado-defesa-pressupostos-duracao",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "66dd36a8-5e55-5f5c-8ae8-36501eab3e3b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O Presidente da República pode, ouvidos o Conselho da República e o Conselho de Defesa Nacional, decretar estado de defesa para preservar ou restabelecer a ordem pública ou a paz social ameaçadas por grave e iminente instabilidade institucional ou atingidas por calamidades de grandes proporções na natureza, por tempo não superior a trinta dias, admitida uma única prorrogação por igual período se persistirem as razões.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 136, caput e § 2º da CF/88.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c95716df4c5a6cd6bdf2f0b5717ac8767f6c6d8144fe3f4908506a9d213c63bd",
    "conceito_principal": "Estado de Defesa: pressupostos e prazos de vigência",
    "habilidade_cobrada": "Compreender os limites temporais e materiais do Estado de Defesa",
    "tese_ou_regra": "O Estado de Defesa dura até 30 dias, prorrogável uma vez por igual período",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "4dd2b186-d78d-5e25-bdb6-bb9d2d3115b9",
        "questao_id": "1285881c-322e-551e-a353-371643a55c38",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e1fc1195-f1b3-5ed6-8205-263ce2dcca7e",
        "questao_id": "1285881c-322e-551e-a353-371643a55c38",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d1d39eea-a228-5619-a85d-71c0cfea3f63",
    "idSlug": "l13-const-pod-013-cnj-natureza-administrativa-ausencia-funcao-jurisdicional",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O Conselho Nacional de Justiça (CNJ) é órgão de controle da atuação administrativa e financeira do Poder Judiciário e do cumprimento dos deveres funcionais dos juízes, não exercendo competência jurisdicional, sendo suas decisões sujeitas a controle de legalidade originário pelo STF.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 103-B da CF/88 e pacífica jurisprudência do STF.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4f58d26ac0e1bde2439c1e59a6870ad7c349faa0a46379b74ffebe4dce1de877",
    "conceito_principal": "Natureza administrativa e atribuições do CNJ",
    "habilidade_cobrada": "Identificar as funções fiscalizatórias do CNJ e ausência de atividade judicante",
    "tese_ou_regra": "O CNJ é órgão administrativo de cúpula sem função jurisdicional",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "5f3b4d98-3e03-5230-a080-a52da6370fd6",
        "questao_id": "d1d39eea-a228-5619-a85d-71c0cfea3f63",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "bbbf4368-a981-5bec-b275-3024af675a71",
        "questao_id": "d1d39eea-a228-5619-a85d-71c0cfea3f63",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e11e3483-faa3-5560-af0e-13ff2b1e7192",
    "idSlug": "l13-const-con-014-sumula-vinculante-requisitos-aprovacao",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "f5742ead-d502-5d7b-953f-2117f3fba269",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Com a finalidade de assegurar a estabilidade jurisprudencial e a segurança jurídica nas esferas administrativa e judiciária, o Supremo Tribunal Federal dispõe de competência para editar enunciados de súmula vinculante. Para a aprovação válida de súmula com força vinculante erga omnes, a Constituição Federal exige decisão de dois terços dos ministros da Corte Suprema e a prévia existência de reiteradas decisões sobre a matéria constitucional em debate.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 103-A da CF/88: o STF poderá, de ofício ou por provocação, mediante decisão de dois terços dos seus membros, após reiteradas decisões sobre matéria constitucional, aprovar súmula com efeito vinculante aos demais órgãos judiciais e à administração pública direta e indireta.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8a465d018f4a24ccc017714ca889b18230710b7d856214ac731774e61dd31cc8",
    "conceito_principal": "Requisitos constitucionais da Súmula Vinculante",
    "habilidade_cobrada": "Identificar o quórum qualificado e os pressupostos materiais das Súmulas Vinculantes",
    "tese_ou_regra": "Súmula Vinculante exige 2/3 dos ministros do STF e reiteração de julgados constitucionais",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "449b1ca1-fef8-5545-b841-c8e89e06e029",
        "questao_id": "e11e3483-faa3-5560-af0e-13ff2b1e7192",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ecdb833a-75d2-5a60-897f-c1830d15f66b",
        "questao_id": "e11e3483-faa3-5560-af0e-13ff2b1e7192",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "bd20db24-34db-5456-b62c-f43e3963de72",
    "idSlug": "l13-const-con-015-reclamacao-constitucional-cabimento-stf",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "f5742ead-d502-5d7b-953f-2117f3fba269",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A reclamação constitucional perante o Supremo Tribunal Federal é cabível para preservar a competência do Tribunal e garantir a autoridade das suas decisões. A respeito do seu cabimento perante a Suprema Corte, assinale a opção correta.",
    "explicacao": "GABARITO: A. Art. 103-A, § 3º da CF/88 e art. 988 do CPC: cabe reclamação contra ato administrativo ou judicial que contrariar Súmula Vinculante ou decisão em controle concentrado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ebc067fd6297f9655374267a94b1e7df7873ba135341bcf0d4bd1daf082d25e1",
    "conceito_principal": "Reclamação constitucional perante o STF",
    "habilidade_cobrada": "Reconhecer as hipóteses de cabimento e vedações da reclamação constitucional",
    "tese_ou_regra": "Reclamação tutela autoridade de súmula vinculante e decisões concentradas do STF",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "6692b936-b83e-5de1-9cd4-62d7b9c59036",
        "questao_id": "bd20db24-34db-5456-b62c-f43e3963de72",
        "letra": "A",
        "texto": "Cabe reclamação para garantir o cumprimento de Súmula Vinculante e de decisões proferidas pelo STF em sede de controle concentrado de constitucionalidade.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Art. 103-A, § 3º da CF/88 e art. 988, III e IV do CPC."
      },
      {
        "id": "2b2bf79b-2ee8-5511-b0e4-15f836258900",
        "questao_id": "bd20db24-34db-5456-b62c-f43e3963de72",
        "letra": "B",
        "texto": "Pode ser ajuizada a qualquer tempo mesmo após o trânsito em julgado da decisão judicial reclamada.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Súmula 734 do STF: não cabe reclamação contra decisão transitada em julgado."
      },
      {
        "id": "f2b85200-a46f-5598-a0d9-5650a506b19b",
        "questao_id": "bd20db24-34db-5456-b62c-f43e3963de72",
        "letra": "C",
        "texto": "Serve como sucedâneo recursal ordinário para reexame amplo de fatos e provas de inquérito policial.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A reclamação não substitui recursos cabíveis nem reexamina provas."
      },
      {
        "id": "b23f9482-f4e3-5a0e-aa6e-858c6ad49f4a",
        "questao_id": "bd20db24-34db-5456-b62c-f43e3963de72",
        "letra": "D",
        "texto": "É instrumento privativo do Procurador-Geral da República, vedada a propositura pelo cidadão lesado.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Qualquer parte interessada lesada por ato contrário possui legitimidade."
      },
      {
        "id": "1cde0170-b399-5d7f-a35a-48f9e0870a34",
        "questao_id": "bd20db24-34db-5456-b62c-f43e3963de72",
        "letra": "E",
        "texto": "Não admite concessão de medida liminar suspensiva pelo relator.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. O relator pode conceder liminar para suspender o ato impugnado."
      }
    ]
  },
  {
    "id": "338a97e6-299c-57af-b162-66c1604b221f",
    "idSlug": "l13-const-pod-016-imunidade-parlamentar-material-nexo-funcional",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "7a887c87-f2d3-504f-8ccf-3f7fe67c1812",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Os Deputados e Senadores são invioláveis, civil e penalmente, por quaisquer de suas opiniões, palavras e votos. Segundo o STF, a imunidade parlamentar material exercida fora do recinto do Parlamento exige a demonstração de nexo causal direto entre as declarações emitidas e o exercício do mandato eletivo.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 53 da CF/88 e jurisprudência consolidada do STF: fora do parlamento, a inviolabilidade depende de pertinência com a função parlamentar.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "07d1e3a4f84a7e5c1381efd830eea37b7f5925b14fddc08427a8ee83767f5750",
    "conceito_principal": "Imunidade parlamentar material e nexo funcional extraparlamentar",
    "habilidade_cobrada": "Aplicar os limites jurisprudenciais da inviolabilidade parlamentar",
    "tese_ou_regra": "Opiniões emitidas fora do parlamento só gozam de imunidade se tiverem nexo com o mandato",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "790e7663-f4d8-5065-9e18-66c8c83b3fd0",
        "questao_id": "338a97e6-299c-57af-b162-66c1604b221f",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "1240bc0c-eba6-5907-83d5-d427225a6fe7",
        "questao_id": "338a97e6-299c-57af-b162-66c1604b221f",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b34556df-dd4c-5b9f-b74b-c74ee98f1882",
    "idSlug": "l13-const-pod-017-ministerio-publico-principios-institucionais",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "São princípios institucionais do Ministério Público a unidade, a indivisibilidade e a independência funcional, incumbindo-lhe a defesa da ordem jurídica, do regime democrático e dos interesses sociais e individuais indisponíveis.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 127, caput e § 1º da Constituição Federal de 1988.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8cafcab2d0801702cbb308db37dffa245ff742f5bc5df73dcdab2a5fa2061932",
    "conceito_principal": "Princípios institucionais e missão do Ministério Público",
    "habilidade_cobrada": "Identificar os postulados constitucionais do Ministério Público",
    "tese_ou_regra": "Unidade, indivisibilidade e independência funcional regem a atuação do Ministério Público",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "bc62a28f-f37a-54a9-8db1-9bad9c984cd6",
        "questao_id": "b34556df-dd4c-5b9f-b74b-c74ee98f1882",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b8cd2de7-019d-58e0-9eda-19adabab666d",
        "questao_id": "b34556df-dd4c-5b9f-b74b-c74ee98f1882",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ccdc35c5-e8e0-512c-b866-3c726e555552",
    "idSlug": "l13-const-pod-018-defensoria-publica-autonomia-funcional",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Às Defensorias Públicas Estaduais e da União são asseguradas autonomia funcional e administrativa e a iniciativa de sua proposta orçamentária dentro dos limites estabelecidos na lei de diretrizes orçamentárias.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 134, § 2º da CF/88 (incluído pela EC 45/2004 e reforçado pela EC 74/2013).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9d65f01b5e6e9fba53aba76a714b2717be686eaffe10defc9cd9fda0bccc400a",
    "conceito_principal": "Autonomia funcional e administrativa da Defensoria Pública",
    "habilidade_cobrada": "Reconhecer as garantias constitucionais conferidas à Defensoria Pública",
    "tese_ou_regra": "A Defensoria Pública goza de autonomia funcional, administrativa e orçamentária",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c64ed8f5-9d01-5d47-b35e-2b70722d3599",
        "questao_id": "ccdc35c5-e8e0-512c-b866-3c726e555552",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "786ad484-b6b4-5e98-8265-6e64d3d0b265",
        "questao_id": "ccdc35c5-e8e0-512c-b866-3c726e555552",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "16725f92-d853-568c-a443-3ffd1deb9b79",
    "idSlug": "l13-const-org-019-municipios-competencia-interesse-local",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "66dd36a8-5e55-5f5c-8ae8-36501eab3e3b",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Guarda Municipal",
    "cargo_nome": "Guarda Civil Municipal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Compete aos Municípios legislar sobre assuntos de interesse local e suplementar a legislação federal e a estadual no que couber, competindo-lhes organizar e prestar os serviços públicos de interesse local, como o transporte coletivo municipal.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 30, I, II e V da Constituição Federal de 1988.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c22a56f00d41ca32988d0d9deae957b3f9c843a901c80e4c228b9d63f8d437cc",
    "conceito_principal": "Competências legislativas e materiais dos Municípios",
    "habilidade_cobrada": "Identificar as competências constitucionais do ente municipal",
    "tese_ou_regra": "Municípios legislam sobre interesse local e suplementam leis estaduais/federais",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "8c714a3f-8ab9-5c65-974e-1132a4674528",
        "questao_id": "16725f92-d853-568c-a443-3ffd1deb9b79",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f7e752d6-28ed-5d80-b8ea-0a0c44db1ab0",
        "questao_id": "16725f92-d853-568c-a443-3ffd1deb9b79",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
    "idSlug": "l13-const-pod-020-advocacia-publica-funcoes-essenciais",
    "disciplina_id": "8a5fd46c-e3ab-5e99-b338-3a17eafa50e9",
    "assunto_id": "0bbb16e6-3694-512f-8c61-a96893588f7f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "No rol das funções essenciais à justiça, a Advocacia-Geral da União (AGU) e as Procuradorias dos Estados têm por função constitucional precípua:",
    "explicacao": "GABARITO: A. Art. 131 e 132 da CF/88: representação judicial e consultoria jurídica das respectivas unidades federativas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9d92ad0c3fd4a5de482cc9331e5337234072cfda9dd4a6a1363738a89fc89e55",
    "conceito_principal": "Atribuições constitucionais da Advocacia Pública",
    "habilidade_cobrada": "Diferenciar as funções da Advocacia Pública, Ministério Público e Defensoria Pública",
    "tese_ou_regra": "À Advocacia Pública cabe a representação judicial e consultoria jurídica do Estado",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "b88cea87-d80a-56ac-932e-622324dc97e2",
        "questao_id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
        "letra": "A",
        "texto": "Representar judicial e extrajudicialmente os respectivos entes federativos e exercer as atividades de consultoria e assessoramento jurídico do Poder Executivo.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Art. 131 e 132 da Constituição Federal."
      },
      {
        "id": "50d568ab-6840-5261-8c77-e6aa630d22f4",
        "questao_id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
        "letra": "B",
        "texto": "Exercer privativamente a titularidade da ação penal pública em crimes contra a administração pública.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A titularidade da ação penal pública é privativa do Ministério Público."
      },
      {
        "id": "16668b65-0c28-5b4c-8b86-0e53475987a9",
        "questao_id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
        "letra": "C",
        "texto": "Julgar os litígios administrativos de natureza disciplinar dos servidores policiais com força de coisa julgada.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Coisa julgada em sentido estrito é exclusiva do Poder Judiciário."
      },
      {
        "id": "eed94dee-0008-5405-85e5-173b08a93721",
        "questao_id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
        "letra": "D",
        "texto": "Realizar perícias de áudio e imagem para os inquéritos da Polícia Federal.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Perícia é atribuição da polícia científica/peritos oficiais."
      },
      {
        "id": "8b9f773b-a26f-5d7b-8ef2-bf51d1f62dd8",
        "questao_id": "165f80c7-632e-5d1d-a7d4-4c5e052e1924",
        "letra": "E",
        "texto": "Promover a defesa técnica criminal dos réus hipossuficientes perante os tribunais do júri.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Esta é função institucional da Defensoria Pública (art. 134 da CF)."
      }
    ]
  }
];
