// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 23

export const m16_questoes = [
  {
    "id": "4d6d7a7c-0479-5ca5-bf52-e17ccde61da1",
    "idSlug": "l13-dh-inter-001-cadh-art4-pena-morte-vedacao-restabelecimento",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Conforme o art. 4º da Convenção Americana sobre Direitos Humanos (Pacto de São José da Costa Rica), nos países que ainda não aboliram a pena de morte, esta somente poderá ser imposta para os delitos mais graves e em cumprimento de sentença transitada em julgado; ademais, o texto convencional proíbe expressamente o restabelecimento da pena de morte nos Estados que já a hajam abolido.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 4º, itens 2 e 3 da CADH: consagração do princípio da vedação de restabelecimento (princípio progressivo abolicionista da pena de morte).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9828df3c78638bb0888d242c58c3828c9eca6caa56e5ea0fff7dc6e28e7893f6",
    "conceito_principal": "Direito à vida e vedação ao restabelecimento da pena de morte na CADH (Art. 4º)",
    "habilidade_cobrada": "Reconhecer as limitações e a cláusula de não restabelecimento da pena capital",
    "tese_ou_regra": "O Estado que aboliu a pena capital não pode reintroduzi-la em sua legislação",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "ba65bb35-ea40-5025-bdc7-0e86378dbd3d",
        "questao_id": "4d6d7a7c-0479-5ca5-bf52-e17ccde61da1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d642dc91-07a9-53bb-9280-d5b651771f63",
        "questao_id": "4d6d7a7c-0479-5ca5-bf52-e17ccde61da1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "425e6aca-b721-5a89-bd1f-b2a41f0c861c",
    "idSlug": "l13-dh-inter-002-audiencia-custodia-cadh-art7-item5",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A audiência de custódia, introduzida formalmente no ordenamento processual penal brasileiro após consolidada interpretação do STF, encontra assento convencional expresso no art. 7º, item 5, da CADH, que determina que toda pessoa presa ou retida deve ser conduzida sem demora à presença de um juiz ou outra autoridade autorizada por lei a exercer funções judiciais.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 7º, 5 da CADH e ADPF 347/STF: a apresentação imediata ao magistrado é direito subjetivo convencional fundamental.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f98aea8e12fc0c8cc464098c3a1b7d8a0750bfbfa558abf144cf5747ab63a708",
    "conceito_principal": "Audiência de custódia como garantia convencional (Art. 7º, item 5 da CADH)",
    "habilidade_cobrada": "Identificar a matriz convencional internacional da audiência de custódia no Brasil",
    "tese_ou_regra": "O preso deve ser apresentado perante a autoridade judiciária competente sem demora",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "5b497469-3ca2-5812-ac23-be9817224c55",
        "questao_id": "425e6aca-b721-5a89-bd1f-b2a41f0c861c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "fdccb00a-723c-57dc-845b-8db2b5d85f09",
        "questao_id": "425e6aca-b721-5a89-bd1f-b2a41f0c861c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "60e973ce-5674-5528-869f-dd05ec933823",
    "idSlug": "l13-dh-inter-003-cadh-art8-garantias-judiciais-prazo-razoavel",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Nos termos do art. 8º da CADH, toda pessoa tem direito a ser ouvida, com as devidas garantias e dentro de um prazo razoável, por um juiz ou tribunal competente, independente e imparcial; para a aferição do prazo razoável, a Corte Interamericana adota quatro critérios objetivos: complexidade do assunto, conduta processual do interessado, conduta das autoridades públicas e a afetação gerada pela duração do processo na situação jurídica da pessoa envolvida.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Jurisprudência reiterada da Corte IDH (Caso Genie Lacayo, Caso Valle Jaramillo etc.) sobre o teste dos 4 elementos do prazo razoável.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a98fe6c4e98653a2640a3a2fd5baf11f0651ff3867edb36633290c66025909ec",
    "conceito_principal": "Garantias judiciais (Art. 8º da CADH) e critérios do prazo razoável da Corte IDH",
    "habilidade_cobrada": "Reconhecer os critérios objetivos da Corte IDH para mensuração da duração razoável do processo",
    "tese_ou_regra": "A duração razoável afere-se pela complexidade, comportamento das partes e das autoridades",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "0effa974-90e4-5e00-adb4-b621fbc5c832",
        "questao_id": "60e973ce-5674-5528-869f-dd05ec933823",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "365885e0-d276-5034-8d03-07f223b50725",
        "questao_id": "60e973ce-5674-5528-869f-dd05ec933823",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e44f8f3a-0b6a-5f20-9da7-fdd95686298c",
    "idSlug": "l13-dh-inter-004-cidh-legitimidade-ampla-ong-individuo",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Perante a Comissão Interamericana de Direitos Humanos (CIDH), qualquer pessoa, grupo de pessoas ou entidade não governamental legalmente reconhecida em um ou mais Estados-membros da OEA possui legitimidade ativa para apresentar petições que contenham denúncias ou queixas de violação da Convenção Americana por um Estado-parte.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 44 da CADH: consagra a legitimação ampla e universal perante a CIDH, dispensando que o peticionário seja a própria vítima direta.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "17e6515cb1f2a0cb0839bc01469aa7e3d4c492a97b3b71d5a0584336af9d761f",
    "conceito_principal": "Legitimidade ativa perante a Comissão Interamericana de Direitos Humanos (Art. 44 CADH)",
    "habilidade_cobrada": "Distinguir a ampla legitimidade de denúncia perante a CIDH",
    "tese_ou_regra": "Qualquer pessoa ou ONG pode peticionar perante a Comissão Interamericana",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "25d471ec-64b2-542d-a125-f506fe049384",
        "questao_id": "e44f8f3a-0b6a-5f20-9da7-fdd95686298c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a4da473e-8957-52b2-977f-667e9ad5c559",
        "questao_id": "e44f8f3a-0b6a-5f20-9da7-fdd95686298c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
    "idSlug": "l13-dh-inter-005-corte-idh-jus-postulandi-vitima-acesso-direto",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "No tocante ao acesso à jurisdição da Corte Interamericana de Direitos Humanos (Corte IDH) e à sistemática de submissão de casos contenciosos, assinale a opção correta.",
    "explicacao": "GABARITO: C. Nos termos do art. 61, item 1, da CADH, somente os Estados-partes e a Comissão têm o direito de submeter um caso à decisão da Corte. Vítimas e ONGs não têm 'jus postulandi' para demandar o Estado diretamente na Corte (embora tenham participação autônoma na fase de alegações após a submissão do caso pela Comissão).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f64d1c78dceaf9c29457aa268c0a36bf170923e974ee23bb66fa054b1ad625f9",
    "conceito_principal": "Competência e legitimidade de submissão à Corte Interamericana (Art. 61 CADH)",
    "habilidade_cobrada": "Diferenciar a atuação da Comissão e a jurisdição contenciosa da Corte IDH",
    "tese_ou_regra": "Apenas a Comissão e os Estados-partes podem submeter casos à Corte IDH",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "1fd2887f-2de5-5973-8e83-3eebf721ef98",
        "questao_id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
        "letra": "A",
        "texto": "Qualquer cidadão brasileiro que sofrer abuso policial pode ajuizar ação indenizatória diretamente na Corte IDH sem necessidade de prévia tramitação na Comissão.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Indivíduos não possuem jus postulandi direto perante a Corte IDH."
      },
      {
        "id": "492f39eb-3ede-56d8-a5c0-0c66cd42c7e0",
        "questao_id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
        "letra": "B",
        "texto": "A Corte IDH tem competência para julgar e condenar criminalmente indivíduos e agentes públicos que praticaram crimes de tortura a penas de prisão.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A Corte IDH julga a responsabilidade internacional do Estado, e não crimes individuais de particulares."
      },
      {
        "id": "227ee61c-0806-5559-9d5e-91ffadc657fc",
        "questao_id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
        "letra": "C",
        "texto": "Somente os Estados-partes e a Comissão Interamericana possuem legitimidade para submeter um caso contencioso à apreciação da Corte Interamericana.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Artigo 61, item 1 da CADH."
      },
      {
        "id": "61829ffe-7038-5152-ad15-aa9ba23ed53f",
        "questao_id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
        "letra": "D",
        "texto": "A sentença proferida pela Corte IDH possui caráter meramente opinativo e desprovido de força executória perante o Judiciário brasileiro.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A sentença da Corte IDH é vinculante, definitiva e inapelável (art. 68 da CADH)."
      },
      {
        "id": "74861412-0067-583e-9b54-f6e8584f4819",
        "questao_id": "f566dc19-ed3b-50d0-8c4f-3378703bbaeb",
        "letra": "E",
        "texto": "O Brasil submete-se compulsoriamente à jurisdição contenciosa da Corte IDH desde a ratificação da Carta da ONU de 1945.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A aceitação da jurisdição contenciosa da Corte IDH deu-se pelo Decreto Legislativo 89/1998."
      }
    ]
  },
  {
    "id": "5c65fbd5-ee07-594c-9c41-5b5bbea90ac0",
    "idSlug": "l13-dh-inter-006-caso-favela-nova-brasilia-investigacao-independente",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "No emblemático Caso Favela Nova Brasília vs. Brasil (2017), a Corte Interamericana condenou o Estado brasileiro por violações ligadas a operações policiais letais e violência sexual, assentando a obrigação de o Brasil assegurar que mortes decorrentes de intervenção policial sejam investigadas por órgão independente e imparcial, diverso da corporação a que pertencerem os agentes envolvidos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Decisão histórica da Corte IDH que impôs diretrizes de independência em investigações de letalidade policial e combate à impunidade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8bb3463270720987c4a2997a7819013c5a7223da4714f3b0ed04ac2c2966628f",
    "conceito_principal": "Caso Favela Nova Brasília vs. Brasil (Corte IDH, 2017) e independência investigativa",
    "habilidade_cobrada": "Identificar as obrigações estatais decorrentes de condenações na Corte IDH sobre atuação policial",
    "tese_ou_regra": "Mortes decorrentes de intervenção policial exigem investigação célere, rigorosa e independente",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "6424c5da-b7de-5465-b9a4-c9d703311543",
        "questao_id": "5c65fbd5-ee07-594c-9c41-5b5bbea90ac0",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "d01dc3b2-a366-5d2a-9b27-3d321a731893",
        "questao_id": "5c65fbd5-ee07-594c-9c41-5b5bbea90ac0",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "fcda7307-4dd2-58b6-916e-4161a160c2a7",
    "idSlug": "l13-dh-inter-007-caso-herzog-crimes-lesa-humanidade-imprescritibilidade",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Ao julgar o Caso Vladimir Herzog e outros vs. Brasil (2018), a Corte Interamericana declarou que o assassinato de Vladimir Herzog, praticado sob tortura em ambiente de custódia estatal durante o regime militar, configurou crime contra a humanidade, ostentando natureza imprescritível e não passível de anistia, graça ou indulto.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A Corte IDH reafirmou sua jurisprudência no sentido de que leis de autoanistia e prescrição ordinária não podem obstar a apuração de crimes contra a humanidade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c22aec37cb0a1348eedeaef9af4a449bea2fe079004ed20edc4f79aeade72a90",
    "conceito_principal": "Caso Vladimir Herzog vs. Brasil e imprescritibilidade de crimes contra a humanidade",
    "habilidade_cobrada": "Reconhecer os efeitos da jurisdição interamericana sobre leis de anistia e crimes de Estado",
    "tese_ou_regra": "Crimes contra a humanidade são imprescritíveis e insuscetíveis de anistia",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "41a2753c-dc84-5fc1-a8e5-94f1ff9405de",
        "questao_id": "fcda7307-4dd2-58b6-916e-4161a160c2a7",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6cd8bd77-9ac3-58e0-969e-1477a5a324c8",
        "questao_id": "fcda7307-4dd2-58b6-916e-4161a160c2a7",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "a3368ff9-5522-5260-9cfb-01578acad22c",
    "idSlug": "l13-dh-inter-008-controle-convencionalidade-difuso-magistratura",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O controle de convencionalidade difuso deve ser exercido de ofício por todos os juízes e tribunais nacionais, cabendo aos magistrados compatibilizar a legislação interna infraconstitucional com os tratados de direitos humanos ratificados pelo Estado e com a jurisprudência da Corte Interamericana.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina do controle de convencionalidade (Caso Almonacid Arellano e Caso Trabalhadores da Fazenda Brasil Verde): todo juiz local atua como juiz interamericano no controle difuso.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8239f9bece834eac715cbf0b85ba9d300c6e92b2da005d2c6fd356e4a686ada2",
    "conceito_principal": "Controle de convencionalidade difuso de ofício pelo Judiciário nacional",
    "habilidade_cobrada": "Compreender o dever do juiz nacional de confrontar a lei local com os tratados de DH",
    "tese_ou_regra": "Juízes nacionais devem exercer o controle de convencionalidade ex officio",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "88651817-8ba2-5c3a-b1eb-54c2b6611922",
        "questao_id": "a3368ff9-5522-5260-9cfb-01578acad22c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "802ebd5e-7ce7-5f1e-a639-17272ae4b780",
        "questao_id": "a3368ff9-5522-5260-9cfb-01578acad22c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "05d4a873-624d-53b0-8382-602768ce57cd",
    "idSlug": "l13-dh-inter-009-cadh-art7-prisao-ilegal-reparacao-indenizatoria",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Nos termos do art. 7º, item 6 e 7, da CADH, toda pessoa privada de sua liberdade ilegalmente tem direito a recorrer a um juiz ou tribunal competente a fim de que este decida, sem demora, sobre a legalidade de sua prisão e ordene sua soltura, caso seja ilegal, além de ter direito à indenização em caso de erro judiciário ou detenção arbitrária.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 7º, 6 e art. 10 da CADH: consagração do habeas corpus convencional e do direito à justa indenização por privação arbitrária da liberdade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4ba108349ffbb87f23a0d6d581d6b26af1b6cf291ec0a80529616fbe5606ed8a",
    "conceito_principal": "Habeas corpus convencional e indenização por prisão arbitrária (Art. 7º e 10 CADH)",
    "habilidade_cobrada": "Identificar as garantias contra detenções ilegais no plano interamericano",
    "tese_ou_regra": "A prisão ilegal confere direito à libertação imediata e à correspondente reparação indenizatória",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "f954fcb4-26d5-5f4a-9cb5-cb3367742958",
        "questao_id": "05d4a873-624d-53b0-8382-602768ce57cd",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a1c197a1-a045-5335-afd5-3f04077904b1",
        "questao_id": "05d4a873-624d-53b0-8382-602768ce57cd",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
    "idSlug": "l13-dh-inter-010-clausula-derrogacao-suspensao-garantias-art27",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em situações de estado de defesa, estado de sítio ou emergência pública que ameace a independência ou segurança do Estado, o art. 27 da CADH disciplina a suspensão temporária de obrigações convencionais. A respeito dessa cláusula de derrogação, assinale a opção correta.",
    "explicacao": "GABARITO: E. O art. 27, 2 da CADH veda terminantemente a suspensão de um núcleo duro de direitos: direito à vida (art. 4), integridade pessoal (art. 5), proibição de escravidão (art. 6), princípio da legalidade e retroatividade benéfica (art. 9), liberdade de consciência/religião (art. 12), proteção à família (art. 17), direito ao nome (art. 18), direitos da criança (art. 19), direitos políticos (art. 23) e as garantias judiciais indispensáveis à proteção de tais direitos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "46db260b2a76b139cffa6874c3ce93fefd49e7a0581c0fca08eced2d36aba323",
    "conceito_principal": "Cláusula de derrogação e direitos inderrogáveis em estado de exceção (Art. 27 da CADH)",
    "habilidade_cobrada": "Identificar o núcleo inderrogável de direitos humanos imunes à suspensão de garantias",
    "tese_ou_regra": "Direitos vitais como vida, integridade, legalidade penal e garantias judiciais jamais podem ser suspensos",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "35a7af63-62d8-5d4c-b006-669a5de68d76",
        "questao_id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
        "letra": "A",
        "texto": "Em estado de sítio, o Presidente da República pode suspender irrestritamente qualquer direito previsto na Convenção Americana, inclusive a vedação à tortura.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. A integridade pessoal e a proibição da tortura são absolutamente inderrogáveis."
      },
      {
        "id": "7d10765c-e0b5-516e-b07f-87a4a5053b52",
        "questao_id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
        "letra": "B",
        "texto": "A suspensão de garantias dispensa qualquer comunicação aos demais Estados-membros da OEA ou ao Secretário-Geral.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Exige-se notificação formal imediata ao Secretário-Geral da OEA (art. 27, 3)."
      },
      {
        "id": "7aa442c8-5675-54d2-8bda-b2d87255a435",
        "questao_id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
        "letra": "C",
        "texto": "O direito à liberdade de locomoção e o direito de reunião tornam-se inderrogáveis e perpétuos em qualquer conjuntura de calamidade.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Locomoção e reunião podem sofrer restrições transitórias e proporcionais."
      },
      {
        "id": "ef50d321-806c-5217-9213-8fd9082ffa76",
        "questao_id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
        "letra": "D",
        "texto": "A decretação de emergência pública autoriza a aplicação retroativa de lei penal mais severa a fatos pretéritos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O princípio da legalidade estrita penal é cláusula inderrogável."
      },
      {
        "id": "0af54225-6e83-58cb-9c29-9414e4e03fe6",
        "questao_id": "eeeb6529-0d8c-598f-a216-40a0c712bf1e",
        "letra": "E",
        "texto": "O art. 27 da CADH veda a suspensão do direito à vida, da integridade pessoal, da proibição da escravidão, da legalidade penal e das garantias judiciais indispensáveis à proteção desses direitos.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Correta. Artigo 27, item 2 da Convenção Americana sobre Direitos Humanos."
      }
    ]
  },
  {
    "id": "75ed09d4-6462-5ddf-8467-7814a7ad2b2a",
    "idSlug": "l13-dh-inter-011-cadh-art5-integridade-pessoal-separacao-presos",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O art. 5º da Convenção Americana determina que as penas privativas de liberdade devem ter por finalidade essencial a reforma e a readaptação social dos condenados, impondo, como regra cogente, que os processados (presos provisórios) devem ficar separados dos condenados, salvo em circunstâncias excepcionais, e submetidos a tratamento adequado à sua condição de não condenados.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 5º, itens 4 e 6 da CADH: consagra a separação obrigatória entre presos provisórios e condenados definitivos como garantia da dignidade humana carcerária.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "447d31aab799d50588175d338bf835ce87f2345c2ae65e5dbf40be5f7b28ec3f",
    "conceito_principal": "Direito à integridade pessoal e segregação de custodiados provisórios (Art. 5º CADH)",
    "habilidade_cobrada": "Reconhecer as diretrizes convencionais sobre classificação e separação de presos",
    "tese_ou_regra": "Presos provisórios devem permanecer alojados separadamente de presos já sentenciados",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "8c2bd646-7e74-5c88-980b-34766421e901",
        "questao_id": "75ed09d4-6462-5ddf-8467-7814a7ad2b2a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "0fa834da-566f-573b-8c30-7c9005a740df",
        "questao_id": "75ed09d4-6462-5ddf-8467-7814a7ad2b2a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "dea05ae4-4a5a-5ed0-b5a6-dcf5b5b6da1b",
    "idSlug": "l13-dh-inter-012-cadh-art13-liberdade-expressao-censura-previa",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Nos termos do art. 13 da CADH, o exercício da liberdade de pensamento e de expressão não pode estar sujeito a censura prévia, mas a responsabilidades ulteriores expressamente fixadas pela lei para assegurar o respeito aos direitos de outrem ou a proteção da segurança nacional, da ordem pública, da saúde ou da moral públicas.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 13, item 2 da CADH: a censura prévia é peremptoriamente vedada, respondendo o emissor a posteriori por eventuais abusos ou ilícitos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6360e89f129d7b0e4fee503dc7964bd2eb000364c143c41f417bc7a3b772570d",
    "conceito_principal": "Liberdade de pensamento e vedação à censura prévia (Art. 13 da CADH)",
    "habilidade_cobrada": "Compreender os limites convencionais à censura estatal e o regime de responsabilidade posterior",
    "tese_ou_regra": "A liberdade de expressão veda censura prévia governamental, admitindo responsabilização posterior",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "844a9205-c5a2-5f6e-854c-fafd5778af78",
        "questao_id": "dea05ae4-4a5a-5ed0-b5a6-dcf5b5b6da1b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "143f7aed-122b-58ac-9602-7991e397337d",
        "questao_id": "dea05ae4-4a5a-5ed0-b5a6-dcf5b5b6da1b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "421f6ba6-b2bc-5d25-afec-f23dc2c38a76",
    "idSlug": "l13-dh-inter-013-esgotamento-recursos-internos-excecoes-cadh",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Para que uma petição seja admitida pela Comissão Interamericana, exige-se como regra geral o prévio esgotamento dos recursos da jurisdição interna; todavia, essa exigência é dispensada quando não existir na legislação interna o devido processo legal para proteção do direito, quando for negado à vítima o acesso aos recursos ou quando houver demora injustificada na decisão judicial.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 46, itens 1, 'a' e 2 da CADH: estabelece a regra da subsidiariedade e as três exceções taxativas ao esgotamento prévio de recursos locais.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1063ee29bcee60246ae48832e09a80f9bcd71d49b7d6fbf3f1a1cf333a41dba0",
    "conceito_principal": "Requisito de esgotamento de recursos internos e suas exceções (Art. 46 CADH)",
    "habilidade_cobrada": "Identificar as situações em que a vítima pode acionar a CIDH diretamente sem esgotar a via local",
    "tese_ou_regra": "Inexistência de devido processo, recusa de acesso ou demora injustificada dispensam o esgotamento interno",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "cb94fcf8-2767-50cb-8532-de73eff6b640",
        "questao_id": "421f6ba6-b2bc-5d25-afec-f23dc2c38a76",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "416c1888-bda6-565e-ac44-6b57f1136aed",
        "questao_id": "421f6ba6-b2bc-5d25-afec-f23dc2c38a76",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "02f485f5-6c60-5288-911e-f50f452a763d",
    "idSlug": "l13-dh-inter-014-corte-idh-medidas-provisorias-extrema-gravidade",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em casos de extrema gravidade e urgência, e quando se fizer necessário para evitar danos irreparáveis às pessoas, a Corte Interamericana de Direitos Humanos pode ordenar medidas provisórias de ofício ou a requerimento da Comissão, inclusive em assuntos que ainda não estejam formalmente submetidos a seu conhecimento jurisdicional.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 63, item 2 da CADH: poder cautelar geral da Corte IDH para concessão de medidas provisórias urgentes (ex.: Caso Penitenciária de Curado).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "bfc3cdec22142f1829b4e199d0b9d4472bad2cd0dfdb8b47c1dd57c268457b80",
    "conceito_principal": "Medidas Provisórias concedidas pela Corte IDH (Art. 63, item 2 da CADH)",
    "habilidade_cobrada": "Reconhecer a natureza e os pressupostos das medidas cautelares e provisórias da Corte IDH",
    "tese_ou_regra": "Extrema gravidade, urgência e risco de dano irreparável legitimam medidas provisórias da Corte IDH",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "4b60058f-223f-5235-b582-48dfe839b89b",
        "questao_id": "02f485f5-6c60-5288-911e-f50f452a763d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "12b45a70-de7d-571e-98f1-6aa1ad771511",
        "questao_id": "02f485f5-6c60-5288-911e-f50f452a763d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
    "idSlug": "l13-dh-inter-015-caso-brasil-verde-trabalho-escravo-discriminacao",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "No Caso Trabalhadores da Fazenda Brasil Verde vs. Brasil (2016), a Corte Interamericana proferiu sentença de grande relevância no combate a crimes graves. Assinale a opção que reflete o entendimento adotado pela Corte nessa decisão histórica.",
    "explicacao": "GABARITO: B. A Corte IDH condenou o Brasil pela prática de trabalho forçado contemporâneo e servidão por dívidas, reconhecendo a violação ao art. 6º da CADH com discriminação estrutural baseada na vulnerabilidade socioeconômica dos trabalhadores aliciados.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "33c28b0d162ed142192f685cc29c851c4f1e619a31526390149f4ae2f6ba0fbc",
    "conceito_principal": "Caso Fazenda Brasil Verde vs. Brasil (Corte IDH, 2016) e trabalho escravo contemporâneo",
    "habilidade_cobrada": "Analisar as diretrizes interamericanas de erradicação da servidão por dívidas e trabalho análogo à escravidão",
    "tese_ou_regra": "O trabalho escravo contemporâneo viola gravemente a CADH e impõe responsabilização estatal por omissão",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "86c0c6af-c3c8-5dbf-99c5-f025b81fc676",
        "questao_id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
        "letra": "A",
        "texto": "A Corte IDH declarou que a caracterização do trabalho escravo moderno exige a privação física absoluta da liberdade com retenção armada permanente em cela fechada.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. A servidão por dívidas e condições degradantes configuram o ilícito sem necessidade de jaula física."
      },
      {
        "id": "b8d7febc-8822-5809-bc5d-d69a60c9598b",
        "questao_id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
        "letra": "B",
        "texto": "A Corte IDH condenou o Brasil por trabalho forçado e servidão por dívida, fixando a imprescritibilidade dessas graves violações e o dever de reparação integral e não repetição.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Decisão histórica do Caso Fazenda Brasil Verde (2016)."
      },
      {
        "id": "09a59102-423a-5411-aea1-23064b5fb976",
        "questao_id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
        "letra": "C",
        "texto": "O tribunal internacional absolveu o Estado brasileiro por entender que a responsabilidade era exclusiva dos proprietários rurais privados.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. O Estado foi condenado por negligência, omissão e tolerância estrutural."
      },
      {
        "id": "21690921-4179-53b5-b575-231480181ee8",
        "questao_id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
        "letra": "D",
        "texto": "Ficou assentado que os fiscais e policiais do trabalho não possuem poder de interdição preventiva em propriedades privadas sem sentença cível prévia.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A decisão cobrou fortalecimento da fiscalização e punição célere."
      },
      {
        "id": "97a90316-318a-5731-8ec1-9edc3d3647f2",
        "questao_id": "52c7ecfb-4188-558e-9ca8-ad3a424e1535",
        "letra": "E",
        "texto": "A Corte determinou a revogação do crime de redução a condição análoga à de escravo do Código Penal brasileiro por considerá-lo excessivamente abrangente.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A Corte elogiou o tipo penal do art. 149 do CP e exigiu sua aplicação efetiva."
      }
    ]
  },
  {
    "id": "24c876cd-4318-5bab-99ea-cb1b594a0017",
    "idSlug": "l13-dh-inter-016-cadh-art8-tradutor-gratuito-estrangeiro-indigena",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Nos termos do art. 8º, item 2, alínea 'a', da Convenção Americana, constitui garantia judicial mínima de toda pessoa acusada o direito irrenunciável de ser assistida gratuitamente por tradutor ou intérprete, caso não compreenda ou não fale o idioma do juízo ou tribunal.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Garantia indeclinável que vincula os atos de polícia judiciária e a instrução processual para estrangeiros e indígenas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "25b39643ec544fd3a6939ecfdb0b23c5d2bcb43b9e4569dc7b0b45c775bf2a1a",
    "conceito_principal": "Garantia de assistência gratuita de tradutor ou intérprete (Art. 8º, 2, 'a' da CADH)",
    "habilidade_cobrada": "Reconhecer a obrigatoriedade de intérprete em interrogatórios e audiências policiais",
    "tese_ou_regra": "O investigado que não domina a língua oficial tem direito público subjetivo a intérprete gratuito",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "c6c91479-06bf-5ba0-ad25-7a4d4695a1c8",
        "questao_id": "24c876cd-4318-5bab-99ea-cb1b594a0017",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "cf5d1f53-1fb2-5b3b-a303-f58077b924ef",
        "questao_id": "24c876cd-4318-5bab-99ea-cb1b594a0017",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "8ce9a3d1-2494-52c4-86e4-2e24d4536dc9",
    "idSlug": "l13-dh-inter-017-cadh-art4-gestante-menor-maior-70-pena-morte",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O art. 4º, item 5, da CADH estabelece vedações subjetivas expressas à aplicação da pena capital nos países que a admitem, proibindo sua imposição a pessoas que, no momento do cometimento do delito, eram menores de dezoito anos ou maiores de setenta anos de idade, bem como a mulheres em estado de gravidez.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 4º, item 5 da CADH: proteção reforçada a menores de 18 anos, idosos acima de 70 anos e mulheres grávidas.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cd1600cfd3e2160cc0edd4be16249130a7d06094a658ed0ce524af855ea67b25",
    "conceito_principal": "Limitações subjetivas e etárias à pena de morte na CADH (Art. 4º, item 5)",
    "habilidade_cobrada": "Identificar as proibições absolutas de aplicação da pena capital a grupos específicos",
    "tese_ou_regra": "Menores de 18, maiores de 70 anos e gestantes jamais podem ser condenados à morte",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "11819749-6359-56ac-a516-e1cf5d9b61b7",
        "questao_id": "8ce9a3d1-2494-52c4-86e4-2e24d4536dc9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e513234c-5a4f-5a00-96ed-89fdcad41f91",
        "questao_id": "8ce9a3d1-2494-52c4-86e4-2e24d4536dc9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5a5e2771-43fc-59a0-9c25-7962ece74b42",
    "idSlug": "l13-dh-inter-018-cadh-indulto-anistia-graca-pedido-morte",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Conforme o Pacto de São José da Costa Rica, toda pessoa condenada à morte tem o direito de solicitar anistia, indulto ou comutação da pena, não podendo a pena capital ser executada enquanto o respectivo pedido estiver pendente de decisão pela autoridade competente.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 4º, item 6 da CADH: efeito suspensivo automático do pedido de clemência/indulto sobre a execução da pena capital.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e228438c2dfb38361adcf1f57d2ac38d0cb48744af011593ac8d1e2ea3bf37c5",
    "conceito_principal": "Direito de solicitar anistia ou indulto por condenado à pena de morte (Art. 4º, item 6 da CADH)",
    "habilidade_cobrada": "Reconhecer o efeito suspensivo de pedidos de clemência soberana",
    "tese_ou_regra": "A pena capital não pode ser executada enquanto pender exame de anistia, indulto ou comutação",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "0c193d45-0a5c-5201-8cde-27db638eb654",
        "questao_id": "5a5e2771-43fc-59a0-9c25-7962ece74b42",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "de38251a-60b4-5445-b3c5-9b26fc168743",
        "questao_id": "5a5e2771-43fc-59a0-9c25-7962ece74b42",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "db8258d9-13ac-524b-939e-592f7dcb57d7",
    "idSlug": "l13-dh-inter-019-corte-idh-cumprimento-sentencas-supervisao",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A Corte Interamericana possui competência para supervisionar o cumprimento de suas próprias sentenças condenatórias, podendo realizar audiências de supervisão e emitir resoluções de monitoramento até a integral execução das medidas de reparação pecuniária, reformas legislativas, protocolos policiais e garantias de não repetição impostas ao Estado.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 68, item 1 da CADH e jurisprudência constante da Corte IDH: a supervisão de cumprimento de sentença é mecanismo inerente à eficácia da jurisdição internacional.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9a95094cd51e424617f5caaa47e3c5eaa9aefda9fc71798f35a0cb7b1b776328",
    "conceito_principal": "Supervisão do cumprimento de sentenças pela Corte Interamericana de Direitos Humanos",
    "habilidade_cobrada": "Compreender o processo contínuo de monitoramento de reparações da Corte IDH",
    "tese_ou_regra": "A Corte IDH monitora a execução de suas decisões até o adimplemento integral de todas as obrigações",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "15f082d9-be62-59ed-ab3b-e0448960ce15",
        "questao_id": "db8258d9-13ac-524b-939e-592f7dcb57d7",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7cbb6d3d-78fc-5f2b-ad96-5a71345e0d35",
        "questao_id": "db8258d9-13ac-524b-939e-592f7dcb57d7",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "c73448be-bf1c-5f19-81d6-883466abe993",
    "idSlug": "l13-dh-inter-020-protocolo-san-salvador-justiciabilidade-direta",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "O Protocolo Adicional à Convenção Americana em Matéria de Direitos Econômicos, Sociais e Culturais (Protocolo de San Salvador de 1988) consagra direitos sociais no sistema interamericano. Nos termos de seu art. 19, item 6, quais direitos admitem acionamento direto do sistema de petições individuais perante os órgãos interamericanos?",
    "explicacao": "GABARITO: D. O art. 19, 6 do Protocolo de San Salvador prevê a justiciabilidade direta mediante petição individual perante a Comissão/Corte IDH apenas para dois direitos específicos: os direitos sindicais (art. 8º, 'a') e o direito à educação (art. 13).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5fd180239fad77e65888b0b9d618c23a357a863f589b70b84ef1e64c60844b9e",
    "conceito_principal": "Justiciabilidade direta no Protocolo de San Salvador de 1988 (Art. 19, item 6)",
    "habilidade_cobrada": "Identificar os direitos sociais passíveis de peticionamento individual direto no sistema interamericano",
    "tese_ou_regra": "Direitos sindicais e direito à educação admitem denúncia individual direta no Protocolo de San Salvador",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "eb036407-a576-5d72-bb83-a7260e3489bc",
        "questao_id": "c73448be-bf1c-5f19-81d6-883466abe993",
        "letra": "A",
        "texto": "Apenas o direito à moradia adequada e o direito à alimentação básica.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Moradia e alimentação não constam no rol restrito de justiciabilidade direta do art. 19.6."
      },
      {
        "id": "3e3c0f05-4bdb-5917-941a-1be517adf802",
        "questao_id": "c73448be-bf1c-5f19-81d6-883466abe993",
        "letra": "B",
        "texto": "Todos os direitos previstos no Protocolo de San Salvador sem nenhuma restrição procedimental.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Apenas dois direitos possuem cláusula expressa de petição individual direta."
      },
      {
        "id": "87b1ed9e-39e5-5738-a106-5476f1cd6dff",
        "questao_id": "c73448be-bf1c-5f19-81d6-883466abe993",
        "letra": "C",
        "texto": "Exclusivamente o direito ao meio ambiente sadio e à previdência social universal.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Não contemplados pelo rol de justiciabilidade direta estrita do protocolo."
      },
      {
        "id": "55fc5eaa-2b5b-51a1-9436-ab8e506aedb1",
        "questao_id": "c73448be-bf1c-5f19-81d6-883466abe993",
        "letra": "D",
        "texto": "Os direitos sindicais (liberdade sindical e filiação) e o direito à educação.",
        "correta": true,
        "ordem": 4,
        "explicacao_especifica": "Correta. Artigo 19, item 6 do Protocolo de San Salvador de 1988."
      },
      {
        "id": "285eccb9-9c0c-5fe2-b47a-e5f5e21d4cca",
        "questao_id": "c73448be-bf1c-5f19-81d6-883466abe993",
        "letra": "E",
        "texto": "O direito à cultura e a fruição de avanços científicos e tecnológicos.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Excluídos do procedimento direto de petição individual."
      }
    ]
  },
  {
    "id": "c07e40a8-ad7e-5ff1-8449-d94030b030c9",
    "idSlug": "l13-dh-inter-021-cadh-art9-legalidade-estrita-retroatividade-benigna",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O art. 9º da Convenção Americana consagra o princípio da legalidade e da irretroatividade da lei penal, assegurando adicionalmente que, se após a perpetração do delito a lei dispuser a imposição de pena mais leve, o delinquente será por ela beneficiado (retroatividade benigna da lei penal).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 9º da CADH e art. 5º, XL da CF/88: a retroatividade da norma penal mais benéfica é garantia fundamental inderrogável.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8fb1cb3112bb347f6f32b6de6607e3c9a373676bf67d1eae143f6f97d69bb6b7",
    "conceito_principal": "Legalidade e retroatividade da lei penal mais benigna na CADH (Art. 9º)",
    "habilidade_cobrada": "Reconhecer a garantia da novatio legis in mellius sob a perspectiva internacional",
    "tese_ou_regra": "A lei penal posterior mais branda retroage sempre em benefício do imputado",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "6cbfe100-ad8e-5af4-a141-d2a00b2697be",
        "questao_id": "c07e40a8-ad7e-5ff1-8449-d94030b030c9",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "4575c327-addb-56ae-b5d1-643975de805d",
        "questao_id": "c07e40a8-ad7e-5ff1-8449-d94030b030c9",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9a3cd510-0e51-56fa-a651-2f028c1c4c40",
    "idSlug": "l13-dh-inter-022-cadh-art11-protecao-honra-dignidade",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "De acordo com o art. 11 da CADH, toda pessoa tem direito ao respeito de sua honra e ao reconhecimento de sua dignidade, sendo proibidas ingerências arbitrárias ou abusivas em sua vida privada, família, domicílio ou correspondência.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Artigo 11, itens 1 e 2 da Convenção Americana sobre Direitos Humanos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "246f2ba493f8c6be404abdeadc9278f1e3f7ad54797710cc9472f892d7eac7b2",
    "conceito_principal": "Proteção da honra e da dignidade na CADH (Art. 11)",
    "habilidade_cobrada": "Identificar as proteções convencionais à inviolabilidade moral e espacial",
    "tese_ou_regra": "A proteção à honra e a vedação a buscas e ingerências arbitrárias decorrem do art. 11 da CADH",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "f834c335-9e6f-58e5-8d55-fec25df28f63",
        "questao_id": "9a3cd510-0e51-56fa-a651-2f028c1c4c40",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "007eb9ef-956c-503b-b4a8-af82dfd676a8",
        "questao_id": "9a3cd510-0e51-56fa-a651-2f028c1c4c40",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "9800c568-a3bc-5171-9657-3e69b7a87973",
    "idSlug": "l13-dh-inter-023-caso-curado-medidas-corte-superlotacao-presidios",
    "disciplina_id": "ee8e2e17-ceae-5165-932a-76c8bc67a294",
    "assunto_id": "766c2683-7c95-5520-9580-bb23b3f92c57",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "Nas Medidas Provisórias relativas ao Complexo Prisional do Curado (Pernambuco), a Corte Interamericana determinou ao Brasil a contagem em dobro de cada dia de privação de liberdade cumprido sob condições degradantes e superlotação incompatíveis com a dignidade humana, salvo para crimes contra a vida, integridade física e crimes sexuais.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Resolução da Corte IDH de 2018 (Caso Curado): aplicação pioneira do cômputo em dobro da pena por cumprimento em condições degradantes violadoras da CADH.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ffc1f611ac31639fe9f15630df8e2e7194657fcefffb5ed9d5678fa8e1da3a84",
    "conceito_principal": "Caso Complexo Penitenciário do Curado e contagem em dobro da pena pela Corte IDH",
    "habilidade_cobrada": "Compreender os efeitos jurídicos executórios de medidas provisórias da Corte IDH no sistema penal",
    "tese_ou_regra": "Condições prisionais degradantes autorizam a compensação por cômputo temporal mitigado da pena",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "cb7dd4d0-fd1b-5a5c-a312-496248d04059",
        "questao_id": "9800c568-a3bc-5171-9657-3e69b7a87973",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "3fc1d985-f6f1-5813-add0-815c5e7a2c51",
        "questao_id": "9800c568-a3bc-5171-9657-3e69b7a87973",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  }
];
