// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 20

export const m13_questoes = [
  {
    "id": "53a35b6b-716f-50a3-b915-d3d069545a8b",
    "idSlug": "l13-adm-prin-001-limp-legalidade-estrita-particular",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Enquanto para os particulares o princípio da legalidade (art. 5º, II da CF) significa que é permitido fazer tudo o que a lei não proíbe, para a Administração Pública o princípio da legalidade estrita (art. 37, caput da CF) impõe que o administrador público só pode agir quando e como a lei autoriza ou determina.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Princípio clássico do Direito Administrativo que diferencia a autonomia da vontade privada da vinculação positiva à lei na função administrativa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "158068f4a92175e42e4655f7ad3ce883bda54312e9ca48a39ba0ae0a8c7a99bc",
    "conceito_principal": "Princípio da legalidade na Administração Pública",
    "habilidade_cobrada": "Distinguir o princípio da legalidade aplicável aos particulares e à Administração",
    "tese_ou_regra": "A Administração Pública só pode agir secundum legem e intra legem",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "76006be0-24a4-57ba-b4ed-810bc2f0235d",
        "questao_id": "53a35b6b-716f-50a3-b915-d3d069545a8b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "014fdaa1-7383-53c0-ad93-e21142c5b315",
        "questao_id": "53a35b6b-716f-50a3-b915-d3d069545a8b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "046e71d5-78b4-5922-945e-6cffc78ac87c",
    "idSlug": "l13-adm-prin-002-impessoalidade-vedacao-promocao-pessoal",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A publicidade dos atos, programas, obras, serviços e campanhas dos órgãos públicos deverá ter caráter educativo, informativo ou de orientação social, dela não podendo constar nomes, símbolos ou imagens que caracterizem promoção pessoal de autoridades ou servidores públicos, sob pena de violação ao princípio da impessoalidade e eventual ato de improbidade administrativa.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 37, § 1º da CF/88 e jurisprudência pacífica do STF e STJ.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7ec0b816e54abd39a7bcfc0e55d5a534a1afe2ccf03434825c3b2ccf5309da6e",
    "conceito_principal": "Princípio da impessoalidade e vedação à promoção pessoal",
    "habilidade_cobrada": "Reconhecer as vedações constitucionais de autopromoção na publicidade oficial",
    "tese_ou_regra": "A publicidade estatal não pode conter símbolos que personalizem o governante ou servidor",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "4d92e19e-348d-58ca-828f-df0e6af2c79d",
        "questao_id": "046e71d5-78b4-5922-945e-6cffc78ac87c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f6c8538e-197c-5090-9316-95d858bfc267",
        "questao_id": "046e71d5-78b4-5922-945e-6cffc78ac87c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7ce1ca35-6ee9-5006-b308-4bf9280b1705",
    "idSlug": "l13-adm-prin-003-autotutela-sumula-473-stf-revogacao-anulacao",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A Administração Pública pode anular seus próprios atos, quando eivados de vícios que os tornam ilegais, porque deles não se originam direitos; ou revogá-los, por motivo de conveniência ou oportunidade, respeitados os direitos adquiridos e ressalvada, em todos os casos, a apreciação judicial.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Enunciado clássico da Súmula 473 do Supremo Tribunal Federal e art. 53 da Lei nº 9.784/99.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3bcd86d545b7b9ac219b21037a98e62e930d18bf2445fc6bf53976954e492b2b",
    "conceito_principal": "Princípio da autotutela administrativa (Súmula 473 STF)",
    "habilidade_cobrada": "Diferenciar as hipóteses de anulação e revogação de atos administrativos",
    "tese_ou_regra": "A Administração anula atos ilegais e revoga atos inconvenientes por autotutela",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "43e75951-e742-5959-99dc-5bcb542ca465",
        "questao_id": "7ce1ca35-6ee9-5006-b308-4bf9280b1705",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "fedf39ac-20cb-5f72-b643-6b0985578fb0",
        "questao_id": "7ce1ca35-6ee9-5006-b308-4bf9280b1705",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "3bb56e9b-1d8c-5b4d-a0de-7abccf398ed4",
    "idSlug": "l13-adm-pod-004-poder-policia-atributos-autoexecutoriedade",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O poder de polícia administrativa manifesta-se por meio de atributos como a discricionariedade, a autoexecutoriedade e a coercibilidade; a autoexecutoriedade autoriza a Administração a executar diretamente suas decisões sem prévia autorização judicial, estando presente quando expressamente prevista em lei ou quando se tratar de medida urgente de defesa da ordem pública.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina administrativista consagrada (Hely Lopes Meirelles, Maria Sylvia Zanella Di Pietro): a autoexecutoriedade depende de previsão legal expressa ou urgência fática.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6bc9af640cafd607e55442a3a494c4c5d60d3d7063d57306b8f26ec84e97c1c6",
    "conceito_principal": "Atributos do poder de polícia administrativa",
    "habilidade_cobrada": "Identificar os requisitos e limites do atributo da autoexecutoriedade",
    "tese_ou_regra": "A autoexecutoriedade dispensa chancela judicial prévia em situações de urgência ou expressa lei",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "519aecb0-1db7-553a-be9c-b0f8b203630e",
        "questao_id": "3bb56e9b-1d8c-5b4d-a0de-7abccf398ed4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "83922ff8-13ab-5a25-a7e6-95f7f4bde44e",
        "questao_id": "3bb56e9b-1d8c-5b4d-a0de-7abccf398ed4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
    "idSlug": "l13-adm-pod-005-abuso-poder-excesso-desvio-finalidade",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "O abuso de poder é gênero que compreende duas espécies fundamentais: o excesso de poder e o desvio de finalidade (ou desvio de poder). Assinale a opção que descreve corretamente a ocorrência de desvio de finalidade em ato administrativo.",
    "explicacao": "GABARITO: C. O desvio de finalidade ocorre quando o agente atua dentro de sua competência legal, mas busca um fim alheio ao interesse público ou diverso daquele fixado pela lei (vício no elemento finalidade).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0d4abae07186ebfac96f4f39b31055ce5046b48eac698ce5e2e8550b2c9ce57b",
    "conceito_principal": "Espécies de abuso de poder: desvio de finalidade vs excesso de poder",
    "habilidade_cobrada": "Diferenciar desvio de finalidade e excesso de poder na atuação administrativa",
    "tese_ou_regra": "Desvio de finalidade vicia o fim legal do ato mesmo com competência formal do agente",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "f5e01fd7-0279-502f-9998-ea3b8743de36",
        "questao_id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
        "letra": "A",
        "texto": "O agente público pratica ato que extravasa os limites quantitativos ou materiais de sua competência funcional.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Isso caracteriza excesso de poder (vício na competência)."
      },
      {
        "id": "a98240ca-99f7-52b6-9f41-475845216695",
        "questao_id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
        "letra": "B",
        "texto": "O ato administrativo padece de ausência de motivação fática quando esta era expressamente exigida pela norma.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Vício no elemento motivo/forma."
      },
      {
        "id": "33fdb12b-bd31-55df-b398-8d5793d66587",
        "questao_id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
        "letra": "C",
        "texto": "O agente atua formalmente dentro de sua esfera de atribuições, mas pratica o ato visando a interesse privado, perseguição a desafeto ou objetivo diverso daquele determinado pela lei.",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Conceito clássico de desvio de poder/finalidade."
      },
      {
        "id": "7eb99593-64ec-5616-a8ce-a6681094991a",
        "questao_id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
        "letra": "D",
        "texto": "O ato é editado por autoridade desprovida de investidura regular no cargo público.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Trata-se de usurpação de função ou funcionário de fato (vício de competência)."
      },
      {
        "id": "8fb6323d-8e77-534c-b0c7-f56a02443125",
        "questao_id": "cb11b6a8-7bb4-5908-870a-22e87dca2d6d",
        "letra": "E",
        "texto": "A autoridade aplica sanção disciplinar exatamente conforme a gradação objetiva imposta pela lei sem qualquer margem de arbítrio.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Trata-se de ato vinculado perfeitamente lícito."
      }
    ]
  },
  {
    "id": "2e1351d5-1d5d-5fa5-be33-decb12a72307",
    "idSlug": "l13-adm-pod-006-poder-hierarquico-delegacao-avocacao",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Penal",
    "cargo_nome": "Policial Penal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O poder hierárquico confere à autoridade superior a faculdade de distribuir funções, fiscalizar, dar ordens, avocar e delegar competências; segundo a Lei nº 9.784/1999, não podem ser objeto de delegação a edição de atos de caráter normativo, a decisão de recursos administrativos e as matérias de competência exclusiva do órgão ou autoridade.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 13 da Lei nº 9.784/99 (mnemônico CE-NO-RA: Competência Exclusiva, atos Normativos e Recursos Administrativos).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "9411ba35e8fba02a09e48c00721ac5ecd26a2826a4f757dddb32ab68e44b185a",
    "conceito_principal": "Limites da delegação de competência (art. 13 Lei 9.784/99)",
    "habilidade_cobrada": "Identificar as matérias indelegáveis no processo administrativo federal",
    "tese_ou_regra": "Atos normativos, recursos e competências exclusivas não admitem delegação",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "84b7959c-4b68-5a8a-882e-f9cd45897bcb",
        "questao_id": "2e1351d5-1d5d-5fa5-be33-decb12a72307",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "e3a76b5e-0daa-54d9-be51-5a7fdb357841",
        "questao_id": "2e1351d5-1d5d-5fa5-be33-decb12a72307",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "74b2e7ca-b70e-5a3d-af0d-14d21ad33150",
    "idSlug": "l13-adm-pod-007-poder-disciplinar-vinculacao-abertura-pad",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O poder disciplinar é a faculdade atribuída à Administração Pública de apurar infrações e aplicar penalidades funcionais a servidores públicos e a particulares que com ela possuam vínculo jurídico específico, caracterizando-se a instauração do processo disciplinar como um dever vinculado da autoridade que toma ciência de falta funcional.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 143 da Lei nº 8.112/90: a autoridade que tiver ciência de irregularidade no serviço público é obrigada a promover a sua apuração imediata.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d4318c36c55f70506d8860629b51ae4ffc49f7036b8fa59002d98c3a709e754d",
    "conceito_principal": "Poder disciplinar e obrigatoriedade da apuração",
    "habilidade_cobrada": "Compreender a natureza vinculada da instauração de apuração disciplinar",
    "tese_ou_regra": "A instauração de procedimento apuratório é dever vinculado da autoridade competente",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "50d35743-adef-53e9-97c5-eb45adcbd1b1",
        "questao_id": "74b2e7ca-b70e-5a3d-af0d-14d21ad33150",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "89f5076d-32b9-5cb1-adf6-87fee5266b53",
        "questao_id": "74b2e7ca-b70e-5a3d-af0d-14d21ad33150",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b229ddc6-38a7-5633-8aeb-4981a1bdc534",
    "idSlug": "l13-adm-ato-008-elementos-ato-administrativo-competencia-finalidade",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "São elementos ou requisitos de validade indispensáveis a todo ato administrativo a competência, a finalidade, a forma, o motivo e o objeto, sendo a competência, a finalidade e a forma requisitos vinculados por excelência na legislação brasileira.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 2º da Lei nº 4.717/65 (Lei da Ação Popular) e doutrina administrativa consolidada.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "1ee9ad4452f71507cacd3926499f1ac49abfb4ef70c1d62fbaf4ca29046ef832",
    "conceito_principal": "Elementos de validade do ato administrativo (COM-FI-FOR-M-OB)",
    "habilidade_cobrada": "Identificar os elementos vinculados e discricionários dos atos administrativos",
    "tese_ou_regra": "Competência, finalidade e forma são elementos sempre vinculados pela lei",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "6ae216a0-5ceb-5c7e-a667-365e5baf288a",
        "questao_id": "b229ddc6-38a7-5633-8aeb-4981a1bdc534",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "82cb6636-7c2b-5e74-bd9a-e5a6a53c45cf",
        "questao_id": "b229ddc6-38a7-5633-8aeb-4981a1bdc534",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "2934c956-4f11-597d-8d07-1ec325f329d8",
    "idSlug": "l13-adm-ato-009-teoria-motivos-determinantes-vinculacao-motivo",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "De acordo com a teoria dos motivos determinantes, a validade do ato administrativo vincula-se aos motivos fáticos e jurídicos apresentados pela Administração como justificativa para sua edição, de modo que, se tais motivos forem inexistentes, falsos ou juridicamente inadequados, o ato será nulo, ainda que se trate de ato originalmente discricionário cuja motivação não fosse obrigatória.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Teoria dos motivos determinantes amplamente acolhida pela jurisprudência do STF e STJ.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "714857c3714f6d9ea8db4aa391ab6950eb306c733ab4b92254a72250ac8f8ce9",
    "conceito_principal": "Teoria dos motivos determinantes",
    "habilidade_cobrada": "Aplicar a teoria dos motivos determinantes ao controle de nulidade de atos discricionários motivados",
    "tese_ou_regra": "Motivação falsa ou inexistente invalida o ato administrativo discricionário",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "a25de786-7bf0-5cdf-93dc-e6f556449fc5",
        "questao_id": "2934c956-4f11-597d-8d07-1ec325f329d8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ac45c678-6fcf-516a-9771-38c8ded505e2",
        "questao_id": "2934c956-4f11-597d-8d07-1ec325f329d8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
    "idSlug": "l13-adm-ato-010-atributos-ato-administrativo-presuncao-legitimidade",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Soldado da Polícia Militar",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Dentre os atributos do ato administrativo, a presunção de legitimidade e veracidade opera relevantes efeitos de ordem processual e substantiva. A esse respeito, assinale a afirmativa correta.",
    "explicacao": "GABARITO: B. A presunção de legitimidade e veracidade tem caráter relativo (iuris tantum), transferindo o ônus da prova da ilegalidade ou inveracidade para quem impugna o ato administrativo.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6ef1f7f7fca2ed8bd976d7aa6d536a59e70555c1d33f3d4966cebaea72b43501",
    "conceito_principal": "Presunção de legitimidade e veracidade dos atos administrativos",
    "habilidade_cobrada": "Identificar os efeitos da presunção iuris tantum sobre a distribuição do ônus probatório",
    "tese_ou_regra": "A presunção de legitimidade dos atos públicos é relativa e inverte o ônus da prova",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "d3663a58-1dd7-5801-b628-8ac6d7807a3a",
        "questao_id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
        "letra": "A",
        "texto": "Possui caráter absoluto (iuris et de iure), impedindo que o particular conteste em juízo a higidez dos fatos certificados pelo policial.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. A presunção é relativa (iuris tantum)."
      },
      {
        "id": "2c1bacac-6010-5b1a-a0b9-7f34cfaef2f0",
        "questao_id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
        "letra": "B",
        "texto": "Tem natureza relativa (iuris tantum), invertendo o ônus da prova em desfavor do administrado que alega a irregularidade do ato.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Os atos presumem-se válidos e verdadeiros até prova em contrário produzida pelo particular."
      },
      {
        "id": "ae247a6d-0993-5cc5-8947-1999e95333e8",
        "questao_id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
        "letra": "C",
        "texto": "Exige que a Administração Pública ajuíze ação judicial declaratória prévia antes de executar qualquer multa de trânsito.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A presunção de legitimidade permite a execução direta do ato administrativo."
      },
      {
        "id": "0ea6720e-097b-552d-b35f-1bba5c2cad9b",
        "questao_id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
        "letra": "D",
        "texto": "Aplica-se unicamente aos atos administrativos enunciativos, sendo vedada em atos punitivos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. É atributo comum a todas as categorias de atos administrativos."
      },
      {
        "id": "a52d43dd-8963-523c-b3a8-d0bab5bf83c6",
        "questao_id": "d6b9519e-5577-5a3c-8bc0-2781ecdac7e0",
        "letra": "E",
        "texto": "Desaparece automaticamente sempre que o administrado interpõe recurso administrativo tempestivo.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A presunção se mantém vigente durante o curso recursal, ressalvado efeito suspensivo concedido."
      }
    ]
  },
  {
    "id": "ed7c1c30-1cee-538c-8924-9c6e306bc99b",
    "idSlug": "l13-adm-ato-011-convalidação-requisitos-vicios-sanaveis",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A convalidação (ou sanatória) é o ato administrativo pelo qual a Administração supre vício de ato ilegal com efeitos retroativos (ex tunc), sendo juridicamente admitida apenas quando o vício residir na competência (desde que não exclusiva) ou na forma (quando não essencial à validade do ato), desde que não cause lesão ao interesse público nem prejuízo a terceiros.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 55 da Lei nº 9.784/99: convalidação opera ex tunc sobre competência não privativa e forma não essencial.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "658feaf91e4ad3f982200b5c7fba3f87164a66bca6377c66458a0adcd7edd8f6",
    "conceito_principal": "Convalidação de atos administrativos e requisitos do art. 55 da Lei 9.784/99",
    "habilidade_cobrada": "Distinguir vícios sanáveis e insanáveis para fins de convalidação",
    "tese_ou_regra": "Convalidação retroage e só incide sobre competência não exclusiva e forma não solene",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "2efc4312-768f-5123-9820-e07c87a22bc0",
        "questao_id": "ed7c1c30-1cee-538c-8924-9c6e306bc99b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "be236bd7-cf2d-5393-8a60-7120fbe108c9",
        "questao_id": "ed7c1c30-1cee-538c-8924-9c6e306bc99b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "1bde50f2-7e0f-51e5-b0db-3da4becfcab1",
    "idSlug": "l13-adm-prin-012-seguranca-juridica-prazo-decadencial-5-anos",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O direito da Administração de anular os atos administrativos de que decorram efeitos favoráveis para os destinatários decai em cinco anos, contados da data em que foram praticados, salvo comprovada má-fé, em homenagem ao princípio da segurança jurídica e da proteção à confiança legítima.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 54 da Lei Federal nº 9.784/99.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2294dad92819ddea1c3d6960e0b54e7f15e671defdad5f0fe8dbff8a3a8342e3",
    "conceito_principal": "Decadência quinquenal da autotutela e proteção da confiança",
    "habilidade_cobrada": "Reconhecer o prazo decadencial de anulação de atos favoráveis e a ressalva de má-fé",
    "tese_ou_regra": "A autotutela decai em 5 anos para atos favoráveis, ressalvada má-fé do beneficiário",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "14fabbf9-1299-53a9-892c-ad7734d5e092",
        "questao_id": "1bde50f2-7e0f-51e5-b0db-3da4becfcab1",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "1bc0db8f-7523-55b6-9916-6f2422bf6e18",
        "questao_id": "1bde50f2-7e0f-51e5-b0db-3da4becfcab1",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0f630f59-209b-5ae7-b79e-9c85afabc488",
    "idSlug": "l13-adm-pod-013-policia-judiciaria-vs-policia-administrativa",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "A polícia administrativa atua preponderantemente de forma preventiva, incidindo sobre bens, direitos e atividades para condicionar seu uso ao bem-estar coletivo, ao passo que a polícia judiciária atua preponderantemente de forma repressiva, incidindo diretamente sobre indivíduos para apurar infrações penais e colher elementos de autoria e materialidade.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Distinção doutrinária clássica entre polícia administrativa e polícia judiciária.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0a6d7c72a1dee878ca7f20840556dd8c8ac164b2aa991d6be7eac10d0c78fc9b",
    "conceito_principal": "Distinção entre polícia administrativa e polícia judiciária",
    "habilidade_cobrada": "Diferenciar a natureza, objeto e incidência das polícias administrativa e judiciária",
    "tese_ou_regra": "Polícia administrativa incide sobre atividades/bens; polícia judiciária incide sobre pessoas na persecução criminal",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "e677a7ed-0756-5565-8bab-04cc9a44525d",
        "questao_id": "0f630f59-209b-5ae7-b79e-9c85afabc488",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "629d2098-3669-5864-aa7e-3d0b72e7d643",
        "questao_id": "0f630f59-209b-5ae7-b79e-9c85afabc488",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "97707a55-32c9-5cb5-a74f-4c1a96715eb7",
    "idSlug": "l13-adm-ato-014-imperatividade-atos-negociais-enunciativos",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A imperatividade é o atributo pelo qual os atos administrativos se impõem a terceiros independentemente de sua concordância; todavia, a imperatividade não está presente em todos os atos administrativos, inexistindo, por exemplo, nos atos negociais (como licenças e autorizações) e nos atos meramente enunciativos (como certidões e pareceres).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina administrativista majoritária (Di Pietro e Celso Antônio Bandeira de Mello): nem todo ato possui imperatividade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "74afc7c3a43f7c01ea258aaa909b62ac92b7137df016e4324b4935dbdbfba34d",
    "conceito_principal": "Atributo da imperatividade e suas exceções",
    "habilidade_cobrada": "Reconhecer os atos administrativos desprovidos do atributo da imperatividade",
    "tese_ou_regra": "Imperatividade não existe em atos negociais e enunciativos",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a84e143e-6ecc-5a94-93fb-4c0d2fa71368",
        "questao_id": "97707a55-32c9-5cb5-a74f-4c1a96715eb7",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "29012d9a-40ad-574a-8ee9-b43fdc3b03ed",
        "questao_id": "97707a55-32c9-5cb5-a74f-4c1a96715eb7",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
    "idSlug": "l13-adm-prin-015-nepotismo-sumula-vinculante-13-cargos-politicos",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A Súmula Vinculante nº 13 do Supremo Tribunal Federal veda a nomeação de cônjuge, companheiro ou parente em linha reta, colateral ou por afinidade, até o terceiro grau, para cargo em comissão ou de confiança. A respeito da incidência dessa súmula em cargos de natureza eminentemente política (ex.: Secretários de Estado ou Ministros de Estado), assinale a afirmativa correta segundo o STF.",
    "explicacao": "GABARITO: E. A Súmula Vinculante 13 não se aplica automaticamente à nomeação para cargos políticos, salvo se restar demonstrada inequívoca falta de qualificação técnica ou intuito de fraude/nepotismo cruzado.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f2f905c207c808e45f7e420f1b33dbba531a0da11f0b63c0a9b90a032fe02da5",
    "conceito_principal": "Súmula Vinculante 13 e aplicação a agentes e cargos políticos",
    "habilidade_cobrada": "Analisar as exceções da Súmula Vinculante 13 fixadas pelo STF para cargos políticos",
    "tese_ou_regra": "Cargos políticos não se submetem à SV 13 em regra, salvo falta de qualificação técnica ou fraude",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "a0793984-afe3-5735-90bb-5affdd7df7f1",
        "questao_id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
        "letra": "A",
        "texto": "Aplica-se indistintamente com anulação automática de toda nomeação ministerial de parentes.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Cargos políticos possuem excepcionalidade reconhecida pelo STF."
      },
      {
        "id": "884cd922-fcbf-551a-84e4-ecfa27ae6424",
        "questao_id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
        "letra": "B",
        "texto": "Não se aplica a nenhum cargo da administração pública municipal, apenas à esfera federal.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Aplica-se a todos os poderes de todos os entes federativos."
      },
      {
        "id": "6169cc59-5da0-52f0-b395-831b97773fc9",
        "questao_id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
        "letra": "C",
        "texto": "Autoriza o nepotismo cruzado quando envolve poderes distintos no mesmo município.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. A SV 13 veda expressamente designações recíprocas (nepotismo cruzado)."
      },
      {
        "id": "1b087844-2564-53e3-b89d-c25118de728c",
        "questao_id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
        "letra": "D",
        "texto": "Impede o cônjuge de ser aprovado em concurso público de provas e títulos.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. O concurso público é forma constitucional de provimento efetivo e não constitui nepotismo."
      },
      {
        "id": "108cbfb7-9930-5341-b9ec-e283ec384528",
        "questao_id": "d96761f7-5bc6-5837-8c99-fa120bf9892c",
        "letra": "E",
        "texto": "A vedação não alcança, em regra, a nomeação para cargos políticos (como Secretários de Estado ou Municipais), ressalvados os casos de patente inaptidão técnica ou fraude manifesta à lei.",
        "correta": true,
        "ordem": 5,
        "explicacao_especifica": "Correta. Jurisprudência pacífica do Plenário do STF (Rcl 29.033 e Rcl 22.339)."
      }
    ]
  },
  {
    "id": "bef9e4da-8636-5892-9343-6bed656b8d67",
    "idSlug": "l13-adm-ato-016-cassacao-caducidade-contraposicao-extincao",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Militar",
    "cargo_nome": "Oficial da Polícia Militar",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A cassação é a forma de extinção do ato administrativo decorrente do descumprimento superveniente, pelo beneficiário, das condições legais ou regulamentares que permitiam a manutenção do ato, como ocorre quando o titular de uma licença policial passa a utilizá-la para fins ilícitos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina de Direito Administrativo: cassação decorre de culpa/ilegalidade superveniente do particular beneficiário.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "fc16569038f9d0a98b77739150e6ef373672c711cdc784c546877e48d5231443",
    "conceito_principal": "Extinção do ato administrativo por cassação",
    "habilidade_cobrada": "Identificar as causas de cassação, caducidade e anulação de atos administrativos",
    "tese_ou_regra": "A cassação extingue o ato quando o beneficiário descumpre requisitos de manutenção",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "fa76ff74-7837-5c00-be0c-e55fe257fed9",
        "questao_id": "bef9e4da-8636-5892-9343-6bed656b8d67",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ad7b5372-9bc7-577d-8d77-e24ed94e5a14",
        "questao_id": "bef9e4da-8636-5892-9343-6bed656b8d67",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "5c46627d-105f-5f79-84e3-f5298b72cc94",
    "idSlug": "l13-adm-pod-017-poder-regulamentar-decreto-autonomo-art84",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "O Chefe do Poder Executivo dispõe de competência para editar decretos autônomos para dispor sobre a organização e funcionamento da administração federal quando não implicar aumento de despesa nem criação ou extinção de órgãos públicos, bem como para a extinção de funções ou cargos públicos quando vagos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Art. 84, VI, 'a' e 'b' da CF/88 (introduzido pela EC 32/2001).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a47a2f80d3883c6c8dc51494881768d72a51cbe6216f9dee8fb4733762d3cb70",
    "conceito_principal": "Decreto autônomo e limites do art. 84, VI da CF/88",
    "habilidade_cobrada": "Identificar as matérias passíveis de disciplina por decreto autônomo",
    "tese_ou_regra": "Decreto autônomo organiza a administração sem criar órgãos/despesas e extingue cargos vagos",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "56925190-e587-5e34-8b0c-41faec996c5d",
        "questao_id": "5c46627d-105f-5f79-84e3-f5298b72cc94",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "cdcb9a06-a2fb-560d-90b2-89d0a423af9c",
        "questao_id": "5c46627d-105f-5f79-84e3-f5298b72cc94",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f28704c4-3992-5a08-ad5a-795a985a6ece",
    "idSlug": "l13-adm-prin-018-continuidade-servico-publico-greve-policiais",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "e45db358-4e84-595b-9769-2957d83a9e54",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O princípio da continuidade do serviço público fundamenta a tese consolidada pelo STF no Tema 541 (ARE 654.432), segundo a qual o exercício do direito de greve, sob qualquer forma ou modalidade, é expressamente vedado a todos os servidores públicos que atuem diretamente na área de segurança pública.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Tese do STF no Tema 541 de repercussão geral: proibição absoluta de greve para policiais civis, federais, rodoviários e agentes penitenciários.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5ff9508c70a70a7d8e1ae1741e603837b5ff5a62d41763617ade73a0cffc496e",
    "conceito_principal": "Vedação ao direito de greve para carreiras de segurança pública (STF Tema 541)",
    "habilidade_cobrada": "Aplicar a tese vinculante do STF sobre a inconstitucionalidade da greve policial",
    "tese_ou_regra": "É inconstitucional a greve de servidores públicos da segurança pública",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "8cf35b8c-f450-5d5e-8e12-5324cf8ced9d",
        "questao_id": "f28704c4-3992-5a08-ad5a-795a985a6ece",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "b27b7671-6831-54c3-a913-0dfd5af4e8cb",
        "questao_id": "f28704c4-3992-5a08-ad5a-795a985a6ece",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f2af3d02-9075-5891-b2a6-8dd78e5b3330",
    "idSlug": "l13-adm-ato-019-silencio-administrativo-efeitos",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "50f75ddd-0ec6-5666-b08f-fa2179657fe1",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O silêncio administrativo não consubstancia, em regra, ato administrativo, mas fato administrativo omissivo, não gerando deferimento tácito de pretensões do particular, salvo quando houver expressa e específica previsão legislativa atribuindo efeito confirmatório à inércia do órgão público.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Doutrina clássica: o silêncio da administração é fato omissivo e depende de lei expressa para produzir efeitos positivos.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "b6d521ad92d38d81181b023fd89c23154dca90e0b4b365b4aa30e0fe1accd026",
    "conceito_principal": "Natureza jurídica do silêncio administrativo",
    "habilidade_cobrada": "Compreender os efeitos materiais e processuais da omissão administrativa",
    "tese_ou_regra": "Silêncio administrativo é fato omissivo e só gera deferimento se previsto em lei",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "87a8e939-58da-5c3a-a73f-16741c95602e",
        "questao_id": "f2af3d02-9075-5891-b2a6-8dd78e5b3330",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "bcc3e2d8-02c7-5fa0-8a55-54990887aa00",
        "questao_id": "f2af3d02-9075-5891-b2a6-8dd78e5b3330",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
    "idSlug": "l13-adm-pod-020-reserva-administracao-merito-controle-judicial",
    "disciplina_id": "0ba958a0-7e2b-5f29-aec6-9578fa2d6b1c",
    "assunto_id": "983f1a52-f054-5492-8318-d892e697f8f7",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "A respeito dos limites do controle jurisdicional sobre o mérito do ato administrativo discricionário, assinale a opção que reflete com exatidão a orientação predominante no Supremo Tribunal Federal e no Superior Tribunal de Justiça.",
    "explicacao": "GABARITO: A. O Poder Judiciário não pode substituir os critérios de conveniência e oportunidade do administrador público, mas pode anular atos discricionários que violem os princípios da proporcionalidade, razoabilidade, legalidade e moralidade.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "23743005c1ded9213798c604f574fc866c98aaec2d996f247860eec86f798fd9",
    "conceito_principal": "Controle judicial do mérito e limites da discricionariedade",
    "habilidade_cobrada": "Analisar o alcance do controle judicial de atos discricionários sob a ótica da proporcionalidade",
    "tese_ou_regra": "O Judiciário controla a razoabilidade e legalidade do ato discricionário sem substituir seu mérito legítimo",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "466166f4-c594-560d-8d14-5fd727e97c17",
        "questao_id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
        "letra": "A",
        "texto": "O Judiciário não pode substituir a valoração de conveniência e oportunidade do administrador, mas pode anular atos discricionários que transgridam a razoabilidade, a proporcionalidade ou a legalidade.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. Jurisprudência pacífica do STF e STJ sobre controle de legalidade ampla e proporcionalidade."
      },
      {
        "id": "9a5df6e2-752f-5bca-a7c9-8430ebf4b958",
        "questao_id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
        "letra": "B",
        "texto": "O mérito administrativo é imune a qualquer fiscalização judicial, mesmo quando verificada manifesta desproporção ou arbitrariedade flagrante.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. A desproporcionalidade manifesta enseja vício de legalidade passível de anulação judicial."
      },
      {
        "id": "95424346-7900-561d-bf5d-7aec43c0fda7",
        "questao_id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
        "letra": "C",
        "texto": "O juiz pode alterar a sanção disciplinar imposta pela autoridade administrativa por mera divergência de política punitiva.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. O Judiciário não comuta nem altera sanções discricionárias legais; limita-se a anular quando ilegais."
      },
      {
        "id": "1a19172c-dab5-558e-99f1-f487f84a4756",
        "questao_id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
        "letra": "D",
        "texto": "A discricionariedade confere ao gestor policial imunidade perante a ação de improbidade administrativa.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Atos discricionários dolosos lesivos ao erário submetem-se plenamente à LIA."
      },
      {
        "id": "0b872bbd-c323-5194-a7fb-bfa03436d4cd",
        "questao_id": "956a16a4-8e94-53a1-aacf-1ed4d9b77e6e",
        "letra": "E",
        "texto": "O mandado de segurança é a única via admitida para o exame do mérito administrativo pelo Poder Judiciário.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Ações ordinárias e populares também exercem controle de validade dos atos."
      }
    ]
  }
];
