// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 15

export const m21_questoes = [
  {
    "id": "fc386dce-fecc-5785-9722-dba5aaa6466a",
    "idSlug": "l13-port-sint-001-concordancia-verbo-haver-tempo-existir",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "No trecho 'Havia muitos indícios de fraude contábil nos relatórios periciais', o verbo 'haver' foi empregado como impessoal no sentido de 'existir', motivo pelo qual deve permanecer compulsoriamente flexionado na terceira pessoa do singular, constituindo erro gramatical a sua flexão para 'Haviam'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O verbo 'haver' com sentido de 'existir' ou 'ocorrer' é impessoal (oração sem sujeito) e conjuga-se exclusivamente na 3ª pessoa do singular.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "05ae817cd2831aeffeee086e9c10c6c6830d71c9137c023af67b5254cdd8eecb",
    "conceito_principal": "Impessoalidade do verbo 'haver' no sentido de 'existir'",
    "habilidade_cobrada": "Reconhecer as regras de concordância com orações sem sujeito e verbos impessoais",
    "tese_ou_regra": "O verbo haver com sentido de existir é impessoal e não flexiona no plural",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "01c893e1-76d1-565c-93e4-3701ae8213be",
        "questao_id": "fc386dce-fecc-5785-9722-dba5aaa6466a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "1d095b8f-f995-519d-a7d3-b08837e4da7a",
        "questao_id": "fc386dce-fecc-5785-9722-dba5aaa6466a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "4591d87a-dad9-5de8-b9b4-cdca8ef86d60",
    "idSlug": "l13-port-sint-002-voz-passiva-sintetica-particula-se-plural",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na frase 'Apuraram-se os crimes de lavagem de dinheiro após a quebra de sigilo', a partícula 'se' atua como pronome apassivador (partícula apassivadora), sendo a locução 'os crimes de lavagem de dinheiro' o sujeito paciente da oração, o que torna obrigatória a concordância do verbo no plural.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Em 'Apuraram-se os crimes', 'os crimes' é sujeito paciente em voz passiva sintética (equivalente a 'os crimes foram apurados'), exigindo verbo no plural.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cfad2f7219b678c8fd4f6bb425cfb9b99fa02018f96fc9810bb6ca606d169439",
    "conceito_principal": "Voz Passiva Sintética e Partícula Apassivadora 'se'",
    "habilidade_cobrada": "Identificar o sujeito paciente e aplicar a concordância verbal obrigatória",
    "tese_ou_regra": "Na voz passiva sintética com partícula apassivadora o verbo concorda com o sujeito paciente",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "8cf89e85-0847-59ca-8dad-932c1ef022bd",
        "questao_id": "4591d87a-dad9-5de8-b9b4-cdca8ef86d60",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "37e8864c-d3c4-5f4d-9549-19af3ea6dcfa",
        "questao_id": "4591d87a-dad9-5de8-b9b4-cdca8ef86d60",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f9dadb89-87fd-57d3-b081-1ed1055a35eb",
    "idSlug": "l13-port-sint-003-crase-locucoes-femininas-a-disposicao",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O emprego do sinal indicativo de crase é obrigatório em locuções prepositivas e adverbiais femininas, a exemplo de 'à disposição da Justiça', 'às pressas' e 'à medida que'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Locuções adverbiais, prepositivas e conjuntivas formadas por palavras femininas exigem crase de forma canônica.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "8b4ed5f42f43344e80b8a14eebdeb6d8993e64076f578961348ac3859f21c3a3",
    "conceito_principal": "Crase obrigatória em locuções prepositivas, adverbiais e conjuntivas femininas",
    "habilidade_cobrada": "Identificar as regras fixas de acentuação grave em locuções estruturais",
    "tese_ou_regra": "Locuções femininas levam acento grave indicativo de crase obrigatoriamente",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "45ffbc0b-4216-5659-b24f-961dc789bff1",
        "questao_id": "f9dadb89-87fd-57d3-b081-1ed1055a35eb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "062ed0fc-3c0c-544f-9633-f6bcf374b4ca",
        "questao_id": "f9dadb89-87fd-57d3-b081-1ed1055a35eb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f178ef81-2019-56c2-bc6f-3cee81c45d1d",
    "idSlug": "l13-port-sint-004-regencia-verbo-implicar-transitivo-direto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "De acordo com a norma-padrão da língua portuguesa, o verbo 'implicar', no sentido de 'acarretar' ou 'trazer como consequência', é transitivo direto e dispensa o emprego da preposição 'em', estando gramaticalmente correta a oração: 'A adulteração do chassi implicará a apreensão imediata do veículo'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O verbo implicar (acarretar) é VTD: 'implicará a apreensão' (e NÃO 'implicará na apreensão').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "163f538513e8d51787a89d7ecb6ab9232a67e49f28c02e62185a73eef57bd0ab",
    "conceito_principal": "Regência do verbo 'implicar' no sentido de acarretar (Transitivo Direto)",
    "habilidade_cobrada": "Corrigir desvios comuns de regência verbal em relatórios oficiais",
    "tese_ou_regra": "O verbo implicar no sentido de acarretar rege complemento sem preposição 'em'",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "5b6c4bd0-4b9e-5b6a-8851-ef8c54149ab0",
        "questao_id": "f178ef81-2019-56c2-bc6f-3cee81c45d1d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9c79f156-98d0-5272-bc23-aad2fb20aa58",
        "questao_id": "f178ef81-2019-56c2-bc6f-3cee81c45d1d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
    "idSlug": "l13-port-sint-005-crase-casos-proibidos-verbos-masculino",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Assinale a alternativa em que o sinal indicativo de crase foi empregado em estrita conformidade com a norma-padrão da língua culta.",
    "explicacao": "GABARITO: D. 'Os agentes dirigiram-se à delegacia central': 'dirigir-se' rege preposição 'a' + artigo definido feminino 'a' de 'delegacia central' = 'à'. Nas demais: A (a pé = masculino proibido), B (a partir = verbo proibido), C (a todas = pronome indefinido proibido), E (a uma = artigo indefinido proibido).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f76e0dd615b1dcc14d46982443bd83f6e3b39ee3fb4488185391b7e89362ab59",
    "conceito_principal": "Emprego Correto do Sinal Indicativo de Crase e Casos de Proibição",
    "habilidade_cobrada": "Diferenciar contextos legítimos de crase frente a casos proibidos",
    "tese_ou_regra": "A crase resulta da fusão de preposição 'a' com artigo 'a', inadmitida antes de verbo ou masculino",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "843ae5d7-7386-5c4b-9919-bf1ba53d63a5",
        "questao_id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
        "letra": "A",
        "texto": "Os policiais realizaram a patrulha à pé durante a madrugada.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. 'Pé' é palavra masculina, proibindo a crase."
      },
      {
        "id": "6f69fbd8-6188-5f21-b910-cacb2c67dac0",
        "questao_id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
        "letra": "B",
        "texto": "A fiscalização terá início à partir das oito horas da manhã.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Antes de verbo no infinitivo ('partir') a crase é proibida."
      },
      {
        "id": "856118e1-e85d-5a5f-bce4-14434ab1aed2",
        "questao_id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
        "letra": "C",
        "texto": "O delegado prestou esclarecimentos à todas as testemunhas presentes.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Antes de pronome indefinido ('todas') a crase é proibida."
      },
      {
        "id": "87207395-ad8d-5d14-8692-07593df83717",
        "questao_id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
        "letra": "D",
        "texto": "Os agentes dirigiram-se à delegacia central para lavrar o flagrante.",
        "correta": true,
        "ordem": 4,
        "explicacao_especifica": "Correta. Regência de 'dirigir-se a' + artigo feminino 'a delegacia'."
      },
      {
        "id": "c2b340b3-7881-519c-b9a2-d3769727186e",
        "questao_id": "6722019b-d17f-51c9-94c2-cdf1e4441667",
        "letra": "E",
        "texto": "A vítima foi conduzida à uma unidade hospitalar com urgência.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Antes do artigo indefinido 'uma' não ocorre crase."
      }
    ]
  },
  {
    "id": "f6aad881-4ce0-51f4-9963-915c40bd2513",
    "idSlug": "l13-port-sint-006-regencia-verbo-aspirar-visar-sentidos",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O verbo 'aspirar', quando empregado com o significado de 'almejar' ou 'pretender' (ex.: 'O candidato aspira ao cargo de Perito Criminal Federal'), rege a preposição 'a' (transitivo indireto); já com o significado de 'sorver' ou 'inalar' (ex.: 'O policial aspirou o gás lacrimogêneo'), é transitivo direto e não exige preposição.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Aspirar = inalar (VTD) / almejar (VTI prep 'a'). Diferenciação semântica clássica da regência verbal.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2abb3329765429b5d0ec38718fa23050bc59ee6e416d7f19cfe41b9f01329380",
    "conceito_principal": "Regência Semântica do verbo 'aspirar' (Inalar vs Almejar)",
    "habilidade_cobrada": "Distinguir a transitividade de verbos com dupla acepção semântica",
    "tese_ou_regra": "Aspirar no sentido de almejar é transitivo indireto com preposição 'a'",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "63f83766-8760-5cd2-b6fe-4b26b34d30fd",
        "questao_id": "f6aad881-4ce0-51f4-9963-915c40bd2513",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "efd382a9-6085-5ae2-9763-022f70cd7b2a",
        "questao_id": "f6aad881-4ce0-51f4-9963-915c40bd2513",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "74a903c3-9d67-51b6-927c-3ee0129fb165",
    "idSlug": "l13-port-sint-007-concordancia-nominal-anexo-bastante-meio",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Na frase 'Seguem anexos os laudos periciais e inclusas as certidões criminais', as palavras 'anexos' e 'inclusas' funcionam como adjetivos e concordam em gênero e número com os respectivos substantivos a que se referem, ao passo que a locução 'em anexo' seria invariável caso tivesse sido utilizada.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. 'Anexo/incluso' flexiona com o substantivo. A locução adverbial 'em anexo' permanece invariável.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "02f4a285243379d38ab07d83411ae76f75f9947b7cd83e5089875e862bbbc151",
    "conceito_principal": "Concordância Nominal: Adjetivos 'anexo/incluso' vs Locução 'em anexo'",
    "habilidade_cobrada": "Aplicar a concordância nominal culta em expedientes policiais",
    "tese_ou_regra": "'Anexo' adjetivo varia em gênero e número; 'em anexo' locução adverbial é invariável",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "f1a67742-e105-562a-a82e-a4f92f0648da",
        "questao_id": "74a903c3-9d67-51b6-927c-3ee0129fb165",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "9972050c-417b-5070-82e6-51d2e14cbe1f",
        "questao_id": "74a903c3-9d67-51b6-927c-3ee0129fb165",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "ab9a1dd3-e245-596c-918b-d5bd4265c72c",
    "idSlug": "l13-port-sint-008-crase-facultativa-possessivo-feminino-singular",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na oração 'O inspetor comunicou o fato a sua equipe / à sua equipe', o emprego do sinal indicativo de crase diante do pronome possessivo feminino singular ('sua') é estritamente facultativo na norma-padrão.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Diante de pronomes possessivos femininos no singular (minha, tua, sua, nossa, vossa), o uso do artigo é facultativo, tornando a crase facultativa.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "555c3dc574f2d8728eb78b2cc596e5a20782cdf43d2832b1570edef4243464a8",
    "conceito_principal": "Crase Facultativa antes de Pronome Possessivo Feminino no Singular",
    "habilidade_cobrada": "Identificar os casos facultativos de crase na norma culta",
    "tese_ou_regra": "Antes de possessivo feminino singular o artigo é facultativo e a crase é opcional",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "d75d7986-ba16-5a7f-b801-943623bb7109",
        "questao_id": "ab9a1dd3-e245-596c-918b-d5bd4265c72c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "a0768ecc-731c-5f17-a734-5397ab035a94",
        "questao_id": "ab9a1dd3-e245-596c-918b-d5bd4265c72c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "eb29389f-dc1e-559f-9011-69cfd5d4e1e2",
    "idSlug": "l13-port-sint-009-regencia-verbo-obedecer-transitivo-indireto",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "De acordo com a norma culta, o verbo 'obedecer' é transitivo indireto e rege a preposição 'a', sendo gramaticalmente incorreta a construção 'O motorista não obedeceu o sinal de parada', devendo-se redigir: 'O motorista não obedeceu ao sinal de parada'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Obedecer e desobedecer exigem preposição 'a' (obedecer a algo/alguém).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "f4f1d616eb3a9409828e0923b1097a156c50462ea5e736b85a1380817b2ef0cb",
    "conceito_principal": "Regência dos verbos 'obedecer' e 'desobedecer' (Transitivos Indiretos)",
    "habilidade_cobrada": "Identificar a transitividade indireta obrigatória de 'obedecer'",
    "tese_ou_regra": "O verbo obedecer rege obrigatoriamente a preposição 'a' perante a norma-padrão",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "925bc371-718d-5f3e-8ffe-5e60c55cad4f",
        "questao_id": "eb29389f-dc1e-559f-9011-69cfd5d4e1e2",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "75bdb805-4ae7-5d78-84ed-9ce2cb91bf67",
        "questao_id": "eb29389f-dc1e-559f-9011-69cfd5d4e1e2",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
    "idSlug": "l13-port-sint-010-concordancia-verbal-sujeito-partitivo",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Considere a frase: 'A maioria dos policiais militares __________ (comparecer) à solenidade de condecoração ontem'. Segundo as regras de concordância verbal da norma-padrão, quais formas verbais preenchem correta e facultativamente a lacuna?",
    "explicacao": "GABARITO: C. Com expressões partitivas (a maioria de, a maior parte de, grande número de) seguidas de adjunto no plural, a concordância é facultativa: pode concordar no singular com o núcleo partitivo ('compareceu') ou no plural por atração com o adjunto ('compareceram').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "6fc6aeb2c1c78a07adbaafee5bc079e46381632e7375882fc8d101b7ad8d057e",
    "conceito_principal": "Concordância Verbal com Expressões Partitivas (Núcleo Singular + Adjunto Plural)",
    "habilidade_cobrada": "Aplicar a dupla possibilidade de concordância em sujeitos partitivos",
    "tese_ou_regra": "Expressões partitivas admitem concordância lógica com o núcleo ou atrativa com o especificador",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c7d36589-5b6d-52d6-9c56-bfb6e02ea5b6",
        "questao_id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
        "letra": "A",
        "texto": "Apenas 'compareceu', sendo o plural absolutamente proibido pela gramática tradicional.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. A concordância atrativa com 'policiais militares' é legítima."
      },
      {
        "id": "8f7830cf-5a75-5c4b-9046-bf743c77459a",
        "questao_id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
        "letra": "B",
        "texto": "Apenas 'compareceram', pois o sujeito é gramaticalmente classificado como composto.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. O sujeito é simples com núcleo partitivo."
      },
      {
        "id": "574e73fd-8ece-540c-a3a9-eebf0e03e9e9",
        "questao_id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
        "letra": "C",
        "texto": "Tanto 'compareceu' (concordância lógica com o núcleo 'maioria') quanto 'compareceram' (concordância atrativa com 'policiais militares').",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. Regra canônica da concordância com expressões partitivas."
      },
      {
        "id": "c39acea5-4a65-5905-99b3-0bb250d85ed0",
        "questao_id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
        "letra": "D",
        "texto": "Apenas 'haviam comparecido', sendo obrigatório o particípio no singular.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Desvia do tempo verbal solicitado e erra no auxiliar."
      },
      {
        "id": "ac18ab2e-c669-5ade-bd4a-7b5ddd2505ae",
        "questao_id": "0af64ea4-68a8-5235-b054-ec7de58a620a",
        "letra": "E",
        "texto": "Nenhuma forma flexionada, devendo o verbo permanecer obrigatoriamente no infinitivo impessoal.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A oração exige verbo conjugado no pretérito perfeito."
      }
    ]
  },
  {
    "id": "0f6e0cae-be5a-5c94-a9f3-738331b23f56",
    "idSlug": "l13-port-sint-011-concordancia-verbo-fazer-tempo-decorrido",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O verbo 'fazer', quando empregado na indicação de tempo transcorrido ou fenômenos climáticos, é impessoal e não admite flexão no plural, estando correta a redação: 'Faz cinco anos que a investigação foi instaurada'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. 'Fazer' indicando tempo decorrido é impessoal (faz cinco anos, e NUNCA 'fazem cinco anos').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ce9b6c1200f9d38d44d6304b55092d30f99c201329eb3cc98489263dc0fb917f",
    "conceito_principal": "Impessoalidade do verbo 'fazer' na indicação de tempo decorrido",
    "habilidade_cobrada": "Reconhecer a invariabilidade de 'fazer' em orações temporais",
    "tese_ou_regra": "O verbo fazer que indica tempo transcorrido não flexiona para o plural",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "b1b40b9e-87a9-5bec-8eec-22f6b399e3ee",
        "questao_id": "0f6e0cae-be5a-5c94-a9f3-738331b23f56",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "40d9210f-452e-57a1-bfff-0ca98f7c4785",
        "questao_id": "0f6e0cae-be5a-5c94-a9f3-738331b23f56",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "96a7f1dc-91d7-542a-b3f9-e3c0bad698d8",
    "idSlug": "l13-port-sint-012-regencia-verbo-preferir-bitransitivo-sem-mais",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O verbo 'preferir' é transitivo direto e indireto, exigindo a preposição 'a' para introduzir o segundo termo, sendo contrária à norma culta a utilização de termos intensificadores ou locuções comparativas como 'mais', 'antes' ou 'do que' (ex.: correto: 'O policial prefere o treinamento tático à rotina burocrática').",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Prefere-se X a Y (nunca 'prefere mais X do que Y'). O acento de crase em 'à rotina' decorre da preposição 'a' + artigo 'a'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "037a08268cea0df1182e9001bd946b1ea00c145278c2227419e0449d553e3ec9",
    "conceito_principal": "Regência do verbo 'preferir' (Preferir X a Y)",
    "habilidade_cobrada": "Expurgar pleonasmos e construções comparativas inadequadas com o verbo preferir",
    "tese_ou_regra": "O verbo preferir rege a preposição 'a' e repele 'do que' ou intensificadores",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "74177f30-5cd9-5118-979f-25246f5dc6d5",
        "questao_id": "96a7f1dc-91d7-542a-b3f9-e3c0bad698d8",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7655f784-6850-5804-a5a0-e44dda942a37",
        "questao_id": "96a7f1dc-91d7-542a-b3f9-e3c0bad698d8",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "4e5475fb-1a87-524e-bf9a-1cf6d41919ec",
    "idSlug": "l13-port-sint-013-crase-pronomes-demonstrativos-aquele-aquilo",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "2eb8117f-c746-5029-9842-dcd698598a16",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Ocorre crase quando a preposição 'a', exigida por um termo regente anterior, funde-se com a vogal inicial dos pronomes demonstrativos 'aquele(s)', 'aquela(s)' ou 'aquilo', como na frase: 'O delegado referiu-se àquele depoimento contraditório'.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Referir-se a + aquele = àquele. A fusão da preposição com o 'a' do pronome demonstrativo recebe acento grave.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3690413b31028ca3fcea2b74c34313669c1981442302ab38a37223cea98b0136",
    "conceito_principal": "Crase com Pronomes Demonstrativos (Àquele, Àquela, Àquilo)",
    "habilidade_cobrada": "Identificar a fusão prepositiva com pronomes demonstrativos iniciados pela letra 'a'",
    "tese_ou_regra": "A preposição 'a' funde-se com a letra inicial de aquele/aquela/aquilo gerando crase",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "1a6a3b99-e8f4-5868-8907-7ef07ddc814d",
        "questao_id": "4e5475fb-1a87-524e-bf9a-1cf6d41919ec",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f74ddac6-275e-52d1-aa16-8abd14666b67",
        "questao_id": "4e5475fb-1a87-524e-bf9a-1cf6d41919ec",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b70e9a9f-d1d8-543b-b5d6-616de50a9b62",
    "idSlug": "l13-port-sint-014-concordancia-nominal-expressao-e-proibido",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Nas expressões 'é proibido', 'é necessário' e 'é permitido', o adjetivo permanece invariável no masculino singular quando o substantivo não vem precedido de artigo determinante (ex.: 'É proibido entrada de civis'); havendo artigo ou determinante feminino, a concordância torna-se obrigatória (ex.: 'É proibida a entrada de civis').",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Sem determinante = invariável ('É proibido entrada'); com determinante = flexão obrigatória ('É proibida a entrada').",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4d2512f32065931578ec85559fed2306791057e382778fd6432f44c3d8626617",
    "conceito_principal": "Concordância das Expressões 'É proibido / É necessário / É permitido'",
    "habilidade_cobrada": "Analisar a presença de determinantes na flexão de predicativos de sujeito",
    "tese_ou_regra": "A presença de artigo feminino determina a flexão obrigatória de 'é proibida'",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a575d782-c3d0-53a1-a782-9602b21da644",
        "questao_id": "b70e9a9f-d1d8-543b-b5d6-616de50a9b62",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "54956473-6da3-5f1e-b917-871cc8049afd",
        "questao_id": "b70e9a9f-d1d8-543b-b5d6-616de50a9b62",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
    "idSlug": "l13-port-sint-015-concordancia-verbal-indice-indeterminacao-sujeito",
    "disciplina_id": "cf63a64b-0209-5181-8fcf-2661da50a633",
    "assunto_id": "874b8ded-33c7-575d-8339-7a2f42e85e25",
    "banca_nome": "Instituto AOCP",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Analise a frase: 'Tratavam-se de questões altamente complexas sobre o tráfico internacional de drogas'. De acordo com a norma-padrão da língua portuguesa, assinale a avaliação gramatical correta.",
    "explicacao": "GABARITO: B. O verbo 'tratar-se de' é transitivo indireto acompanhado de pronome 'se' como índice de indeterminação do sujeito. Com índice de indeterminação, o verbo fica obrigatoriamente no singular: 'Tratava-se de questões altamente complexas...'.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ce6c623545a7aae139f94e1755f54c941068675741c65ec9abe63c273edb9ac2",
    "conceito_principal": "Índice de Indeterminação do Sujeito e Invariabilidade do Verbo no Singular",
    "habilidade_cobrada": "Diferenciar a partícula apassivadora (VTD) do índice de indeterminação do sujeito (VTI)",
    "tese_ou_regra": "Com índice de indeterminação do sujeito o verbo permanece fixo na 3ª pessoa do singular",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "6793228b-93c5-5007-bf7a-61a3ed7dc6b7",
        "questao_id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
        "letra": "A",
        "texto": "A frase está correta, pois o verbo deve concordar no plural com o sujeito paciente 'questões altamente complexas'.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. 'De questões' é objeto indireto preposicionado, não sujeito."
      },
      {
        "id": "6c79d81b-ec58-5493-bb46-fcc2e903cc0a",
        "questao_id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
        "letra": "B",
        "texto": "A frase apresenta erro de concordância verbal, pois o verbo 'tratar-se' com índice de indeterminação do sujeito deve permanecer obrigatoriamente na terceira pessoa do singular: 'Tratava-se de questões'.",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. Regra estrita do índice de indeterminação do sujeito."
      },
      {
        "id": "95727a16-7504-5fa9-8914-62f5bc5898bc",
        "questao_id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
        "letra": "C",
        "texto": "A frase é ambígua e deveria ter sido escrita na voz passiva analítica com o verbo haver.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Não se trata de ambiguidade, mas de erro de concordância."
      },
      {
        "id": "ce4c6a24-7dcc-5be2-8dca-347f16d4f639",
        "questao_id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
        "letra": "D",
        "texto": "O emprego da preposição 'de' é facultativo após o verbo tratar quando acompanhado de pronome reflexivo.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. A preposição 'de' é obrigatória pela regência do verbo."
      },
      {
        "id": "7ce5d3fd-45ed-584c-93bc-3c2bc36a878f",
        "questao_id": "483e1c9e-7782-53ba-b421-6f87c073aa39",
        "letra": "E",
        "texto": "A flexão no plural é autorizada facultativamente por motivo de eufonia fonética.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. A norma culta não admite pluralização com índice de indeterminação."
      }
    ]
  }
];
