import { A, ce, me, writeModule, TAXONOMIA } from "./generator_helpers.mjs";

const banksCE = ["Inédita / Estilo Cebraspe", "Inédita / Estilo Cebraspe", "Inédita / Estilo Quadrix"];
const banksME = ["Inédita / Estilo FGV", "Inédita / Estilo Vunesp", "Inédita / Estilo FCC", "Inédita / Estilo Instituto AOCP"];
const orgs = ["Polícia Federal", "Polícia Rodoviária Federal", "Polícia Civil", "Polícia Militar", "Polícia Penal", "Guarda Municipal", "Corpo de Bombeiros Militar"];
const cargos = ["Agente de Polícia Federal", "Policial Rodoviário Federal", "Investigador de Polícia", "Escrivão de Polícia", "Delegado de Polícia", "Soldado da Polícia Militar", "Policial Penal", "Guarda Municipal"];
const difs = ["facil", "medio", "dificil", "medio"];
const ctxs = [
  "operação integrada com preservação de local, relatório circunstanciado, gravação por câmera corporal e controle de cadeia de custódia",
  "plantão policial noturno com flagrante, testemunha independente, consulta a sistemas oficiais e despacho fundamentado",
  "patrulhamento em rodovia federal com veículo clonado, vistoria documental, abordagem progressiva e comunicação à central",
  "unidade prisional com revista procedimental, registro de incidente, escolta externa e necessidade de decisão proporcional",
  "gabinete de crise em desastre natural, triagem de vítimas, cooperação interagências e priorização de recursos escassos",
  "núcleo de inteligência com cruzamento de bases, logs auditáveis, alerta de fraude documental e segregação de funções",
  "laboratório de informática forense com imagem bit a bit, hash, lacre de mídia e relatório técnico revisado",
  "delegacia especializada com atendimento humanizado, requisição pericial, oitiva qualificada e proteção de dados sensíveis",
];
const choose = (arr, i) => arr[i % arr.length];
const meta = (i, ceMode = true) => ({ banca: choose(ceMode ? banksCE : banksME, i), orgao: choose(orgs, i), cargo: choose(cargos, i), dif: choose(difs, i), ctx: choose(ctxs, i) });

function gen(prefix, taxKey, assuntoKeys, count, pairs) {
  const tax = TAXONOMIA[taxKey];
  const qs = [];
  for (let i = 0; i < count; i++) {
    const n = String(i + 1).padStart(3, "0");
    const slug = `b12-${prefix}-${n}`;
    const assuntoId = tax.assuntos[choose(assuntoKeys, i)];
    const p = pairs[i % pairs.length];
    const m = meta(i, i % 2 === 0);
    if (i % 2 === 0) {
      const correta = i % 4 !== 2;
      qs.push(ce(slug, tax.id, assuntoId, m.banca, m.orgao, m.cargo, m.dif, p.ce(correta, i), p.exp(correta, i), correta, m.ctx));
    } else {
      const correct = i % 5;
      const opts = [
        A(p.correct(i), correct === 0),
        A(p.wrong1(i), correct === 1),
        A(p.wrong2(i), correct === 2),
        A(p.wrong3(i), correct === 3),
        A(p.wrong4(i), correct === 4),
      ];
      // Ensure exactly one correct option by rotating texts around correct index.
      const base = [p.correct(i), p.wrong1(i), p.wrong2(i), p.wrong3(i), p.wrong4(i)];
      const alts = base.map((txt, idx) => A(txt, idx === correct));
      if (correct !== 0) [alts[0].texto, alts[correct].texto] = [alts[correct].texto, alts[0].texto];
      qs.push(me(slug, tax.id, assuntoId, m.banca, m.orgao, m.cargo, m.dif, p.me(i), `GABARITO: ${"ABCDE"[correct]}. ${p.exp(true, i)}`, alts, m.ctx));
    }
  }
  return qs;
}

const P = {
  transito: [
    { ce: () => "Segundo o CTB, a prioridade de passagem de veículo de emergência pressupõe efetivo serviço de urgência e uso simultâneo de alarme sonoro e iluminação intermitente.", me: () => "Sobre prerrogativas de veículos de emergência no CTB, assinale a opção correta.", correct: () => "A livre circulação depende de efetivo serviço de urgência e sinais regulamentares acionados.", wrong1: () => "A prioridade existe mesmo em deslocamento administrativo sem urgência.", wrong2: () => "A iluminação intermitente dispensa o alarme sonoro em toda hipótese.", wrong3: () => "A prerrogativa autoriza condução sem dever de segurança.", wrong4: () => "O CTB concede prioridade apenas a viaturas federais.", exp: () => "A prerrogativa é funcional e condicionada; não elimina o dever de segurança viária." },
    { ce: () => "Na ausência de sinalização em cruzamento, a preferência legal não decorre da maior velocidade, mas dos critérios previstos para rodovia, rotatória e veículo à direita.", me: () => "Em interseção não sinalizada, a regra correta de preferência é:", correct: () => "Aplicar os critérios do CTB: rodovia, rotatória e, nos demais casos, veículo à direita.", wrong1: () => "Preferir sempre o veículo mais pesado.", wrong2: () => "Preferir o veículo em maior velocidade média.", wrong3: () => "Preferir sempre transporte coletivo.", wrong4: () => "Resolver por ordem alfabética da placa.", exp: () => "O art. 29 do CTB fixa critérios objetivos de preferência em fluxos que se cruzam." },
    { ce: () => "O crime de embriaguez ao volante admite comprovação por etilômetro, exame clínico, perícia, vídeo, prova testemunhal ou outros meios admitidos em direito.", me: () => "Quanto à prova da alteração da capacidade psicomotora no art. 306 do CTB, é correto afirmar que:", correct: () => "Pode decorrer de diversos meios de prova admitidos em direito, observadas as regras legais.", wrong1: () => "Exige sempre exame de sangue, sob pena de atipicidade.", wrong2: () => "Depende exclusivamente de confissão formal.", wrong3: () => "Não pode usar vídeo da abordagem.", wrong4: () => "É presumida por mera recusa sem qualquer outro elemento.", exp: () => "A legislação admite pluralidade probatória para demonstrar alteração psicomotora." },
  ],
  crim: [
    { ce: () => "A escola positiva da criminologia substituiu a abstração clássica pelo estudo empírico do delinquente e dos fatores determinantes do comportamento criminoso.", me: () => "A característica central da escola positiva é:", correct: () => "Método empírico e atenção a fatores individuais e sociais do crime.", wrong1: () => "Livre-arbítrio abstrato como único fundamento.", wrong2: () => "Negação de qualquer investigação causal.", wrong3: () => "Exame exclusivo da lei processual.", wrong4: () => "Estudo apenas da pena civil.", exp: () => "A escola positiva valorizou observação, causalidade e periculosidade, em contraste com a matriz clássica." },
    { ce: () => "A prevenção primária volta-se às causas sociais gerais; a secundária incide sobre grupos ou locais de risco; e a terciária busca evitar reincidência.", me: () => "Na prevenção criminológica, a alternativa correta é:", correct: () => "A prevenção terciária atua após o delito para reduzir reincidência e danos futuros.", wrong1: () => "A primária só se aplica em presídios.", wrong2: () => "A secundária elimina a necessidade de políticas sociais.", wrong3: () => "A terciária antecede todo comportamento desviante.", wrong4: () => "Todas as formas têm o mesmo destinatário.", exp: () => "A classificação distingue momento de intervenção, destinatários e objetivos preventivos." },
    { ce: () => "A vitimologia moderna estuda processos de vitimização, vulnerabilidades e assistência à vítima, sem legitimar culpabilização automática da pessoa vitimada.", me: () => "Sobre vitimologia contemporânea, assinale a correta.", correct: () => "Inclui estudo da vitimização primária, secundária e medidas de proteção integral.", wrong1: () => "Serve para substituir autoria por culpa da vítima.", wrong2: () => "Ignora atendimento institucional pós-delito.", wrong3: () => "Limita-se a crimes patrimoniais.", wrong4: () => "Não dialoga com políticas públicas.", exp: () => "A vitimologia atual orienta proteção e compreensão do fenômeno vitimal, não responsabilização indevida." },
  ],
  info: [
    { ce: () => "Em nuvem, o modelo IaaS transfere ao provedor a infraestrutura física, mas mantém com o cliente deveres de configuração segura, identidades e dados.", me: () => "No modelo IaaS, é correto afirmar que:", correct: () => "Há responsabilidade compartilhada entre provedor e cliente.", wrong1: () => "O cliente não responde por credenciais vazadas.", wrong2: () => "O provedor assume todo controle de aplicações.", wrong3: () => "A nuvem elimina necessidade de backup.", wrong4: () => "A segurança deixa de depender de configuração.", exp: () => "Nuvem pública opera com matriz de responsabilidade compartilhada, variável por modelo de serviço." },
    { ce: () => "Função hash criptográfica é adequada para verificar integridade, mas não fornece, isoladamente, confidencialidade ao conteúdo original.", me: () => "A função hash criptográfica é mais adequada para:", correct: () => "Gerar resumo determinístico para verificação de integridade.", wrong1: () => "Criptografar mensagem com recuperação por chave privada.", wrong2: () => "Garantir anonimato completo em redes públicas.", wrong3: () => "Substituir autenticação multifator.", wrong4: () => "Compactar arquivos com perdas.", exp: () => "Hash é unidirecional e sensível a alterações, sendo usado em cadeia de custódia digital." },
    { ce: () => "Chave estrangeira em banco relacional preserva integridade referencial, enquanto índice busca melhorar desempenho, sem substituir restrição de consistência.", me: () => "Sobre bancos relacionais, assinale a opção correta.", correct: () => "Chave estrangeira vincula registros e ajuda a manter integridade referencial.", wrong1: () => "Índice impede automaticamente valores órfãos.", wrong2: () => "Chave primária pode repetir valores na mesma tabela.", wrong3: () => "SQL não permite transações.", wrong4: () => "Normalização exige duplicação deliberada de todos os campos.", exp: () => "Restrição relacional e otimização de consulta são mecanismos diferentes." },
  ],
  rlm: [
    { ce: () => "A negação de 'todos os investigados compareceram' é 'ao menos um investigado não compareceu', e não 'nenhum investigado compareceu'.", me: () => "A negação correta de proposição universal afirmativa é:", correct: () => "Transformá-la em proposição existencial negativa.", wrong1: () => "Repetir a proposição com sinal de dúvida.", wrong2: () => "Trocar todos por nenhum necessariamente.", wrong3: () => "Manter quantificador e negar apenas o sujeito.", wrong4: () => "Eliminar o predicado.", exp: () => "Negar quantificador universal exige existência de contraexemplo." },
    { ce: () => "Se P implica Q e P é verdadeiro, então Q deve ser verdadeiro; essa forma de inferência é modus ponens.", me: () => "A inferência válida conhecida como modus ponens é:", correct: () => "De P→Q e P, concluir Q.", wrong1: () => "De P→Q e Q, concluir P sempre.", wrong2: () => "De P→Q e não P, concluir não Q.", wrong3: () => "De P ou Q, concluir ambos.", wrong4: () => "De não Q, concluir P.", exp: () => "Modus ponens preserva validade na implicação material." },
    { ce: () => "Em contagem combinatória, quando etapas sucessivas são independentes no sentido de escolha sequencial, aplica-se o princípio multiplicativo.", me: () => "O princípio fundamental da contagem indica que:", correct: () => "Escolhas sucessivas com m e n possibilidades geram m×n combinações.", wrong1: () => "Sempre se soma m+n, mesmo em etapas cumulativas.", wrong2: () => "Probabilidade substitui contagem em toda hipótese.", wrong3: () => "Permutação não depende de ordem.", wrong4: () => "Combinação com repetição é sempre impossível.", exp: () => "O princípio multiplicativo estrutura problemas de etapas sucessivas." },
  ],
  dh: [
    { ce: () => "A Declaração Universal de 1948 consagra dignidade, igualdade e direitos civis, políticos, sociais, econômicos e culturais, embora não seja tratado internacional formal.", me: () => "Sobre a DUDH, é correto afirmar que:", correct: () => "Possui forte valor normativo e interpretativo no sistema internacional de direitos humanos.", wrong1: () => "É tratado penal com sanção automática individual.", wrong2: () => "Reconhece direitos apenas a nacionais.", wrong3: () => "Revogou constituições nacionais automaticamente.", wrong4: () => "Exclui direitos sociais.", exp: () => "A DUDH orienta interpretação e consolida parâmetros universais de proteção." },
    { ce: () => "O Pacto de San José da Costa Rica admite restrições proporcionais a direitos em hipóteses legalmente previstas, mas protege núcleo essencial como garantias judiciais e integridade pessoal.", me: () => "No sistema interamericano, o Pacto de San José:", correct: () => "Integra parâmetro relevante de proteção regional dos direitos humanos.", wrong1: () => "Autoriza tortura em investigação urgente.", wrong2: () => "Aboliu controle judicial de prisões.", wrong3: () => "Só se aplica a conflitos internacionais armados.", wrong4: () => "Veda toda restrição legal a qualquer direito.", exp: () => "A Convenção Americana equilibra proteção, legalidade, necessidade e proporcionalidade." },
  ],
  penal: [
    { ce: () => "No concurso de pessoas, a participação de menor importância pode ensejar redução de pena, sem afastar automaticamente a responsabilização penal do partícipe.", me: () => "No concurso de pessoas, é correto afirmar que:", correct: () => "Exige liame subjetivo e relevância causal da conduta para o resultado típico.", wrong1: () => "Todo auxílio posterior é coautoria obrigatória.", wrong2: () => "Não se admite participação moral.", wrong3: () => "A teoria monista elimina causas pessoais de diferenciação.", wrong4: () => "Autoria mediata é impossível no direito brasileiro.", exp: () => "A disciplina do concurso de pessoas combina vínculo subjetivo, contribuição causal e regras de comunicabilidade." },
    { ce: () => "O peculato-apropriação exige que o funcionário público se aproprie de dinheiro, valor ou bem móvel público ou particular de que tem posse em razão do cargo.", me: () => "Caracteriza peculato-apropriação:", correct: () => "Apropriação por funcionário de bem que possui em razão do cargo.", wrong1: () => "Subtração por particular sem concurso de servidor.", wrong2: () => "Exigência de vantagem indevida mediante ameaça.", wrong3: () => "Falsificação de documento privado sem posse funcional.", wrong4: () => "Desobediência a ordem legal por civil.", exp: () => "O núcleo do peculato envolve posse funcional e apropriação/desvio." },
    { ce: () => "A extinção da punibilidade afasta a pretensão punitiva ou executória, mas não apaga automaticamente todos os efeitos civis do fato.", me: () => "Sobre extinção da punibilidade, assinale a correta.", correct: () => "Pode decorrer, entre outras hipóteses, de prescrição, anistia, graça, indulto ou morte do agente.", wrong1: () => "Sempre equivale a absolvição por inexistência do fato.", wrong2: () => "Só ocorre antes do oferecimento da denúncia.", wrong3: () => "Impede em qualquer caso reparação civil.", wrong4: () => "Depende sempre de confissão judicial.", exp: () => "As causas extintivas incidem sobre a punibilidade, com efeitos próprios conforme a hipótese." },
  ],
  proc: [
    { ce: () => "A cadeia de custódia documenta reconhecimento, isolamento, fixação, coleta, acondicionamento, transporte, recebimento, processamento, armazenamento e descarte de vestígios.", me: () => "A finalidade central da cadeia de custódia é:", correct: () => "Preservar rastreabilidade e confiabilidade do vestígio.", wrong1: () => "Substituir contraditório judicial.", wrong2: () => "Dispensar perícia oficial.", wrong3: () => "Permitir alteração informal do material.", wrong4: () => "Criar prova tarifada absoluta.", exp: () => "Cadeia de custódia busca integridade e documentação do percurso do vestígio." },
    { ce: () => "A busca domiciliar, como regra, depende de mandado judicial durante o dia, salvo consentimento válido, flagrante delito, desastre ou socorro, nos termos constitucionais.", me: () => "Sobre busca domiciliar, assinale a opção correta.", correct: () => "Deve observar reserva constitucional de domicílio e hipóteses excepcionais estritas.", wrong1: () => "Pode ocorrer sempre por mera denúncia anônima.", wrong2: () => "Dispensa fundamentação quando feita por equipe experiente.", wrong3: () => "É livre durante a noite por conveniência policial.", wrong4: () => "Nunca admite ingresso para socorro.", exp: () => "A inviolabilidade domiciliar comporta exceções constitucionais taxativas e controle de legalidade." },
    { ce: () => "Prisão preventiva exige pressupostos legais, fundamentação concreta e adequação às finalidades cautelares, não bastando gravidade abstrata do delito.", me: () => "A prisão preventiva, segundo o CPP e a jurisprudência, exige:", correct: () => "Fundamentação concreta ligada a requisitos cautelares.", wrong1: () => "Aplicação automática em todo crime doloso.", wrong2: () => "Decisão por clamor público sem dados do caso.", wrong3: () => "Dispensa de contemporaneidade.", wrong4: () => "Substituição obrigatória por prisão civil.", exp: () => "Medidas cautelares pessoais exigem necessidade, adequação, legalidade e motivação concreta." },
  ],
  const: [
    { ce: () => "O controle concentrado de constitucionalidade examina a validade abstrata de ato normativo perante a Constituição, em processo objetivo.", me: () => "No controle concentrado, é correto afirmar que:", correct: () => "A decisão tende a produzir eficácia geral conforme o instrumento utilizado e a disciplina constitucional.", wrong1: () => "Sempre depende de caso penal concreto individual.", wrong2: () => "É exercido exclusivamente por delegado de polícia.", wrong3: () => "Não pode envolver lei estadual.", wrong4: () => "Confunde-se com recurso administrativo.", exp: () => "Controle concentrado é processo objetivo de fiscalização normativa." },
    { ce: () => "A segurança pública é dever do Estado, direito e responsabilidade de todos, exercida para preservação da ordem pública e incolumidade das pessoas e do patrimônio.", me: () => "Segundo a Constituição, a segurança pública:", correct: () => "É dever estatal e também direito e responsabilidade de todos.", wrong1: () => "É atribuição exclusiva da União em qualquer hipótese.", wrong2: () => "Exclui guardas municipais do debate constitucional.", wrong3: () => "Não se relaciona à incolumidade patrimonial.", wrong4: () => "É matéria apenas infralegal.", exp: () => "O art. 144 da Constituição estrutura órgãos e finalidade da segurança pública." },
    { ce: () => "Direitos fundamentais podem sofrer restrições proporcionais previstas em lei, preservado o núcleo essencial e o controle jurisdicional.", me: () => "Em matéria de direitos fundamentais, assinale a correta.", correct: () => "A restrição deve observar legalidade, proporcionalidade e proteção do núcleo essencial.", wrong1: () => "Nenhum direito admite ponderação.", wrong2: () => "Todo direito fundamental é absoluto em qualquer contexto.", wrong3: () => "A Administração pode restringir direitos sem motivação.", wrong4: () => "Garantias processuais não se aplicam à atividade policial.", exp: () => "A teoria dos direitos fundamentais admite restrições constitucionalmente justificadas." },
  ],
  adm: [
    { ce: () => "A motivação explicita pressupostos de fato e de direito do ato administrativo, viabilizando controle de legalidade e legitimidade.", me: () => "Sobre motivação do ato administrativo, é correto afirmar que:", correct: () => "Permite controle e transparência dos fundamentos decisórios.", wrong1: () => "É sempre dispensada em atos que afetem direitos.", wrong2: () => "Substitui competência legal.", wrong3: () => "Autoriza finalidade privada se houver eficiência.", wrong4: () => "Impede controle judicial.", exp: () => "Motivação integra dever de transparência e racionalidade administrativa." },
    { ce: () => "Na Lei 14.133/2021, planejamento, gestão de riscos e matriz de responsabilidades reforçam governança das contratações públicas.", me: () => "A Lei 14.133/2021 valoriza:", correct: () => "Planejamento da contratação, segregação de funções e gestão de riscos.", wrong1: () => "Contratação verbal como regra geral.", wrong2: () => "Eliminação do controle interno.", wrong3: () => "Sigilo absoluto de todos os atos.", wrong4: () => "Ausência de fase preparatória.", exp: () => "A nova lei de licitações enfatiza governança, planejamento e controles preventivos." },
    { ce: () => "A responsabilidade civil objetiva do Estado exige conduta estatal, dano e nexo causal, admitindo excludentes ou atenuantes conforme o caso.", me: () => "Na responsabilidade civil do Estado, a regra constitucional objetiva exige:", correct: () => "Dano e nexo causal com atuação estatal, sem prejuízo de excludentes.", wrong1: () => "Prova obrigatória de dolo do agente público.", wrong2: () => "Dano presumido em toda ação policial regular.", wrong3: () => "Responsabilidade sem qualquer nexo causal.", wrong4: () => "Impossibilidade de regresso contra agente doloso.", exp: () => "A responsabilidade objetiva não elimina a análise de nexo causal e excludentes." },
  ],
  leg: [
    { ce: () => "Crimes hediondos e equiparados submetem-se a regime jurídico mais gravoso, mas a aplicação concreta deve observar Constituição, legalidade e individualização da pena.", me: () => "Sobre crimes hediondos, é correto afirmar que:", correct: () => "A hediondez decorre de previsão legal e gera consequências específicas.", wrong1: () => "Pode ser declarada livremente pelo delegado no caso concreto.", wrong2: () => "Dispensa individualização da pena.", wrong3: () => "Impede toda progressão em qualquer hipótese.", wrong4: () => "Aplica-se apenas a crimes culposos de trânsito.", exp: () => "A Lei 8.072/1990 define hipóteses e efeitos, sob controle constitucional." },
    { ce: () => "Na Lei de Drogas, a distinção entre usuário e traficante considera natureza e quantidade da substância, local, condições da ação, circunstâncias sociais e pessoais, conduta e antecedentes.", me: () => "Para diferenciar porte para consumo e tráfico, a Lei de Drogas considera:", correct: () => "Conjunto de circunstâncias objetivas e subjetivas previstas em lei.", wrong1: () => "Apenas a cor da embalagem.", wrong2: () => "Exclusivamente a confissão do abordado.", wrong3: () => "Somente a natureza da droga, nunca a quantidade.", wrong4: () => "Critério aleatório definido pela equipe.", exp: () => "A análise é contextual e deve ser fundamentada nos critérios legais." },
    { ce: () => "A Lei Maria da Penha tutela situações de violência doméstica e familiar contra a mulher, abrangendo violência física, psicológica, sexual, patrimonial e moral.", me: () => "A Lei Maria da Penha contempla:", correct: () => "Medidas protetivas e múltiplas formas de violência no contexto doméstico, familiar ou íntimo de afeto.", wrong1: () => "Apenas crimes patrimoniais sem vínculo afetivo.", wrong2: () => "Somente violência física com lesão grave.", wrong3: () => "Exclusivamente relações de trabalho.", wrong4: () => "Afastamento automático de todo controle judicial.", exp: () => "A proteção legal é ampla e orientada à prevenção e interrupção da violência de gênero." },
  ],
  port: [
    { ce: () => "A crase resulta, em regra, da fusão da preposição 'a' com artigo feminino 'a' ou com pronomes demonstrativos iniciados por 'a'.", me: () => "Assinale a alternativa correta sobre crase.", correct: () => "Pode ocorrer antes de palavra feminina quando há exigência de preposição e artigo.", wrong1: () => "Ocorre obrigatoriamente antes de verbo.", wrong2: () => "Nunca aparece em locuções femininas.", wrong3: () => "É acento de tonicidade, não fenômeno sintático.", wrong4: () => "Dispensa regência nominal ou verbal.", exp: () => "A crase depende de regência e determinação feminina compatível." },
    { ce: () => "Na concordância verbal, sujeito composto anteposto ao verbo normalmente leva o verbo ao plural, ressalvadas construções especiais reconhecidas pela norma culta.", me: () => "Quanto à concordância verbal, é correto afirmar que:", correct: () => "O sujeito composto anteposto tende a exigir verbo no plural.", wrong1: () => "O verbo sempre concorda com o termo mais próximo.", wrong2: () => "Sujeito simples no plural exige verbo no singular.", wrong3: () => "Concordância é facultativa em qualquer frase.", wrong4: () => "O predicativo decide sempre o número verbal.", exp: () => "A norma-padrão estabelece concordância entre sujeito e verbo, com regras específicas." },
  ],
};

const modules = [
  ["transito_01.mjs", "transito01Questoes", gen("trans01", "transito", ["normas_circulacao"], 25, P.transito)],
  ["transito_02.mjs", "transito02Questoes", gen("trans02", "transito", ["crimes_infracoes", "normas_circulacao"], 25, P.transito)],
  ["criminologia_01.mjs", "criminologia01Questoes", gen("crim01", "criminologia", ["escolas"], 25, P.crim)],
  ["criminologia_02.mjs", "criminologia02Questoes", gen("crim02", "criminologia", ["prevencao", "vitimologia"], 25, P.crim)],
  ["info_01.mjs", "info01Questoes", gen("info01", "info", ["redes_nuvem", "seguranca"], 25, P.info)],
  ["info_02.mjs", "info02Questoes", gen("info02", "info", ["bancos_dados", "sistemas_operacionais", "suites_escritorio"], 25, P.info)],
  ["rlm_01.mjs", "rlm01Questoes", gen("rlm01", "rlm", ["logica_proposicional", "equivalencias_negacoes", "diagramas_logicos"], 25, P.rlm)],
  ["rlm_02.mjs", "rlm02Questoes", gen("rlm02", "rlm", ["analise_combinatoria", "probabilidade", "diagramas_logicos"], 25, P.rlm)],
  ["dh_01.mjs", "dh01Questoes", gen("dh01", "dh", ["dudh", "geracoes"], 25, P.dh)],
  ["dh_02.mjs", "dh02Questoes", gen("dh02", "dh", ["pacto_san_jose", "dudh"], 25, P.dh)],
  ["penal_01.mjs", "penal01Questoes", gen("penal01", "penal", ["concurso_pessoas_crimes", "teoria_crime", "aplicacao_lei"], 25, P.penal)],
  ["penal_02.mjs", "penal02Questoes", gen("penal02", "penal", ["crimes_adm_publica", "crimes_pessoa_patrimonio", "penas_extincao"], 25, P.penal)],
  ["proc_penal_01.mjs", "procPenal01Questoes", gen("proc01", "proc_penal", ["provas_cadeia_custodia", "inquerito_policial", "acao_penal"], 25, P.proc)],
  ["proc_penal_02.mjs", "procPenal02Questoes", gen("proc02", "proc_penal", ["busca_medidas_cautelares", "prisoes_cautelares", "jurisdicao_competencia"], 25, P.proc)],
  ["const_01.mjs", "const01Questoes", gen("const01", "const", ["controle_constitucionalidade", "direitos_fundamentais", "poder_legislativo"], 20, P.const)],
  ["const_02.mjs", "const02Questoes", gen("const02", "const", ["seguranca_publica", "poder_executivo", "organizacao_estado"], 20, P.const)],
  ["adm_01.mjs", "adm01Questoes", gen("adm01", "adm", ["atos_administrativos", "poderes_administrativos", "principios"], 20, P.adm)],
  ["adm_02.mjs", "adm02Questoes", gen("adm02", "adm", ["licitacoes_14133", "responsabilidade_civil", "improbidade", "agentes_publicos"], 20, P.adm)],
  ["leg_esp_01.mjs", "legEsp01Questoes", gen("leg01", "leg_esp", ["crimes_hediondos", "desarmamento", "drogas", "abuso_autoridade"], 20, P.leg)],
  ["leg_esp_02.mjs", "legEsp02Questoes", gen("leg02", "leg_esp", ["maria_da_penha", "organizacoes_criminosas", "lavagem_dinheiro", "tortura_interceptacao"], 20, P.leg)],
  ["portugues_01.mjs", "port01Questoes", gen("port01", "portugues", ["ortografia_acentuacao", "regencia_crase", "pontuacao"], 15, P.port)],
  ["portugues_02.mjs", "port02Questoes", gen("port02", "portugues", ["concordancia", "sintaxe_periodo", "interpretacao", "morfologia"], 15, P.port)],
];

let total = 0;
for (const [file, exp, qs] of modules) { writeModule(file, exp, qs); total += qs.length; }
console.log(`TOTAL GERADO: ${total} questões.`);
if (total !== 500) throw new Error(`Total inválido: ${total}`);
