// Arquivo autoral de questões do Lote 13 da Expansão Policial (v3.3-lote13)
// Quantidade de questões: 20

export const m20_questoes = [
  {
    "id": "bf459707-dae7-53c7-aa1c-7a62c18b0e27",
    "idSlug": "l13-rlm-comb-001-principio-multiplicativo-pfc-senhas",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Para acessar o cofre de evidências da delegacia, cada perito deve cadastrar uma senha composta por 3 letras distintas do alfabeto de 26 letras seguidas de 2 dígitos distintos de 0 a 9. Pelo Princípio Fundamental da Contagem, o número total de senhas distintas possíveis é igual a 26 x 25 x 24 x 10 x 9 = 1.404.000 senhas.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Letras distintas: 26 x 25 x 24 = 15.600. Dígitos distintos: 10 x 9 = 90. Total = 15.600 x 90 = 1.404.000.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "5c38bb4413fde8428579b9b6440e2e2c9373860bbbfe4507be0aa0d81b007a53",
    "conceito_principal": "Princípio Fundamental da Contagem (PFC) com elementos distintos",
    "habilidade_cobrada": "Calcular o total de combinações de senhas e acessos em investigações",
    "tese_ou_regra": "A quantidade de configurações distintas é o produto das escolhas sucessivas disponíveis",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "3b52c2f9-63e8-5de1-bfab-227478699db4",
        "questao_id": "bf459707-dae7-53c7-aa1c-7a62c18b0e27",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "360035f7-6d28-54ab-8f80-d26427a7e988",
        "questao_id": "bf459707-dae7-53c7-aa1c-7a62c18b0e27",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "97ec881a-0861-54fc-a2d3-5067cf89b633",
    "idSlug": "l13-rlm-comb-002-combinacao-simples-comissao-investigadores",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Uma delegacia dispõe de 8 investigadores e deseja formar uma equipe de plantão composta por 3 policiais. Como a ordem de escolha dos investigadores não altera a composição da equipe, o total de equipes distintas que podem ser formadas é dado pela combinação simples C(8, 3) = (8 x 7 x 6) / (3 x 2 x 1) = 56 equipes.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A ordem não importa na formação de comissões/equipes: C(8,3) = 8! / (3! 5!) = 56.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "e4c601ce57c5e0b929ceaa363d3ad6cf587529518e7e8f40f783ccaa19aac65f",
    "conceito_principal": "Combinação Simples na formação de equipes e comissões policiais",
    "habilidade_cobrada": "Calcular agrupamentos não ordenados mediante fórmula de combinação simples",
    "tese_ou_regra": "Agrupamentos onde a ordem dos elementos é irrelevante são calculados por combinação simples",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "8e8f56d2-fd26-5fcc-882f-68ef52291cd5",
        "questao_id": "97ec881a-0861-54fc-a2d3-5067cf89b633",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "202c3169-dc24-593c-a77f-2c854c7db002",
        "questao_id": "97ec881a-0861-54fc-a2d3-5067cf89b633",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f03f41bf-0e09-59ad-93e4-a9409dfe1f1d",
    "idSlug": "l13-rlm-comb-003-arranjo-simples-cargos-distintos-ordem",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Dentre 10 policiais rodoviários federais de um posto, devem ser escolhidos 3 para exercerem, respectivamente, as funções distintas de Chefe de Operações, Fiscal de Pista e Rádio-Operador. Como a ordem e a destinação funcional importam, o número de maneiras distintas de preencher esses cargos é dado pelo arranjo simples A(10, 3) = 10 x 9 x 8 = 720 maneiras.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Quando a ordem/função importa, utiliza-se Arranjo Simples: A(10,3) = 10! / 7! = 720.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "be32df0da82da49f6bb05cbb51ddb7d1c97242ae9c6f1289b1f478c7de9a0795",
    "conceito_principal": "Arranjo Simples e diferenciação em relação à combinação simples",
    "habilidade_cobrada": "Identificar situações em que a ordem dos elementos gera configurações distintas",
    "tese_ou_regra": "Quando a ordem dos elementos altera o resultado funcional, aplica-se o arranjo simples",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "dac96502-6f73-5f9c-be3d-f54e50394848",
        "questao_id": "f03f41bf-0e09-59ad-93e4-a9409dfe1f1d",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2ce8ed8f-2cff-5ce7-9e25-5bd69847b958",
        "questao_id": "f03f41bf-0e09-59ad-93e4-a9409dfe1f1d",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7b57dc6d-d401-58ed-94f7-cb2fcad5a78b",
    "idSlug": "l13-rlm-comb-004-permutacao-simples-anagramas-viaturas",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "O número total de maneiras distintas de estacionar 5 viaturas policiais identificadas (V1, V2, V3, V4 e V5) em 5 vagas contíguas alinhadas em frente ao departamento é dado pela permutação simples P5 = 5! = 5 x 4 x 3 x 2 x 1 = 120 maneiras.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Permutação simples de 5 elementos em 5 posições: P(5) = 5! = 120.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "a112041de10c464685330588bc26488b640e4a9f30503dd98dc2efe3eb61909f",
    "conceito_principal": "Permutação Simples de n elementos distintos (n!)",
    "habilidade_cobrada": "Calcular o número de disposições lineares de objetos em filas e vagas",
    "tese_ou_regra": "A ordenação de n objetos distintos em n posições é dada por n!",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "cae6c853-d49b-54d5-8eb0-2b0e60c3cbd7",
        "questao_id": "7b57dc6d-d401-58ed-94f7-cb2fcad5a78b",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "91e1c3c4-08fc-553d-9808-ac1529abd5d7",
        "questao_id": "7b57dc6d-d401-58ed-94f7-cb2fcad5a78b",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
    "idSlug": "l13-rlm-comb-005-probabilidade-classica-amostragem-pericia",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em uma caixa de evidências apreendidas, há 12 invólucros plásticos idênticos, dos quais 4 contêm substância entorpecente pura e 8 contêm substância adulterada com pó neutro. Se um perito retirar aleatoriamente 2 invólucros sucessivamente e sem reposição, qual é a probabilidade de que ambos os invólucros retirados contenham substância entorpecente pura?",
    "explicacao": "GABARITO: B. Primeira retirada: 4/12. Segunda retirada: 3/11. Probabilidade conjunta = (4/12) x (3/11) = (1/3) x (3/11) = 3/33 = 1/11.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3e895419671fdb71be44dcc2a1a6f746cf813d5b9a62a97e6bfee56ebc8bbce9",
    "conceito_principal": "Probabilidade Condicional e Eventos Sucessivos Sem Reposição",
    "habilidade_cobrada": "Calcular a probabilidade de eventos dependentes em retiradas sem reposição",
    "tese_ou_regra": "A probabilidade de dois eventos sucessivos sem reposição é P(A) * P(B|A)",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "1d3be864-71ee-51a9-8ed3-cf17591b354d",
        "questao_id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
        "letra": "A",
        "texto": "1/9",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Seria com reposição (4/12 x 4/12 = 1/9)."
      },
      {
        "id": "560997d8-eb56-5f69-97cb-c7a8933ddbd2",
        "questao_id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
        "letra": "B",
        "texto": "1/11",
        "correta": true,
        "ordem": 2,
        "explicacao_especifica": "Correta. (4/12) * (3/11) = 1/11."
      },
      {
        "id": "3e2a1ad6-4535-598e-8443-18af4816d6d4",
        "questao_id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
        "letra": "C",
        "texto": "2/11",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Cálculo proporcional inadequado."
      },
      {
        "id": "cf906284-de9e-54d8-8594-b4709ad76dd3",
        "questao_id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
        "letra": "D",
        "texto": "1/3",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Esta é a probabilidade da primeira retirada isolada."
      },
      {
        "id": "5571766d-9de7-5015-8f43-4b3fb8bec658",
        "questao_id": "12021d8a-be19-5a21-8a12-7dffafe7e32d",
        "letra": "E",
        "texto": "4/33",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Erro na simplificação fracionária."
      }
    ]
  },
  {
    "id": "96d19954-4a26-5664-822a-7c53b77dbe3a",
    "idSlug": "l13-rlm-comb-006-teoria-conjuntos-intersecao-diagrama-venn",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "671e06a6-a523-512a-a333-08f2542f694f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em uma delegacia com 50 policiais, 30 participaram do curso de Tiro Tático (T), 25 participaram do curso de Negociação de Crises (N) e 10 participaram de ambos os cursos. Nesse cenário, o número de policiais que participaram de pelo menos um dos cursos é igual a 45, e exatamente 5 policiais não participaram de nenhum dos cursos.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. n(T U N) = n(T) + n(N) - n(T inter N) = 30 + 25 - 10 = 45. Nenhum curso = 50 - 45 = 5.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "940907e600988f14f97b019c63ce5c14c23dcace4ed8db691d1e72f27346b154",
    "conceito_principal": "Teoria dos Conjuntos: Cardinalidade da União n(A U B) = n(A) + n(B) - n(A inter B)",
    "habilidade_cobrada": "Resolver problemas de contagem com Diagramas de Venn e exclusão de duplicidades",
    "tese_ou_regra": "A união de dois conjuntos é a soma de suas cardinalidades menos a interseção",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "1c280066-c3cd-55dc-9ca4-8c7c622dc889",
        "questao_id": "96d19954-4a26-5664-822a-7c53b77dbe3a",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "af2d55dd-2036-5f07-a5b5-65bb1e456cde",
        "questao_id": "96d19954-4a26-5664-822a-7c53b77dbe3a",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "fa2475b7-a4bb-515b-be2f-06ae7d8df72c",
    "idSlug": "l13-rlm-comb-007-permutacao-com-repeticao-letras-policia",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O número total de anagramas distintos que podem ser formados com todas as 7 letras da palavra 'POLICIA' (que possui a letra 'I' repetida 2 vezes e as demais letras distintas) é igual a 7! / 2! = 5.040 / 2 = 2.520 anagramas.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Palavra POLICIA tem 7 letras com a letra I repetida 2 vezes: P_7^(2) = 7! / 2! = 2.520.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "cfb85407e7310218e91bb8859f2bad66d03b43fd1d1126c3baf7507d79d32b1b",
    "conceito_principal": "Permutação com Repetição (n! / k!)",
    "habilidade_cobrada": "Calcular o número de anagramas de palavras contendo elementos repetidos",
    "tese_ou_regra": "A repetição de elementos exige a divisão do fatorial total pelo fatorial das repetições",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "c8696802-af65-5ece-9753-f752d61c553e",
        "questao_id": "fa2475b7-a4bb-515b-be2f-06ae7d8df72c",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "5713b08e-a6a3-50f8-9360-b01c2a951688",
        "questao_id": "fa2475b7-a4bb-515b-be2f-06ae7d8df72c",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "dba86d8a-7362-53b5-ad0b-a3e20798599e",
    "idSlug": "l13-rlm-comb-008-probabilidade-complementar-pelo-menos-um",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "A probabilidade de um radar capturar um veículo infrator em uma blitz é de 80% (0,8). Se três veículos infratores passarem sucessivamente pelo radar de forma independente, a probabilidade de que pelo menos um deles seja capturado é igual a 1 - (0,2)^3 = 1 - 0,008 = 0,992 (ou 99,2%).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. P(pelo menos um) = 1 - P(nenhum). P(nenhum ser capturado) = (0,2)^3 = 0,008. Logo, P = 1 - 0,008 = 0,992 (99,2%).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "d02bdf8e64570d1de7cad339bd39575b6d97dde5dc448c19c8f0d2a9574fcc93",
    "conceito_principal": "Probabilidade do Evento Complementar: P(ao menos um) = 1 - P(nenhum)",
    "habilidade_cobrada": "Calcular probabilidades em múltiplos ensaios independentes via evento complementar",
    "tese_ou_regra": "O evento complementar de 'ao menos um sucesso' é a ocorrência de 'nenhum sucesso'",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "36bc4a19-6553-5dd8-b6dc-d3424eab81ec",
        "questao_id": "dba86d8a-7362-53b5-ad0b-a3e20798599e",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "7aa0bd5a-e3a2-5aa6-a7e4-6bcec95dfe34",
        "questao_id": "dba86d8a-7362-53b5-ad0b-a3e20798599e",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "6590e9f3-440d-5aed-ae1c-8f4b0dbe31cb",
    "idSlug": "l13-rlm-comb-009-principio-casa-dos-pombos-gavetas-dirichlet",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "671e06a6-a523-512a-a333-08f2542f694f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Em uma delegacia especializada trabalham 13 policiais civis. Pelo Princípio da Casa dos Pombos (ou Princípio das Gavetas de Dirichlet), pode-se garantir com certeza absoluta que pelo menos dois desses policiais fazem aniversário no mesmo mês do ano.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. O ano possui 12 meses (casas) e há 13 policiais (pombos). Como 13 > 12, pelo menos um mês conterá no mínimo 2 aniversariantes.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "ffe4aea75c9c6d90267e80444a3d1d3da6c6c8d886048d97b336140817032802",
    "conceito_principal": "Princípio da Casa dos Pombos (Princípio das Gavetas de Dirichlet)",
    "habilidade_cobrada": "Aplicar garantias dedutivas de coincidência por contagem exaustiva de categorias",
    "tese_ou_regra": "Distribuir n+1 elementos em n categorias garante que ao menos uma categoria terá 2+ elementos",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "e33461d3-92d4-5bc9-827f-313986882b63",
        "questao_id": "6590e9f3-440d-5aed-ae1c-8f4b0dbe31cb",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "f3c06263-b12c-5083-a1a4-c64f4a3edcca",
        "questao_id": "6590e9f3-440d-5aed-ae1c-8f4b0dbe31cb",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
    "idSlug": "l13-rlm-comb-010-probabilidade-uniao-eventos-nao-mutuamente-exclusivos",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Em uma blitz policial com 100 veículos abordados, constatou-se que 20 estavam com IPVA atrasado, 15 estavam com pneus carecas e 5 apresentavam ambas as irregularidades simultaneamente. Se um desses 100 veículos for sorteado ao acaso para fiscalização detalhada, qual é a probabilidade de ele apresentar pelo menos uma dessas duas infrações?",
    "explicacao": "GABARITO: C. P(A U B) = P(A) + P(B) - P(A inter B) = 20/100 + 15/100 - 5/100 = 30/100 = 30% = 0,30.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "3396f49c3864099d4af4a6b055c8814fffd141bb790a823216bb21b192ca96f0",
    "conceito_principal": "Probabilidade da União de Eventos: P(A U B) = P(A) + P(B) - P(A inter B)",
    "habilidade_cobrada": "Calcular probabilidades em espaços amostrais com dupla ocorrência",
    "tese_ou_regra": "A probabilidade da união deduz a probabilidade da interseção para evitar dupla contagem",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "d346d279-b4f8-5f19-ac25-1ddf86e9d482",
        "questao_id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
        "letra": "A",
        "texto": "35%",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Somou sem subtrair a interseção (20 + 15 = 35)."
      },
      {
        "id": "d65092c9-4675-5736-8ed7-2b0a0f305567",
        "questao_id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
        "letra": "B",
        "texto": "25%",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Subtraiu a interseção duas vezes."
      },
      {
        "id": "a99df38e-0efa-5768-99ec-d532c8394def",
        "questao_id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
        "letra": "C",
        "texto": "30%",
        "correta": true,
        "ordem": 3,
        "explicacao_especifica": "Correta. P(A U B) = 20% + 15% - 5% = 30%."
      },
      {
        "id": "d3b34ffe-cc06-5fe5-a57b-968e26e40fbd",
        "questao_id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
        "letra": "D",
        "texto": "40%",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Valor superior à união real dos conjuntos."
      },
      {
        "id": "705cb170-3674-55df-aefc-1534b7f09db8",
        "questao_id": "b28eca43-e4d2-5f00-9087-ff54ba374a0d",
        "letra": "E",
        "texto": "5%",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Esta é a probabilidade da interseção exclusiva."
      }
    ]
  },
  {
    "id": "3d1c80df-8b36-535e-8496-e0a9fb15a6af",
    "idSlug": "l13-rlm-comb-011-combinacao-comissao-mista-homens-mulheres",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "De um grupo de 6 policiais federais homens e 4 policiais federais mulheres, deseja-se constituir uma comissão de 4 membros contendo exatamente 2 homens e 2 mulheres. O número total de maneiras distintas de formar essa comissão é igual a C(6, 2) x C(4, 2) = 15 x 6 = 90 maneiras.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Escolha dos 2 homens: C(6,2) = 15. Escolha das 2 mulheres: C(4,2) = 6. Pelo princípio multiplicativo: 15 x 6 = 90 comissões.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "2f08ff8241e697bf40ff4304389ca7960d418eb5f2a778594038ba8f39b736ac",
    "conceito_principal": "Combinação Simples Composta em Subgrupos Estratificados",
    "habilidade_cobrada": "Combinar seleções independentes em subconjuntos com restrições",
    "tese_ou_regra": "A seleção de subgrupos independentes é obtida pelo produto das respectivas combinações",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "5ba1b12d-9e94-538e-a401-0d5ccab996e1",
        "questao_id": "3d1c80df-8b36-535e-8496-e0a9fb15a6af",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "68ad7e8e-ddd4-59d4-b51e-1a9932877767",
        "questao_id": "3d1c80df-8b36-535e-8496-e0a9fb15a6af",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "f0802fe3-4c5c-5a08-bdcf-a31317bb6003",
    "idSlug": "l13-rlm-comb-012-conjuntos-diferenca-a-menos-b",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "671e06a6-a523-512a-a333-08f2542f694f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Escrivão de Polícia Civil",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Sejam o conjunto A formado por todos os crimes contra a pessoa e o conjunto B formado por todos os crimes que admitem fiança policial fixada pelo Delegado. A operação de diferença de conjuntos A - B representa o conjunto de todos os crimes contra a pessoa que NÃO admitem fiança fixada pelo Delegado de Polícia.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. A diferença A - B é o conjunto dos elementos que pertencem a A e não pertencem a B.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0fb98243fb1e2a4255b888007d7d6acc604a162898446bce41ee60cda100db3f",
    "conceito_principal": "Operação de Diferença de Conjuntos (A - B)",
    "habilidade_cobrada": "Interpretar operações de teoria dos conjuntos aplicadas a classificações penais",
    "tese_ou_regra": "A diferença A - B contém os elementos exclusivos de A que não integram B",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "c3902c2b-fd57-5b02-be1a-5ef219e2ddb4",
        "questao_id": "f0802fe3-4c5c-5a08-bdcf-a31317bb6003",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "6f0a42ff-ebf1-54bc-b599-9901dcb90edc",
        "questao_id": "f0802fe3-4c5c-5a08-bdcf-a31317bb6003",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "731e6128-9837-5f0e-9a0d-d5ffa65c57a5",
    "idSlug": "l13-rlm-comb-013-probabilidade-condicional-formula-bayesiana",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "dificil",
    "enunciado": "A probabilidade condicional de ocorrência de um evento A, dado que um evento B já ocorreu com probabilidade não nula P(B) > 0, é calculada pela razão entre a probabilidade da interseção dos eventos e a probabilidade do evento condicionante, expressa pela fórmula P(A|B) = P(A inter B) / P(B).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Definição formal e canônica de probabilidade condicional de Kolmogorov.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "c32c93095edbcc9c06bcda497fd4bb727995cff9dbeb4f3583da1e8bb6611c6f",
    "conceito_principal": "Definição Matemática de Probabilidade Condicional P(A|B)",
    "habilidade_cobrada": "Reconhecer a formulação analítica do espaço amostral reduzido",
    "tese_ou_regra": "A probabilidade condicional ajusta o espaço amostral ao evento condicionante ocorrido",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "14b578f0-71cd-5086-b097-e22a19f2cdbe",
        "questao_id": "731e6128-9837-5f0e-9a0d-d5ffa65c57a5",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "12529134-4363-5882-8dcf-a5d10b050688",
        "questao_id": "731e6128-9837-5f0e-9a0d-d5ffa65c57a5",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "890bbf28-df7c-5aa2-8643-1a875cc315dd",
    "idSlug": "l13-rlm-comb-014-permutacao-circular-mesa-reunioes",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "O número de maneiras distintas de dispor 6 delegados de polícia ao redor de uma mesa de reunião circular é dado pela permutação circular PC6 = (6 - 1)! = 5! = 120 maneiras, visto que rotações completas da mesa não geram novas posições relativas entre os membros.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Permutação circular de n elementos: PC(n) = (n - 1)!. Para n=6, PC(6) = 5! = 120.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "28bd53198cbfc3d9790e51bc6b6c7769a8bbb46db385d330cbd5b140619355cf",
    "conceito_principal": "Permutação Circular: PC(n) = (n - 1)!",
    "habilidade_cobrada": "Calcular ordenações cíclicas eliminando equivalências rotacionais",
    "tese_ou_regra": "Em arranjos circulares a fixação de uma referência reduz a contagem em 1 elemento ((n-1)!)",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "15ac0f49-5fa5-5d69-a82e-7ab94b8c335a",
        "questao_id": "890bbf28-df7c-5aa2-8643-1a875cc315dd",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "28df6aa7-699e-54e9-96cf-5211e21f849d",
        "questao_id": "890bbf28-df7c-5aa2-8643-1a875cc315dd",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
    "idSlug": "l13-rlm-comb-015-conjuntos-tres-conjuntos-venn-operacoes",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "671e06a6-a523-512a-a333-08f2542f694f",
    "banca_nome": "FGV",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Delegado de Polícia Civil",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "dificil",
    "enunciado": "Em uma força-tarefa contra o crime organizado com 80 agentes policiais:\n- 40 são especialistas em Armamento Pesado (A);\n- 35 são especialistas em Inteligência Cibernética (C);\n- 30 são especialistas em Perícia Financeira (F);\n- 15 dominam A e C;\n- 12 dominam A e F;\n- 10 dominam C e F;\n- 5 dominam as três especialidades (A, C e F).\nQuantos agentes dessa força-tarefa dominam pelo menos uma dessas três especialidades?",
    "explicacao": "GABARITO: A. Fórmula de 3 conjuntos: n(A U C U F) = n(A) + n(C) + n(F) - [n(A n C) + n(A n F) + n(C n F)] + n(A n C n F) = 40 + 35 + 30 - (15 + 12 + 10) + 5 = 105 - 37 + 5 = 73 agentes.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "0be780a463c8a1a7ebc5567430608c4a200b0953f89908d49c98211dce4b0060",
    "conceito_principal": "Cardinalidade da União de Três Conjuntos pelo Princípio da Inclusão-Exclusão",
    "habilidade_cobrada": "Calcular união de múltiplos conjuntos com interseções duplas e triplas",
    "tese_ou_regra": "A união de 3 conjuntos soma os unitários, subtrai as duplas e ressuma a tripla",
    "nivel_cognitivo": "analisar",
    "alternativas": [
      {
        "id": "d49e30ed-fdb7-5265-b480-06b04e163038",
        "questao_id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
        "letra": "A",
        "texto": "73 agentes.",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Correta. n(A U C U F) = 40 + 35 + 30 - 37 + 5 = 73."
      },
      {
        "id": "a6ea4c09-8a22-5565-a943-6727f945c901",
        "questao_id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
        "letra": "B",
        "texto": "68 agentes.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Esqueceu de somar a interseção tripla (+5)."
      },
      {
        "id": "514c4745-13f3-544a-a92c-b073869b6ceb",
        "questao_id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
        "letra": "C",
        "texto": "80 agentes.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Há 7 agentes que não dominam nenhuma das três."
      },
      {
        "id": "54e7da13-3f96-5658-b253-e97ceba7f5ac",
        "questao_id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
        "letra": "D",
        "texto": "60 agentes.",
        "correta": false,
        "ordem": 4,
        "explicacao_especifica": "Incorreta. Erro na subtração das interseções duplas."
      },
      {
        "id": "42b32c74-eed7-5e03-949f-32c143db8103",
        "questao_id": "73effca0-897b-540e-8e8b-7f81f2d09ae9",
        "letra": "E",
        "texto": "78 agentes.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Erro aritmético nas etapas intermediárias."
      }
    ]
  },
  {
    "id": "05561cb2-25d1-577b-9c41-4b448b568551",
    "idSlug": "l13-rlm-comb-016-probabilidade-eventos-independentes-multiplicacao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Agente de Polícia Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Dois eventos A e B são considerados estatisticamente independentes quando a ocorrência do evento B não altera a probabilidade de ocorrência do evento A, hipótese em que a probabilidade da ocorrência simultânea de ambos é dada pelo produto de suas probabilidades individuais: P(A inter B) = P(A) x P(B).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Propriedade fundamental dos eventos independentes: P(A|B) = P(A) => P(A inter B) = P(A) * P(B).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "91b86daea7b642590825f935271c0b501dddaee327169ef14ac0f6858547d4c9",
    "conceito_principal": "Definição e Propriedade de Eventos Independentes em Probabilidade",
    "habilidade_cobrada": "Reconhecer a regra da multiplicação para eventos descorrelacionados",
    "tese_ou_regra": "Eventos independentes têm probabilidade conjunta calculada pelo produto simples",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "a91d4a10-8430-5592-9e1f-76e9cd36a8da",
        "questao_id": "05561cb2-25d1-577b-9c41-4b448b568551",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "cdb42f75-bd9a-51fb-9fcd-92a6478c1f39",
        "questao_id": "05561cb2-25d1-577b-9c41-4b448b568551",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "e7322b4e-87cc-5508-85c1-d306f82dfee4",
    "idSlug": "l13-rlm-comb-017-fatorial-propriedades-zero-fatorial-um",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Na teoria da análise combinatória, o fatorial de um número natural n (denotado por n!) representa o produto de todos os inteiros positivos menores ou iguais a n, adotando-se por convenção matemática e consistência combinatória que 0! = 1 e 1! = 1.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Definição axiomática fundamental: 0! = 1, 1! = 1, e n! = n * (n-1)!.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "7876b58d7a8004d4017ea5f061e659fa44bb1688815e303076db2469af1e8dcb",
    "conceito_principal": "Definição e Propriedades da Função Fatorial (0! = 1)",
    "habilidade_cobrada": "Identificar os axiomas fundamentais da combinatória clássica",
    "tese_ou_regra": "Por definição formal e consistência de agrupamentos vazios, 0! é igual a 1",
    "nivel_cognitivo": "recordar",
    "alternativas": [
      {
        "id": "6ae5b43c-0f5b-5c71-b655-390cfc944dee",
        "questao_id": "e7322b4e-87cc-5508-85c1-d306f82dfee4",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "ad1e5077-a37c-5fb7-85ac-b60bd6191a79",
        "questao_id": "e7322b4e-87cc-5508-85c1-d306f82dfee4",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "01ebe086-9266-5a0b-abf6-40b21d94ab64",
    "idSlug": "l13-rlm-comb-018-probabilidade-soma-eventos-mutuamente-excludentes",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "48745dac-cbf3-5f1d-a0a2-1767a7d44429",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Rodoviária Federal",
    "cargo_nome": "Policial Rodoviário Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "facil",
    "enunciado": "Dois eventos são mutuamente excludentes quando não podem ocorrer simultaneamente em um mesmo experimento aleatório (sua interseção é o conjunto vazio, A inter B = vazio), sendo a probabilidade da ocorrência de um OU outro calculada pela soma direta de suas probabilidades: P(A U B) = P(A) + P(B).",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Quando eventos são mutuamente excludentes, P(A inter B) = 0, logo P(A U B) = P(A) + P(B).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "97d7ce5959939ab5a7b8f22b36c627ad021ad8b64d11fcb6bff801fdf001b266",
    "conceito_principal": "Eventos Mutuamente Excludentes e Aditividade Direta da Probabilidade",
    "habilidade_cobrada": "Aplicar a soma direta de probabilidades quando a interseção é impossível",
    "tese_ou_regra": "Eventos disjuntos têm probabilidade da união calculada pela simples soma das partes",
    "nivel_cognitivo": "compreender",
    "alternativas": [
      {
        "id": "4a4fbdaa-d736-5f67-a5ca-e39b92890493",
        "questao_id": "01ebe086-9266-5a0b-abf6-40b21d94ab64",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "2d50de13-99bb-52bd-8ff8-c4dfd3a060c8",
        "questao_id": "01ebe086-9266-5a0b-abf6-40b21d94ab64",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "72668e5a-f800-53a2-90e7-65227b4dacbf",
    "idSlug": "l13-rlm-comb-019-sequencias-logicas-padroes-progressao",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "671e06a6-a523-512a-a333-08f2542f694f",
    "banca_nome": "Cebraspe",
    "orgao_nome": "Polícia Federal",
    "cargo_nome": "Perito Criminal Federal",
    "ano": 2026,
    "tipo": "certo_errado",
    "dificuldade": "medio",
    "enunciado": "Considere a sequência lógica de códigos de investigação: 3, 7, 15, 31, 63, X. Seguindo o padrão de formação lógica em que cada termo subsequente é obtido pelo dobro do termo anterior somado a uma unidade (a_n = 2 * a_(n-1) + 1), o próximo termo X é corretamente igual a 127.",
    "explicacao": "GABARITO: CERTO. GABARITO: CERTO. Padrão: 3*2+1=7; 7*2+1=15; 15*2+1=31; 31*2+1=63; 63*2+1=127 (ou 2^(n+1) - 1).",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "118ce6ed3fb4e4c5065caf6751d98dfeead49604c0658afa27ec060c998c0e05",
    "conceito_principal": "Identificação de Padrões em Sequências Lógicas Numéricas",
    "habilidade_cobrada": "Deduzir a lei de formação recursiva de sequências numéricas",
    "tese_ou_regra": "A aplicação da regra recursiva a_n = 2*a_(n-1) + 1 sobre 63 resulta exatamente em 127",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "eaf893cc-cdfb-5aae-833d-27b50ba88349",
        "questao_id": "72668e5a-f800-53a2-90e7-65227b4dacbf",
        "letra": "C",
        "texto": "Certo",
        "correta": true,
        "ordem": 1,
        "explicacao_especifica": "Assertiva correta de acordo com a legislação e jurisprudência aplicável."
      },
      {
        "id": "594f714b-5e1b-5c20-ad1a-a01d4f953f74",
        "questao_id": "72668e5a-f800-53a2-90e7-65227b4dacbf",
        "letra": "E",
        "texto": "Errado",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Assertiva correta."
      }
    ]
  },
  {
    "id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
    "idSlug": "l13-rlm-comb-020-combinatoria-distribuicao-casos-investigados",
    "disciplina_id": "dac6313a-adfd-50ca-98a1-09fb195469ff",
    "assunto_id": "791c7278-7511-50df-bddf-600d9b818aaf",
    "banca_nome": "Vunesp",
    "orgao_nome": "Polícia Civil",
    "cargo_nome": "Investigador de Polícia",
    "ano": 2026,
    "tipo": "multipla_escolha",
    "dificuldade": "medio",
    "enunciado": "Um delegado precisa distribuir 5 inquéritos policiais distintos entre 5 escrivães de polícia, de modo que cada escrivão receba exatamente um inquérito. De quantas maneiras distintas essa distribuição pode ser realizada?",
    "explicacao": "GABARITO: D. Trata-se de uma bijeção/permutação simples de 5 elementos: P5 = 5! = 5 x 4 x 3 x 2 x 1 = 120 maneiras.",
    "prompt_versao": "v3.3-lote13",
    "is_autoral_ia": true,
    "modelo_ia": "Claude Fable 5.1",
    "revisada_por_especialista": false,
    "especialista_revisor_id": null,
    "anulada": false,
    "desatualizada": false,
    "motivo_desatualizacao": null,
    "versao": 1,
    "fingerprint": "4e858570629057abb623b4fdef762e59b1e0269570fedf74fabd77d19cd7b31d",
    "conceito_principal": "Permutação Simples de Atribuições Um-a-Um (5! = 120)",
    "habilidade_cobrada": "Modelar problemas de alocação biunívoca de tarefas como permutações simples",
    "tese_ou_regra": "A alocação de n itens distintos a n agentes sem repetição é calculada por n!",
    "nivel_cognitivo": "aplicar",
    "alternativas": [
      {
        "id": "c0d68865-19d5-56c3-9928-130bbf2bb88e",
        "questao_id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
        "letra": "A",
        "texto": "25 maneiras.",
        "correta": false,
        "ordem": 1,
        "explicacao_especifica": "Incorreta. Seria 5 x 5 (não considera redução de inquéritos)."
      },
      {
        "id": "abc9f862-542a-561d-9282-6f5403c30843",
        "questao_id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
        "letra": "B",
        "texto": "60 maneiras.",
        "correta": false,
        "ordem": 2,
        "explicacao_especifica": "Incorreta. Erro aritmético de divisão."
      },
      {
        "id": "c7a1ea7d-82b1-542a-aab1-b384aa0f4e04",
        "questao_id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
        "letra": "C",
        "texto": "3.125 maneiras.",
        "correta": false,
        "ordem": 3,
        "explicacao_especifica": "Incorreta. Seria 5^5 com repetição irrestrita."
      },
      {
        "id": "55740abe-161c-50da-84af-00c488279287",
        "questao_id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
        "letra": "D",
        "texto": "120 maneiras.",
        "correta": true,
        "ordem": 4,
        "explicacao_especifica": "Correta. 5! = 120 maneiras distintas de distribuição um a um."
      },
      {
        "id": "1e4d0508-9ee5-51f3-b25b-23ebdbb7d575",
        "questao_id": "7ca72aac-d30c-5e8d-b67d-0cdc0932cec5",
        "letra": "E",
        "texto": "15 maneiras.",
        "correta": false,
        "ordem": 5,
        "explicacao_especifica": "Incorreta. Seria combinação ou soma simples."
      }
    ]
  }
];
